### ISSUE TITLE
Importing scapy.arch.linux on other OS

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#100]
For the native BPF support, I need to call the function scapy.arch.linux.get_if() in Mac OS X (and other BSD derivatives). This function works fine on OS X, however the test at [Line 73](https://github.com/secdev/scapy/blob/master/scapy/arch/linux.py#L73) prevents the module from loading.

I can imagine several ways to fix this:
1. suppress this test as well as the one at  [line 120](https://github.com/secdev/scapy/blob/master/scapy/arch/linux.py#L120)
2. move this test to the Linux specific part of scapy/arch/__init__.py at [line 80](https://github.com/secdev/scapy/blob/master/scapy/arch/__init__.py#L80)
3. create scapy/arch/common.py and move get_if() into it

What solution should I implement ?

**Comment by p-l-** [comment]
I think `scapy.arch.linux` should not be imported from MacOS X code, so the best solution is probably to move it to `scapy.arch.common`.

There is something I don't understand: why is the tcpdump test failing?

**Comment by guedou** [comment]
`tcdump -V` starts a capture on OS X =)

**Comment by p-l-** [comment]
OK good to know!
