### ISSUE TITLE
Decode TaZmen Sniffer Protocol packets

### ISSUE THREAD

**Issue by moham96** [secdev/scapy#1000]
Hi,
Is it possible to add tzsp decoder to strip the encapsulation and get and parse the encapsulated layers?

**Comment by guedou** [comment]
Yes, you can implement it as a contribution and submit a pull request.

**Comment by speakinghedge** [comment]
:santa: :gift: :beer:

**Comment by moham96** [comment]
@speakinghedge Thank you very much for your work:)
I just have one question why does it work in python2 and not in python3?

**Comment by speakinghedge** [comment]
> Thank you very much for your work:)

Na. I have a strong affinity to that kind of protocol (out of my history)  - it was more or less a natural reflex. 

> I just have one question why does it work in python2 and not in python3?

What does not work? And plz check my latest commits (esp. 0d63eda) - I guess the way I prepared some dicts created some FUD.

**Comment by moham96** [comment]
@speakinghedge I used your latest commits and still the code works in python2 but not in python3, in python2 the packets gets decoded and new layers are created from the TZSP packets while it python3 the packets don't get decoded and they stay as raw UDP packet

**Comment by speakinghedge** [comment]
I'm busy right now - will be able to work on this now+6h.

can you provide some sample data (e.g. small pcap)?

**Comment by moham96** [comment]
@speakinghedge Sure, here is a small pcap from my mikrotik router 

[sample.pcap.zip](https://github.com/secdev/scapy/files/1591424/sample.pcap.zip)

**Comment by speakinghedge** [comment]
thanks for the sample. 
should be fixed with b3938ad - plz confirm.

**Comment by moham96** [comment]
@speakinghedge Yes, it works on python 3.6.3. Thanks

**Comment by speakinghedge** [comment]
@guedou can be closed - was merged / issue is solved.
