### ISSUE TITLE
[ci] Import error with Travis on osx

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1001]
Issue found will investigating and fixing #827  .

In this build https://travis-ci.org/secdev/scapy/jobs/320169025, it looks like Scapy is not configured correctly. The output of `python -c "from scapy.all import *; print conf"` is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/all.py", line 25, in <module>
    from scapy.route import *
  File "scapy/route.py", line 14, in <module>
    from scapy.arch import get_working_if
ImportError: cannot import name get_working_if
```

**Comment by avonar** [comment]
can you give more info? what system do you use? 
This commit was merged `abe5cc9`, so i tried to checkout and install scapy, i have ubuntu and i dont have your problem.

**Comment by guedou** [comment]
I wrote and merged the commit that your are referring =)

As the title states, it is an OS X issue related to Travis. I guess that it can be reproduced with
`SCAPY_USE_PCAPDNET=yes python -c "from scapy.all import *; print conf"`

**Comment by avonar** [comment]
```
 /m/d/g/scapy> export SCAPY_USE_PCAPDNET=yes
 /m/d/g/scapy> python -c "from scapy.all import *; print conf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "scapy/arch/__init__.py", line 54, in <module>
    from scapy.arch.pcapdnet import *
  File "scapy/arch/pcapdnet.py", line 350, in <module>
    import pcapy as pcap
ImportError: No module named pcapy
```
