### ISSUE TITLE
Finish the two basic IPv4 address checks in pton_ntop.py - #399

### ISSUE THREAD

**Issue by stryngs** [secdev/scapy#1026]
I'm opening this issue to help out with #399 

I will try to do my best with it. It seems like a pretty easy concept; verify the object can only be ipv4.  Tons of ways to do this; re would seem the proper path.

Thoughts?

**Comment by p-l-** [comment]
You probably don't want to use `re` here. The easiest way is probably to count (`len()`) the number of elements in `part`, then use `enumerate()` in the `for` statement and then you can check if you're processing the last part.

**Comment by guedou** [comment]
The goal is to accept formats from [RFC5156](https://tools.ietf.org/html/rfc5156):
- IPv4-Mapped Addresses: `::FFFF:0:0/96`
- IPv4-Compatible Addresses: `::<ipv4-address>/96`

That will be more than enough if you can implement it to get similar results as
`[socket.inet_pton(socket.AF_INET6, ip6) for ip6 in ["::1.2.3.4", "::ffff:1.2.3.4"]]`

Please don't forget to add unit tests.

**Comment by Noslenesilv** [comment]
been checking some stuff and you want the same result as  [socket.inet_pton(socket.AF_INET6, ip6) for ip6 in ["::1.2.3.4", "::ffff:1.2.3.4"]] but when inet_pton is called but that if:else statment is a workaround which will disappear ?!

**Comment by aebrow4** [comment]
Hello @guedou, I have submitted a PR for this: #1555
