### ISSUE TITLE
Improper condition for scapy/arch/indows/_init__.py/NetworkInterfaceDict.load_from_powershell()

### ISSUE THREAD

**Issue by karpierz** [secdev/scapy#1028]
Scapy Version: v2.3.3-1008
System: Windows10
Python Version: 2.7.14

File: scapy/arch/indows/\_\_init\_\_.py  Line:647

There is:
    if _detect[0] and not _detect[2] and (not hasattr(self, "restarted_adapter") or self.restarted_adapter):
I suppose that should be:
    if _detect[0] and not _detect[2] and (not hasattr(self, "restarted_adapter") or not self.restarted_adapter):

Thanks,
Adam Karpierz

**Comment by gpotter2** [comment]
Indeed ! Thanks a lot for reporting

**Comment by gpotter2** [comment]
Should be fixed in https://github.com/secdev/scapy/pull/1032
