### ISSUE TITLE
Problems while importing scapy on some environments (e.g. Eclipse, some peculiarly configured Windows boxes etc.) 

### ISSUE THREAD

**Issue by karpierz** [secdev/scapy#1029]
Scapy Version: v2.3.3-1008
System: Windows10
Python Version: 2.7.14

File: scapy/\_\_init\_\_.py

There are a problems of using master/scapy  on some environments  like e.g. Eclipse, some peculiarly configured Windows - mostly old - boxes etc.)
When scapy is started/imported and git is installed, some console windows appears while _version() is performed.
Also this issue has impact on decrease of scapy launch/import speed.

The reason is a wrong order of condition in scapy/\_\_init\_\_.py/def _version()
Currently reading from git has precedence over reading from the VERSION file.
It makes launching the git **even** when VERSION file already exists.
The solution is simply: reverting of condition order.

Patch below:
```
--- C:\AK\scapy-master\scapy\__init__.py	2017-11-09 12:48:00.127430400 +0100
+++ C:\AK\scapy-master-OK\scapy\__init__.py	2017-11-10 12:39:57.307207300 +0100
@@ -61,17 +61,17 @@
 def _version():
     version_file = os.path.join(_SCAPY_PKG_DIR, 'VERSION')
     try:
-        tag = _version_from_git_describe()
-        # successfully read the tag from git, write it in VERSION for
-        # installation and/or archive generation.
-        with open(version_file, 'w') as f:
-            f.write(tag)
+        with open(version_file, 'r') as f:
+            tag = f.read()
         return tag
     except:
-        # failed to read the tag from git, try to read it from a VERSION file
+        # failed to read the tag froma VERSION file, try to read it from git
         try:
-            with open(version_file, 'r') as f:
-                tag = f.read()
+            tag = _version_from_git_describe()
+            # successfully read the tag from git, write it in VERSION for
+            # installation and/or archive generation.
+            with open(version_file, 'w') as f:
+                f.write(tag)
             return tag
         except:
             # Rely on git archive "export-subst" git attribute.

```

Thanks,
Adam Karpierz

**Comment by karpierz** [comment]
`--- C:\AK\scapy-master\scapy\__init__.py	2017-11-09 12:48:00.127430400 +0100
+++ C:\AK\scapy-master-AK\scapy\__init__.py	2017-11-10 12:39:57.307207300 +0100
@@ -61,17 +61,17 @@
 def _version():
     version_file = os.path.join(_SCAPY_PKG_DIR, 'VERSION')
     try:
-        tag = _version_from_git_describe()
-        # successfully read the tag from git, write it in VERSION for
-        # installation and/or archive generation.
-        with open(version_file, 'w') as f:
-            f.write(tag)
+        with open(version_file, 'r') as f:
+            tag = f.read()
         return tag
     except:
-        # failed to read the tag from git, try to read it from a VERSION file
+        # failed to read the tag froma VERSION file, try to read it from git
         try:
-            with open(version_file, 'r') as f:
-                tag = f.read()
+            tag = _version_from_git_describe()
+            # successfully read the tag from git, write it in VERSION for
+            # installation and/or archive generation.
+            with open(version_file, 'w') as f:
+                f.write(tag)
             return tag
         except:
             # Rely on git archive "export-subst" git attribute.
`

**Comment by p-l-** [comment]
It is normal that reading the version from git has precedence over reading from the static file, since reading from git will actually write the static file. So if we applied your patch, we would have git create the VERSION file on the first run, and that file would never get updated.

The best solution if you think it slows down running or importing Scapy on your setup is to install Scapy and run it from where it is installed rather than from your local repository clone.

Please re-open if I misunderstood you or you disagree with this.

**Comment by karpierz** [comment]
I understand . I suppose that only one/first create of VERSION is a correct way.

My/our problem (unexpected lauching of git, git bash console window appearing) exist because of
condition in _version_from_git_describe() does not works as expected on my boxes (old Windows?, old buggy Python 2.7.8 where '/' path separator is not treated in the same way as '\\'? nevermind...)

Simple fix below fully avoids our problems:
```
diff --git a/scapy/__init__.py b/scapy/__init__.py
index 4893a9f..4f38578 100644
--- a/scapy/__init__.py
+++ b/scapy/__init__.py
@@ -38,7 +38,7 @@ def _version_from_git_describe():
         >>> _version_from_git_describe()
         '2.3.2.dev346'
     """
-    if not os.path.isdir(os.path.join(_SCAPY_PKG_DIR, '../.git')):
+    if not os.path.isdir(os.path.join(os.path.dirname(_SCAPY_PKG_DIR), '.git')):
         raise ValueError('not in scapy git repo')
 
     p = subprocess.Popen(['git', 'describe', '--always'], cwd=_SCAPY_PKG_DIR,
```

Thanks,
Adam Karpierz
