### ISSUE TITLE
Scapy 2.4.0

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1030]
A v2.4 [release candidate](https://github.com/secdev/scapy/releases) was tagged this morning. The goal is to make a v2.4.0 by the end of the month. In the meantime, other `rc` will be released depending on the reported issues.

**Comment by p-l-** [comment]
If you have issues or PR that you think should be reviewed before 2.4.0 is released, please comment here.

**Comment by karpierz** [comment]
For my/our purposes are worth and important:
[1028](https://github.com/secdev/scapy/issues/1028)
[1029](https://github.com/secdev/scapy/issues/1029)
PS: those fixes allows to avoid our local patched repo of master/scapy and use official release by the pip.
It will greatly simplify our scapy installation and maintenance.

Thanks,
Adam Karpierz

**Comment by guedou** [comment]
@karpierz could you make pull requests? Thanks.

**Comment by karpierz** [comment]
Hmm.. It is a  problem because I am not familiar with github at all :( Sorry.
I promise that I will stay "github expert" with ev. next more important/wider changes ;).
Could you please at this moment exceptionally include fixes from those issues "by hand"? 

Thanks,
Adam Karpierz

**Comment by p-l-** [comment]
We can now use the [Release 2.4](../projects/1) project to track this.

**Comment by karpierz** [comment]
..also [1035](https://github.com/secdev/scapy/issues/1035) is IMHO important and should be included in v.2.4

**Comment by p-l-** [comment]
I remove issues as they are added to the project.

**Comment by karpierz** [comment]
Please add also [#1039](https://github.com/secdev/scapy/issues/1039) - (updated #1029)

**Comment by gpotter2** [comment]
Hi !
I would have liked https://github.com/secdev/scapy/pull/917 to be added to 2.4.0.
Current NetflowV9 implementation is not working, and it would be ashame to get it packed in 2.4.0. Also fixes #916 and #1060.

**Comment by karpierz** [comment]
Trifle: [#1078](https://github.com/secdev/scapy/issues/1078)

**Comment by p-l-** [comment]
@gpotter2 implementing this properly would require a stateful implementation of `PacketList()`. I'm working on it but I'd rather do this after 2.4.0 release.

**Comment by gpotter2** [comment]
@p-l- I get it. But because 2.4.0 is going to be used way more than the dev version, in the meantime, it would be good to get something that works. We can implement the stateful `PacketList()` later (I'll be happy  to help with that).

At least #917 works, using `netflowv9_defragment`.

**Comment by karpierz** [comment]
[#1128](https://github.com/secdev/scapy/issues/1128)

**Comment by karpierz** [comment]
[#1129](https://github.com/secdev/scapy/issues/1129)

**Comment by karpierz** [comment]
#1139

**Comment by karpierz** [comment]
#1141

**Comment by karpierz** [comment]
#1146

**Comment by gpotter2** [comment]
My personal `2.4.0` list (will update/remove it when done). All my other PRs are low priority.
Broken stuff:
- https://github.com/secdev/scapy/pull/1162 (Windows 8 IPv6 = **Critical**)
- https://github.com/secdev/scapy/pull/917 (netflowv9)
- https://github.com/secdev/scapy/pull/1137 (route generators)
- https://github.com/secdev/scapy/pull/1104 (duplicated logs)
- https://github.com/secdev/scapy/pull/1088 (fix send module)
Very cool features I would like to have in 2.4.0:
- https://github.com/secdev/scapy/pull/1165 (monitor mode on windows: was nealy implemented with npcap addition)
- https://github.com/secdev/scapy/pull/1164 (fancier routes printing system)

**Comment by karpierz** [comment]
Hi,
What about/what I should do with:
[#1133](https://github.com/secdev/scapy/pull/1133)
[#1146](https://github.com/secdev/scapy/pull/1146)
[#1141](https://github.com/secdev/scapy/pull/1141)
PR/fixes to complete its for merge for the master?
Thanks,
Adam

**Comment by guedou** [comment]
@karpierz there are already assigned to the project https://github.com/secdev/scapy/projects/1

**Comment by karpierz** [comment]
@guedou assigned, but not merged quite a long time so it is inconvinient for us, because we aim (even forse:) to use only the public/official version (event if it is on dev. state as for now) of scapy in out users/cases.

Thanks,
Adam

**Comment by p-l-** [comment]
@karpierz we're doing our best... sorry for the delays, we too would like to be faster :)

**Comment by karpierz** [comment]
No problem. Thanks :)

**Comment by karpierz** [comment]
#1198 - a bug (for us even a blocker).

**Comment by guedou** [comment]
2.4.0 is supposed to be released really soon. How come this issue did not show up in the previous RC?

**Comment by karpierz** [comment]
Because in previous RC the "monitor" feature has not been  implemented at all.

**Comment by guedou** [comment]
Thanks for the clarification. I though that you did your tests with master, and was a bit worried that we missed something.

**Comment by karpierz** [comment]
Yes, but it was even worse. Previously working production code began to give errors :(.

**Comment by guedou** [comment]
Do you have other issues with current master ?

**Comment by karpierz** [comment]
Yes, but they are not blokers (maybe with one exception) so I don't want to give you extra work.
In this week I will spend a lot of time to finishing its and creating ev. PRs, but some of them will need discussion/investigation with you, so rather there will no strict requirements to include them in 2.4.x.

**Comment by guedou** [comment]
Thanks a lot! I really appreciate your efforts in making Scapy more stable.

**Comment by karpierz** [comment]
... and bugfix #1225

**Comment by karpierz** [comment]
...and (as I said earlier) not mandatory/not a blocker or even bugfix #1126, but.. why not ? ;)

**Comment by karpierz** [comment]
Thanks for acceptation! (especially for #1226;)

**Comment by gpotter2** [comment]
@karpierz Hi ! Could you delete all your posts in this issue that have been fixed please ? It's easier to see what's done or not

**Comment by karpierz** [comment]
One question. Is there any change to drop support for Python 3.3 ?
Py3.3 is very buggy and brings many problems - for us is important especially e.g unicode decoding/encoding probolems/bugs for some kinds of binary data and others like e.g. handles
inheritance by the subprocess (its cannot be fully protected even by the recent Gabriel's patch/hack) etc.
For instance most of packages on pypi already drops support for Python3 < 3.4

**Comment by guedou** [comment]
It will be removed as a side effect of #1160 =)

**Comment by karpierz** [comment]
Excellent ;) Thanks

**Comment by karpierz** [comment]
...and (probably last really important from my side) #1234

**Comment by karpierz** [comment]
...and (appears in the meantime) #1235

**Comment by karpierz** [comment]
...and bugfix #1237

**Comment by karpierz** [comment]
...and last #1240 (the same ares as #1226)

**Comment by karpierz** [comment]
Blocker #1256 (Disabling the snmpwalk test due to unknown but very often instabilities).

**Comment by guedou** [comment]
Scapy v2.4.0 will be released on March 21.

I selected the necessary PR under the TODO section in https://github.com/secdev/scapy/projects/1

**Comment by karpierz** [comment]
Don't forget about #1236.
It is really important for us and our customers.

**Comment by karpierz** [comment]
#1269

**Comment by karpierz** [comment]
Question:
What I should do with #1240 ?
Do I have to do a rebase or it is ok/enough?
PS: and what about regression fixed by #1253 ? Is it finally implemented/will certainly be included in 2.4.0final?

**Comment by guedou** [comment]
v2.4.0 will happen today. The 4 PR currently in TODO under the project will be merged. The other ones likely won't be.

#1240 and #1253 are both in the list =)

**Comment by karpierz** [comment]
Excellent!
So last request from my side "in this century" :)
Could you include in TODO also #1271?
Ok, the test for this fix is not ideal perfect/not quite completed for now, but will be useful
for us/my company/our customers because we will use (and already partially intensively use tls layer.
So It is very important for us to enter such (even little) fixes/improvements in the official scapy release.

**Comment by guedou** [comment]
This is only related to encrypting and decrypting, and never encounter any issue while sniffing traffic. Therefore, I don't think that it should be integrated into v2.4.0 as the PR is not ready.

**Comment by karpierz** [comment]
Please add to TODO #1275

**Comment by karpierz** [comment]
UPDATE:
PR #1269 is finished succesfully. Please include it in TODO.

All another errors in layers/tls/tools module has been fixed.
All code in this module has been ported to Python3.
Tests are added for all functions in this module.

PR is ready for merge to the master.

**Comment by karpierz** [comment]
Please include it in TODO: #1276

**Comment by karpierz** [comment]
> Scapy v2.4.0 will be released on March 21.

When do you plan to release (and publish on pypi) at least RC version of scapy that will contain all things from current TODO ?

**Comment by guedou** [comment]
@p-l- merged all of them except #1269 as I prefer renaming the fragment field.

v2.4.0 could happen next Monday.

**Comment by karpierz** [comment]
#1269 is fixed and is ready for merge to the master.

**Comment by karpierz** [comment]
#1285

**Comment by gpotter2** [comment]
I always find bugs at the last second, here are critical ones:
https://github.com/secdev/scapy/pull/1284 https://github.com/secdev/scapy/pull/1283
This one is quite important, as it's part of the Python 3 / Python 2 compatibility, and updates the notebooks
https://github.com/secdev/scapy/pull/1286

**Comment by karpierz** [comment]
#1288

**Comment by karpierz** [comment]
#1290 (Fix PY3 incompatibilities)

**Comment by guedou** [comment]
Let’s make v2.4.0 happen Tuesday!

Please add and check the necessary PR. I will have a look at them today. Everything not ready won’t make to v2.4.0.

**Comment by guedou** [comment]
Let's keep #1286#1292 for the next release!

Concerning #1291 and #1288 if @gpotter2 agrees with the changes I will merged them before v2.4.0. They are not critical for Scapy core features.

**Comment by karpierz** [comment]
About #1296. FYI Sorry but at the next release I will not be available :(. (of course a branch still will be exist).

**Comment by karpierz** [comment]
I fully agree to #keep both #1292 and #1286 for the next release.
So only #1228 has to be considered and merged.

**Comment by guedou** [comment]
I rather do v2.4.0 tomorrow, and have a look at #1288 and #1292 during the week as they are not critical.

**Comment by karpierz** [comment]
Excellent :)

**Comment by karpierz** [comment]
#1294 (critical when when we have different versions of python installed.)

**Comment by karpierz** [comment]
FYI about #1292.
Sorry but at the next release I will not be available :(. (of course a branch still will be exist
and will be available for merge).

I withdrew editing/cosmetic changes, which made the fix trivial and obvious.

**Comment by guedou** [comment]
@karpierz we decided to go for v2.4.0 right now (ae348f8611529fe20dcd703e2bd37f20322c4535).

**Comment by karpierz** [comment]
My request is only about #1294. It is really annoying for our users and makes real problems (another python is launched than expected). Sorry for delay of reporting it :(.

**Comment by guedou** [comment]
@karpierz  Don't worry we will merge it =) We had to release it to move forward. You made an amazing job at making this v2.4.0 release better. Thanks a lot !

**Comment by guedou** [comment]
I just tagged v2.4.0 and pushed it to pipy. 

We would like to thank all the contributors for their work on v2.4.0 !

**Comment by karpierz** [comment]
Uff.. Thanks a lot for merge #1294  :)
PS: Please imagine a hundreds of users that reports "me":
"Why Python3.X is launched (and scapy from it) when I directly use C:\Python27\Scripts\scapy" ?
Horrible ;)

**Comment by p-l-** [comment]
@karpierz I do not like this kind of comments. I'm sorry if you're upset, but we are all doing our best here. So please try to keep your sarcasm for yourself.

**Comment by karpierz** [comment]
My comment?. Sarkazm? It is not a sarcasm.
It was just an innocent joke from normal company's users word :).
I cannot believe that it could have been treated differently.

**Comment by karpierz** [comment]
But ok, Now I really "upset" (means I'm just sad).
It's time to go "rest" (especially since I have not slept a lot the last 3 nights).
Goodbye and thanks for cooperation and of course I thank you very much and I am very grateful for this version of the scapy.

**Comment by p-l-** [comment]
Sorry if that was a joke, and have a good night ;-)
