### ISSUE TITLE
WARNING: Error building scapy IPv4 routing table : invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by JeongJuhyeon** [secdev/scapy#1034]
OS: Windows 10 LTSB

Scapy version: Tried both Scapy 2.4rc2 and whatever the version is from /scapy/archive/master.zip, get the same error. 

When launching scapy, the warning "WARNING: Error building scapy IPv4 routing table : invalid literal for int() with base 10:" comes up. Also, using

`t=IP()`
`t.src`
gives
`WARNING: No route found (no default route?)
'0.0.0.0'`

**Comment by gpotter2** [comment]
Hi !
Could you please start a powershell, run
`Get-NetRoute -AddressFamily IPV4 | select ifIndex, DestinationPrefix, NextHop, RouteMetric, InterfaceMetric | fl`
and report the content ?
That would help us understanding the bug. Thanks a lot !!

**Comment by JeongJuhyeon** [comment]
Sure!
	ifIndex           : 5
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 18
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 23
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 13
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 3
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 11
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 4
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 1
	DestinationPrefix : 255.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 5
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 18
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 23
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 13
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 3
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 11
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 4
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 1
	DestinationPrefix : 224.0.0.0/4
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 18
	DestinationPrefix : 192.168.139.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 18
	DestinationPrefix : 192.168.139.1/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 18
	DestinationPrefix : 192.168.139.0/24
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 3
	DestinationPrefix : 192.168.103.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 3
	DestinationPrefix : 192.168.103.9/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 3
	DestinationPrefix : 192.168.103.0/24
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 5
	DestinationPrefix : 192.168.29.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 5
	DestinationPrefix : 192.168.29.1/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 5
	DestinationPrefix : 192.168.29.0/24
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 23
	DestinationPrefix : 169.254.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 23
	DestinationPrefix : 169.254.213.128/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 23
	DestinationPrefix : 169.254.0.0/16
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 1
	DestinationPrefix : 127.255.255.255/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 1
	DestinationPrefix : 127.0.0.1/32
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 1
	DestinationPrefix : 127.0.0.0/8
	NextHop           : 0.0.0.0
	RouteMetric       : 256
	InterfaceMetric   :

	ifIndex           : 3
	DestinationPrefix : 0.0.0.0/0
	NextHop           : 192.168.103.1
	RouteMetric       : 0
	InterfaceMetric   :

If it matters, ifIndex 3 is my Wi-Fi adapter and would be the one I'd like to use.

**Comment by gpotter2** [comment]
As you can see, you're not getting any data for `InterfaceMetric`. This means that you are using an old version of powershell, but still, scapy should not be failing.

**Comment by gpotter2** [comment]
Thanks a lot for reporting !
Should be fixed in https://github.com/secdev/scapy/pull/1037
You can try it with this zip:
https://codeload.github.com/gpotter2/scapy/zip/win-metrics-fix

**Comment by JeongJuhyeon** [comment]
With the new version, the warning has changed to

    WARNING: Error building scapy IPv4 routing table : 'NoneType' object has no attribute 'group'

And

    t = IP()
    t.src

still gives the same

    WARNING: No route found (no default route?)
    '0.0.0.0'

**Comment by gpotter2** [comment]
Working on it...
