### ISSUE TITLE
Scapy 2.4rcX on Windows does not work when PoweShell is off (or not found).

### ISSUE THREAD

**Issue by karpierz** [secdev/scapy#1035]
Scapy Version: 2.4rc2-9
System: Windows10
Python Version: 2.7.14

File: scapy/arch/windows/\_\_init\_\_.py

ImportError appears when scapy is used with disabled PoweShell (conf.prog.powershell is None or exe does not exist).
The reason is that _PowershellManager() constructor expects a real exe path in conf.prog.powershell var
but receives None.

Patch below:

```
diff --git a/scapy/arch/windows/__init__.py b/scapy/arch/windows/__init__.py
index 94a31bc..7e68065 100644
--- a/scapy/arch/windows/__init__.py
+++ b/scapy/arch/windows/__init__.py
@@ -735,7 +735,8 @@ class NetworkInterfaceDict(UserDict):
         return self.show(print_result=False)
 
 # Init POWERSHELL_PROCESS
-POWERSHELL_PROCESS = _PowershellManager()
+if conf.prog.powershell is not None:
+    POWERSHELL_PROCESS = _PowershellManager()
 
 IFACES = NetworkInterfaceDict()
 IFACES.load_from_powershell()
```
PS: I've checked an impact for other pieces of code and I'v noticed that the above change/patch has no impact for ev. regression except one place: _read_routes6_7() -> read_routes6() where I'v not found
dependence/condition  like 'if conf.prog.powershell in not None'.
I'v not checked a code deeply because I am not familiar with scapy deeper.. so.. I count on your forgiveness and help at this point/place :).

Thanks,
Adam Karpierz

**Comment by gpotter2** [comment]
Hi ! Should be fixed in #1036, thanks for reporting. On my machine it fixes the bug.

Could you try using https://codeload.github.com/gpotter2/scapy/zip/win-nops ?
Thanks a lot !
