### ISSUE TITLE
Problems while importing scapy on some environments (e.g. Eclipse, some peculiarly configured Windows boxes etc.) 

### ISSUE THREAD

**Issue by karpierz** [secdev/scapy#1039]
Scapy Version: v2.3.3-1008
System: Windows10
Python Version: 2.7.14

Updated (closed) issue: [#1029](https://github.com/secdev/scapy/issues/1029l)

File: scapy/\_\_init\_\_.py

There are a problems of using master/scapy  on some environments  like e.g. Eclipse, some peculiarly configured Windows - mostly old - boxes etc.)
When scapy is started/imported and git is installed, some console windows appears while _version() is performed.
Also this issue has impact on decrease of scapy launch/import speed.

Problem (unexpected lauching of git, git bash console window appearing) exist because of
condition in _version_from_git_describe() does not works as expected on my/our boxes (old Windows?, old buggy Python 2.7.8 where '/' path separator is not treated in the same way as '\\'? nevermind...)

Simple fix below fully avoids our problems:

```
diff --git a/scapy/__init__.py b/scapy/__init__.py
index 4893a9f..4f38578 100644
--- a/scapy/__init__.py
+++ b/scapy/__init__.py
@@ -38,7 +38,7 @@ def _version_from_git_describe():
         >>> _version_from_git_describe()
         '2.3.2.dev346'
     """
-    if not os.path.isdir(os.path.join(_SCAPY_PKG_DIR, '../.git')):
+    if not os.path.isdir(os.path.join(os.path.dirname(_SCAPY_PKG_DIR), '.git')):
         raise ValueError('not in scapy git repo')
 
     p = subprocess.Popen(['git', 'describe', '--always'], cwd=_SCAPY_PKG_DIR,
```

Thanks,
Adam Karpierz

**Comment by p-l-** [comment]
You're right. We should never use hard-coded `/` as path separator anyway. Thanks!
