### ISSUE TITLE
Native *BSD support

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#104]
I am making good progress to port the [BPF mode](http://scapy.ml.secdev.narkive.com/RnyJSzKj/bpf-mode) to Scapy 2

So far, it works fine on OS X 10.9.5 but I need to write better unit tests to ensure that the patch will also work on other *BSD flavors.

Here is the teasing:
```python
>>> sys.platform

'darwin'

>>> conf.L3socket

<L3bpfSocket: read/write packets using BPF>

>>> srp1(Ether()/IP(dst="8.8.8.8")/ICMP(), filter="host 8.8.8.8")

Begin emission:

..Finished to send 1 packets.

.*

Received 4 packets, got 1 answers, remaining 0 packets

<Ether  dst=b8:e8:56:45:8c:e6 src=3a:71:de:90:0b:64 type=0x800 |<IP  version=4L ihl=5L tos=0x0 len=28 id=0 flags= frag=0L ttl=41 proto=icmp chksum=0xcbbb src=8.8.8.8 dst=172.20.10.2 options=[] |<ICMP  type=echo-reply code=0 chksum=0xffff id=0x0 seq=0x0 |>>>
```

**Comment by p-l-** [comment]
Great!

**Comment by guedou** [comment]
The code is now available here: https://github.com/guedou/scapy-bpf

So far, only the IPv6 tests fails (but they also do with pcap/dnet).

**Comment by guedou** [comment]
The code is still under development.The current items must be checks before commiting to the main repository:
- [ ] write unit tests for functions in bpf.py and bsd.py
- [ ] test on FreeBSD
- [ ] test on OpenBSD
- [ ] test on NetBSD

**Comment by krytarowski** [comment]
Thank you for your NetBSD work.

**Comment by guedou** [comment]
@krytarowski Thanks for your support ! I have a special relation with NetBSD as I used it a lot few years ago =) I won't be able to test the code on something else than amd64. If you have access to other architectures, I will be pleased to fix the bugs (if any).

**Comment by krytarowski** [comment]
Lately I'm focused on amd64.

**Comment by guedou** [comment]
PR #221 includes this patch, and is waiting to be reviewed.
