### ISSUE TITLE
support rfc 4448 encapsulating Ethernet frame in MPLS

### ISSUE THREAD

**Issue by haozheng10** [secdev/scapy#1044]
I have a patch I'd like to submit for review, which adds support for 4448 encapsulating Ethernet frame in MPLS with optional control word.
Please let me know how to proceed.

Thanks,

Hao

**Comment by p-l-** [comment]
Hi,

Thanks! Just create a pull-request and submit it for review.

**Comment by haozheng10** [comment]
it seems that I don't have the permission to fork the repo.  Can you give me the permission?

**Comment by p-l-** [comment]
You don't need a permission to fork this repository.
