### ISSUE TITLE
Fix incorrect str() calls

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1049]
Some calls to `str()` look incorrect (see for example `git grep ' str(' scapy/layers/tls/`). We might want to fix that before releasing v2.4.0.

**Comment by gpotter2** [comment]
Actually TLS module is currently broken (automaton tests are disabled)

We need to work this out before releasing scapy

**Comment by p-l-** [comment]
Should be OK now. Please reopen if needed.
