### ISSUE TITLE
traceroute6(): wrong order with Python

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1052]
With Python3, routers addresses are displayed in the wrong order (likely an alphabetic one):

In [66]: traceroute6("www.free.fr", minttl=8, maxttl=12)
Begin emission:
............Finished to send 5 packets.
***.*.....
Received 22 packets, got 4 answers, remaining 1 packets
   2a01:0e0c:0001:0000:0000:0000:0000:0001   :tcphttp 
10 2001:7f8:1::a501:2322:1                    3       
11 2a01:e04:3::5                              3       
8  ::ffff:194.79.137.174                      3       
9  2001:7f8:1::a501:3193:1                    3

**Comment by p-l-** [comment]
I'll have a look, same for IPv4 traceroute results actually.

**Comment by p-l-** [comment]
PR on its way, I'm writing a test.

**Comment by guedou** [comment]
Wow! I guess that the fastest patch of a bug discovered during an IPv6 workshop with Scapy =)
