### ISSUE TITLE
Travis CI tests are extremly slow

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1056]
They sometimes take 1-2 days to complete...
We may want to remove some of the OSX builds, which are very very slow to start

**Comment by guedou** [comment]
@p-l- pointed out that there is a huge macOS build backlog due to issues earlier this week. It seems to be recovering but we might suffer from it during few more days: https://www.traviscistatus.com/

In the mean time, we decided to exceptionally merge PR with macOS tests that did not finish.
