### ISSUE TITLE
Cannot decode the flows of NetflowV9 in scapy

### ISSUE THREAD

**Issue by vasiqmz** [secdev/scapy#1060]
I'm using scapy to iterated through the Netflow packets and extract the content from the flows in each packets.
I wrote the following code in scapy but I'm unable to get the flows, it shows the data in RAW format.

`
n1 = NetflowHeader(packt[0][UDP].payload)
Gives the below output

<NetflowHeaderV9  count=10 sysUptime=613895520 unixSecs=Thu, 19 Oct 2017 10:46:45 +0000 (1508410005) packageSequence=1079 SourceID=8 |<NetflowFlowsetV9  flowSetID=424 length=604 templates=[<NetflowTemplateV9  templateID=5120 fieldCount=445 template_fields=[<Raw  load="\x1e\x00\x01\xbd\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Z\x7fY\x00\x00\x1e\x08$\x95x\xd3$\x97M'\ndg\x01  \x00\x04\x14\x00\x03\x90\x1e\x00\x03\x90\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00W\xc9`\x00\x00\x1d+$\x95x\xd3$\x97M-\ndg\x01  \x00\x04\x14\x00\x03\xbc\x1e\x00\x03\xbc\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00YQ\x8a\x00\x00\x1dl$\x95x\xd7$\x97MB\ndg\x01  \x00\x04\x14\x00\x02\xbd\x1e\x00\x02\xbd\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Y\xe6\xdc\x00\x00\x1d\x9e$\x95x\xe3$\x97M7\ndg\x01  \x00\x04\x14\x00\x02m\x1e\x00\x02m\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Yb\x0c\x00\x00\x1d\xc3$\x95x\xdc$\x97MI\ndg\x01  \x00\x04\x14\x00\x02\x85\x1e\x00\x02\x85\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Y\xfe\x15\x00\x00\x1d\xb2$\x95x\xd2$\x97MH\ndg\x01  \x00\x04\x14\x00\x032\x1e\x00\x032\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Y\xd1\xc6\x00\x00\x1d\x9a$\x95x\xd3$\x97MP\ndg\x01  \x00\x04\x14\x00\x00^\x1e\x00\x00^\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Z\x1d\xf4\x00\x00\x1e\x1c$\x95x\xd1$\x97MQ\ndg\x01  \x00\x04\x14\x00\x02\xe2\x1e\x00\x02\xe2\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Y\xcf\x96\x00\x00\x1d\xfd$\x95x\xd6$\x97MO\ndg\x01  \x00\x04\x14\x00\x00E\x1e\x00\x00E\x00\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x03 \x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x02\xfb\x00Z\x8bs\x00\x00\x1d\xde$\x95x\xde$\x97MO\ndg\x01  \x00\x04" |>] |>] |<NetflowDataflowsetV9  templateID=22514 length=51698 |>>>
`

As you can see the data is not getting decoded I even tried using NetflowDataflowsetV9 but still it's not decoding the data.

**Comment by gpotter2** [comment]
Hi !
Netflowv9 format is currently not working on the master branch.
I’ve made a PR to fix it https://github.com/secdev/scapy/pull/917 but as we are working on Python 3 support, this is low priority.

You can use the code provided in this PR to decode Netflowv9.
The process is then the following:
- capture packets/load them from a pcap
- call `netflowv9_defragment(plist)`

This is required because NetflowV9 is using separated packets to store the headers.

However, this implementation might change in the future (this is only the first stage of a PR), so the API might change in a near future.

It will work for now :)

Have a good day

**Comment by vasiqmz** [comment]
Thank you for the reply, Here's what I did since your PR wasn't in the Master merge as you said. I downloaded your netflow.py file and used it to run the code.

But it doesn't work in my case, I'm having Netflow packets with the template ID of 256
The code crashes with an exception in
`if len(current_ftl.records) < 0 or (not hasattr(current_ftl.records[0], "fieldValue")):`

I'll debug the code to see why it crashed, in the mean time, any suggestions ?

**Comment by gpotter2** [comment]
Hi !

Could you provide a pcap file (in a zip so github can can handle it) ?

I could then try to debug that to see what’s going on

Thanks !

**Comment by vasiqmz** [comment]
Hi !

Sorry for the late reply. 
It turns out, the code has no issues the PCAP, I believe was corrupted.
As I tried the code on a new PCAP and it works fine.

Thank you,
Vasiqullah

**Comment by vasiqmz** [comment]
Hi !
The decode works fine except for few fields, it doesn't decode the value, instead it gives the binary values back ...
Do I need to make another function call to decode the rest of the fields. Like if you see the output below after calling `netflowv9_defragment`

                  |###[ Netflow DataFlowset Record V9 ]###
                  |  LAST_SWITCHED= b'X\x19\xbb\xb4'
                  |  FIRST_SWITCHED= b'X\x18\xbd\xb4'
                  |  IN_BYTES  = b'\x00\x00\x0c\xa2'
                  |  IN_PKTS   = b'\x00\x00\x00*'
                  |  INPUT_SNMP= b'\x00\xdd'
                  |  OUTPUT_SNMP= b'\x00\xe5'
                  |  IPV4_SRC_ADDR= 192.168.10.2
                  |  IPV4_DST_ADDR= 192.34.55.44
                  |  PROTOCOL  = b'\x06'
                  |  TOS       = b'\x00'
                  |  L4_SRC_PORT= b'\x02\x02'
                  |  L4_DST_PORT= b'M\xcc'
                  |  IPV4_NEXT_HOP= 192.23.44.21
                  |  DST_MASK  = b'\x1b'
                  |  SRC_MASK  = b'\x00'
                  |  TCP_FLAGS = b'\x00'

Any idea ?

**Comment by gpotter2** [comment]
Hi !
I've updated https://github.com/secdev/scapy/pull/917 to decode more fields.

A very few won't be decoded, because their size are un-predictable, and will be returned as bytes. If those fields are the one you wanted to use, please tell me and I'll try to make them beeing decoded as well.

Thanks a lot for submitting !

**Comment by vasiqmz** [comment]
Hi !
Did you modify the `netflow.py` and `fields.py` because I used your updated code and I still see the data returned in bytes, just like the last one.
Did i miss something?

**Comment by gpotter2** [comment]
With the latest version of the branch, i get stuff like
```
                  |###[ Netflow DataFlowset Record V9 ]###
                  |  IPV4_SRC_ADDR= 20.0.0.7
                  |  IPV4_DST_ADDR= 30.0.0.7
                  |  TOS= 0x0
                  |  PROTOCOL= 253
                  |  L4_SRC_PORT= 0
                  |  L4_DST_PORT= 0
                  |  ICMP_TYPE= 0x0
                  |  INPUT_SNMP= b'\x00\x00\x03 '
                  |  SRC_AS= 1
                  |  DST_AS= 1
                  |  BGP_IPV4_NEXT_HOP= 0.0.0.0
                  |  OUTPUT_SNMP= b'\x00\x00\x02\xfb'
                  |  IN_BYTES= b'\x00Zk\xc0'
                  |  IN_PKTS= b'\x00\x00\x1e\n'
                  |  FIRST_SWITCHED= 613775.619 sec
                  |  LAST_SWITCHED= 613895.565 sec
                  |  IPV4_NEXT_HOP= 10.100.103.1
                  |  SRC_MASK= 32
                  |  DST_MASK= 32
                  |  TCP_FLAGS= 0
                  |  IP_PROTOCOL_VERSION= 4
```
You can try after having installed this version of scapy: https://github.com/gpotter2/scapy/archive/fix-netflowv9.zip

**Comment by dijey099** [comment]
@gpotter2 I need your help please! 🙏🏽
if I have a Packet received from a python-socket as follow:
`sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(("0.0.0.0", 2055))
payload, routeur = sock.recvfrom(1464)`

I can have Netflow header with scapy as follow:
`netflowHeader = NetflowHeader(payload)`

and get output by calling:
`netflowHeader .show()`

Output:
`###[ Netflow Header ]###
  version   = 9
###[ Netflow Header V9 ]###
     count     = 25
     sysUptime = 407638356
     unixSecs  = Thu, 24 Nov 2022 10:01:45 +0300 (1669284105)
     packageSequence= 293857
     SourceID  = 0
###[ Netflow DataFlowSet V9/10 ]###
        templateID= 258
        length    = 708
        \records   \
         |###[ Netflow DataFlowset Record V9/10 ]###
         |  fieldValue= "\\xd0C\\xdc\\xdc\\xc0\\xa8\\xad\\xea\x00\x00\x00\x00\x005\\xe5z\x00\
###[ Netflow DataFlowSet V9/10 ]###
           templateID= 260
           length    = 48
           \records   \
            |###[ Netflow DataFlowset Record V9/10 ]###
            |  fieldValue= '\\x8e\\xfa\\xc9\n\\xc0\\xa8\\xae\'\x00\x00\x00\x00\x01\\xbb\\xea"\x18\x001\x00\x1e\x00\x00\x00\x03\x00\x00\x00\\xf4\x18K\\xd5\\xcc\x18Kִ\x06(\x08\x00\\xff\x00\x00'
###[ Netflow DataFlowSet V9/10 ]###
              templateID= 259
              length    = 120
              \records   \
               |###[ Netflow DataFlowset Record V9/10 ]###
               |  fieldValue= '\\xc0\\xa8\\xb0h\\x97e\x01\\x8c\\x9ax\\x86\\x81\\xe9b\x01\\xbb`

Can you please show me how to decode le "fieldValue" in "Netflow DataFlowset Record V9/10" ? 🙏🏽
**I really need to reed value in each flow (like in Wireshark)**
