### ISSUE TITLE
FlagsField flag test expression

### ISSUE THREAD

**Issue by antoniovazquezblanco** [secdev/scapy#107]
I'm working with scapy and I'm interested in enhancing RadioTap packet parsing. In order to do that I feel it is important and convenient to improve FlagsField in order to provide an efficient way of testing if a particular flag is present. I don't know if this is a wanted feature, and in case it is, I'm not sure what's the most efficient way to do it as I'm not yet as familiar with the structure of the project as I would like to.

Any hints?

Thank you very much.

**Comment by p-l-** [comment]
Hi,

This is a very complex, and interesting, question. Yes it would be a great feature to have something like `TCP().flags.S == True`, and maybe `x = TCP(); x.flags.S = 0`.

However, I'm not sure yet what is the best way to do that, and I will need some time to think about it. I have started to write an implementation, but there's still quite a lot of work ahead, I'll update this issue as soon as I have more to share.

**Comment by antoniovazquezblanco** [comment]
Thank you very much! ;)
