### ISSUE TITLE
Activate Python 3 / OSX builds in Travis

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1071]
We must perform Python3 builds in Travis before releasing v2.4.0. Issue #1015 could have been catch with these tests.

It seems that we need to install Python3 ourselves.  The corresponding PR must also fix #967

**Comment by guedou** [comment]
The backlog is still quite big: ˜2000 jobs in the queue. I will work on the fix when it will ne slower.

**Comment by guedou** [comment]
Testing Python3 without fixing the version can be done with `homebrew`. If we want to install a specific version, the best approach is to use `pyenv`. Both ways will require tests.

**Comment by p-l-** [comment]
Fixed by #1106.
