### ISSUE TITLE
Beacon Frame Timestamp Not Showing in PCAP

### ISSUE THREAD

**Issue by InvictusParadox** [secdev/scapy#1073]
When sniffing Beacons (Dot11Beacon) generated by scapy using Wireshark, or any other wireless packet capture tool, the timestamp (In Wireshark, IEEE 802.11 wireless LAN -> Fixed Parameters -> Timestamp) is all zeros or empty. In my Python, I do have, for example, `Dot11Beacon(cap='ESS+privacy', timestamp=time.time())` No matter what I put in the timestamp field, whether a static or dynamic value (like in the example shown), the sniffed packets from scapy do not have a timestamp.

The type of Wi-Fi card I am using, AWUS052NHS, does support packet injection. I have tried other Alfa cards (when transmitting and sniffing) and I get the same results. I am able to see the timestamp field with a value from other nearby access points.

I am able to see all other values from the Beacon that are supposed to be there.

![timestamp](https://user-images.githubusercontent.com/35581539/35125671-209f8122-fc70-11e7-90cc-0b8b3fc476f8.PNG)

**Comment by guedou** [comment]
Can you share the whole Scapy packet that your are injecting as well as the corresponding pcap ?

**Comment by InvictusParadox** [comment]
Attached is a zip file with the python script and the pcap file. Thanks!

[Beacon.zip](https://github.com/secdev/scapy/files/1649540/Beacon.zip)

Here's a link to just download the PCAP.
[PCAP](https://drive.google.com/open?id=1NmbyEh2itdHjsMz8h2QtxQqHb_LcvGcV)

In case you don't want to open the zip file, here is the Python code I am using.

`from scapy.all import *
import string
import random
import os
import decimal
from time import time

iface = 'wlan2mon'
channel = 8
os.system("iwconfig " + iface + " channel " + str(channel))
SeqNum = random.randint(14,4000) * 16

boottime = time()

while True:

	for i in range(0,200):
		netSSID = 'SSID' + str(i)
		add1 = 'ff:ff:ff:ff:ff:ff'
		add2 = '44:48:c1:%02x:%02x:%02x' % (random.randint(0,255),random.randint(0,255),random.randint(0,255))
		dot11 = Dot11(type=0, subtype=8, addr1=add1, addr2=add2, addr3=add2, SC=SeqNum)
		beacon = Dot11Beacon(cap='ESS+privacy', beacon_interval=0x0190)
		essid = Dot11Elt(ID='SSID',info=netSSID, len=len(netSSID))
		rates = Dot11Elt(ID="Rates", info="\x82\x84\x0c\x12\x18\x24\x30\x48\x60\x6c")
		dsset = Dot11Elt(ID="DSset", info=chr(channel))
		rsn = Dot11Elt(ID='RSNinfo', info=(
		'\x01\x00'
		'\x00\x0f\xac\x04'
		'\x02\x00'
		'\x00\x0f\xac\x04'
		'\x00\x0f\xac\x02'
		'\x01\x00'
		'\x00\x0f\xac\x02'
		'\x0c\x00'))

		frame = RadioTap()/dot11/beacon/essid/rates/dsset/rsn

		d = time() - boottime
		s = '{0:f}'.format(d)
		s = s.replace(".","")
		ts = int(s)
		frame[Dot11Beacon].timestamp = ts
		for z in range(0,1):
			sendp(frame, iface=iface, verbose=True)
		if SeqNum == 65504:
			SeqNum = random.randint(14,4000) * 16
		else:
			SeqNum += 16
`

**Comment by guedou** [comment]
Could you provide a minimal example that trigger your issue (aka a Scapy one liner)? Thanks.

**Comment by InvictusParadox** [comment]
Here is a good one liner that also replicates the issue:

`sendp(RadioTap()/
          Dot11(addr1="ff:ff:ff:ff:ff:ff",
                addr2="44:48:c1:d1:e1:f1",/
          Dot11Beacon(cap="ESS", timestamp=100)/
          Dot11Elt(ID="SSID", info='SSID100')/
          iface="wlan2mon", loop=1)`

Here is a minimal Python script as well:

`from scapy.all import *
add1 = 'ff:ff:ff:ff:ff:ff'
add2 = '44:48:c1:d1:e1:f1'
dot11 = Dot11(type=0, subtype=8, addr1=add1, addr2=add2, addr3=add2)
beacon = Dot11Beacon(timestamp=100)
essid = Dot11Elt(ID='SSID',info='SSID100')
frame = RadioTap()/dot11/beacon/essid
sendp(frame, iface='wlan2mon')`

**Comment by guedou** [comment]
The built frame looks ok:
```
>>> p = Dot11(addr1="ff:ff:ff:ff:ff:ff", addr2="44:48:c1:d1:e1:f1")/Dot11Beacon(cap="ESS", timestamp=100)/Dot11Elt(ID="SSID", info='SSID100')
>>> Dot11(raw(p))[Dot11Beacon]
<Dot11Beacon  timestamp=100 beacon_interval=100 cap=ESS |<Dot11Elt  ID=SSID len=7 info='SSID100' |>>
```

**Comment by InvictusParadox** [comment]
I agree, but the actual transmitted packet (or received) packet does not contain the timestamp information. Try it yourself. Have one interface transmit while another interface (on another machine or the same machine) sniffs the packet. You should see a zeroed out timestamp.

**Comment by guedou** [comment]
This shows that Scapy generates the correct frame and that it could be an issue with your setup, that I cannot use myself.

You can for example write the frame to a PCAP, replay it with airplay-ng, then check the timestamp value.

**Comment by InvictusParadox** [comment]
I found the issue. For what it's worth, this may help some others out too.

It appears that the rt2800usb driver that Linux uses for the Alfa (and probably most other) Wi-Fi cards removes, zeroes out, etc the timestamp value when transmitted. I don't know why/how it does that. This was tested on a Ubuntu 17.10, Ubuntu 16.04, and Kali 2017.3 system.

I was able to use the on-board Wi-Fi on a Raspberry Pi Zero W, which uses a Broadcom driver that supports monitor mode and packet injection, with Kali Linux installed to successfully transmit a beacon frame with a timestamp value. (Woohooo!!)

If you have any suggestions, while not relevant to Scapy, on how to fix the driver issues, please let me know.

Thank you for your help!

**Comment by guedou** [comment]
Thanks for this report. You could add a note in Scapy documentation. That will be really useful.
