### ISSUE TITLE
.coveragerc ignored

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1076]
Since we migrated the tests to Python 3, `.coveragerc` is ignored. This explains why the coverage has lowered.
I guess it's because we don't start codecov from the same folder than before.

PS: `.coveragerc` needs to be fixed: a tab is used instead of 4 spaces

**Comment by guedou** [comment]
I noticed it too while looking at codecov. We will see how #1077 goes.

**Comment by guedou** [comment]
We need to investigate this one.
