### ISSUE TITLE
[IPv6] Unit tests regression on Linux 4.14

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1099]
On Linux 4.14, Scapy `conf.route6` does not return the same result. This impacts the selected source IPv6 address:

```
>>> IPv6(dst="fe80::3871:deff:fe09:e555").show2()
###[ IPv6 ]### 
  version= 6
  tc= 0
  fl= 0
  plen= 0
  nh= No Next Header
  hlim= 64
  src= fe80::3871:deff:fe09:e555 <-- with 4.12 and below, src is set to ::1
  dst= fe80::3871:deff:fe09:e555
```

I will some time to understand which behaviour is preferred / correct.

**Comment by gpotter2** [comment]
On Windows, you'll have this when the loopback interface is not available/enabled
```
>>> IPv6().show2()
###[ IPv6 ]###
  version= 6
  tc= 0
  fl= 0
  plen= 0
  nh= No Next Header
  hlim= 64
  src= 2a01:e35:2f17:fe60:7120:6558:9886:fa88
  dst= ::1
```
But that's expected as `::1` is simply not available.

I would say that `src` should be set to `::1` if a loopback interface matching this IP is available

**Comment by guedou** [comment]
Everything works as expected...
