### ISSUE TITLE
Support pypy3?

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1107]
Shall we also support pypy3 in our builds?

**Comment by p-l-** [comment]
I don't know. Anyway, I don't think it should block the 2.4.0 release.

**Comment by johnthagen** [comment]
FYI, [at least as of last month PyPy3 support on Windows is "beta"](https://morepypy.blogspot.com/2018/01/pypy-5101-bugfix-release-for-python-35.html), in case that affects how you CI PyPy3.

**Comment by p-l-** [comment]
@johnthagen thanks, that's good to know but for now we do not test Pypy w/ Windows.
