### ISSUE TITLE
isn't the document update?

### ISSUE THREAD

**Issue by senaps** [secdev/scapy#1108]
hi, im a beginner in the whole network programming, but usually am able to search and ask.
but, problems here are somehow fundamental. i installed scapy and tried the `raw(IP())` thing and it threw an error!
had to read the code to find out that it may have changed to `Raw()` and even that, throws a not handled error at me.
i imported the code in python script to use `smb` layer thing, and it's not working as i wished it to work, and i there is no way i could find out how to make that work.(i wanted to use `twisted` to send/recive).

i wanted to create a new protocol based on the example smb with it being the way i want it to be, and it's generating the data that i want, but when sent on the line,  well, it didn't work.

__i did fall in Love with scapy, i have no idea where i would use it but really like to use it. but there is no **good** source for me to learn it.__

so, where would one, completely new to this stuff start's learning? where is an active community residing now that i can ask questions? `IRC` is empty and no one responds after a week of trying.

**Comment by guedou** [comment]
Please don’t harass us! 

I replied yesterday on IRC and told you to first try without using twisted. You said that you did not do it...

Also, we cannot help without any piece of code.

**Comment by senaps** [comment]
huh, i said i love the thing! :) sorry that i wrote as if there is something wrong with scapy!
i didn't know how to do run it without twisted. i will come back with some code and hope to see you again on irc.


but, for real, is there a problem with the documents or i have a bad installation?

**Comment by p-l-** [comment]
Please open one issue for each error or question. Also report your **exact** error messages, together with the version of Scapy you are using ("it threw an error!" does **not** help us).
