### ISSUE TITLE
"Generating sets of packets" (as explained in the documentation) does not work for mixed sequence and range (e.g. IP(ttl=[1,2,(5,9)]))

### ISSUE THREAD

**Issue by qupfer** [secdev/scapy#1118]
Hi,
as explained in the [tutorial](http://scapy.readthedocs.io/en/latest/usage.html#generating-sets-of-packets)  
these two lines 
`b=IP(ttl=[1,2,(5,9)])`
`[p for p in b]` 
should create a set of 7 packets, like
`[<IP ttl=1 |>, <IP ttl=2 |>, <IP ttl=5 |>, <IP ttl=6 |>, <IP ttl=7 |>, <IP ttl=8 |>, <IP ttl=9 |>]`.

But the result is just:
`[<IP  ttl=1 |>, <IP  ttl=2 |>, <IP  ttl=(5, 9) |>]`

If I just use a "sequence" (`IP(ttl=[1,2,5,7,9])`) or "range" (`IP(ttl=(1,9)`), the result is that I expected. 

So, there are recent changesin scpay and the documentation is outdated or Is this a bug or I'm just stupid ;) ?

Thanks!

**Comment by gpotter2** [comment]
Good catch !
Should be fixed in https://github.com/secdev/scapy/pull/1121

**Comment by guedou** [comment]
Here is the commit that introduces this regression:

```
$ python test.py
[<IP  ttl=1 |>, <IP  ttl=2 |>, <IP  ttl=5 |>, <IP  ttl=6 |>, <IP  ttl=7 |>, <IP  ttl=8 |>, <IP  ttl=9 |>]
7
$ git bisect good
4dbc2b99d385f82049f2c6716357a94e51be5f79 is the first bad commit
commit 4dbc2b99d385f82049f2c6716357a94e51be5f79
Author: Pierre LALET <pierre.lalet@cea.fr>
Date:   Thu Jan 21 12:49:13 2016 +0100

    Use xrange objects to (internally) represent tuples in field values

:040000 040000 37909dc2daf7daa0a27076f69e75a8c64f328d06 f03375175c5442a19535b7392053180f0fe9c935 M	scapy
```

@p-l- can you have a look ?
