### ISSUE TITLE
scapy config using obsolete utilities

### ISSUE THREAD

**Issue by xambroz** [secdev/scapy#1120]
Hello,
the scapy/config.py is using (on Linux) quite obsolete tools to display PDF and PostScript.
PDF - acroread is not supported on Linux anymore since 2013 
PS - gv - ghostview was not having even minor release since 2013 with very old-style X11 user interface

What about using the xdg-open ... which will then use the system preferences to use the default application configured for that file type? This way the users can configure within their desktop environment on what applications to use.

This is the patch used in Fedora:
https://src.fedoraproject.org/rpms/scapy/blob/master/f/scapy-2.2.0-xdg-open.patch

```
# HG changeset patch
# User Lubomir Rintel <lkundrak@v3.sk>
# Date 1411237938 -7200
# Node ID 0ce553161b799e9dc91f63de73dfdb0f50360056
# Parent  ac04713bb61839a3476b72118e3d1c3ce5c81e86
Do not default to acroread and gv

They are not very likely to be present nowadays. Default to user's preferred
application instead.

diff --git a/scapy/config.py b/scapy/config.py
--- a/scapy/config.py
+++ b/scapy/config.py
@@ -56,8 +56,8 @@
 
     
 class ProgPath(ConfClass):
-    pdfreader = "acroread"
-    psreader = "gv"
+    pdfreader = "xdg-open"
+    psreader = "xdg-open"
     dot = "dot"
     display = "display"
     tcpdump = "tcpdump"
```

**Comment by gpotter2** [comment]
Hi, and thanks for reporting !
This fix sounds very fair, and I've implemented it in https://github.com/secdev/scapy/pull/1122

**Comment by xambroz** [comment]
Hello gpotter2,
using evince instead of the acroread is slightly better, from the current support point of view.
But from user perspective on linux hard-coding the evince is wrong idea - same way as it is wrong to hardcode acroread.
I believe using the xdf-open is much better option for users as they can decide (and/or actually use their existing settings). It is part of the Free Desktop https://www.freedesktop.org/wiki/Software/xdg-utils/. It allows each user to use for opening the PDF files the tool which he decided that should be their default tool for PDF (yes in many cases it is evince).

It will work with Gnome, with KDE, LXDE, XFCE, openbox and probably some others.

Please re-consider your decision.

Michal Ambroz

**Comment by guedou** [comment]
See #1255
