### ISSUE TITLE
Sniff() doesn't capture the whole data from Raw Packet on fly

### ISSUE THREAD

**Issue by maximMole** [secdev/scapy#1124]
I am trying to capture data from Raw packet on fly:
`>>> sniff(iface="wlan0", filter="tcp", prn=function)`
`def function(pkt):
    ...`
I am trying to get unencrypted packets from a specific website. But it doesn't show me the complete Data from Raw packet and skip the last part of it. i.e. the arguments specified by the POST request while submitting the web form.

**Comment by guedou** [comment]
Could you report your Scapy and OS version ?
 Also, can you try on a wired network ? That could help us identify the cause of the issue.

**Comment by gpotter2** [comment]
Are you sure your packets are not fragmented ?

**Comment by guedou** [comment]
Closed due to no reply from the author.
