### ISSUE TITLE
Traceroute test on Python 3.4

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1130]
On several builds I had, this test seems to be failing a lot
```
###(486)=[failed] show()
>>> def test_show():
...     with ContextManagerCaptureOutput() as cmco:
...         tr6 = TracerouteResult6(tr6_packets)
...         tr6.show()
...         result = cmco.get_output()
...     expected = "  2001:db8::1                               :udpdomain \n"
...     expected += "1  2001:db8::1                                3         \n"
...     expected += "2  2001:db8::2                                3         \n"
...     expected += "3  2001:db8::3                                3         \n"
...     expected += "4  2001:db8::4                                3         \n"
...     expected += "5  2001:db8::5                                3         \n"
...     expected += "6  2001:db8::6                                3         \n"
...     expected += "7  2001:db8::7                                3         \n"
...     expected += "8  2001:db8::8                                3         \n"
...     expected += "9  2001:db8::9                                3         \n"
...     expected += "10 2001:db8::10                               3         \n"
...     expected += "11 2001:db8::11                               3         \n"
...     index_result = result.index("\n1")
...     index_expected = expected.index("\n1")
...     assert(result[index_result:] == expected[index_expected:])
... 
>>> test_show()
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "<input>", line 21, in test_show
AssertionError
```

e.g. https://travis-ci.org/secdev/scapy/jobs/337700526

**Comment by p-l-** [comment]
That's the same problem I've had before in different tests. Sometimes, the `/etc/services`-based resolver does not work, and that produces `:53` instead of `:udpdomain`.

**Comment by gpotter2** [comment]
Right, it seems that it's a travis failure

e.g. from https://travis-ci.org/secdev/scapy/jobs/337700526

> removed ‘/etc/apt/sources.list.d/basho_riak.list’
> W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release: The following signatures were invalid: KEYEXPIRED 1515625755
> W: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 Release' is not signed.
> W: The repository 'http://ppa.launchpad.net/couchdb/stable/ubuntu trusty Release' does not have a Release file.
> W: Failed to fetch https://packagecloud.io/computology/apt-backport/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
> W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/trusty/InRelease  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
> W: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/trusty/InRelease  Failed to connect to packagecloud.io port 443: Connection timed out
> W: Failed to fetch http://ppa.launchpad.net/openjdk-r/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/pollinate/ppa/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/trusty/InRelease  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/chris-lea/redis-server/ubuntu/dists/trusty/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
> W: Failed to fetch http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/trusty/main/binary-i386/Packages  Unable to connect to ppa.launchpad.net:http:
> W: Some index files failed to download. They have been ignored, or old ones used instead.
