### ISSUE TITLE
ASN1 CHOICE with ambiguous ASN1 packets

### ISSUE THREAD

**Issue by martingalloar** [secdev/scapy#1131]
Hey all! I've some doubts about how to make `ASN1F_CHOICE` to work with ambiguous ASN1 packets.

Let's say we've the following two obsiously different ASN1 packet definitions:
```
class ASN1Packet1(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_IA5_STRING("field1", ""),
        ASN1F_IA5_STRING("field2", ""),
    )

class ASN1Packet2(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_SEQUENCE(
        ASN1F_IA5_STRING("field1", ""),
        ASN1F_INTEGER("field2", ""),
    )
```

Now let's say that we've the following packet that have the previous two as choices:
```
class ASN1Packet1or2(ASN1_Packet):
    ASN1_codec = ASN1_Codecs.BER
    ASN1_root = ASN1F_CHOICE("packet", ASN1Packet1(),
                             ASN1Packet1,
                             ASN1Packet2,
    )
```

It's not currently possible to have the CHOICE field to correctly parse the two different but valid packets, as shown with the following code:
```
p1 = ASN1Packet1(field1="some field1 value", field2="some field2 value")
p2 = ASN1Packet2(field1="some field1 value", field2=1234)

ASN1Packet1or2(str(p2))
ASN1Packet1or2(str(p1))
```
The guilty code is https://github.com/secdev/scapy/blob/master/scapy/asn1fields.py#L460, that uses the `network_tag` of the packet `ASN1_root` as key, resulting in two different packets starting with the same tag to be resolved as the same choice.

I can imagine some dirty recursive strategies for fixing this but not sure what would be the best approach. Any hint and or suggestion?

**Comment by gpotter2** [comment]
Hi !
Sorry for the delay, are you still having your issue ?
Because ASN.1 isn't easy, I guess no one really wanted to get into it 😄

**Comment by martingalloar** [comment]
Hey! NP. I kind of workarounded it by implementing a try/except, you can see it in https://github.com/CoreSecurity/pysap/blob/master/pysap/utils/fields.py#L295. I think this is far from ideal but yeah as you said, ASN.1 isn't easy. I think the problem even might be on the ASN.1 definition itself, as this will happen with any way of trying to implement a parser with those ASN.1 structures that are somehow ambiguous.

**Comment by gpotter2** [comment]
Glad you could find some way out.

We have worked out a `MultipleTypeField`, which takes a different type depending on other values of the same packet. I wonder if it could be used with ASN1F_CHOICE (it is not a packet but an object, so *should* (not tested, i have no idea) be compatible with ASN1Packets).

Feel free to close this issue if you think you don't need any more help. :)

**Comment by martingalloar** [comment]
Thanks for pointing this out! I think something like the `MultipleTypeField` might be a good approach and maybe also work for some other non ASN.1 use cases I'd solved using a similar approach. Will probably move to using it when ready in a scapy release!
