### ISSUE TITLE
SNMPv3 packet support

### ISSUE THREAD

**Issue by vikas-boundless** [secdev/scapy#1132]
Enhancements : Support for SNMPv3 packtes required.

**Comment by vikas-boundless** [comment]
I can work over it if no one else it working.

**Comment by gpotter2** [comment]
No one's currently working on that.
If you are willing to submit a PR, feel free to do so !

**Comment by vikas-boundless** [comment]
I am on it. Thanks

**Comment by guedou** [comment]
Moved to #399
