### ISSUE TITLE
[Windows] POWERSHELL_MANAGER is never closed explicitly

### ISSUE THREAD

**Issue by rgom** [secdev/scapy#1136]
scapy-2.4.0rc4.dev58-py2.7
Windows 7

POWERSHELL_MANAGER isn't closed in arch/windows/__init__.py

That's a problem, because subprocess used inherits open files. The files can't be deleted without waiting for scapy to end (sleep-wait-repeat).

I've added POWERSHELL_MANAGER.close() near the bottom of __init__.py and it solved the problem.

Steps to reproduce:
1. Create a file.
2. Replace sys.stdout/stderr with it (I'm doing a tee)
3. Import scapy
4. Try to remove created file after closing it

Observed behaviour:
- exception - file in use, can't be deleted

Expected behaviour:
- file is deleted just fine

Reproducible:
- always

**Comment by gpotter2** [comment]
@rgom Hi ! Thanks a lot for reporting

> Try to remove created file after closing it

Do you mean closing the file or scapy ?

Thanks !

**Comment by rgom** [comment]
Hello,
I mean closing the file.

If I create a file:

a = open('...', 'w')

then do a subprocess:

subprocess.Popen()...

then close the file:

a.close()

the file can't be deleted with:

os.remove(a.name)

Please compare to Python bug report https://bugs.python.org/issue19575
This is identical story, but all the enhancements went to Python 3.

I can see no other way to proceed than proposed (add the close explicit call).
If anybody can come up with anything smarter, I'd appreciate.

HTH,
Robert

**Comment by rgom** [comment]
```import os
f = open('c:/temp/x.txt', 'w')
from scapy import all as scapy  # TROUBLE AHEAD
f.close()
os.remove(f.name)
```

```
Traceback (most recent call last):
  File "D:\A.py", line 9, in <module>
    os.remove(f.name)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:/temp/x.txt'
```

**Comment by gpotter2** [comment]
I understand what you mean.

The point of not calling `POWERSHELL_MANAGER.close()` is that scapy does not have to start any more shell while performing OS access (through cmd/powershell). It speeds up the process to have a shell in no-CPU mode in the background.

I'm looking into a solution :)

**Comment by gpotter2** [comment]
This is a Python 2.7 bug.
It was fixed on python 3.4+ ([link](https://www.python.org/dev/peps/pep-0433/)).

Scapy is not responsible for it... I'll try to find a work-around

**Comment by rgom** [comment]
Thank you for the feedback.

I must admit I have a different opinion, since I didn't observe that on any other imported package.

I have a workaround for my applications (adding NOINHERIT flag when opening a file created before importing scapy), but it's hard for me to maintain and I'd expect similar bug reports in the future.

I couldn't find anything relevant in subprocess myself (close_fds has significant limitations).

Regards,
Robert

**Comment by karpierz** [comment]
It is god know issue/error in Py2.
There is no other option than setting this flag by ctypes fro windows.
In Python 2.7 there is no sys.get/set_handle_inheritable() but is easy to write those.
Another way/workaround (on our side) is to wait for finishing thread (and - powershell -process) process in it.
On scapy side will be best of existing e.g. scapy.finalize() method which will be responsible for close
appropriate resouces e.g. POWERSHELL_PROCESS) and can be used in our code _before_ our closing/renaming blocked file/handle.

**Comment by karpierz** [comment]
Another workaround is to use scapy.???.???.POWERSHELL_PROCESS.close() in our code (in place when finalize() should be used) but it is weird, not portable etc. etc. Simply: such way cannot be used/implemented :(
Waiting for release handle is much better/natural (simply emulates waiting for semaphore.. Yes, it 
is de facto the same problem:).

**Comment by karpierz** [comment]
Another way is use io.open() instead of open() but I don't know whether io.open() has the same
feature (not inherit handles in child processes) as both (open() & io.open()) in PY3.
Anyway: worth to  check this out... but can be another problem with encoding etc...
io.open() & open(0 is not quite the same (especially in Py2).

**Comment by karpierz** [comment]
Anyway:... 
Maybe worth to replace powershell/vbscript callls for appropriate pure Python solutions ?
In one/two places is easy (e.g. reading Windows registry) in other will be harder but.. not impossible..
Is there a chance for doing it in short period for release 2.4? I doubt :(

**Comment by gpotter2** [comment]
I’m thinking of a hack to set all opened files as not herited. Should be possible with windll api calls.. will check that out tonight.

**Comment by karpierz** [comment]
Maybe our hacks will be useful for you...

```
# ctypes's backports from PY3


def get_inheritable(fd):

    from ctypes import byref
    from ctypes import windll, wintypes
    from ctypes import WinError
    from msvcrt import get_osfhandle

    HANDLE_FLAG_INHERIT = 1

    handle = wintypes.HANDLE(get_osfhandle(fd))
    flags  = wintypes.DWORD()
    if not windll.kernel32.GetHandleInformation(handle, byref(flags)):
        raise WinError()

    return bool(flags.value & HANDLE_FLAG_INHERIT)


def set_inheritable(fd, inheritable):

    from ctypes import windll, wintypes
    from ctypes import WinError
    from msvcrt import get_osfhandle

    HANDLE_FLAG_INHERIT = 1

    handle = wintypes.HANDLE(get_osfhandle(fd))
    mask   = wintypes.DWORD(HANDLE_FLAG_INHERIT)
    flags  = wintypes.DWORD(HANDLE_FLAG_INHERIT if inheritable else 0)
    if not windll.kernel32.SetHandleInformation(handle, mask, flags):
        raise WinError()


with open("AAA.txt", "w") as f:
    print(get_inheritable(f.fileno()))
    set_inheritable(f.fileno(), False)
    print(get_inheritable(f.fileno()))


import os
with os.fdopen(os.open("XXX.txt", os.O_NOINHERIT | os.O_WRONLY | os.O_CREAT), "w") as f:
    print(get_inheritable(f.fileno()))
    from scapy import all as scapy  # TROUBLE AHEAD
os.remove("XXX.txt")

# Displays: False (meani OK).
```

**Comment by karpierz** [comment]
:: I’m thinking of a hack to set all opened files as not inherited.

subprocess.Popen(close_fds=True) will be helpful but then exist some problems with stdout/stderr redirection. 

Thanks,
Adam Karpierz

**Comment by gpotter2** [comment]
I got a working fix !

**Comment by gpotter2** [comment]
@karpierz @rgom 
Hi !
Issue was fixed in https://github.com/secdev/scapy/pull/1138
![image](https://user-images.githubusercontent.com/10530980/35926617-dd8a551a-0c28-11e8-91d1-8b9e5d98cfe2.png)

`close_fds` is not available when stdout/stderr is used. The provided hack converts already existing opened files to non inheritable ones.

**Comment by gpotter2** [comment]
@karpierz For the record, it's really hard for us not to call any CMD/VBS commands, without having to implement C code.

As scapy is a pure python project, it would become harder to compile, and break with the `download-and-run` policy

**Comment by karpierz** [comment]
I really can help in this area in the future because I am familiar with ctypes usage a years (and I am really very old C/C++ programmer;) 
Seriously: Practically all my low-level Python C-related code is based only and only on ctypes.

**Comment by gpotter2** [comment]
@karpierz You are really welcomed to do so !

**Comment by karpierz** [comment]
Thank for your fix a lot!! 
It was really blocked thing for us.

**Comment by rgom** [comment]
Thank you for the fix.
I confirm it fixes the test case provided - I'll have to verify it on bigger code base to see impact on actual code, but I don't expect surprises.
Is it going to land in 2.4 release?

Regards,
Robert

**Comment by rgom** [comment]
Update:
I've verified the change successfully on bigger code base.

**Comment by gpotter2** [comment]
FTR, all of this was made obsolete by https://github.com/secdev/scapy/pull/1759 (C calls to mod Thebes interfaces)
