### ISSUE TITLE
Custom Packet has problems with self.explicit

### ISSUE THREAD

**Issue by fsch2** [secdev/scapy#1143]
Hi there, first of all, thanks for scapy, it's great!

I wonder what the meaning of the `self.explicit` property of the `class Packet` is. The reason for my question:

I have created a custom field, an array with a predefined number of elements. The internal representation is a Python list. I can add it to a packet and it is serialized correctly **if (and only if)** I manually set `self.explicit` of the packet to `True`. The reason for this seems to be, that `do_build` in packet.py does some weird stuff, when `self.explicit` is false:

https://github.com/secdev/scapy/blob/e91f3a81b4cefeaed850701999813ccfd93d626e/scapy/packet.py#L423-L425

Can someone explain what `self.explicit` should be used for? What does the complicated logic invoked by `do_build` actually do? Thanks in Advance!

Cheers

**Comment by fsch2** [comment]
This is the code. Sorry, it is a bit lengthy.
```python
class FixedLenArray(Field):

    __slots__ = ...
    def __init__(self, name, default_element, element_count, fieldtype):
        if not isinstance(element_count, int):
            raise TypeError("'element_count' must be an int!")
        if not issubclass(fieldtype, Field):
            raise TypeError("'fieldtype' must be a Field!")

        # Define the member variables
        self.element_count = element_count
        self.fieldtype = fieldtype
        self.default_element = default_element
        factory = self.fieldtype("n/a", self.default_element)
        self.sz = self.element_count * calcsize(factory.fmt)
        
        Field.__init__(self, name, [default_element]*element_count,
                       fmt = "{}s".format(self.sz))
                
    def i2m(self, pkt, x):
        """Convert from internal to machine represenation.

        The specified value is converted to machine representation
        by converting the elements one by one. The specified value
        must be iterable (e.g. a list), otherwise this will fail.
        
        Args:
            pkt: The Packet that the field belongs to

            x: The internal value that is encoded.
        """
        assert isinstance(x, Iterable)
        it = itertools.chain(x, itertools.repeat(self.default_element))
        buffer = b""
        factory = self.fieldtype("n/a", self.default_element)
        for _ in range(self.element_count):
            buffer = factory.addfield(pkt, buffer, it.__next__())
        return buffer

    def m2i(self, pkt, x):
        """Convert from machine to internal represenation.

        The specified value is converted to internal representation
        by converting the elements one by one. The element_count
        property is used to determine the number of elements that
        needs to be converted.
        
        Args:
            pkt: The Packet that the field belongs to

            x: The buffer that is decoded.
        """
        factory = self.fieldtype("n/a", self.default_element)
        val = []
        for _ in range(self.element_count):
            x, item = factory.getfield(pkt, x)
            val.append(item)
        return val
```

**Comment by guedou** [comment]
`explicit` is used to know if the packet is implicit (i.e. IP()/UDP), or explicit (i.e. IP(ttl=(0,2)/UDP(), Scapy will generate 3 packets).

**Comment by fsch2** [comment]
@guedou Thanks for the reply.

I am afraid, I still don't understand the meaning of ``explicit``. Apart from it being the opposite of ``implicit``. Is an implicit packet one that is auto-generated because a layer above *needs* it? If so, then what is the purpose of the complex logic in packet.py using the iterators?

Then again, I was able to resolve the problem by setting the ``islist`` attribute to ``True``. That did the trick.

**Comment by guedou** [comment]
The documentation provides more examples of implicit packets: http://scapy.readthedocs.io/en/latest/introduction.html?highlight=implicit.

In a nutshell, there are Scapy Packets (i.e. Python objects), that express more than one 'physical' packet (i.e. ones sent over the network).

If your field contains a list, `islist` is the way to go.

**Comment by fsch2** [comment]
Thanks, again. I got it now. It helps me thinking of *implicit* packets as *parametrized* packets. By that, an implicit packet is a description of a series/set of explicit packets using some list or set to iterate over.

I am writing this down, it might help someone in the future.
