### ISSUE TITLE
DHCPv6Relay packet not properly dissected

### ISSUE THREAD

**Issue by lidllohntsich** [secdev/scapy#1147]
Scapy is not able to handle the following packet correctly:

0000  0C012001078900000000000000000000 .. .............
0010  00BAFE80000000000000000000000000 ................
0020  11110012000B495056362D544553542D ......IPV6-TEST-
0030  310009002A0C00200107890000000000 1...*.. ........
0040  0000000000001AFE8000000000000000 ................
0050  0000000000ABCD0009000401000000   ...............

Wireshark has no problem to handle the packet.

Here is the pkt.show() printout:
###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
  msgtype   = RELAY-FORW
  hopcount  = 1
  linkaddr  = 2001:789::ba
  peeraddr  = fe80::1111
###[ DHCP6 Interface-Id Option ]### 
     optcode   = INTERFACE_ID
     optlen    = 11
     ifaceid   = 'IPV6-TEST-1'
###[ DHCP6 Relay Message Option ]### 
        optcode   = RELAY_MSG
        optlen    = 42
        \message   \
         |###[ DHCPv6 Generic Message ]### 
         |  msgtype   = RELAY-FORW
         |  trid      = 0x2001
         |###[ Unknown DHCPv6 Option ]### 
         |     optcode   = 1929
         |     optlen    = 0
         |     data      = ''
         |###[ Unknown DHCPv6 Option ]### 
         |        optcode   = 0
         |        optlen    = 0
         |        data      = ''
         |###[ Unknown DHCPv6 Option ]### 
         |           optcode   = 0
         |           optlen    = 0
         |           data      = ''
         |###[ Raw ]### 
         |              load      = '\x00\x1a\xfe\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xab\xcd\x00\t\x00\x04\x01\x00\x00\x00'

Instead of DHCPv6 Generic Message layer,  it should be:
DHCPv6 Relay Forw
--Relay Message
-----DHCPv6 Solicit

If you need additional info, just let me know.

Thanks

regards
lidl

[dhcpv6_relay_fw.zip](https://github.com/secdev/scapy/files/1720272/dhcpv6_relay_fw.zip)

**Comment by guedou** [comment]
Thanks for the report. Could you send us a pcap ?

**Comment by lidllohntsich** [comment]
zip file  added to initial post

**Comment by speakinghedge** [comment]
Le wild guess: The DHCP6OptRelayMsg treats the payload as an option - but it should be a DHCPv6 message.

@lidllohntsich could you please test the attached patch?

[fix-dhcpv4-relay-message.zip](https://github.com/secdev/scapy/files/1721229/fix-dhcpv4-relay-message.zip)

**Comment by speakinghedge** [comment]
I'm going to create a PR a soon as I was able to fix the related tests.

**Comment by speakinghedge** [comment]
PR is [here](https://github.com/secdev/scapy/pull/1149) and 

```
frm = Ether()/IPv6()/UDP()/DHCP6_RelayForward()/DHCP6OptRelayMsg()/DHCP6_RelayForward()/DHCP6OptRelayMsg()/DHCP6_Solicit()/Raw(b'X' * 256)
frm = Ether(frm.do_build())
frm.show()
```

results in

```
###[ Ethernet ]### 
  dst       = ff:ff:ff:ff:ff:ff
  src       = 00:00:00:00:00:00
  type      = 0x86dd
###[ IPv6 ]### 
     version   = 6
     tc        = 0
     fl        = 0
     plen      = 344
     nh        = UDP
     hlim      = 64
     src       = ::1
     dst       = ::1
###[ UDP ]### 
        sport     = dhcpv6_server
        dport     = dhcpv6_server
        len       = 344
        chksum    = 0xb18a
###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
           msgtype   = RELAY-FORW
           hopcount  = 0
           linkaddr  = ::
           peeraddr  = ::
###[ DHCP6 Relay Message Option ]### 
              optcode   = RELAY_MSG
              optlen    = 298
###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
                 msgtype   = RELAY-FORW
                 hopcount  = 0
                 linkaddr  = ::
                 peeraddr  = ::
###[ DHCP6 Relay Message Option ]### 
                    optcode   = RELAY_MSG
                    optlen    = 260
###[ DHCPv6 Solicit Message ]### 
                       msgtype   = SOLICIT
                       trid      = 0x0
###[ Unknown DHCPv6 Option ]### 
                          optcode   = 22616
                          optlen    = 22616
                          data      = 'X<removed 254 X>X'
```

Also attached a stripped pcap that only contains the relevant frames.

[dhcpv6-relay-stripped.zip](https://github.com/secdev/scapy/files/1721627/dhcpv6-relay-stripped.zip)

**Comment by lidllohntsich** [comment]
first of all thanks for the quick response.

Unfortunately your patch did not work. It even spoiled up some other DHCPv6 msgs.
BTW the interfaceID is missing in your example.
Anyhow here is the printout of the pkt.show():

###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
  msgtype   = RELAY-FORW
  hopcount  = 1
  linkaddr  = 2001:789::ba
  peeraddr  = fe80::1111
###[ DHCP6 Interface-Id Option ]### 
     optcode   = INTERFACE_ID
     optlen    = 11
     ifaceid   = 'IPV6-TEST-1'
###[ Raw ]### 
        load      = '\x00\t\x00*\x0c\x00 \x01\x07\x89\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1a\xfe\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xab\xcd\x00\t\x00\x04\x01\x00\x00\x00'

**Comment by speakinghedge** [comment]
Hmm.. works with the trace you provided.

If I replay the two DHCPv6 frames from [your trace](https://github.com/secdev/scapy/files/1721627/dhcpv6-relay-stripped.zip) I get:

```
###[ Ethernet ]### 
  dst       = 33:33:00:01:00:02
  src       = 00:13:3b:13:25:dd
  type      = 0x86dd
###[ IPv6 ]### 
     version   = 6
     tc        = 0
     fl        = 0
     plen      = 50
     nh        = UDP
     hlim      = 64
     src       = fe80::1111
     dst       = ff02::1:2
###[ UDP ]### 
        sport     = dhcpv6_server
        dport     = dhcpv6_server
        len       = 50
        chksum    = 0xdad
###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
           msgtype   = RELAY-FORW
           hopcount  = 0
           linkaddr  = 2001:789::1a
           peeraddr  = fe80::abcd
###[ DHCP6 Relay Message Option ]### 
              optcode   = RELAY_MSG
              optlen    = 4
###[ DHCPv6 Solicit Message ]### 
                 msgtype   = SOLICIT
                 trid      = 0x0

###[ Ethernet ]### 
  dst       = 00:13:3b:13:25:de
  src       = 00:a0:57:1b:ac:ab
  type      = 0x86dd
###[ IPv6 ]### 
     version   = 6
     tc        = 0
     fl        = 0
     plen      = 103
     nh        = UDP
     hlim      = 64
     src       = fd00:db8::1
     dst       = fd00:db8::2
###[ UDP ]### 
        sport     = dhcpv6_server
        dport     = dhcpv6_server
        len       = 103
        chksum    = 0xd736
###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
           msgtype   = RELAY-FORW
           hopcount  = 1
           linkaddr  = 2001:789::ba
           peeraddr  = fe80::1111
###[ DHCP6 Interface-Id Option ]### 
              optcode   = INTERFACE_ID
              optlen    = 11
              ifaceid   = 'IPV6-TEST-1'
###[ DHCP6 Relay Message Option ]### 
                 optcode   = RELAY_MSG
                 optlen    = 42
###[ DHCPv6 Relay Forward Message (Relay Agent/Server Message) ]### 
                    msgtype   = RELAY-FORW
                    hopcount  = 0
                    linkaddr  = 2001:789::1a
                    peeraddr  = fe80::abcd
###[ DHCP6 Relay Message Option ]### 
                       optcode   = RELAY_MSG
                       optlen    = 4
###[ DHCPv6 Solicit Message ]### 
                          msgtype   = SOLICIT
                          trid      = 0x0
```

And the patch should not affect any other message as it changes the _DHCP6OptRelayMsg_ only.

Can you provide a sample pcap containing the frames you used in your [last post](https://github.com/secdev/scapy/issues/1147#issuecomment-365645410)?

**Comment by speakinghedge** [comment]
even this works as expected:

```
Ether()/IPv6()/UDP()/DHCP6_RelayForward()/DHCP6OptIfaceId()/DHCP6OptRelayMsg()/DHCP6_RelayForward()/DHCP6OptIfaceId()/DHCP6OptRelayMsg()/DHCP6_Solicit()/Raw(b'X' * 256)
```

**Comment by speakinghedge** [comment]
instead if using the patch from above you could also checkout the _fix-dhcpv6-relay-message-clean-#1147_ branch from [my forked repo](git@github.com:speakinghedge/scapy.git).

**Comment by lidllohntsich** [comment]
trying out your patch via the scapy shell seem to work. 
In my setup I got this packet from a router and sniffed it via scapy sniff().
Dumping the received packet in the show() or trying perform checks on the
problematic protocol layer still fail with your patch.

**Comment by speakinghedge** [comment]
wild guess: the traffic from your router is IPv6 traffic and contains IPv6 extension headers?

**Comment by speakinghedge** [comment]
attached a trace used for testing sniff()with the 'setup' below - works for me. so sniff() seems to be okay.

```
eth2@ns:yummi                                  eth1@ns:default
---+                +--------------+           +------
    |---------------| le switch    |-----------|
---+                +--------------+           +-----
tcpreplay...                                   sniff()
```

could you capture the traffic from your router on the wire using a TAP or switch with a span/mirror port?

[dhcpv6-test-frames.zip](https://github.com/secdev/scapy/files/1726799/dhcpv6-test-frames.zip)

**Comment by speakinghedge** [comment]
in other words (coffee hasn't kicked yet so I missed to ask the proper question): 

1. are you using sniff in your scapy-shell setup (that works) or a trace?

2. Are all frames affected/corrupted or only DHCPv6? (as you reported some issues with VLAN in your setup).

3. Can you provide a little more context? Like: OS, Python version, expected behavior vs observed behavior (a rough sketch would be enough like: I send Ether()/Aldi()/Is()/Better() but I got Ether()/Lidl()/Raw() )

4. Can you provide some raw frames directly from the wire from your life system?

**Comment by guedou** [comment]
@lidllohntsich does #1158 works? It provides a simpler fix and does not break the current API.

**Comment by lidllohntsich** [comment]
@guedou  Thanks. Patch seems to work. I could not see any side effects any longer.

**Comment by gpotter2** [comment]
@guedou @p-l- Has not been auto-closed.
Shall be closed
