### ISSUE TITLE
in6_getLocalUniquePrefix() can't be called from a Python script

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#115]
The following code does not work:

```
$ cat test.py
from scapy.all import *

in6_getLocalUniquePrefix()

$ python test.py 
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    in6_getLocalUniquePrefix()
  File "/home/guedou/prog/python/scapy/github/scapy-issues.git/scapy/utils6.py", line 393, in in6_getLocalUniquePrefix
    rawmac = get_if_raw_hwaddr(conf.iface6)[1]
NameError: global name 'get_if_raw_hwaddr' is not defined
```

**Comment by guedou** [comment]
There is a circular dependency between scapy/arch/linux.py and scapy/utils6.py

**Comment by guedou** [comment]
@p-l- I am quite confused with this bug. Without some (heavy ?) refactoring, the simplest patch that I found is the following:
```
$ git diff --no-ext-diff scapy/utils6.py
diff --git a/scapy/utils6.py b/scapy/utils6.py
index 647efa8..1c9e953 100644
--- a/scapy/utils6.py
+++ b/scapy/utils6.py
@@ -390,6 +390,7 @@ def in6_getLocalUniquePrefix():
     j = int((tod - i)*(2**32))
     tod = struct.pack("!II", i,j)
     # TODO: Add some check regarding system address gathering
+    from scapy.arch.linux import get_if_raw_hwaddr
     rawmac = get_if_raw_hwaddr(conf.iface6)[1]
     mac = ":".join(map(lambda x: "%.02x" % ord(x), list(rawmac)))
     # construct modified EUI-64 ID
```
I wonder if this is the best way to fix the issue. On one hand, it works. On the other hand, it does not mean that similar bugs will also be fixed ... What is your advise ?

**Comment by p-l-** [comment]
Will this work on architectures other than Linux? Maybe `from scapy.arch import get_if_raw_hwaddr` would be enough?

We have some circular dependencies issues that we need to fix (and a lot of them are around `arch`), but that's a huge work and I have not worked on it enough so far to have a clear idea of the best long-term solution.

**Comment by guedou** [comment]
You're right, this patch was not working. Your proposal works fine on Linux and FreeBSD.

**Comment by bobsaintcool** [comment]
Awesome thanks!
