### ISSUE TITLE
ICMPv6 lacks support for MLDv2

### ISSUE THREAD

**Issue by speakinghedge** [secdev/scapy#1152]
__affected version:__ master

__affected protocol(s):__ ~IPv6~, ICMPv6

__brief description__: ~fails to dissect payload after IPv6 extension header (probably related to padding with length of zero)~ as [discovered](https://github.com/secdev/scapy/issues/1152#issuecomment-365935428) by  @guedou MLDv2 is not supported by the ICMPv6 layer

__how to reproduce__:

(using attached trace)
```
frm = rdpcap('ipv6-with-extension-and-zero-padding.pcap', count=1)
frm.show()
```

__actual result__:

```
0000 Ether / fe80::a00:27ff:fed4:10bb > ff02::16 (0) / IPv6ExtHdrHopByHop / Raw
```

Payload after _IPv6ExtHdrHopByHop_ is dissected as Raw().

__expected result__:

as seen in Wireshark:
![ipv6-extension-with-zero-padding](https://user-images.githubusercontent.com/1612957/36247949-188526dc-1236-11e8-80e0-4c00a0c61e94.png)

__sample trace:__ [ipv6-with-extension-and-zero-padding.zip](https://github.com/secdev/scapy/files/1726867/ipv6-with-extension-and-zero-padding.zip)

**Comment by guedou** [comment]
Scapy does not currently support MLDv2. That the real issue here.

**Comment by speakinghedge** [comment]
is see...

for reference: https://tools.ietf.org/html/rfc3810

**Comment by guedou** [comment]
I am working on a fix.
