### ISSUE TITLE
 "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by nickever** [secdev/scapy#1157]
I've tried a few different install methods without luck. Any suggestions for a fix to the error below. Running '$sudo pip3 install scapy' on macOS 10.12. Thanks

```
Collecting scapy
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 690kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-qawomv3p/scapy/setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-qawomv3p/scapy/
```

**Comment by guedou** [comment]
Which version of Python and pip are you using?

Can you try with the following command? It will install the current release candidate.
```
pip install --pre scapy
```

**Comment by nickever** [comment]
Thanks for the reply guedou. Python v3.6.4 and Pip v9.0.1

installing the --pre version worked. Thanks!

**Comment by guedou** [comment]
v2.3.3 does not work with Python3. v2.4.0 supports it and will be released when the remaining issues are fixed: https://github.com/secdev/scapy/projects/1
