### ISSUE TITLE
2.3.3 stable release setup.py chmod 0755

### ISSUE THREAD

**Issue by ruivapps** [secdev/scapy#1159]
2.3.3 stable release (default pip install scapy)still using os.chmod(fname, 0755)
I see master is already updated. [ Commit ](https://github.com/secdev/scapy/commit/291400c1b6f65363e33cc982aaf0d43d31cc424e)

is there any plan to bring the change to 2.3.3 version? 
So, **pip install scapy** on python3 won't raise 

~~~
SyntaxError: invalid token
~~~

**Comment by guedou** [comment]
Scapy 2.3.3 does not support Python". Scapy 2.4.0 will.

In the mean time, please use
```
pip install --pre scapy
```
