### ISSUE TITLE
monitor mode of wireless device in OSX not working

### ISSUE THREAD

**Issue by dreerr** [secdev/scapy#1161]
When trying to run a simple program like
```
def pktIdentifier(pkt):
    if pkt.haslayer(Dot11Beacon):
        print("[+] Detected 802.11 Beacon Frame")
    elif pkt.haslayer(Dot11ProbeReq):
        print("[+] Detected 802.11 Probe Frame")
sniff(iface="en0", prn=pktIdentifier)
```
Scapy isn't able to set the network interface into proper monitoring mode. Whereas `tcpdump -i en0 -I -py IEEE802_11` immediately turns monitoring mode on and the icon in the menu bar changes to: ![bildschirmfoto 2018-02-16 um 19 57 41](https://user-images.githubusercontent.com/1454661/36324154-cecc6d60-1353-11e8-8b90-2807c8d286bc.png)

Using `conf.use_pcap` didn't work either, there is also a StackOverflow stub [here](https://stackoverflow.com/a/46914983/336633)

**Comment by guedou** [comment]
Scapy does not enable monitor mode, as some users want to sniff the real IP traffic, while others want the 802.12 one.

 You need to do it yourself for example, using airmon-ng or ifconfig depending on your OS.

**Comment by guedou** [comment]
It seems that it used to be better in the old days according to this comment: https://github.com/the-tcpdump-group/libpcap/blob/7a04be7771d44a2f7e74210cc39e4df0ccef8d97/pcap-bpf.c#L752

I will try to hack something, but won't have time to push a proper fix anytime soon.

**Comment by dreerr** [comment]
Thanks for investigating that issue! There seems to be no way in OSX to set the Airport Card into Monitor Mode, without capturing into that program. The ways I found to enter Monitor Mode was with WireShark, KisMac, `sudo tcpdump -Ii en0` and `airport sniff CHANNEL` 
But when having a capture session with i.e. tcpdump it is not possible to attach scapy on the same interface. 

pcap's [pcap_set_rfmon()](https://www.tcpdump.org/manpages/pcap_set_rfmon.3pcap.html) seems to be the sticking point here.

**Comment by gpotter2** [comment]
Hello !
I managed to implement monitor mode in Windows (https://github.com/secdev/scapy/pull/1165).

What's annoying with it is that `pcap_set_rfmon` needs to be called on non-activated handles, which means you can't use `pcap_open_live` functions (or any equivalent). For instance, I had to call even lower API (see PR: `pcap_create`, `pcap_activate`...).

You might want to grab ideas from the Windows implementation (which uses pcap)

Good week

**Comment by gpotter2** [comment]
I've poked `pypcap` to see if they could implement `pcap_set_rfmon`.

They nicely responded that there was an awaiting PR: https://github.com/pynetwork/pypcap/pull/67 that supports it.

I don't have access to an OSX machine with WiFi enabled. Would be really cool if someone could implement monitor mode.
Note: proper way to start a monitor socket is

```
self.pcap = pcap_create(self.iface, self.errbuf)
pcap_set_snaplen(self.pcap, snaplen)
pcap_set_promisc(self.pcap, promisc)
pcap_set_timeout(self.pcap, to_ms)
if pcap_set_rfmon(self.pcap, 1) != 0:
    warning("Could not set monitor mode")
if pcap_activate(self.pcap) != 0:
    warning("Could not activate the handler")
```

**Comment by guedou** [comment]
As Scapy does not need a pcap module on OS X, I want this feature to be implemented with ctypes only.

**Comment by gpotter2** [comment]
I didn't know :/ sry

**Comment by guedou** [comment]
@dreer can you try PR #1215 ?

**Comment by guedou** [comment]
I have another patch for other *BSD but I cannot test it =/

**Comment by dreerr** [comment]
Successfully working under OSX High Sierra 🤘

**Comment by guedou** [comment]
Perfect !

**Comment by grahulprouhit** [comment]
my wifi card is on monitor mode but not able to find any network
