### ISSUE TITLE
Scapy send issue on latest build '2.4.0rc4.dev94' on python3.

### ISSUE THREAD

**Issue by aryan21710** [secdev/scapy#1176]
I am trying to send an icmp packet using my wireless interface. I keep getting following error. I am using the latest scapy version on python3. When i try to send packet using python3 shell, i keep getting segmentation fault 11 error. Both sr and send is failing. But it works seamlessly using ./run_python. Any suggestion workaround is really appeciated. Is this a known issue? I have tried updating the scapy to the latest version from the github repository which is ' 'Version 2.4.0rc4.dev94'.

++++++++++++++++++

bash-3.2$ ifconfig en1
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500ether 24:a0:74:ef:c2:0a 
inet6 fe80::1421:2877:9b9f:8b7e%en1 prefixlen 64 secured scopeid 0x5 
inet 192.168.0.56 netmask 0xffffff00 broadcast 192.168.0.255nd6 options=201<PERFORMNUD,DAD>media: autoselect
status: active
bash-3.2$ ping -S 192.168.0.56 www.google.com
PING www.google.com (172.217.166.68) from 192.168.0.56: 56 data bytes64 bytes from 172.217.166.68: icmp_seq=0 ttl=55 time=26.458 ms64 bytes from 172.217.166.68: icmp_seq=1 ttl=55 time=21.927 ms

bASH-3.2$ scapy
WARNING: Cannot read wireshark manuf database 
WARNING: Crypto-related methods disabled for IPsec, Dot11 and TLS 
         layers (needs python-cryptography v1.7+).WARNING: No route found for IPv6 destination :: (no default route?)INFO: Can't import python-cryptography v1.7+. Disabled WEP 
decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec 
encryption/authentication.WARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.

>>> sr(IP(dst='www.google.com')/ICMP())
Traceback (most recent call last):
File "<console>", line 1, in <module>
File "/Library/Python/2.7/site-packages/scapy-2.4.0rc4-
py2.7.egg/scapy/sendrecv.py", line 364, in sr
s = conf.L3socket(promisc=promisc, filter=filter, iface=iface, 
nofilter=nofilter)
File "/Library/Python/2.7/site-packages/scapy-2.4.0rc4-
py2.7.egg/scapy/arch/bpf/supersocket.py", line 57, in __init__(self.ins, self.dev_bpf) = get_dev_bpf()
File "/Library/Python/2.7/site-packages/scapy-2.4.0rc4-
py2.7.egg/scapy/arch/bpf/core.py", line 98, in get_dev_bpfraise Scapy_Exception("No /dev/bpf handle is available !")
Scapy_Exception: No /dev/bpf handle is available

**Comment by guedou** [comment]
Scapy needs “root”. Did you try with sudo ?

**Comment by aryan21710** [comment]
All the other sappy commands works without sudo... also I am trying scapy
from python interactive shell. I first import the scapy.all module. Once I
am in the shell it doesn't give me an option to use sudo(send(IP)).

**Comment by guedou** [comment]
Could you try with:
```
git clone https://github.com/secdev/scapy/
cd scapy/
sudo ./run_scapy_py3
```
Also, which OS are you using?

**Comment by aryan21710** [comment]
./run_scapy works.  I am using python 3.4 on Macos.

**Comment by guedou** [comment]
Did you try the command that I gave you? You are not helpful...

**Comment by aryan21710** [comment]
I will try that command and will get back to you.  Let me know what else
info you need.

I have a very bad network connection today coz of some repair work.

**Comment by aryan21710** [comment]
When I try
git clone https://github.com/secdev/scapy ... it throws fatal error
"destination path scapy already exists and is not an empty directory".

**Comment by guedou** [comment]
Try in another directory ...

**Comment by aryan21710** [comment]
Tried in another dir and it worked. Please see the logs.


bash-3.2$ git clone https://github.com/secdev/scapy/

Cloning into 'scapy'...

remote: Counting objects: 15877, done.

remote: Compressing objects: 100% (48/48), done.

remote: Total 15877 (delta 44), reused 51 (delta 31), pack-reused 15798

Receiving objects: 100% (15877/15877), 68.00 MiB | 664.00 KiB/s, done.

Resolving deltas: 100% (8771/8771), done.

bash-3.2$ cd scapy

bash-3.2$ sudo ./run_scapy3

Password:

sudo: ./run_scapy3: command not found

bash-3.2$ sudo ./run_scapy_py3

WARNING: Cannot read wireshark manuf database

INFO: Can't import matplotlib. Won't be able to plot.

INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().

INFO: Can't import python-cryptography v1.7+. Disabled WEP
decryption/encryption. (Dot11)

INFO: Can't import python-cryptography v1.7+. Disabled IPsec
encryption/authentication.

WARNING: IPython not available. Using standard Python shell instead.

AutoCompletion, History are disabled.



*                     aSPY//YASa       *

*             apyyyyCY//////////YCa    **   |*

*            sY//////YSpcs  scpCY//Pp  **   | Welcome to Scapy*

* ayp ayyyyyyySCP//Pp           syY//C **   | Version 2.4.0rc4.dev109*

* AYAsAYYYYYYYY///Ps              cY//S**   |*

*         pCCCCY//p          cSSps y//Y**   |
https://github.com/secdev/scapy <https://github.com/secdev/scapy>*

*         SPPPP///a          pP///AC//Y**   |*

*              A//A            cyP////C**   | Have fun!*

*              p///Ac            sC///a**   |*

*              P////YCpc           A//A**   | Craft packets before they
craft*

*       scccccp///pSP///p          p//Y**   | you.*

*      sY/////////y  caa           S//P**   |                      --
Socrate*

*       cayCyayP//Ya              pY/Ya**   |*

*        sY/PsY////YCc          aC//Yp *

*         sc  sccaCY//PCypaapyCP//YSs  *

*                  spCPY//////YPSps    *

*                       ccaacs         *



*>>> *send(IP(dst='www.google.com')/ICMP())

.

Sent 1 packets.

*>>> *



Let me know if you need to test me another build.

On Sat, Feb 24, 2018 at 7:10 PM, Guillaume Valadon <notifications@github.com

**Comment by guedou** [comment]
So there is no issue, you only need to launch Scapy using sudo.

**Comment by aryan21710** [comment]
Can you please let me know why scapy fails when i a run a python script in
which scapy module is imported?

Script:-

#!/usr/bin/python3

import sys

from scapy.all import *


png=IP(dst='www.google.com')/ICMP()

print ('CALLING SCAPY SEND PROGRAM')

try:

   r=srloop(png,count=10)

   for i in r:

       if i.haslayer(ICMP):

          print ('THE ICMP PACKETS ARE:-',str(i[ICMP]))

except:

   print ('SENDING PACKETS FAILED AGAIN:-', sys.exc_info()[0])




Logs:-

bash-3.2$ python3 scapy_send.py

CALLING SCAPY SEND PROGRAM

 SENDING PACKETS FAILED AGAIN:- <class 'scapy.error.Scapy_Exception'>


On Sat, Feb 24, 2018 at 8:05 PM, Guillaume Valadon <notifications@github.com

**Comment by p-l-** [comment]
@aryan21710 please do **not** comment on a closed issue. Open another one if you have another question. Also, please format your text correctly, it is too hard to read.

**Comment by Khumoyun1307** [comment]
> Scapy needs “root”. Did you try with sudo ?

Same issue for me but my os is Windows . what can I do
