### ISSUE TITLE
Contrib tests in regression.uts

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1177]
Some contrib tests are in regression.uts and need to be moved.

**Comment by speakinghedge** [comment]
will work on it. (kind of compensation for the FUD I left over in LLDP)

**Comment by speakinghedge** [comment]
Is there anything else beside the MPLS tests?

**Comment by guedou** [comment]
I would like to move scapy/contrib/*.uts to test/contrib.

**Comment by speakinghedge** [comment]
> I would like to move...

or

I would *also* like to move...

as moving scapy/contrib/*.uts is somehow different from extracting contrib tests from regression.uts.

I can do it - new ticket or new issue title?

**Comment by speakinghedge** [comment]
Btw: nice trick to make me read the 10K lines of tests. Learned a lot.  :smile:

**Comment by guedou** [comment]
Sorry =/

**Comment by speakinghedge** [comment]
did I miss something? open PR and refine there?

**Comment by p-l-** [comment]
@guedou can we close this one?

**Comment by guedou** [comment]
I would like to move them to either scapy/contribs/ or tests/contribs. I prefer the last solution as it would be a good opportunity to move all tests under tests/

**Comment by speakinghedge** [comment]
> I would like to move them to either scapy/contribs/ or tests/contribs. I prefer the last solution as it would be a good opportunity to move all tests under tests/

Any decision/opinion/ideas/comments on that?

**Comment by gpotter2** [comment]
I do agree with guedou, it would be a good idea to relocate the tests.

It was very handy to have the tests next to the files at the time some contrib modules were missing tests, but we now have added tests for all of them so It isn’t necessary anymore
