### ISSUE TITLE
Scapy send issue from python interactive shell. Follow up to the #1176 issue.

### ISSUE THREAD

**Issue by aryan21710** [secdev/scapy#1182]
**I am trying to send an icmp packet using my wireless interface. I keep getting following error. I am using the latest scapy version on python3. When i try to send packet using python3 shell, i keep getting segmentation fault 11 error. Both sr and send is failing. But it works seamlessly using ./run_python. Any suggestion workaround is really appeciated. Is this a known issue? I have tried updating the scapy to the latest version from the github repository which is ' 'Version 2.4.0rc4.dev94'.**

++++++++++++++++++

bash-3.2$ ifconfig en1
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500ether 24:a0:74:ef:c2:0a
inet6 fe80::1421:2877:9b9f:8b7e%en1 prefixlen 64 secured scopeid 0x5
inet 192.168.0.56 netmask 0xffffff00 broadcast 192.168.0.255nd6 options=201<PERFORMNUD,DAD>media: autoselect
status: active
bash-3.2$ ping -S 192.168.0.56 www.google.com
PING www.google.com (172.217.166.68) from 192.168.0.56: 56 data bytes64 bytes from 172.217.166.68: icmp_seq=0 ttl=55 time=26.458 ms64 bytes from 172.217.166.68: icmp_seq=1 ttl=55 time=21.927 ms

bASH-3.2$ scapy
WARNING: Cannot read wireshark manuf database
WARNING: Crypto-related methods disabled for IPsec, Dot11 and TLS
layers (needs python-cryptography v1.7+).WARNING: No route found for IPv6 destination :: (no default route?)INFO: Can't import python-cryptography v1.7+. Disabled WEP
decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec
encryption/authentication.WARNING: IPython not available. Using standard Python shell instead.
AutoCompletion, History are disabled.

sr(IP(dst='www.google.com')/ICMP())
Traceback (most recent call last):
File "", line 1, in 
File "/Library/Python/2.7/site-packages/scapy-2.4.0rc4-
py2.7.egg/scapy/sendrecv.py", line 364, in sr
s = conf.L3socket(promisc=promisc, filter=filter, iface=iface,
nofilter=nofilter)
File "/Library/Python/2.7/site-packages/scapy-2.4.0rc4-
py2.7.egg/scapy/arch/bpf/supersocket.py", line 57, in init(self.ins, self.dev_bpf) = get_dev_bpf()
File "/Library/Python/2.7/site-packages/scapy-2.4.0rc4-
py2.7.egg/scapy/arch/bpf/core.py", line 98, in get_dev_bpfraise Scapy_Exception("No /dev/bpf handle is available !")
Scapy_Exception: No /dev/bpf handle is available

OS:- Mac
Python:- Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
Scapy build:- 2.4.0rc4.dev94
Dev asked to try latest build and following steps which worked seamlessly.

git clone https://github.com/secdev/scapy/
cd scapy/
sudo ./run_scapy_py3

But when the same thing is tried using a python script and importing scapy module or running scapy under python interactive shell, send/sr/srloop fails.

**Script:-**

    #!/usr/bin/python3

     import sys
     from scapy.all import *

     png=IP(dst='www.google.com')/ICMP()
     print ('CALLING SCAPY SEND PROGRAM')
     try:
         r=srloop(png,count=10)
     
     except:
        print ('SENDING PACKETS FAILED AGAIN:-', sys.exc_info()[0])

     for i in r:
          if i.haslayer(ICMP):
              print ('THE ICMP PACKETS ARE:-',i.show())

**Logs:-**

bash-3.2$ python3 scapy_send.py
CALLING SCAPY SEND PROGRAM
 SENDING PACKETS FAILED AGAIN:- <class 'scapy.error.Scapy_Exception'>

**Comment by p-l-** [comment]
Please format your code properly, we cannot read it now. Read [Github documentation about Markdown](https://guides.github.com/features/mastering-markdown/) and edit your comment.

**Comment by gpotter2** [comment]
@aryan21710 You should give more information about your OS:
- what OSX version are you using ?
- on which device ? Is it virtual ?

**Comment by guedou** [comment]
@aryan21710 please start Scapy as root, for example using sudo.

**Comment by aryan21710** [comment]
Thank You. The script executes flawlessly when ran with sudo.

On Tue, Feb 27, 2018 at 1:38 PM, Guillaume Valadon <notifications@github.com

**Comment by kauegimenes** [comment]
@guedou I have the same issue, already tried running the script with sudo.
mac os 10.13.3

**Comment by guedou** [comment]
Which version of Python and Scapy are you using?

This is likely not an issue with Scapy.

**Comment by kauegimenes** [comment]
scapy-python3 v0.23
Python v3.6.4

**Comment by guedou** [comment]
You are not using this project code...

**Comment by kauegimenes** [comment]
@guedou Its possible to use this project with python v3?

**Comment by gpotter2** [comment]
Yes. We know it's confusing, but for now `scapy-python3` points to an outdated scapy fork.
Please uninstall it and install scapy via `pip install --pre scapy`
