### ISSUE TITLE
Scapy sr:- How to read answered and unanswered summary from the output of sr.

### ISSUE THREAD

**Issue by aryan21710** [secdev/scapy#1188]
As per documentation "Sr return a tuple of two lists. The first element is a list of tuples (packet sent, answer), and the second element is the list of unanswered packets. These two elements are lists, but they are wrapped by an object to present them better, and to provide them with some methods that do most frequently needed actions"

     >>> sr(IP(dst="192.168.8.1")/TCP(dport=[21,22,23]))
     Received 6 packets, got 3 answers, remaining 0 packets
     (<Results: UDP:0 TCP:3 ICMP:0 Other:0>, <Unanswered: UDP:0 TCP:0 ICMP:0 Other:0>)
     
How to print the Unanswered and Answered packets? ans.summary and unans.summary doesnt work.

**Comment by gpotter2** [comment]
You may use `show()` on those lists.

**Comment by p-l-** [comment]
More precisely:

    >>> ans, unans = sr([...])
    >>> ans.show()

**Comment by aryan21710** [comment]
Thank you. It worked.
