### ISSUE TITLE
Using `sendp` inside `bridge_and_sniff` stops bridging

### ISSUE THREAD

**Issue by jomo** [secdev/scapy#1190]
```python
def mitm(pkt):
  if one_moment_in_time:
    sendp(Ether()/IP(dst="1.2.3.4",ttl=(1,4)), iface="eth2")
  return pkt

bridge_and_sniff("eth2", "eth3", xfrm12=mitm, xfrm21=mitm, prn=lambda x:x.summary())
```

I have been using `bridge_and_sniff` as shown above and noticed that – in this case – frames were no longer forwarded from `eth2` to `eth3` (they still were from `eth3` to `eth2`, though) after `sendp` was used.

*Edit:* Just in case it matters, this was done on Kalix Linux 32 bit using two Ethernet interfaces

I assume this is a bug, or maybe I am doing it wrong?

**Comment by speakinghedge** [comment]
you did everything right :smile: - this was caused by a bug.
