### ISSUE TITLE
Is there a way to follow tcp stream / session when using PcapReader to analysis huge pcap file

### ISSUE THREAD

**Issue by zavierxu** [secdev/scapy#1191]
When using rdpcap function, I can get sessions in this way:
```python
sessions = rdpcap('filename').sessions()
```
But I have no idea about using PcapReader to follow sessions

**Comment by guedou** [comment]
The `.sessions()` can only be called on `PacketList` object. You need to implement a similar logic in your code to use it with something else.

**Comment by souravs17031999** [comment]
@zavierxu were you able to resolve this ? 
@guedou can you please post any example of how to get the sessions in case I am using PcapReader for reading a continuos stream.
