### ISSUE TITLE
Send destination on bridge

### ISSUE THREAD

**Issue by valour01** [secdev/scapy#1192]
Consider a scenario that I have a host A and a host B. Between A and B I have a host C. I set the C as the bridge using the tool `brctl`. On host C, I use scapy to create a TCP packet. I set the src as A's addr and the dst as B's addr and then I use `send` to send it out. 

However, when I use Wireshark to capture the packets on both A and B. I noticed that it is A that receiving the TCP packet rather than B. Then I set the iface as the one that directly connected with B. However, B doesn't received, either. Could you please give me some suggestions how to control the destination when I send packets on a host set as a bridge.

**Comment by guedou** [comment]
Did you try injecting using Ethernet instead of IP ?

**Comment by valour01** [comment]
I tried it just now. I am not very sure how to inject using Ethernet instead of IP. I create `e = Ether()` and I set `e.dst = destination interface MAC address` and `e.src = source interface MAC address`; Then I use `send(e/i/t)` instead of `send(i/t)`. However, I could not capture the packets on both A and B. I don't know whether I am right. Could you please give me a small example on injecting using Ethernet?

**Comment by guedou** [comment]
Please have a look at the documentation

**Comment by speakinghedge** [comment]
> Then I use send(e/i/t) instead of send(i/t)

and

> Please have a look at the documentation

especially for the small difference between _send()_ and _send**p**()_
