### ISSUE TITLE
packet.time_sent can't be set because of object copy during list comprehension

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#1199]
https://github.com/secdev/scapy/blob/254ab6d5ae443bb2190e85e4898bfdd8bace9c54/scapy/sendrecv.py#L186

Is this list comprehension necessary at this position? Without a list comprehension, the time_sent values in the objects to be sent will be propagated to the original object. Because of the deep copy in the list comprehension, the time_sent is only set in a temporary object and not in the original object. This applies for all sr and sr1 function calls.

**Comment by guedou** [comment]
What issue are you facing that will require changing this line? Please provide an example.

**Comment by polybassa** [comment]
Hi, here is an example:
```
>>> TIMEOUT = 2
...:conf.verb = 0
...:packet = IP(dst="192.168.178.1", ttl=20)/ICMP()
...:reply = sr1(packet, timeout=TIMEOUT)
...:packet.sent_time is None
...:
True
```

**Comment by polybassa** [comment]
Here is another example. SuperSocket.send() sets the sent_time correctly
```
>>> TIMEOUT = 2
...:conf.verb = 0
...:packet = IP(dst="192.168.178.1", ttl=20)/ICMP()
...:reply = sr1(packet, timeout=TIMEOUT)
...:print(packet.sent_time)
...:s = L2Socket()
...:s.send(packet)
...:print(packet.sent_time)
...:
...:
None
1521442246.051092
```

**Comment by guedou** [comment]
Issue confirmed. I don't have time to investigate it.

**Comment by polybassa** [comment]
The problem ist not the mentioned line. 
The issue is probably in ```packet.__iter__```

**Comment by gpotter2** [comment]
@polybassa was right, we should have fixed `__iter__` instead. The current fix is very ressource-consuming.

I have a patch incoming. The `__iter__` function is probably the most obscure code in Scapy :smile:
