### ISSUE TITLE
I has meet some problem whether I use python2.7 or python3.5+,that is I could not get the interfae or macaddress

### ISSUE THREAD

**Issue by wubucheng** [secdev/scapy#1206]
Detail:
The first question is when I use the method 'get_if_hwaddr' to get mac address, they can not work and the exception is "AttributeError: 'unicode' object has no attribute 'pcap_name'" By the way,My environment is window10+ Python2.7+scapy2.3.3.
The other question is when I use the method 'sniff(iface,count)'  I pass the parameters to the iface, I got the error message is "AttributeError: 'str' object has no attribute 'ismonitor'". In this time I change my environment to pyton 3.5.
So confuse me,Could you help me?

**Comment by gpotter2** [comment]
Hi !
On Windows, unlike on *nix systems, you need to pass a `NetworkInterface` object.
For instance, look at the default one located in `conf.iface`.

You may also use the `IFACES` interface to list them:
![image](https://user-images.githubusercontent.com/10530980/36938018-e0ff1374-1f1b-11e8-8da1-4156ca3054d0.png)

You also have handy functions:
- `dev_from_pcapname(x)`
- `dev_from_index(x)`
- `IFACES.dev_from_name(x)`
That you can import from `scapy.arch.windows` or `scapy.all`, that will help you get the interface.

Feel free to ask any other question :-)

**Comment by wubucheng** [comment]
Thanks for your help! But when I use python,how could I get a IFACES object? I guess can use
 'IFACES = NetworkInterfaceDict()
IFACES.load_from_powershell()'
but  the result unlike a IFACES object

**Comment by gpotter2** [comment]
You can import IFACES using
`from scapy.all import IFACES`
The object is ready to use

**Comment by wubucheng** [comment]
Excuse me,now I have anoter question.Like "---[ Ethernet ]-......---[ IP ]--....--[ ICMP ]--",how can I know the packets has the layer 'icmp' or another in python.Should I using 'packets[index][ICMP]' to test?

**Comment by guedou** [comment]
Please read the documentation, and don't edit your questions.

You can access a specigic layer using the following syntax: p[ICMP], p[ICMP:2], or p[0].
