### ISSUE TITLE
sendp ICMP(type=8) is not correct but sr1(ICMP(type=8)) is correct

### ISSUE THREAD

**Issue by qdyxmas** [secdev/scapy#1210]
my code is 
#coding=utf8
from scapy.all import *
import binascii
import time
timestamp= "%08x" %(time.time())
opt=[IPOption('%s%s%s'%('\x44\x28\x09\x00',binascii.a2b_hex(timestamp),'\x00'*36))]

packet=Ether(src="00:11:22:33:44:55",dst="00:b0:cc:34:be:38")/IP(src="192.168.3.217",dst="192.168.3.1",options=opt,ihl=15)/ICMP(type=8)/"abcdefg"
sendp(packet,iface="eth7")

when i exec script,I capture the icmp packet use wireshark and find the icmp.type is reply

**Comment by guedou** [comment]
Please provide information about your OS, Python and Scapy versions. We won't help your otherwise. This is not a forum but an issue tracker.

**Comment by qdyxmas** [comment]
win7 + scapy2.3.3+python2.10

**Comment by guedou** [comment]
Please try with current master.

**Comment by qdyxmas** [comment]
when i change '\x00'*36 to '\x00'*32 ,it's ok now.
it's my fault ,tks
