### ISSUE TITLE
ImportError: No module named consts

### ISSUE THREAD

**Issue by yuz835** [secdev/scapy#1214]
test/run_tests -P "load_contrib('ethercat')" -t scapy/contrib/ethercat.uts

Traceback (most recent call last):
  File "test/../scapy/tools/UTscapy.py", line 14, in <module>
    from scapy.consts import WINDOWS
ImportError: No module named consts

anyone knows what the problem is? I'm on Mac Os

**Comment by guedou** [comment]
Please report your OS, Python and Scapy versions...

**Comment by yuz835** [comment]
OS: macOS High Sierra 
Python: 2.7
Scapy: I cloned from https://github.com/speakinghedge/scapy
@speakinghedge

**Comment by gpotter2** [comment]
You got an older version of scapy installed on your computer.
Get to the clone folder and overwrite the current version using
`python setup.py install`

**Comment by yuz835** [comment]
thanks alot, I will take a try, and will update later

**Comment by guedou** [comment]
I am sorry but what is the point of opening an issue on this github when you are using code from another one ?
Except wasting our time, I cannot think of anything!

**Comment by yuz835** [comment]
hmm, my bad, I didnt find the issue tab of that one. 
I should ping him directly.
sorry again @guedou
