### ISSUE TITLE
Unsolved issues in compatibility.py in latest version

### ISSUE THREAD

**Issue by yuval9313** [secdev/scapy#1217]
I get stuck on multiple types of problems caused by compatibility.py in Scapy 2.3.3
I've read some guides on some fixes but other issues keep occurring
I've installed the older version (scapy 2.3.2) which has its own unfixable problems
please help me.

p,s running time is very low, it takes about 2 -3 min for Scapy to load also in CMD

**Comment by yuval9313** [comment]
Tried that already
CMD: Requirement already satisfied: scapy

and yet problems keep occurring

**Comment by gpotter2** [comment]
`pip install --upgrade --pre scapy`
