### ISSUE TITLE
OSError: This operation requires Npcap.

### ISSUE THREAD

**Issue by zaheersyed** [secdev/scapy#1221]
I m getting this error while using scapy on windows.
I have installed Npcap on my WIndows 2016 Server. But I m still seeing this error.

sendp( packet, iface=conf.iface )

03/07/2018 12:11:29 - worker - INFO - Traceback (most recent call last):
  File "windows_worker.py", line 343, in play_packet
    sendp( packet, iface=conf.iface )
  File "C:\Python27\lib\site-packages\scapy\sendrecv.py", line 302, in sendp
    socket = conf.L2socket(iface=iface, *args, **kargs)
  File "C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 259, in __init__
    self.ins = open_pcap(iface, 1600, self.promisc, 100, monitor=monitor)
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 856, in open_pcap
    if iface.ismonitor():
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 547, in ismonitor
    self._check_npcap_requirement()
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 527, in _check_npcap_requirement
    raise OSError("This operation requires Npcap.")
OSError: This operation requires Npcap.

**Comment by yuval9313** [comment]
You need to install Npcap on your computer
You can find a link an installer [here](https://nmap.org/npcap/)

You might also need Wireshark but first install this and report us if it work

**Comment by zaheersyed** [comment]
I have installed "Npcap 0.99-r1 installer". But Im still seeing the issue.

**Comment by gpotter2** [comment]
Thanks for reporting. This is a bug.
Will provide a fix very soon

**Comment by gpotter2** [comment]
Thanks !
This should be fixed with https://github.com/secdev/scapy/pull/1222
You may want to try this PR.

You surely had Winpcap installed: with this PR, you don't need to install npcap anymore.

Sorry for the inconvenient. We recently have had unstable changes performed

**Comment by zaheersyed** [comment]
Thank you for the fix.

So either Winpcap or Npcap is fine ?
I started with Winpcap and then I uninstalled it and installed Npcap.
With Winpcap uninstalled and Npcap installed, I was seeing the above error.

**Comment by gpotter2** [comment]
Having Winpcap and Npcap installed is not the best option.

I would recommand to have Npcap installed, rather than Winpcap, as it is way more updated and recent. 
However, I know nothing of their compatibility on Windows Servers.

Both of them will work fine with the fix.

Please watch out: when uninstalling Winpcap, the installation is not complete, and you need to perform several manual steps to uninstall it properly:
http://scapy.readthedocs.io/en/latest/installation.html#winpcap-npcap-conflicts
