### ISSUE TITLE
How can I access the default ethernet interface on windows in scapy? [question]

### ISSUE THREAD

**Issue by zaheersyed** [secdev/scapy#1227]
The IFACES object looks like this for me.
 {'data': {'{762EBD09-20AF-48E2-96AD-30B0AE76C826}': <NetworkInterface Npcap Loopback Adapter {762EBD09-20AF-48E2-
96AD-30B0AE76C826}>, '{F317E41B-F8EE-416B-A715-57A3EE680F96}': <NetworkInterface vmxnet3 Ethernet Adapter {F317E41B-F8EE-416B-A715-57A3EE680F96}>}}

I m trying to access eth0 so that I can use it in sendp().
My 'ipconfig' looks like this:

C:\Users\Administrator> ipconfig

Windows IP Configuration

Ethernet adapter eth0:

   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : XXX.XX.XXX.XX
   Subnet Mask . . . . . . . . . . . : XXX.XXX.XXX.X
   IPv4 Address. . . . . . . . . . . : XXX.XXX.X.XXX
   Subnet Mask . . . . . . . . . . . : XXX.XXX.XXX.XXX
   Default Gateway . . . . . . . . . : XXX.XX.XXX.X

Tunnel adapter isatap.{F317E41B-F8EE-416B-A715-57A3EE680F96}:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : XXXX::XXXX:XXX.XX.XXX.XX%16
   Link-local IPv6 Address . . . . . : XXXX::XXXX:XXX.XXX.X.XXX%16
   Default Gateway . . . . . . . . . :

Ethernet adapter Npcap Loopback Adapter:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : XXXX::XXXX:XXXX:XXXX:XXXX%18
   Autoconfiguration IPv4 Address. . : XXX.XXX.XXX.X
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Default Gateway . . . . . . . . . :

Tunnel adapter isatap.{762EBD09-20AF-48E2-96AD-30B0AE76C826}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   IPv6 Address. . . . . . . . . . . : XXXX:X:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX
   Link-local IPv6 Address . . . . . : XXXX::XXXX:XXXX:XXXX:XXXX%7
   Default Gateway . . . . . . . . . : ::

**Comment by gpotter2** [comment]
Duplicated https://github.com/secdev/scapy/issues/1206

**Comment by zaheersyed** [comment]
I dont see eth0 listed.

>>> IFACES
INDEX  IFACE                     IP             MAC
15     vmxnet3 Ethernet Adapter  172.xx.xxx.xx  00:50:16:11:A0:C1
18     Npcap Loopback Adapter    127.0.0.1      00:00:00:00:00:00

**Comment by gpotter2** [comment]
There is no eth0 on windows...

Please have a look on google
