### ISSUE TITLE
Documentation for setting RadioTap Fields

### ISSUE THREAD

**Issue by ZackAlfakir** [secdev/scapy#1228]
When creating a RadioTap Layer, it is clear how to set the fields that are in the header, but not any of the additional fields that are marked as present. Additionally, the Layer does not correctly calculate it's length, leading to packet alignment issues.

**Comment by gpotter2** [comment]
Hi ! Welcome to scapy

Please elaborate your issue so we can help you:
- provide your OS, Python version
- retry with latest scapy `pip install —pre scapy`
- provide code or a pcap
- provide a screenshot of wireshark with the malformed packet or similar

Thanks !

**Comment by ZackAlfakir** [comment]
OS: Ubuntu 16.04
Python: 3.5.2
Scapy: 89a077139b5328f2ba165a305602b65930418686

```
ping = Ether(dst=dst_mac, src=src_mac, type=0x800) / \
           IP(version=4, ihl=5, tos=0x0, len=84, id=50065, flags="DF", frag=0, ttl=64, proto="icmp",
              chksum=0xf3b4, src=src_ip, dst=dst_ip, options=[]) / \
           ICMP(type="echo-request", code=0, chksum=0x8e15, id=0x7a88, seq=0xb) / \           
 Raw(load=b'\xfa\x7f\x9dZ\x00\x00\x00\x00\x94\xa9\x04\x00\x00\x00\x00\x00\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./01234567')
```
( The above may not be fully copy/pastable due to text wrapping)

`wireshark([ping, RadioTap()/ping])`

![image](https://user-images.githubusercontent.com/2652713/37356544-a38fd08e-26bc-11e8-92f5-6c2c8cd12565.png)

You'll notice that on the one with the RadioTap layer, it has moved the bits over, pushing the MAC address back. Here is the details for each.

![image](https://user-images.githubusercontent.com/2652713/37356673-e3bc91e2-26bc-11e8-8e3f-43b17276d002.png)

![image](https://user-images.githubusercontent.com/2652713/37356699-f2b98894-26bc-11e8-9f81-d48082546a02.png)


While it may be that I am doing something wrong, it would be helpful if there was any documentation on RadioTap within Scapy. Particularly when to use it, and how to set the internal fields when they are marked as present in the bitmap.

**Comment by gpotter2** [comment]
You cannot bind `RadioTap` to `Ether`: it's not a valid packet.
What would, for instance, be a valid packet would be

`RadioTap()/Dot11()/LLC()/SNAP()/Ether()`

![image](https://user-images.githubusercontent.com/10530980/37370846-bca6d56c-270d-11e8-809c-3b9d84af4216.png)

**Comment by ZackAlfakir** [comment]
Thanks for the help. Is there any documentation out there that I can use to learn more about how to use RadioTap? Also, how does one set the fields in the RadioTap layer when present != 0? The only examples I have found so far are with present=0, but I need to set present to allow fields (which is clear) and then put those fields in the layer (which I can't find).

**Comment by oycillessen** [comment]
I think the radiotap is generate by only localhost ,is this right?

**Comment by gpotter2** [comment]
`RadioTap` is used on W-lan / wifi interfaces, as it’s the link layer used with it. It’s the lowest link layer as it contains multiple tags and stuff.

The WiFi interface might be cropping this layer, sometimes returning difrectly a “fake” `Ether()`, it even sometimes a `Dot11()` layer.

When you are sending / receiving a packet on the localist loop back interface, it uses `Loopback()`
