### ISSUE TITLE
wrpcap regression

### ISSUE THREAD

**Issue by bartex80** [secdev/scapy#1242]
`wrpcap('/tmp/empty.pcap', [])`
should write a pcap header but the file is empty instead

scapy==2.4rc5 is wrong, scapy==2.4rc4 and below was OK

**Comment by guedou** [comment]
confirmed.

**Comment by karpierz** [comment]
We observe the same issue.
In rc5 a writing of pcpap header has been (probably intentionally) removed from:
class RawPcapWriter.write(self, pkt):

@@ -13,7 +13,6 @@
                 try:
                     p = next(pkt)
                 except StopIteration:
-                    self._write_header(b"")
                     return
                 self._write_header(p)
                 self._write_packet(p)

**Comment by guedou** [comment]
Issue caused by 82e3214279fd8bb99a2f9cc1aaec8110813a762f

Here is a piece of code that could be used as a unit test:
```
from scapy.all import *
import os
import tempfile
filename = tempfile.mktemp(suffix=".pcap")
wrpcap(filename, [])
fstat = os.stat(filename)
assert fstat.st_size != 0
os.remove(filename)
```

**Comment by guedou** [comment]
@p-l- could you have a look?
