### ISSUE TITLE
In sendp() using an 'inter' value less than 0.001 results in the packets being sent out at max rate

### ISSUE THREAD

**Issue by tyler124** [secdev/scapy#1246]
When I use:
`sendp(packetList, iface=myIfaces[SCAPY_DEV], inter=0.001, verbose=False)`

My packets get sent out as expected, with a 0.001 second gap between packets

However, when I use:
`sendp(packetList, iface=myIfaces[SCAPY_DEV], inter=0.0009, verbose=False)`

I get a similar result as using inter=0, with there only being a .00024 gap between some packets. 

Is 0.001 intended to be the floor for the time between packets before just sending them at the max possible rate? If so, have an exception thrown when trying to pass an inter < 0.001, or specify the minimum value in the documentation?

**Comment by speakinghedge** [comment]
The inter(framegap - IFG) is just a sleep - the time required to build and send the frame is not taken into account - so the observable IFG will vary a lot (depending on the 'power' and utilization of your CPU, the structure/complexity of the frame). And even the call to sleep() will add some delta that depends on the underlying operating system.

But you can speedup sending frames a lot by
1. build all the frames before sending them or
2. use sendpfast (that pre-builds the stream and utilizes tcpreplay for sending the frames at a defined speed).

Did some measurement with a simple 512-byte frame (Ether/IP/Raw) that shows nicely the
possible speedup / the avg IFG in seconds:
```
sendp-10k.pcap - avg ifg: 0.0002752736
sendp-with-socket-10k.pcap - avg ifg: 0.0002793264
sendp-pre-build-10k.pcap - avg ifg: 0.0000041194
sendpfast-10k.pcap - avg ifg: 0.0000010448
```
Using naked `sendp` together with L2Socket and pre-build frames I was able to set the IFG using `sleep()` with a granularity of 0.0001s.

Depending on your requirements the sendpfast/tcpdump option could be the better solution.
You could even set the time between the frames manually per frame and tcpreplay will
use that information to calculate the IFG and send the frames accordingly. 

If the stock tcpdump provided by your distribution is not fast & accurate enough you
could rebuild it using more sophisticated driver frontend (e.g. Intel DPDK - needs a supported NIC) 
or even spent some $$$ on a Endace DAG card. Most of them offer a granularity of 15 or 7.5 nano seconds and nowadays you can get them for cheap (compared to the original prices, got a 4-port 7.5G4 for 80€ at enay).
