### ISSUE TITLE
Undefined name ' p' in _tls_aead_auth_decrypt()

### ISSUE THREAD

**Issue by cclauss** [secdev/scapy#1249]
Should this be __c__ instead of __p__?

$ python3 -m flake8 . --count --select=E9,F82 --show-source --statistics
```
./scapy/layers/tls/tools.py:199:9: F821 undefined name 'p'
    l = p.len - alg.nonce_explicit_len - alg.tag_len
        ^
./scapy/layers/tls/tools.py:201:44: F821 undefined name 'p'
    A = read_seq_num + struct.pack('!BHH', p.type, p.version, l)
                                           ^
./scapy/layers/tls/tools.py:201:52: F821 undefined name 'p'
    A = read_seq_num + struct.pack('!BHH', p.type, p.version, l)
                                                   ^
```

**Comment by guedou** [comment]
It looks like it. If you fix that could you also add a unit test?

**Comment by karpierz** [comment]
Fixed by #1269

**Comment by guedou** [comment]
Thanks a lot!

Could you try to add a unit test? This code is not tested that is why this issue was never discovered. You can find example in https://github.com/secdev/scapy/blob/6d5c078b8e2d85bbb244ded02e417d577842c0ce/test/tls.uts

Let me know if you need support.

**Comment by karpierz** [comment]
Done, but your help is needed.
Se my last comment in #1269

**Comment by karpierz** [comment]
PR is finished succesfully.

All another errors in layers/tls/tools module has been fixed.
All code in this module has been ported to Python3.
Tests are added for **all** functions in this module.

PR is ready for merge to the master.
