### ISSUE TITLE
IKEv2 handshake

### ISSUE THREAD

**Issue by user189** [secdev/scapy#1262]
Hello,

I'm learning how to use Scapy and in order to do so am trying to establish an IKEv2 handshake.

I have run into a similar issue expressed in Issue #1178, more precisely the Attribute field that stays empty (IKE_SA_INIT packet).
So far I have used a workaround by adding the attribute as raw data but it's not really practical.

I also try to create an IKE_AUTH initiator request, having received an IKE_SA_INIT response. To get a grasp of how to create the packet I tried to parse a packet I recorded from an IKEv2 exchange I did. However, when reading the resulting packet with Scapy, the structure is changed and it is read as an ESP packet.
```

###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 320
  id        = 20098
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = udp
  chksum    = None
  src       = 192.168.74.132
  dst       = 192.168.74.149
  \options   \
###[ UDP ]### 
     sport     = ipsec_nat_t
     dport     = ipsec_nat_t
     len       = 300
     chksum    = None
###[ ESP ]### 
        spi       = 0x0
        seq       = 640397260
        data      = d1a7a82f6159eb12308655562e2023080000000100000120230001049f3819641b0b3dbbf3c780d9e441bb2fd59695ed472bd4b7f956212ebd67bb4399fc94bd7dcd6e4168985e5518dbc1888c20d5ea43a46d4b406190a5538420edde10c716c1d1eeb62527dddcc865554a5921b753561da8ae811b0d4306b2f1bd9684cdd01d2221f8a1aea6d8580b1cccee369c9c013fe02d3fe4ae0fc0fd40841aaf2db2bb1a97cccab75ac85a8b96885a367b1fbc5bf0666bd57d6ec768157f0a2780bca05e87089a57ef62a7b9e513aff8d56754167578bb02a7726cb3683ab11855e30ff4f481de35551899045c6b18ff5fa77998921f38cf71af780b54d52b4463b3a963b27a2653ffeeab2d25cda6dabdca539c862ecf67cf9552933af0
```
If anyone has had experience dealing with IKEv2 handshake, feedback would be appreciated, thanks.

**Comment by guedou** [comment]
Could give use the following information?
- Scapy version
- Python version
- OS
- the packet that trigerred the issue

**Comment by user189** [comment]
- Scapy version : 2.4.0rc4.dev65
- Python version: 2.7
- OS: Kali 4.12.0
- Packet: 
The packet that I try to parse with Scapy is a regular IKE_AUTH packet:
![image](https://user-images.githubusercontent.com/34303662/37659471-6459d8bc-2c50-11e8-859e-66e19a36c860.png)

And I end up with the aforementioned result with IP/UDP/ESP.

**Comment by guedou** [comment]
Try:
```
load_contrib("ikev2")
p[UDP].decode_payload_as(IKEv2)
```

**Comment by user189** [comment]
Works for me, thank you!

**Comment by Zq1993Zq** [comment]
hello
  I'm try to  create an IKE_AUTH initiator request, and auth_type of IKEv2_payload_AUTH is ‘Shared Key Message Integrity Code’， the secret should be where? and load of IKEv2_payload_AUTH will be auto calculate？because accord to 2.15 on rfc7296,  load of IKEv2_payload_AUTH need the secret。
I hope help form you， thanks！
