### ISSUE TITLE
bridge_and_sniff functions suddenly stops

### ISSUE THREAD

**Issue by mmyxolidian** [secdev/scapy#1266]
When I execute my script, bridge_and_sniff function starts normally and suddenly gets stopped and program terminates. Sometimes it occurs some seconds after launching it, and some other times can be working properly for 1 hour and then get stopped.

**Comment by speakinghedge** [comment]
What scapy and python version is in use? What platform?
What is the purpose of the script? Can you add relevant code snippets (formatted)?
Does it terminate by raising an exception? If so - plz add the stacktrace here.
Could you plz add a brief description of your setup?

Are you sending any data inside the sniff callback? -> see #1190

**Comment by mmyxolidian** [comment]
So, the platform where Scapy Script is running is Ubuntu Server 17.10. Scapy current dev version (switched because in stable same thing happened). Python latest 2.7. The purpose of the script is to perform a transparent MITM attack by altering packets on the fly. 

Setup: enp0s8 is directly connected to a Win10 machine where ABB OPC server is installed. enp0s3 is directly connected to a mikrotik, where also ABB ac800m and a Win10 machine with ABB CCB are connected. 

The objective of the script is to filter Manufacturing Message Specification (MMS) packets and to alter them (purpose that I haven't achieved yet).

No exception is getting raised. The program terminates with a funny "bye!!" Here is relevant code:

`interfaces = {
	"plc-ccb": "enp0s3",
	"opc": "enp0s8"
	}

def is_mms_packet(pkt):
	ret = False
	if pkt.haslayer(TCP):
		if (pkt[TCP].sport == 102) or (pkt[TCP].dport == 102):
			ret = True
	return ret

def pkt_callback_PLC_OPC(pkt):
	ret = True
	if is_mms_packet(pkt):
		print pkt.show()
		#wrpcap("test-mms.pcap", pkt, append=True)
		#writePacketInDisk(pkt)
	#ret = performAttack(pkt)
	return ret

def pkt_callback_OPC_PLC(pkt):
	ret = True
	if is_mms_packet(pkt):
		print pkt.show()
		#wrpcap("test-mms.pcap", pkt, append=True)
		#writePacketInDisk(pkt)
	#ret = performAttack(pkt)
	return ret

def enable_bridge():
	print "hello!!"
	#while 1:
	bridge_and_sniff(interfaces["plc-ccb"], interfaces["opc"], xfrm12=pkt_callback_PLC_OPC, 
                        xfrm21=pkt_callback_OPC_PLC, count=0, store=0)
	#prn = lambda x: x.summary()
	print "bye!!"

if __name__ == "__main__":
	conf.verb=3
	conf.sniff_promisc=True
	enable_bridge()
	#testing()
`

**Comment by speakinghedge** [comment]
Code looks okay. As I'm currently forced to use a Windows box a can't try it right now (but later today) - but from my experience with #1190 I guess that your interfaces are catching some outgoing frames (e.g. IPv6 neigh stuff) and therefore they are removed silently (https://github.com/secdev/scapy/blob/master/scapy/sendrecv.py#L747). If no socket is left the b-n-s exits. You should try to apply https://github.com/secdev/scapy/pull/1251 and see if the issue persists. As always (if you are going to do some sniffing action) - disable all services on the used interfaces (no IPv6 support, DHCP, ...).

Side note: ABB + MMS sounds like IEC 61850. If you are going to do a MITM here you should address SMV and GOOSE first (way easier to do handle the MITM and you could trigger protection easily - much simpler than controlling a CBR via MMS). If this is an academical work you should also discuss MITM in context of IEC 62351 :smile:

**Comment by mmyxolidian** [comment]
Thank you so much :))

**Comment by mmyxolidian** [comment]
Apparently your workaround solved the problem, I really appreciate it. Regarding the side notes, this work is part of my PhD dissertation, so although they won't be considered in this WP (deadline in 2 weeks 😅), I may find it useful in near future. In conclusion, thanks so much again 😃

**Comment by guedou** [comment]
@mmyxolidian good luck for the deadline! Don't forget to credit Scapy if you used it. It is often used during PhDs but rarely cited =)

**Comment by guedou** [comment]
Fixed thanks to #1190

**Comment by daniel-leicht** [comment]
> So, the platform where Scapy Script is running is Ubuntu Server 17.10. Scapy current dev version (switched because in stable same thing happened). Python latest 2.7. The purpose of the script is to perform a transparent MITM attack by altering packets on the fly.
> 
> Setup: enp0s8 is directly connected to a Win10 machine where ABB OPC server is installed. enp0s3 is directly connected to a mikrotik, where also ABB ac800m and a Win10 machine with ABB CCB are connected.
> 
> The objective of the script is to filter Manufacturing Message Specification (MMS) packets and to alter them (purpose that I haven't achieved yet).
> 
> No exception is getting raised. The program terminates with a funny "bye!!" Here is relevant code:
> 
> ```
> interfaces = {
> 	"plc-ccb": "enp0s3",
> 	"opc": "enp0s8"
>   }
> 
> def is_mms_packet(pkt):
> 	ret = False
> 	if pkt.haslayer(TCP):
> 		if (pkt[TCP].sport == 102) or (pkt[TCP].dport == 102):
> 			ret = True
> 	return ret
> 
> def pkt_callback_PLC_OPC(pkt):
> 	ret = True
> 	if is_mms_packet(pkt):
> 		print pkt.show()
> 		#wrpcap("test-mms.pcap", pkt, append=True)
> 		#writePacketInDisk(pkt)
> 	#ret = performAttack(pkt)
> 	return ret
> 
> def pkt_callback_OPC_PLC(pkt):
> 	ret = True
> 	if is_mms_packet(pkt):
> 		print pkt.show()
> 		#wrpcap("test-mms.pcap", pkt, append=True)
> 		#writePacketInDisk(pkt)
> 	#ret = performAttack(pkt)
> 	return ret
> 
> def enable_bridge():
>        print "hello!!"
>        bridge_and_sniff(interfaces["plc-ccb"], interfaces["opc"], xfrm12=pkt_callback_PLC_OPC, 
>                         xfrm21=pkt_callback_OPC_PLC, count=0, store=0)
>        print "bye!!"
> 
> if __name__ == "__main__":
> 	conf.verb=3
> 	conf.sniff_promisc=True
> 	enable_bridge()
> 	#testing()
> ```

Hi @mmyxolidian, 

I'm searching the internet for AC 800M MMS capture files and can't find any. Excuse me for piggy backing this issue thread, but perhaps you have still have such PCAP that you can share? :)

Thanks you!
