### ISSUE TITLE
[Enhancement] MACsec: Support for Extended Packet Number (XPN)

### ISSUE THREAD

**Issue by g-mahieux** [secdev/scapy#1270]
Hello,

I am working with Scapy's MACsec implementation and found it very useful (thank you).

Unfortunately, it lacks support for XPN (Extended Packet Numbering) which roughly is an extension providing support for 64 bit packet numbers.
I am proposing to submit a patch implementing it, but I'd like the feedback of original authors about which direction to take. Options would be:
- modify the existing MACsecSA class to add a couple parameters which are only used when XPN is enabled (this is what I am working on at the moment). Most changes apply to "make_iv()" only.
- overload MACsecSA as MACsecSA_XPN (or something like that) and implement the differences there (sounds less user friendly to me)

I see there are some associated unit tests, thus standard test vectors from the specification's annexes could be implemented to ensure compliance.

Thank you for your feedback.

_Tagging users who have been active on Scapy's MACsec implementation: @guedou @qsn_

**Comment by g-mahieux** [comment]
Another point on which your input would be welcome:
With XPN, the packet number to store in MACsecSA is 64 bits, but in the MACsec packet the field is still 32 bit (for the 32 LSB). Thus the following options are possible:
- store a 64b PN in MACsecSA and only forward the 32b LSB to the packet in encap()
- store the additional 32 MSB bits in a separate field (xpn_msb) of MACsecSA
I am working with the first option at the moment but that can change if you request it.

**Comment by g-mahieux** [comment]
No suggestion/feedback? Should I just submit a PR?

**Comment by guedou** [comment]
We are busy with the 2.4.0 imminent release. It is currently better to submit a PR and discuss it.

**Comment by g-mahieux** [comment]
Will do, thanks!
