### ISSUE TITLE
Remove the queso module?

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1274]
While trying to write tests for the queso module, I could not easily find the source code online. It seems that the project is now abandoned. Shall we remove this module?

**Comment by gpotter2** [comment]
The version [that we advise to get in the documentation](http://scapy.readthedocs.io/en/latest/installation.html#optional-software-for-special-features) indeed seems a little old...

![image](https://user-images.githubusercontent.com/10530980/37724599-710d4670-2d31-11e8-9340-c12a1463569c.png)
