### ISSUE TITLE
TCP checksum computation function

### ISSUE THREAD

**Issue by H1ghl4nd3r** [secdev/scapy#128]
Hi,

There is no "user-friendly" function to compute tcp checksums in `scapy/utils.py`, the only way I could find to do it was with the same method than in `scapy/layers/inet.py` (i.e. packing the pseudo header and calling `checksum(pshdr+p`)). I think it would be useful to have one as I seem not to be the only one to want it (several questions have been asked on SO) and TCP checksum computation is not familiar to everyone. Something like `tcp_checksum(ip_src, ip_dst, proto, pkt)`. What do you think?

**Comment by guedou** [comment]
An alternative could be to add a docstring to the `checksum()`  function. This could be a good way to explain how to use this function outside of Scapy to compute IP, IPv6 and TCP checksums. I would love to review a PR implementing this idea.

I believe that users will find it more useful.

**Comment by guedou** [comment]
An example was added in #691
