### ISSUE TITLE
Feature Request: Allow output control for sendp, sendpfast, family.

### ISSUE THREAD

**Issue by ZackAlfakir** [secdev/scapy#1281]
Currently when using `sendp` or `sendpfast` there is a lot of output to console. The output for `sendp` can be silenced with:

```
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)
conf.verb = 0
```

It would be nice if there were a simpler way to make it so we can control where scapy output and errors go.

However, the output for `sendpfast` cannot be silenced because of this line:

```
subprocess.check_call(argv)
```

If we were allowed other inputs to the `sendpfast` function, we could do something like:

```
subprocess.check_call(argv, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
```

This could be fixed with allowing a `**kwargs` argument. The user could input any dictionary into `sendpfast` and have variables such as `"stdout": subprocess.DEVNULL` exploded into the subprocess call with `subprocess.check_call(argv, **kwargs)`.

**Comment by guedou** [comment]
It will be more consistent to output the result of subprocess to logging. Do you want to submit a PR?
