### ISSUE TITLE
cls argument in issubclass() of ntp.py must be a class

### ISSUE THREAD

**Issue by LennyJ** [secdev/scapy#1287]
I'm starting a new issue that is a duplicate of #1087 
That issue got closed and I wasn't sure my comment on it would still be noticed.

**Comment by gpotter2** [comment]
Linked to https://github.com/secdev/scapy/issues/1087#issuecomment-375977982

Hi!

Please provide some examples / pcaps / anything that is related to your issue or crashes, so that we can help you.

Please also provide your python version and scapy version (for the latter, if you are not using the latest GitHub one, please download it)

Thanks!

**Comment by LennyJ** [comment]
I found an online example .pcap that produces the same error.
The pcap file can be downloaded via the [Wireshark Website](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=NTP_sync.pcap)

`pcap = rdpcap(pcap_file_path)`
`sessions = pcap.sessions()`
should be enough to reproduce the error.

I am using Python version:
`3.5.3`
I am using Scapy version:
`2.4.0rc5`

**Comment by karpierz** [comment]
Already fixed. Try to use current master.

**Comment by LennyJ** [comment]
The current master does indeed work correctly.
I had Pycharm managing my packages. While I was using version 2.4.0rc5 it wasn't the latest build corresponding to master.

Thanks a lot :)

**Comment by karpierz** [comment]
...the difference between rc5-1 and rc5-76 can be significant ;).

**Comment by gpotter2** [comment]
Hehe, if you keep adding stuff (I'm also a culprit), we won't get 2.4.0 soon ^^

**Comment by LennyJ** [comment]
Yes, you are right. I should have checked the exact version more thoroughly.
I apologize for the inconvenience :)

**Comment by karpierz** [comment]
@gpotter2 I am from the beginning only "adding" stuff mostly for achieve my/our customers dream named FBC ;)

**Comment by karpierz** [comment]
@LennyJ Could you please close this issue?
