### ISSUE TITLE
Hope to add monitor ssid function

### ISSUE THREAD

**Issue by Evilmass** [secdev/scapy#1296]
**packet32.h**

    struct _PACKET_OID_DATA {
        ULONG Oid;                  ///< OID code. See the Microsoft DDK documentation or the file ntddndis.h
                                    ///< for a complete list of valid codes.
        ULONG Length;               ///< Length of the data field
        UCHAR Data[1];              ///< variable-lenght field that contains the information passed to or received
                                    ///< from the adapter.
    };
    typedef struct _PACKET_OID_DATA PACKET_OID_DATA, *PPACKET_OID_DATA;

**ntddndis.h:**

#define NDIS_802_11_LENGTH_SSID         32
#define OID_802_11_SSID                 0x0D010102

    typedef struct _NDIS_802_11_SSID
    {
        ULONG   SsidLength;         // length of SSID field below, in bytes;
                                    // this can be zero.
        UCHAR   Ssid[NDIS_802_11_LENGTH_SSID];           // SSID information field
    } NDIS_802_11_SSID, *PNDIS_802_11_SSID;

    BOOLEAN
    pktSet802_11SSID(LPADAPTER ptrAdap, PNDIS_802_11_SSID ptrSsid)
    {
        unsigned char       buffer[sizeof(PACKET_OID_DATA) + sizeof(NDIS_802_11_SSID)];
        PPACKET_OID_DATA    ptrOid;
        ptrOid = (PPACKET_OID_DATA)buffer;
        ptrOid->Oid     = OID_802_11_SSID;
        ptrOid->Length  = sizeof(NDIS_802_11_SSID);
        memcpy(ptrOid->Data, ptrSsid, sizeof(NDIS_802_11_SSID));
        if (!PacketRequest(ptrAdap, TRUE, ptrOid))
          return FALSE;
        return TRUE;
    }

**Comment by gpotter2** [comment]
Hi!
Could you elaborate what you mean, please? Wasn't able to guess your question from that piece of code :/

Thanks!

**Comment by Evilmass** [comment]
@gpotter2 
i mean, can scapy monitor network adaptor's SSID from ndis drivers?

**Comment by guedou** [comment]
It cannot actually do that. Unless you explain a legitimate use, it probably never will.

**Comment by test-black** [comment]
i am trying to write a gameserver platform for playstation portable, and need those package to finish data exchange
I know that the request is very unreasonable, but still hope this function can be added

**Comment by Evilmass** [comment]
i am trying to write a gameserver platform for playstation portable, and need those package to finish data exchange
I know that the request is very unreasonable, but still hope this function can be added
