### ISSUE TITLE
Npcap: OEM request

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1297]
Hi,
We are currently running our Appveyor tests with a with an old version of Npcap, which used to support the /silent install.

I've seen on their license page:

https://github.com/nmap/npcap/blob/master/LICENSE

> Free and open source software producers are also welcome to contact us
> for redistribution requests.  However, we normally recommend that such
> authors instead ask your users to download and install Npcap themselves.

That we were theoretically able to ask them for a way to get it installed on the Appveyor servers.

I asked feydor (npcap team member) a few times and got no answer... It would be great if a member of secdev could ask them on their "official" email (sales@nmap.com) to get either a license or similar so that we can update the tests.

As a reminder, we are encouraging Windows users to migrate to Npcap when Winpcap is detected, so it would be nice of them to share this with us...

Thanks!

**Comment by guedou** [comment]
@phil777 got a positive answer by email =)
