### ISSUE TITLE
Scapy not sniffing packets on running code in python file

### ISSUE THREAD

**Issue by sipian** [secdev/scapy#1298]
When I am sniffing with scapy from `sudo python3` interpreter

    from scapy.all import *
    packets = sniff(iface="enp7s0", filter="icmp", count=10, prn=lambda x:x.sprintf("{IP:%IP.src% -> %IP.dst% :: %IP.seq% \n}"))
I am getting the following output of prn,<br>
\<My-IP\> -> 172.217.26.174 :: 331
172.217.26.174 -> \<My-IP\> :: 331
\<My-IP\> -> 172.217.26.174 :: 332
172.217.26.174 -> \<My-IP\> :: 332
\<My-IP\> -> 172.217.26.174 :: 333
172.217.26.174 -> \<My-IP\> :: 333

But on writing this in a python file and running it with `sudo python3 file.py`, I am getting empty new-lines as output of prn.

`pip3 show scapy` is giving Version as **git-archive.devf89055dac**

**Comment by guedou** [comment]
You need to print the output of sprints. Please read the online help.
