### ISSUE TITLE
How can I make a unit-test dependant on python3 with tox

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#1299]

**Comment by polybassa** [comment]
Since the CI-environment changed to tox, some of my unit-tests are failing, because I can not make them dependant on either python2 or python3

**Comment by guedou** [comment]
What is your exact issue? You can test the Python flavour using `six.PY2` or `six.PY3`.

For example, see the output of `git grep six.PY test/*.uts`.

**Comment by polybassa** [comment]
Thanks
