### ISSUE TITLE
2.4.0-rc5 Unusable in 32-bit Windows XP SP3

### ISSUE THREAD

**Issue by PorscheMonty** [secdev/scapy#1309]
Hello there. This is what I get as soon as I run_scapy:

"WARNING: No match between your pcap and windows network interfaces found. You probably won't be able to send packets. Deactivating unneeded interfaces and restarting Scapy might help. Check your winpcap and powershell installation, and access rights.

WARNING: No default IPv4 routes found. Your Windows release may no be supported and you have to enter your routes manually"

What could possibly be causing this, assuming XP support has not been deliberately and silently dropped? What can I do to get around t? 2.3.3 works perfectly fine on the exact same machine.

Best regards and sorry for the inconveniences.

**Comment by gpotter2** [comment]
Hello !

Could you please report the result of the following commands, launched from scapy’s Shell:

```
from scapy.arch.windows import _read_routes_xp; _read_routes_xp()
```
```
import plateform; platform.release()
```

Very sorry for the inconvenience: we have been doing many changes to the routing system recently, to support IPv6, windows 10... and could not test it on windows XP

**Comment by gpotter2** [comment]
Thanks for submitting !
It has been fixed in https://github.com/secdev/scapy/pull/1314

**Comment by PorscheMonty** [comment]
![scapy](https://user-images.githubusercontent.com/10228056/38276023-4b2e0e2e-3783-11e8-8d9f-cc03ba8e5535.png)
Up and running, guys!
Thank you so much.
