### ISSUE TITLE
fragmented response not parsed

### ISSUE THREAD

**Issue by gumblr** [secdev/scapy#131]
Scapy does not parse fragmented answers correctly. A minimal working example is attached.
[scapy.fragmented.responses.github.txt](https://github.com/secdev/scapy/files/231919/scapy.fragmented.responses.github.txt)

**Comment by guedou** [comment]
Scapy does not support fragmented (IPv4 or IPv6) packets out of the box, as the core logic is to send a request and wait for a response.

You need to implement the fragmentation logic yourself. A good start is available in this document https://www.sans.org/reading-room/whitepapers/detection/ip-fragment-reassembly-scapy-33969
