### ISSUE TITLE
L2ListenTcpdump fail

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1318]
The `FIXME_py3` flag was lost during tox migration, explaining why we see such failures

```
= Test L2ListenTcpdump socket
~ netaccess FIXME_py3

# Often (but not always) fails with Python 3
import time
for i in range(10):
    read_s = L2ListenTcpdump(iface=conf.iface)
    out_s = conf.L2socket(iface=conf.iface)
    time.sleep(5)  # wait for read_s to be ready
    icmp_r = Ether()/IP(dst="secdev.org")/ICMP()
    res = sndrcv(out_s, icmp_r, timeout=5, rcv_pks=read_s)[0]
    read_s.close()
    out_s.close()
    time.sleep(5)
    if res:
        break

response = res[0][1]
assert response[ICMP].type == 0
```

Completly forgot about it, this ages from python 3 migration.

I cannot reproduce it on my Windows machine :/ Should be able to in a week.
Would be great if someone could investigate in the mean time

**Comment by guedou** [comment]
#1320 will temporary fix the failing test. You can revert it if you find a proper fix.

**Comment by guedou** [comment]
@gpotter2 shall we flag this for v2.4.3? Otherwise we might want to close this issue.

**Comment by p-l-** [comment]
I think #1320 is enough. That's a corner case on Python 2, so...
