### ISSUE TITLE
IP alias route issue

### ISSUE THREAD

**Issue by hheennrryy21** [secdev/scapy#1319]
On Linux, when having an interface with two ip addresses, scapy is not able to map the addresses correctly. Therefore, when trying to connect to some foreign address, scapy chooses the wrong source address.

**Procedures:**

1. Run this 

`conf.route`

2. Output
```
 Network      Netmask        Gateway     Iface            Output IP     Metric
0.0.0.0      0.0.0.0        10.128.0.6  eth0             10.128.1.199  100
10.128.0.0   255.255.252.0  0.0.0.0     eth0             10.128.1.199  100
127.0.0.0    255.0.0.0      0.0.0.0     lo               127.0.0.1     1
169.254.0.0  255.255.0.0    0.0.0.0     eth0             10.128.1.199  1000
172.17.0.0   255.255.0.0    0.0.0.0     docker0          172.17.0.1    0
172.18.0.0   255.255.0.0    0.0.0.0     br-e60690d47946  172.18.0.1    0
192.168.9.0  255.255.255.0  0.0.0.0     eth0             10.128.1.199  0
```
If you look at eth0, it has the following configuration. 
```

 Network      Netmask        Gateway     Iface            Output IP     Metric
192.168.9.0  255.255.255.0  0.0.0.0     eth0             10.128.1.199  0
10.128.0.0   255.255.252.0  0.0.0.0     eth0             10.128.1.199  100
```

This is incorrect. It should be like so.

```

 Network      Netmask        Gateway     Iface            Output IP     Metric
192.168.9.0  255.255.255.0  0.0.0.0     eth0             192.168.9.67  0
10.128.0.0   255.255.252.0  0.0.0.0     eth0             10.128.1.199  100
```

ip addr results

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:dd:7f:d0 brd ff:ff:ff:ff:ff:ff
    inet 10.128.1.199/22 brd 10.128.3.255 scope global dynamic eth0
       valid_lft 80160sec preferred_lft 80160sec
    inet 192.168.9.67/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e484:21d4:a58:9535/64 scope link 
       valid_lft forever preferred_lft forever
```

The route tables are intact, and have no issues. This is confirmed by pinging a foreign address from the Linux command line.

If I want scapy to work, I have to supply a "src" field with the interface address.

This does not work.
`sr(IP(dst="192.168.9.1")/ICMP())`

This does work.
`sr(IP(dst="192.168.9.1", src="192.168.9.67")/ICMP())`

**Comment by guedou** [comment]
Which Scapy version are you using? Could you try again with 2.4.0 or current master ?

**Comment by hheennrryy21** [comment]
Hi guedou, thank you for responding. I am using scapy-2.4.0.  I just checked and I have the latest from git. scapy (2.4.0.dev33).

**Comment by hheennrryy21** [comment]
It looks like scapy is using the first address the interface was configured with for the "Output IP" in conf.route. The additional IP addresses are ignored.

**Comment by guedou** [comment]
We fixed a similar issue last year. Could you provide:
- your kernel version
- the output of /proc/net/route

**Comment by guedou** [comment]
IP aliasing is an obsolete Linux feature (https://www.kernel.org/doc/Documentation/networking/alias.txt). You need to be careful when using them =)

If I understand correctly, you used `ip addr add 192.168.3.56/24 dev eth0` without the `label` argument. If correct, I can try to investigate and find a fix for Scapy.

**Comment by hheennrryy21** [comment]
Yes exactly. I used IP alias without the label argument. Thanks for the help!

**Comment by gpotter2** [comment]
@guedou So what should we do with this issue ?

**Comment by guedou** [comment]
I do not remember everything. But, I think that I did not manage to find a fix =/

**Comment by gpotter2** [comment]
If IP aliasing is the obstacle, and obsolete, we could consider simply not supporting it :/

**Comment by guedou** [comment]
@hheennrryy21 did you find a solution?

**Comment by hheennrryy21** [comment]
IP aliasing is indeed obsolete feature (e.g. eth0:1, wlan1:2), but multiple IP address support for interfaces is still something very common in the networking field. Scapy can't cope with this yet. This can be done since netlink does indeed provide this information.  For example, one popular project, pyroute2, is able to pull two IP addresses from a single interface.

**Comment by guedou** [comment]
Could you provide an example (besides aliasing) of something that does not work? Thanks.

**Comment by hheennrryy21** [comment]
At the moment I have not encountered any other issues :) Thanks.

**Comment by guedou** [comment]
Thanks! I will close the issue =)
