### ISSUE TITLE
[Enhancement]How to add sip protocol layer in scapy?

### ISSUE THREAD

**Issue by Sean2379607955** [secdev/scapy#1323]
I hope to add sip and rtp layer in scapy.
RTP is easy to decode.
But for SIP payload, there is text with split character, like : ; \r \n.
I not found split character method in document of adding new protocol.
Can you help for sip decoding?

**Comment by speakinghedge** [comment]
> I hope to add sip and rtp layer in scapy.

RTP is already part of scapy. you can find it here: *scapy/layers/rtp.py*

>But for SIP payload, there is text with split character, like : ; \r \n.
I not found split character method in document of adding new protocol.

The way SIP represents the data is completely different from the way scapy works.

Scapy focuses on binary protocols build from a set of atomic types (so they are easy to model, parse and generate).

SIP is based entirely on text - and in scapy text finds its expression only in Str* fields (e.g. StrField) that won't add any further semantic to the text after the data was dissected. In other words: There is no support for parsing text in scapy. In theory you could implement SIP by hacking down the BNF - but based on the aspect that your lifetime is limited...

> Can you help for sip decoding?

First check the web for ready-to-use SIP parser. If this won't bring up something useful...

You can find a list of BNF parsers/generators [here](https://wiki.python.org/moin/LanguageParsing). You could start with a small subset of all possible messages. Strip down the BNF from the RFC to your needs, fire up the generator and feed the generated parser with the payload from a TCP resp. UDP (port 5060) flow. If this works - call me back and I will help you to integrate this somehow into a 'dissect only but somehow real' SIP layer.

**Comment by gpotter2** [comment]
@speakinghedge You’re absolutely right.

Scapy may, in a quite future, support a few text protocols such as basic html, sip or rtc, but it would require brand new special text dissecting mechanics (to be reusable), which is not on the todo list for now.

**Comment by Kicey** [comment]
> [@speakinghedge](https://github.com/speakinghedge) You’re absolutely right.
> 
> Scapy may, in a quite future, support a few text protocols such as basic html, sip or rtc, but it would require brand new special text dissecting mechanics (to be reusable), which is not on the todo list for now.

Well, is there any progress?
