### ISSUE TITLE
getattr() in volatile.py throws an AttributeError when str() or hexdump() is used on fuzz packet

### ISSUE THREAD

**Issue by bsrivalli3012** [secdev/scapy#1325]
Hello, 
I have recently installed Scapy to use it to fuzz a CoAP server. I found a few threads related to this by @bsmelo  and tried to recreate the results by building the fuzz packets the exact same way. But when I try to convert it into a string using str(), I get an AttributeError when the getattr() function in volatile.py is called. 
I have installed the latest version of scapy from the secdev/scapy repository.
I have not modified any of the files in scapy (coap.py , utils.py , volatile.py etc) Please help me identify the source of this error.

$ sudo python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> from scapy.contrib.coap import *
>>> 
>>> 
>>> 
>>> conf.L3socket = L3RawSocket
>>> 
>>> 
>>> fuzz_pattern = fuzz(CoAP(ver=1L, type=RandNum(0, 1), code=RandNum(0, 4), token=RandBin(RandNum(0, 8)), options=[(11L, 'core')], paymark='\xff'+str(RandBin())))
>>> 
>>> s = str(fuzz_pattern)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 350, in __str__
    return str(self.build())
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 460, in build
    p = self.do_build()
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 441, in do_build
    self = next(iter(self))
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 828, in loop
    for x in loop(todo[:], done):
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 820, in loop
    elt = self.getfieldval(eltname)
  File "/usr/local/lib/python2.7/dist-packages/scapy/contrib/coap.py", line 240, in getfieldval
    if v:
  File "/usr/local/lib/python2.7/dist-packages/scapy/volatile.py", line 127, in __nonzero__
    return bool(self.value)
  File "/usr/local/lib/python2.7/dist-packages/scapy/volatile.py", line 89, in __getattr__
    return getattr(self._fix(), attr)
AttributeError: 'int' object has no attribute 'value'
>>>

**Comment by bsrivalli3012** [comment]
@bsmelo @guedou Marking you on this issue since I have been following the issues related to fuzzing CoAP server using scapy that you have resolved previously. Thanks in advance :)

**Comment by guedou** [comment]
Please upgrade to the latest Scaly version. It seems that you are using an old one.

**Comment by bsrivalli3012** [comment]
Thanks for the prompt response. I have installed scapy using the pip2 command. Therefore I am assuming it is the latest development version that is being installed. I have also upgraded it just to be sure using git pull. I get the same error as before. 
![attributeerror](https://user-images.githubusercontent.com/33404977/38570604-428facb2-3cbc-11e8-9d03-66d5621503af.png)

**Comment by bsmelo** [comment]
I can't reproduce your issue either, could you please:
- Check your scapy version?
```
 $ scapy
Welcome to Scapy (2.3.3.dev493)
>>>
```
- Try from outside the scapy folder?
```
 $ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> from scapy.contrib.coap import *
>>> conf.L3socket = L3RawSocket
>>> fuzz_pattern = fuzz(CoAP(ver=1L, type=RandNum(0, 1), code=RandNum(0, 4), token=RandBin(RandNum(0, 8)), options=[(11L, 'core')], paymark='\xff'+str(RandBin())))
>>> s = str(fuzz_pattern)
>>> 
```

**Comment by bsrivalli3012** [comment]
Hey, 
Scapy version : 2.4.0
I have tried running it from outside the scapy folder. Same error occurs. 
I am not sure if there are any support modules that need to be installed along with scapy. Do you think I am missing any python packages needed ?

**Comment by gpotter2** [comment]
Fixes

**Comment by bsrivalli3012** [comment]
Thanks a lot, everyone :) The issue is resolved.
