### ISSUE TITLE
I'm not receiving any packets with sr1()

### ISSUE THREAD

**Issue by suryax04** [secdev/scapy#1327]
I'm on a armv7 nexus 5..my iface = "rmnet0"

Here's what I did :

s = IP()

s.src = "My Ip"

a.dst = "Destination IP"

The destination IP address is a random IP address that I picked.

sr1(src,dst)

Sent 1 packet..

It gives me 0 answers but 1000+ packets received..

What am I doing wrong ?

Thank you .

**Comment by guedou** [comment]
You are not using Scapy correctly. Please have a look a the documentation.

**Comment by suryax04** [comment]
Okay..I'll check it out thoroughly.. thank you .
