### ISSUE TITLE
Will scapy support random seed in RandNum?

### ISSUE THREAD

**Issue by dark-lbp** [secdev/scapy#133]
Some time i use scapy to fuzz, but by default RandInt or RandShort didn't have the seed.If i got a crash after fuzz,  some time i can't recurrence it again,i think it's not good for fuzz...
so I tried to add random seed support to volatile.py, cause i didn’t know scapy verymach, there might be some better way to do this .
[volatile.py.txt](https://github.com/secdev/scapy/files/235737/volatile.py.txt)

**Comment by guedou** [comment]
It should word fine if you set the seed using `random.seed`. The following example builds the same _random_ IPv6 packets.

```python
>>> random.seed(2807); IPv6(str(fuzz(IPv6())))
WARNING: No route found for IPv6 destination 0c3f:47ab:8fa8:023f:6594:ed94:412f:eaa6 (no default route?)
<IPv6  version=11L tc=184L fl=490160L plen=0 nh=141 hlim=150 src=:: dst=c3f:47ab:8fa8:23f:6594:ed94:412f:eaa6 |>
>>> random.seed(2807); IPv6(str(fuzz(IPv6())))
WARNING: No route found for IPv6 destination 0c3f:47ab:8fa8:023f:6594:ed94:412f:eaa6 (no default route?)
<IPv6  version=11L tc=184L fl=490160L plen=0 nh=141 hlim=150 src=:: dst=c3f:47ab:8fa8:23f:6594:ed94:412f:eaa6 |>
```

However, keep in mind that some fields do not return random values. As Scapy is not a fuzzing framework, you might need to patch Scapy depending on your fuzzing case. For example, the NTP times are not random but change at every call.

```python
>>> random.seed(2807); NTP(str(fuzz(NTP())))
<NTP  leap=longminute version=7L mode=client stratum=184L poll=30L precision=101L delay=60820.6775665 dispersion=36254.9091797 id=9.159.140.135 ref=1139228226.48 orig=Thu, 28 Apr 2016 09:35:52 +0000 recv=37710615.5607 sent=Thu, 28 Apr 2016 09:35:52 +0000 |>
>>> random.seed(2807); NTP(str(fuzz(NTP())))
<NTP  leap=longminute version=7L mode=client stratum=184L poll=30L precision=101L delay=60820.6775665 dispersion=36254.9091797 id=9.159.140.135 ref=1139228226.48 orig=Thu, 28 Apr 2016 09:35:53 +0000 recv=37710615.5607 sent=Thu, 28 Apr 2016 09:35:53 +0000 |>
```
