### ISSUE TITLE
Create packet with raw bytes as str

### ISSUE THREAD

**Issue by ZackAlfakir** [secdev/scapy#1334]
I was wondering if this is a possibility with scapy.

I have a string that looks like so: 
`000026002f4000a0200800a0200800001b2db7ec0100000010308f09c000cb000000c300cb01c4007c0018742eb7cf16c3cabcb2` (type str)

And I want to convert it into a scapy packet. I know I can do this with a string that looks like this:
`b'\x00\x00&\x00/@\x00\xa0 \x08\x00\xa0 \x08\x00\x00\x1b-\xb7\xec\x01\x00\x00\x00\x100\x8f\t\xc0\x00\xcb\x00\x00\x00\xc3\x00\xcb\x01\xc4\x00|\x00\x18t.\xb7\xcf\x16\xc3\xca\xbc\xb2'` (type bytes)

So is there a way to either plug in the top string, or convert the top string into the scapy-compatible one?

**Comment by ZackAlfakir** [comment]
In python2 this is possible with:
```
x = 000026002f4000a0200800a0200800001b2db7ec0100000010308f09c000cb000000c300cb01c4007c0018742eb7cf16c3cabcb2
RadioTap(x.decode('hex'))
```

However, this does not seem to work in Python3:

```
In [290]: d
Out[290]: '000026002f4000a0200800a0200800001b2db7ec0100000010308f09c000cb000000c300cb01c4007c0018742eb7cf16c3cabcb2'

In [291]: RadioTap(d.decode('hex'))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-291-27aa25d5f027> in <module>()
----> 1 RadioTap(d.decode('hex'))

AttributeError: 'str' object has no attribute 'decode'

```

**Comment by ZackAlfakir** [comment]
The solution was to do the following:

```
import codecs
d = '000026002f4000a0200800a0200800001b2db7ec0100000010308f09c000cb000000c300cb01c4007c0018742eb7cf16c3cabcb2'
RadioTap(codecs.decode(d, 'hex'))
```

**Comment by ZackAlfakir** [comment]
Reopened just because I wanted to know if this is expected behavior or not.

**Comment by gpotter2** [comment]
This is python 3 specific, not scapy. (Not related to scapy)

Have a look at `scapy.compat.py` Whig contains useful compatibility functions such as `hex_bytes`

Regards,
