### ISSUE TITLE
sniff not properly reading QinQ

### ISSUE THREAD

**Issue by adrian62** [secdev/scapy#1335]
I use the sniff function to listen on a trunk interface that receives a mix of tagged (VLAN 802.1q) frames and double-tagged (QinQ) frames.

    >>> e8loc=sniff(iface='ens8',count=6,filter='not stp')
    >>> e8loc.summary()
    Ether / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw

The captured frames  are actually the ones double-tagged on the wire, and they are shown as single tagged with the inner tag.

    >>> e8loc[0]
    <Ether  dst=01:00:5e:00:00:05 src=52:54:00:0d:18:9f type=0x8100 |<Dot1Q  prio=6 id=0 vlan=2051 type=0x800 |<IP  version=4 ihl=5 tos=0xc0 len=76 id=1261 flags= frag=0 ttl=1 proto=ospf chksum=0xfd8b src=198.18.16.9 dst=224.0.0.5 options=[] |<Raw  load='\x02\x01\x00,\xc6\x12\x00\x01\x00\x00\x00\xe6$\xa9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xfc\x00\n\x12\x01\x00\x00\x00(\x00\x00\x00\x00\x00\x00\x00\x00\xff\xf6\x00\x03\x00\x01\x00\x04\x00\x00\x00\x01' |>>>>

If I capture packets using tcpdump and save them to a file, and then load the file into scaPy all is well. I can see both single and double tagged frames and all the layers are present.

    >>> e8=rdpcap('2vlan.pcap')
    >>> e8.summary()
    Ether / Dot1Q / 198.18.16.10 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.10 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / 198.18.16.10 > 224.0.0.5 ospf / Raw
    Ether / Dot1Q / Dot1Q / 198.18.16.9 > 224.0.0.5 ospf / Raw

I see both the frames wha single tag (originating from IP address ending in .10) as well as the double tagged ones, and the layers appear correctly in the buffers:

    >>> e8[0]
    <Ether  dst=01:00:5e:00:00:05 src=52:54:00:d6:9f:9e type=0x8100 |<Dot1Q  prio=0 id=0 vlan=2001 type=0x800 |<IP  version=4 ihl=5 tos=0xc0 len=64 id=23241 flags= frag=0 ttl=1 proto=ospf chksum=0xa7ba src=198.18.16.10 dst=224.0.0.5 options=[] |<Raw  load='\x02\x01\x00,\n\x00c\x0b\x00\x00\x00\xe6\xb7\x94\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xfc\x00\n\x02\x01\x00\x00\x00(\xc6\x12\x10\n\x00\x00\x00\x00' |>>>>
    >>> e8[1]
    <Ether  dst=01:00:5e:00:00:05 src=52:54:00:0d:18:9f type=0x8100 |<Dot1Q  prio=6 id=0 vlan=2001 type=0x8100 |<Dot1Q  prio=6 id=0 vlan=2051 type=0x800 |<IP  version=4 ihl=5 tos=0xc0 len=76 id=7575 flags= frag=0 ttl=1 proto=ospf chksum=0xe4e1 src=198.18.16.9 dst=224.0.0.5 options=[] |<Raw  load='\x02\x01\x00,\xc6\x12\x00\x01\x00\x00\x00\xe6$\xa9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xfc\x00\n\x12\x01\x00\x00\x00(\x00\x00\x00\x00\x00\x00\x00\x00\xff\xf6\x00\x03\x00\x01\x00\x04\x00\x00\x00\x01' |>>>>>

Also, just a nuisance that I can't get the second tag as follows, it always returns the outer tag:

    >>> e8[1].getlayer(Dot1Q).vlan
    2001
    >>> e8[1].getlayer(Dot1Q).getlayer(Dot1Q).vlan
    2001

However I can get it like this:

    >>> e8[1].getlayer(1).vlan
    2001
    >>> e8[1].getlayer(2).vlan
    2051

Last, Scapy is awesome and I am grateful for it.

**Comment by guedou** [comment]
On Linux, Scapy can not currently sniff 802.1Q. It is an open issue #969 that we will fix. The best alternative is to sniff using the pcapy, see https://github.com/secdev/scapy/issues/1289

You want to use `p[Dot1Q] `or `p[Dot1Q:2]` to access the 802.1Q layers.
