### ISSUE TITLE
Scapy.net: create project ?

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1339]
What should we do about scapy.net?

There are different ways we could update the website:
- keep a text website
- make a fancy website, in the style of https://scrapy.org/ (obviously different, and surely not as promotable "fast and powerful" -_-, but smooth)

Tons of things should be updated, so i think it would be a good idea to create a Project with the TODO-list.

What's your opinion @guedou @p-l- ?

**Comment by guedou** [comment]
Our goal was to have a new fancy website when releasing v2.4.0. We are not exactly there =)

`scapy.net` is currently hosted on github pages and distributed thanks to Cloudflare. I would like to use a static web site generator like Jekyll or Hugo to obtain a result like:
- https://deanattali.com/beautiful-jekyll/
- https://themes.gohugo.io/kube/
- https://uppy.io

A nice and simple landing page can do the trick. It is important that we describe the Python3 port and that Scapy can easily be installed.

Unfortunately, I did not find time to work on this =/

**Comment by guedou** [comment]
Thnaks to @gpotter2 we have a fancy website =)
