### ISSUE TITLE
send packets not showing up in wireshark

### ISSUE THREAD

**Issue by stacksreg123** [secdev/scapy#1341]
Hi here is my code:
```
#!/usr/bin/env python3
from scapy.all import sniff, send

def spoof_and_send(packet):
	packet[0][1].dst = '192.168.0.5'
	send(packet)

packets = sniff(filter='udp and portrange 6000-7999', prn=spoof_and_send)
```

I'm trying to spoof the destination IP and send it.
In console it keeps saying "1 Packet has been sent". 
I cant see the packages on wireshark though.

**Comment by guedou** [comment]
Commenting `packet[0][1].dst = '192.168.0.5'` will likely make your example work. Please follow @gpotter2 advices and reopen this issue if needed.

**Comment by stacksreg123** [comment]
Ok thanks for the advice.
This is the updated code:
```
#!/usr/bin/env python3
from scapy.all import sniff, sendp, IP, Ether

def spoof_and_send(packet):
	packet[IP].dst = '192.168.0.5'
	packet[Ether].src = None
	packet[Ether].type = None
	
	sendp(packet)

packets = sniff(filter='udp and portrange 6000-7999', prn=spoof_and_send)
```

It seems to me that there is no chksm attribute to Ether; @gpotter2 ?

Well now I can see udp packets being sent on wireshark. On the target machine no packets arrive.

**Comment by gpotter2** [comment]
It should be
```
def spoof_and_send(packet):
	packet[IP].dst = '192.168.0.5'
	packet[Ether].dst = None
	packet[IP].chksum = None
	
	sendp(packet)
```

**Comment by stacksreg123** [comment]
Ok with that code it works, somewhat..
For some reasons the same packets are sent many times over and over again. Its like it sends the same packets in a loop. 

The full code is:
```
#!/usr/bin/env python3
from scapy.all import sniff, sendp, IP, Ether

def spoof_and_send(packet):
	packet[IP].dst = '192.168.0.5'
	packet[Ether].dst = None
	packet[Ether].chksum = None
	
	sendp(packet)

packets = sniff(filter='(src host 192.168.0.7 and udp dst portrange 6000-7999) or (dst host 192.168.0.7 and udp src portrange 6000-7999)', prn=spoof_and_send)
```

**Comment by guedou** [comment]
Well, your code sends a packet every time it receives one.
