### ISSUE TITLE
 FlagsField flag names containing "-" are inaccessible via dot notation.

### ISSUE THREAD

**Issue by mtihlenfield** [secdev/scapy#1346]
#### Things to consider

1. Please check that you are using the latest scapy version, e.g. installed via:

   `pip install https://github.com/secdev/scapy`

2. If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: https://gitter.im/secdev/scapy

3. Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

#### Brief description

An `AttributeError` is thrown when trying to access via dot notation a `FlagsField` flag that contains an "-" in it's name.

For example, the Dot11 protocol has a `FlagsField` called `FCfield` which has flags called `to-DS` and `from-DS`. Trying to access the flags like this:

    packet.FCfield.toDS
    packet.FCfield.to_DS

causes an `AttributeError`. However you can access them like this:

    packet.FCfield.__attr__("to-DS")

I don't know of other procotols that have this issue but I suspect any FlagsField flag with a "-" would be affected.

#### Environment

- Scapy version: 2.4.0
- Python version: 3.6.4
- Operating System: Arch Linux

#### How to reproduce

    import scapy.all as sc
    import scapy.layers.dot11 as dot11

    packets = sc.rdpcap("sample.pcapng")

    for packet in packets:
        if packet.haslayer(dot11.Dot11):
            dot11_layer = packet.getlayer(dot11.Dot11)
            to_ds = dot11_layer.FCfield.toDS
            # or to_ds = dot11_layer.FCfield.to_DS
            print("to-DS: {}".format(to_ds))

#### Actual result

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/scapy/fields.py", line 1298, in __getattr__
        return bool((2 ** self.names.index(attr)) & int(self))
    ValueError: 'toDS' is not in list

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "./test.py", line 10, in <module>
        to_ds = dot11_layer.FCfield.toDS
      File "/usr/lib/python3.6/site-packages/scapy/fields.py", line 1302, in __getattr__
        return super(FlagValue, self).__getattr__(attr)
    AttributeError: 'super' object has no attribute '__getattr__'

#### Expected result

    to-DS: True
or

    to-DS: False

#### Related resources

[Sample pcap](https://file.io/6FbVln)

**Comment by p-l-** [comment]
Fixed by @guedou in #1421. Use `dot11_layer.FCfield.to_DS`.
