### ISSUE TITLE
Unable to Accurately Set Time Fields in NTP Layer

### ISSUE THREAD

**Issue by colleen15** [secdev/scapy#135]
I'm trying to modify the time fields in the NTP layer, and not having any luck. I've tried setting packet.recv to an integer value and a string representation of time, but no matter what I try, when I send the packet, this field is always set to the default 0. Is there any example code that I just missed that would show me how to do this? Thank you in advance.

**Comment by p-l-** [comment]
Hi,

For now, the only answer would be to use:
```Python
NTP(recv=int(time.time() + scapy.layers.ntp._NTP_BASETIME))
```

This is not convenient, it is possible to use a string representing the date (based on a specific format `%a %b %d %H:%M:%S %Y`); for now, this does not crash, but does **not** set the correct value (PR #137 fixes that):
```Python
NTP(recv="Thu Apr 28 11:22:33 2016")
```

Also, PR #137 introduces a new way to set the `TimeStampField` value using a `datetime()` object:
```Python
NTP(recv=datetime.now())
```

**Comment by colleen15** [comment]
Thanks very much for getting to this so quickly. I'll be using it today!
