### ISSUE TITLE
Web redirection

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1353]
We should redirect http://secdev.org/projects/scapy/ to https://scapy.net

@p-l- @guedou @phil777

**Comment by phil777** [comment]
Done.

**Comment by guedou** [comment]
I am not sure that a HTTP redirect is the best solution as we might lose search engines referencing. Could you use a reverse proxy instead? See https://httpd.apache.org/docs/2.4/rewrite/proxy.html
