### ISSUE TITLE
name 'ByteField' is not defined in 'scapy/contrib/lldp.py'

### ISSUE THREAD

**Issue by ofull37** [secdev/scapy#1360]
File "**/scapy/contrib/lldp.py", line 702, in LLDPDUGenericOrganisationSpecific
    ByteField('subtype', 0x00),
NameError: name 'ByteField' is not defined

#### Environment
- Scapy version: < scapy2.4.0 >
- Python version: < 3.6.3 >
- Operating System: < ubuntu16.04.4 >

**Comment by gpotter2** [comment]
Hi,
That was fixed 20h ago :)
https://github.com/secdev/scapy/pull/1336
Please retry using master
`pip install git+git://github.com/secdev/scapy.git`
