### ISSUE TITLE
release tarballs for 2.4.0 on githug and/or pypi

### ISSUE THREAD

**Issue by danieljakots** [secdev/scapy#1373]
Hi,

Unless I'm mistaken by the new Warehouse, currently the only way to get 2.4.0 is https://github.com/secdev/scapy/archive/v2.4.0.tar.gz. This tgz hash depends on the software github is running and it's not stable across time and the gh node you hit. For more details you can read https://github.com/stealth/opmsg/issues/19#issuecomment-374955568

Would it be possible to host a proper release on pypi or github?
AFAICS, pypi download link is a github link.

Thanks!

**Comment by guedou** [comment]
That's a really interesting fact that I did not know!

pypi distributes the tarball that I generated before uploading it to pypi. Here is the checksum of the original tarball:
```
$ sha256sum dist/scapy-2.4.0.tar.gz 
452f714f5c2eac6fd0a6146b1dbddfc24dd5f4103f3ed76227995a488cfb2b73  dist/scapy-2.4.0.tar.gz
```

That is the hash of the file distributed by pypi.
