### ISSUE TITLE
Signal strength (RadioTap.dbm_antsignal) not working

### ISSUE THREAD

**Issue by calebmadrigal** [secdev/scapy#1379]
It seems there's not a clean way to get signal strength (like `frame[RadioTap].dbm_antsignal).

- Scapy version: 2.4.0
- Python version: 3.6.5
- Operating System: Ubuntu 17.10

**Comment by calebmadrigal** [comment]
Looks like this probably gives me what I need: `signal_strength = -(256-ord(frame[RadioTap].notdecoded[-4:-3]))`, but I would think a cleaner solution would be better.

**Comment by gpotter2** [comment]
Could you share a pcap ?

**Comment by gpotter2** [comment]
Thanks !
Could you re-try using https://github.com/gpotter2/scapy/commit/f5e10d716a9a7b248a70446026547a9afc719311 ?
It adds support for those fields. Would be great if you could test if a bit

**Comment by gpotter2** [comment]
Fixed in https://github.com/secdev/scapy/issues/1379 ! You might want to have a look

**Comment by calebmadrigal** [comment]
I'll check it out later tonight!
