### ISSUE TITLE
DNSRR PTR records --- unable to populate rdata with pointer to rrname

### ISSUE THREAD

**Issue by emacsuser123** [secdev/scapy#1380]
#### Brief description

Cannot populate DNSRR answer, type PTR successfully

#### Environment

- Scapy version: 2.4.0
- Python version: 3.6
- Operating System:  Ubuntu 17.10 desktop

#### How to reproduce

Create an instance of DNSRR (as part of a whole DNS instance). Set type to PTR. Set rrname to, for instance, "one.two.three.local".
We want rdata to be something like:   "four.five.three.local"
So, the rdata field should be something like: "four.five.<pointer to three.local>
The pointer to "three.local" will be: 0xc0 0x16
because 0x16 = 22 = 12 + 10 (12 is the length for the DNS header, and 10 is:
4 + 1 + 4 + 1 (length of "four" word, 1 byte length, length of "five", 1 byte length) 

I'm not able to set that pointer properly.

You can see below that 'y' variable contains a DNSRR answer, with no rdata at that point:
>>> y = DNSRR(type='PTR', ttl=120)
>>> y.rrname = 'one.two.three.local'
>>> y.show()
###[ DNS Resource Record ]### 
  rrname    = 'one.two.three.local'
  type      = PTR
  rclass    = IN
  ttl       = 120
  rdlen     = 1
  rdata     = ''

Now, I put 'y' inside an enclosing DNS instance, 'z' variable:

>>> z = DNS(an=y)
>>> z.show()
###[ DNS ]### 
  id        = 0
  qr        = 0
  opcode    = QUERY
  aa        = 0
  tc        = 0
  rd        = 1
  ra        = 0
  z         = 0
  ad        = 0
  cd        = 0
  rcode     = ok
  qdcount   = 0
  ancount   = 1
  nscount   = 0
  arcount   = 0
  qd        = None
  \an        \
   |###[ DNS Resource Record ]### 
   |  rrname    = 'one.two.three.local'
   |  type      = PTR
   |  rclass    = IN
   |  ttl       = 120
   |  rdlen     = 1
   |  rdata     = ''
  ns        = None
  ar        = None

Now, I fill in rdata field in 'y' variable, setting the pointer to what I said:

>>> y.rdata = "four.five\xc0\x16"
>>> z.show()
###[ DNS ]### 
  id        = 0
  qr        = 0
  opcode    = QUERY
  aa        = 0
  tc        = 0
  rd        = 1
  ra        = 0
  z         = 0
  ad        = 0
  cd        = 0
  rcode     = ok
  qdcount   = 0
  ancount   = 1
  nscount   = 0
  arcount   = 0
  qd        = None
  \an        \
   |###[ DNS Resource Record ]### 
   |  rrname    = 'one.two.three.local'
   |  type      = PTR
   |  rclass    = IN
   |  ttl       = 120
   |  rdlen     = 14
   |  rdata     = 'four.five\xc3\x80\x16'
  ns        = None
  ar        = None

So, it seems that the pointer is somehow not being recognized.
It gets a value of \xc3\x80\x16, not the one I used.

#### Actual result

Bad pointer value

#### Expected result

Pointer value set to: 0xc0 plus an additional byte pointing to the desired domain label.

Thanks.
-Bob V

**Comment by guedou** [comment]
Scapy does not support DNS compression. It can decode packets, but cannot encode them correctly. I had a look at the code and did not find a way to support this correctly.

Currently, you either don't use compression or edit the packet yourself:
```
>>> r = raw(DNS(an=DNSRR(type='PTR', rrname="one.two.three.local", rdata="four.five.three.local")))
>>> DNS(r[:-13] + b"\xc0\x14")
<DNS  id=0 qr=0 opcode=QUERY aa=0 tc=0 rd=1 ra=0 z=0 ad=0 cd=0 rcode=ok qdcount=0 ancount=1 nscount=0 arcount=0 qd=None an=<DNSRR  rrname='one.two.three.local.' type=PTR rclass=IN ttl=0 rdata='four.five.three.local.' |> ns=None ar=None |>
```
