### ISSUE TITLE
python.exe because of scapy

### ISSUE THREAD

**Issue by TheGoodguy12** [secdev/scapy#139]
hey, I need help !!
everytime I run python script with from scapy.all import * 
it crashes!!! Can someone help me fix it ?
I have large work to do with scapy for tommrow and now it's not working!!

**Comment by p-l-** [comment]
Sorry but we are going to need more information about the "crash". Can you run a Python interpreter, enter `from scapy.all import *` and post the full output here (including Python version, etc.)?

**Comment by TheGoodguy12** [comment]
Python version 2.7
Python.exe isn't response. Windows searching for resolving.
And then it crashed ,
I tried script with print 'hello' and it worked .

**Comment by TheGoodguy12** [comment]
*the script was only print 'hello' not with scapy so I'm sure it's scapy that crashes.

**Comment by p-l-** [comment]
Do you have an error message?

**Comment by TheGoodguy12** [comment]
Yes, "Python.exe isn't working." And then it crashes

**Comment by guedou** [comment]
Please give more details about your issue. There is no way we can help with such a generic error message.
