### ISSUE TITLE
struct.error: ubyte format requires 0 <= number <= 255 scapy- fuzz() 

### ISSUE THREAD

**Issue by wihack** [secdev/scapy#1395]
I know that scapy can't be longer than 255, but I used the fuzz() function for fuzzing. Can't I use the fuzz() function?

code：
frame=fuzz(Dot11(proto=0,FCfield=0,ID=0,addr1="11:22:33:44:55:66",addr2="11:22:33:44:55:77",addr3="11:22:33:44:55:77",SC=0,addr4=None)/Dot11Beacon(beacon_interval=0,cap="ESS")/Dot11Elt())
sendp(frame,loop=1)

Can you give me a solution? I am very anxious

**Comment by wihack** [comment]
Wǒ de python bǎnběn wèi 2.7 Scapy bǎnběn wèi 2.2.0.

My python version is 2.7 scapy version 2.2.0.

**Comment by guedou** [comment]
Please use the issue template

**Comment by guedou** [comment]
Please upgrade to 2.40 or current dev version an reopen the issue if needed.

**Comment by joswr1ght** [comment]
Instead of just closing all of these issues, maybe `fuzz()` could be a little smarter, and not try to force data into an element that is not supported?
