### ISSUE TITLE
scapy fuzz() function <=255？

### ISSUE THREAD

**Issue by wihack** [secdev/scapy#1396]
#### Brief description
return s+struct.pack(self.fmt, self.i2m(pkt,val))
struct.error: ubyte format requires 0 <= number <= 255

#### Environment
python version 2.7
scapy version 2.2
ubuntu 16.04

#### How to reproduce
frame=fuzz(Dot11(proto=0,FCfield=0,ID=0,addr1="11:22:33:44:55:66",addr2="11:22:33:44:55:77",addr3="11:22:33:44:55:77",SC=0,addr4=None)/Dot11Beacon(beacon_interval=0,cap="ESS")/Dot11Elt())
sendp(frame,loop=1)

Q：
Can you give me a solution? I am very anxious

**Comment by guedou** [comment]
See my comments in #1395
