### ISSUE TITLE
Invalid regexp in HTTP/2 header parsing ?

### ISSUE THREAD

**Issue by JuhaniPolvi** [secdev/scapy#1397]
#### Brief description

Regular expression used in parsing HTTP/2 attributes from text seems to be incorrect.

#### Environment

scapy version 2.4.0

#### How to reproduce

Use class HPackHdrTable function parse_txt_hdrs to parse an attribute with name starting with colon, e.g.

handler = HPackHdrTable()
data = handler.parse_txt_hdrs(':scheme: http')

#### Actual result

Attribute is not created

#### Expected result

Should create specified attribute

I found that changing the regular expression (defined in function _parse_header_line) from

b'^(?::([a-z\-0-9]+)|([a-z\-0-9]+):)\s+(.+)$'

to

b'^(?::([a-z\-0-9]+)|([a-z\-0-9]+)):\s+(.+)$'

seemed to fix this issue.

**Comment by p-l-** [comment]
Hi,

Thanks for this report! Do you have a "real world" example (PCAP file, maybe) to share? If you do, maybe you could create a pull request and add a test for this bug?

**Comment by JuhaniPolvi** [comment]
In this case pcap files are not helpful except in checking the results, e.g. in Wireshark. The problem is in encoding, creating HTTP/2 frames, not in decoding. However this can be checked using the interactive mode of scapy, using wireshark or similar to check the results.

Starting in interactive mode try the following (I'm using >>> prefix to show typing in the interactive mode prompt)

>>>load_contrib("http2")

Load the http2 module

>>>magic = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"

Declare the magic word used to identify HTTP/2 content. This is not strictly necessary but without it Wireshark won't recognise the data as HTTP/2

>>>handler = HPackHdrTable()

Instantiate handler used to parse the data

>>>h2_frame = handler.parse_txt_hdrs(":method: GET\n:scheme: http\n:authority: www.example.com\n:path: /login.php\nuser-agent: Mozilla")

Declare simple HTTP/2 frame containing method, the three URL parts and some kind of user agent. Note that the parser can parse multiple attributes separated by line breaks.

>>>packet = Ether() / IP() / TCP(dport=80) / magic / h2_frame

Generate simple HTTP/2 frame containing ethernet header, IP header, TCP header (destination port 80 for HTTP), magic word and actual frame.

>>>wrpcap("test.pcap", packet)

Save the packet as a pcap file. You should save the files under different names for comparison.

Opening the file in Wireshark should clearly show the difference. In the original version only the user agent is present (since the key didn't start with a colon) while the rest is simply missing. In the modified version all fields are present.

**Comment by guedou** [comment]
Sorry, it took me ages to have a look at RFC7451. According to my understanding, and `Appendix A` header name does not end with `:`. Hence, you need to write:
`h2_frame = handler.parse_txt_hdrs(":method GET\n:scheme http\n:authority www.example.com\n:path /login.php\nuser-agent: Mozilla")`

**Comment by guedou** [comment]
Feel free to reopen if I am wrong. I am not an HTTP/2 expert.
