### ISSUE TITLE
Scapy fuzz() wrong length

### ISSUE THREAD

**Issue by wihack** [secdev/scapy#1398]
Brief description

Before following your advice, upgrade scapy to scapy2.4, but if I execute the fuzz() function I still get a length error:

Environment
scapy version 2.4.0
python 2.7

How to reproduce

 victim="11:22:33:44:55:66"
Attacker="22:33:44:55:66:77"
Frame = Dot11 (proto=0, FCfield=0, ID=0, addr1=victim, addr2=attacker,
                     Addr3=attacker,SC=0,addr4=None)/Dot11Beacon(beacon_interval=100,cap="ESS")/Dot11Elt(ID=0)
Sendp(fuzz(frame), loop=1)

Actual result

    return s+struct.pack(self.fmt, self.i2m(pkt,val))
struct.error: ubyte format requires 0 <= number <= 255

Expected result

There should be no error

**Comment by wihack** [comment]
Can you give me a 【fuzz（）（StrLenField.max_length）】 demonstration of usage? really thankful

**Comment by wihack** [comment]
Can you show me how to use (StrLenField.max_length)? I have updated the latest version of scapy

**Comment by p-l-** [comment]
You don't need to use `.max_length` yourself.

Also, for now, the patch has not been merged yet, so you have to apply it by yourself if you want to try it.

**Comment by wihack** [comment]
OK, how can I update this patch? When can this bug be fixed? I am very anxious and look forward to your update

**Comment by wihack** [comment]
OK, I understand. When you update this patch, where can I know that you have updated this patch?

**Comment by wihack** [comment]
I installed it using git clone https://github.com/secdev/scapy python setup.py install.
