### ISSUE TITLE
Field Unused in ICMPv6DestUnreach and ICMPv6TimeExceeded

### ISSUE THREAD

**Issue by antekirtt** [secdev/scapy#140]
Hello, I'm using Scapy to test ICMPv6 covert channels and I got an error with the "unused" field of both Destination Unreachable and Time Exceeded messages.
The error is:
struct.error: ubyte format requires 0 <= number <= 255

In fact I'm inserting 4 bytes of data, as from rfc4443, while it seems that X3BytesField is defined for 1 byte. If I test it with 1 byte all is fine.

Any idea?

**Comment by guedou** [comment]
Scapy supports multipart ICMP messages as defined in RFC4884. In a nutshell, it uses one byte from the original four bytes unused field to encode the lenght of ICMP extensions (see [scapy/contrib/icmp_extensions.py](https://github.com/secdev/scapy/blob/master/scapy/contrib/icmp_extensions.py)).

I can't help you more as you did not provide an example. Splitting your 4 bytes into length and used will do the trick.

**Comment by antekirtt** [comment]
Thanks for the suggestion, I did not consider RFC4884 which update RFC4443, my bad. Now it is working as expecting.
