### ISSUE TITLE
man page spelling error

### ISSUE THREAD

**Issue by irl** [secdev/scapy#1401]
intances should be instances.

It would be nice if this wasn't gz compressed in the source, otherwise I'd have done a pull request.

**Comment by guedou** [comment]
Thanks for reporting the issue. I don’t think that there is a need to have that file compressed. We could remove it and apply your changes.

**Comment by irl** [comment]
Great thanks. man also throws an error on Debian when compiling the man page, but I've not investigated because it's a compressed file and not easily patched in the Debian package. If it's not compressed in the next release, I'll investigate that and hopefully make a pull request.
