### ISSUE TITLE
Error mac field in Ether layer with packet send from netfilterqueue

### ISSUE THREAD

**Issue by yangyinqi** [secdev/scapy#1405]
#### Things to consider

1. Please check that you are using the latest scapy version, e.g. installed via:

   `pip install https://github.com/secdev/scapy`

2. If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: https://gitter.im/secdev/scapy

3. Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

#### Brief description

I found that when I used `netfilterqueue` as a packet source, the Ether layer message would be cunfused. The dst and src mac fields were totally not real, as well as type field.

The source codes are:
``` python
from netfilterqueue import NetfilterQueue
import os
from scapy.all import *

def process_data(pkt):
    #  print(isinstance(scapy_pkt, bytes))
    scapy_ether = Ether(pkt.get_payload())
    scapy_pkt = Packet(pkt.get_payload())
    print("-------------------------")
    scapy_ether.show()
    print("-------------------------")
    scapy_pkt.show()
    #  pkt.set_payload(payload)
    #  hw = pkt.get_hw()
    #  if hw:
        #  print(":".join("{:02x}".format(ord(chr(c))) for c in hw[0:6]))
    pkt.accept()

queue_num = 1
nfq1 = NetfilterQueue()
nfq1.bind(queue_num, process_data)
os.system('iptables -F')
os.system('iptables -A INPUT -j NFQUEUE --queue-num %d' % (queue_num))
os.system('iptables -A OUTPUT -j NFQUEUE --queue-num %d' % (queue_num))

try:
    nfq1.run()
except KeyboardInterrupt:
    os.system('iptables -F')
    nfq1.unbind()
    print('User exit!')
```

#### Environment

- Scapy version: < 2.4 >
- Python version: < 3.6.5 >
- Operating System: < Ubuntu18 64bit >

#### How to reproduce

Just run the code above, and wait for the packet. The output will show the packet info including raw frame and Ether layer info.

#### Actual result
![image](https://user-images.githubusercontent.com/13461266/39825338-201c3c42-53e4-11e8-82e2-1884b4e04f9d.png)
#### Expected result
The real src and dst mac addresser are `08:00:27:7d:63:6d` and `8c:70:5a:8d:b2:90`.
#### Related resources

< traces / sample pcaps (stripped to the relevant frames), related standards, RFCs or other resources >

**Comment by guedou** [comment]
nfqueue returns IP packets. Use IP() instead of `Ether()`.

**Comment by p-l-** [comment]
FWIW, you can tell @guedou is right because each packet starts with `0x45` (first byte of what is incorrectly decoded as the Ethernet destination address), which is standard for an IPv4 packet: first nibble is version (4), second is IP header length, (5 4-bytes words, i.e. 20 bytes, which is the length of an IP header without any option).
