### ISSUE TITLE
sniff not catching all UDP packets.

### ISSUE THREAD

**Issue by zwilcox** [secdev/scapy#1406]
- Scapy version: scapy-2.4.0
- Python version: 2.7
- Operating System: Win7

I'm attempting to catch  udp packets on a particular port.
Wireshark show's I'm capturing  472 packets on this port.

I've created a simple script where I count the number of packets in the sniff call back.  I then print the numbers when I press ctrl-c.  
The number of packets caught by scapy's sniff is 345.

The numbers aren't exactly the same, but the miss-rate hovers around 25-35%

See the below code:
``

    def exitAndWriteToFile(signum, frame):
        print "ctrl was pressed:"
        print "Number of packets caught: " + str(packetCount)
        exit()

    signal.signal(signal.SIGINT, exitAndWriteToFile)

    global packetCount
    packetCount = 0

    def countPackets(packet):
        global packetCount
        packetCount += 1

     sniff(iface=networkInterface, filter='udp and port 8193', prn=countPackets)

edit:  I'm also filtering on udp port 8193 in wireshark

**Comment by guedou** [comment]
Depending on the packet rate, Scapy might miss some packets =/
