### ISSUE TITLE
Question: Meta-Information in Packets

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#1418]
Hi, I'm planning to extend the ISOTP implementation a little bit. 
I've the following problem. 
An ISOTP socket is similar to a StreamSocket. ISOTP communication uses a source and a destination, and maybe a extended source and a extended destination. 
A ISOTPSocket is instantiated with a source and a destination and the optional extended source and destination. The Socket needs this information to operate. 
On the CAN-Layer, only the destination is used to transfer packets to the correct endpoint. This means, the source information is removed from the Socket, and you don't see this information on a lower layer. Only the Socket has the full picture of source and destination and extended informations.
A ISOTP Packet only contains a payload at the moment. This was the easiest way to implement this. I just have to give this packet to the socket, and the raw data is sent. Nevertheless I would like to store source and destination and optionally extended information inside a ISOTP-Packet. Since this information is not consistant with the lower layers, I'm wondering, what the best way to implement this meta-information inside a ISOTP Packet, would be. A field wouldn't work in this case. Can you give me an advice on this?
Cheers Nils

**Comment by guedou** [comment]
Isn't it better to provide the addresses as parameters to the socket?

**Comment by polybassa** [comment]
This is exactly my question. The addresses are a parameter in the socket, anyway. But from a packet, I've no way to determine the src and the destination address.
This page shows ISOTP communication: http://www.emotive.de/wiki/index.php?title=ISOTP

Source and destination are not part of the data on the bus. Only one or two frame handling bytes are present. So a Field in a Packet wouldn't be the correct way to store this information. Nevertheless source and destination information would be valuable in the Packet for later analysis.

Cheers Nils

**Comment by gpotter2** [comment]
If you have no other way of storing data, you can use `__slots__`
![image](https://user-images.githubusercontent.com/10530980/40111963-c5994a64-5904-11e8-904a-98921b656051.png)

**Comment by polybassa** [comment]
Thanks for this answers. 
Addresses will be stored in Sockets. A global storage doesn't work, since I would have to store Addresses for every connection. This slots solutions sounds good, to store addresses in a Packet, even if the adresses are not part of the transmitted data.

**Comment by guedou** [comment]
Cool =)
