### ISSUE TITLE
No such file or directory : 'manuf'

### ISSUE THREAD

**Issue by Van-hoa** [secdev/scapy#1422]
Hi !

I used Scapy on Linux and it works really well.

But now, for a project i have to launch my script from a C# program so i need to use Scapy on Windows.

I have VS installed, Npcap and i have download the zip archive of Scapy.

When i install Scapy with the setup.py and try to run my script from PyCharm i have an error "FileNotFoundError: [Errno 2] No such file or directory: 'path/to/manuf'".

I don't really understand what requirements i missed to use Scapy on Windows.

Do you have any solutions ? 

Thank's.

**Comment by gpotter2** [comment]
Hmmmm,

I could not find a single occurence of ""path/to/manuf"" in scapy's code :/ Are you sure you are using a recent scapy version ?

Also, have you any line with the error code (full stackerror print please)

There are no other requirements than Npcap

Thanks !

**Comment by Van-hoa** [comment]
The full error is "FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Personnel\\manuf'".
I didn't want to give the path in my OS, but anyways it seems that i don't have manuf (it seems to be related with something like a Wireshark's database).

Of course, i am using the latest version of Scapy.

Thanks ! 

(If it's needed, i can take screenshots to show you my code and/or the full stack error).

**Comment by gpotter2** [comment]
Got it, this is indeed a bug: you are missing a Wireshark installation registered in the PATH variable, (if you want in the meantime, install wireshark and add its main folder to the PATH).

In python 2, it was "IOError", in python 3 it's "fileNotFoundError" (extended from OSError).

fixed in https://github.com/secdev/scapy/pull/1424

**Comment by Van-hoa** [comment]
I didn't add Wireshark to PATH ! 

Thank's ! I can use Scapy with the interactive shell, there is still issues with PyCharm but i think it's just some configurations in settings.
