### ISSUE TITLE
Bug. 

### ISSUE THREAD

**Issue by walentybzyk** [secdev/scapy#1447]
#### Brief description
Using __settattr__() method with parameter **payload** bytes type cause error.
Bytes type payload doesn't correctly iterated in __iter__() method.
In __iter__() method, loop() function converts bytes to int type.
Finally argument of add_payload() method isn't instance of Packet or bytes causes error:
"TypeError: payload must be either 'Packet' or 'bytes', not [117]" .

#### Environment

- Scapy version: 2.4.
- Python version: 3.65
- Operating System: Win10

#### How to reproduce
eth = Ether()
setattr(eth,"payload",b'user payload')
eth
<Ether  |b'user payload'>
print(eth)

#### Actual result
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\scapy\packet.py", line 353, in __str__
    return str(self.build())
  File "C:\Python\Python36\lib\site-packages\scapy\packet.py", line 463, in build
    p = self.do_build()
  File "C:\Python\Python36\lib\site-packages\scapy\packet.py", line 444, in do_build
    self = next(iter(self))
  File "C:\Python\Python36\lib\site-packages\scapy\packet.py", line 847, in loop
    pkt = self.clone_with(payload=payl, **done2)
  File "C:\Python\Python36\lib\site-packages\scapy\packet.py", line 820, in clone_with
    pkt.add_payload(payload)
  File "C:\Python\Python36\lib\site-packages\scapy\packet.py", line 194, in add_payload
    raise TypeError("payload must be either 'Packet' or 'bytes', not [%s]" % repr(payload))  # noqa: E501
TypeError: payload must be either 'Packet' or 'bytes', not [117]

#### Expected result
b'\xff\xff\xff\xff\xff\xff\xc8\xff(\xd9\xec\xfb\x90\x00user payload'

**Comment by p-l-** [comment]
Hi,

Why would you use `setattr()` here? The correct way to do what you're trying to do is:
```
>>> Ether() / b'user payload'
<Ether  |<Raw  load='user payload' |>>
>>> print(_)
WARNING: Mac address to reach destination not found. Using broadcast.
b'\xff\xff\xff\xff\xff\xff GG\xee\xdd\xa8\x90\x00user payload'
```

**Comment by walentybzyk** [comment]
I use it to parsing xml file with setting many parameters from xml and only with payload this problem 
the problem occurs.

**Comment by p-l-** [comment]
OK, I'm not sure to understand, but anyway you should just use `Ether() / b'user payload'` and not `setattr()`.

**Comment by walentybzyk** [comment]
I would iterate on xml node tag which are compatible  with scapy frame parameter. 
My xml file look:
 <ip>
              <dst>'170.187.204.221'</dst>
              <src>'153.136.119.102'</src>
               <ttl>123</ttl>
               <id>4</id>
                <tcp>
                       <sport>4</sport>
                        <payload>b'user payload</payload>
               </tcp>
</ip>
 <ip>
              <dst>'1.187.204.221'</dst>
              <src>'13.136.119.102'</src>
               <ttl>123</ttl>
               <id>4</id>
                <tcp>
                       <sport>4</sport>
                        <payload>b' another user payload</payload>
               </tcp>
</ip>
setattr(frame, child.tag, eval(child.text))
child is node tag eg. dst, child.text is value in the node
and this code is working with every parameter except payload.
I necessary to creating any number of frames declared in xml file.  And frame are nested like Ether()/IP()/TCP()

**Comment by p-l-** [comment]
As a side remark, IMO your XML format sucks: the `tcp` node is not a field of the `ip` node, and `payload` is not a field of `tcp`. There is no way for a parser to guess that (generically).

In Scapy, to set a packet's payload, use `pkt / payload` and **not** `setattr(pkt, "payload", payload)`.

**Comment by gpotter2** [comment]
You got tons of way to store scapy packets:

- use pcaps (`wrpcap()` and `rdpcap()`)
- use raw bytes `raw(pkt)` then `Ether(raw_pkt)`
- use pickle `cPickle.dumps(pkt)` and `cPickle.loads(pkt)` if you want plain string

XML is definitely a quite bad option. If you want to open external built packets in scapy, build them (e.g `Ether(dst=stuff)/IP(...)/TCP(...)`
