### ISSUE TITLE
OSX: “station monitor” mode when using monitor=True

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1453]
According to
https://github.com/calebmadrigal/trackerjacker/issues/5#issuecomment-388416793

The way we start monitor mode under OSX sets the interface into a weird pseudo-locked mode

> In one terminal:
> 
> ```
> >>> import scapy.all as scapy
> >>> scapy.sniff(iface='en0', prn=lambda p: p.summary(), monitor=True)
> ```
> In another terminal (after running the above):
> 
> ```
> $ /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I
>      agrCtlRSSI: -62
>      agrExtRSSI: 0
>     agrCtlNoise: -93
>     agrExtNoise: 0
>           state: running
>         op mode: station monitor
>      lastTxRate: 216
>         maxRate: 400
> lastAssocStatus: 0
>     802.11 auth: open
>       link auth: none
>           BSSID: 82:2a:a8:55:71:15
>            SSID: colectivo
>             MCS: 5
>         channel: 157,1
> ```
> As you can see, the op mode is station monitor. And when I try switching to a different channel, it doesn't work

**Comment by gpotter2** [comment]
Calling @guedou for OSX

**Comment by guedou** [comment]
Sorry for the looong delay. I do not boot macOS often ...

This behavior is expected that the `station monitor` mode is used to sniff raw 802.11 frames. Sniffing with `tcpdump -I` does exactly the same. When `sniff()` stops the mode goes back `station`.
