### ISSUE TITLE
Scapy with Python3 stripped unknown TCP options

### ISSUE THREAD

**Issue by matttbe** [secdev/scapy#1459]
#### Brief description

Scapy with Python3 strips unknown TCP options while it is not doing that with Python2.

I receive some packets with Netfilter Queue, I can read them correctly with Scapy but when rebuilding them after modifications, unknown TCP options are stripped. This unknown option is MPTCP (TCP option 30).

#### Environment

- Scapy version: 2.4.0
- Python version: 2.7.5 and 3.4.8
- Operating System: CentOS 7.5
- NetfilterQueue: 0.8.1

I need to setup an IPTables rule to intercept TCP packet, e.g. in FORWARD:
```iptables -w -A FORWARD -p tcp -j NFQUEUE --queue-num 1```

#### How to reproduce

I intercept packets with NetfilterQueue, everything seems ok until I modify the packet, even simply removing the checksum is enough:

```#! /usr/bin/python3

from scapy.all import *
from netfilterqueue import NetfilterQueue


def cb_modify(packet):
	pkt = IP(packet.get_payload())
	pkt.show2()

	tcp = pkt.getlayer(TCP)

	del pkt.chksum
	del tcp.chksum

	pkt.show2()

	packet.set_payload(bytes(pkt)) # for Python2, please use: packet.set_payload(str(pkt))
	packet.accept()

nfqueue = NetfilterQueue()
#1 is the IPtables rule queue number
nfqueue.bind(1, cb_modify)
try:
	print("[*] waiting for data")
	nfqueue.run()
except KeyboardInterrupt:
	pass
```

#### Actual result

With Python3, I got:

```
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 72
  id        = 16352
  flags     = DF
  frag      = 0
  ttl       = 63
  proto     = tcp
  chksum    = 0xe3cb
  src       = 10.1.2.1
  dst       = 10.2.2.1
  \options   \
###[ TCP ]### 
     sport     = 47986
     dport     = search_agent
     seq       = 536014316
     ack       = 0
     dataofs   = 13
     reserved  = 0
     flags     = S
     window    = 29200
     chksum    = 0x8868
     urgptr    = 0
     options   = [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4294693388, 0)), ('NOP', None), ('WScale', 6), (30, b'\x10\x03\xc1\x1c\x95\x9b\x81R_1')]

###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 72
  id        = 16352
  flags     = DF
  frag      = 0
  ttl       = 63
  proto     = tcp
  chksum    = 0xe3cb
  src       = 10.1.2.1
  dst       = 10.2.2.1
  \options   \
###[ TCP ]### 
     sport     = 47986
     dport     = search_agent
     seq       = 536014316
     ack       = 0
     dataofs   = 13
     reserved  = 0
     flags     = S
     window    = 29200
     chksum    = 0xedb3
     urgptr    = 0
     options   = [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4294693388, 0)), ('NOP', None), ('WScale', 6)]
```

#### Expected result

We can see the the latest TCP option has been stripped (and the TCP checksum is different but I guess correct for this modified packet).

With Python2, same version of Scapy, I have:

```
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 72
  id        = 9903
  flags     = DF
  frag      = 0
  ttl       = 63
  proto     = tcp
  chksum    = 0xfcfc
  src       = 10.1.2.1
  dst       = 10.2.2.1
  \options   \
###[ TCP ]### 
     sport     = 38923
     dport     = search_agent
     seq       = 2514678136
     ack       = 0
     dataofs   = 13
     reserved  = 0
     flags     = S
     window    = 29200
     chksum    = 0x65a8
     urgptr    = 0
     options   = [('MSS', 1460), ('SAckOK', ''), ('Timestamp', (4294694872, 0)), ('NOP', None), ('WScale', 6), (30, '\x10\x03\n\xcdD\xca\xde\xf1\xcf\x91')]

###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 72
  id        = 9903
  flags     = DF
  frag      = 0
  ttl       = 63
  proto     = tcp
  chksum    = 0xfcfc
  src       = 10.1.2.1
  dst       = 10.2.2.1
  \options   \
###[ TCP ]### 
     sport     = 38923
     dport     = search_agent
     seq       = 2514678136
     ack       = 0
     dataofs   = 13
     reserved  = 0
     flags     = S
     window    = 29200
     chksum    = 0x65a8
     urgptr    = 0
     options   = [('MSS', 1460), ('SAckOK', ''), ('Timestamp', (4294694872, 0)), ('NOP', None), ('WScale', 6), (30, '\x10\x03\n\xcdD\xca\xde\xf1\xcf\x91')]
```

Same TCP options and checksum.

#### Related resources

I didn't try but I guess we can also forge packets with an unknown option and we should get the same results but at least here, we are sure that the packet was correct in input and only the rebuild failed.

Don't hesitate to tell me if you need more details!

And thank you for developing and maintaining this excellent tool!

**Comment by matttbe** [comment]
I confirm that we can also craft the packets ourselves. Here is what I did using "scapy" command line tool:

```python
>>> pkt = IP()/TCP()
>>> tcp = pkt.getlayer(TCP)
>>> tcp.options   = [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4294693388, 0)), ('NOP', None), ('WScale', 6), (30, b'\x10\x03\xc1\x1c\x95\x9b\x81R_1')]
>>> tcp.show()
###[ TCP ]### 
  sport= ftp_data
  dport= http
  seq= 0
  ack= 0
  dataofs= None
  reserved= 0
  flags= S
  window= 8192
  chksum= None
  urgptr= 0
  options= [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4294693388, 0)), ('NOP', None), ('WScale', 6), (30, b'\x10\x03\xc1\x1c\x95\x9b\x81R_1')]

>>> tcp.show2()
WARNING: option [30] is not string.
WARNING: option [30] is not string.
###[ TCP ]### 
  sport= ftp_data
  dport= http
  seq= 0
  ack= 0
  dataofs= 10
  reserved= 0
  flags= S
  window= 8192
  chksum= 0x5792
  urgptr= 0
  options= [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4294693388, 0)), ('NOP', None), ('WScale', 6)]

>>> tcp.show()
###[ TCP ]### 
  sport= ftp_data
  dport= http
  seq= 0
  ack= 0
  dataofs= None
  reserved= 0
  flags= S
  window= 8192
  chksum= None
  urgptr= 0
  options= [('MSS', 1460), ('SAckOK', b''), ('Timestamp', (4294693388, 0)), ('NOP', None), ('WScale', 6), (30, b'\x10\x03\xc1\x1c\x95\x9b\x81R_1')]

```

`tcp.show2()` shows me that these options are stripped and this warning is displayed: ```WARNING: option [30] is not string.
WARNING: option [30] is not string.```

**Comment by gpotter2** [comment]
> Scapy with Python3 strips unknown TCP options while it is not doing that with Python2.

Hmmmm,

could you return what
```python
print(scapy.VERSION)
```
says, when you are importing python (in your file)

Thanks !

**Comment by matttbe** [comment]
Hi @gpotter2 

Thank you for your comment.

I also have the problem with the scapy cli, when crafting packet. With it, I have this:

```
>>> print(scapy.VERSION)
2.4.0
```

**Comment by matttbe** [comment]
@gpotter2 I guess that in this file: https://github.com/secdev/scapy/blob/master/scapy/layers/inet.py#L342
We should have this:
```python
if not isinstance(oval, bytes):
```

(`bytes` instead of `str`)

**Comment by gpotter2** [comment]
Thanks for reporting & finding a fix !

Mind submitting a PR ?

You may also use `if not isinstance(oval, (str, bytes)):` to be sure not to break anything

**Comment by matttbe** [comment]
> Thanks for reporting & finding a fix !

That's the least I can do! :)

> Mind submitting a PR ?

Just did in #1460

> You may also use `if not isinstance(oval, (str, bytes)):` to be sure not to break anything

Thank you for the recommendation. I can do that if you prefer. Do you prefer me to wait for travis to finish with the current version (only with `bytes`) or should I change that now?

**Comment by matttbe** [comment]
> > You may also use `if not isinstance(oval, (str, bytes)):` to be sure not to break anything
> 
> Thank you for the recommendation. I can do that if you prefer. Do you prefer me to wait for travis to finish with the current version (only with `bytes`) or should I change that now?

Indeed, you were right, I was breaking stuff, thank you :)
