### ISSUE TITLE
When interface names are too long read_routes() with `exceptions.OSError: Device not configured`

### ISSUE THREAD

**Issue by hellais** [secdev/scapy#147]
It seems like this issue was already [reported on the bitbucket repository](https://bitbucket.org/secdev/scapy/issues/5106/oserror-device-not-configured) and it seems to mainly be affecting OSX users when they are using virtualbox.

The fix proposed inside of the that ticket, though actually doesn't fully address the core of the issue.

Looking into this a bit more it seems like the problem has to do with a bug inside of netstat and the fact that it truncates the netif column in when running `netstat -nr`.

In theory `netstat -nrW` is meant to over come this (the docs say "-W    In certain displays, avoid truncating addresses even if this causes some fields to overflow."), though this is a lie and still leads to the netif field being truncated.
For reference these are the bugs reporting this issue on FreeBSD:

* https://lists.freebsd.org/pipermail/freebsd-bugs/2014-April/055732.html
* https://www.mail-archive.com/freebsd-bugs@freebsd.org/msg07205.html

It looks like a fix for this was submitted to FreeBSD (https://svnweb.freebsd.org/base?view=revision&revision=290367), though probably most platforms don't yet ship an up to date version of netstat.

I did a bit of research into how this can possibly be solved, but from the looks of it there is no way to extract the correct interface name on platforms where netstat doesn't fully respect the `-W` option.
I am thinking that since this leads to scapy basically being unusable on platforms where this bug occurs it's perhaps better to wrap calls to `scapy.arch.get_if_addr()` with a try except and when a `OSError: Device not configured` error is thrown, hence leading to the truncated interfaces from being ignored when reading the routes.

Thoughts?

**Comment by guedou** [comment]
Fixed in PR #260
