### ISSUE TITLE
manpage fixes proposititions from doclifter

### ISSUE THREAD

**Issue by phil777** [secdev/scapy#1476]
This is automatically generated email about markup problems in a man
page for which you appear to be responsible.  If you are not the right
person or list, please tell me so I can correct my database.

See http://catb.org/~esr/doclifter/bugs.html for details on how and
why these patches were generated.  Feel free to email me with any
questions.  Note: These patches do not change the modification date of
any manual page.  You may wish to do that by hand.

I apologize if this message seems spammy or impersonal. The volume of
markup bugs I am tracking is over five hundred - there is no real
alternative to generating bugmail from a database and template.

--
                             Eric S. Raymond

Problems with scapy.1:

Invalid or unterminated font escape.

```
--- scapy.1-unpatched	2018-04-17 20:07:54.884035979 -0400
+++ scapy.1	2018-04-17 20:12:07.243538518 -0400
@@ -73,7 +73,7 @@
 
 .SH FILES
 \fB$HOME/.scapy_prestart.py\fR
-This file is run before scapy core is loaded. Only the \fb\conf\fP object 
+This file is run before scapy core is loaded. Only the \fBconf\fP object 
 is available. This file can be used to manipulate \fBconf.load_layers\fP 
 list to choose which layers will be loaded:
 
@@ -100,11 +100,11 @@
 .LP
 Test the robustness of a network stack with invalid packets:
 .nf
-sr(IP(dst="172.16.1.1", ihl=2, options="\verb$\x02$", version=3)/ICMP())
+sr(IP(dst="172.16.1.1", ihl=2, options="\everb$\ex02$", version=3)/ICMP())
 .fi
 
 .LP
-Packet sniffing and dissection (with a bpf filter or thetereal-like output):
+Packet sniffing and dissection (with a bpf filter or tshark-like output):
 .nf
 a=sniff(filter="tcp port 110")
 a=sniff(prn = lambda x: x.display) 
```

**Comment by gpotter2** [comment]
It would be a good opportunity to make the man doc more complete + update the links, startup options....

**Comment by gpotter2** [comment]
Should be fixed in https://github.com/secdev/scapy/pull/1528

**Comment by gpotter2** [comment]
@guedou @phil777 @p-l- Should any of you contact back the [doclifter owner](mailto:esr@thyrsus.com) and signal the update ?
