### ISSUE TITLE
output format of hexdump changed

### ISSUE THREAD

**Issue by mar2345** [secdev/scapy#1478]
#### Brief description
output format of function hexdump() changed v2.3.3 vs. v2.4
PLEASE keep org. format

#### Environment
scapy 2.3.3   vs. scapy 2.4

#### How to reproduce
 p=Ether()/IP()
 hexdump(p)

#### Actual result
0000  FFFFFFFFFFFF00000000000008004500 ..............E.
0010  00140001000040007CE77F0000017F00 ......@.|.......
0020  0001                             ..
>>> 

#### Expected result
as Scapy 2.3.3
0000   FF FF FF FF FF FF 00 00  00 00 00 00 08 00 45 00   ..............E.
0010   00 14 00 01 00 00 40 00  7C E7 7F 00 00 01 7F 00   ......@.|.......
0020   00 01                                              ..
>>> 

#### Related resources
hexdump.\_\_name\_\_   ->   'hexdump'
hexdump.\_\_module\_\_ ->  'scapy.utils'
utils.py

**Comment by gpotter2** [comment]
Hi !

Sorry for the very late answer. This is indeed unwanted and fixed through https://github.com/secdev/scapy/issues/1522
