### ISSUE TITLE
is Profinet DCP support ?

### ISSUE THREAD

**Issue by yanzixiang** [secdev/scapy#1492]
I saw those files to support Profinet in contrib:

https://github.com/secdev/scapy/blob/master/scapy/contrib/pnio.py
https://github.com/secdev/scapy/blob/master/scapy/contrib/pnio_rpc.py
https://github.com/secdev/scapy/blob/master/scapy/contrib/pnio_rtc.py

in pnio.py, we defined some packet kind,
but how to get the futher information ?

```python3
PNIO_FRAME_IDS = {
    0x0020: "PTCP-RTSyncPDU-followup",
    0x0080: "PTCP-RTSyncPDU",
    0xFC01: "Alarm High",
    0xFE01: "Alarm Low",
    0xFEFC: "DCP-Hello-Req",
    0xFEFD: "DCP-Get-Set",
    0xFEFE: "DCP-Identify-ReqPDU",
    0xFEFF: "DCP-Identify-ResPDU",
    0xFF00: "PTCP-AnnouncePDU",
    0xFF20: "PTCP-FollowUpPDU",
    0xFF40: "PTCP-DelayReqPDU",
    0xFF41: "PTCP-DelayResPDU-followup",
    0xFF42: "PTCP-DelayFuResPDU",
    0xFF43: "PTCP-DelayResPDU",
}
```

@guedou
@smainand

**Comment by smainand** [comment]
Hello,
The Profinet protocol is not fully supported, and some constants are simply specified on an indicative basis.
If you are interested in completing the support of Profinet, you should look at the PR #443, which proposes a rewrite that looks promising.
Seb.
