### ISSUE TITLE
enhancment of PPPoED class

### ISSUE THREAD

**Issue by lidllohntsich** [secdev/scapy#1496]
Scapy does not support proper handling of PPPoE tags, neither setting nor desecting is
supported. Instead hex data has to be used. (PPPoE tags are handled as raw data)

I tried to enhance the class PPPoED() in scapy.layers.ppp.py at least for the PPPoE tags
'Service Name' and 'Host Unique'. Unfortunately it's not fully working. (see attached
PADI.txt)
[PADI.txt](https://github.com/secdev/scapy/files/2137726/PADI.txt)

Neither the 'Service Name' nor the 'Host Unique' classes are handled correctly. (i tried to use the same mechanism which is already used in the IPCP option handling). But the respective classes are not detected properly.

It would great if you could help me to make it work. (updated in attachement)

[ppp.py.zip](https://github.com/secdev/scapy/files/2137681/ppp.py.zip)

**Comment by gpotter2** [comment]
Fixed by https://github.com/secdev/scapy/issues/1660
