### ISSUE TITLE
Sending L3 packets results in exception on Windows [bug]

### ISSUE THREAD

**Issue by zaheersyed** [secdev/scapy#1498]
While sending L3 packets on windows the below error is seen.
This issue is seen only with L3 packets. Other packets are sent successfully on Windows.

'module' object has no attribute 'AF_PACKET'

Sample code:

conf.L3socket = L3RawSocket .  #When this line is commented out the exception is not seen but this line is needed to be able to send L3 packets  
send(packet[IP])

Scapy version:  Version 2.3.3

**Comment by p-l-** [comment]
Why do you need to change `conf.L3socket`? `send()` sends layer 3 packets out of the box.

Also, if you have an exception, it would probably be helpful to post it with your bug report...

**Comment by gpotter2** [comment]
Also, `Version 2.3.3` is old
