### ISSUE TITLE
utf-8 error

### ISSUE THREAD

**Issue by pintman** [secdev/scapy#150]
The following error occured in OpenSuse 13.2. It seems there are some umlauts in /etc/services that caused the error. Changing line 110 in scapy/data.py in load_services(filename) from

    f=open(filename)

into 

    f=open(filename, encoding='latin1')

solved the problem for me.

Here is the error message:

Traceback (most recent call last):
  File "/home/marco/tmp/tmp.py", line 1, in <module>
    from scapy.all import sniff
  File "/usr/lib/python3.4/site-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/lib/python3.4/site-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/lib/python3.4/site-packages/scapy/data.py", line 185, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/lib/python3.4/site-packages/scapy/data.py", line 111, in load_services
    for l in f:
  File "/usr/lib64/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 3269: invalid continuation byte

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this one! Can you post the faulty line from `/etc/services`?

**Comment by pintman** [comment]
I don't know where to look at. If position 3269 is meant to be 0xCC5 in hex, I can give the following dump from hexdump although I don't see a 0xe9 there.

00000ca0  20 50 72 6f 63 65 73 73  20 20 5b 42 65 72 6e 69  | Process  [Berni|
00000cb0  65 5f 56 6f 6c 7a 5d 0a  23 20 20 20 20 20 20 20  |e_Volz].#       |
00000cc0  20 20 20 20 20 20 20 20  20 20 20 34 2f 74 63 70  |           4/tcp|
00000cd0  20 20 20 20 20 20 20 20  55 6e 61 73 73 69 67 6e  |        Unassign|
00000ce0  65 64 20 0a 23 20 20 20  20 20 20 20 20 20 20 20  |ed .#           |

Searching for bye e9 yields to the following output

~$ hexdump -C /etc/services |grep 'e9 '
000a2cc0  5f 53 6f 6c 6c e9 5d 0a  23 20 20 20 20 20 20 20  |_Soll.].#       |
000bce20  5d 0a 69 63 6c 2d 74 77  6f 62 61 73 65 39 20 20  |].icl-twobase9  |
000bce60  6c 2d 74 77 6f 62 61 73  65 39 20 20 20 20 20 20  |l-twobase9      |
000bce80  69 63 6c 2d 74 77 6f 62  61 73 65 39 20 20 5b 4a  |icl-twobase9  [J|
000e4160  20 20 46 41 55 43 4f 4e  4e 45 54 20 49 6e 67 e9  |  FAUCONNET Ing.|
00121ba0  6e 5f 44 5f 53 6f 6c 6c  e9 20 20 20 20 20 20 20  |n_D_Soll.       |
00121bc0  6c 6c e9 20 20 20 20 20  20 20 20 20 20 20 20 56  |ll.            V|
00121e30  6e 64 65 72 65 72 20 20  20 20 20 20 20 53 e9 62  |nderer       S.b|
00125230  20 20 20 20 20 20 20 20  20 20 20 20 53 74 e9 70  |            St.p|

Maybe some of this output might help.

**Comment by p-l-** [comment]
You seem to be using Python 3, Scapy only works with Python 2.5 to 2.7. If you're using Scapy3k, please report the bug there.

**Comment by pintman** [comment]
OK. I opened an issue here: https://github.com/phaethon/scapy/issues/90

Hopefully this is the right place.
