### ISSUE TITLE
Custom keyboardinterrupt handling

### ISSUE THREAD

**Issue by H5a337230** [secdev/scapy#1507]
I am using scapy as core of my tool, everything is ok but, i want to handle keyboardinterrupt(ctrl+c) in my own way.
With a simple search i find out that you handled that with just with a ```pass``` statement in sendrecv.
I used an exception to handle ctrl+c even used signal to do that,  but it seems ```pass``` statement will not let me to handle in my own way.
Is there any way to do this or i should modify sendrecv handling part and recompile scapy?

**Comment by gpotter2** [comment]
We currently have no ways of handling such a thing.

However, if you are not using the `stop_filter` or `count` arguments, scapy cannot stop sniffing by other ways than ^C, which means that you know that when the function returns, ^C has been pressed.

In what ways would you require such a feature ? If it is really blocking we may consider adding it

**Comment by H5a337230** [comment]
As I know, `stop_filter` is used when i want to define a condition, and when that condition happens, scapy will stop and `count` means that after specified count number of packets it will stop(0 equals infinit). but what I want is that, when user hit ^C, scapy stops what it doing and fallback to the main function written by me then raise another  function

I don`t know, maybe its not related to scapy, but I thought that, you are best choice to ask this question
