### ISSUE TITLE
scapy/__init__py: changing git_archive_id

### ISSUE THREAD

**Issue by blshkv** [secdev/scapy#1520]
Hi, we are experiencing a strange issue with the current ```git_archive_id``` variable, see the following line:
https://github.com/secdev/scapy/blob/master/scapy/__init__.py#L81 

The initial bug report is filled at our tracker:
https://github.com/pentoo/pentoo-overlay/issues/287

Somehow, this variable changes in time and we have seen different values. Below are just few examples:
"```c32159d45  (HEAD -> master)```" and "```c32159d45```"

the last one is "```e3a2a80c9  (refs/pull/1508/head)```".

In the next line, you generate a checksum using ```sha1 = git_archive_id.strip().split()[0]``` which will strip the tail and use the commit number only.

However, it generates an archive with a different checksum if we (at Pentoo)  download the latest snapshot of the tool using a commit as reference like in the following link:
https://github.com/secdev/scapy/archive/e3a2a80c9a63861bcbe7f24c004d0446d59106b7.tar.gz

Could you fix the format or strip it earlier so that the archive's checksum would not change please?

Thank you

**Comment by gpotter2** [comment]
Hi ! what do you think of https://github.com/secdev/scapy/pull/1521

**Comment by blshkv** [comment]
yeap, that should fix it
