### ISSUE TITLE
error while using hexraw()

### ISSUE THREAD

**Issue by urbi001** [secdev/scapy#1525]
Welcome to Scapy (3.0.0)
>>> fname=rdpcap('mitm_channel2_2nd_exp.pcap')
>>> pkt=fname[0]
>>> hexdump(pkt)
0000   00 00 38 00 2F 40 40 A0  20 08 00 A0 20 08 00 00   ..8./@@. ... ...
0010   C0 F0 C0 18 00 00 00 00  10 02 71 09 A0 00 E1 00   ..........q.....
0020   00 00 00 00 00 00 00 00  01 F0 C0 18 00 00 00 00   ................
0030   16 00 11 03 E1 00 E1 01  80 00 00 00 FF FF FF FF   ................
0040   FF FF B8 27 EB AF EC BA  B8 27 EB AF EC BA D0 50   ...'.....'.....P
0050   83 F1 C7 1F 00 00 00 00  64 00 11 05 00 05 50 69   ........d.....Pi
0060   5F 41 50 01 08 82 84 8B  96 24 30 48 6C 03 01 02   _AP......$0Hl...
0070   05 04 01 02 00 00 07 06  55 53 20 01 0B 1E 20 01   ........US ... .
0080   00 23 02 13 00 2A 01 00  32 04 0C 12 18 60 30 14   .#...*..2....`0.
0090   01 00 00 0F AC 04 01 00  00 0F AC 04 01 00 00 0F   ................
00a0   AC 02 0C 00 2D 1A 21 00  1F FF 00 00 00 00 00 00   ....-.!.........
00b0   00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
00c0   3D 16 02 08 00 00 00 00  00 00 00 00 00 00 00 00   =...............
00d0   00 00 00 00 00 00 00 00  7F 01 04 DD 09 00 10 18   ................
00e0   02 00 00 0C 00 00 DD 18  00 50 F2 02 01 01 80 00   .........P......
00f0   03 A4 00 00 27 A4 00 00  42 43 5E 00 62 32 2F 00   ....'...BC^.b2/.
0100   66 89 28 9B                                        f.(.
>>> hexraw(pkt)
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
NameError: name 'hexraw' is not defined
>>>

**Comment by guedou** [comment]
You are using an incorrect Scapy version. Please update to the code used in this repository.
