### ISSUE TITLE
Finishing vtp.py

### ISSUE THREAD

**Issue by jaredwelsh** [secdev/scapy#1535]
Finishing the VLAN Trunk Protocol at [vtp.py](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/contrib/vtp.py)

Todo:
       - Join messages
       - RE MD5 hash calculation
       - Have a closer look at 8 byte padding in summary adv.
       - h2i function for VTPTimeStampField
       - add length of packet

Reference:
[cisco vlan trunk protocol](http://www.cisco.com/en/US/tech/tk389/tk689/technologies_tech_note09186a0080094c52.shtml)

**Comment by guedou** [comment]
I do not understand why you opened this issue. Can you po code some explanations?

**Comment by guedou** [comment]
I understand now =)
The explanation was missing from your first post.

**Comment by guedou** [comment]
@jaredwelsh any update?

**Comment by guedou** [comment]
Moved to #399
