### ISSUE TITLE
No interface for loading external layers

### ISSUE THREAD

**Issue by wasilukm** [secdev/scapy#1540]
Currently (<=2.4.0) all layer extensions must be copied to `scapy/layers` and added to global `config.py` which makes distributing and using of external layers complicated.

Please add an interface which will allow scripts to load external layers to scapy scope or consider making `_load()` from `main.py` public.

**Comment by guedou** [comment]
The contrib mechanism is a possible way to go: copy your layer to scapy/contrib/ then call load_contrib().

It is seems to fit your need. Otherwise, please provide more example of your use case.

**Comment by guedou** [comment]
That's a good way to do it =)
