### ISSUE TITLE
Got "Bad File Descriptor" in exe by Pyinstaller with nonconsole

### ISSUE THREAD

**Issue by Sean2379607955** [secdev/scapy#1546]
If I run pyinstaller without -nonconsole, it will run correctly but with a command window.
It seemed scapy can not run in exe without console.
Please help to find a way to run scapy without console.

**Comment by gpotter2** [comment]
Hi !

I will be looking into this issue. This has been confirmed by other stackoverflow users

**Comment by gpotter2** [comment]
Hi ! Could you please elaborate and give some reproducable example ? Thanks !
