### ISSUE TITLE
license clarification?

### ISSUE THREAD

**Issue by saobao913** [secdev/scapy#1547]
Hi,

I have a python project released under Apache 2.0 license and would like to use this project (released under GPL 2.0+)

What are the implications viz a viz,
1) combining licenses this way, 
2) combining licenses this way for Python projects?

Regards.

**Comment by gpotter2** [comment]
I am not an expert, but according to

> However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.
>This is an identical issue for both GPLv2 and GPLv3.

**Comment by gpotter2** [comment]
@p-l- You surely know more on this one than I do

**Comment by guedou** [comment]
No answer received.

**Comment by guedou** [comment]
The clarification was provided, and the text given by @gpotter2 is perfectly clear: it is not possible. There is no need to keep the issue open.
