### ISSUE TITLE
Special field for grouping fields in a packet?

### ISSUE THREAD

**Issue by fsch2** [secdev/scapy#1554]
Hi there,

I would like to logically group several fields into a collection of fields. The purpose is to enable people to easily create reusable groups of fields. The members are fields themselves and they need to be passed to the constructor. A first test with the following code seems to do what it should:

```python
class CollectionField(sf.Field):

    islist = True
    __slots__ = ["members"]

    def __init__(self, name, members):
        super().__init__(name, None)
        for member in members:
            assert isinstance(member, sf.Field)
        self.members =  members
        self.default = [member.default for member in self.members]
        self.sz = sum([member.sz for member in self.members])

    def addfield(self, pkt, s, val):
        for (member, val) in zip(self.members, val):
            s = member.addfield(pkt, s, val)
        return s
 
    def getfield(self, pkt, s):
        values = []
        for member in self.members:
            s, value = member.getfield(pkt, s)
            values.append(value)
        return  s, values
```

It can be used like this:

```python
class Test(scapy.packet.Packet):
    fields_desc = [ CollectionField("myCollection",
           [ scapy.fields.IntField("item0", 0xDEAD),
              scapy.fields.StrFixedLenField("item1", "teststring", 12),
              scapy.fields.IntField("item2", 0xBEEF)]
    )]

testobj = Test()
```

In this example, `testobj.myCollection` can be used to assign a list to the CollectionField or read the value of it. Which will also return list.

From a users perspective, it would however be much more intuitive, if one could access the members of the collection using the "."-access. Just like the fields can be accessed on a packet. In the example above, this would mean read/write access to the members of the collection by doing `testobj.myCollection.item0` (and item1, item 2 respectively).

Question 1: How could this be done? I would rather not modify in packet.py, only my implementation.
Question 2: Could this be of interest to the scapy code base?

**Comment by gpotter2** [comment]
I really would like to see re-useable group fields, which would allow some extra trickery (for instance in Bluetooth.py)

However I don’t think that it should be named, but rather like `PadField` or `ConditionalField`, a transparent group (with no name).

This will be achievable by editing `getfield` and `addfield` functions. See `MultipleTypeField` in fields.py, which does not have the same behavior but is based on the same principle

**Comment by p-l-** [comment]
Could you use a constant list of fields?
```Python
COLLECTION_FIELDS = [
    scapy.fields.IntField("item0", 0xDEAD),
    scapy.fields.StrFixedLenField("item1", "teststring", 12),
    scapy.fields.IntField("item2", 0xBEEF),
]

class Test(scapy.packet.Packet):
    fields_desc = [Field1(...), Field2(...)] + COLLECTION_FIELDS + [Field3(...)]
```

**Comment by fsch2** [comment]
Thanks a lot for the replies. Until then, I did not fully understand the `PacketField`. Now that I know about the capabilities, I do not think that a CollectionField is absolutely necessary.
