### ISSUE TITLE
Define DHCP6 IA-options

### ISSUE THREAD

**Issue by aebrow4** [secdev/scapy#1556]
Hello, I'm interested in helping out with this issue from [roadmap](https://github.com/secdev/scapy/issues/399).

From the code it isn't obvious to me what the problem is - can you explain what needs to be done?

https://github.com/secdev/scapy/blob/master/scapy/layers/dhcp6.py#L352

**Comment by gpotter2** [comment]
Hmm, so if you have a look at the RFC of this layer:
https://tools.ietf.org/html/rfc3315#section-22.6

You will notice that nothing says what exactly is “IAadd-options” (it’s type, content...)

The todo means to crouch the internet, maybe wireshark code (useally a very good source), to find what this field should be (current is only a StrFieldLen == we don’t know)

**Comment by guedou** [comment]
Implemented by #1945
