### ISSUE TITLE
"Cannot read wireshark manuf database" on macOS 

### ISSUE THREAD

**Issue by montblanc18** [secdev/scapy#1561]
Hi, I start to use scapy recently, and this is my first time to write an issue.

#### Brief description
I typed ```sudo issue```, but I got ```WARNING: Cannot read wireshark manuf database```.

#### Environment
- Scapy version: 2.4.0 (installed by pip)
- Python version: 3.6.1 (installed by pyenv)
- Operating System: macOS Sierra
- Wireshark: 2.6.2 (installed by MacPorts)

#### How to reproduce
```text
$ sudo scapy
Password:
WARNING: Cannot read wireshark manuf database
```
#### Actual result
Scapy cannot read wireshark manuf database.

#### Expected result
Scapy can read wireshark manuf database.

 #### Others
I checked scapy/data.py.
```python 
    IP_PROTOS = load_protocols("/etc/protocols")
    ETHER_TYPES = load_ethertypes("/etc/ethertypes")
    TCP_SERVICES, UDP_SERVICES = load_services("/etc/services")
    MANUFDB = None
    for prefix in ['/usr', '/usr/local', '/opt', '/opt/wireshark']:
        try:
            MANUFDB = load_manuf(os.path.join(prefix, "share", "wireshark",
                                              "manuf"))
            if MANUFDB:
                break
        except (IOError, OSError):  # Same as above
            pass
    if not MANUFDB:
        log_loading.warning("Cannot read wireshark manuf database")
```
On the other hand, I confirmed bellow on my environment.
```text
$ sudo find /opt -name '*manuf*'
/opt/local/share/wireshark/manuf
```

Is it dupricated to use Wireshark installed by MacPorts?

**Comment by gpotter2** [comment]
Well we can’t check every location ever for wireshark’s manuf file.
You can create a python file in `$HOME/.scapy_prestart.py` and set

```
conf.prog.wireshark = “/path...”
```

This file will be loaded on scapy’s startup

**Comment by montblanc18** [comment]
Thank you for your reply.

I tried some case as below:
#### I got the msg 'WARNING: Cannot read wireshark manuf database'
- scapy 2.4.0 installed by ```pip install scapy``` & run by ```sudo scapy```+ create ```$HOME/.scapy_prestart.py```.

#### I did NOT get any warning.
- scapy Version git-archive.devb5a810c93 run by ```sudo ./run_scapy```.
- scapy Version 2.4.0.dev396 ruby by ```sudo ./run_scapy```.

Anyway, there is no problem to use scapy by this command in my case.
If I get new problem, I'll write new issue.
