### ISSUE TITLE
Cannot offer DHCP for Windows

### ISSUE THREAD

**Issue by daoxuanhung** [secdev/scapy#1565]
from scapy.all import DHCP_am
from scapy.base_classes import Net

dhcp_server = DHCP_am(iface='eth1', domain='example.com',
                      pool=Net('192.168.10.0/24'),
                      network='192.168.10.0/24',
                      gw='192.168.10.254',
                      renewal_time=600, lease_time=3600)
dhcp_server()

I wrote this code to make a DHCP server, But it just offers IP address to Linux clients, Windows clients get DHCP NAK after DHCP Request.

**Comment by guedou** [comment]
@gpotter2 any thoughts?

**Comment by gpotter2** [comment]
Can't reproduce. Here's the same snippet.

![image](https://user-images.githubusercontent.com/10530980/59556718-afab1700-8fc7-11e9-9ca7-466ab8811c19.png)

triggered via `ipconfig /renew`.

The main router is answering faster than the attacker, therefore an attack doesn't work, but the custom request is valid, and no NAK is issued. I'm also not sure what the issue mean:

> Windows clients get DHCP NAK after DHCP Request.

?! A NAK is only issued by the server. We never send those in the  `DHCP_am` (`BOOTP_am`). This is probably not scapy related.

**Comment by guedou** [comment]
Feel free to re-open the issue if you can explain if this is related to Scapy.
