### ISSUE TITLE
Route parsing fails after calling `setns`

### ISSUE THREAD

**Issue by pajowu** [secdev/scapy#1567]
#### Brief description

When run inside a network namespace with `setns` called form python, scapy fails to read the routes correctly.

#### Environment

- Scapy version: 2.4.0, 2.4.0.dev396
- Python version: 3.7, 3.6
- Operating System: Arch Linux

#### How to reproduce

1. Setup a network namespace
2. Add a inteface to that namespace
3. Run the attaches script

```
sudo ip netns add TEST
sudo ip link set netns TEST dev enp0s25
sudo python netns-crash.py
```

#### Actual result

```
Traceback (most recent call last):
  File "netns-crash.py", line 5, in <module>
    conf.route.resync()
  File "[...]/venv/lib/python3.7/site-packages/scapy/route.py", line 36, in resync
    self.routes = read_routes()
  File "[...]/venv/lib/python3.7/site-packages/scapy/arch/linux.py", line 275, in read_routes
    ifaddr_int = struct.unpack("!I", ifreq[20:24])[0]
UnboundLocalError: local variable 'ifreq' referenced before assignment
```

#### Expected result

The routes should be resynced, then a packet should be sent.
When running the script without the call to `conf.route.resync`, it crashed because it tries to send it on an interface only available in the main namespace

**Comment by gpotter2** [comment]
Well, it seems that scapy does not entirely work on 3.7, according to 
https://github.com/secdev/scapy/pull/1568

**Comment by pajowu** [comment]
Just checked and confirmed that the same crash occurs on python 3.6

**Comment by p-l-** [comment]
I'm not sure how this would happen in current development code (at least the bug about `ifreq` being undefined seems fixed in current development version, while it existed in 2.4.0):

```Python
        try:
            ifreq = ioctl(s, SIOCGIFADDR, struct.pack("16s16x", iff.encode("utf8")))  # noqa: E501
        except IOError:  # interface is present in routing tables but does not have any assigned IP  # noqa: E501
            ifaddr = "0.0.0.0"
        else:
            addrfamily = struct.unpack("h", ifreq[16:18])[0]
            if addrfamily == socket.AF_INET:
                ifaddr = scapy.utils.inet_ntoa(ifreq[20:24])
            else:
                warning("Interface %s: unknown address family (%i)", iff, addrfamily)  # noqa: E501
                continue
```

Do you get the same message with 2.4.0.dev396?

**Comment by pajowu** [comment]
Yes, I do:

```
Traceback (most recent call last):
  File "netns-crash.py", line 5, in <module>
    conf.route.resync()
  File "[...]venv/lib/python3.6/site-packages/scapy/route.py", line 36, in resync
    self.routes = read_routes()
  File "[...]venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 283, in read_routes
    ifaddr_int = struct.unpack("!I", ifreq[20:24])[0]
UnboundLocalError: local variable 'ifreq' referenced before assignment
```

The error occurs a bit below the code you pasted (line 283):

```
        # Attempt to detect an interface alias based on addresses inconsistencies  # noqa: E501
        dst_int = socket.htonl(int(dst, 16)) & 0xffffffff
        msk_int = socket.htonl(int(msk, 16)) & 0xffffffff
>        ifaddr_int = struct.unpack("!I", ifreq[20:24])[0]
        gw_str = scapy.utils.inet_ntoa(struct.pack("I", int(gw, 16)))
        metric = int(metric)
```

**Comment by p-l-** [comment]
You're totally right!

**Comment by p-l-** [comment]
Could you try to apply the patch from #1573 and report if it fixes your issue? Thanks!

**Comment by pajowu** [comment]
Yes, this fixes the crash
