### ISSUE TITLE
Dissect multiple occurrences of PacketField?

### ISSUE THREAD

**Issue by fsch2** [secdev/scapy#1572]
Hi all,

I recently learned about `PacketField` and what it can do. Great! Now, in a first test, I am was trying to use multiple `PacketField`s in the same fields_desc. The setup looks like this:

```python
class MyPacket(Packet):
    fields_desc = [ByteField("b1", 0)]

class Helper(Packet):
    fields_desc = [PacketField("f0", MyPacket(), MyPacket),
                   ByteField("f1", 0),
                   PacketField("f2", MyPacket(), MyPacket),
                   ByteField("f3", 0)]
```

There is an issue when dissecting a stream of bytes:

```python
p = Helper(b"\xDE\xAD\xBE\xEF")
print(p.__repr__())
```
This yields `<Helper  f0=<MyPacket  b1=222 |<Raw  load='\xad\xbe\xef' |>> |>`. So all the bytes after the first field are interpreted as the raw load of the first `PacketField`. The bytes are not used to fill the other three fields in the `Helper` class.

I am not saying this is a bug, but it is definitely not what I expected. Is this the intended behavior?

I assume, there are two ways to work around this:
1. I see in the definition of the `PacketField`, that this behavior can be changed by using a `PadField` at some point, but the exact use is not clear to me.
2. For more complicated setups, the `PacketListField` is an option.

Thanks in advance for any comments!

**Comment by gpotter2** [comment]
You must use

```python
class MyPacket(Packet):
    fields_desc = [ByteField("b1", 0)]

    def extract_padding(self, s):
        return "", s
```

to specify that the packet can be nested.

![image](https://user-images.githubusercontent.com/10530980/44479951-517d0400-a642-11e8-9b4b-5c6079246b06.png)

**Comment by fsch2** [comment]
Thanks, I will give it a try tomorrow!

**Comment by fsch2** [comment]
Works perfectly. Thanks!

**Comment by p-l-** [comment]
The "scapyest" way to do this would probably to simply add;
```Python
bind_layers(MyPacket, Padding)
```
You can also use `bind_bottom_up()`.
