### ISSUE TITLE
scapy-http not sniffing packets

### ISSUE THREAD

**Issue by vladic4t** [secdev/scapy#1583]
#### Brief description

while using scapy-http, I don't get any packet printing out on the console (not sniffing)

I was having a problem related to bytes and strings using scapy-http but resolved thanks by the following github issue: https://github.com/invernizzi/scapy-http/pull/27/files

#### Environment

- Scapy version: 3.0.0
- Python version: Python 3.6.6
- Operating System: Kali Linux (Debian)

< dump results that outline the issue, please format your code >

`#! python3.6

import scapy.all as scapy
import scapy_http.http

def sniff(interface):
    scapy.sniff(iface=interface, store=False, prn=process_sniffed_packet)

def process_sniffed_packet(packet):
    if packet.haslayer(scapy_http.http.HTTPRequest):
        print(packet.show())

sniff("eth0")`

**Comment by gpotter2** [comment]
Hi ! They are a few problems with your issue:

- we are not scapy-http and this won’t provide any support for it.
- scapy 3.0.0 is an outdated forked copy of scapy, which isn’t really scapy. Please uninstall it and install scapy from this github or from `pip install scapy`

**Comment by vladic4t** [comment]
Hi!
Thanks for your reply.
I think I have installed scapy through `pip3 install scapy` or through `pip install scapy-python3`, but most likely the first one.
If I reinstall scapy through `pip install scapy` this will not get me so far, since this will actually install the tool on my python 2.7 version which I don't prefer to use.

Thanks anyways, I will create another thread in the scapy-http github.

**Comment by gpotter2** [comment]
You can use `pip3 install scapy`

Anything but `scapy-python3` actually
