### ISSUE TITLE
New ISO-TP implementation, AttributeError with sr1

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#1591]
In `ISOTPNativeSocket.__init__` the attribute `self.ins` is not set anymore.
But `SuperSocket` accesses it, for example:
```python
def fileno(self):
    return self.ins.fileno()
```

Thus, `socket.sr1(packet)` will crash with:

> AttributeError: 'ISOTPNativeSocket' object has no attribute 'ins'

Simple script to reproduce:
```python
from scapy.all import *

conf.contribs['ISOTP'] = {'use-can-isotp-kernel-module': True}

from scapy.contrib.isotp import *
from scapy.contrib.automotive.uds import *

socket = ISOTPSocket('can0', 0x123, 0x456, basecls=UDS)
packet = UDS(b'\xC7\x01')
socket.sr1(packet)
```

@epozzobon

**Comment by gpotter2** [comment]
A simple rename of `can_socket` to `ins` will do

**Comment by akorb** [comment]
Same for `ISOTPSoftSocket`

`send` works, but `sr1` does not.

**Comment by akorb** [comment]
@polybassa 
What is the state of the fix?

**Comment by polybassa** [comment]
It's ready to merge
