### ISSUE TITLE
question

### ISSUE THREAD

**Issue by elliottecton** [secdev/scapy#1596]
#### Things to consider

I have check 1-3. The `gitter` link went to a blank page.

#### Brief description

I want to contribute dissectors for RPC, NFSv{3, 4.0, 4.1}, but I'm having a hard time connecting the 'packet creation' instructions with the dissector section. Definitely want to contribute the code I create back to scapy.

#### Environment

- Scapy version: Current
- Python version: 2.7 and 3.6
- Operating System: All. 

#### How to reproduce

NA

#### Actual result

NA

#### Expected result

Expect RPC and NFS layers to be dissected like they are in Wireshark

#### Related resources

NA

**Comment by gpotter2** [comment]
I don’t really get what your issue is, If you’re not sure how to create a protocol in scapy, you should have a look at http://scapy.readthedocs.io/en/latest/ 

The doc is quite complete and really helpful

**Comment by guedou** [comment]
Feel free to reopen.

BTW, I check and the gitter link woks fine. It could have been a temporary issue.
