### ISSUE TITLE
scapy/layers/vxlan.py needs a new binding

### ISSUE THREAD

**Issue by crserban** [secdev/scapy#1600]
Hi,

Cisco ACI uses a specific UDP destination port for VXLAN, which is port 48879. (http://static-void.io/aci-span-intro/)
Can you please add the following binding to scapy/layers/vxlan.py as soon as possible?
**bind_layers(UDP, VXLAN, dport=48879)**

Thank you!

**Comment by gpotter2** [comment]
Hi !
Thanks for the report ! Could you submit a PR and add it at the bottom of vxlan.py (next to other bindings ?)

Thanks !

**Comment by guedou** [comment]
Fixed by #1604
