### ISSUE TITLE
Avoid calculating L3/L4 checksum

### ISSUE THREAD

**Issue by mshteinbok** [secdev/scapy#1603]
Hi,
I saw that scapy calculates the checksum by itself once it sends the packet.
Would be great if there will be a flag to avoid calculating it and let the kernel/HW (that supports csum offload) to do that.

**Comment by guedou** [comment]
I do not believe that it is possible as Scapy is injecting raw packets, the kernel is involved regarding computations as routing or checksums.

Could you provide some code examples if you think that it is something that we can implement?

**Comment by mshteinbok** [comment]
I believe Scapy is the one that calculates the checksum and not the kernel - Am I wrong?

The checksum can be seen through show2() function prior the packet is sent.

Regards,
Michael

________________________________

**Comment by guedou** [comment]
Scapy computes checksums because it injecta raw packets.

Do you know to implement what you are requesting? I do not believe that it possible.

**Comment by mshteinbok** [comment]
Basically you can ask the kernel to comput that.
In case it is running over a NIC that supports checksum offload, the kernel will not calculate it either but let the HW to do it.

May that work?


Regards,
Michael

________________________________

**Comment by guedou** [comment]
Do you know how to do that while using raw packets?

**Comment by guedou** [comment]
Closed as this is not currently to inject RAW packets while having the kernel compute the checksums.
