### ISSUE TITLE
wirelen set on rdpcap but never updated before _writepacket

### ISSUE THREAD

**Issue by bensmith83** [secdev/scapy#1606]
#### Brief description

wirelen is set on rdpcap but never updated packet copy() or add_payload() or remove_payload(), so on write via either wrpcap() or PcapWriter() the wirelen can be shorter than caplen causing truncated packets.

#### Environment

- Scapy version: 2.4.0
- Python version: 3.6
- Operating System: macos 10.13.6

#### How to reproduce

pktdump = PcapWriter(write_path, append=True, sync=True) #same with wrpcap()
packets = rdpcap(path)
pktdump.write(packets[0])
pktdump.write(packets[1])
cooked = packets[2].copy()
cooked[TCP].remove_payload() #raw payload
cooked[TCP].add_payload(new_longer_payload)
pktdump.write(cooked)
pktdump.write(packets[3])

#### Actual result

I don't know how to share this exactly, but in the pcap at "write_path", the packet #2 is truncated to the length of the packet at that position in "path" pcap. the bytes in the "new_longer_payload" are there, but truncated at exact length of the original packet.
Original:
![image](https://user-images.githubusercontent.com/7976816/45652066-63b35c00-baa1-11e8-9390-6b88a004cc43.png)
New:
![image](https://user-images.githubusercontent.com/7976816/45652022-44b4ca00-baa1-11e8-9225-8b85917eee50.png)

#### Expected result

I'd expect to see the whole string extending beyond the previous end of the packet. The test string I'm using is "Really Long String I'm adding to the packet data and should show up" and it's truncated after the 'p' in 'packet data'.

**Comment by guedou** [comment]
Thanks for the report! Here is a simpler way to reproduce the issue:
```
>>> wrpcap("test.pcap", [p1, p2])
>>> p1 = Ether()/IP()/UDP()/DNS()
>>> p2 /= Raw("abc")
>>> wrpcap("test.pcap", [p1, p2])
>>> rdpcap("test.pcap").summary()
Ether / IP / UDP / DNS Qry 
00:00:40:11:7c:bc > 45:00:00:2e:00:01 (0x7f00) / Raw
```

**Comment by guedou** [comment]
Could you share more information? I did not manage to reproduce this issue.

**Comment by guedou** [comment]
Issue closed as I cannot be reproduced.
