### ISSUE TITLE
Inconsisten hash value

### ISSUE THREAD

**Issue by bsloane1650** [secdev/scapy#1616]
#### Brief description

Value of hash(packet) is not consistent for equivalent packets.
Eg. It does not hold that pktA==pktB => hash(pktA)==hash(pktB)

This appears to be the result of working with different packets which are the same at higher layers. In the example below, the objects being compared are the IP layer, which are identical. However, their containing Ethernet layer differs.

#### Environment

- Scapy version: 7c61676aef950ca268eac480902dd91cb0abe3a4
- Python version: Python 2.7.15rc1
- Operating System: Ubuntu 18.04.1

#### How to reproduce
```
p1=Ether("\\&\n\x82'Z\x00\x00P]g\x96\x08\x00E\x00\x02\x18\x00\x00@\x00\x00\x11\x8ar\xc0\xa8\xb1\xba\xc0\xa8\xbbW\x88\x80\x11P\x02\x04\\\x99")
p2=Ether("\x00\x00P]g\xb6\\&\na\xd3\xca\x08\x00E\x00\x02\x18\x00\x00@\x00\x00\x11\x8ar\xc0\xa8\xb1\xba\xc0\xa8\xbbW\x88\x80\x11P\x02\x04\\\x99")
p1['IP']==p2['IP']
hash(p1['IP'])==hash(p2['IP'])
```

#### Actual result

```
>>> p1['IP']==p2['IP']
True
>>> hash(p1['IP'])==hash(p2['IP'])
False
```

#### Expected result

```
>>> p1['IP']==p2['IP']
True
>>> hash(p1['IP'])==hash(p2['IP'])
True
```

**Comment by gpotter2** [comment]
This behavior seems (to me) expected.

`hash()` is used by python to compare OBJECTS, thus 2 different objects shouldn’t have the same hash. It would be breaking lots of stuff to overwrite this behavior for general objects such as packets.

Your case is too restricted:
![ebfaf045-b090-4a10-8d0f-6e248f1625ae](https://user-images.githubusercontent.com/10530980/46244511-2378a580-c3e0-11e8-9340-dc3229cddad3.jpeg)

However, the scapy internal `hashret()` function will return the same thing for the same packets. But that’s a very different thing

**Comment by guedou** [comment]
Does this quick and dirty patch do the job?

```
diff --git a/scapy/packet.py b/scapy/packet.py
index d839c390..54568c94 100644
--- a/scapy/packet.py
+++ b/scapy/packet.py
@@ -1004,6 +1004,9 @@ class Packet(six.with_metaclass(Packet_metaclass, BasePacket,
         """DEV: returns a string that has the same value for a request and its answer."""  # noqa: E501
         return self.payload.hashret()
 
+    def __hash__(self):
+        return int(self.hashret().encode("hex"), 16)
+
     def answers(self, other):
         """DEV: true if self is an answer from other"""
         if other.__class__ == self.__class__:
```

**Comment by gpotter2** [comment]
Do we really care though ? What's the use case of `hash()` on packets ?!

**Comment by guedou** [comment]
If we can easily implement it, we should. However, I think that hashing a Packet is application dependent.

**Comment by p-l-** [comment]
I think `Packet` instances should not be hashable, since they are mutable.

From the [documentation](https://docs.python.org/2/glossary.html#term-hashable):
> An object is hashable if it has a hash value which never changes during its lifetime
And:
> All of Python’s immutable built-in objects are hashable, while no mutable containers (such as lists or dictionaries) are.

It is the case, by default, with Python 3, but not with Python 2. #2124 fixes that.
