### ISSUE TITLE
sniff enables PROMISC mode temporarily when sniff_promisc is False (SOLUTION INCLUDED)

### ISSUE THREAD

**Issue by brandonpoc** [secdev/scapy#1623]
OS: Linux (other UNIXes too?)
NOTE: I'm too lazy to clone it, make the mods, issue a pull request etc; the fix is quick.

The problem: calls to sniff() enter promiscuous mode very shortly even if conf.sniff_promisc is disabled, when 'filter' is given to sniff(). This is because the call to the L2 socket routines call attach_filter in arch/linux.py, which is calling os.popen() with tcpdump in order to open the tcpdump process and get some information for the rest of the function. As a result, the desired device(s) go into promiscuous mode very shortly until tcpdump exits.  This is seen simply by tail'ing the kernel log and executing the sniff(iface='whatever', filter='dst port 1000') function.

The fix: In the call to os.popen() that executes tcpdump, add the argument "-p" to the parameters if sniff_promisc is disabled. '-p' tells tcpdump to not go into PROMISC mode. NOTE: the position of the promisc setting in 'conf' might need to be changed too.

They generate the same output, except with -p promiscuous mode is never entered and has the programmer's desired intention translated over to that short tcpdump execution.

**Comment by guedou** [comment]
Thanks! PR #1653 proposes a fix.
