### ISSUE TITLE
Issue in capturing pcap file, intermittently,  in latest scapy code.

### ISSUE THREAD

**Issue by JeevanNailwal** [secdev/scapy#1632]
#### Issue

Trying to catch the pcap of packets generated from scapy using sniff command. I am stopping pcap capture by setting a thread event while call of stop_capture functionality. At the time of stop, I am using wrpcap function to write the captured packets in a pcap file. 

#### Brief description

At odd number of instance, I amgetting empty pcap file while on even number of instance, getting the proper file. please see the attached pcap_files.tar.gz file.

My code snippet is also attached (in txt file)

[pcap_files.tar.gz](https://github.com/secdev/scapy/files/2453673/pcap_files.tar.gz)
[scapy_pcap_code_snippet.txt](https://github.com/secdev/scapy/files/2453674/scapy_pcap_code_snippet.txt)

- Scapy version: 2.4
- Python version: 3.4
- Operating System: ubuntu

#### How to reproduce
Command used to produce the packets:

dummy_pkt = ether/ip/tcp

payload_data = None

if (len(dummy_pkt)) < (frame_len):
   if 'pattern' in payload:
       data = (payload["pattern"].encode("utf-8")).decode("hex")
   else:
       data = "\x00"

   size_data = len(data)
   payload_data = data * (((frame_len - len(dummy_pkt))/size_data))

pkt = ether/ip/tcp/payload_data

where frame_len is the size of frame which i want in my network.

**Comment by JeevanNailwal** [comment]
Hi everyone, i am stuck at this issue and unable to move forward. Can someone please help me out here?

**Comment by guedou** [comment]
Could you provide a small example that triggers your issue? I had looked at your code snippet but I can't invest time trying to modify it to try to reproduce this issue.

**Comment by JeevanNailwal** [comment]
Hi, thanks for the notice, I made a snapshot of the program to generate the packet stream.
generate_packet(frame_len, port_name):
    dummy_pkt = Ether()/IP()/TCP()
    if (len(dummy_pkt)) < (frame_len):
       data = "\x00"
       payload_data = data * ((frame_len - len(dummy_pkt)))

   pkt = Ether()/IP()/TCP()/payload_data
   sendp(pkt, count = 10,  iface = port_name)

In a seperate thread, I am sending command to start the pcap capture and stop the pcap capture command. I updated the pcap capture code too, attached below
[updated_scapy_pcap_code_snippet.txt](https://github.com/secdev/scapy/files/2467289/updated_scapy_pcap_code_snippet.txt)


One more correction, python version which i ma using is 2.7.10

**Comment by p-l-** [comment]
Can you format your issue correctly? Please have a look at the Github [markdown documentation](https://guides.github.com/features/mastering-markdown/) and edit your comments. That would be much easier for us to help you.

**Comment by guedou** [comment]
I cannot reproduce.

Please reopen if you can provide an example that exhibit an issue with Scapy.
