### ISSUE TITLE
Can't pip install https://github.com/secdev/scapy on Kali 

### ISSUE THREAD

**Issue by Mr-P3rry** [secdev/scapy#1636]
I'm running kali version
Linux kali 4.18.0-kali1-amd64 #1 SMP Debian 4.18.6-1kali1 (2018-09-10) x86_64 GNU/Linux

when i run 
_pip install https://github.com/secdev/scapy_

it gives me this error
Collecting https://github.com/secdev/scapy
  Downloading https://github.com/secdev/scapy
     / 204kB 963kB/s
**Cannot unpack file /tmp/pip-sJ8wey-unpack/scapy (downloaded from /tmp/pip-0B1CKi-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-0B1CKi-build**

**Comment by guedou** [comment]
You need to add git+ in front of the URL.
