### ISSUE TITLE
when writing packet in pcap file in this way pkt[1]["IP"].fields['src'] = '0.0.0.0' no change was found in modified packet

### ISSUE THREAD

**Issue by surya1104** [secdev/scapy#1644]
I am reading pcap and trying to modify it dynamically 
pkt= rdpcap("\\Temp\\GTP.pcap")
val = ["src","dst"]
            
            for v in val :
                  pkt[1]["IP"].fields['src'] = '0.0.0.0' 
wrpcap("\\Temp\\modified.pcap",pkt)

While writing it no changes are  seen

But same code is working fine when i am chaging code as below.
   for v in val :
                  pkt[1]["IP"].src = '0.0.0.0' 

I am thinking issue during the writing of file.

**Comment by guedou** [comment]
Please use `pkt[IP].src = "0.0.0.0"` instead.

**Comment by surya1104** [comment]
pkt[IP].src = "0.0.0.0" is working is already tried it .But i need to fields dynamically
v= [ 'src','dst']
  for v in val :
              pkt[1]["IP"].fields[v] = '0.0.0.0

**Comment by guedou** [comment]
If you are not happy with my answer don't give me a thumb down! You opened an issue to ask a question without providing any useful information that we can use to help you.

Use:
```
> >>> p = IP()/ICMP()
> >>> p[IP].setfieldval("src", "1.2.3.4")
> >>> p
> <IP  frag=0 proto=icmp src=1.2.3.4 |<ICMP  |>>
```

Next time, please be kind and explain your problem clearly on gitter and not on the bugtracker.

**Comment by surya1104** [comment]
Thanks @guedou  above approach is working .
