### ISSUE TITLE
The import_hexcap function has some bugs

### ISSUE THREAD

**Issue by tcp80** [secdev/scapy#1650]
def import_hexcap():
    p = ""
    try:
        while True:
            l = input().strip()
            try:
                p += re_extract_hexcap.match(l).groups()[2]
            except:
                warning("Parsing error during hexcap")
                continue
    except EOFError:
        pass
    
    p = p.replace(" ","")
    return p.decode("hex")

1.Python3 does not support the decode("hex") method
2.Replace() is a string method, and the string has no decode method

**Comment by guedou** [comment]
Please conform to the issue template, if you want us to help you. It looks like you are using an outdated version of Scapy.

**Comment by tcp80** [comment]
> 如果您希望我们为您提供帮助，请遵守问题模板。看起来您使用的是过时的Scapy版本。
Sorry, I installed scapy with pip, it seems to be different from git.
