### ISSUE TITLE
Inconsistency in attach_filter handling

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1655]
We have an inconsistency in the way we handle Tcpdump calls:
- on Linux, if it fails (wrong filter or tcpdump not available), it prints a warning (or nothing depending on the case)
- on OSX, we properly raise an error

We also have duplicated `atach_filter` functions, which we could merge

**Comment by guedou** [comment]
You're correct. Except the way used to configure the filter, there are quite similar.
