### ISSUE TITLE
Twisted causing issue in  VirtualEnv 

### ISSUE THREAD

**Issue by this-is-r-gaurav** [secdev/scapy#1658]
While installing Scrapy to VirtualEnv Twisted Packages causing some issue. 
I am using pip3 install scrapy 
To install it, Globally it is installing well but i need it in a seprate project.

![screenshot from 2018-10-24 00-16-53](https://user-images.githubusercontent.com/25682376/47383881-48341480-d723-11e8-91d9-e196b1ce47d3.png)

**Comment by gpotter2** [comment]
Hi !
Here is `scapy` not `scrapy`
