### ISSUE TITLE
[Travis] flake8 was updated to 3.6.0

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1659]
flake8 tests are broken thanks to 'W504 line break after binary operator' and ' W605 invalid escape sequence'.

See https://travis-ci.org/secdev/scapy/jobs/445176377

**Comment by guedou** [comment]
@gpotter2 could you have a look at W605 ? It looks trivial to fix but only impact Windows. I don't want to silently breal something.

**Comment by gpotter2** [comment]
Done, see https://github.com/secdev/scapy/pull/1666

**Comment by gpotter2** [comment]
FTR see https://github.com/secdev/scapy/issues/1660
