### ISSUE TITLE
Possible bug - Using weird seq/ack value while TCP handshaking

### ISSUE THREAD

**Issue by Dry8r3aD** [secdev/scapy#1663]
#### Brief description

Main issue : Packet sent by Scapy script has weird seq/ack value, and cause TCP handshake fail.

#### Environment

- Scapy version: 2.4.0
- Python version: 3.4.2
- Operating System: 
  - Debian 8.5
  - Debian 3.16.7-ckt11-1+ap4 (2017-04-20) x86_64 GNU/Linux

#### How to reproduce
* Just simply run the script below
```Python
from scapy.all import *

seq = random.randint(5000,10000)
sport = random.randint(1024,65535)
dport = 80

# SYN
ip_packet = IP(dst='192.168.40.245')
syn_packet = TCP(sport=sport, dport=dport, flags='S', seq=seq, window=9600)

# SYN Send & SYNACK
synack = sr1(ip_packet/syn_packet)

# ACK
ACK = TCP(sport=sport, dport=dport, flags='A', seq=synack.ack, ack=synack.seq + 1, window=9600)

# ACK Send && response
res = sr1(ip_packet/ACK)
```

#### Actual result

Result - Packetdump from 192.168.40.245
![2018-10-25 4 26 49](https://user-images.githubusercontent.com/5144422/47482913-cfdc6900-d872-11e8-91b6-a6048d313613.png)
Result - PAcketdump from localhost(Where script is ran)
![2018-10-25 4 29 51](https://user-images.githubusercontent.com/5144422/47483047-38c3e100-d873-11e8-9efe-9f9181a6e504.png)

#### Expected result
* In the yellow box, seq should be 8904, and ack should be 2007624897(syn-ack's seq)
![yello](https://user-images.githubusercontent.com/5144422/47483141-758fd800-d873-11e8-8774-f9443fda9dd0.png)

This might not be a scapy library's bug, but I think there's a possibility, since the ACK packet layer I created has a right value for ack/seq, but packet had weird value.

Thank you :)

**Comment by Dry8r3aD** [comment]
FYI, I'am using virtualenv!

**Comment by Dry8r3aD** [comment]
I tested on more various env, and had the same result.

1. Ubuntu 18.04, no virtualenv
Python : 3.6.6
Scapy : 2.4.0

2. Ubuntu 18.04, no virtualenv
Python : 2.7.15
Scapy : 2.4.0

**Comment by uhei** [comment]
IMHO this is not a bug.

Your tcpdump has relative sequence numbers enabled (therefore 2 and 1). Furthermore to have a valid TCP handshake your ACK should increment the ack number (ack=synack.seq + 1) and not the seq number.

**Comment by Dry8r3aD** [comment]
Omg..! Thanks for the answers @p-l- @uhei 
I guess it's not a bug but my mistake.. 

I will close the issue!
