### ISSUE TITLE
scapy sniff multiple interfaces

### ISSUE THREAD

**Issue by proocho** [secdev/scapy#1671]
#### Description

I need to sniff on multiple interfaces simultaneously. I found in scapy documentation the following line:

`sniff(iface=["eth1","eth2"],` `prn=packet_handler)`

My question is: Can I somehow differentiate the network interface in packet_handler function? Do I need to create a thread for every interface?

#### Environment

-   Scapy version: `2.4.0`
-   Python version: `2.7.15`
-   Operating System: `Ubuntu 18.04`

Thank you for your answer in advance.

**Comment by gpotter2** [comment]
As of today, you can’t. Scapy will create several sockets (one for each interface), and sniff simultaneously on all of them.

You will need to either have several threads, either call something like

```python
a = conf.L2Socket(iface="eth0")
b = conf.L2Socket(iface="eth1")
while True:
    pkt1 = a.nonblock_recv()
    if pkt1:
        #...
    pkt2 = b.nonblock_recv()
    if pkt2:
        # ...
```

**Comment by santos-lucas** [comment]
i think pkt.summary() should be enought for you.
