### ISSUE TITLE
p0f module does not detect OS version (UNKNOWN)

### ISSUE THREAD

**Issue by sjosz** [secdev/scapy#1678]
When running the p0f module from Scapy with a Python script it does not detect the OS versions, it only shows UNKNOWN. The latest signature file is loaded to /etc/p0f/p0f.fp (from https://github.com/p0f/p0f/blob/master/p0f.fp):

#### How to reproduce
```
Run python3
from scapy.all import *
load_module("p0f")
sniff(prn=prnp0f, filter='tcp', iface='eth0')
```

#### Environment

-   Scapy version: `Scapy 2.4`
-   Python version: `3.6`
-   Operating System: `Ubuntu 16.04`

#### Actual result

```  -> 172.217.17.35:http (A)
192.168.0.8:45954 - UNKNOWN [237:64:1:*:N,N,T:AT:?:?] (up: 3712 hrs)
  -> 172.217.17.35:http (A)
172.217.17.35:http - UNKNOWN [0:57:0:40:.:.:?:?]
  -> 192.168.0.8:45954 (R)
172.217.17.35:http - UNKNOWN [0:57:0:40:.:.:?:?]
  -> 192.168.0.8:45954 (R)
```

#### Expected result

I would expect it to show which OS version is used. It works perfectly when I run the installed p0f version on Ubuntu.

```
.-[ 192.168.0.8/45956 -> 172.217.17.35/80 (syn) ]-
|
| client   = 192.168.0.8/45956
| os       = Linux 3.11 and newer
| dist     = 0
| params   = none
| raw_sig  = 4:64+0:0:1460:mss*20,7:mss,sok,ts,nop,ws:df,id+:0
|
`----
.-[ 192.168.0.8/45956 -> 172.217.17.35/80 (http request) ]-
|
| client   = 192.168.0.8/45956
| app      = ???
| lang     = none
| params   = none
| raw_sig  = 1:Host,User-Agent,Accept=[*/*]:Connection,Accept-Encoding,Accept-Language,Accept-Charset,Keep-Alive:curl/7.47.0
|
```

**Comment by sjosz** [comment]
I did some more tests, if I place the following files in de /etc/p0f directory it works: p0fo.fp, p0fr.fp, p0fa.fp .

However, these are old signature databases, is it possible to get it work with the latest signature database named p0f.fp ?

**Comment by gpotter2** [comment]
Feel free to use the gitter https://gitter.im/secdev/scapy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by guedou** [comment]
Moved to #399
