### ISSUE TITLE
Dummy Packet Pumping to the Network

### ISSUE THREAD

**Issue by swamyb3679** [secdev/scapy#1686]
#### Brief description:

Issue in transferring dummy packet into network, where listener is able to receive the data but it is in hexa-decimal format(not as string).

#### Environment:

-   Scapy version: 2.4.0
-   Python version: 3.6.6
-   Operating System: Ubuntu18.04

#### How to reproduce:

When i try to reproduce whatever the data was given in the following code, it is not reflecting the same in packet analyzer 'Wireshark'. Where the data is extracting in hexa-decimal format(not in string).

#### Code:

-----------------------------------------------------------------------------------------------------------------------
import sys
import scapy.all
import scapy.packet
import scapy.fields
import scapy.layers

class Details(Packet):
         
         name = "Packet Information"
         fields_desc=[StrField("Field_Data","")]

bind_layers(UDP,Details,sport=217,dport=217)
p=IP(dst="192.168.1.6")/UDP()/Details(Field_Data="Project Data Information")
p.show()
sr(p,iface="enp1s0")

-----------------------------------------------------------------------------------------------------------------------
#### Actual result:

Data (24 bytes)

      Data: 50726f6a656374204461746120496e666f726d6174696f6e
      [Length: 24]

![image](https://user-images.githubusercontent.com/44764046/48111023-75c9a380-e275-11e8-8e6a-b8bcf91329bb.png)

#### Expected result:

Data (24 bytes)

      Data: Project Data Information
      [Length: 24]

**Comment by p-l-** [comment]
Hi,

Could you format your code properly using Markdown? It is hard to read like that.

**Comment by guedou** [comment]
I dot not see any issue with Scapy or Wireshark. The string is sent in plain text, and is also received in plaintext as shown on your image.
