### ISSUE TITLE
Allow binary data for Obsolete/Unassigned TCP options 

### ISSUE THREAD

**Issue by ecthros** [secdev/scapy#1687]
#### Brief description

Arguments to TCP Options are not correctly parsed in python3, making it impossible to store certain values in undefined TCP Options.
This affects TCP Options. Note that it only affects python3, as it will work as intended in python2.

#### Environment
-   Scapy version: `scapy-2.4.0.dev561`
-   Python version: `Python 3.6.5`
-   Operating System: `Ubuntu 18.04`
#### How to reproduce

Use a TCP Option not defined in the TCPOptions dictionary in `scapy/scapy/layers/inet.py` and set the value to an unprintable ASCII character or characters.

```
from scapy.all import IP, TCP, Raw, send
pkt = IP(dst="127.0.0.1", src="127.0.0.1") / TCP() / Raw("message")
pkt["TCP"].options = [(57, '\xee\xee')]
send(pkt)
```

#### Actual result

Scapy will send the packet, but the following options are actually sent (found from Wireshark):

![image](https://user-images.githubusercontent.com/14065974/48043958-563c5900-e157-11e8-8f8b-921717a251a7.png)

#### Expected result
There should be only one option, `(Option-Kind=57, Option-Length=4, Payload='eeee')`
Note that this works as intended in python2:

![image](https://user-images.githubusercontent.com/14065974/48043997-8c79d880-e157-11e8-8c9d-866d9195afe4.png)

#### Potential fixes

Allow a bytes object to be passed in instead of a string. Using strings will automatically force unprintable characters, such as '\xee', to their ASCII representation (turning '\xee' in to 'î'). However, these characters cannot be converted back into their hexadecimal representation (for example, 'î' is converted into b'\xc3\xae'). Note that in the above screenshots, each '\xee' was converted to '\xc3\ae', yet the length of '\xee' is 1 and the actual string used is two bytes long. 

This is partly due to the `raw()` function in `scapy/compat.py` defaulting to the following call:
```return bytes(x, encoding="utf8")```
which does not return the correct values for values of x greater than 127.

**Comment by gpotter2** [comment]
On Python 3, bytes need a `b` 😄 

![image](https://user-images.githubusercontent.com/10530980/48304751-f0691c00-e51e-11e8-8f0b-65c3788e704d.png)

You need to use `pkt["TCP"].options = [(57, b'\xee\xee')]`
