### ISSUE TITLE
Sniffer WIFI beacons in 5 GHz 

### ISSUE THREAD

**Issue by victormanoly** [secdev/scapy#1691]
I have an application to sniffer the WIFI beacons and get some parameters from them. I'm using Python 2.7 on Ubuntu 18. For network beacons operating at 2.4 GHz, the application captures the beacon without problems. When the beacons are of networks in 5 GHz the application does not show the beacon (my wireless network card is dual band). The interesting thing is the following: in this last case, with the application open and without showing the 5 GHz networks, I go in the graphical interface of the Operating System to see the available wireless networks, and just at that moment, my application, unable to that moment of showing all the networks, begins to show them in the way they should be. The interface that I use for this is in monitor mode. My question is whether at the moment that through the OS we ask to show the wireless networks, it take any action to increase the sensitivity or gain of the wireless interface in order to see correctly all the available networks?

**Comment by guedou** [comment]
I do not understand how this is related to Scapy. Feel free to reopen if you can provide a specific Scapy issue, and a way to reproduce this behavior.

**Comment by victormanoly** [comment]
Well, I am using the "scapy" sniff function in an interface in monitor
mode, and for some reason, when I scan in another interface to know the
available networks, is that the sniff function is able to show the beacons
of networks operating in 5 GHz (before that no show any beacon in this
band). So, I think that the "scapy" sniff function is only able to provide
a greater sensitivity to the interface that is using it when this happens. I
would like to know if there is any way to get all the beacons without
having to perform any action on another interface.

**Comment by p-l-** [comment]
Scapy `sniff()` function will not change the current band your wireless adapter is tuned on.

Running a wireless network "scan" will make your adapter tune to all the bands to find available networks; if scapy (or another program like tcpdump or tshark/wireshark, for that matters) is sniffing at the same time, it will sniff beacons from the other bands.

This is totally expected: Scapy does not provide a tool to change the current wireless chan, you have to do this externally.
