### ISSUE TITLE
Tests: Vcan tests disabled on xenial

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1696]
This is a reminder that accordingly to: https://github.com/secdev/scapy/pull/1571

All vcan socket tests are now disabled on `xenial` builds by default, as the `vcan` module is not installed by default on the `xenial` travis builds (as of 11/2018)

**Comment by guedou** [comment]
@gpotter2 what do we need to do to check if the checks can now run? If it is still not possible, we can safely close this issue.

**Comment by guedou** [comment]
This is still not working on xenial =/

**Comment by gpotter2** [comment]
Travis have announced that they now support xenial builds: https://docs.travis-ci.com/user/reference/bionic/
