### ISSUE TITLE
import scapy.all slowness on Windows 10 (Scapy ver=2.4.0)

### ISSUE THREAD

**Issue by timmy8526** [secdev/scapy#1699]
#### Brief description

The simplest import scapy.all will take more than 5 sec to succeed somehow. 
And I have no idea where is the slowness come from so I cannot provide more info.
If you need more into, please let me know how to get enough info to debug this, thanks.

#### Environment

-   Scapy version: `2.4.0`
-   Python version: `3.6.5`
-   Operating System: `Windows 10 Pro 64-bit (10.0, Build 17134) `

#### How to reproduce

The scenario can be reproduced in this py file:
```
import datetime
print(datetime.datetime.now())
import scapy.all
print(datetime.datetime.now())

>>
2018-11-12 18:14:08.375769
2018-11-12 18:14:13.74180
```

**Comment by gpotter2** [comment]
If you start a Powershell, you’ll see that scapy takes about the same speed to start than it. M

We have to perform heavy Powershell calls to get the routes on start. You can try to use the latest GitHub versions, which has an improved loading time, or try to disable Powershell (Scapy will fall back on VBS, which is less accurate), by adding `conf.prog.powershell = None` to your `./scapy_startup.py` file (cf the [docs](http://scapy.readthedocs.io/en/latest/) )

**Comment by timmy8526** [comment]
I've downloaded the latest GitHub versions and try below:
```
import datetime
print(datetime.datetime.now())
import scapy.all as scapy
scapy.conf.prog.powershell = None
print(datetime.datetime.now())

>>> 
2018-11-14 10:11:08.419737
2018-11-14 10:11:12.171733
```

Which is faster but still took 4 sec ..
This is really slowing down my pytest which shall be completed in 1 sec but due to import scapy it takes 5 ~8 sec randomly. Is there any other way to speed up this to less than 1 sec?

**Comment by guedou** [comment]
Depending on your use case, you can only import the classes, functions, ... instead of using *
That will speed up some things.

**Comment by timmy8526** [comment]
@guedou sorry, I am afraid I didn't make my question clear enough.

I did try it.. but the slowness still exists.
I was trying to ask is there any other way to load this two classes without unnecessary importing so it can speed up my pytest as expectation.
```
import datetime
print(datetime.datetime.now())
from scapy.sendrecv import sniff
from scapy.layers.dhcp import DHCP
print(datetime.datetime.now())

>>>
2018-11-14 13:56:42.663986
2018-11-14 13:56:47.311021
```

**Comment by timmy8526** [comment]
Is there any other workaround/suggestion to speed up the importing processes? Please help .. Orz

**Comment by gpotter2** [comment]
You could try
```
from scapy.arch.windows import *
conf.prog.powershell = None # Enable VBS fallback
from scapy.all import *
```

But the real issue is that you should be loading scaly outside your pytest, or increase the timeout.

**Comment by p-l-** [comment]
You should probably use:
```Python
from scapy.sendrecv import sniff
from scapy.layers.dhcp import DHCP
```

But this will take about the same time anyway.

**Comment by timmy8526** [comment]
Thanks @p-l- , actually I had tried it in previous [comment](https://github.com/secdev/scapy/issues/1699#issuecomment-438548204), and yes, it did take the same time.

@gpotter2 I also tried to mock scapy inside pytest, but it didn't work due to 'import scapy' will be loaded before all unit tests started, there's no way to mock it. And even if I find a way to mock or to load scapy outside pytest, my unit test will become meaningless due to app's functionalities are tested by fake scapy.

Furthermore, I tried on Linux (ubuntu 18.04) and Windows Server 2012, both 'import scapy' only take 1 sec. I am wondering why it takes so much time on Windows 10 specifically.

**Comment by gpotter2** [comment]
They are a numerous amount of ways to mock scapy. It'll be hard to increase the boot time.

I can't really do much for that :/

**Comment by timmy8526** [comment]
In that case, I will try to figure find a workaround to resolve issue. Thank you for helping me on this issue.

**Comment by gpotter2** [comment]
This will be fixed by https://github.com/secdev/scapy/pull/1759
