### ISSUE TITLE
L2socket does not set the promiscuous mode

### ISSUE THREAD

**Issue by p-l-** [secdev/scapy#17]
`conf.L2socket` (at least on Linux) has no option to set the promiscuous 

This prevents `srp()` from getting answers when a sent packet has a source MAC address set to a value different from the device MAC address.

**Comment by guedou** [comment]
Could you provide an example ?

**Comment by p-l-** [comment]
I have found this why trying to help someone [on the mailing list](http://article.gmane.org/gmane.comp.security.scapy.general/5294).

Here is a simple way to reproduce:
```
>>> mac = RandMAC()._fix()
>>> srp(Ether(src=mac, dst=ETHER_BROADCAST)/ARP(hwsrc=mac, pdst="192.168.1.254"), timeout=3)
Begin emission:
Finished to send 1 packets.

Received 0 packets, got 0 answers, remaining 1 packets
(<Results: TCP:0 UDP:0 ICMP:0 Other:0>, <Unanswered: TCP:0 UDP:0 ICMP:0 Other:1>)
```

Now running a `tcpdump -ni eth0` in another shell to set the promiscuous mode:
```
>>> srp(Ether(src=mac, dst=ETHER_BROADCAST)/ARP(hwsrc=mac, pdst="192.168.1.254"), timeout=3)
Begin emission:
Finished to send 1 packets.
*
Received 1 packets, got 1 answers, remaining 0 packets
(<Results: TCP:0 UDP:0 ICMP:0 Other:1>, <Unanswered: TCP:0 UDP:0 ICMP:0 Other:0>)
```

**Comment by p-l-** [comment]
With the patch provided in #20, the above example works without the need to run a separate `tcpdump` process.
