### ISSUE TITLE
Throwing error while decrypting Ipsec using scapy

### ISSUE THREAD

**Issue by surya1104** [secdev/scapy#1701]
sa = SecurityAssociation(ESP, spi=0xc0000967, crypt_algo='AES-CBC', crypt_key='c8fa97e9e52b82afbd5846f0b24243')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/scapy/layers/ipsec.py", line 789, in __init__
    (crypt_algo, list(CRYPT_ALGOS)))
TypeError: unsupported encryption algo 'AES-CBC', try ['NULL']

**Comment by gpotter2** [comment]
Please use the issue template.

Your issue is that you don’t have cryptography installed (or you have an outdated version of cryptography / Scapy)
