### ISSUE TITLE
The filter of sniff function does not work properly

### ISSUE THREAD

**Issue by TonyPtolemy** [secdev/scapy#1711]
#### Brief description

I m executing the sniff with the following filter
But the sniff always catch some other protocol packets.
And other filter statements have no effect, too.
> pkt = sniff(filter='Tcp and port 53', count=50)

#### Environment

-   Scapy version: `2.4.0`
-   Python version: `Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32`
-   Operating System: `Windows 10 64 bit`

#### How to reproduce

> from scapy.all import *
> pkt = sniff(filter='Tcp and port 53', count=50)

#### Actual result

> <Sniffed: TCP:22 UDP:26 ICMP:0 Other:2>

#### Related resources

The following is the warning when I run scapy and my pip list
> WARNING: PyX dependencies are not installed ! Please install TexLive or MikTeX.
> WARNING: No route found for IPv6 destination :: (no default route?)
> WARNING: IPython not available. Using standard Python shell instead.
> AutoCompletion, History are disabled.
> WARNING: IPyton not available. On Windows, colors are disabled

> Package         Version
> --------------- -------
> asn1crypto      0.24.0
> cffi                   1.11.5
> cryptography   2.4.2
> cycler               0.10.0
> idna                 2.7
> kiwisolver        1.0.1
> matplotlib       3.0.2
> numpy            1.15.4
> pip                  10.0.1
> pycparser        2.19
> pyparsing        2.3.0
> pyreadline       2.1
> python-dateutil 2.7.5
> pywin32          224
> PyX                 0.14.1
> scapy              2.4.0
> setuptools      39.1.0
> six                   1.11.0
> winpcapy        1.0.2

Am I missing something in my filter? How I can avoid this problem?
Forgive my grammar mistake because my native language is not English.

**Comment by p-l-** [comment]
I don't know about Windows, but under Linux I get a warning `tcpdump: syntax error in filter expression: syntax error`.

The correct filter is `"tcp and port 53"` (or `"tcp port 53"`), with a lowercase "t".

Can you tell us if using the correct filter fixes this issue?

**Comment by TonyPtolemy** [comment]
> I don't know about Windows, but under Linux I get a warning `tcpdump: syntax error in filter expression: syntax error`.
> 
> The correct filter is `"tcp and port 53"` (or `"tcp port 53"`), with a lowercase "t".
> 
> Can you tell us if using the correct filter fixes this issue?

Thanks for your reply. Now sniff(filter='tcp') works properly.
But  sniff(filter='tcp and port 53') took a lot of time but couldn't catch one packet.
How can I solve this problem?

**Comment by TonyPtolemy** [comment]
> 我不知道Windows，但在Linux下我收到警告`tcpdump: syntax error in filter expression: syntax error`。
> 
> 正确的过滤器是`"tcp and port 53"`（或`"tcp port 53"`），小写“t”。
> 
> 您能告诉我们使用正确的过滤器是否修复了这个问题？

Ok, this issue has nothing to do with scapy, because my wireshark can't catch packet from port 53 either. But both of them are normal when catching other ports.
