### ISSUE TITLE
IndexError on import in _exec_query_ps() for interface description with newline

### ISSUE THREAD

**Issue by jimmbelll** [secdev/scapy#1718]
`from scapy.all import *`  fails with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy\all.py", line 18, in <module>
    from scapy.arch import *
  File "scapy\arch\__init__.py", line 73, in <module>
    from scapy.arch.windows import *  # noqa F403
  File "scapy\arch\windows\__init__.py", line 946, in <module>
    IFACES.load_from_powershell()
  File "scapy\arch\windows\__init__.py", line 834, in load_from_powershell
    ifaces_ips = get_ips()
  File "scapy\arch\windows\__init__.py", line 544, in get_ips
    ['Description', 'IPAddress']):
  File "scapy\arch\windows\__init__.py", line 243, in _exec_query_ps
    lines[-1] += sl[0].strip()
IndexError: list index out of range

```
The lines list is empty, raising the IndexError.

#### Environment

-   Scapy version: latest master (zip) pulled today (2018-11-28)
-   Python version: `2.7.15`
-   Operating System: `Windows 7: platform.platform() == 'Windows-7-6.1.7601-SP1'`
-   Powershell `$PSVersionTable.PSVersion`
```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

#### Detail
At the iteration raising IndexError, local variable `line` is `"for Windows x64"`. The previous line of windows powershell output has already yielded `['', 'Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter']`  on row 248 and cleared `lines` on row 249.

Oddly enough, the powershell command being sent:
```
Get-WmiObject Win32_NetworkAdapterConfiguration | select Description, IPAddress | fl | out-string -Width 4096
```
seems not produce a newline here.

> ...
> Description : Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
> IPAddress   :
> ...
> 

This fix seems to work: replace row 243 `lines[-1] += sl[0].strip()` with `if lines: lines[-1] += sl[0].strip()`

#### See Also
https://github.com/secdev/scapy/issues/400
https://github.com/secdev/scapy/issues/781

**Comment by gpotter2** [comment]
Hi,

Thanks a lot for reporting & analysis

Could you share a *(cropped)* but valid output of
```
Get-WmiObject Win32_NetworkAdapterConfiguration | select Description, IPAddress | fl | out-string -Width 4096
```

That does trigger the issue, so that we can add a unit test with your fix ?

**Comment by jimmbelll** [comment]
Seems like Windows PowerShell isn't regarding the "Out-String -Width 4096" part of the command, as discussed [here](https://social.technet.microsoft.com/Forums/Lync/en-US/b95be418-4893-4e2d-bf61-3bca5c89551b/avoid-line-wrap-in-powershell-output).

Cropped output from command-line run is in [gwo.txt](https://github.com/secdev/scapy/files/2629880/gwo.txt), attached, but it doesn't have the wrap.

The offending output from the POWERSHELL_PROCESS.query() command in _exec_query_ps(), that shows lines getting wrapped, is in [ps_query.txt](https://github.com/secdev/scapy/files/2629932/ps_query.txt), and it's valid python.

A test that handles ps_query.ps_output, as though it came from the POWERSHELL_PROCESS.query() call in  _exec_query_ps(), should be a valid test.

Hope that helps.

**Comment by jimmbelll** [comment]
Verified that the import of https://github.com/secdev/scapy/pull/1725 does not produce this particular issue. See https://github.com/secdev/scapy/issues/1727 for update.
