### ISSUE TITLE
IndexError on import in NetworkInterfaceDict.load_from_powershell() arch/windows

### ISSUE THREAD

**Issue by jimmbelll** [secdev/scapy#1727]
My environment produced https://github.com/secdev/scapy/issues/1718

Trying the latest commit. I now get this crash.

```
>>> from scapy.all import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "scapy\all.py", line 18, in <module>
    from scapy.arch import *
  File "scapy\arch\__init__.py", line 73, in <module>
    from scapy.arch.windows import *  # noqa F403
  File "scapy\arch\windows\__init__.py", line 953, in <module>
    IFACES.load_from_powershell()
  File "scapy\arch\windows\__init__.py", line 843, in load_from_powershell
    interface.ip = ifaces_ips.get(interface.name, "")[0]
IndexError: string index out of range
```

#### Environment

Windows 7
See: https://github.com/secdev/scapy/issues/1718

#### Detail

I think that line 843 should have a different default, since it's looking for an interface name that's not in ifaces_ips and I think shouldn't be:
```
    interface.ip = ifaces_ips.get(interface.name, [""])[0]
```

**With this change, the import works and show_interfaces() returns what appears to be correct.**

Relevant values at this point in the code: 

ifaces_ips: {'Realtek PCIe GBE Family Controller': ['10.0.0.2'], 'VMware Virtual Ethe
rnet Adapter for VMnet8': ['192.168.171.1'], 'TAP-Windows Adapter V9': ['172.21.
30.100'], 'VMware Virtual Ethernet Adapter for VMnet1': ['192.168.234.1'], 'Micr
osoft Loopback Adapter': ['127.0.0.1'], 'Intel(R) PRO/1000 GT Desktop Adapter':
['192.168.0.240']}

interface: {'name': 'Bluetooth Device (Personal Area Network)', 'netid': 'Bluetooth Network
 Connection', 'mac': '5C:F3:70:7E:01:85', 'win_index': '24', 'guid': '{F9E79680-
C325-4D94-B8EC-1425C940D457}', 'description': ''}

**Comment by gpotter2** [comment]
Correct, I missed that

**Comment by jimmbelll** [comment]
Verified that https://github.com/secdev/scapy/pull/1729 works as expected, making the import succeed and show_interfaces() to display correctly in my environment, that produced this issue.
