### ISSUE TITLE
Segmentation fault when closing socket using Scapy+Pypcap

### ISSUE THREAD

**Issue by grace-grimwood** [secdev/scapy#1731]
#### Brief description

Using Pypcap and with conf.use_pcap set to True, if Scapy attempts to close a sniff socket on Ubuntu, a segmentation fault occurs. The same happens under both when using the Scapy CLI, and when running it in a python file.

#### Environment

-   Scapy version: Development build (commit 80ab97ce32105da4b8fc15496712b8643f248860)
-   Python version: 2.7.15rc1
-   Operating System: Ubuntu 18.04 (Kernel 4.15.0-42-generic)

Pypcap version 1.2.2, does not happen on Pypcap 1.1.5, haven't tested it on any other versions.

#### How to reproduce

1. Install the latest release of Scapy via PIP
2. Install the latest version of Pypcap via PIP
3. Open the Scapy CLI as sudo and run the following code:
```
conf.use_pcap = True
import scapy.arch.pcapdnet
sniff(timeout=<insert arbitrary amount here>)
```

A segmentation fault will occur when the socket is being closed.

The same will happen if the following is run (as sudo) as a standalone python script:
```
from scapy.all import *
conf.use_pcap = True
import scapy.arch.pcapdnet
sniff(timeout=<insert arbitrary amount here>)
```
**NB:** Scapy has to be run as sudo on Ubuntu when using Pypcap, or an OSError is raised.

#### Actual result

When running in Python or the Scapy CLI, all I get is this:

`Segmentation fault`

#### Expected result

Literally anything other than a segfault.

#### Related resources

I attempted to debug with gdb, but as I am very much not confident with Cython, much less C, I was having trouble making heads or tails of it. Here's a screencap of the gdb output.

![full gdb segfault](https://user-images.githubusercontent.com/15976368/49488031-e6ca9e00-f8a9-11e8-88e3-45e0edc19b5c.png)

**Comment by grace-grimwood** [comment]
Correction: I seem to be running the development version of Scapy. I will try this again with the 2.4.0 release.

**Comment by grace-grimwood** [comment]
So the issue is fixed by rolling back to v2.4.0. It seems that the latest build has a problem with Pypcap, and it seems to me at least that the issue may be related to the passing of an integer to the "immediate" arg for pcap.pcap in pcapdnet.py on lines [302](https://github.com/secdev/scapy/blob/80ab97ce32105da4b8fc15496712b8643f248860/scapy/arch/pcapdnet.py#L302), [307](https://github.com/secdev/scapy/blob/80ab97ce32105da4b8fc15496712b8643f248860/scapy/arch/pcapdnet.py#L307), and [310](https://github.com/secdev/scapy/blob/80ab97ce32105da4b8fc15496712b8643f248860/scapy/arch/pcapdnet.py#L310), as the \_\_init\_\_ function for [the pcap class in Pypcap](https://github.com/pynetwork/pypcap/blob/v1.2.2/pcap.pyx) specifies immediate as a boolean, and then passes that value unmodified through to the C wrapper, which I imagine then passes the same unmodified value to the libpcap library itself.

If I get the time I'll take a look at it at home and see if I can fix it, but I'm reporting this because I stumbled across the issue while using Scapy for a project at work, and my employer isn't too keen on me spending working hours fixing something that isn't company IP.

**Comment by grace-grimwood** [comment]
Whoops misclicked. Sorry.

**Comment by guyharris** [comment]
And in the pypcap master branch, it's using `pcap_create()`, `pcap_set_immediate_mode()`, and `pcap_activate()`, and *then* it's using `pcap_ex_immediate()`.  That should work on Linux - and everything else; if it can use `pcap_set_immediate_mode()`, it doesn't *need* to use `pcap_ex_immediate()`.

**Comment by grace-grimwood** [comment]
Hey @p-l- I ran git bisect, and it produced this:
```
a0b9d02dbb07d6bc09a722525d4ce71c63af700c is the first bad commit
commit a0b9d02dbb07d6bc09a722525d4ce71c63af700c
Author: gpotter2 <gabriel@potter.fr>
Date:   Wed Apr 18 18:08:44 2018 +0200

    Update pypcap & libpcap API calls

:040000 040000 3767c1a746e2e7b44a2d52e5ef55e798acf451be aa17ce9b4aa4483fd7ce8863b88108edf8ee062a M      scapy
```

It's worth noting that prior to this commit there is a different bug that appears on closing the socket, but nothing nearly as serious as a segfault. It just prints out `WARNING: __del__: don't know how to close the file descriptor. Bugs ahead ! Please report this bug.` before the overall capture summary. I would imagine that the commit that git bisect reports as the first bad commit (secdev/scapy@aa17ce9) was an attempt to remedy this earlier bug.

**Comment by grace-grimwood** [comment]
Also @guyharris sorry, I figured I was probably wrong about the cause of the segfault, it was more a suggestion than anything else. I'm a UI Dev by trade, so Linux libs are not really my forte - but I'm learning! 😄

**Comment by p-l-** [comment]
Thanks a lot for this bisect @grace-grimwood! @gpotter2, could you have a look?

**Comment by gpotter2** [comment]
I was able to replicate. The segmentation fault happens while closing the pcap handler (in `__del__`)
