### ISSUE TITLE
a packet with big playload cannot use sendp success

### ISSUE THREAD

**Issue by hnlisf** [secdev/scapy#1737]
>>> d = str([1,]*500)
>>> len(d)
1500
>>> s=srp(Ether()/IP(dst="192.168.0.1")/TCP(sport=9999)/d,iface="Intel(R) Centrino(R) Wireless-N 2200")
Begin emission:
Finished sending 1 packets.
...............................
Received 31 packets, got 0 answers, remaining 1 packets

**When the length of  packet load is 1410, it can be sent successfully by sendp method. like this:**
>>> d = str([1,]*470)
>>> len(d)
1410
>>> s=srp(Ether()/IP(dst="192.168.0.1")/TCP(sport=9999)/d,iface="Intel(R) Centrino(R) Wireless-N 2200")
Begin emission:
Finished sending 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets

**But I need to send the packet load length is more than 1500, how to solve this problem?**

**Comment by gpotter2** [comment]
That is most likely not a scaly issue.

You need to change the MTU (Maxmium Transmission Unit) size of your OS. On Linux it’s pretty easy, but rather hard and restricted on Windows.

Have a look at https://www.cyberciti.biz/faq/centos-rhel-redhat-fedora-debian-linux-mtu-size/amp/ for linix
