### ISSUE TITLE
[Win] The powershell process can not be killed via close method

### ISSUE THREAD

**Issue by SeaHOH** [secdev/scapy#1744]
#### Brief description

The powershell process which start up with instance POWERSHELL_PROCESS can not be killed via itself close method.

#### Environment

-   Scapy version: 2.4.0
-   Python version: `3.x`
-   Operating System: `Windows`

#### How to reproduce

```py
import time
from scapy.arch import POWERSHELL_PROCESS
time.sleep(10)
POWERSHELL_PROCESS.close()
```

#### Actual result

Then throw an exception, and the powershell process were not be killed.
>a bytes-like object is required, not 'str'

#### Expected result

The powershell process could be killed via close method.

#### Related resources

It could be killed in dev version, but I think the code`"exit\n"`should be`b"exit\n"`.
https://github.com/secdev/scapy/blob/06fad2ed1249dd9a04965c9115d995c5d601198e/scapy/arch/windows/__init__.py#L218

**Comment by gpotter2** [comment]
Thanks a lot for reporting this bug !

Should now be fix against master
