### ISSUE TITLE
Version comparison not tolerant for development package version.

### ISSUE THREAD

**Issue by mmajche** [secdev/scapy#1746]
https://github.com/secdev/scapy/blob/0cd9b58d04b9c2ec7b65c9e8f73a89d095c39913/scapy/config.py#L368
It results in following error: ` ValueError: invalid literal for int() with base 10: ''` when used for package with not standardized version, such as `2.4.dev0` because splitting by "." returns last element as an empty string: `''`. One way of fixing that is by adding `version_tags = filter(None, version_tags)` before mentioned line, but I am not sure if it's right thing to do as I am not fluent in regular expressions, maybe it could be altered instead.

**Comment by gpotter2** [comment]
Hi, sorry for the delay. This is indeed a bug, thanks for reporting
