### ISSUE TITLE
ASN1_BIT_STRING : return value of __bytes__() is incorrect

### ISSUE THREAD

**Issue by ziffusion** [secdev/scapy#1761]
#### Brief description

ASN1_BIT_STRING.\_\_bytes__() and ASN1_BIT_STRING.\_\_str__() should return BER encoded TLV, but returns self.val_readable instead.

Compare with behavior of ASN1_BOOLEAN.\_\_bytes__() and ASN1_BOOLEAN.\_\_str__().

#### Environment

-   Scapy version: `Version 2.4.0.dev650 03f4176ab711fbf5e49e905cd285f7df7913f105`
-   Python version: `2.7.15rc1`
-   Operating System: `Linux 4.15.0-43-generic`

#### How to reproduce
\>>> a = ASN1_BIT_STRING("10101", "value")
\>>> raw(a)
\>>> str(a)
\>>> a = ASN1_BOOLEAN(1)
\>>> raw(a)
\>>> str(a)

#### Actual result
'10101'
'10101'
'\x01\x01\x00'  
'\x01\x01\x00'                             ..

#### Expected result
'\x03\x06\x0010101'
'\x03\x06\x0010101'
'\x01\x01\x00'
'\x01\x01\x00'    

#### Suggestion
Remove \_\_bytes__() and \_\_str__() from ASN1_BIT_STRING. Use inherited one from the base ASN1_Object.
Or I can send a pull request.

**Comment by gpotter2** [comment]
Hi ! Thanks for reporting & sorry for the delay

If you have time, feel free to send a pull request.
If you could add some unit tests (have a look at the .uts files in `test/`)
