### ISSUE TITLE
TypeError: 'OSError' object is not subscriptable after updating to Linux kernel 4.20.0

### ISSUE THREAD

**Issue by kreddkrikk** [secdev/scapy#1766]
I'm seeing the following error when I try to send a packet with scapy, after upgrading to Linux kernel 4.20.0 from 4.19.12:

```
TypeError: 'OSError' object is not subscriptable
```

Kernel version: 4.20.0-arch1-1-ARCH
Python version: 3.7.1-1

After upgrading to the latest Arch Linux kernel (4.20.0) I can no longer send packets with scapy (version 2.4.0-2) in Python 3. I make the assumption the kernel upgrade is the reason this issue occurred because I successfully sent a packet with scapy in 4.19.12, upgraded to 4.20.0, rebooted, and could no longer send packets in scapy. I used the following code to send a packet:

``` python
from scapy.all import *
client="192.168.0.100"
server="192.168.0.101"
ip = IP(src=client, dst=server)
tcp = TCP(sport=12345, dport=80, flags="S")
res=send(ip/tcp)
```

The error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/scapy/sendrecv.py", line 302, in send
    realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python3.7/site-packages/scapy/sendrecv.py", line 276, in __gen_send
    s.send(p)
  File "/usr/lib/python3.7/site-packages/scapy/arch/linux.py", line 488, in send
    if msg[0] == 22 and len(sx) < conf.min_pkt_size:
TypeError: 'OSError' object is not subscriptable
```

When checking tcpdump/wireshark, I notice the SYN packet never gets sent. This code worked fine before the kernel update. Also, using sr1 instead of send doesn't print any errors or call stacks, but still never sends the packet:

``` python
sr1(ip/tcp)
```
```
Begin emission:
...................................... (and so on)
```

I can, however, successfully initiate a 3-way handshake with Python 2.7.15-2, but a subsequent HTTP GET request packet never gets sent:

```python
from scapy.all import *
client='192.168.0.100'
server='192.168.0.101'
ip = IP(src=client, dst=server)
tcp = TCP(sport=12345, dport=80, flags="S")
res = sr1(ip/tcp)
tcp = TCP(sport=12345, dport=80, flags="A", seq=res[TCP].ack, ack=res[TCP].seq+1)
send(ip/tcp)
tcp = TCP(sport=12345, dport=80, flags="A", seq=res[TCP].ack, ack=res[TCP].seq+1)
payload = "GET / HTTP/1.1\r\nHost: " + server + "\r\n\r\n"
res = sr1(ip/tcp/payload)
```

Which prints a "Begin emission: ................." after the HTTP GET request and never sends the packet.

**Comment by gpotter2** [comment]
Hello, could you retry using the development version of scapy ?

- uninstall scapy
- `wget https://github.com/secdev/scapy/archive/master.zip && unzip master.zip && cd scapy-master && sudo python setup.py install`

In most recent versions, the line that the bug is pointing at has been updated to:
`if msg.errno == 22 and len(x) < conf.min_pkt_size:`

**Comment by felix-walter** [comment]
I'm observing the same issue with Arch Linux 64bit, kernel 4.20.0-arch1. Installing the current master using `python setup.py install` inside a venv fixes it for me.

**Comment by gpotter2** [comment]
Thanks for the report
