### ISSUE TITLE
Unable to send Data packet with 802.11

### ISSUE THREAD

**Issue by rabubake** [secdev/scapy#1767]
I'm trying to transmit a data frame (using scapy in ubuntu 18.04) between my desktop and laptop. I would like the MSDU to just be some raw data and not an upper layer frame. For whatever reason I am unable to detect transmitted packets between the devices.

Both devices are set in monitor mode and are connected to the same frequency/channel. For example, my desktop has wireless interface _wlp4s0_ which I set up as follows:

`sudo ifconfig wlp4s0 down`
`sudo iwconfig wlp4s0 mode monitor`
`sudo ifconfig wlp4s0 up`
`sudo iwconfig wlp4s0 channel n`

When I check `iw dev` or `iwconfig` I can see that both wireless interfaces are in monitor mode and at the same frequency with a non-zero tx-power.

I have no problems sniffing the channel using scapy with the following code:

`sniff(iface = "wlp4s0", prn = output)`

Where prn just prints out the summary of any packet.

When I try to transmit I use the following code on one device:
```

    header = Dot11(
       addr1 = "00:16:ea:12:34:56",
       addr2 = "00:16:ea:12:34:56",
       addr3 = "ff:ff:ff:ff:ff:ff",
       type = 2,`
       subtype = 0,
       FCfield = 0)

    data = "testtesttesttest"
    packet = header / data
    sendp(packet , iface= "wlp4s0", loop = 1, inter = 0.100)

```
Despite the transmitting device stating the packet has been transmitted, the other devices cannot see any of the packets while sniffing the channel. Similarly, while using `ifconfig` the tx_count for the interface is not increasing.

I've tried switching roles on both devices, but have also had no luck.

Any help would be greatly appreciated, thanks!

**Comment by gpotter2** [comment]
You might want to retry using a libpcap provider: they usually handle sending WiFi stuff better than raw python sockets (the default on Linux)

- install the latest scapy version from github
- install libpcap (it usually comes with Wireshark), and `pcapy` or `pypcap` from pip
- use `conf.use_pcap = True` before performing any networking operations in your code/scapy.

**Comment by rabubake** [comment]
Thanks for the response.

I installed libpcap with pip and added the lines `conf.use_pcap = True` and `import pcap` to the start of my code, but nothing has changed

**Comment by gpotter2** [comment]
If you wanna add a crc, you can use `Dot11FCS` instead of `Dot11` :/ That adds the CRC automatically

**Comment by rabubake** [comment]
I'm currently using the intel 7260 and intel 5300 wireless cards. I did some digging and it seems that they don't support packet injections. I tried using the airmon-ng injection test (aireplay -9) and the packet injections don't seem to work. I'm assuming if that isn't working then scapy probably won't work either.

**Comment by gpotter2** [comment]
That's probably it :/ Most adapters can sniff but not inject raw 802.11

**Comment by rabubake** [comment]
Thanks for the help. Looks like I have to buy a usb adapter!
