### ISSUE TITLE
Missing raw payload data in packet

### ISSUE THREAD

**Issue by evandrix** [secdev/scapy#1775]
#### Brief description

Packet #287 in .pcap is missing the trailing `WFAER5D+dG2YH2` data.

#### Environment

-   Scapy version: scapy-2.4.0.dev661
-   Python version: 2.7
-   Operating System: OSX 10.12.6 / Ubuntu 16.04.5

#### How to reproduce

```
#!/usr/bin/env python
#-*- coding: utf-8 -*-

import sys
from scapy.all import *

if __name__ == "__main__":
	pcap_file = sys.argv[1]
	for i,pkt in enumerate(PcapReader(pcap_file)):
		if i+1 == 287: print pkt[Raw].load
```

#### Actual result - via Python script above^^

```
aPPS1lQmTMnHmXq9yPVHu0Ucv+FYbV3/AO/5D4VH3uU7Zl1tmUXUFNxbXkmx4rp1HORqKxznOa6E
...
Cm2VglEBfeiH0FMXJaa
```

#### Expected result - obtained using Wireshark 2.6.3 (v2.6.3-0-ga62e6c27)

```
aPPS1lQmTMnHmXq9yPVHu0Ucv+FYbV3/AO/5D4VH3uU7Zl1tmUXUFNxbXkmx4rp1HORqKxznOa6E
...
Cm2VglEBfeiH0FMXJaaWFAER5D+dG2YH2
```

note the extra `WFAER5D+dG2YH2` in the "Expected result", that is missing from the "Actual result"

#### Related resources

[super_secret_packet_capture.pcap.zip](https://github.com/secdev/scapy/files/2741956/super_secret_packet_capture.pcap.zip)

**Comment by evandrix** [comment]
as a reference,

```
import dpkt
with open(pcap_file,"rb") as f:
  pcap = dpkt.pcap.Reader(f)
  for i,(ts,buf) in enumerate(pcap):
    eth = dpkt.ethernet.Ethernet(buf)
    ip = eth.data
    tcp = ip.data
    if tcp.dport==25 and tcp.data and (i+1)==287:
      print tcp.data
```

... produces the "Expected result"

```
$ python -c "import dpkt; print dpkt.__version__"
1.9.1
```

**Comment by gpotter2** [comment]
Scapy doesn’t read packets bigger than the MTU by default, as the pcap implementation mimic a real socket, which is limited (if your adapter and OS supports it, highly unlikely) to 65535 (th MTU).

To receive bigger packets, you must specify the MTU manually:
![0e0418d1-28ed-40ae-83de-b05041082f95](https://user-images.githubusercontent.com/10530980/50936398-d9d43800-146f-11e9-864a-91e2b774d26e.jpeg)

(Here I set twice the MTU for instance)

**Comment by evandrix** [comment]
@gpotter2 : :+1:  yep, can confirm that that is the issue - increasing the MTU makes it work properly now, thanks

reference [here](https://bitbucket.org/secdev/scapy/issues/5148/datamtu-is-too-small) about setting `MTU`

**Comment by ArthurMLago** [comment]
Hi, I just stumbled on this same problem when using rdpcap, with a capture obtained through lo interface.
The mtu configure on the interface was 65536, checking on wireshark, tcp segments had length 65483, but scapy only captured up until 65469. Capturing packets with a lower interface MTU, or setting the MTU as described in the link above worked.(thanks for the info).

However, to avoid further confusion, shouldn't the default value be higher? I had never changed the MTU size on my system, so I suppose more people may have this issue in the future.
I'm running linux(uname -r: 5.6.15-arch1-1), so nothing extraordinary here.
