### ISSUE TITLE
pypi does not display HTML or mardown

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#1778]
pypi does not seem to display our README correctly: https://pypi.org/project/scapy/

**Comment by gpotter2** [comment]
It seems from 
https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi that
![3511b1e8-21ce-49f0-984f-e66c964dd284](https://user-images.githubusercontent.com/10530980/50961302-a02f1b80-14c7-11e9-9e1a-513dee1ef64d.jpeg)
/

**Comment by guedou** [comment]
Thanks. I will install everything using a new virtualenv.
