### ISSUE TITLE
Make MDNS queries with Scapy

### ISSUE THREAD

**Issue by Lodags** [secdev/scapy#179]
Thank you Guedou for you help !

The issue is that I try to forge mDNS queries, but they aren't successful as they don't return any answers. They are successfully sent though.

(The dig command : dig -x 192.168.50.29 @224.0.0.251 -p 5353 +short )

Here is what I tried : 
sr1 or wireshark(IP(dst="224.0.0.251")/\
                UDP(dport=5353)/\
                DNS(rd=1,qd=DNSQR(qname="192.168.50.29",qtype='PTR')))

Wireshark:
   ->The dig frame is a good MDNS frame
   -> The Scapy is a DNS frame (... I don't know why I expected a mDNS here)

When I try to replay the dig request, it doesn't work. It looks like this : 
d=sr1(IP(dst="224.0.0.251")/\
        UDP(dport=5353)/\
        Raw(load=   '\x03\x83'
                    #Transaction ID
                    '\x01\x00'
                    #Flags
                    '\x00\x01'
                    #Questions
                    '\x00\x00'
                    #Answers RR
                    '\x00\x00'
                    #Authority RR
                    '\x00\x00'
                    #Additionnal RRs
                    '\x02\x32\x39\x02\x00\x10\x35\x30\x03\x31\x36\x38\x03\x31\x39\x32\x07\x69\x6e\x2d\x61\x64\x00\x20\x64\x72\x04\x61\x72\x70\x61\x00'
                    #Name
                    '\x00\x0c'
                    #PT
                    '\x00\x01'))
                    #IN

However, when I try to send this kind of packet, forged by myself, it's detected as malformed by wireshark.
Do you have a better way to do this ?
If no, does a mDNS layer is required ? I'd love to contribute to Scapy and make one if it's needed. But as I am just an amateur in networks, is it relevant to create a new layer ?

Thank you !

Lodags -- I hope I'm understandable, I'm French. (And sometimes even Frenchs don't understand me)

**Comment by guedou** [comment]
First thing first,  you need to use the latest Scapy fron github, see below.

Old Scapy:
````
>>> Ether('33\x00\x00\x00\xfb\xb8\xe8VE\x8c\xe6\x86\xdd`\x0c\xc1&\x00)\x11\xff\xfe\x80\x00\x00\x00\x00\x00\x00\xba\xe8V\xff\xfeE\x8c\xe6\xff\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfb\x14\xe9\x14\xe9\x00)\xb4>\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x04_ssh\x04_tcp\x05local\x00\x00\x0c\x00\x01')
<Ether  dst=33:33:00:00:00:fb src=b8:e8:56:45:8c:e6 type=0x86dd |<IPv6  version=6L tc=0L fl=835878L plen=41 nh=UDP hlim=255 src=fe80::bae8:56ff:fe45:8ce6 dst=ff02::fb |<UDP  sport=mdns dport=mdns len=41 chksum=0xb43e |<Raw  load='\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x04_ssh\x04_tcp\x05local\x00\x00\x0c\x00\x01' |>>>>
````
Note that you can force the decoding using `pkt[UDP].decode_payload_as(DNS)`.

Current Scapy:
````
>>> Ether('33\x00\x00\x00\xfb\xb8\xe8VE\x8c\xe6\x86\xdd`\x0c\xc1&\x00)\x11\xff\xfe\x80\x00\x00\x00\x00\x00\x00\xba\xe8V\xff\xfeE\x8c\xe6\xff\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfb\x14\xe9\x14\xe9\x00)\xb4>\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x04_ssh\x04_tcp\x05local\x00\x00\x0c\x00\x01')
<Ether  dst=33:33:00:00:00:fb src=b8:e8:56:45:8c:e6 type=0x86dd |<IPv6  version=6L tc=0L fl=835878L plen=41 nh=UDP hlim=255 src=fe80::bae8:56ff:fe45:8ce6 dst=ff02::fb |<UDP  sport=mdns dport=mdns len=41 chksum=0xb43e 
```

Then, I think that  Scapy does not match replies with queries. The following should work and it does not:
`>>> sr1(IP()/UDP(dport=5353)/DNS(qd=DNSQR(qtype="PTR", qname="_googlecast._tcp.local.")))`

This will requires fixes in different locations. I don't have time to investigate more tonight.

**Comment by Lodags** [comment]
Okay, I upgraded to the latest Scapy from GitHub (sorry for not using it since the beginning). Thank you for the tips though. Would you like some help to implement that if you don't have the time ? I'd love to give a contribution to Scapy, as little as it would be. I'm a student and eager to learn !

**Comment by guedou** [comment]
While thinking about possible fixes, I realised that mDNS should work with IPv6. Indeed, the following works perfectly on my home network:

```python
>>> sr1(IPv6()/UDP(dport=5353)/DNS(qd=DNSQR(qtype="PTR", qname="_http._tcp.local.")))
```

**Comment by guedou** [comment]
@Lodags does the PR #203 works for you usage ?

**Comment by Lodags** [comment]
Yes ! It works ! Thank you very much ! Wireshark doesn't recognize it as mdns but it doesn't matter.

**Comment by AntonioLeonUPV** [comment]
hi, how can I add the QU flag = true in a query?
I'd want the qclass= 0x8001 

 I try with this, but does not work. 
sr1(IP(dst="224.0.0.251")/UDP(dport=5353, sport=5353)/DNS(qd=DNSQR(qtype="PTR", qname="_ipp._tcp.local.", qclass='\x08\x01'))) 

many thanks
