### ISSUE TITLE
sendpfast() not working with Python 2.7

### ISSUE THREAD

**Issue by jrickman** [secdev/scapy#1798]
#### Brief description

Part of the changes from 2.3 to 2.4 included `sendpfast()` changing from using `subprocess.check_call()` to `subprocess.Popen()`.

The `subprocess.Popen()` call is using a context object form for automatic closing of the handle:

```python
        with subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as cmd:  # noqa: E501
            stdout, stderr = cmd.communicate()
```

I believe this context object form wasn't introduced to Popen until Python 3.

In Python 2.7, this raises `AttributeError: __exit__`, which causes an error message in interactive mode and the packet is not sent.

#### Environment

-   Scapy version: confirmed with both 2.4.2 release as well as latest master `e5a9b82f`
-   Python version: `Python 2.7.14`
-   Operating System: Docker image based on `Debian GNU/Linux 8 (jessie)`

#### How to reproduce

```bash
docker run --rm -it python:2 bash
apt-get update && apt-get install -y tcpreplay
pip install scapy==2.4.2
scapy
sendpfast(Ether() / IP(proto='udp', dst='233.43.202.24') / UDP(dport=11124) / 'TEST', iface='eth0')
```

#### Actual result

```
INFO: ['tcpreplay', '--intf1=eth0', '--topspeed', '/tmp/scapyoGcRCI']
ERROR: Cannot execute [tcpreplay]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 371, in sendpfast
    with subprocess.Popen(argv, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as cmd:  # noqa: E501
AttributeError: __exit__
```

#### Expected result

```
WARNING: Mac address to reach destination not found. Using broadcast.
.
Sent 1 packets.
```

**Comment by p-l-** [comment]
Thanks for your report. This should be fixed (as soon as #1805 is merged).
