### ISSUE TITLE
Scapy.sniff() on Windows missing stop_filter and opened_socket arguments

### ISSUE THREAD

**Issue by jackpreston** [secdev/scapy#181]
Why does `sniff()` in the Windows version of scapy `arch/windows/__init__.py` not include the `stop_filter` argument? It is also missing the `opened_socket` argument.

**Comment by guedou** [comment]
I have not good explanation to provide, except that the Windows code somehow evolved on its own.

**Comment by gpotter2** [comment]
This is so old... Fixed in https://github.com/secdev/scapy/pull/455
