### ISSUE TITLE
802.11-FCS: addr3, SC, fcs seem to be messed up in data frames (type=2)

### ISSUE THREAD

**Issue by m6c7l** [secdev/scapy#1811]
During sniffing I noticed sn's and fn's not changing over time which are supposed to change. This happens as far as I can tell to data packets (type=2) only, regardless of their subtype. It seems that 4 bytes of addr3 (source address) are replaced with the frame check sequence (fcs) and vice versa. A simple show() of the 802.11-FCS layer shows the issue due to wrong decoding as well.

To be more explicit and in order to describe the issue more precise, here an example to correct raw bytes of a ScaPy-sniffed packet (actual state) to a packet assumed to be correct (desired state):

```python
# 802.11-FCS raw bytes (textual representation)
#    fcf  d    addr1        addr2        addr3?        sc?   qc   payload        fcs?
s = "8826|d000|969609eb76aa|96961fc38c50|9696*c1574fc3|1fc3*|0000|aaaa03..68b261|*8c50b000*"
s = re.sub('[|\*]', '', s)
s = re.findall('..', s)
l = ['|'] 
s = ''.join(s[:2] + l + s[2:4] + l + s[4:10] + l + s[10:16] + l +
            s[16:18] + s[22:24] + s[-4:-2] + l + s[-2:] + l + s[24:26] + l +
            s[26:-4] + l + s[18:22])
print(s)
# 8826|d000|969609eb76aa|96961fc38c50|96961fc38c50|b000|0000|aaaa03..68b261|c1574fc3
```

In the example above sn becomes 11, fn becomes 0 and addr2 becomes equal to addr3, which would be correct.

I am using Scapy 2.4.2 and Python 3.6.8 on GNU/Linux 4.20 to sniff kind of regular traffic on 802.11bgn physical layers, whereby I need to get  the (correct) sequence (sn) and fragment numbers (fn).

**Comment by gpotter2** [comment]
Confirmed, 
https://github.com/secdev/scapy/blob/2a27dac6e9753d34a43d33d5d4f9d9614f51d00c/scapy/layers/dot11.py#L370 is the root of the issue (wrongly built in some cases)

**Comment by m6c7l** [comment]
I guess I can help to solve the issue.

**Comment by gpotter2** [comment]
Could you share a pcap with a a packet containing the issue ? That would be easier to reproduce. Thanks !

**Comment by m6c7l** [comment]
I attached a [pcap file](https://github.com/secdev/scapy/files/2809685/scapy_issue_1811.zip) that shows the issue for frames of type 2 subtype 4. Those packets got sn's from 3537 to 3636, but Scapy is decoding each to 3121 and fn 15 in SC.

Nevertheless, I do not think this is the root of the issue with regard to data frames (i.e. type 2):

> https://github.com/secdev/scapy/blob/2a27dac6e9753d34a43d33d5d4f9d9614f51d00c/scapy/layers/dot11.py#L370

But I think it is indeed not doing a good job for control frames (type 1), at least for subtypes 9, 11, 12 and 13. I came up with this function that creates expected results:

```python
def pre_dissect_new(s):
    ty = (s[0] & 0b00001100) >> 2
    sty = (s[0] & 0b11110000) >> 4    
#    ds = (s[1] & 0b00000011) >> 0
    sc_present = not (ty in (1,) and sty in (10,11,12))
    length =  4
    length += 6                                                  # addr1
    length += (ty in (0,2)) * (2 * 6 + 2)                        # addr2, addr3, sc
#    length += 1 * (ds // 3) * 6                                 # addr4
    length += 1 * (ty in (1,) and sty in (8,9,10,11,14,15)) * 6  # addr2
    length += 1 * (ty in (1,) and sty in (8,9)) * 4              # extra
#    length += 4                                                 # fcs
    return s[:length], s[-4:], s[length:-4]                      # dot11, fcs, rest
```

**Comment by gpotter2** [comment]
Thanks again for your report. It should be fixed in  https://github.com/secdev/scapy/issues/1811

Could you please have a look ? Thanks !

PS: i removed the length guess, so that we support all possible cases :-)

**Comment by m6c7l** [comment]
Confirmed. Issue seems to be resolved by https://github.com/gpotter2/scapy/tree/fixkrack for my use case. Thank you!
