### ISSUE TITLE
Does scapy support parse ipfix/sflow packet?

### ISSUE THREAD

**Issue by JackSunshine** [secdev/scapy#1813]
Hi,
scapy is a great project, thanks to the authors, I'd like to know does scapy support ipfix/sflow? can i use scapy decode an ipfix/sflow packet? or Is any way I can implement my own class by inhering scapy class

Thanks

**Comment by gpotter2** [comment]
No it’s not implemented. Feel free to add a PR :)

Yes you can implement it, have a look at our doc:
https://scapy.readthedocs.io/en/latest/

**Comment by gpotter2** [comment]
Hi @JackSunshine 
https://github.com/secdev/scapy/pull/1965 is still in a beta phase, but should now be able to dissect IPFix. It would be great if could check it out and test it (it's not merged into master yet)

Thanks !
