### ISSUE TITLE
ZCLReadAttributeStatusRecord incorrect parsing

### ISSUE THREAD

**Issue by hgbstu** [secdev/scapy#1815]
#### Brief description

If there are multiple entries of ZCLReadAttributeStatusRecord in a packet scapy returns only the first one, the rest is interpreted as RAW.

#### Environment

-   Scapy version: 2.4.0.dev653
-   Python version: Python 2.7.13 
-   Operating System: Debian 9.5

#### How to reproduce

```
class ZCLGeneralReadAttributesResponse(Packet):
    name = "General Domain: Command Frame Payload: read_attributes_response"
    fields_desc = [
        PacketListField("read_attribute_status_record", [], ZCLReadAttributeStatusRecord),  # noqa: E501
    ]
```
 I added the `extract_padding(...)` line to `ZCLReadAttributeStatusRecord(Packet)` (this is needed as far as I understand correctly for `PacketListField` to work)

```
class ZCLReadAttributeStatusRecord(Packet):
    name = "ZCL Read Attribute Status Record"
    fields_desc = [
        # Attribute Identifier
        XLEShortField("attribute_identifier", 0),
        # Status
        ByteEnumField("status", 0, _zcl_enumerated_status_values),
        # Attribute data type (0/1 octet), only included if status == 0x00 (SUCCESS)  # noqa: E501
        ConditionalField(
            ByteEnumField("attribute_data_type", 0, _zcl_attribute_data_types),
            lambda pkt:pkt.status == 0x00
        ),
        # Attribute data (0/variable in size), only included if status == 0x00 (SUCCESS)  # noqa: E501
        ConditionalField(
            StrLenField("attribute_value", "", length_from=lambda pkt:util_zcl_attribute_value_len(pkt)),  # noqa: E501
            lambda pkt:pkt.status == 0x00
        ),
    ]
    
    def extract_padding(self, p):
        return "", p
```
The function `util_zcl_attribute_value_len()` returns the length for `attribute_value`. However if `pkt.attribute_data_type == 0x42` (I assume it's the same also for 0x43, 0x44) accessing `pkt.attribute_value[0]` results in the following error message. 

>   File "/usr/local/lib/python2.7/dist-packages/scapy/layers/zigbee.py", line 1503, in util_zcl_attribute_value_len
>     return int(pkt.attribute_value[0])  # defined in first octet
> IndexError: string index out of range

```
def util_zcl_attribute_value_len(pkt):
    # Calculate the length of the attribute value field
    if (pkt.attribute_data_type == 0x00):  # no data
        return 0
...
    elif (pkt.attribute_data_type == 0x42):  # Character string
        return int(pkt.attribute_value[0])  # defined in first octet
    elif (pkt.attribute_data_type == 0x43):  # Long octet string
        return int(pkt.attribute_value[0:2])  # defined in first two octets
    elif (pkt.attribute_data_type == 0x44):  # Long character string
        return int(pkt.attribute_value[0:2])  # defined in first two octets
```
I think this is because `pkt.attribute_value` is not initialized yet. How can I access the "next" byte to return the correct length?

#### Incorrect result
![grafik](https://user-images.githubusercontent.com/18686294/51772976-b1923d80-20ed-11e9-9ca7-850ea30e2489.png)

#### Expected result
![grafik](https://user-images.githubusercontent.com/18686294/51772878-7132bf80-20ed-11e9-93b1-24bf5f09d368.png)

**Comment by gpotter2** [comment]
Hi thanks for your report. Could you:
- retry with 2.4.2
- share a packet (as raw bytes, pcap, hex... anything) so that we can replicate ?

Thanks !

**Comment by hgbstu** [comment]
Tested it again with Scapy 2.4.2.dev25, same behaviour.

In order to reproduce this bug you have to fix another parsing bug first (I will open a seperate bug report for this one shortly).

In `class ZigbeeAppDataPayload(Packet):` change the line 
`ConditionalField(ByteField("block_number", 0), lambda pkt: pkt.fragmentation != 0), # noqa: E501`
to 
`        ConditionalField(ByteField("block_number", 0), lambda pkt: (pkt.fragmentation != 0 and pkt.fragmentation is not None)),  # noqa: E501`

**How to reproduce**
```
#!/usr/bin/env python

from scapy.all import *

conf.dot15d4_protocol = "zigbee"

if __name__ == '__main__':
    payload = '@\x01\x00\x00\x04\x01\x01\r\x18 \x01\x00\x00\x00 \x01\x04\x00\x00B\x07sengled'
    obj = ZigbeeAppDataPayload(payload)
    print '  ', repr(obj)
    print(obj.show2())
```

**Comment by gpotter2** [comment]
Hi ! Sorry but the packet you've given doesn't really replicate anything :/ It works fine

**Comment by hgbstu** [comment]
It could be I have not expressed the problem clearly, sorry for that. `ZCLGeneralReadAttributesResponse` is part of the `ZigbeeAppDataPayload` packet. I will try to explain it again :) 

**Preperation** 

- Add `extract_padding(...) `to `ZCLReadAttributeStatusRecord` as mentioned in the initial post. 
- Change the line `ConditionalField(ByteField("block_number", 0), lambda pkt: pkt.fragmentation != 0), # noqa: E501` in `ZigbeeAppDataPayload(Packet)` to  `ConditionalField(ByteField("block_number", 0), lambda pkt: (pkt.fragmentation != 0 and pkt.fragmentation is not None)), # noqa: E501` (Otherwise the parsing is already incorrect in `ZigbeeAppDataPayload` and we do not reach the code that is responsible for the bug we are talking about here.)

Now at least the first `ZCL Read Attribute Status Record` should be parsed correctly, however there are two in the given example.

After editing the scapy source as mentioned above the output of the code in my previous post is the following: 
```
   <ZigbeeAppDataPayload  frame_control=ack_req delivery_mode=unicast aps_frametype=data dst_endpoint=1 cluster=basic profile=HA_Home_Automation src_endpoint=1 counter=13 |<ZigbeeClusterLibrary  reserved=0 disable_default_response=1 direction=1 manufacturer_specific=0 zcl_frametype=profile-wide transaction_sequence=32 command_identifier=read_attributes_response |<ZCLGeneralReadAttributesResponse  read_attribute_status_record=[<ZCLReadAttributeStatusRecord  attribute_identifier=0x0 status=SUCCESS attribute_data_type=Unsigned_8-bit_integer attribute_value='\x01' |<Raw  load='\x04\x00\x00B\x07sengled' |>>] |>>>
###[ Zigbee Application Layer Data Payload (General APS Frame Format) ]### 
  frame_control= ack_req
  delivery_mode= unicast
  aps_frametype= data
  dst_endpoint= 1
  cluster   = basic
  profile   = HA_Home_Automation
  src_endpoint= 1
  counter   = 13
###[ Zigbee Cluster Library (ZCL) Frame ]### 
     reserved  = 0
     disable_default_response= 1
     direction = 1
     manufacturer_specific= 0
     zcl_frametype= profile-wide
     transaction_sequence= 32
     command_identifier= read_attributes_response
###[ General Domain: Command Frame Payload: read_attributes_response ]### 
        \read_attribute_status_record\
         |###[ ZCL Read Attribute Status Record ]### 
         |  attribute_identifier= 0x0
         |  status    = SUCCESS
         |  attribute_data_type= Unsigned_8-bit_integer
         |  attribute_value= '\x01'
         |###[ Raw ]### 
         |     load      = '\x04\x00\x00B\x07sengled'
```

The expected output is the something like this (manually edited)

```
   <ZigbeeAppDataPayload  frame_control=ack_req delivery_mode=unicast aps_frametype=data dst_endpoint=1 cluster=basic profile=HA_Home_Automation src_endpoint=1 counter=13 |<ZigbeeClusterLibrary  reserved=0 disable_default_response=1 direction=1 manufacturer_specific=0 zcl_frametype=profile-wide transaction_sequence=32 command_identifier=read_attributes_response |<ZCLGeneralReadAttributesResponse  read_attribute_status_record=[<ZCLReadAttributeStatusRecord  attribute_identifier=0x0 status=SUCCESS attribute_data_type=Unsigned_8-bit_integer attribute_value='\x01' |>, <ZCLReadAttributeStatusRecord  attribute_identifier=0x4 status=SUCCESS attribute_data_type=character_string attribute_value='\xsengled' |>] |>>>
###[ Zigbee Application Layer Data Payload (General APS Frame Format) ]### 
  frame_control= ack_req
  delivery_mode= unicast
  aps_frametype= data
  dst_endpoint= 1
  cluster   = basic
  profile   = HA_Home_Automation
  src_endpoint= 1
  counter   = 13
###[ Zigbee Cluster Library (ZCL) Frame ]### 
     reserved  = 0
     disable_default_response= 1
     direction = 1
     manufacturer_specific= 0
     zcl_frametype= profile-wide
     transaction_sequence= 32
     command_identifier= read_attributes_response
###[ General Domain: Command Frame Payload: read_attributes_response ]### 
        \read_attribute_status_record\
         |###[ ZCL Read Attribute Status Record ]### 
         |  attribute_identifier= 0x0
         |  status    = SUCCESS
         |  attribute_data_type= Unsigned_8-bit_integer
         |  attribute_value= '\x01'
         |###[ ZCL Read Attribute Status Record ]### 
         |  attribute_identifier= 0x4
         |  status    = SUCCESS
         |  attribute_data_type= character_string
         |  attribute_value= '\xsengled'
```

I hope you can reproduce it now.

**Comment by hgbstu** [comment]
Unfortunately the commit #1816 also produces a wrong output. 

I changed the line `ConditionalField(ByteField("block_number", 0 ...` as mentioned above in order to get the right codepath executed. See #1818

```
   <ZigbeeAppDataPayload  frame_control=ack_req delivery_mode=unicast aps_frametype=data dst_endpoint=1 cluster=basic profile=HA_Home_Automation src_endpoint=1 counter=13 |<ZigbeeClusterLibrary  reserved=0 disable_default_response=1 direction=1 manufacturer_specific=0 zcl_frametype=profile-wide transaction_sequence=32 command_identifier=read_attributes_response |<ZCLGeneralReadAttributesResponse  read_attribute_status_record=[<ZCLReadAttributeStatusRecord  attribute_identifier=0x0 status=SUCCESS attribute_data_type=Unsigned_8-bit_integer attribute_value='\x01' |>, <Raw  load='\x04\x00\x00B\x07sengled' |>] |>>>
###[ Zigbee Application Layer Data Payload (General APS Frame Format) ]### 
  frame_control= ack_req
  delivery_mode= unicast
  aps_frametype= data
  dst_endpoint= 1
  cluster   = basic
  profile   = HA_Home_Automation
  src_endpoint= 1
  counter   = 13
###[ Zigbee Cluster Library (ZCL) Frame ]### 
     reserved  = 0
     disable_default_response= 1
     direction = 1
     manufacturer_specific= 0
     zcl_frametype= profile-wide
     transaction_sequence= 32
     command_identifier= read_attributes_response
###[ General Domain: Command Frame Payload: read_attributes_response ]### 
        \read_attribute_status_record\
         |###[ ZCL Read Attribute Status Record ]### 
         |  attribute_identifier= 0x0
         |  status    = SUCCESS
         |  attribute_data_type= Unsigned_8-bit_integer
         |  attribute_value= '\x01'
         |###[ Raw ]### 
         |  load      = '\x04\x00\x00B\x07sengled'
```

**Comment by gpotter2** [comment]
Thanks, I finally understood the issue. You've added some extra infos all over the place 😄 
Fixed in https://github.com/secdev/scapy/pull/1816 (updated)

**Comment by hgbstu** [comment]
#1818 seems fixed in #1816, thanks!
Regarding the `ZCL Read Attribute Status Records` I see the the same output as in my previous post. Should this also be fixed already?

**Comment by gpotter2** [comment]
Seems to be working on my end :/

![image](https://user-images.githubusercontent.com/10530980/51793304-a3f8b880-21be-11e9-9dbe-a97afc039fbd.png)

I also fixed ZigbeeAppCommandPayload (unrelated, in https://github.com/secdev/scapy/pull/1816). It wasn't following the RFC properly

**Comment by hgbstu** [comment]
Tested it again on a clean install, it works. Thank you!

One more thing: Is there a reason why the length of the string, in the example it's `\x07`, is included in `attribute_value` ?

**Comment by gpotter2** [comment]
It allows to make wrongly built fields, and also spares the implementation of the encoding part (it would be very short. We could add it if you think it’s more useful that way)

Thanks for the report
