### ISSUE TITLE
layers/can/rdcandump extended canId incorrect

### ISSUE THREAD

**Issue by ebroecker** [secdev/scapy#1821]
While looking at:

https://github.com/secdev/scapy/blob/2254f78e34b7b031c0d933d749cdd8b8d670b09f/scapy/layers/can.py#L134-L135

I think I found a bug.
There can be can-ids lower than 0x7ff which are also extended frames.
It's even possible to have same CAN-ID on the bus on time as "standard" and one time as "extended".

In the log file-format can-ids with have 3 digits if standard can, and use 8 digits for extended frames.
```
001#1122334455667788
00000001#1122334455667788
```

can frame header has an extra-bit for "extended": https://en.wikipedia.org/wiki/File:CAN-Bus-frame_in_base_format_without_stuffbits.svg

For comparison the regarding code in python-can:
https://github.com/hardbyte/python-can/blob/89f4c2052d0d0378c171a81317d68b2a80fd00dd/can/io/canutils.py#L60-L64

https://github.com/hardbyte/python-can/blob/89f4c2052d0d0378c171a81317d68b2a80fd00dd/can/io/canutils.py#L133-L136

**Comment by ebroecker** [comment]
yes, maybe something like
```python
if len(idn) > 3:
   pkt.flags = 0b100
```
should fix this issue.

**Comment by polybassa** [comment]
can be closed
