### ISSUE TITLE
VXLAN: different behavior between 2.4.0 and 2.4.2

### ISSUE THREAD

**Issue by mcorbin** [secdev/scapy#1824]
#### Brief description

The VXLAN() constructor doesn't have the same behavior in 2.4.2 than in 2.4.0.

#### Environment

-   Scapy version: master (6865162a1062d91b0189bf962cbc7af76d330d87)
-   Python version: `3.7.2`
-   Operating System: `Debian testing`

#### How to reproduce

Build a VXLAN packet from raw bytes (cf the example).

#### Actual result

Scapy 2.4.2/master:

```python
>>> a = VXLAN(b'\x08\x00\x00\x00\x00"H\x00\xcaF\xae\x10\xed\x0f\x0c\x00\x00\x00\x00\x00\x08\x06\x00\x01\x08\x00\x06\x04\x00\x02\x0c\x00\x00\x00\x00\x00\x7f\xff\xff\xfe\x11"3DUf\x7f\x00\x00\x02')
>>> a
<VXLAN  flags=Instance reserved1=0 vni=0x2248 reserved2=0x0 |<Raw  load='\xcaF\xae\x10\xed\x0f\x0c\x00\x00\x00\x00\x00\x08\x06\x00\x01\x08\x00\x06\x04\x00\x02\x0c\x00\x00\x00\x00\x00\x7f\xff\xff\xfe\x11"3DUf\x7f\x00\x00\x02' |>>
```

#### Expected result

Scapy 2.4.0:

```python
>>> a = VXLAN(b'\x08\x00\x00\x00\x00"H\x00\xcaF\xae\x10\xed\x0f\x0c\x00\x00\x00\x00\x00\x08\x06\x00\x01\x08\x00\x06\x04\x00\x02\x0c\x00\x00\x00\x00\x00\x7f\xff\xff\xfe\x11"3DUf\x7f\x00\x00\x02')
>>> a
<VXLAN  flags=Instance reserved1=0 vni=0x2248 reserved2=0x0 |<Ether  dst=ca:46:ae:10:ed:0f src=0c:00:00:00:00:00 type=ARP |<ARP  hwtype=0x1 ptype=0x800 hwlen=6 plen=4 op=is-at hwsrc=0c:00:00:00:00:00 psrc=127.255.255.254 hwdst=11:22:33:44:55:66 pdst=127.0.0.2 |>>>
```

As you can see, I have a `Ether` field in 2.4.0 but a `Raw` field in 2.4.2.

3dd5817a789f3d4767e64d309b9b8ecb790e8e15 introduced the issue (found using `git bisect`).

**Comment by gpotter2** [comment]
Thanks for reporting, the bindings had actually been modified, and that made a regression.

Will be fixed as soon as https://github.com/secdev/scapy/pull/1825 is merged. You can pull Scapy from the branch until then
