### ISSUE TITLE
Wrong encoding Dot11EltRSN

### ISSUE THREAD

**Issue by ash09** [secdev/scapy#1826]
#### Brief description

MFPR (Management Frame Protection Required) and MFPC (Management Frame Protection Capable) bits are set to 0 in Wireshark whereas they were set to 1 in Dot11EltRSN. 

#### Environment

-   Scapy version: 2.4.2
-   Python version: 3.6.7
-   Operating System: Debian 9

#### How to reproduce

> Dot11EltRSN(mfp_required=1, mfp_capable=1)

> <Dot11EltRSN  group_cipher_suite=<RSNCipherSuite  |> pairwise_cipher_suites=[<RSNCipherSuite  |>] akm_suites=[<AKMSuite  |>] mfp_required=1 mfp_capable=1 |>

#### Actual result

> b'0\x14\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x01\x03\x00'

![bug_scapy](https://user-images.githubusercontent.com/9435297/52129154-1cd09800-2637-11e9-8e90-3751d9897c67.png)

#### Expected result

> b'0\x14\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x01\xc0\x00'

**Comment by gpotter2** [comment]
Hi ! Thanks for the report,

Could you check that https://github.com/secdev/scapy/pull/1829 fixes it for you ? Thanks
