### ISSUE TITLE
Automaton error "filedescriptor out of range in select()"

### ISSUE THREAD

**Issue by cornacchia** [secdev/scapy#1831]
Greetings, I am using an automaton to parse some incoming packets.
I create a new automaton for each packet and then run it, something like this:
```python
class MyAutomaton(Automaton):
  def parse_args(self, pkt, **kargs):
    Automaton.parse_args(self, **kargs)
    self.pkt = pkt
  ##### REST OF  CLASS CODE #####

def PacketHandler(pkts):
  pkt = pkts[0]
  my_automaton = MyAutomaton(pkt)
  my_automaton.run()

sniff(iface="myIface", prn=PacketHandler)
```
Each run terminates in a final state, there are no loose ends.
This works nicely for a while but eventually the script raises this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/scapy/automaton.py", line 771, in _do_control
    self.send_sock = self.send_sock_class(**self.socket_kargs)
  File "/usr/local/lib/python3.4/dist-packages/scapy/arch/linux.py", line 458, in __init__
    _flush_fd(self.ins)
  File "/usr/local/lib/python3.4/dist-packages/scapy/arch/linux.py", line 379, in _flush_fd
    r, w, e = select([fd], [], [], 0)
ValueError: filedescriptor out of range in select()
```
The packets are sent by a script with a frequency of one every 0.1 seconds. The error is raised few seconds after I start the capture. If I try to decrease the frequency it takes longer but eventually the error is always raised.

Is this because I create a new automaton for each packet and these are not destroyed correctly after the run?
Are there better ways to do this?
I saw that another issue (#67) mentioned this same error, but I think in my case it could be related to the way I'm creating the automata.

I considered creating only one automaton and passing the packet as arguments to the `run` method but I wasn't able to do it (the documentation states that by overloading the `parse_args` method I should be able to pass something to the `run` method and I verified that `parse_args` is actually called every time i call `run`. But I wasn't able to pass the packet and couldn't find any examples of arguments passed to the `run` method of an automaton).

This is the system state:
* Scapy 2.4.2
* Python 3.4.3
* Ubuntu 14.04.4 LTS

**Comment by guedou** [comment]
Please try again with Scapy 2.4.0

**Comment by cornacchia** [comment]
I'm sorry, I was checking out the scapy version which is used with python 2.
The script which causes the error uses python 3 and scapy v.2.4.2 (I updated the original question).

**Comment by guedou** [comment]
My guess is that you are hitting the maximum number of opened file descriptors. Can you try increasing this limit and try again?
As your `PacketHandler()` is triggered for all received packets that can happen really fast.

**Comment by gpotter2** [comment]
^ An automaton is a quite heavy object, you would normally use only one automaton to handle everything, not start one on ever packet received

**Comment by cornacchia** [comment]
Understood. I actually think it will be easier for me to just implement a custom class for the job I need to do at this point. The Automaton class is probably overkill. Thank you for the insights!

**Comment by gpotter2** [comment]
It really isn’t overkill, it’s very powerful but you should check the doc :) it already has the sockets included, so it shouldn’t depend on a sniff()

Good day,
