### ISSUE TITLE
Scapy (re.graph) Issue

### ISSUE THREAD

**Issue by walabus** [secdev/scapy#184]
Hi,

Here is the Scapy Code (Version 2.2.0):

    res,unans = traceroute([“12.0.2.2”],dport=[80,443],maxttl=20,retry=-2)
    res.graph(target="> /tmp/graph.svg")

Error:
![index](https://cloud.githubusercontent.com/assets/2124883/15610395/505ec99c-2425-11e6-9a0f-21cb2a1c2433.png)

Is it not possible to only use the IP address for graphing purposes. I have internal network diagram and want to use Scapy in this. No DNS implementation in the current network. 

Please advice.

Kind regards,
Aubrey

**Comment by p-l-** [comment]
You should upgrade to current development version, but there is another bug there, so wait until #185 has been merged ;)

**Comment by walabus** [comment]
Hi,

Thanks, ETA of the merge?
