### ISSUE TITLE
False negative using packet.haslayer()

### ISSUE THREAD

**Issue by willbelr** [secdev/scapy#1854]
It seems that haslayer() is broken in scapy 2.4.2-1. An app that used to work fine this summer is now broken, as the method always return 0.

\# Details
> Python version: 3.7.2-3
> Scapy version: 2.4.2-1
> OS: Arch Linux (up to date)
> Package: python-scapy
> Network adapter: Alfa AWUS036NHA

\# Steps to reproduce:
1. airmon-ng start wlp0s20u2
2. Run this script:

```
#!/usr/bin/python3
import scapy.all as scapy
dev = "wlp0s20u2mon"

def parse(packet):
    print("PACKET:", packet.layers())
    print("HAS DOT11:", packet.haslayer(scapy.Dot11))

while True:
    scapy.sniff(iface=dev, prn=parse, count=1, store=False)
```

# Output:
> PACKET: [<class 'scapy.layers.dot11.RadioTap'>, <class 'scapy.layers.dot11.Dot11FCS'>, <class 'scapy.layers.dot11.Dot11Beacon'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11EltRates'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11EltRSN'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11Elt'>, <class 'scapy.layers.dot11.Dot11EltVendorSpecific'>, <class 'scapy.layers.dot11.Dot11EltVendorSpecific'>, <class 'scapy.layers.dot11.Dot11EltVendorSpecific'>]
HAS DOT11: 0

**Comment by gpotter2** [comment]
Hi !
Please retry against master, that was fixed in https://github.com/secdev/scapy/pull/1667

**Comment by haim0n** [comment]
Not sure I'm barking at a right tree, but now it seems that the only way to test it Dot11 in the packet is by only accessing it, all other methods fail:
```
>>> pkt = Ether()/IP()/Dot11FCS()
>>> Dot11 in pkt
False
>>> pkt[Dot11]
<Dot11FCS  |>
>>> pkt.haslayer(Dot11)
0
```
And it takes now a try/except wrapping around the code to handle the `IndexError` in case the pkt doesn't have the layer.

**Comment by gpotter2** [comment]
@haim0n Please open a new issue

**Comment by haim0n** [comment]
Maybe it's worth reopening the original issue?
