### ISSUE TITLE
PacketField.randval() ignores size of packet

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#1861]
**Before reproducing:**
Change the line pids_00_1F.py:112 `PacketField('dtc', None, OBD_DTC)` of class `OBD_PID02` to 
`PacketField('dtc', b'', OBD_DTC)`
`fuzz` does not give a random value to a field if its default value is `None`. To the time I wrote this class, I didn't know that.

**Steps to reproduce:**
```python
load_contrib("automotive.obd.obd")
p = fuzz(OBD_PID02())
bytes(p) # repeat
```

**Expected:**
The field `dtc` contains two random bytes.

**Given:**
The field `dtc` contains from 0 to 1200 random bytes.

The reason is, `PacketField` does not overwrite `randval`, thus `StrField.randval()` is called and this one ignores the size of the "packet type" (`cls`) in `PacketField`.

**Comment by polybassa** [comment]
I assume, we have to provide a custom implementation for `randval`, in this case. Is this correct @gpotter2 ?

**Comment by akorb** [comment]
I assume the same. But not in `OBD_DTC`, rather in `PacketField`. This is not an OBD specific but a general issue.

Another example:
```python
p = fuzz(MKABasicParamSet())
bytes(p)
```

**Comment by gpotter2** [comment]
> `fuzz` does not give a random value to a field if its default value is None.

That would break checksums/fields that require `post_build`. If you want to have those fuzzed, you need to set them manually

**Comment by gpotter2** [comment]
Yes, you have to provide a `randval`, as I don’t assume we have anything for PacketField yet :/

We (or you) could add a parameter to PacketField to specify the random generator, that would be called by the PacketField’s `randval()` if that helps

**Comment by akorb** [comment]
> That would break checksums/fields that require `post_build`. If you want to have those fuzzed, you need to set them manually

So, the appropriate default value for checksums is `None` (or post-builded fields in general) and for usual fields `b''`?

**Comment by gpotter2** [comment]
@akorb Yes, that's usually how we do it.

Even things like `ByteField("len", None)`  are used when the length is set in the `post_build`

**Comment by akorb** [comment]
Suggestion to put into `PacketField`:
```python
    def randval(self):
        from scapy.packet import fuzz
        return fuzz(self.cls())
```

fuzz is like `randval` on the Packet-level. And this calls the `randval` method for each field from `cls`.
Works great for my use-case and seems to have the same behavior as the `randval` from other fields:

```python
from scapy.packet import fuzz
from scapy.contrib.automotive.obd.obd import *

class ComparisonPacket(Packet):
    fields_desc = [
        StrFixedLenField('data', b'', 5)
    ]

# Direct randval() calls on fields

r1 = PacketField('dtc', b'', OBD_DTC).randval()
print(bytes(r1))
print(bytes(r1))
print()

r2 = StrFixedLenField('data', b'', 5).randval()
print(bytes(r2))
print(bytes(r2))
print()

# Indirect randval() calls on packets with fuzz()

p = fuzz(OBD_PID02())
print(bytes(p))
print(bytes(p))
print()

p = fuzz(ComparisonPacket())
print(bytes(p))
print(bytes(p))
```

Example output:
```
b'\x9dT'
b'r\xf6'

b'\x9d\xea\x86\xb6\xf5'
b'*\\\x0e\xa6\xc3'

b'b\xb1'
b'\xa0T'

b'\xde\xb5\x05\xd0\xe8'
b'\x94 \x98\xdb='
```

This shows the same behavior for the new and an existing `randval` implementation. Each changes its values on every build.

**Comment by akorb** [comment]
@polybassa @guedou Any thoughts?

**Comment by guedou** [comment]
I think that adding the `randval()` method to `PacketField` makes sense.

**Comment by akorb** [comment]
Great. I will add some unit tests and create a PR soon.
