### ISSUE TITLE
Scapy v2.4.3

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#1866]
~~We need to make a 2.4.3 quite soon, as we're getting tons of reports of the *BSD bug & the missing LICENSE bug (https://github.com/secdev/scapy/issues/1864, https://github.com/secdev/scapy/issues/1862, https://github.com/secdev/scapy/issues/1796, https://github.com/secdev/scapy/issues/1793, https://github.com/secdev/scapy/issues/1783)~~: **See 2.4.3rc1** (which isn't really an rc..)

Among the opened PRs, here are the one I'd like to see included, before the **release** (it's fine if it's not included in the rc):
- [x] https://github.com/secdev/scapy/pull/1869 (Drop distutils + cleanup executables)
- [x] https://github.com/secdev/scapy/pull/1848 (that's something scapy3k was bragging about, except we make a 2-line version of `tdecode` thanks to @p-l- tip)
- [x] https://github.com/secdev/scapy/pull/1849 (it fixes a quite bad regression of the DNS module + cleans it up)
- [x] https://github.com/secdev/scapy/pull/1865 (doc + log fixes)
- [x] https://github.com/secdev/scapy/pull/1847 (the latency thing + doc cleanup)
- [x] https://github.com/secdev/scapy/pull/1884 (quite critical 802.11 fix)
- [x] (potentially) https://github.com/secdev/scapy/pull/1858 if they manage to finish the PR in time
- [x] generally all Automative-related bug fixes, to make sure we have something stable for their first appearances
- [x] https://github.com/secdev/scapy/pull/1994: fix MultipleTypeField
- [x] https://github.com/secdev/scapy/pull/1934: Fox tcpdump detection
- [x] https://github.com/secdev/scapy/pull/1968 : cleanup the DNS implementation
- [x] https://github.com/secdev/scapy/pull/1907: fix Loopback on OpenBSD
- [x] https://github.com/secdev/scapy/pull/1986 : a TLS dissection issue
- [x] https://github.com/secdev/scapy/pull/1996: nice console improvements
- [x] https://github.com/secdev/scapy/pull/2005: fix tshark/tcpdump handling of `linktype`
- [x] https://github.com/secdev/scapy/pull/2028: remove over-restricting rule in monitor mode & doc
- [x] https://github.com/secdev/scapy/pull/2011: Fix Ethertypes
- [x] https://github.com/secdev/scapy/pull/2035: +5-10% dissection speed
- [x] https://github.com/secdev/scapy/pull/1999: **Asynchronous sniffing**
- [x] https://github.com/secdev/scapy/pull/2057: drop dependencies for libpcap Python bindings
- [x] https://github.com/secdev/scapy/pull/1983: Backward compatibility fields
- [x] https://github.com/secdev/scapy/pull/2105: remove duplicated code
- [x] https://github.com/secdev/scapy/pull/2102: fix race conditions
- [x] https://github.com/secdev/scapy/pull/2091: support 802.1Q natively on linux
- [x] https://github.com/secdev/scapy/pull/2108: smarted interface selection with high level commends (sr suite)
- [x] https://github.com/secdev/scapy/pull/2146: TLS 1.3 overhaul

Non blocking but cool:
- [x] https://github.com/secdev/scapy/pull/1925: HTTP 1.0

**Comment by guedou** [comment]
I can do a v2.4.3rc1 on Tuesday and submit it to pypi with the current master. That will fix the main issues and leave more time to fix the other problems.

**Comment by guedou** [comment]
I did not see your answer earlier. A test failed locally, I will submit a PR.

I had to disable the ISOTP unit tests, using:
```
tox -- -T scapy/contrib/isotp.uts
```

@polybassa do you think that it is possible to implement a check that will disable ISOTP unit tests automatically when the mandatory requirements are not installed?

**Comment by guedou** [comment]
Other tests related to the TLS Automaton are also faling locally.

**Comment by polybassa** [comment]
Hi, @epozzobon implemented a similar behaviour here: https://github.com/secdev/scapy/blob/c1ee9d061b531873735a2a31488bb7b28ed8d8bd/scapy/contrib/isotp.uts#L65
I think, we can extend this check to all ISOTPSocket related unit-tests.

**Comment by polybassa** [comment]
@guedou What tests did fail for you, locally?

**Comment by guedou** [comment]
@polybassa the first failing test is
failed 046BF42D Test sniffer with multiple frames

then this one and the following tests:
failed 4953DB12 Verify that packets are not lost if they arrive before the sniff() is called

**Comment by guedou** [comment]
On Unbuntu 18.10, `linux_warnings` fails as well as some tests in `isotp.uts`.

**Comment by polybassa** [comment]
Thanks for this information. I'll create a PR for this. How urgent is this problem? Can it wait a week?

**Comment by guedou** [comment]
@polybassa is that can be fixed before v2.4.3, that will be perfect. I created issue #1887 to track this.

In the mean time, I will release v2.4.3rc1.

**Comment by guedou** [comment]
FYI, I just tagged v2.4.3rc1 and pushed it to pypi. People having issues with v2.4.2 can now do `pip install --pre scapy`.

**Comment by guedou** [comment]
I would like to release v2.4.3 before BlackHat US 2018 where I will présent Scapy.

Shall we start publishing rc regularly like we did for v2.4.0 ? For example, every week before August.

**Comment by gpotter2** [comment]
Sounds good, but I'd like to have the HTTP PR included in the first RC, if possible to get reports on it.

**Comment by guedou** [comment]
I just released v2.4.3rc2. We will do rc3 once the HTTP PR is merged.

**Comment by gpotter2** [comment]
I must say I am happily surprised the SVG rendered properly on PyPI 👍

**Comment by guedou** [comment]
I just released v2.4.3rc3

**Comment by guedou** [comment]
@gpotter2 @p-l- I would like to freeze the last RC by July 24 and only fix mandatory things until the release on August 5 (before my BlackHAt presentation).

Could you have a look at the pending PR at https://github.com/secdev/scapy/projects/4 and merge the relevant ones? I would like to remove them from the project on July 24. Thanks!

**Comment by guedou** [comment]
Here is the proposed v2.4.3 change log (with the help of `git log --no-merges --oneline v2.4.2..v2.4.3rc3`):

# Main Changes

# Core

- 364 commits since v2.4.2
- better native support for FreeBSD, NetBSD, OpenBSD
- Windows: native RAW sockets support, load interfaces/routes using C calls, ...
- latency improvements
- `sniff()` can be used to test BPF fiters on pcap files
- more unit tests and Python3 compatibility
- asynchronous sniffing
- UTScapy vim syntax highlighting

# Layers

## Major changes

## New

- HTTP, ATA over Ethernet, OVD, IEC 60870-5-104, enip, ... 

## Improved

- NetflowV9, ISOTP, Zigbee, RTR, BLE, PPI, DNS, LLDP, ...

**Comment by gpotter2** [comment]
If TLS 1.3 isn't finished by then, I'd advise to delay 2.4.3 slightly (make more rcs if necessary).

Though it's on a great pace, so we probably won't have to do that.

**Comment by guedou** [comment]
I just tagged v2.4.3 and pushed it to pypi.

**Comment by gpotter2** [comment]
Hello @irl and sorry for the ping,

It would be nice if you could find some time to update the Debian package to 2.4.3 :smile:

Would you like us to contact you in some way each time we release a new version (which happens less than once every 6months or so at the current rate) ?

Thanks a lot for your help !
