### ISSUE TITLE
problem with building DHCPv6 relay message

### ISSUE THREAD

**Issue by godfryd** [secdev/scapy#1906]
#### Brief description
I have an issues with building DHCPv6 message while combining dhcp6.DHCP6OptRelayMsg with dhcp6.DHCP6_Solicit. There is added in-between data, DHCPv6 Generic Message.

It seems that this is similar issue to secdev/scapy#1147 but in opposite direction - not while parsing the packet but while building.

#### Environment

-   Scapy version: 2.4.3rc1.dev8
-   Python version: 2.7
-   Operating System: Ubuntu 18.10

#### How to reproduce
In Scapy shell:
```python
m = dhcp6.DHCP6OptRelayMsg() / dhcp6.DHCP6_Solicit()
m.show()
```
#### Actual result
```
###[ DHCP6 Relay Message Option ]### 
  optcode= RELAY_MSG
  optlen= None
  \message\
   |###[ DHCPv6 Generic Message ]### 
   |  msgtype= None
   |  trid= 0x0
###[ DHCPv6 Solicit Message ]### 
     msgtype= SOLICIT
     trid= 0x0
```
#### Expected result

```
###[ DHCP6 Relay Message Option ]###
                 optcode   = RELAY_MSG
                 optlen    = None
###[ DHCPv6 Solicit Message ]###
                    msgtype   = SOLICIT
                    trid      = 0xb253f7
```

**Comment by gpotter2** [comment]
That’s because you need to:
```python
>>> m = DHCP6OptRelayMsg(message=[DHCP6_Solicit()])     >>> m.show2()                                           ###[ DHCP6 Relay Message Option ]### 
  optcode= RELAY_MSG
  optlen= 4
  \message\
   |###[ DHCPv6 Solicit Message ]### 
   |  msgtype= SOLICIT
   |  trid= 0x0

>>>
```
Instead

**Comment by gpotter2** [comment]
Feel free to reopen if you think it still is a bug
