### ISSUE TITLE
Troopers 2019 Slides

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#1914]
Hi,
our slides from the troopers talk are temporarily available here: http://ins-3.de/troopers2019/

What would be the best way in your opinion to make the information in these slides available?
Would it be better to serve these slides somewhere, or should I integrate the relevant information into the Scapy documentation?

**Comment by gpotter2** [comment]
That looks really nice !

Right now all the slides we have are stored on the Scapy.net website https://github.com/secdev/secdev.github.io/tree/master/conf

But that’s messed up, as no one ever bumps into them (The website really needs an overhaul, as it really is an outdated duplicate of the doc. We should remove the demo + build yourself, and implement merge into the doc. I’ll work on cleaning that up when i get time).

In the meantime, you could put them up there, and link to them in the doc, or do whatever you feel is best. (let’s see what the other maintainers say)

Thanks a lot for your involvement in Scapy :smile:

**Comment by guedou** [comment]
Awesome research! I am really happy when Scapy is used with such good results =)

The scapy.net website is likely the best place to add this link! If you feel like it, you can make an interactive tutorial using Jupyter Notebooks and store it into scapy/notebook/

**Comment by polybassa** [comment]
@guedou I would be happy, if you could add the slides to scapy.net (or is this something, I can do by my own?). In the near future we will make some kind of a automotive security lecture. During this, we will generate interactive tutorials. I will not make a notebook right now. 
 
One problem with interactive tutorials for automotive stuff is always the hardware setup. We will think about a decent way, to abstract that.

**Comment by guedou** [comment]
@polybassa you can submita PR to https://github.com/secdev/secdev.github.io and we will merge it.

**Comment by polybassa** [comment]
done
