### ISSUE TITLE
stop_filter is causing memory leaks

### ISSUE THREAD

**Issue by AhmedWas** [secdev/scapy#1918]
The issue is described clearly in this [stackoverflow question ](https://stackoverflow.com/questions/55234510/scapy-stop-filter-is-causing-huge-memory-leak) with simple repro steps.

**Comment by AhmedWas** [comment]
I did a quick fix for it and it's working fine for me. The fix is the answer to the stackoverflow question.

**Comment by AhmedWas** [comment]
sorry, closed by accictendt. Please close it only if you see what I did as an appropriate fix. Thanks!

**Comment by gpotter2** [comment]
Thanks for the report !
This should be fixed in https://github.com/secdev/scapy/pull/1847
