### ISSUE TITLE
How to create a Field that is polymorphic 

### ISSUE THREAD

**Issue by jdiog0** [secdev/scapy#1919]
How can I define a polymorphic field that depends on another field of the same layer. The field is composed of several other fields. Since that field can be one of several classes I would like to avoid multiple ConditionalFields.

Something like what was asked here: https://stackoverflow.com/questions/36138159/virtual-packetfield-how-to-handle-a-polymorphic-protocole

**Comment by gpotter2** [comment]
I’ve answered on StackOverflow :-) under
https://stackoverflow.com/a/55248141/5459467

Basically we now have a new `MultipleTypeField` that does the trick
