### ISSUE TITLE
Missing support for DTLS layer

### ISSUE THREAD

**Issue by piotrek204** [secdev/scapy#1931]
As a scapy user I would like to be able to parse DTLS packet in a similar way as TLS packets. 
Now to do it, have to be installed an external packet ([scapy-ssl_tls](https://github.com/tintinweb/scapy-ssl_tls)). Reducing dependencies (like scapy-ssl_tls) during using the scapy seems to be desirable.

**Comment by guedou** [comment]
Feel free to contribute an implement DTLS. I will be happy to review the code.

**Comment by guedou** [comment]
Moved to  #399
