### ISSUE TITLE
Wifi radiotap not well dissected (bandwidth and SGI)

### ISSUE THREAD

**Issue by JMbonnamy22** [secdev/scapy#1933]
some wifi frames are not well dissected especially bandwidth and Short Guard Interval fields for HT frames.
Envirronnement 👍
-   Scapy version: '2.4.3rc1.dev17'
-   Python version: `e.g. 3.7.2`
-   Operating System: windows 10
![scapy_wifi_dissection](https://user-images.githubusercontent.com/48909249/54942271-035d1580-4f2f-11e9-819a-3db369457356.png)

pkt.bandwidth is always None, should be 0, 1 or 4 (20, 40, 80 MHz)
pkt.guard_interval is always 0 (should be 1 for short guard interval)
you can test on the four frames given in the attached pcap file
[scapy_error.zip](https://github.com/secdev/scapy/files/3004789/scapy_error.zip)

best regards
Jean-Michel

**Comment by gpotter2** [comment]
Hi and thanks for the report !

Could you please check that https://github.com/secdev/scapy/pull/1954 fixes the issue ? Note that some fields were renamed (they were duplicates causing some fields to be `None`)

Thanks !
