### ISSUE TITLE
How to create a variable Field of bytes little endian

### ISSUE THREAD

**Issue by jdiog0** [secdev/scapy#1936]
How to define a Field that stores a variable length of bytes in little-endian and hexadecimal. I would need a camp such as XLEStrLenField.

**Comment by gpotter2** [comment]
Please note that this is an issue tracker, not a forum.
Please questions on the gitter or on specialized forums such as StackOverFlow.

[![Join the chat at https://gitter.im/secdev/scapy](https://badges.gitter.im/secdev/scapy.svg)](https://gitter.im/secdev/scapy?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
