### ISSUE TITLE
Can't send IPv6 packets

### ISSUE THREAD

**Issue by TheNavigat** [secdev/scapy#1941]
#### Brief description

Sending an IPv6 packet fails.

#### Environment

-   Scapy version: 2.4.2
-   Python version: 2.7.15rc1 and 3.6.7
-   Operating System: Ubuntu 18.04

While IPv4 packets are sent correctly, I can't get scapy to send out IPv6 packets correctly through the right interfaces.

Using `tcpdump -i any -e`, I can see the packets with the interface `00:00:00:00:00:00`.

Using Wireshark captures no IPv6 packets on the interfaces connected with the outside world.

The client has 2 interfaces, `eth0` and `eth1`. It can ping the server correctly using the same IPv6 IP I have in the Scapy script.

#### How to reproduce

`send(IPv6(dst="fe80::1038:69ff:fed1:2d8a"))`, where the destination is an actual IPv6 address. The IP address I have here is an actual IPv6 address of an interface I have on the node.

#### Actual result

Packets don't get sent correctly, Wireshark captures nothing on the correct interface (in this case `eth1`)

#### Expected result

Packets should be sent correctly

**Comment by gpotter2** [comment]
We use the same methods to send both v4 and v6 packets, the issue is most likely your configuration / the interfaces.

> Using tcpdump -i any -e, I can see the packets with the interface 00:00:00:00:00:00.

`00:00:00:00:00:00` usually means the packet is on loopback. That matches interface `Lo`. If you wanted to send loopback packets, you might need to use

`sendp(Loopback()/IPv6(...)...)`

but that doesn’t seem to be your case.

Are you sure to actually have IPv6 ? It’s normal to see loopback IPv6 packets even when IPv6 isn’t really available.

Scapy should warn you when loading (shell), and your `conf.route6` should only contain local stuff

**Comment by TheNavigat** [comment]
Thanks for the swift reply!

I have actually tried sending a similar packet using Python's `socket` and `dpkt` and it worked.

```python
import dpkt
import socket

sockfd = socket.socket(socket.AF_INET6, socket.SOCK_RAW, socket.IPPROTO_RAW)

sockfd.setsockopt(socket.IPPROTO_IPV6, socket.IP_HDRINCL, True)

u = dpkt.udp.UDP(
    dport=50000,
    sport=50000,
    data="aa"
)

u.ulen = len(u)

src_ip = socket.inet_pton(socket.AF_INET6, 'fe80::a88f:dff:feaa:564b')
dst_ip = socket.inet_pton(socket.AF_INET6, 'fe80::1038:69ff:fed1:2d8a')

i = dpkt.ip6.IP6(
    dst = dst_ip,
    src = src_ip,
    data = u,
    p = dpkt.ip.IP_PROTO_UDP,
    nxt = dpkt.ip.IP_PROTO_UDP
)

i.all_extension_headers = []
i.extension_hdrs = []
i.len = len(i)
i.plen = len(u)

sockfd.sendto(bytes(i), ('fe80::1038:69ff:fed1:2d8a', 0))
sockfd.close()

print("sent")
```

I am not intending to send loopback packets, but apparently for some reason it ends up on the loopback interface.

I do have IPv6 configured, I assume correctly. `conf.route6` outputs the following:

```
Destination                   Next Hop  Iface  Src candidates            Metric
fe80::/64                     ::        eth1   fe80::a88f:dff:feaa:564b  256
::1/128                       ::        lo     ::1                       0
fe80::a88f:dff:feaa:564b/128  ::        lo     ::1                       0
```

However, as you mentioned, Scapy does indeed complain about no default route for IPv6:

`WARNING: No route found for IPv6 destination :: (no default route?)`

I'm not sure what am I doing incorrectly here.

**Comment by TheNavigat** [comment]
So, after digging a little further it turns out that the problem is with the default routes indeed.

Apparently the default Python library `socket` does some magic that Scapy doesn't do to figure out the correct route.

For those who get stuck at the same problem, https://samsclass.info/124/proj11/P10xN-scapy-ipv6.html helped me a lot.

Thanks!
