### ISSUE TITLE
AttributeError: 'L2Socket' object has no attribute 'ins'

### ISSUE THREAD

**Issue by dfroger** [secdev/scapy#1942]
I'm running `scapy 2.4.2` on `Debian 9`, `Python 3.6`. (I just `pip install scapy`).

This example works (the pcap file is created):

    from scapy.all import Ether, IP, TCP, wrpcap
    packet = Ether() / IP(dst="1.2.3.4") / TCP(dport=123)
    wrpcap('foo.pcap', [packet])

but I get this message on standard error:

    Exception ignored in: <bound method SuperSocket.__del__ of <scapy.arch.linux.L2Socket object at 0x7f0f8bcdd7b8>>
    Traceback (most recent call last):
      File "(...)/venv/lib/python3.6/site-packages/scapy/supersocket.py", line 123, in __del__
        self.close()
      File "(...)/venv/lib/python3.6/site-packages/scapy/arch/linux.py", line 481, in close
        set_promisc(self.ins, self.iface, 0)
    AttributeError: 'L2Socket' object has no attribute 'ins'

Thanks!

**Comment by gpotter2** [comment]
This was fixed very recently https://github.com/secdev/scapy/commit/659f6ccdca2d862c5a477c65ea8b76b68955530e

You can retry using the master build

**Comment by dfroger** [comment]
thanks

**Comment by abriel** [comment]
> This was fixed very recently [659f6cc](https://github.com/secdev/scapy/commit/659f6ccdca2d862c5a477c65ea8b76b68955530e)
> 
> You can retry using the master build

Hi,
just tested master branch and got:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/scapy/supersocket.py", line 129, in __del__
    self.close()
  File "/usr/local/lib/python3.7/site-packages/scapy/arch/linux.py", line 482, in close
    if self.promisc and self.ins:
AttributeError: 'L2Socket' object has no attribute 'ins'
```

So, it fails on the condition?
python version 3.7.2.

Thanks!

**Comment by rllola** [comment]
I have the same error showing.

I also just tested with python 3.6 on ubuntu 18.04

**Comment by gpotter2** [comment]
Please note that this issue only happens after another issue already happens.
Most likely, you didn't start Scapy as sudo

**Comment by rllola** [comment]
Yes, I have been researching a bit about the limitation. I also have the problem that I am using PyQt5 and I have a tray icon element in my app and for that I need the UID to be the one of my user.

I don't know how to solve that ? Any advice ?

**Comment by gpotter2** [comment]
This is not the right place to ask.
You can't use Scapy without admin rights. By that I mean that it's a Linux kernel restriction.

**Comment by rllola** [comment]
It is indeed not the best place. 
I have found a way though... I think.

https://stackoverflow.com/questions/36215201/python-scapy-sniff-without-root

It seems you can hack around it by using `setcap` maybe not recommended ?
