### ISSUE TITLE
Add option for raw to meaningful value conversion when specifying field list

### ISSUE THREAD

**Issue by tigre-bleu** [secdev/scapy#1943]
*Sorry for the unclear title, I agree it sucks but I did not find better. Feel free to make proposals :-)*

## Actual Situation

For some protocols, the content of fields is associated to a resolution parameter. For instance, a geographical heading is physically in the range [0°, 360°] but to make it fit in 1 byte, a resolution of 1.41° is set.

So a raw value of 160 in the field corresponds to an actual heading of 225,6°

It is a lot more practical for the user to handle directly the actual value than the raw value.

Of course in that situation, we could subclass `ByteField` and modify `i2h` and `h2i` to have the required behaviour but this cannot be easily scaled for protocols that handle a lot of different fields like that.

One protocol I work on has dozens if not hundreds of BitFields with various sizes and different resolutions. It is not realistic to create the same amount of custom fields. Unless I missed something, there is no possibility at the moment to tackle the issue.

## Proposal

We could add a way to subdefine a custom i2h and h2i callbacks when listing the fields in `fields_desc` like this:

```python
class MyPacket(Packet):
    name = "Position"

    def raw2deg(self, x):
        return x*1.41

    def deg2raw(self, x):
        return x/1.41

    fields_desc = [
        ByteField("heading", None, i2h=raw2deg, h2i=deg2raw)
        ByteField("something_else", None)
    ]
```

What do you think?

**Comment by gpotter2** [comment]
The recent automotive protocols implemented that: have a look at `ScalingField` in `fields.py` (master branch only)

**Comment by tigre-bleu** [comment]
Thanks, I'll have a look.
