### ISSUE TITLE
Nanosecond libpcap

### ISSUE THREAD

**Issue by tbozo** [secdev/scapy#195]
Hi,

I wish I could use scapy for nanosecond analysis, but I get a 
"Not a supported capture file", when trying to read a pcap encoded as Nanosecond lib pcap.
(I'm using the latest revision)

Enclosed the same 3 packets encoded by wireshark with different settings.
the nanosecondlibpcap.pcap file is the one I'd like to be able to read.
We should be able to see : 
packet 1 at 15:21:09:000150304
packet 2 at 15:21:09:000169406
packet 3 at 15:21:09:000216777

Although pcapng seems to be able to use nanoseconds, somehow the nanosecond part is lost (at least when visualizing with wireshark)

[pcaps.zip](https://github.com/secdev/scapy/files/311692/pcaps.zip)

**Comment by Spannella** [comment]
Hi I was trying to use a nanosecond libpcap dataset as well and I am getting a bad magic error. I would really like to use Scapy for this project. 
Thanks.

**Comment by tbozo** [comment]
you can try dpkt which is more lightweight and does the job

**Comment by p-l-** [comment]
@tbozo @Spannella sorry for the delay, can you test the patch from #412 and tell us if that covers your needs?
