### ISSUE TITLE
sniff() is broken

### ISSUE THREAD

**Issue by m-src** [secdev/scapy#196]
The sniff loop should 'break' if the result from s.recv() is 'None'. This check stops the loop when no more packets are available but got left out sometime after 2.3.2. The CPU will race without it and only Ctrl-C interrupt. Continuous reading from a streaming file object (like subprocess.Popen.stdout) will still work with the check because a read() somewhere will block until data is available, never resulting in an empty s.recv().

Also, won't blocking read()'s hinder the (by the looks of it) ongoing work to support multiple sources by looping thru sniff_sockets? Might the introduction of 'stop_switch' be related to this as well? Oh well, reading from the other sources would not get held up for too long if 'select' unblocks first when a whole packet is available.

**Comment by guedou** [comment]
Thanks for reporting this problem. Could you provide an example that could help us reproduce the issue ?

**Comment by m-src** [comment]
```
import scapy.all as scapy

scapy.sniff(offline='NTP_sync.pcap') # ...or use any capture file
```
Sample capture file: https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=NTP_sync.pcap

Expected result is the sniff summary after processing, eg:
```
<Sniffed: TCP:0 UDP:0 ICMP:120 Other:721>
```
But instead the loop continues, racing the CPU, and must be broken with a KeyboardInterrupt.

Being unfamiliar with the development cycle I'd feel silly supplying a two-line diff, especially since there seems to be ongoing work in the sniff() function...? The added support for an existing file object (as opposed to just a filename) is cool, it allows one to do:
```
# Make dumpcap output raw pcap packets to stdout
dumpcap_args = ['dumpcap', '-w', '-', '-P']
dumpcap = subprocess.Popen(args=dumpcap_args, stdout=subprocess.PIPE)
# Process them with Python
scapy.sniff(offline=dumpcap.stdout
```
The example above still works with the "if p is None: break" check.

**Comment by m-src** [comment]
What I saw as signs of future changes to sniff() probably have other motivations... Putting the source (file, socket, etc) in a list outside the call to select(), and outside of the loop, is better for performance and not necessarily for handling multiple sources. Using stop_event could simply be for clarity/individual preference. I'll add a PR for the original issue...

**Comment by robmarkcole** [comment]
Following this example https://medium.com/@edwardbenson/how-i-hacked-amazon-s-5-wifi-button-to-track-baby-data-794214b0bdd8#.w4nc1y8i5

I get this error

`print sniff(prn=arp_display, filter="arp", store=0, count=10)
  File "/home/pi/Documents/scapy/scapy/sendrecv.py", line 607, in sniff
    **karg)]
  File "/home/pi/Documents/scapy/scapy/arch/linux.py", line 484, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))
  File "/usr/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 1] Operation not permitted`

**Comment by gpotter2** [comment]
Looks that is has been fixed

> Expected result is the sniff summary after processing, eg:
> 
> <Sniffed: TCP:0 UDP:32 ICMP:0 Other:0>

and
```
>>> sniff(offline='NTP_sync.pcap')
<Sniffed: TCP:0 UDP:32 ICMP:0 Other:0>
>>>
```

@guedou @p-l-  Close ?

**Comment by orn1983** [comment]
What version has this been fixed in? Running 2.3.3 (newest in pip at time of writing), and this is still an issue for me. sniff doesn't break loop when it reaches the end of the file. Keyboard interrupt will make it stop sniffing and report sniff summary.

**Comment by gpotter2** [comment]
You should try using the latest GitHub version 
https://github.com/secdev/scapy.git

**Comment by orn1983** [comment]
Sorry -- it has indeed been fixed in the latest GitHub version. I guess it's still broken in PIP.

**Comment by william-stearns** [comment]
Good evening, all,
    What's the next step to get this out as a released package in pip and
ports?
    Cheers,
    - Bill

**Comment by guedou** [comment]
The next stable release will likely happens at the end of the year. In the mean time, you can install the development version using:pip install git+https://github.com/se dev/scapy
