### ISSUE TITLE
Scapy does not replay ping through vpn

### ISSUE THREAD

**Issue by sab24** [secdev/scapy#1978]
#### Brief description

scapy cannot reproduce the packages being generated with ping through an ipsec tunnel on Macos 10.14.4

#### Environment

Setup

    git clone https://github.com/secdev/scapy.git
    cd scapy
    python3 --version
    Python 3.7.3
    sudo ./run_scapy
    WARNING: No route found for IPv6 destination :: (no default route?)

                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
    ayp ayyyyyyySCP//Pp           syY//C    | Version 2.4.3rc1.dev92
    AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | Wanna support scapy? Rate it on
       scccccp///pSP///p          p//Y   | sectools!
      sY/////////y  caa           S//P   | http://sectools.org/tool/scapy/
       cayCyayP//Ya              pY/Ya   |             -- Satoshi Nakamoto
        sY/PsY////YCc          aC//Yp    |
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs
                                       using IPython 7.4.0

#### How to reproduce

     sniff(filter="icmp")

Now ping in another tab

     ping 172.28.3.103

Find it in Scapy:
```
     ^C<Sniffed: TCP:0 UDP:0 ICMP:4 Other:0>
     a=_
     a
     <Sniffed: TCP:0 UDP:0 ICMP:4 Other:0>
     a[0]
     <Loopback  type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=84 id=62879 flags= frag=0 ttl=64 
   proto=icmp chksum=0x2569 src=172.28.4.1 dst=172.28.3.103 |<ICMP  type=echo-request code=0 
   chksum=0xf45 id=0x7674 seq=0x0 |<Raw load='\\\xa8\x82\xf7\x00\x08\xa7\x9b\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./01234567' |>>>>
        sr1(a[0])
        Begin emission:
        Finished sending 1 packets.
        .......................^C
        Received 23 packets, got 0 answers, remaining 1 packets
        conf.route.resync()
        sr1(a[0])
        Begin emission:
        Finished sending 1 packets.
        .......................```

#### Actual result

No ping reply is found

#### Expected result

Ping arrives back

#### Related resources

**Comment by gpotter2** [comment]
Please format your code correctly: use `\`\`\`` above and below code blocks such as
```
This
```

**Comment by sab24** [comment]
> Please format your code correctly: use ``` above and below code blocks such as
> 
> ```
> This
> ```

Thanks, the layout looks better now.

**Comment by gpotter2** [comment]
Does it work generally, without the tunnel ? Usually, you can't replay ICMP packets: hosts dismiss packets with the sequence number

**Comment by sab24** [comment]
> Does it work generally, without the tunnel ? Usually, you can't replay ICMP packets: hosts dismiss packets with the sequence number

Good question. On the LAN from another pc I get 
sr1(IP(dst="172.28.3.103", ttl=20)/ICMP())
Begin emission:
Finished sending 1 packets.
*
Received 1 packets, got 1 answers, remaining 0 packets
<IP  version=4 ihl=5 tos=0x0 len=28 id=1 flags= frag=0 ttl=254 proto=icmp chksum=0x6148 src=172.28.3.103 dst=172.17.0.3 options=[] |<ICMP  type=echo-reply code=0 chksum=0x0 id=0x0 seq=0x0 |>>

Through the vpn:

sr1(IP(dst="172.28.3.103", ttl=20)/ICMP())
Begin emission:
Finished sending 1 packets.
.........................................................................^C
Received 73 packets, got 0 answers, remaining 1 packets

**Comment by gpotter2** [comment]
Are you using the correct interface ? You might have a different interface used for the tunnel.
In that case, you may need to provide the `iface=` argument to `srp`

**Comment by sab24** [comment]
Yeah also thought about that, I tried all interfaces that show routes in the routing table.
```
>>> sr1(IP(dst="172.28.3.103", ttl=20)/ICMP(), iface="ipsec0")
Begin emission:
Finished sending 1 packets.
........................................................................................^C
Received 88 packets, got 0 answers, remaining 1 packets
>>> sr1(IP(dst="172.28.3.103", ttl=20)/ICMP(), iface="en0")
Begin emission:
WARNING: Could not get the source MAC: No MAC address found on ipsec0 !
WARNING: Could not get the source MAC: No MAC address found on ipsec0 !
WARNING: Mac address to reach destination not found. Using broadcast.
WARNING: more Could not get the source MAC: No MAC address found on ipsec0 !
Finished sending 1 packets.
................^C
Received 16 packets, got 0 answers, remaining 1 packets
```

**Comment by gpotter2** [comment]
In your first post, the packet you received has a `Loopback` header. That's not common: Scapy appends `Ether` layers when using `send/sr`. You must be using some sort of loopback interface as proxy.

You might wanna try using the `sr1p/sendp` to send at layer 2 directly, and add yourself the `Loopback` layer.

**Comment by sab24** [comment]
Yeah, I think Ipsec0 is a loopback interface

```
ip addr show ipsec0                                                            ✔  2119  14:52:00
ipsec0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1400
	inet 172.28.4.1 --> 172.28.4.1/8 ipsec0
```

I tried with srp, is this the correct way?

```
a[0]
<Loopback  type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=84 id=7788 flags= frag=0 ttl=64 proto=icmp chksum=0xfc9c src=172.28.4.1 dst=172.28.3.103 |<ICMP  type=echo-request code=0 chksum=0x41d5 id=0x4b55 seq=0x0 |<Raw  load='\\\xa8}\xdd\x00\x05\xa5G\x08\t\n\x0b\x0c\r\x0e\x0f\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./01234567' |>>>>

>>> srp(a[0], iface="ipsec0")
Begin emission:
Finished sending 1 packets.
....................^C
Received 20 packets, got 0 answers, remaining 1 packets
(<Results: TCP:0 UDP:0 ICMP:0 Other:0>,
 <Unanswered: TCP:0 UDP:0 ICMP:1 Other:0>)

```

**Comment by gpotter2** [comment]
I don't understand your situation
> On the LAN from another pc I get
> Through the vpn

?! Another PC on your Lan ? That would mean the machine you are trying to ping is on you LAN, how on earth would it be pingable through a VPN ?!

In any case, that's very likely not a Scapy bug, but rather some consequences of your setup.

**Comment by sab24** [comment]
> I don't understand your situation
> 
> > On the LAN from another pc I get
> > Through the vpn
> 
> ?! Another PC on your Lan ? That would mean the machine you are trying to ping is on you LAN, how on earth would it be pingable through a VPN ?!
> 
> In any case, that's very likely not a Scapy bug, but rather some consequences of your setup.

The LAN I am referring to is the remote location. On the LAN, I mean the physical location there, sshing into that machine. Through the VPN I mean the roadwarrior at another physical location.

The first sniff is from pinging a computer on the lan through the virtual private network(VPN). On Macos I can access all computers on the LAN through the ipsec0 interface, I can ping them, I only cannot ping them through Scapy. All other programs work fine, I use it daily. 

On the LAN is another development server, when running scapy from there things work fine. Probably when I move this computer to the physical location it will also work. It is just scapy somehow not getting traffic through ipsec0 interface. If it was the setup there would be more issues with other programs, which I cannot find. 

Maybe more permissions are needed on Macos to access the tunnel?
