### ISSUE TITLE
RadioTap Dummy Channel vs. Frequency confusion

### ISSUE THREAD

**Issue by bannsec** [secdev/scapy#1979]
#### Brief description
RadioTap layer seems to confuse what the Frequency is vs. what the Channel is.

#### Environment

-   `scapy===git-archive.deve44bd373f`
-   `3.6`
-   `Ubuntu 18.04`

#### How to reproduce
- Simply capture 802.11 traffic and check out the "Channel" field.

#### Actual result
- Channel values such as `2452`

#### Expected result
- The actual channel, such as channel 9 in the above example.
- A separate field called "Frequency" that would contain `2452` from above.

**Comment by gpotter2** [comment]
Hi & thanks for the report
Could you please share a pcap or a packet as bytes/hex so that we can reproduce ?
Thanks !

**Comment by bannsec** [comment]
Sure. Attached
[example.zip](https://github.com/secdev/scapy/files/3050616/example.zip)

**Comment by gpotter2** [comment]
That's not correct. In reality, there is only 1 channel field (and a tags one), which stores the frequency of the channel. Scapy does not interpret, thus unlike wireshark, it does not create "fake" fields to add extra informations.

 When you see "channel 9", what happens in reality is that Wireshark matches the frequency using the following table:
![DAB70E02-FD20-4A52-893D-68AF2ACACB33](https://user-images.githubusercontent.com/10530980/55746396-dc780680-5a39-11e9-8c32-20d4322e94e7.jpeg)

This is technically not a bug. We could however potentially edit the Channel field to display the channel number between parenthesis, it that's any clearer. Feel free to submit a PR

**Comment by bannsec** [comment]
Yep, definitely aware of the frequency vs channel (thus the title and description of this ticket). However, Scapy is indeed either mis-representing the data or improperly parsing it.

RadioTap Defines the channel field here: https://www.radiotap.org/fields/Channel.html

Note, it is explicit that the channel field is comprised of __two__ subfields:
- frequency <-- this is what scapy defines as "Channel"
- flags

Correspondingly, scapy exposes a "Channel" field in the radiotap layer, which appears to actually be the frequency subfield. It further exposes "ChannelFlags" and "ChannelFrequency" which appear to not actually get populated. In this way, the "Channel" field in scapy is incorrect, since it does not include flags as defined by radiotap.

To truly not interpret the underlying information, the Channel field in radiotap layer would be 4 bytes and include the flags.

Note that radiotap does a better job at avoiding some of the confusion since it explicitly calls this frequency, since 802.11 defines channel as frequency bands.

**Comment by gpotter2** [comment]
I see your point.
Currently:
- we use `ChannelFrequency` for `XChannel.freq` https://www.radiotap.org/fields/XChannel
- we use `Channel` for the real channel frequency, because that's what wireshark used to do before switching to `channel.freq`
![6B9924D9-D802-4E22-A4B7-67108F2B449B](https://user-images.githubusercontent.com/10530980/55751887-0257d800-5a47-11e9-9cbd-2b36b639eafd.jpeg)

We could change the names, but that would break already existing code :/

**Comment by bannsec** [comment]
Hmm.. Would it break functionality to also add the frequency to
ChannelFrequency variable that doesn't seem to get populated?

**Comment by gpotter2** [comment]
It's normal that it doesn't get populated: `ChannelFrequency` is used for XChannel ! I literally said that above

**Comment by bannsec** [comment]
Indeed. Just attempting to identify a way to make the attributes in your
tool less misleading.

Imho the proper answer from both a pythonic and following standards
approach would be to change channel into a class object that exposes the
two sub properties. Thus channel.frequency could be used. And for the
concern about breaking things already written for the current way, simply
override pythons duck typing for the class.

**Comment by gpotter2** [comment]
https://github.com/secdev/scapy/pull/1983/commits/2a1cf29bdf1ab03e9357d81a41b9f7436bebee8b should resolve the issue :smile: Feel free to have a look
