### ISSUE TITLE
Messed up SSID display/parse

### ISSUE THREAD

**Issue by bannsec** [secdev/scapy#1981]
#### Brief description
Sometimes it appears scapy mis-parses the SSID in 802.11 packets. It ends up parsing two fields it believes are SSID, the second of which has a bunch of extra garbage (or unparsed data).

#### Environment
- `scapy===git-archive.deve44bd373f`
-   Python `3.6`
-   Operating System: `Ubuntu Bionic`

#### How to reproduce
Load up the attached pcap. `.show` and `repr` to see the weirdness.

#### Actual result
In example:

```
In [6]: pkt.summary()
Out[6]: "RadioTap / Dot11FCS / Dot11ProbeResp / Dot11Elt / Dot11EltRates / Dot11Elt / Dot11EltCountry / SSID='\\x8d[ \\x01\\x03*\\x01\\x00-\\x1a,\\x18\\x1b\\xff\\xff\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x000\\x18\\x01\\x00\\x00\\x0f\\xac\\x04\\x01\\x00\\x00\\x0f\\xac\\x04\\x02\\x00\\x00\\x0f\\xac\\x01\\x00\\x0f\\xac\\x03(\\x006\\x03*L\\x00=\\x16\\x06\\x00\\x05\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00F\\x05s\\xc0\\x00\\x00\\x00\\x7f\\x06\\x00\\x10\\x00\\x04\\x01@\\x85\\x1e\\x10\\x00\\x8f\\x00\\x0f\\x00\\xff\\x03Y\\x001617-AP33-SorcA\\x00\\n\\x00\\x00:' / Dot11Elt / Dot11EltVendorSpecific / Dot11EltVendorSpecific / Dot11EltVendorSpecific / Dot11EltVendorSpecific / Dot11EltVendorSpecific"

###[ 802.11 Information Element ]###
                       ID        = SSID
                       len       = 138
                       info      = '\x8d[ \x01\x03*\x01\x00-\x1a,\x18\x1b\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x000\x18\x01\x00\x00\x0f\xac\x04\x01\x00\x00\x0f\xac\x04\x02\x00\x00\x0f\xac\x01\x00\x0f\xac\x03(\x006\x03*L\x00=\x16\x06\x00\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00F\x05s\xc0\x00\x00\x00\x7f\x06\x00\x10\x00\x04\x01@\x85\x1e\x10\x00\x8f\x00\x0f\x00\xff\x03Y\x001617-AP33-SorcA\x00\n\x00\x00:'
```

The correct SSID was parsed higher up in the packet:

```
###[ 802.11 Information Element ]###
           ID        = SSID
           len       = 9
           info      = 'WLAN-TWDC'
```

#### Expected result
Expecting to see `WLAN-TWDC` as the SSID.

#### Related resources
[dot11_example.zip](https://github.com/secdev/scapy/files/3055459/dot11_example.zip)

**Comment by gpotter2** [comment]
When you link pcaps, please either tell which packet is the right one, or select only the concerned packets... it's annoying to look for it. I've found it this time:
`rdpcap("./dot11_example.pcap")[42]`
But it would be nice not to have to look for them 😄

**Comment by gpotter2** [comment]
Thanks for the report, it appears to be a bug of the `Dot11EltCountry` field. Could you check that https://github.com/secdev/scapy/pull/1984 fixes the issue for you ? Thanks !
