### ISSUE TITLE
bluetooth ATT group packetlist parsing question 

### ISSUE THREAD

**Issue by notmikeb** [secdev/scapy#1995]
#### Brief description
how do use a length field with a list of grouped fields for Bluetooth ATT protocol

I am doing some Bluetooth ATT packet parsing
I don't know to to use PacketListField or FieldListField to do the parsing
could you get me a hint about dynamic field length?

I use a fixed value, 7 , to do the att_data_list parsing
but i should not use a fixed value,7

regarding ATT "Read_By_Type_Response" spec's definition, 
length field is the length of a pair of Handle and Value, aka Attribute_Data_HandleValue.
after length field , there are a few Attribute_Data_HandleValue Fields
It is a list grouping fields
user could use att_data_list[0].handle to access the handle value
user could use att_data_list[0].data to access the data value

#### Environment
-   Scapy version: latest
-   Python version: 3.5
-   Operating System: win10

#### How to reproduce
my temporary workaround code are shown below
It only works when length is 7
I wonder how to change it to arbitrary length field

a full sample code
#sample-data
```python
from scary.layers.bluetooth import *
a1 = HCI_Hdr(bytes.fromhex('0248201b001700040009070200020300002a0400020500012a0600020700042a'))

a1.show()
```

Console output as below
###[ ATT header ]###
           opcode    = 0x9
###[ Read By Type Response ]###
              length    = 7
              \att_data_list\
               |###[ Attribute_Data_HandleValue ]###
               |  handle    = 0x2
               |  data      = 020300002a
               |###[ Attribute_Data_HandleValue ]###
               |  handle    = 0x4
               |  data      = 020500012a
               |###[ Attribute_Data_HandleValue ]###
               |  handle    = 0x6
               |  data      = 020700042a

The code snippet inside scapy/layers/Bluetooth.py

```python
class Attribute_Data_HandleValue(Packet):
    name = "Attribute_Data_HandleValue"
    fields_desc = [XLEShortField("handle", 0),
                   XStrLenField("data", 0, length_from= lambda x: 5),
                   ]
    def extract_padding(self, p):
        return "", p

class ATT_Read_By_Type_Response(Packet):
    name = "Read By Type Response"
    fields_desc = [
                   ByteField('length', None), 
                   PacketListField ("att_data_list", None, Attribute_Data_HandleValue), 
                    ]
                    
```

#### Expected result
not to use a fixed length 7 to do the parsing
The length field is a arbitrary number

after length field, there are a few Attribute_Data_HandleValue Fields
those Attribute_Data_HandleValue should have the same length of data value

user could use att_data_list[0].handle to access the handle value
user could use att_data_list[0].data to access the data value

#### Related resources
the length is not a fixed value
so the data is a kind of XStrLenField with a 'length_from' value
since Attribute_Data_HandleValue cannot access the length value, I don't know how to get the length value and create it

###[ ATT header ]###
           opcode    = 0x9
###[ Read By Type Response ]###
              length    = 6
              \att_data_list\
               |###[ Attribute_Data_HandleValue ]###
               |  handle    = 0x2
               |  data      = 02030000
               |###[ Attribute_Data_HandleValue ]###
               |  handle    = 0x4
               |  data      = 02050001
               |###[ Attribute_Data_HandleValue ]###
               |  handle    = 0x6
               |  data      = 02070004

**Comment by gpotter2** [comment]
Hi. Please format your post correctly, it's barely readable :/
https://github.github.com/gfm/

**Comment by notmikeb** [comment]
Hi
I reformat it
Could you check it
Thanks

**Comment by notmikeb** [comment]
> Hi. Please format your post correctly, it's barely readable :/
> https://github.github.com/gfm/

hi sir,
I reformat it
thanks

**Comment by gpotter2** [comment]
Thanks for the report ! It should now be fixed in https://github.com/secdev/scapy/issues/2015

**Comment by gpotter2** [comment]
@notmikeb Also, I had a question to ask you:
I've noticed that you own a copy of the Scapy documentation, available over:

https://readthedocs.org/projects/markdown222/

This copy is apparently based on scapy3k, which has now been renamed + is quite outdated. Is there a reason of why you keep it online ?
If you are not using, it would be nice if you could delete the read the docs page, because it is quite confusing: some users reported they were looking for "scapy3" which doesn't exist anywhere else.

Thanks for your understanding !

**Comment by notmikeb** [comment]
Close the page :)
