### ISSUE TITLE
Is there a way to follow tcp stream using scapy

### ISSUE THREAD

**Issue by li-develop** [secdev/scapy#2001]
Hello, I just using scapy to analysis a pcap . Can scapy has a way to doing follow tcp stream like wireshark?

**Comment by gpotter2** [comment]
If you're working on a pcap, you can use
`rdpcap("./pcap").sessions()`

**Comment by rith-vik-7** [comment]
How exatly to extract objects from `TCP STREAM` using scapy like we do in wireshark

**Comment by gpotter2** [comment]
This is not a forum
