### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by Technerder** [secdev/scapy#2004]
#### Brief description

I am currently trying to install scapy for python3 on my debian 9.8 machine

#### Environment

-   Scapy version: Latest pypi version
-   Python version: 3.5.3
-   Operating System: Debian 9.8 Stretch

#### How to reproduce

Run: ``sudo python3 -m pip install scapy``

#### Actual result

`Collecting scapy
From cffi callback <function _verify_callback at 0x7ff4454ea2f0>:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/SSL.py", line 309, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: module 'lib' has no attribute 'X509_up_ref'
  Could not find a version that satisfies the requirement scapy (from versions: )
No matching distribution found for scapy
`

#### Expected result

Expected it to install like all other packages

**Comment by gpotter2** [comment]
This is not a Scapy issue bug an issue with your environment.
Have a look at https://github.com/pyca/pyopenssl/issues/728, your PyOpenSSL version is outdated. It's usually a pain to fix as you can't use pip to update it.

My advice would be to update it via your distro's package manager, then update pip then uninstall it.

**Comment by Technerder** [comment]
Thank you for the quick response, reinstalling ``pyopenssl`` seemed to fix the issue
