### ISSUE TITLE
Help on  gtp-u inner IPv6  scapy command  !!

### ISSUE THREAD

**Issue by asingh1984** [secdev/scapy#2007]
I'm trying to craft GTP-U packets , for the following address family scenarios.
a) For Inner IPv4 scenarios - Wireshark do recognize it as GTP packets
b) But For Inner IPv6 scenarios - Wireshark does not recognize it as GTP packets (Wireshark just treats it as data.. )

Need some help to get the correct format for inner ipv6 command,  so the wireshark treats it as GTP-U packets  instead of data packets.

thanks !

======================
GTP-U commands
=====================
1) Outer IPv4 and Inner IPv4 --> Wireshark does recognize it as GTP packets.
send(IP(src="100.100.100.1", dst="100.100.100.81")/UDP(sport=2152,dport=2152)/GTP_U_Header(TEID=9999)/IP(src="1.1.1.1", dst="2.2.2.2")/UDP(sport=1111,dport=2222),inter=0.01,count=1)

2) Outer IPv6 and Inner IPv4 --> Wireshark does recognize it as GTP packets.
send(IPv6(src="2002::100:100:100:1",dst="2002::100:100:100:81")/UDP(sport=2152,dport=2152)/GTP_U_Header(TEID=9999)/IP(src="1.1.1.1", dst="2.2.2.2"),inter=0.01,count=100)

3) Outer IPv4 and Inner IPv6 --> Wireshark does not !!! recognize it as GTP packets. (Wireshark just treats it as data.. )
send(IP(src="100.100.100.1", dst="100.100.100.81")/UDP(sport=2152,dport=2152)/GTP_U_Header(TEID=9999)/IPv6(src="2002::101:101:101:1", dst="2002::102:102:102:1")/UDP(sport=1111,dport=2222),inter=0.01,count=100)

4) Outer IPv6 and Inner IPv6 --> Wireshark does not !!! recognize it as GTP packets.(Wireshark just treats it as data.. )
send(IPv6(src="2002::100:100:100:1",dst="2002::100:100:100:81")/UDP(sport=2152,dport=2152)/GTP_U_Header(TEID=9999)/IPv6(src="2002::101:101:101:1", dst="2002::102:102:102:1")/UDP(sport=1111,dport=2222),inter=0.01,count=10)

#### Things to consider

1.  Please check that you are using the latest scapy version, e.g. installed via:

    `pip install --upgrade git+git://github.com/secdev/scapy`

2.  If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: <https://gitter.im/secdev/scapy>

3.  Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: <https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde>

#### Brief description

> describe the main issue in one sentence
> if possible, describe what components / protocols could be affected by the issue (e.g. wrpcap() + IPv6, it is likely this also affects XXX)

#### Environment

-   Scapy version: `scapy version and/or commit-hash`
-   Python version: `e.g. 3.5`
-   Operating System: `e.g. Minix 3.4`

> if needed - further information to get a picture of your setup (e.g. a sketch of your network setup)

#### How to reproduce

> step-by-step explanation or a short script, may reference section 'Related resources'

#### Actual result

> dump results that outline the issue, please format your code

#### Expected result

> describe the expected result and outline the difference to the actual one, could also be a screen shot (e.g. wireshark)

#### Related resources

> traces / sample pcaps (stripped to the relevant frames), related standards, RFCs or other resources

**Comment by gpotter2** [comment]
Please fill the issue template
