### ISSUE TITLE
L2CAP_ConnResp answers method is comparing the wrong Channel Identifier fields

### ISSUE THREAD

**Issue by HorakS** [secdev/scapy#2012]
#### Brief description

The answers method of L2CAP_ConnResp (scapy/layers/bluetooth.py) is comparing the wrong Channel Identifier fields.

#### Actual result

The answers method of L2CAP_ConnResp checks whether the _dcid_ field of the Response is the same as the _scid_ field from the Request.
However, according to Bluetooth Core spec v4.2 (p. 63):

> 4.3 CONNECTION RESPONSE (CODE 0x03)
> Source Channel Identifier - SCID (2 octets)
> This field contains the channel endpoint on the device receiving this
> Response packet. This is copied from the SCID field of the connection
> request packet.

On the other hand, the Destination Channel Identifier (DCID) of the Response is chosen by the receiver of the Request and is not necessarily related to the SCID of the Request.

This leads to L2CAP Connection Responses not getting detected as answers to Connection Requests if SCID and DCID differ.

#### Expected result

Instead of:

> return isinstance(other, L2CAP_ConnReq) and self.dcid == other.scid

it should be 

> return isinstance(other, L2CAP_ConnReq) and self.scid == other.scid

**Comment by gpotter2** [comment]
Thanks for the notice !

Feel free to submit a PR
