### ISSUE TITLE
BluetoothHCISocket recv() method has no default value for parameter x (bufsize)

### ISSUE THREAD

**Issue by HorakS** [secdev/scapy#2013]
#### Brief description

The recv() method of BluetoothHCISocket is missing a default value for the 'x' parameter, which may cause an Exception when calling sniff() on the socket.

#### How to reproduce

- Create a BluetoothHCISocket and call its sniff() method.
- Make sure there is HCI traffic going on, e.g. by sending commands to your HCI device.

#### Actual result

There is an Exception, since no value for argument 'x' of recv() is provided:

>  File "test.py", line 12, in <module>
>   s.sniff()
>  File "/usr/lib/python3/dist-packages/scapy/supersocket.py", line 73, in sniff
>    return sendrecv.sniff(opened_socket=self, *args, **kargs)
>  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 767, in sniff
>    p = s.recv()
> TypeError: recv() missing 1 required positional argument: 'x'

#### Expected result

A default value for the buffer size should be used. Probably 0xfff as for the BluetoothL2CAPSocket.

**Comment by gpotter2** [comment]
It appears that you are using an old Scapy version (the lines quoted have been changed since then).

Please retry against master

**Comment by HorakS** [comment]
You are correct. This has been fixed already 2 months ago. I was still using 2.4.0.
