### ISSUE TITLE
Problem with Ether function with dual interfaces

### ISSUE THREAD

**Issue by CJLaFleur** [secdev/scapy#2017]
Hi all,

I've been messing around with Scapy recently and I like it a lot. I recently built a ping tool and I wanted to add features to it using Scapy. I've been trying to use scapy to get the MAC address of active hosts on my network, but it seems like doing this from a host with two active NICs causes some problems.

I'm using a pretty simple script that looks like this:

import scapy.all as scapy

def scan(ip):
    req = scapy.ARP(pdst = ip)
    broadcast = scapy.Ether(dst = "ff:ff:ff:ff:ff:ff", src = "MAC")
    broadcast_req = broadcast/req
    answered = scapy.srp(broadcast_req, timeout = 1)[0]
    print(answered.summary())

scan("192.168.245.3/24")

I know it works on a machine with a single interface because I've tried it. I've also tried changing the MAC from the broadcast MAC to the MAC of the interface I wish to use, but that didn't seem to help either. I also tried setting the source MAC when calling the Ether function as shown in my code, but that also did not fix the issue.

I'm using Python 3.6 and Scapy 2.4.2

I couldn't find anything that seemed helpful regarding this issue in the documentation or the rest of this forum so I'm not sure if this is a bug or if it's just an obscure detail missing. Anyway, thanks for the help.

Also, a side note. in the ARP Ping section of the documentation, this command fails ans.summary(lambda (s,r): r.sprintf("%Ether.src% %ARP.psrc%") )

**Comment by gpotter2** [comment]
The networking functions have a `iface` key argument to select the interface you want to use.
