### ISSUE TITLE
Unable to Index into Scapy List for TLS packet

### ISSUE THREAD

**Issue by xq1xq1xq1** [secdev/scapy#2019]
#### Brief description

Trying to index to get second item in TLS list

#### Environment

-   Scapy version: 2.3.2
-   Python version: 2.7.12
-   Operating System: Ubuntu 16.04.5 LTS

#### How to reproduce

Capture TLS Exchange and create PCAP.
Read TLS Packet into Scapy

The structure of the TLS packet looks like:

[ Ether ]
[ IP ]
.
.
.
[ TLS Client Hello ]
[ TLS Extension ]
.
.
.
.
[ TLS Extension Application-Layer Protocol Negotiation ]
  length - 0xc
  [TLS ALPN Protocol]
    length = 0x2
    data = 'xx'
  [TLS ALPN Protocol]
    length = 0x8
    data = 'http/1.1'

when I print out the item pathed down to
[ TLS Extension Application-Layer Protocol Negotiation ].data I only get xx.

sslpacket['TLS Record']['TLS Handshakes']

I can not get to the second item with the  http/1.1 data

When I iterate over [ TLS Extension Application-Layer Protocol Negotiation ] in a   for    loop I only find 1 element and that is for xx

#### Actual result

only retrieve 1st item in list

#### Expected result

Be able to index to any item in list and get data for that item

**Comment by gpotter2** [comment]
See https://stackoverflow.com/a/56044587/5459467
