### ISSUE TITLE
Send RTS frame once, but capture multiple RTS frames instead

### ISSUE THREAD

**Issue by shyan003** [secdev/scapy#2026]
#### Brief description

> I tried to build and send RTS frame from my PC, but I captured multiple RTS frames from other computer. I had tried Python 2 and 3, still same problem.

#### Environment

-   Scapy version: `2.4.2`
-   Python version: `3.7.3`
-   Operating System: `Fedora 30`
-   Wi-Fi Adapter: `Asus AC51`

#### How to reproduce

> This is the script I wrote.
![Screenshot from 2019-05-15 17-53-18](https://user-images.githubusercontent.com/45695077/57768051-5d16da80-773d-11e9-8451-09e30ea4f32d.png)

#### Actual result

> The output from Python 3 when I run the script.
![Screenshot from 2019-05-15 17-51-54](https://user-images.githubusercontent.com/45695077/57768167-a2d3a300-773d-11e9-8d7a-0ce5d7352797.png)

> What I captured from local computer
![Screenshot from 2019-05-15 18-02-44](https://user-images.githubusercontent.com/45695077/57768216-bd0d8100-773d-11e9-999b-68ecaea5f025.png)

> What I captured from other computer
![Screenshot 2019-05-15 at 17 52 23](https://user-images.githubusercontent.com/45695077/57768252-ceef2400-773d-11e9-8899-9fb452e535c7.png)

#### Expected result

> I expected the RTS frame was sent only once.

**Comment by gpotter2** [comment]
Hi & thanks for the report !

The last time I checked this issue (we already had a report if I recall correctly), we got to the conclusion that it wasn't on Scapy side (might not be 100% true).

You could try using `libpcap` (`conf.use_pcap = True` and `monitor=True` when sending), to see if that helps.

It's most likely due to how we inject the packets, that might conflict with either the kernel or some drivers, resulting in the packet being duplicated :/

**Comment by shyan003** [comment]
@gpotter2 I installed pcapy and modified the script as you said, but the problem still existed.

I installed devel versions.
![Screenshot from 2019-05-16 14-00-32](https://user-images.githubusercontent.com/45695077/57830657-5774cf80-77e5-11e9-9593-899be79ed289.png)

I installed pcapy.
![Screenshot from 2019-05-16 14-01-09](https://user-images.githubusercontent.com/45695077/57830658-580d6600-77e5-11e9-83cf-fa66c61b3f50.png)

I modified the script.
![Screenshot from 2019-05-16 14-01-37](https://user-images.githubusercontent.com/45695077/57830659-580d6600-77e5-11e9-84d6-dfe22046955e.png)

**Comment by gpotter2** [comment]
When using `pcapy`, it should be
`sendp(frame, iface=iface, monitor=True)`

**Comment by shyan003** [comment]
Problem still existed.

**Comment by gpotter2** [comment]
That's most likely due to your driver. If even `libpcap` can't get around it, (they've been doing that for far longer than we have), we probably can't do much about it :/

**Comment by shyan003** [comment]
OK, I will test on other Wi-Fi adapters.

**Comment by guedou** [comment]
I cannot reproduce either. 

Please re-open the issue if you find a way to reproduce it.
