### ISSUE TITLE
Is Scapy Proxy Aware?

### ISSUE THREAD

**Issue by siftfan99** [secdev/scapy#2030]
I just have a quick question. I'm trying to send a packet build by Scapy to a remote destination IP, but there's a proxy in my way. Is Scapy proxy aware? Can Scapy be configured to send packets through a proxy so they reach their final destination? I searched online & through the Scapy documentation.

I'm having a hard time finding anything that would help. Some online hits refer to using/building Scapy as a proxy, but that's not what I'm after.

TIA!
Siftfan99

**Comment by guedou** [comment]
Scapy injects packets at layer 2 or 3. A proxy usually works at upper layer, after TCP or UDP.

If there is a proxy on your network, you won't be able to send arbitrary packets at layer 2 or 3. Scapy won't help you.
