### ISSUE TITLE
sniff() misses tcp segments during nfs traffic 

### ISSUE THREAD

**Issue by avekceeb** [secdev/scapy#2036]
#### Brief description
Packets missed by scapy sniff when capturing nfs writes with sizes > 1K

#### Environment
-   Scapy version: 2.4.3rc1.dev160
-   Python version: 2.7.12 | 3.5.2
-   Operating System: Ubuntu 4.15.0-50-generic

#### How to reproduce
```python
ps = sniff(iface='enp0s25')
```

```bash
mount -o vers=4.1,proto=tcp,sec=sys,hard,intr,rsize=1024,wsize=1024 \
            nfs.server.addr:/srv /mnt
dd if=/dev/urandom of=/mnt/testfile bs=1048576 count=1 oflag=direct
# this produces a bunch of 1236 byte-long writes (rpc + nfs headers + 1K data)  
```
``` python
# ^C
wrpcap('nfs-traf-by-scapy.pcap', ps)
# problem could be inspected in wireshark by opening saved pcap
# or by inspecting tcp seqence nr and lengths (see runme.py below):
from runme import show_seq
show_seq(ps)
```

#### Actual result
```
#287: seq=453958555 len=116 next=453958671
#288: seq=3054623541 len=1236 next=3054624777
#289: seq=453958671 len=116 next=453958787
#290: seq=3054624777 len=1236 next=3054626013
... segment(s) missed
#291: seq=453958903 len=116 next=453959019
... segment(s) missed
#292: seq=3054627249 len=1236 next=3054628485
... segment(s) missed
#293: seq=453959947 len=116 next=453960063
... segment(s) missed
#294: seq=3054638373 len=1236 next=3054639609
```
#### Expected result
All the packets are captured. Note that this is always the case with steps above but using tcpdump

#### runme.py
```python
def show_seq(pkts):
    seqs = []
    i = 0
    for p in pkts:
        i += 1
        if TCP in p:
            tcp = p.payload.payload
            if hasattr(tcp, 'payload') and (2049 in (tcp.sport, tcp.dport)):
                l = len(tcp.payload)
                s = tcp.seq
                n = l+s
                seqs.append(n)
                if i < 5:
                    continue
                if s not in seqs:
                    print("... segment(s) missed")
                print('#%d: seq=%d len=%d next=%d' %
                    (i, s, l, n))
```

**Comment by guedou** [comment]
Unfortunately, Scapy could miss some packets under load. Here, you can use `sniff(filter="tcp and port 2049")` to benefit from Linux kernel filters.

**Comment by avekceeb** [comment]
Oh, I've got...
But where is the bottle neck? Can I tweak it somehow? Or is this some fundamental python limitation?
Thank you for the hint.

**Comment by guedou** [comment]
Unfortunately, there is not much that you can easily do.

**Comment by gpotter2** [comment]
> this some fundamental python limitation

That's more like it. Scapy never "skips" any packets on its own. In the worse case, a packet is not dissected and appears as `Raw()`.

We rely either on Python (Linux) or libpcap (and it's wrappers) to provide the packets.
Switching to libpcap might help, by setting
`conf.use_pcap = True`
but there is no guarantee.

**Comment by avekceeb** [comment]
Indeed, `use_pcap` improves things dramatically - in the same case first missed segment becomes `#1515` vs `#290` previously
Setting  `bind_layers(TCP, Raw, dport=2049) bind_layers(TCP, Raw, sport=2049)` does not do any magic :-)

Anyway, thank you, guys for clarifying stuff, I'll be more modest on traffic...
