### ISSUE TITLE
Where to place commandline utilities

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2044]
Hi Scapy Maintainers,

we are planning to release some small commandline utility scripts for Scapy. Here an example:
ISOTPScanner: Scans for open isotp sockets on targets
In Scapy, we have a function like this
`def isotpscan(socket, range, ...)` which returns found sockets as a list.
In addition to that, we would like to provide a small commandline utility, as well. 
```
...
def main()
    argparse() #Some parameters
    isotpscan(args.socket, args.range, ...)
```
This commandline utility is basically using the same functions. I would like to have both possibilities. Using the isotpscan from a Scapy session or using the utility from a terminal.

Can I add these utility files to Scapy? If yes, where should I add these files? Somewhere inside my automotive structure? In modules?

Cheers

**Comment by guedou** [comment]
We already have some tools in `scapy/tools/`. I think that it makes sense to also put these ones.

**Comment by polybassa** [comment]
Thanks for your answer.
