### ISSUE TITLE
Bug: wrong base class usage in radius.

### ISSUE THREAD

**Issue by lidllohntsich** [secdev/scapy#2045]
the following file should be corrected:
scapy/layers/radius.py

`
class _RadiusAttrIPv4AddrVal(RadiusAttribute):
.....
`

should be:
`
class _RadiusAttrIPv4AddrVal(_SpecificRadiusAttr):
.....
`

without this change, the 'type' IE will be always 4.

**Comment by gpotter2** [comment]
Hi & thanks for the report.
Feel free to submit a PR !
