### ISSUE TITLE
Python 3.4 Tests failing

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#2049]
All Python 3.4 (and only those) tests have been failing for a few days *(yesterday?)* 🙁 

It's an issue with `pip` that fails to install `tox`, at a moment where it tries to (un?)install `six`. My guess would be that the `six` installed by default on Travis is partially/wrongly installed, but I've opened an issue there to be sure.

I tried to install the latest pip version to see if that fixed the issue in https://github.com/secdev/scapy/pull/2050. It didn't

**Some failing builds:**

https://travis-ci.com/secdev/scapy/jobs/204212531
https://travis-ci.com/secdev/scapy/jobs/204212540

**The Issue on travis.community**
https://travis-ci.community/t/python-3-4-failing-to-uninstall-pre-installed-six-since-a-few-days/3562

**Comment by gpotter2** [comment]
@guedou The bug actually seems to still be active.

Do we really want to fight to get the 3.4 builds running ? The EOL of 3.4 was last March:
https://www.python.org/dev/peps/pep-0429/#id4
IMH we should just drop those builds..

**Comment by guedou** [comment]
I had some strange errors too (“toc command not found”), and I guess that it is related to Travis.

I don’t mind supporting “old” Python versions as long as we don’t spend too much time doing so.

I would like to support Python 3.4 for v2.4.3 if possibles. As we suffer from errors, I think that the best alternatives is to comment the 3.4 test, and open an issue tagged with the next release to remind us to have a look (either removing the support or fixing it).

Does this sound ok?

**Comment by gpotter2** [comment]
@guedou Sounds good !

**Comment by guedou** [comment]
It seems that #2051 did the trick! The tests looks stable now.
