### ISSUE TITLE
BitField crossing byte bonduary incorrect

### ISSUE THREAD

**Issue by wodz** [secdev/scapy#2054]
scapy 2.4.2
python 3.6.7

#### How to reproduce
class Test(Packet):
  name = 'Test'
  fields_desc = [
    BitField('value0', 0, 12),
    BitField('value1', 0, 12),
    ByteField('value2', 0)]

d = bytes([0x5f, 0xf0, 0x05, 0x00])
T(d)
<T value0=1535 value1=5 value2=0 |>

How values are incorrect (I think this is due to crossing byte boundary).

**Comment by guedou** [comment]
Please respect the issue template. We need the Python version, Scapy version to help you.

**Comment by guedou** [comment]
Everything looks fine 0x5ff is 1535, and 0x005 is 5. Reopen if necessary.
