### ISSUE TITLE
MTU size unnecessarily too big in some circumstances making scapy performance bad for small packets?

### ISSUE THREAD

**Issue by KaliszAd** [secdev/scapy#2055]
My problem is, getting packets from [PcapReader](https://github.com/secdev/scapy/blob/6dde6ae78bc0cc3a577035d7469c2806e97160e8/scapy/utils.py#L1032-L1036) from scapy.utils seems to be quite slow. I am searching for ways to make it perform better.

```
def read_packet(self, size=MTU):
        rp = super(PcapReader, self).read_packet(size=size)
        if rp is None:
            return None
s, pkt_info = rp
```

Here, it seems [MTU size being 0xffff -> 65535 bytes](https://github.com/secdev/scapy/blob/449ce6af007638156d0f681ccd5e543bcb84238e/scapy/data.py#L154) are read no matter how big the actual packet might be. If pcap-captures with a certain snaplen are being processed, the MTU will be often times to two orders to large and introduce (in my opinion) unnecessary inefficiency.

Without having deep understanding of the code at hand, I want to reach out for ideas how to improve the efficiency without breaking stuff. Maybe, the MTU for PcapReader purposes could be set more conservatively and if it turns out later in the processing, that further bytes need to be read, those should be returned and the MTU adjusted by some relative amount for further packets. This could also work in the opposite direction, starting large and adjusting based on real observed length.
(This would be like TCP window scaling, where we start small and adjust.)

Another approach would be to supply a hint to PcapReader that the packets will not be larger than n bytes (for instance because we know the snaplen we captured with) and therefore it is meaningless to read more than that at a time.

This could of course introduce an adverse effect by basically doing very small reads and not gaining any benefit. Maybe, some kind of buffer (maybe even of the size 64k or more) and reading from it could have the desired effect of preventing block storage IO and processing small packets with greater efficiency.

**Comment by KaliszAd** [comment]
Btw. the file I am processing contains ~ 10 mio packets captured with snaplen of 128 bytes (file is 1.2 GB big). Just reading it with dd and writing to /dev/null with block size of 64k takes about 0.13 seconds, because it is already in RAM. Even after a page cache flush it takes about 1.8 seconds.
Just iterating through 100000 packets without doing anything it takes about 24 seconds. With doing some data analysis, the same takes about 30 seconds. Obviously, just getting the packets for processing takes 80% of the time in this case.

**Comment by KaliszAd** [comment]
And for 1 mio packets processed, the numbers look even worse. Just reading the packets takes 272 seconds, while reading and also processing them takes 326 seconds. It looks like the reading of the packets starts to dominate the more packets are read. (Probably because the processing of the packets actually uses dictionaries and therefore doesn't get extended much after a certain amount of items in it.)
The measurement is done with Core i7-7500U, 16 GB RAM and a NVMe SSD.

**Comment by gpotter2** [comment]
Interesting question. A few thoughts:
- we are aware that Scapy is slow (sadly). We take more time to read most packets than some other libraries, because of how we pack the fields/packets: indeed, some libraries are faster, but each layer is implemented in hundreds of lines (dpkt...), therefore not flexible at all
- It's interesting that you state that the reading time takes longer that packet dissection, I was pretty convinced of the opposite (might be wrong).
- I'm pretty sure the MTU is a wrong lead (again I could be wrong). Here's where we use it:
https://github.com/secdev/scapy/blob/449ce6af007638156d0f681ccd5e543bcb84238e/scapy/utils.py#L980
We read the packet using the size provided by its pcap header. It's dynamic, we only "crop" packets bigger than the MTU

**Comment by KaliszAd** [comment]
Last but not least a comparable dpkt script, that iterates through 1 mio packets and parses them in a basic way takes on the same machine 13.5 seconds (21x faster!). I guess, I will try to port my packet analysis to dpkt and report back, how it went.

**Comment by KaliszAd** [comment]
> Interesting question. A few thoughts:
> 
>     * we are aware that Scapy is slow (sadly). We take more time to dissect packets than some other libraries, because of how we pack the fields/packets: indeed, some libraries are faster, but each layer is implemented in hundreds of lines (dpkt...), therefore not flexible at all. That's why we support way more protocols
> 
>     * It's interesting that you state that the reading time takes longer that packet dissection, I was pretty convinced of the opposite (might be wrong).

If I see correctly, there is some minimal [parsing](https://github.com/secdev/scapy/blob/6dde6ae78bc0cc3a577035d7469c2806e97160e8/scapy/utils.py#L1039) going on if I write:
`for pkt in PcapReader(capture_name)`


>     * I'm pretty sure the MTU is a wrong lead (again I could be wrong). Here's where we use it:
>       https://github.com/secdev/scapy/blob/449ce6af007638156d0f681ccd5e543bcb84238e/scapy/utils.py#L980

Yes, that assumption seems right - my bad, I glossed over the function. After a test, I see the caplen seems to be appropriate considering the data. I really is possible, that the caplen is in fact so short (often 60 bytes in my case), that exactly what I was talking about is happening - maybe the small reads are not beneficial for performance and some kind of larger chunk read + buffer would behave better.

The slicing is performant enough (actually substantially faster for larger numbers):
timeit.repeat("b'0156464aeffb0156464aeffb0156464aeffb0156464aeffb0156464aeffb'[:65535]")

>       We read the packet using the size provided by its pcap header. It's dynamic, we only "crop" packets bigger than the MTU

I will be happy to provide some further help and answer questions. I see the strengths of Scapy, but speed doesn't seem to be one of those, which is unfortunate, since some tasks depend on the speed.

I renamed the issue to reflect these findings.

**Comment by KaliszAd** [comment]
So even after I have completely ported my packet analysis over to dpkt, I am still ~20x faster with processing 10.8 mio packets in 185 seconds. @gpotter2 is right about dpkt being more "cryptic" or slightly more demanding concerning the usage, but the efficiency seems to be rather high.

**Comment by gpotter2** [comment]
Problem solved then.
