### ISSUE TITLE
vim syntax highlighting for *.uts files

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2075]
Hi, I've created a syntax highlighting of *.uts files for vim. I would like to share that. Is there a proper place in the Scapy repo for that?

[vim_uts_syntax.zip](https://github.com/secdev/scapy/files/3264840/vim_uts_syntax.zip)

**Comment by gpotter2** [comment]
This is really cool !

You can add it to `test/` for now.
I was planning to reorganize the tests (https://github.com/secdev/scapy/issues/1177), so it'll probably change soon anyway.

What would be awesome would be to add a `.sh` script to install the format in one go (copy the files to `~/.vim....`)

**Comment by guedou** [comment]
Cool idea!

I think that `test/syntax` or `doc/syntax/` are good location candidates. The files and a small doc to install them correctly are more than enough.
