### ISSUE TITLE
AttributeErrror: module 'os' has no attribute 'popen2' when using voip module

### ISSUE THREAD

**Issue by Charefdz1995** [secdev/scapy#2077]
Hello I have installed the last scapy version, I want to use the module voip but i has the issue 
AttributeErrror: module 'os' has no attribute 'popen2' when using voip_play function.

**Comment by p-l-** [comment]
Hi,

Thanks for your report. Could you try the fix proposed in #2078 and tell us if it works for you?

Thanks in advance,

Pierre

**Comment by Charefdz1995** [comment]
Hello, 
Thanks for the reply.
I have fixed with subprocess and get this error fron sox package . 
FileNotFoundError: [Errno 2] No such file or directory: 'sox -t .ul  - -t ossdsp /dev/dsp'
Regards

**Comment by p-l-** [comment]
Are you certain you have applied the exact patch from #2078?

**Comment by guedou** [comment]
I checked that the PR fixes the issue when sox is correctly installed. Please reopen if not.
