### ISSUE TITLE
TCP_client doesn't work with localhost

### ISSUE THREAD

**Issue by louisabraham** [secdev/scapy#2081]
Hi, I could make the example from https://bitbucket.org/secdev/scapy/wiki/doc/TCP work:

```python
s=TCP_client.tcplink(Raw, "www.test.com", 80)
s.send(b"GET /\r\n")
s.recv()
```

However, when I try to do it with ncat listening on my machine, it doesn't work:

`ncat -lk 1234`

```python
tcp = TCP_client.tcplink(Raw, "127.0.0.1", 1234)
tcp.send(b"hello")
```

I don't get any error but ncat doesn't show anything. I also tried with "localhost" and my local ip without success.
However, when I used the public address of my internet box with port forwarding, it worked.
Hence, it seems the problem is specific to localhost.

Note: `conf.L3socket` is `L3bpfSocket` and I'm on macOS.

**Comment by M4zD4i** [comment]
Ola, @louisabraham ! Not sure, but it seems that your problem might be related to loopback interface. This answer on SO helps me with similar issue: https://stackoverflow.com/a/41449990

**Comment by louisabraham** [comment]
Thank you for your answer. It might be the same issue. However, I'm not trying to sniff the packet, just to send it normally. I'm pretty sure this is a problem with the `L3socket`.

**Comment by gpotter2** [comment]
Did you try to pass an `iface=` argument to the socket ?

**Comment by guedou** [comment]
@louisabraham the loop-back interface behave differently from a regular interface, see https://scapy.readthedocs.io/en/latest/troubleshooting.html#i-can-t-ping-127-0-0-1-scapy-does-not-work-with-127-0-0-1-or-on-the-loopback-interface
