### ISSUE TITLE
Solaris support for send/recieve packet

### ISSUE THREAD

**Issue by xirs** [secdev/scapy#209]
Solaris is S11 now, and S12 will come soon. It has changed more since S10. for example,
1. 'netstat' 's output format when read_route
2. libdnet/libpcap support when send/recv message.
3. AF_PACKEt and PYTHON's AF_PACKET support when send/recv message
4. DLPI support
I update solaris.py under scapy/arch/, it is tested at Solaris S11 and S12, and also is tested at X86 and Sparc. hope it helpful.
[solaris.zip](https://github.com/secdev/scapy/files/349001/solaris.zip)

**Comment by guedou** [comment]
Closing the issue as the corresponding code is now discussed in PR #210
