### ISSUE TITLE
Apparently inconsistent behavior of Ether.src whith DHCP

### ISSUE THREAD

**Issue by zokrezyl** [secdev/scapy#2093]
Hi. I am on latest scapy and I noticed a strange behavior. (Consider the code below for DHCP discovery). If I have the interface configured previously (with dhclient) then the src ethernet address is set correctly. If the interface is not configured (ip) then 00:00:00:00:00 is set... Is that normal behavior? 

Thus, without iface configured I have the following output

> ###[ Ethernet ]### 
>   dst       = ff:ff:ff:ff:ff:ff
>   src       = 00:00:00:00:00:00
>   type      = IPv4
> ###[ IP ]### 
>      version   = 4
>      ihl       = None
>      tos       = 0x0
>      len       = None
>      id        = 1
>      flags     = 
>      frag      = 0
>      ttl       = 64
>      proto     = udp
> 

with iface configured
```

1 b'\x00\x0c)\xca=\xe0'
###[ Ethernet ]### 
  dst       = ff:ff:ff:ff:ff:ff
  src       = 00:0c:29:ca:3d:e0
  type      = IPv4
###[ IP ]### 
     version   = 4
     ihl       = None
     tos       = 0x0
     len       = None
     id        = 1
     flags     = 
     frag      = 0

```

```
from scapy.all import *

conf.checkIPaddr = False
conf.iface = "ethpy"
fam,hw = get_if_raw_hwaddr(conf.iface)
print(fam,hw)
#dhcp_discover = Ether(dst="ff:ff:ff:ff:ff:ff",src=hw)/\
dhcp_discover = Ether(dst="ff:ff:ff:ff:ff:ff")/\
        IP(src="0.0.0.0",dst="255.255.255.255")/\
        UDP(sport=68,dport=67)/\
        BOOTP(op=1, chaddr=hw, xid=0xDEADBEEF)/\
        DHCP(options=[
                ("message-type","discover"), 
                ("hostname", "vlan-3601"),
                "end", "pad"])

print(dhcp_discover.show())
ans, unans = srp(dhcp_discover)

print(ans.show())
print(unans.show())

```

**Comment by guedou** [comment]
When Scapy does not manage to retrieve the MAC address, for example when the interface is done, the MAC address will be set to 00:00:00:00:00:00

**Comment by zokrezyl** [comment]
Thanks. But if you have idea why the different behavior in the two cases, would be nice if you could share the info. I mean what is the heuristic used if the interface has an IP vs. when not.
