### ISSUE TITLE
Add Encrypted Server Name Indication for TLS 1.3 

### ISSUE THREAD

**Issue by mrsylerpowers** [secdev/scapy#2096]
As this Encrypted Server name is added to more and more browsers I believe it would be a good addition to add the ability to dissect tls packets with the with the client hello containing a [Encrypted SNI](https://datatracker.ietf.org/doc/draft-ietf-tls-esni/).

**Comment by gpotter2** [comment]
closed in https://github.com/secdev/scapy/pull/2396
