### ISSUE TITLE
Unused code in scapy/utils.py

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#2103]
codacy identified that the following block is never reached: https://github.com/secdev/scapy/blob/master/scapy/utils.py#L891

I think that the `raise` statement must be removed. @p-l- @gpotter2 what do you think?

**Comment by gpotter2** [comment]
Definetly. It's a 2-years old forgotten debug statement
https://github.com/secdev/scapy/commit/5e8857410015a93f6371459b2f870432ded39b9f#diff-fb7023a8077b5e1da2c3a462e59e0a89R728
