### ISSUE TITLE
Travis CI: sudo is deprecated

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#2112]
We missed it, but according to https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

> Over the next few weeks, we encourage everyone to remove any sudo: false configurations from your .travis.yml. Soon we will run all projects on the virtual-machine-based infrastructure, the sudo keyword will be fully deprecated.

**`sudo` is now always enabled on Travis CI builds.** This means that half of our tests are useless.

I am for removing them (or if we leave some non-sudo tests, let's only keep a single one). They aren't that useful and take a spot in the queue.

It would greatly reduce the time Travis tests take to pass.

**Comment by p-l-** [comment]
While I do understand it would be great to have Travis-CI run faster, I think non-sudo tests (the fact that Travis-CI allows it or not is not the most important; what matters is whether we run scapy with or without sudo) are important as they ensure we can still use Scapy without being root for parsing PCAP and dissecting packets, using TCP or UDP sockets, etc.

What do you think?

**Comment by guedou** [comment]
@p-l- is right. We need to keep the non-root tests. In the paste, Scapy did not work or broke while not run as root.

Concerning Travis, if will submit a PR to remove the `sudo: required` directive.

To make the test run faster, we could, for example, run `py27-linux_non_root` and `py27-linux_root` together but that will make the results harder to read..

**Comment by gpotter2** [comment]
Can we at least lower the amount of non root tests we run ?

For instance, in https://github.com/secdev/scapy/pull/2279 I've only kept a 2.7 and a 3.8 non-root test + the dependency-specific ones.
If it works on those two, knowing that we still test all the others with root, it shouldn't be possible to introduce a regression for non-root tests.

**Comment by guedou** [comment]
IMHO py27-linux_non_root, py27-linux_non_root_old-cryptography, py38-linux_non_root, pypy-linux_non_root & pypy3-linux_non_root must be kept for now.

We could remove (or merge in a single run): py34-linux_non_root, py35-linux_non_root, py36-linux_non_root, py37-linux_non_root.

If you feel like submitting a dedicated PR, could you also uncomment pypy3-linux_root ?
