### ISSUE TITLE
issue in getting length of PacketListField()

### ISSUE THREAD

**Issue by cq674350529** [secdev/scapy#2115]
#### Brief description

When calcing the length of `PacketLenField()` using `length_of()` in `FieldLenField()`, the returned size mismatched the actual size.  

Following is a simple demo.

``` python
import struct
from scapy.all import PacketListField, Packet, StrNullField, ByteField, FieldLenField, RandString, PacketField

class TestField(Packet):
    name = "test field"
    fields_desc = [
        StrNullField('data', 'test')
    ]

class TestPacket(Packet):
    name = "test packet"
    fields_desc = [
        ByteField('header', 1),
        FieldLenField('length', None, length_of="items", fmt="<H", adjust=lambda pkt,x:x),
        PacketListField("items", [], TestField, length_from=lambda p:p.length)
        # PacketField("items", None, TestField)
    ]

test_packet = TestPacket(items=[TestField(), TestField(data=RandString())])
# test_packet = TestPacket(items=TestField(data=RandString()))

build_packet = test_packet.build()

print("packet[len: %d]: %s" %  (len(build_packet), build_packet))

print("Calc length with packet: %d" % (len(build_packet) - 3))
print("Calc length from field: %d" % (struct.unpack("<H", build_packet[1:3])))
```

One of the output is as follows. As can be seen from the result, the value of 'length' field is wrong (even bigger than the total size of packet).

``` shell
$ python3.6 test_scapy.py 
packet[len: 31]: b'\x01\x60\x00test\x00BBmpu3vLg3Iyk8ZBGn6HRT\x00'
Calc length with packet: 28
Calc length from field: 96
```

By the way, I also tested it with `PacketField()`. And It seemed work well.

Did I misuse the `PacketListField()`? Thanks.

#### Environment

-   Scapy version: 2.4.3rc1.dev285 (updated with `pip` from git)
-   Python version: `3.6`
-   Operating System: `Ubuntu 16.04`

**Comment by guedou** [comment]
That is the expected behavior. The `data` field is set to a random string. A new random string will be created every time that the filed is manipulated. Here, it happens at least twice: while computing the packet length, and while setting the value.

You could do the following to ensure that the same random string is issued for all computations:
```
random_string = raw(RandString())
test_packet = TestPacket(items=[TestField(), TestField(data=random_string)]
```

**Comment by cq674350529** [comment]
@guedou Thanks. As you suggested, the length calced is correct due to the same random string. 

But in my case, I need to fuzz the `data` field with `RandString()`. If filled with `raw(RandString())`, the `data` field is always same.  Another way to do this is to calc length in the custom `post_build()`, which is what I have done.
