### ISSUE TITLE
Helper methods in new contrib layers

### ISSUE THREAD

**Issue by ldp77** [secdev/scapy#2118]
I'm working on several new layers in preparation for a pull request and I have a design question. For my implementation I need certain methods to manipulate several fields based on one argument, or access/change attributes from a PacketListField more elegantly than the typical `pkt[lyr].attr1.attr2...`. My question is, is it acceptable to have methods like these included in my pull request or is it preferred that new layers be as simple as possible?

**Comment by gpotter2** [comment]
It's hard to understand your implementation :/ A code snippet is usually way more explicit 😄

**Comment by ldp77** [comment]
Sorry about no snippet, I don't know that I have one that's both reasonably short and easy to follow. Given that contrib layers may implement private methods, I don't envision a problem there. I'm working on ONC-RPC v2, NFSv3, NFS Mount v3, NLMv4, and Portmapper. I don't see any of those in layer or contrib. Thanks for the quick reply btw!
