### ISSUE TITLE
AttributeError: 'str' object has no attribute 'do_build'

### ISSUE THREAD

**Issue by YanYingTan** [secdev/scapy#2121]
The issue I faced is I got the AttributeError: 'str' object has no attribute 'do_build' when trying to run python decodexorpayload.py p.pcap on the command prompt.

The environment I am using is Scapy 2.4.3rc1.dev282 with Python 2.7.14 on Kali Linux 64-bits VM.

In this photo, it is the command I use in Scapy to write a pcap file.
![Scapy](https://user-images.githubusercontent.com/33506637/60478694-f67e5980-9cb5-11e9-968f-4bf7f2b3af2d.png)

This is the python file I used to decode xor payload in the pcap.
![python file](https://user-images.githubusercontent.com/33506637/60478753-2af21580-9cb6-11e9-98ed-6932da8cb68f.png)

So when I run the command python decodexorpayload.py p.pcap, I got this error.
![error](https://user-images.githubusercontent.com/33506637/60478795-465d2080-9cb6-11e9-97a7-f120a9576e51.png)

**Comment by guedou** [comment]
Please keep in mind that this is not a forum. You should provide a minimal example in a text format that triggers an issue in Scapy code.
