### ISSUE TITLE
AttributeError: 'str' object has no attribute 'do_build'

### ISSUE THREAD

**Issue by YanYingTan** [secdev/scapy#2122]
The issue I faced is I got the AttributeError: 'str' object has no attribute 'do_build' when trying to run it. I had already installed Scapy but why it keeps showing me that Scapy is still not installed.

The environment I am using is Scapy 2.4.3rc1.dev282 with Python 2.7.14 on Kali Linux 64-bits VM.

**Comment by guedou** [comment]
Duplicate of #2121.
