### ISSUE TITLE
Mac OS Catalina

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#2134]
**From:** https://stackoverflow.com/q/56936549/5459467

> I'm trying to create a sniffer from the scapy module. I'm running Python 3.7 on macOS Catalina. Assuming that it's something with the macOS Catalina public beta version. I just wanna know what's causing the problem if so. I'm trying hard to understand why scapy throws an index out of bounds trace:
> 
> **main.py**
> 
> ```
> import scapy.all as scapy
> 
> p = scapy.sniff()
> 
> p.summary()
> Result:
> 
> Traceback (most recent call last):
>   File "/Users/tom/PycharmProjects/sniffer/main.py", line 2, in <module>
>     import scapy.all as scapy
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 33, in <module>
>     import scapy.route  # noqa: F401
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/route.py", line 194, in <module>
>     conf.route = Route()
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/route.py", line 27, in __init__
>     self.resync()
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/route.py", line 35, in resync
>     self.routes = read_routes()
>   File "/Users/tom/PycharmProjects/sniffer/venv/lib/python3.7/site-packages/scapy/arch/unix.py", line 82, in read_routes
>     netif = rt[4 + mtu_present + prio_present + refs_present + locked]
> IndexError: list index out of range
> ```

I'd guess it is indeed related to Catalina, but am no expert. @guedou Could you please have a look?

**Comment by guedou** [comment]
I cannot do much without the output of ‘netstat -rn’ =\

Catalina is currently in beta and will be released in September 2019.

**Comment by gpotter2** [comment]
I had a friend try it out, here's the output:
http://dpaste.com/3TE9W3T
It would be nice if 2.4.3 stayed stable after the Catalina release

**Comment by guedou** [comment]
Thanks! I was able to reproduce the issue.

**Comment by guedou** [comment]
A friend of mine does not have any issue with 10.14.5 (updated from 10.13). The `netstat` output is the same as before, i.e. the Flags and Refs column are there.

Did your friend made a fresh install? Does he use the same version?

**Comment by gpotter2** [comment]
He's on 10.15 (beta), in a fresh install.

**Comment by guedou** [comment]
Which version of 10.15?

**Comment by gpotter2** [comment]
I've updated my post a lot sorry, it's 10.15 19A471t

**Comment by guedou** [comment]
I got confused with version names and numbers...

The PR is correct.
