### ISSUE TITLE
sctp chunk data , data decode

### ISSUE THREAD

**Issue by anust** [secdev/scapy#2136]
I have scapy installed from https://github.com/secdev/scapy,  when I sniff my sctp packet and print using packet.show()
it shows data in  SCTPChunkData  in the format as "\x01\x00\x01\x01\x00\x00\x00n\x02\x10\x00\\\x00\x00\x00\x01\x00\x00\x00\x02\x03\x00\x00\x0b\t\x80\x03\x0e\x19\x0b\x12\x08\x00\x11\x04\x00\x00\" 
please tell me how to decode it using sctp.py from your repository?

**Comment by guedou** [comment]
Could you share the whole packet?

**Comment by anust** [comment]
###[ Ethernet ]### 
  dst       = 0a:02:02:02:02:02
  src       = 0a:01:01:01:01:01
  type      = IPv4
###[ IP ]### 
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 148
     id        = 4660
     flags     = 
     frag      = 0
     ttl       = 255
     proto     = sctp
     chksum    = 0x91ac
     src       = 100.10.10.10
     dst       = 100.20.20.20
     \options   \
###[ SCTP ]### 
        sport     = 2905
        dport     = 2905
        tag       = 0x0
        chksum    = 0xedc3ab6a
###[ SCTPChunkData ]### 
           type      = data
           reserved  = 0
           delay_sack= 0
           unordered = 0
           beginning = 1
           ending    = 1
           len       = 116
           tsn       = 0xfb
           stream_id = 0x0
           stream_seq= 0xfb
           proto_id  = Reserved
           data      = '\x01\x00\x01\x01\x00\x00\x00n\x02\x10\x00\\\x00\x00\x00\x01\x00\x00\x00\x02\x03\x00\x00\x0b\t\x80\x03\x0e\x19\x0b\x12\x08\x00\x11\x04\x00\x00\x00\x00\x00\x00\x0b\x12\x08\x00\x11\x04\x11\x11\x11\x11\x11\x11.b,H\x04\x00\x00\x00\xfbk\x1a(\x18\x06\x07\x00\x11\x86\x05\x01\x01\x01\xa0\r`\x0b\xa1\t\x06\x07\x04\x00\x00\x01\x00\x01\x02l\x08\xa1\x06\x02\x01\x01\x02\x01\xfb'

**Comment by gpotter2** [comment]
Please share the **raw data** if the packet.

**Comment by anust** [comment]
[10.pcap.tar.gz](https://github.com/secdev/scapy/files/3376832/10.pcap.tar.gz)
I have a pcap file for with sctp protocol, I am sniffing it using scapy python,

**def http_header(packet):
    if packet.haslayer(IP):
          packet.show()
sniff(iface='my_interface', prn=http_header)**

 and its output is  
###[ Ethernet ]###
dst = 0a:02:02:02:02:02
src = 0a:01:01:01:01:01
type = IPv4
###[ IP ]###
version = 4
ihl = 5
tos = 0x0
len = 148
id = 4660
flags =
frag = 0
ttl = 255
proto = sctp
chksum = 0x91ac
src = 100.10.10.10
dst = 100.20.20.20
\options 
###[ SCTP ]###
sport = 2905
dport = 2905
tag = 0x0
chksum = 0xedc3ab6a
###[ SCTPChunkData ]###
type = data
reserved = 0
delay_sack= 0
unordered = 0
beginning = 1
ending = 1
len = 116
tsn = 0xfb
stream_id = 0x0
stream_seq= 0xfb
proto_id = Reserved
data = '\x01\x00\x01\x01\x00\x00\x00n\x02\x10\x00\\x00\x00\x00\x01\x00\x00\x00\x02\x03\x00\x00\x0b\t\x80\x03\x0e\x19\x0b\x12\x08\x00\x11\x04\x00\x00\x00\x00\x00\x00\x0b\x12\x08\x00\x11\x04\x11\x11\x11\x11\x11\x11.b,H\x04\x00\x00\x00\xfbk\x1a(\x18\x06\x07\x00\x11\x86\x05\x01\x01\x01\xa0\r`\x0b\xa1\t\x06\x07\x04\x00\x00\x01\x00\x01\x02l\x08\xa1\x06\x02\x01\x01\x02\x01\xfb'

I want to get the data in decoded or at-least read able form.

**Comment by guedou** [comment]
It seems to work as expected. Which result are you expecting?

**Comment by anust** [comment]
I want to decode this 
data = '\x01\x00\x01\x01\x00\x00\x00n\x02\x10\x00\x00\x00\x00\x01\x00\x00\x00\x02\x03\x00\x00\x0b\t\x80\x03\x0e\x19\x0b\x12\x08\x00\x11\x04\x00\x00\x00\x00\x00\x00\x0b\x12\x08\x00\x11\x04\x11\x11\x11\x11\x11\x11.b,H\x04\x00\x00\x00\xfbk\x1a(\x18\x06\x07\x00\x11\x86\x05\x01\x01\x01\xa0\r`\x0b\xa1\t\x06\x07\x04\x00\x00\x01\x00\x01\x02l\x08\xa1\x06\x02\x01\x01\x02\x01\xfb'
so that its human readable.

**Comment by anust** [comment]
Is it utf-16 encoding? or utf with base64? I wan t to know the  packet structure of **data** of sctp chunk data

**Comment by gpotter2** [comment]
There is no support for MTP in scapy yet. That's your issue.
