### ISSUE TITLE
supersocket.py L3RawSocket module 'socket' has no attribute 'AF_PACKET'

### ISSUE THREAD

**Issue by shuguang101** [secdev/scapy#2148]
line 150: self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501

socket.AF_PACKET not supported MacOS
python3.7

**Comment by guedou** [comment]
Please fill the issue template, and reopen the issue.

**Comment by douniwan5788** [comment]
use `L3bpfSocket` on MacOS
