### ISSUE TITLE
Can I change tcp packets that got from arp spoof and re-send?

### ISSUE THREAD

**Issue by uemahra** [secdev/scapy#2150]
Hi, scapy is great! I'm using it recently. I'm wondering if I use arp spoof target and gateway's traffic, I can get a lot of tcp packets, if I use scapy to intercept packets matches my criteria con
dition, and change its layer 7 data a little, and re-send, is it possible?

**Comment by gpotter2** [comment]
Please fill the issue template.

But yeah, it looks possible
