### ISSUE TITLE
Can't send packet for all clients

### ISSUE THREAD

**Issue by SSL0** [secdev/scapy#2155]
I'm trying to send a package to everyone:

    send_packet = Ether(dst='FF:FF:FF:FF:FF:FF') / ARP(pdst='192.168.1.*')
    ans, nans = srp(send_packet, verbose=0, timeout=2)

But i get error:

    File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 222, in sndrcv
    p.sent_time = timessent[i]
    KeyError: 0

Python version: 3.7.3
Scapy version: 2.4.2

**Comment by gpotter2** [comment]
- please fill the issue template
- please retry against master branch
- please clarify who's "everyone"
