### ISSUE TITLE
Got error on send packet to all device in LAN

### ISSUE THREAD

**Issue by SSL0** [secdev/scapy#2156]
#### Brief description

>I try to send ARP packet to all subnet (in the range 192.168.1.1/255)

#### Environment

-   Scapy version: `2.4.2`
-   Python version: `3.7.3`
-   Operating System: `Debian`

#### How to reproduce
```
from scapy.all import *
send_packet = Ether(dst='FF:FF:FF:FF:FF:FF') / ARP(pdst='192.168.1.*')
ans, nans = srp(send_packet, verbose=0, timeout=2)

```
#### Actual result

>I get the error:

```

File "main.py", line 95, in <module>
    ARP_Scanner(0)	
  File "main.py", line 65, in ARP_Scanner
    ans, nans = srp(send_packet, verbose=0, timeout=2)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 500, in srp
    result = sndrcv(s, x, *args, **kargs)
  File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 222, in sndrcv
    p.sent_time = timessent[i]
KeyError: 0

```

**Comment by gpotter2** [comment]
We already fixed that issue.
Note that Scapy 2.4.4 doesn't exist. **Please try against the master branch !!!**

**Comment by SSL0** [comment]
Really, sorry for this, i just install this with pip

**Comment by SSL0** [comment]
Yes thank you, it's working, but I don't get a response( But if I send a packet to gateway personally, he do it.

**Comment by SSL0** [comment]
It works, but I do not get an answer to Python 3.7, but if I use Python 2.7, then everything works, could you please help me? (Sorry for the inconvenience)

**Comment by gpotter2** [comment]
I am no wizard :smile: Youmll need to give move information & context than just "it doesn't work".

The codebase *should* be fully Python 2 & 3 compliant.

Most likely, you are still using an old Scapy with Python 3.7. Please:
- download the master branch on GitHub
- `python3 setup.py install`

If you want to do the same for Python 2, use `python`

**Comment by SSL0** [comment]
> Most likely, you are still using an old Scapy with Python 3.7. Please:
> 
>     * download the master branch on GitHub
> 
>     * `python3 setup.py install`
> 
> 
> If you want to do the same for Python 2, use `python`.

Interesting, yesterday I download master branch from Github and install scapy only on Python3, right now I try to install this on Python2 and this is don't work. I enter the same code as before installing Scapy to Python2.

**Comment by gpotter2** [comment]
This is very likely not a Scapy issue, but one with your setup.

If you are certain this is a Scapy issue: **please give details. Don't just say "it doesn't work". Do you have an error ?**

**Comment by SSL0** [comment]
I did not fix the problem, but I found another way, I just created an array with all IP addresses and indicated it in pdst. (For those who have a similar problem)
