### ISSUE TITLE
ioctl error on Linux 5.2.1

### ISSUE THREAD

**Issue by akorb** [secdev/scapy#2167]
Recently, I updated to the kernel `5.2.1-1-MANJARO`.

Since then sockets throw an error. With `5.1.18-1-MANJARO` the error does not appear.

**Example 1:**
```python
load_layer('http')
req = HTTP()/HTTPRequest(
     Accept_Encoding=b'gzip, deflate', 
     Cache_Control=b'no-cache', 
     Connection=b'keep-alive', 
     Host=b'www.secdev.org', 
     Pragma=b'no-cache' 
     )
a = TCP_client.tcplink(HTTP, "www.secdev.org", 80)
scapy.arch.linux.get_last_packet_timestamp(a)
```

Output: ```OSError: [Errno 25] Inappropriate ioctl for device```

**Example 2:**
Scapy Instance 1:
```python
from scapy.contrib.automotive.obd.obd import *
from scapy.config import conf
conf.contribs['ISOTP'] = {'use-can-isotp-kernel-module': True}
from scapy.contrib.isotp import *
socket = ISOTPSocket('vcan0', sid=0x123, did=0x456, basecls=OBD)
socket.recv()
```

Scapy Instance 2
```python
from scapy.contrib.automotive.obd.obd import *
from scapy.config import conf
conf.contribs['ISOTP'] = {'use-can-isotp-kernel-module': True}
from scapy.contrib.isotp import *
socket = ISOTPSocket('vcan0', sid=0x456, did=0x123, basecls=OBD)
socket.send(OBD())
```

Output (Instance 2): ```OSError: [Errno 25] Inappropriate ioctl for device```

Call stack:
```
~/src/scapy/scapy/contrib/isotp.py in recv_raw(self, x)
   1598                 return None
   1599 
-> 1600             ts = get_last_packet_timestamp(self.can_socket)
   1601             return self.basecls, pkt, ts
   1602 

~/src/scapy/scapy/arch/linux.py in get_last_packet_timestamp(sock)
    386 if os.uname()[4] in ['x86_64', 'aarch64']:
    387     def get_last_packet_timestamp(sock):
--> 388         ts = ioctl(sock, SIOCGSTAMP, "1234567890123456")
    389         s, us = struct.unpack("QQ", ts)
    390         return s + us / 1000000.0
```

The problem seems to be the syscall of `ioctl` with `SIOCGSTAMP`.
But I cannot find a modification of this call in the changelog of Linux 5.2.1.

I doubt this problem is related to a change in scapy, but at least I wanted it to be mentioned and documented. With example code.

**Comment by gpotter2** [comment]
Thanks for the report.
It's probably either a bug or a deprecation we missed.

**Comment by akorb** [comment]
I just notied that while `Example 2` works again with the old Linux version `5.1.18-1-MANJARO`, `Example 1` does not.

Maybe the code isn't even correct in `Example 1`. I just tried to force a call to `get_last_packet_timestamp`

**Comment by gpotter2** [comment]
Correct.

Actually, `TCP_client.tcplink` is a SuperSocket that wraps an Automaton.
Therefore, the `.fileno()` returns the one from the Automaton pipes, rather than actual sockets.

This works:

```python

load_layer('http')
req = HTTP()/HTTPRequest(
     Accept_Encoding=b'gzip, deflate', 
     Cache_Control=b'no-cache', 
     Connection=b'keep-alive', 
     Host=b'www.secdev.org', 
     Pragma=b'no-cache' 
     )
a = TCP_client.tcplink(HTTP, "www.secdev.org", 80)
scapy.arch.linux.get_last_packet_timestamp(a.atmt.listen_sock) 
```

**Comment by akorb** [comment]
As expected, the problem was not caused by scapy. Turned out a commit in the Linux Kernel caused a problem in the ISOTP Kernel Module we are using.

It has been fixed some minutes ago.
See: https://github.com/hartkopp/can-isotp/issues/16

**Comment by gpotter2** [comment]
Great, glad you could figure it out.
