### ISSUE TITLE
scapy can't send packet in windows7/python2.7

### ISSUE THREAD

**Issue by virtowlee** [secdev/scapy#217]
Hello ,This's my first time to use scapy.And i saw a problem.
Windows7,and Python2.7.
my code is just sample:
data = "hello world "
a = IP(dst="129.132.2.21")/TCP()/data
send(a)

But it told my it's wrong.
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
     send(a)
   File "D:\Python27\lib\site-packages\scapy\sendrecv.py", line 267, in sendp
     return __gen_send(conf.L2socket(iface=iface, *args, **kargs), x, inter=inter, loop=loop, 
   count=count, verbose=verbose, 
   File "D:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 326, in __init__
     self.outs = dnet.eth(iface)
   File "dnet.pyx", line 112, in dnet.eth.__init__
   OSError: No error

PS:My computer use wireless network.

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this. Can you tell us which version of Scapy you are using? How did you install it?

**Comment by virtowlee** [comment]
Scapy 2.3.2   
I use  pip install Scapy

Thank you!

And i think this problem may be about Scapy with the wireless network?
When  i use ADSL network,it's fine.

**Comment by gpotter2** [comment]
Hi,
I used to have this strange error while using the default scapy version, but since i got the dev one it works perfectly. (even if there is a crash on start issue that i kinda fixed myself)

**Comment by guedou** [comment]
Thanks @gpotter2 !

**Comment by cswarnan** [comment]
Hi I am using scapy 2.3.3. When I am trying to send a packet to my own IP address I am getting error 
File "dnet.pyx", line 250, in dnet.eth.init

I am on wired connection. 
Please suggest.

**Comment by gpotter2** [comment]
Can you retry using the dev version ?
(download it from github, see the docs)

What OS are you using, what python version ?

**Comment by cswarnan** [comment]
@gpotter2 I have windows 7 with Python27.
I tried using latest code from github, but now getting:

Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix, NextHop
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], Comman 
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], Comman 
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Begin emission:
Finished to send 1 packets.
.......................................................................................................................................................

and it never stops. I need to stop execution.

**Comment by gpotter2** [comment]
This is VERY interessting !

It means that you are using an old/not supported version of Windows. Scapy should be supporting all, so that is a bug.

Could you create a new issue on github and tell us which windows version you are using, so we would be able to fix it ?

Thank you !

**Comment by cswarnan** [comment]
@gpotter2 - I created an issue #562 , Also will be creating one more ticket where I am facing issue with sending packets to multiple hosts from one source.
