### ISSUE TITLE
RawPcapReader next() incompatible with read_packet() in scapy/utils.py

### ISSUE THREAD

**Issue by pateldt** [secdev/scapy#2189]
The next() iterator method is not compatible with current implementation of read_packet().

read_packet() raises an EOFError when no more packets are available (previously None was returned).   This needs to be caught in next() and a StopIteration exception needs to be raised.

**Comment by gpotter2** [comment]
Hi & thanks a lot for the report.
This should be fixed in https://github.com/secdev/scapy/pull/2190
