### ISSUE TITLE
Empty Layer Dissection

### ISSUE THREAD

**Issue by Matheus-Garbelini** [secdev/scapy#2192]
Hello, I was trying to add more packet types to the current bluetooth low energy Layer and I ,can't find the solution of how to add empty layers (no fields). 
Explaining better I've stopped in the following simple situation:
```Python
from scapy.layers.bluetooth4LE import *
from scapy.utils import raw
from binascii import hexlify
# Create LL_START_ENC_REQ pkt
pkt = BTLE(access_addr=0x998876) / BTLE_DATA() / CtrlPDU() / LL_START_ENC_REQ()

print(pkt.summary())
print(hexlify(raw(pkt)))

# Decode the same packet
pkt = BTLE('76889900030105f33307'.decode('hex'))
print(pkt.summary())
print(hexlify(raw(pkt)))
```

However, this is my result:
```BASH
BTLE / BTLE_DATA / CtrlPDU / LL_START_ENC_REQ
76889900030105f33307
BTLE / BTLE_DATA / CtrlPDU
76889900030105f33307
```

There's nothing I can do because LL_START_ENC_REQ class has no fields (Per BLE standard):
```Python
class LL_START_ENC_REQ(Packet):
    name = 'LL_START_ENC_REQ'
```

Off course, the packet is build correctly because the bind layer is added. I've zipped my custom bluetooth layer so you can test by overwriting the original layer file (there's some fixes I've made, but its not complete for me to submit a PR).
**Also, there's a lot of other cases where an opcode defines a packet type which does not have fields, but the next layer name is there no matter what. Is it possible to get such layer added by modifying CtrlPDU layer? I tried to use "guess_payload_class", but it's not being called because the payload size is 0.***

Thanks

[bluetooth4LE.zip](https://github.com/secdev/scapy/files/3456387/bluetooth4LE.zip)

**Comment by Matheus-Garbelini** [comment]
Ok, so I've found the solution, I just copied the "do_dissect_payload" of the class Packet and added in the first `if s` the check against `None`:

```Python
    def do_dissect_payload(self, s):
        if s is not None:
            cls = self.guess_payload_class(s)
            try:
                p = cls(s, _internal=1, _underlayer=self)
            except KeyboardInterrupt:
                raise
            except Exception:
                if conf.debug_dissector:
                    if issubtype(cls, Packet):
                        log_runtime.error("%s dissector failed" % cls.__name__)
                    else:
                        log_runtime.error("%s.guess_payload_class() returned [%s]" % (self.__class__.__name__, repr(cls)))  # noqa: E501
                    if cls is not None:
                        raise
                p = conf.raw_layer(s, _internal=1, _underlayer=self)
            self.add_payload(p)
```

The reason why I found this important is because this would enable to detect any packet type in the comparison such as `if LL_LL_START_ENC_REQ in pkt:` without needing to check the same condition as declared on the bind layer. 

If this solution were to be applied in the Packet class, would this trigger unexpected behavior across Scapy?

**Comment by gpotter2** [comment]
This will probably break a lot of things.

The real way of doing that would be to do the 
`cls = self.guess_payload_class(s)`
before, then
`if s or not cls.fields_desc:`
...

However, I'm a little afraid that this will kill the performances :/

**Comment by Matheus-Garbelini** [comment]
Nice @gpotter2, so if we need a layer on scapy that contains some empty fields I can just override the do_dissect_payload with your suggestion.

However, this issue also occurs for the att protocol present in the layer bluetooth.py. Some devices can send an att read response with length 0, so you get a packet with only the layers before, even though the packet is a att read response as per opcode. 

I'm modifying scapy for my application as I need to detect precisely the layers in Bluetooth packet, however, I'm not sure if my patches could go to a PR then. Is it ok to add such behavior for only the layers that have this len=0 properties, or that would be a breaking change? I understand that would affect performance as you mentioned because a extra guess would be made for every packet of the patches layer.

Could a new keyword be added to bind layers to tell the dissector that such layer is expected to have 0 fields? Something like: bind_layers(x,y,allow_empty=True)

**Comment by guedou** [comment]
Could `post_dissection_done()` work for your use case?

For example:
```
from scapy.all import *

class Test(Packet):
    name = "Test"
    fields_desc = [ ByteField("type", 0) ]

    def dissection_done(self, pkt):
        if self.type == 1:
            self.add_payload(Test1())

class Test0(Packet):
    name = "Test 0"
    fields_desc = [ ByteField("type", 0) ]

class Test1(Packet):
    name = "Test 1"

bind_layers(Test, Test0, type=0)
bind_layers(Test, Test1, type=1)

Test(raw(Test())).show()
Test(raw(Test()/Test0())).show()
Test(raw(Test()/Test1())).show()
```

**Comment by Matheus-Garbelini** [comment]
@guedou that would work for sure. It would also facilitate the fix for scapy layers such as ATT which have this problem. Would the `dissection_done` overhead be ok to the base Packet class? I imagine that this would have to be called in its `do_dissect_payload` right?

**Comment by guedou** [comment]
It is already implemented =)

**Comment by Matheus-Garbelini** [comment]
Thanks @guedou I'll let you know with a PR when the patches are correctly applied in the dissection_done for ATT layer + BLE. Thank you very much as always.
