### ISSUE TITLE
Trouble with installing scapy

### ISSUE THREAD

**Issue by sidtechnical** [secdev/scapy#2196]
I am trying to install scapy as per the instructions given [here](https://scapy.readthedocs.io/en/latest/installation.html)

My system is as follows:
Ubuntu 18.04.2 LTS
Python 3.6.8

Both scapy[complete] and scapy[basic] options are showing me the following message. 

```
>> 
Collecting scapy[complete]
  Using cached https://files.pythonhosted.org/packages/4f/00/d4d12afbe08d448931dd3346ba6c8756ddcda66a3670a81b107d74adc2e0/scapy-2.4.3rc4.tar.gz
Collecting ipython (from scapy[complete])
  Using cached https://files.pythonhosted.org/packages/b0/88/d996ab8be22cea1eaa18baee3678a11265e18cf09974728d683c51102148/ipython-5.8.0-py2-none-any.whl
Collecting pyx (from scapy[complete])
  Using cached https://files.pythonhosted.org/packages/f7/25/59c136568c1b61ee087155c874fcd9f7196a943a6a5ee3429efeb30ea2a8/PyX-0.15.tar.gz
No files/directories in /tmp/pip-build-qjrYmH/pyx/pip-egg-info (from PKG-INFO))
```

**Comment by guedou** [comment]
Are you using `pip` or `pip3` ?

I tested with `pip3` and it works fine. The following command will give you a more detailed output `pip install --verbose scapy[complete]`

**Comment by guedou** [comment]
Please reopen if the issue persists.
