### ISSUE TITLE
Don't receive a response from sr1 function

### ISSUE THREAD

**Issue by jimmytsadiotis** [secdev/scapy#2199]
Hey,
I am trying to establish a 3-way handshake connection with all the device on my network. However, there is a device that does not respond to a SYN packet and my program is stuck. I am using Wireshark for inspection of packets, and nothing comes back. 
Is there any way that can overcome this issue? similar to a timeout parameter on sr() function.
Thanks.

**Comment by gpotter2** [comment]
This really depends on the code you are using. We can't do much without a code snippet.

Almost all networking related functions have a `timeout` parameter in Scapy. You can use that.

I'd advise to use the https://scapy.readthedocs.io/en/latest/layers/tcp.html#scapy-s-tcp-client-automaton, if you're not trying to do it yourself

**Comment by jimmytsadiotis** [comment]
Thanks for your reply.
I've create a syn packet like this:

> _pkt = sr1(IP(dst=destinationIP)/TCP(dport=destinationPort, flags='S', seq=sequenceNum, ack =acknowledgeNum))_

Then i am checking the responses with an if statement:
_

if pkt[TCP].flags == 18 #for SYNACK
   then do something
else:
    close connection

_

For all the devices of the network, the program works fine. However, there is one device that does not respond, but I don't care about it. All I want is to be able to capture somehow that there is no response from sr1 function and send a packet to the next device.
sr1() function does not have a timeout parameter. What i tried to do was something like:
_

> if pkt is None:
>    continue

_
But it does not work as well.

**Comment by gpotter2** [comment]
> sr1() function does not have a timeout parameter. 

That is certainly not true

**Comment by gpotter2** [comment]
Closing as unclear with recent informations.
