### ISSUE TITLE
Scapy doesn't work reliably (sniff)!!!

### ISSUE THREAD

**Issue by Veek** [secdev/scapy#220]
Guys this is incredibly annoying but Scapy doesn't work reliably - if at all: 
http://storage8.static.itmages.com/i/16/0715/h_1468547235_2559921_f5eca5aac6.png
http://storage2.static.itmages.com/i/16/0715/h_1468564015_1673852_090659a7ad.png

Just trying to sniff between my modem iface and my box.

**Comment by guedou** [comment]
Thanks for your interest in Scapy, and such a detailed and helpful description of your issue. It really helps improving the project, and providing you a detailed answer !

**Comment by Veek** [comment]
there are two snapshots of code, ping, and the lack of output - **are you suggesting that I magically create output to make your reading more interesting?**

**Comment by guedou** [comment]
Please accept my apologies. I used an OCR to extract the code and test it myself. However, I can't reproduce this issue as I got an error, see:

```
$ python myscapy.py 
  File "test.py", line 1
SyntaxError: Non-ASCII character '\xff' in file test.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

I should have done something wrong.

**Comment by Veek** [comment]
http://stackoverflow.com/questions/38370317/scapy-callback-no-output-with-pkt-show
http://pastebin.com/mvet98mV
#!/usr/bin/python

from scapy.all import TCP, IP, ICMP, sniff

def icmp_callback(pkt):
    pkt.show()

print 'start'
sniff(filter='icmp', iface='eth0', prn=lambda x: x.show())

**Comment by guedou** [comment]
I got the following error:
```
# python myscapy.py 
  File "myscapy.py", line 6
    pkt.show()
      ^
IndentationError: expected an indented block```
