### ISSUE TITLE
Is there easy way to decrypt https data

### ISSUE THREAD

**Issue by Prairial** [secdev/scapy#2201]
Like wireshark, which use `$SSLKEYLOGFILE` to decrypt on the fly. 
THX.

**Comment by guedou** [comment]
The TLS notebooks contain examples that show how to do that: https://github.com/secdev/scapy/tree/master/doc/notebooks/tls

**Comment by koxu1996** [comment]
I am looking for the same thing, but I am not sure where I should put _ClientRandom_ and _Secret_.
@guedou Notebook is not really helpful, could you elaborate a little more?

**Comment by muuuh** [comment]
@guedou Could you please provide a sample with SSLKEYLOGFILE?

**Comment by dewebdes** [comment]
why u close this issue?
if we have the certificate files of a domain, then we must can simply decrypt https application data from packets with scapy but nobody present a clear solution, in Notebook u just speak about hello message and ... that not useful.

I try to write a code but it fall in ERROR:
**value Error: ciphertext length must be equal to key size**

![Capture](https://user-images.githubusercontent.com/40831732/150693332-4659548c-5685-4684-848d-58084e0350e2.PNG)
