### ISSUE TITLE
How could I know the right response of each request?

### ISSUE THREAD

**Issue by rambler1002** [secdev/scapy#2208]
How could I know the right response of each request?
There are many of request and response packets sniffed with scapy2.4.3. But I want to get the right response packet of each http request, What can I do?

**Comment by gpotter2** [comment]
Hi,

What are you using to perform this sniff ? HTTP requests are nothing more than TCP payloads, therefore the requests should be matched using the various sequence numbers.

You should be able to use the `.answers()` method of a packet containing a `HTTPResponse` on a packet containing a `HTTPRequest` to see if they match.

**Comment by rambler1002** [comment]
Thank you! I tried it just now, in some case it works, but other case it isn't work right. That's, when response packet is split to translate, and I used the session=TCPSession of sniff() method. 
If I remove session=TCPSession, they can match, but only the first response packet matched.My code is:
class Sniffer(object):
    def __init__(self):
        load_layer("http")
        self.request_list = []
    
    def start_sniff(self):
        nif_name = 'Npcap Loopback Adapter'
        sniff(iface=nif_name, prn=self.packet_callback, count=0)
    
    def packet_callback(self, packet):
        if packet.haslayer(HTTPRequest):
            self.request_list.append(packet)
        elif packet.haslayer(HTTPResponse):
            for p in self.request_list:
                if packet.answers(p) == 1:
                    print(p[HTTPRequest])
                    print(packet[HTTPResponse])
                
            print('------------------------')

if __name__ == '__main__':
    sniffer = Sniffer()
    sniffer.start_sniff()

**Comment by rambler1002** [comment]
Thank you! I tried it just now, in some case it works, but other case it isn't work right. That's, when response packet is split to translate, and I used the session=TCPSession of sniff() method.
If I remove session=TCPSession, they can match, but only the first response packet matched.Here is my test code:

 
load_layer("http")
request_list = []

def packet_callback(packet):
    if packet.haslayer(HTTPRequest):
         request_list.append(packet)
    elif packet.haslayer(HTTPResponse):
        for p in request_list:
            if packet.answers(p) == 1:
                print(p[HTTPRequest])
                print(packet[HTTPResponse])

nif_name = 'Npcap Loopback Adapter'
sniff(iface=nif_name, prn=packet_callback, count=0, session=TCPSession)

**Comment by rambler1002** [comment]
I try it again and find one thing. If some httpresponse data is split to two packets or more, only the first packet has HTTPResponse layer(in other words, only the first packet's haslayer(HTTPResponse) returns True, the rest returns False). So I can't get the all response data with the former comment code.Is there good idea to resolve it?

**Comment by gpotter2** [comment]
When using the `TCPSession`, http responses are recompiled.
I'm not sure what you mean :/

**Comment by rambler1002** [comment]
Yeah, I know http responses were recompiled when using TCPSession. My question is, in this case I want to match the recompiled httpreponse and httprequest, how to do it?

**Comment by gpotter2** [comment]
The code you posted above seems quite reasonable to me :/

**Comment by ckristo** [comment]
> Thank you! I tried it just now, in some case it works, but other case it isn't work right. That's, when response packet is split to translate, and I used the session=TCPSession of sniff() method.
> If I remove session=TCPSession, they can match, but only the first response packet matched.Here is my test code:
> 
> ```python
> load_layer("http")
> request_list = []
> 
> def packet_callback(packet):
>    if packet.haslayer(HTTPRequest):
>         request_list.append(packet)
>    elif packet.haslayer(HTTPResponse):
>        for p in request_list:
>            if packet.answers(p) == 1:
>                print(p[HTTPRequest])
>                print(packet[HTTPResponse])
> 
> nif_name = 'Npcap Loopback Adapter'
> sniff(iface=nif_name, prn=packet_callback, count=0, session=TCPSession)
> ```

This somehow didn't work for me - it returned the same response for every request. Here is what worked for me:

```python
sessions = sniff(offline = pcap_file, filter = filter, session = TCPSession).sessions()

# get all HTTP requests first
http_requests = []
for session_key, packets in sessions.items():
    http_requests.extend([ p for p in packets if p.haslayer(HTTPRequest) ])

# find HTTP responses for HTTP requests
ret = []
for http_req in http_requests:
    session_key = f"TCP {http_req[IP].dst}:{http_req[TCP].dport} > {http_req[IP].src}:{http_req[TCP].sport}"
    http_resp = sessions[session_key].filter(lambda p: p.haslayer(HTTPResponse))[0]
    # http_req => http_resp
```
