### ISSUE TITLE
TCP with fuzz generates packets with too long options

### ISSUE THREAD

**Issue by tristan-ovh** [secdev/scapy#2209]
#### Brief description

When generating random TCP packets (```Ether()/IP()/fuzz(TCP())```), the packet might have too many TCP options, creating more than 40 bytes of options, which is not valid.
It causes issues when trying to generate the actual packet.

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.6.8`
-   Operating System: `CentOS 7`

#### How to reproduce

Use this script (test.py):
```python
from scapy.all import *

test = Ether()/IP()/fuzz(TCP())

for i in range(10000):
    bytes(test)
```

```bash
python3 test.py
```

#### Actual result

```
Traceback (most recent call last):
  File "../../test.py", line 6, in <module>
    bytes(test)
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 487, in __bytes__
    return self.build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 607, in build
    p = self.do_build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 592, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 579, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 592, in do_build
    pay = self.do_build_payload()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 579, in do_build_payload
    return self.payload.do_build()
  File "/usr/local/lib/python3.6/site-packages/scapy/packet.py", line 594, in do_build
    return self.post_build(pkt, pay)
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/inet.py", line 629, in post_build
    p = p[:12] + chb((dataofs << 4) | orb(p[12]) & 0x0f) + p[13:]
  File "/usr/local/lib/python3.6/site-packages/scapy/compat.py", line 70, in chb
    return struct.pack("!B", x)
struct.error: ubyte format requires 0 <= number <= 255
```

#### Expected result

No output as packets should be generated properly.

#### Digging up

The issue does not seem to exist in scapy 2.4.0.

I have checked the cause of the printed exception. The wrong value is the result of a computation based on the TCP options length, which is 44 bytes, more than the 40 specified for TCP.

**Comment by tristan-ovh** [comment]
Hi!
I edited my description because it incorrectly stated that the issue does not exist in Python 2. I believe it does. But it does not exist in scapy 2.4.0 (python 2 or 3).

**Comment by guedou** [comment]
Here is the commit that introduced this regression:
```
git bisect bad
b4ffb62a65e33927ca5e231bd4210cf8b0919dd3 is the first bad commit
commit b4ffb62a65e33927ca5e231bd4210cf8b0919dd3
Author: gpotter2 <gabriel@potter.fr>
Date:   Sat Nov 10 22:33:56 2018 +0100

    TCPOptions improvements

:040000 040000 f6738d9f7e94aa2d86e217308f953af7d99497fc 4f3d7ac2e512c0337590b3afd0090e50cb218f02 M	scapy
:040000 040000 6014a16e60cb2895ffb41ba895e34b71b537f392 43777454867a624680b0cd20c693e16ebcd11666 M	test
```

A shorter way to reproduce the issue:
```
from scapy.all import *

random.seed(733)
raw(Ether()/IP()/fuzz(TCP()))
```

**Comment by gpotter2** [comment]
If you have a look at https://github.com/secdev/scapy/commit/b4ffb62a65e33927ca5e231bd4210cf8b0919dd3, you'll see that it doesn't actually creates a regression, but rather allows the issue to happen.

The real issue is the computation of the TCP data offset that is missing some safety parenthesis. Should be fixed in https://github.com/secdev/scapy/pull/2212
