### ISSUE TITLE
how to parse http packet which transport not through 80 and 8080

### ISSUE THREAD

**Issue by JackYangzg** [secdev/scapy#2218]
I have many http packets not using 80 or 8080 to transport, when using scapy to parse, It all parse as TCP raw packets. how can I parse it as http.

**Comment by gpotter2** [comment]
You may bind a new port using
```
bind_layers(TCP, HTTP, sport=...)
bind_layers(TCP, HTTP, dport=...)
```

**Comment by JackYangzg** [comment]
> You may bind a new port using
> 
> ```
> bind_layers(TCP, HTTP, sport=...)
> bind_layers(TCP, HTTP, dport=...)
> ```
> 
> Or manually call `HTTP(...)` on the raw payload.

OK, Thanks
