### ISSUE TITLE
Unnecessary override of guess_payload_class in EAP layer

### ISSUE THREAD

**Issue by tgoettler** [secdev/scapy#2220]
Scapy version: 2.4.2

The guess_payload_class function in layers/eap.py -> class EAP is overwritten and always returns Padding. This means, that adding a custom layer in a separate program is not simply possible via bind_layers, and it is hard to debug why this does not work. We did a workaround by overriding the function again, but this should not be the case.

We do not see any reason, why Padding should be hardcoded, because the default "Raw" which is returned if no specific layer is defined, should suffice. The Commit in which this was changed, contains no information why this was added.

**Comment by gpotter2** [comment]
Hi and thanks for the report.

@p-l- could you please have a look ? It appears that you did this commit.

https://github.com/secdev/scapy/blob/a864193915adff0e00bb5a9bcd3f2ffd62f9e43d/scapy/layers/eap.py#L288-L290

**Comment by p-l-** [comment]
That's because `EAP` layer is not supposed to have any payload. So if it does, it can be considered as padding. This is useful when the EAP layer is used as a field (which is the case in the radius protocol implementation).

Does that create any issue?

**Comment by tgoettler** [comment]
Thanks for the reply, now it got clearer why the change was implemented. We see now, that in scapy every EAP type has its own implementation and only inherits from EAP. 

But this was not applicable in our case:
We implemented WPS, which als uses EAP as encapsulation. In the WPS messages, there are different WPS Elements used, and these Elements are also used in e.g. in Beacons, therefore it should be a reusable layer. It follows, that when adding a new layer to EAP, we need to guess the payload via bind_layers, which is no longer possible when Padding is returned hardcoded.

We understand the reasoning, and we also know how to work around this, therefore it does not present an issue, it might just be difficult to see for someone unexperienced in scapy why an additional layer does not work.

Would it be possible to return Padding only if no lower layer was bound?

**Comment by p-l-** [comment]
I don't think it would be possible. Could you show your current code so that we can find a solution?

**Comment by gpotter2** [comment]
Wouldn't it work to only set `default_payload_class` to return `Padding` ?

That way the default `guess_payload_class` would return Padding if no other bindings are met.

**Comment by tgoettler** [comment]
We tested shortly with your proposition, and it worked.

**Comment by guedou** [comment]
Closing the issue as it seems resolved.
