### ISSUE TITLE
[Errno 90] Message too long with sendp()

### ISSUE THREAD

**Issue by catshy** [secdev/scapy#2222]
When i use scapy(version:2.4.3) to send packet between two network interfaces,got the following error:

> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "test.py", line 13, in run
    self.pcap.loop(0, self.callback)
  File "pcap.pyx", line 426, in pcap.pcap.loop
  File "test.py", line 17, in callback
    sendp(pt, iface=self.iface2)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3.dev15-py2.7.egg/scapy/sendrecv.py", line 362, in sendp
    realtime=realtime, return_packets=return_packets)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3.dev15-py2.7.egg/scapy/sendrecv.py", line 291, in __gen_send
    s.send(p)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3.dev15-py2.7.egg/scapy/arch/linux.py", line 559, in send
    return SuperSocket.send(self, x)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3.dev15-py2.7.egg/scapy/supersocket.py", line 49, in send
    sent = self.outs.send(sx)
error: [Errno 90] Message too long

Env：
```
p@p:~/Documents/code$ uname -a
Linux p 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Here is demo code:
```
import pcap
from scapy.all import *
import threading
class test(threading.Thread):
    def __init__(self, iface, iface2, direct=1, promisc=True, to_ms=50.0, immediate=True):
        threading.Thread.__init__(self)
        self.iface=iface
        self.iface2=iface2
        self.pcap = pcap.pcap(name=iface, promisc=promisc, timeout_ms=to_ms, immediate=True)
        self.pcap.setdirection(direct)
    def run(self):
        self.pcap.loop(0, self.callback)
    def callback(self, timestamp, pkt, *args):
        pt=Ether(str(pkt))
        sendp(pt, iface=self.iface2)
thread1=test("enp0s5", "enp0s5")
thread1.start()
thread1.join()
#remember to make some traffic.
```

Please help take a look.

**Comment by guedou** [comment]
Please provide a shorter example that could helps use reproduce your issue.

**Comment by catshy** [comment]
Thanks for replay.
```
from scapy.all import *
import pcap
def callback(timestamp, pkt, *args):
    pt=Ether(str(pkt))
    sendp(pt, iface="enp0s5")
    sendp(pt, iface="enp0s5")
sniffer = pcap.pcap(name=None, promisc=True, immediate=True, timeout_ms=50)
sniffer.loop(0, callback)
```
 Have a try with this example, you can find the pcap-library  [here](https://github.com/pynetwork/pypcap).

**Comment by guedou** [comment]
Can you reproduce the issue with Scapy only? Could you provide an example of `pt`?

**Comment by catshy** [comment]
I use pcap-library( it is the python version of libpcap) to capture packets. 
In theory, any packet is ok. What I did was just to visit some website.

**Comment by guedou** [comment]
I can’t reproduce the issue. If you are not able to provide specific info, there is no way to help you.

**Comment by guedou** [comment]
Please reopen the issue if you manage to provide a simple reproducer.

**Comment by lukemeierj** [comment]
A simple repro with Python 3.6.4 and Scapy 2.4.3:

```
from scapy.all import *
pkt = Ether()/Raw('a'*10000)
sendp(pkt)
```
`OSError` looks like it might be a system configuration problem as described [on StackOverflow](https://stackoverflow.com/questions/33791995/python-ioerror-errno-90-message-too-long-passing-long-list-to-spi-function) and [Kernal.org](https://www.kernel.org/doc/Documentation/spi/spidev).  

> There's a limit on the number of bytes each I/O request can transfer
  to the SPI device.  It defaults to one page, but that can be changed
  using a module parameter.

However, when I run the following script:
```
for i in range(9000, 9100):
     pkt = Ether()/Raw("a"*i)
     try:
         sendp(pkt)
     except OSError:
         print(i)
         print(len(pkt))
         break
```

The errors begin when the `len(packet) == 9016` and `i == 9002`.  

My page size is `4096`, so there must be something else configuring this limit.

**Comment by kaashifchoudhury** [comment]
Could it be related to MTU of the interface and fragmentation?
The numbers 1515 and 9016 seem very close to standard MTU/Jumbo frame MTU sizes.

**Comment by NeffIsBack** [comment]
I am running into the same error. Scapy only crashes with a packet length > 1500 and only on layer 2 (`send` does work seamlessly while `sendp` crashes). 
Did anyone solve the problem? Can i specify fragmentation somehow?

**Comment by gpotter2** [comment]
Scapy is low level. If you want to fragment, use `fragment()`.
