### ISSUE TITLE
Is there have some special treatment?

### ISSUE THREAD

**Issue by rambler1002** [secdev/scapy#2226]
I use the packet's method `answers` to check if response packet is the request's response. I got result is 0, however, I printed the request and the response, they are matched.
In windows, I haven't find this problem, it just in linux(Centos7), with the same codes.
another thing, I find there are many of .answers method, such packet, tcp, ip, httpresponse.I want to know which is the best one to check response and request.thanks.

**Comment by gpotter2** [comment]
Hi, please make a proper question (in proper English :/ I can barely understand it), and fill up the template.

You should use the `.answers()` of the upperest layer, because it will go through each layer to check wether a packet is an answer (first IP, then TCP...)
