### ISSUE TITLE
Radius packet with multiple vendor specific attribute issue

### ISSUE THREAD

**Issue by pankajsheoran** [secdev/scapy#2229]
Scapy Version 2.4.3
Python 3.7.1
MacBook 10.14.6 

A radius packet have multiple RadiusAttr_Vendor_Specific attribute while accessing vendor specific attribute only first one is accessed.

```
for (pkt_data, pkt_metadata,) in RawPcapReader(file_name):
 ether_pkt = CookedLinux(pkt_data)
 ip_pkt = ether_pkt[IP]
 if ip_pkt.proto == 17:
  udp_pkt=ether_pkt[UDP]
  radius_pkt=udp_pkt[Radius]
  print (radius_pkt[RadiusAttr_Vendor_Specific])
```

the packet contains two vendor specific attributes. We cannot access second vendor specific attribute.

   |###[ Vendor-Specific ]### 
   |  type      = Vendor-Specific
   |  len       = 12
   |  vendor_id = 14179
   |  vendor_type= 1
   |  vendor_len= 6
   |  value     = '\x00\x00\x00-'

   |###[ Vendor-Specific ]### 
   |  type      = Vendor-Specific
   |  len       = 23
   |  vendor_id = 9
   |  vendor_type= 1
   |  vendor_len= 17
   |  value     = 'nas-update=true'

**Comment by gpotter2** [comment]
You can use `.iterpayloads()` to iterate through the sublayers.
See https://scapy.readthedocs.io/en/latest/api/scapy.packet.html#scapy.packet.Packet.iterpayloads

**Comment by pankajsheoran** [comment]
thanks that helped. I was hoping something like below:

packet[TCP].dport

One more question can I decrypt radius packets if I have radius key?  In wireshark we can do this by giving key under protocol>radius

**Comment by guedou** [comment]
@pankajsheoran this is not supported.

**Comment by alamgirqazi** [comment]
> Scapy Version 2.4.3
> Python 3.7.1
> MacBook 10.14.6
> 
> A radius packet have multiple RadiusAttr_Vendor_Specific attribute while accessing vendor specific attribute only first one is accessed.
> 
> ```
> for (pkt_data, pkt_metadata,) in RawPcapReader(file_name):
>  ether_pkt = CookedLinux(pkt_data)
>  ip_pkt = ether_pkt[IP]
>  if ip_pkt.proto == 17:
>   udp_pkt=ether_pkt[UDP]
>   radius_pkt=udp_pkt[Radius]
>   print (radius_pkt[RadiusAttr_Vendor_Specific])
> ```
> 
> the packet contains two vendor specific attributes. We cannot access second vendor specific attribute.
> 
> |###[ Vendor-Specific ]###
> | type = Vendor-Specific
> | len = 12
> | vendor_id = 14179
> | vendor_type= 1
> | vendor_len= 6
> | value = '\x00\x00\x00-'
> 
> |###[ Vendor-Specific ]###
> | type = Vendor-Specific
> | len = 23
> | vendor_id = 9
> | vendor_type= 1
> | vendor_len= 17
> | value = 'nas-update=true'

Hi, When I run the same code, I get the error ```IndexError: Layer [UDP] not found```

I'm using a pcap file and trying to access Radius packets which I can see clearly in wireshark. Any clue where I might be wrong ?

Also I'm using Python 2.7
