### ISSUE TITLE
Get_if_addr() Can't find IP addresses and masks from specific interfaces under Windows

### ISSUE THREAD

**Issue by DamienDaco** [secdev/scapy#2235]
Hi,

I'm really sorry to post this issue here, but Stackoverflow isn't helping and I can't find any solutions.

**Issue:** Can't extract IP / mask from specific, non default interfaces under Windows.

- Scapy version **2.4.3**
- Python version **3.7.4**
- Windows version **10 Pro**

I'm trying to extract the IP(v4) addresses and masks from all my interfaces under Windows 10.
(Goal is to write a gui app that lets the user select any ingress/egress interface to perform some Scapy tasks.)

When using **get_if_addr(conf.iface)**, it correctly displays my default IP like so:

>get_if_addr(conf.iface)
>192.168.1.100

However, it's impossible to do the same with other (non default) Windows interfaces.
For instance:
>get_if_addr('vEthernet (Default Switch)')
>AttributeError: 'str' object has no attribute 'ip'

I tried to search in **get_windows_if_list()**, but all the IPs (IPv4 + IPv6) are appended to a list , with a single key 'ips', that prevents me from easily extracting the IPv4 I'm looking for:

>get_windows_if_list()
>...... (Some output omitted).... ,** 'ips': ['fd00::41ce:4474:6d5e:273f', 'fd00::8d5e:5cf7:ac22:a8f7', 'fe80::41ce:4474:6d5e:273f', '192.168.1.100']**},

That list of ips has an unpredictable length, it may contain a variable number of IPv4/6, depending on the interface selected. Therefore it's hard to get the right value.
Also, there's no mention of the masks.

I also tried **get_if_list()** but that doesn't help either, as it outputs a list of strings:
> get_if_list()
['\\Device\\NPF_{F1E4D0EF-4C5F-4403-A7D9-4998FC78268F}', '\\Device\\NPF_{4F24A185-4939-4F72-8BD2-5D60259B1DAA}', '\\Device\\NPF_{826A32C0-E477-4343-BCD7-DBD8013685F4}', '\\Device\\NPF_{72F195BF-8C1E-4A96-B493-B5144E65F381}']

Thank you.

**Comment by gpotter2** [comment]
Try:
```
get_if_addr(IFACES.dev_from_name('vEthernet (Default Switch)'))
```
