### ISSUE TITLE
CAN SignalPacket and SignalField dont function

### ISSUE THREAD

**Issue by cameronstubber** [secdev/scapy#2252]
#### Brief description

A Custom Layer using SignalPacket and SignalField to implement a Multiplex frame (based on DBC) returns 0 for all field values, no matter what data values are set in the CAN Data field. It appears as if SignalPacket does not have any connection to the data field in the CAN Packet.

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7.4
-   Operating System: Windows 10 Enterprise 64

CAN Frames are being loaded from CSV for reconstruction.

#### How to reproduce

Define a DBC as a Custom Layer:
```
class MyPacket(SignalPacket) 
    fields_desc = [
        LEUnsignedSignalField("multiplexor", default=0, start=0, size=8),
        ConditionalField(LEUnsignedSignalField("sig1", default=0, start=8, size=1), lambda p: p.multiplexor == 0),
        ConditionalField(LEUnsignedSignalField("sig2", default=0, start=8, size=1), lambda p: p.multiplexor == 1)
    ]
```

Create 2 CAN Frames, with data values of

```
b'\x00\x00\x00\x00\x00\x00\x00\x00'
b'\x01\x00\x00\x00\x00\x00\x00\x00'
```

Construct the frame:

`myFrame = CAN(flags=theFlags, identifier=theIdentifier, length=theLength, data=theData)/MyPacket()`

#### Actual result

The value of `signalFrame.getfieldval("multiplexor")` is 0 in both cases.

In my real case, i have a dbc/multiplexor with about 20 values, but all values are 0 in all frames when the value of data is constantly changing between x00 and xff.

#### Expected result

The value of multiplexor from the second frame should be 1

**Comment by polybassa** [comment]
Hi, thanks for your request. 
The creation of your CAN-Frame is not correct.
It should be like this (if you use `CAN`)
```python
myFrame = CAN(flags=theFlags, identifier=theIdentifier, length=theLength, data=bytes(MyPacket(theData)))
```

or you define a CANHeader for your purpose:

```python
class CANHeader(CAN):
    """A minimal implementation of the CANopen protocol, based on
    Wireshark dissectors. See https://wiki.wireshark.org/CANopen
    """
    fields_desc = [
        FlagsField('flags', 0, 3, ['error',
                                   'remote_transmission_request',
                                   'extended']),
        XBitField('identifier', 0, 29),
        FieldLenField('length', None, length_of='data', fmt='B'),
        ThreeBytesField('reserved', 0)
    ]

bind_layers(CANHeader, MyPacket, identifier=0x123)
```

**Comment by polybassa** [comment]
#2253 should fix this

**Comment by polybassa** [comment]
Thanks for this issue.

**Comment by cameronstubber** [comment]
Appreciate the response @polybassa - Will give it a go and come back to you :)

**Comment by polybassa** [comment]
This issue can be closed
