### ISSUE TITLE
NetFlow v9 dissection interferes with raw bytes

### ISSUE THREAD

**Issue by bbayles** [secdev/scapy#2257]
The [attached capture](https://github.com/secdev/scapy/files/3632876/v9_options-template-padding.pcap.gz) displays some strange behavior under Scapy 2.4.3 (on Linux x86-64, presumably elsewhere also).

Scapy and Wireshark disagree about what the contents of the UDP portion of the packet are:

```
Scapy:     fb200807007840a10009000277efe9c450c843f900362202000000000001001801000004000800010000002a0004002900040101004477ef819077ef81900000003c00000001009300930ac900640ac9033b060009ee0b3500000ac9033b131302000000000000260bdc69aa6480996649a0000000000000
Wireshark: fb200807007840a10009000277efe9c450c843f900362202000000000001001801000004000800010000002a00040029000400000101004477ef819077ef81900000003c00000001009300930ac900640ac9033b060009ee0b3500000ac9033b131302000000000000260bdc69aa6480996649a000000000
```

Looking at the actual PCAP data with a hex editor supports the Wireshark interpretation.

Scapy seems to be dropping a `00 00` and tacking it on to the end. The missing pair of bytes are interpreted correctly in Wireshark as NetFlow padding bytes:

![image](https://user-images.githubusercontent.com/1922815/65275751-e70bf100-daeb-11e9-81e1-d6186f99979f.png)

This script shows the issue:
```python
from binascii import hexlify
from scapy.all import PcapReader

with PcapReader('v9_options-template-padding.pcap.gz') as reader:
    packet = next(reader)

hexlify(bytes(packet['UDP'])).decode()
```

Doing this (i.e., turning off the NetFlow dissector restores the correct behavior) mitigates the issue:

```python
split_layers(UDP, NetflowHeader, dport=2055)
split_layers(UDP, NetflowHeader, sport=2055)
```

So the problem is that the NetFlow dissector is interfering with how the earlier parts of the packet are represented.

**Comment by ir193** [comment]
I noticed the NetflowDataflowsetV9 is parsed as a payload of NetflowOptionsFlowsetV9, but actually it should be under NetflowHeaderV9 and in parallel to NetflowOptionsFlowsetV9. 
So I think it's a bug of scapy's netflow implementation

**Comment by ir193** [comment]
This is happening because NetflowDataflowsetV9 is binded as payload of NetflowDataflowsetV9. It should be like this:

```
Netflow Header
    NetflowOptionsFlowsetV9
      templates=[]
      padding zero
   NetflowDataflowsetV9
      datafields
```

But scapy parsed as:

```
Netflow Header
    NetflowOptionsFlowsetV9
      templates=[]
      NetflowDataflowsetV9
          datafields
      padding zero

```

**Comment by gpotter2** [comment]
Hi & sorry for the delay. Fixed in https://github.com/secdev/scapy/pull/2464
