### ISSUE TITLE
Console Application to view sniffed packets

### ISSUE THREAD

**Issue by AlexAshs** [secdev/scapy#2262]
### **Packet viewer, which provides a live view of sniffed packets, regardless of which layer.**

The tool will mainly work with urwid as a console UI library and blinker as a callback interface.
It will be refactored from the UI [mitmproxy](https://mitmproxy.org/) uses.

**Key features will be:** 
- a modular architecture, so there's a possibility to interchange the UI
- compatibility to all layers
- VIM-bindings to navigate the sniffed packets in a reasonable manner (scrolling, searching, ordering for specific keys, filtering)
- optional detail views, which offer functionality specific to a certain layer (replaying packets, editing the payload, etc.)
- a parser, which can save and load the captured session to pcap or similar files

The overall objective is, to have a tool which enables you to easily monitor and interact with network traffic in a live session, built into scapy

**My questions are:**

Do the maintainers @gpotter2 @guedou see a need for this tool in scapy?
And if so, do you have any thoughts/reservations/suggestions for me?

I am still in the research process of how this may be implemented, so I am open to and happy about suggestions! :)

**Comment by guedou** [comment]
Being able to interact with packets with an interface like `mitmproxy` sounds very interesting. Let us know when you have something ready to test or review. [Scapy pipes](https://scapy.readthedocs.io/en/latest/advanced_usage.html#pipetools) provide a way to manipulate packets that might interest you.

**Comment by AlexAshs** [comment]
Thank you for the hint.
It's great to hear, that there's a demand for such a tool!

So far my only update is, that I have been trying to refactor `mitmproxy` in a top down way, which prooved quite complicated and inefficient.

Now I will try a more straight forward bottum up approach, which will slowly incorporate features of mitmproxy, as I learn to understand, how it works.

Once I have the first prototype, I will post it here.

Just a small formal question: where would I place the code for the tool within the scapy file structure?

I suspect, at some point it will need to be a folder containing several files, in order to provide maintainability.

**Comment by guedou** [comment]
I think that the best option is to develop this interface outside of Scapy. That will simplify your project, and won't increase the complexity of Scapy source code.

**Comment by AlexAshs** [comment]
So would you say, I should make it an independent viewer, which uses scapy as a library, or would you suggest importing it in scapy, as soon as a certain point is reached in Development?

**Comment by guedou** [comment]
Yes, the independent viewer seems to be the best strategy to start with.

**Comment by AlexAshs** [comment]
@polybassa , you proposed, that this would be a part of the scapy project.
What are your thoughts on this?

**Comment by polybassa** [comment]
Whatever is easier for you.

**Comment by guedou** [comment]
Please do it separately at first.

**Comment by AlexAshs** [comment]
I am :)
