### ISSUE TITLE
Scapy make mistakes recognizing encryption in network_stats()

### ISSUE THREAD

**Issue by Diablloo** [secdev/scapy#2268]
**Description:**
It seems to happen due to incorrect `Dot11Elt` payload recognition. Bug often appears if network uses wps (says `WEP` when `WPA2/PSK` is used). Example packet is below.

nework_stats() output:
`{'ssid': 'ASUS', 'rates': [16, 68, 0, 1, 2, 16, 71, 0, 16, 40, 128, 40, 128, 40, 128, 24], 'channel': 12, 'country': 'FR', 'country_desc_type': None, 'crypto': {'WEP'}}`

Wireshark output:
![image](https://user-images.githubusercontent.com/42441602/66035483-e58eef80-e513-11e9-9664-fe8a749c840d.png)

**Environment**:
- scapy 2.4.3
- system Win10

[asus_wps_beacon.zip](https://github.com/secdev/scapy/files/3680498/asus_wps_beacon.zip)

**Comment by guedou** [comment]
What is the expected result for this packet?

This issue will be fixed by #2248.
