### ISSUE TITLE
Unable to Set Duration Field on Dot11 RTS Packet

### ISSUE THREAD

**Issue by taospartan** [secdev/scapy#2274]
When trying to send an RTS pkt with ID of timeval, this is not recieved in wireshark, it is always parsed as 0.

scapy-2.4.3.dev93
raspbian buster
Alfa AWUS051NH v2
python 3.7.3

```
conf.use_pcap = True
bytes = struct.pack("<H", 35595)
timeval = struct.unpack(">H", bytes)[0]
pkt = RadioTap() / Dot11(addr1=mac1, addr2=mac2, type=1, subtype=11, ID=timeval)
sendp(pkt, iface=monIface, verbose=0, count=pktCnt, monitor=True)
```

**Comment by guedou** [comment]
Scapy is correclty buidling the packet:
```
>>> Dot11(raw(Dot11(ID=struct.unpack(">H", struct.pack("<H", 35595))[0]))).ID
2955
```

This is more likely an issue with you wireless card driver.
