### ISSUE TITLE
packet not received

### ISSUE THREAD

**Issue by sh1va73** [secdev/scapy#2292]
I dont seem to receive packets i send with scapy.
This is the command I did : send(IP(src=“SOURCEIP”,dst=“DESTINATIONIP”)/ICMP()/“Hello world”)
The response is 1 packet send.
But its not received when I check with Wireshark.

**Comment by guedou** [comment]
Please use the template.

**Comment by sh1va73** [comment]
Yes, I tried that as well:

Welcome to Scapy (2.3.1)
>>> x = IP(ttl=64)
>>> x.src="SOURCEIP"
>>> x.dst="MYIP"
>>> send(x)
.
Sent 1 packets.
>>> send(x)

No result with Wireshark or tcpdump.
