### ISSUE TITLE
import sacpy.all  wrong  in windows 7 x64/python 2.7

### ISSUE THREAD

**Issue by a23764996** [secdev/scapy#231]
I do  import scapy.all, and cannot run next code always！

**Comment by p-l-** [comment]
Hi,

Can you add the code you cannot run and the error message?

**Comment by gpotter2** [comment]
I'm working with windows 7/10 x64, and i've never seen that...
```
C:\Users\gpotter>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import ARP
>>> ARP().show()
###[ ARP ]###
 ...........
```
So i guess it's your code's fault. You might also want to have a look at the [doc](http://www.secdev.org/projects/scapy/doc/) to learn how to use scapy.

**Comment by p-l-** [comment]
Feel free to re-open @a23764996 if needed. Closing based on @gpotter2 statement.
