### ISSUE TITLE
Broken sendp(realtime=True)

### ISSUE THREAD

**Issue by b-x** [secdev/scapy#2318]
`sendp(..., realtime=True)` is broken in scapy 2.4.3
It produces TypeError:

```
File "/usr/local/lib/python3.7/dist-packages/scapy/sendrecv.py", line 290, in __gen_send
    dt0 = ct - p.time
TypeError: unsupported operand type(s) for -: 'float' and 'decimal.Decimal'
```

The issue is introduced by this commit:
ebd4e26d - fix double precision for timestamp (4 months ago) <Sergey Platonov>

**Comment by p-l-** [comment]
Where do the packet you are trying come from? Did you read them from a PCAP file (which I suspect)?
