### ISSUE TITLE
on win32 -- AttributeError in open_pcap()

### ISSUE THREAD

**Issue by skewty** [secdev/scapy#2321]
#### Brief description

In Windows  with SCAPY 2.4.3

### `scapy/arch/windows/__init__.py`

```py
    def open_pcap(iface, *args, **kargs):
        """open_pcap: Windows routine for creating a pcap from an interface.
        This function is also responsible for detecting monitor mode.
        """
        iface_pcap_name = pcapname(iface)
        if not isinstance(iface, NetworkInterface) and \
           iface_pcap_name is not None:
            iface = IFACES.dev_from_name(iface)
        if iface.is_invalid():
            raise Scapy_Exception(
                "Interface is invalid (no pcap match found) !"
            )

def pcapname(dev):
    """Get the device pcap name by device name or Scapy NetworkInterface

    """
    if isinstance(dev, NetworkInterface):
        if dev.is_invalid():
            return None
        return dev.pcap_name
    try:
        return IFACES.dev_from_name(dev).pcap_name
    except ValueError:
        return IFACES.dev_from_pcapname(dev).pcap_name
```

When `iface` parameter is specified by `if_entry['name']` (from `get_windows_if_list()`) instead of `class NetworkInterface` and the interface name is valid but `pcapname()` returns `None` (because `IFACES.dev_from_name(dev)` worked but `.pcap_name` is `None`) then `if iface.is_invalid()` is called when iface is still just a `str` so `AttributeError` is raised.

**Comment by skewty** [comment]
Simply changing that line to: `if iface is None or iface.is_invalid()` would fix the issue reported above.
Would you like me to do a PR?

FYI I re-installed npcap software and `IFACES.dev_from_name(dev).pcap_name` is no longer returning `None`.

**Comment by gpotter2** [comment]
Hi and sorry for the late reply.

> Would you like me to do a PR?

That would be greatly appreciated, thanks
