### ISSUE TITLE
why import module long time?

### ISSUE THREAD

**Issue by pirxon** [secdev/scapy#2327]
#### Environment
-   Scapy version: `scapy 2.4.3.dev161`
-   Python version: `3.5.2`
-   Operating System: `Ubuntu 16.04.6 LTS`

(venv) user@ubuntu:~/venv/c_arping$ time /home/user/venv/bin/python3 -c 'from scapy.layers.l2 import arping'                                                
real    0m5.380s
user    0m1.596s
sys     0m5.312s

**Comment by guedou** [comment]
What does the following do?
```
git clone https://github.com/secdev/scapy_test --depth 1
cd scapy_test
time python3 -m scapy
```

**Comment by pirxon** [comment]
(venv) pirx@bras3:~/venv/scapy/test$ time python3 -m scapy
                                      
                     aSPY//YASa       
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version 2.4.3.dev161
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | Craft me if you can.
       scccccp///pSP///p          p//Y   |                   -- IPv6 layer
      sY/////////y  caa           S//P   |
       cayCyayP//Ya              pY/Ya
        sY/PsY////YCc          aC//Yp 
         sc  sccaCY//PCypaapyCP//YSs  
                  spCPY//////YPSps    
                       ccaacs         
                                       using IPython 7.9.0
>>>                                                                                                                                                                            

real    0m14.144s
user    0m9.228s
sys     0m5.636s

**Comment by pirxon** [comment]
first I tried as you wrote.
maybe you made a mistake in the name of the repository?

~/venv$ git clone https://github.com/secdev/scapy_test --depth 1
Cloning into 'scapy_test'...
Username for 'https://github.com': pirxon  
Password for 'https://pirxon@github.com': 
remote: Repository not found.

**Comment by guedou** [comment]
can you share the output of `ip route` and `ip link` ?

**Comment by pirxon** [comment]
~/venv$ ip link | wc -l    
12168
~/venv$ ip route | wc -l     
2157

**Comment by guedou** [comment]
That is likely the reason why loading is slow on your system: Scapy parses all routes and all interfaces

**Comment by pirxon** [comment]
I suspected. Thanks you. Best regards
