### ISSUE TITLE
Sniff not capturing IPv6 Packets

### ISSUE THREAD

**Issue by Menahra** [secdev/scapy#2328]
### Brief description

Scapy's sniff() function does not recognize ipv6 packets.

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.5
-   Operating System: Debian 9

Simple network. Three machines, one acting as a client, one as a router (with firewall which is currently accepting everything), one as a server.

#### How to reproduce

On the server machine I am setting up a scapy command line sniff() and on the client machine I send an Echo Request via

`sr(IPv6(dst="xx:xx:xx::x")/ICMPv6EchoRequest())`

which terminates in scapy, but when I check the results of the sniff() I do not see any IPv6 packet.
When I try the same via IPv4 it works 

`sr(IP(dst="x.x.x.x")/ICMP())`

I tested the same with scapy versions 2.4.2 and 2.4.1 and 2.4.0 and found out that 2.4.0 was the
only of these versions that captured this IPv6 packet.

**Comment by guedou** [comment]
Are you injecting and sniffing on the same network interface? Scapy IPv6 support works perfectly fine on my Debian.

**Comment by Menahra** [comment]
I do not specify an interface, because I thought without specifying, scapy sniffs on all interfaces. 
Is that assumption incorrect?

**Comment by guedou** [comment]
Scapy sniffs on `conf.iface` by default. That will explain your issue
if IPv6 is not avaible on ` conf.iface`.

**Comment by Menahra** [comment]
I tested the output of conf in both scapy versions, and get for conf.iface the following outputs

    - in scapy 2.4.0:
            `iface      = eno1   iface6     = enp4s0f0`

     - in scapy 2.4.3:
            `iface      = eno1   iface6     = enp4s0f0`

where 'eno1' is the interface device for IPv4 and 'enp4s0f0' is the device for IPv6 on both machines (they have same name).

**Comment by guedou** [comment]
`sniff()` never listened on all interfaces. In your setup, you will need to call `sniff(iface="enp4s0f0")` to get IPv6 packets.
