### ISSUE TITLE
-OO flag TypeError

### ISSUE THREAD

**Issue by MVCionOld** [secdev/scapy#2331]
https://github.com/secdev/scapy/blob/0712f1efcf6d33ec83bb41488cfdf036bcf5b7b0/scapy/sendrecv.py#L558

Change
```python
 sr_func.__doc__ += _DOC_SNDRCV_PARAMS
```
to
```python
 sr_func.__doc__ = __str__(sr_func.__doc__) + _DOC_SNDRCV_PARAMS
```

**Comment by gpotter2** [comment]
Thanks for the report. fixed in https://github.com/secdev/scapy/pull/2334
