### ISSUE TITLE
Scapy write to file (python)

### ISSUE THREAD

**Issue by jlKampos** [secdev/scapy#2337]
Hello everyone.

I have this problem. At work i have a pcap file with data stored in arrays, every frame has an array with 10 entrys each.
The ideia is to loop trough all the frames create a copy of the packeth, change this array values and export the changed packets to a pcap file.
I can easly change the values, and dump the pkt.show() out put to a txt file.
The txt file shows all entries changed, but the exportedc pcap file, only shows 2 entries of the array changed all the rest is with the default values.

Has any one else had this problem ? or similar ??

i have built the changed packets like: pkt = pkt.build()

**Comment by guedou** [comment]
This is not a forum but a bug tracker.

Please ask your question on https://gitter.im/secdev/scapy instead.
