### ISSUE TITLE
Scapy doesn't recognize SOME/IP-SD layer

### ISSUE THREAD

**Issue by kruemelbacke** [secdev/scapy#2343]
#### Environment

-   Scapy version: v2.4.3.dev31
-   Python version: 3.6.4
-   Operating System: Windows 10 64bit

#### How to reproduce
```
from scapy.all import *
load_contrib("automotive.someip_sd")

ea = SDEntry_Service()
ea.tpe = 0
ea.srv_id = 0x1234
ea.inst_id = 0x5678
ea.ttl = 3

sd = SD()
sd.set_entryArray(ea)
some = sd.get_someip(True)

print("original packet:")
some.show()

some_raw = SOMEIP(some.build())

print("rebuilt packet:")
some_raw.show()
```

#### Actual result

```
original packet:
###[ SOME/IP ]### 
  \msg_id    \
   |###[ MessageId ]### 
   |  srv_id    = 65535
   |  sub_id    = EVENT_ID
   |  event_id  = 256
  len       = None
  \req_id    \
   |###[ RequestId ]### 
   |  client_id = 0
   |  session_id= 0
  proto_ver = 1
  iface_ver = 1
  msg_type  = NOTIFICATION
  retcode   = E_OK
###[ SD ]### 
     flags     = 0
     res       = 0x0
     len_entry_array= None
     \entry_array\
      |###[ Service Entry ]### 
      |  type      = 0
      |  index_1   = 0
      |  index_2   = 0
      |  n_opt_1   = 0
      |  n_opt_2   = 0
      |  srv_id    = 4660
      |  inst_id   = 22136
      |  major_ver = 0
      |  ttl       = 0x3
      |  minor_ver = 0
     len_option_array= None
     \option_array\

rebuilt packet:
###[ SOME/IP ]### 
  \msg_id    \
   |###[ MessageId ]### 
   |  srv_id    = 65535
   |  sub_id    = EVENT_ID
   |  event_id  = 256
  len       = 36
  \req_id    \
   |###[ RequestId ]### 
   |  client_id = 0
   |  session_id= 0
  proto_ver = 1
  iface_ver = 1
  msg_type  = NOTIFICATION
  retcode   = E_OK
###[ Raw ]### 
     load      = '\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x124Vx\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00'

```

#### Expected result

Scapy should recognize the SD layer, but instead there is only a Raw layer given. I understand, that there is no simple bind, because of the fieldclasses, but there should be another possibility to bind the SOMEIP and the SD layer. 

#### Related resources

Autostar writes in the official protocol docs:

> [PRS_SOMEIPSD_00151]dService Discovery messages shall use the Service-ID (16Bits) of 0xFFFF

> [PRS_SOMEIPSD_00152]dService Discovery messages shall use the Method-ID (16Bits) of 0x8100

> [PRS_SOMEIPSD_00154]dService Discovery messages shall have a Client-ID (16Bits) set to  0x0000, since there exists only a single SOME/IP-SD instance.

This could be used to recognize a SD Layer.

**Comment by baarse** [comment]
Thanks for the issue, seems like a legit error.
Do you want to provide a pull request?

**Comment by kruemelbacke** [comment]
I will provide one if a solution was found

**Comment by polybassa** [comment]
You probably have to modify the `post_build` function in the `SOMEIP` class

**Comment by kruemelbacke** [comment]
It's not about the building. The packet is built correctly and wireshark captures it properly. The problem is, that the SD Layer is not binded to the SOME/IP Layer. The solution is not that easy, because a bind like the following doesn't work.

`bind_layers(SOMEIP, SD, msg_id.srv_id = 0xffff)`

The problem is the SOME/IP's fields which define the SD Layer are not simple fields, but a field class.

**Comment by polybassa** [comment]
Hi, thanks for your reply. This is the same, we observed. A solution would be a custom implementation of ‘guess_payload’. Sorry for my point to ‘post_build’. I did a similar thing on ISOTP: https://github.com/secdev/scapy/blob/d31378c886be2b831f80d29df4b5974c2921bf42/scapy/contrib/isotp.py#L211

Hope this example helps you for your PR.

**Comment by kruemelbacke** [comment]
Unfortunately no, but thank you for your answer. The field that defines if there is a SD Layer is not in the payload itself, but in the SOMEIP Layer. The problem here is, that the `guess_payload_class` only gets the payload as param and not the needed SOMEIP Layer. Any further idea how to bind the layers?
´´´
###[ SOME/IP ]###
  \msg_id\
   |###[ MessageId ]###
   |  srv_id= 0xFFFF <==========
   |  sub_id= METHOD_ID                  These fields define if there's a SD Layer or not (or event_id)
   |  method_id= 0x8100 <=======
...
´´´

**Comment by polybassa** [comment]
Hi, I might be wrong, but shouldn't it be possible to use `self` in `guess_payload_class`. `self` should be the `SOMEIP` packet, which then should allow you to ask for `self.msg_id.srv_id`.

**Comment by kruemelbacke** [comment]
Oh well, that's brilliant! Thank you, I will test it
