### ISSUE TITLE
contrib/cdp.py CDPMsgIPPrefix class has wrong format

### ISSUE THREAD

**Issue by y0ny0ns0n** [secdev/scapy#2344]
#### Brief description

[CDPMsgIPPrefix class](https://github.com/secdev/scapy/blob/2be23d9/scapy/contrib/cdp.py#L236) has following fields
```python
class CDPMsgIPPrefix(CDPMsgGeneric):
    name = "IP Prefix"
    type = 0x0007
    fields_desc = [XShortEnumField("type", 0x0007, _cdp_tlv_types),
                   ShortField("len", 8),
                   IPField("defaultgw", "192.168.0.1")]
```
But in real CDP(Cisco Discovery Protocol) packet, IP Prefixes has A.B.C.D/netmask format
```
IP Prefix: 20.0.0.0/24
14 00 00 00 18
```
quoted from [wireshark](https://github.com/wireshark/wireshark/blob/e206eb2/epan/dissectors/packet-cdp.c#L471)

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `2.7.13`
-   Operating System: `Windows 10 64bit Pro`

#### Actual result
![image](https://user-images.githubusercontent.com/47174372/69647196-66014500-10ac-11ea-9439-34171829bf67.png)
![image](https://user-images.githubusercontent.com/47174372/69647289-8df0a880-10ac-11ea-9d29-2b704afe90c7.png)

#### Related resources

[test.pcap.zip](https://github.com/secdev/scapy/files/3892593/test.pcap.zip)

**Comment by y0ny0ns0n** [comment]
![image](https://user-images.githubusercontent.com/47174372/69650836-892ef300-10b2-11ea-99e7-033443593e60.png)
I edit it for immediate use.

**Comment by guedou** [comment]
Thanks for your detailed description. Can you check is PR #2361 ?
