### ISSUE TITLE
StreamSocket issue with SSL-wrapped sockets

### ISSUE THREAD

**Issue by X-Cli** [secdev/scapy#235]
My understanding is that a Scapy StreamSocket can be used to receive "packets" instead of bytes from a TCP socket. The "wrapping" occurs by providing the "base" socket to the **init** of StreamSocket, like this:

```
import socket
import scapy.supersocket
import scapy.packet
import scapy.fields
import struct

class TestPacket(scapy.packet.Packet):
  name = 'Test Packet'
  fields_desc = [ scapy.fields.IntField('value', 0) ]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1', 1234))
ss = scapy.supersocket.StreamSocket(s, basecls=TestPacket)
try:
  assert isinstance(ss.recv(), TestPacket), "Never displayed"
except struct.error:
  pass #Segment does not contain a full TestPacket
```

StreamSocket peeks into the kernel buffers, parses the peeked data, computes the extraneous byte count and unloads from the kernel buffer only the bytes that were actually used to produce the packet to be returned.

This strategy ensures that a recv() call always return data that is the begining of a new packet, wherever this recv() call is performed. This even allows complex construction such as:
1. swapping the basecls between two calls of recv(), 
2. sharing of a single "base" socket between multiple StreamSocket

Unfortunately, this approach does not work when using SSLContext-wrapped sockets. Indeed, SSLContext-wrapped socket expose a "recv" API, which is supposedly compatible with the recv() API of a socket.socket object (duck typing !). This compatibility is not complete, however, and SSLContext-wrapped socket cannot use any recv() flags, including the socket.MSG_PEEK flag that is used in StreamSocket.recv.

```
import socket
import scapy.supersocket
import scapy.packet
import scapy.fields
import struct
import ssl

class TestPacket(scapy.packet.Packet):
  name = 'Test Packet'
  fields_desc = [ scapy.fields.IntField('value', 0) ]

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(('127.0.0.1', 1234))
ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
sslsock = ctx.wrap_socket(s)
ss = scapy.supersocket.StreamSocket(sslsock, basecls=TestPacket)
try:
  ss.recv()
  assert False, "Never displayed"
except:
  assert True, "Never displayed"
  raise
```

This code displays:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fmaury/scapy/scapy/supersocket.py", line 122, in recv
    pkt = self.ins.recv(x, socket.MSG_PEEK)
  File "/usr/lib/python2.7/ssl.py", line 751, in recv
    self.__class__)
ValueError: non-zero flags not allowed in calls to recv() on <class 'ssl.SSLSocket'>
```

An obvious fix would be to never peek into the kernel buffer and instead to handle a StreamSocket internal buffer. This would however mean that the StreamSocket **init** would require transfer of the ownership of the socket (meaning the "base" socket is no longer supposed to be recv()ed from "outside" of the StreamSocket instance). This would require also some tricks so that a segment containing multiple packets would not perform a blocking recv() call while the buffer contains enough bytes to generate a new basecls packet.
Put another way, this change would still permit usage 1) but would require to break compatibility with usage 2) from the previous list.

What is your take on this? 
Should StreamSocket be modified, breaking compatibility with some maybe negligible existing usages? 
Should I send a pull request with a new SteamSocket subclass ("SSLStreamSocket" or "ExclusiveStreamSocket" or something similar), whose code would be very similar to StreamSocket, but using an internal buffer instead of the peek trick?

Thanks.
Cheers,
Florian

**Comment by gpotter2** [comment]
@X-Cli Hey !
Is there anything that still needs to be done in this issue ?

**Comment by gpotter2** [comment]
@X-Cli Thanks
