### ISSUE TITLE
OBDScanner Unit Tests need refactoring

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2351]
All OBDScanner unit tests weren't executed for a long time through the silent change to XENIAL runners on travis. 

This is a reminder to refactor the following unit tests:
https://github.com/secdev/scapy/blob/master/test/tools/obdscanner.uts
https://github.com/secdev/scapy/blob/master/test/contrib/automotive/obd/scanner.uts

**Comment by polybassa** [comment]
@akorb @TabeaSpahn

**Comment by TabeaSpahn** [comment]
Will have a look at this :)
