### ISSUE TITLE
The Linux cooked capture.

### ISSUE THREAD

**Issue by alporkx** [secdev/scapy#2354]
Hello,

I am not sure that it is correct place for this question.
However I try to use scapy for generating packet which has "Linux cooked capture".

The  "Linux cooked capture"contains:
Packet type: Sent by us (4)
Link-layer address type: 1
Link-layer address length: 6
Source: HewlettP_a1:44:88 (6c:3b:e5:a1:44:88)
Unused: 0000
Protocol: IPv4 (0x0800)

Could you please suggest me module scapy, I need to use for sending it?

Thanks for any suggestion.

**Comment by gpotter2** [comment]
See https://scapy.readthedocs.io/en/latest/api/scapy.layers.l2.html#scapy.layers.l2.CookedLinux
For the packet format, and
https://scapy.readthedocs.io/en/latest/usage.html#sending-packets
To send them
