### ISSUE TITLE
Interface routing issue with `send` on layer 3

### ISSUE THREAD

**Issue by Elder-Wu** [secdev/scapy#2355]
I setup my UDP server by python code below.
```python
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.bind(('192.168.8.104', 9999))

print('Bind UDP on 9999...')

while True:
    data, addr = s.recvfrom(1024)
    print('Received from %s ---> %s' % (addr, data.decode("utf-8")))
```
and then,I try to send UPD package by scapy.
```python
send(IP(src="192.168.8.110",dst="192.168.8.104")/UDP(dport=9999,sport=5678)/"Hello scapy udp")
```
result is `Sent 1 packets.in terminal`.But I can't see anything in my udp server logout.

and then,I try to use another way to send UPD package like this:
```python
sr1(IP(src="192.168.8.110",dst="192.168.8.104")/UDP(dport=9999,sport=5678)/"Hello scapy udp")
```
IT WORKED(I mean that i can see logout in my UDP server)!!!WHY?????Can somebody answer for me.

**I asked this question on StackOverflow.com but nobody answer for me.So,if you see this,please help me.Thank you for your waste time watch this.**

**Comment by guedou** [comment]
This is likely a bug. Can you test PR #2356?

**Comment by Elder-Wu** [comment]
Thanks for your help!!!but now,I dont know how to test your RP.I've never make github issues before.So sorry about that.Can you tell me how to test your pr code?

**Comment by guedou** [comment]
```
git clone https://github.com/guedou/scapy-issues.git
cd scapy-issues
git checkout -b guedou-issue_#2355 master
git pull https://github.com/guedou/scapy-issues.git issue_#2355
sudo ./run_scapy
```

**Comment by Elder-Wu** [comment]
Great!!!I run your PR code successfully!And the bug seems to be fixed.
