### ISSUE TITLE
error: can't copy 'doc\scapy.1': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by NetherXiaoYu** [secdev/scapy#2368]
C:\Users\kitro\AppData\Local\Programs\Python\Python37>python C:\Users\kitro\Desktop\scapy-master\setup.py install
C:\Users\kitro\AppData\Local\Programs\Python\Python37\lib\site-packages\setuptools\dist.py:484: UserWarning: The version specified ('git-archive.dev3ad5b80a34') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing scapy.egg-info\PKG-INFO
writing dependency_links to scapy.egg-info\dependency_links.txt
writing entry points to scapy.egg-info\entry_points.txt
writing requirements to scapy.egg-info\requires.txt
writing top-level names to scapy.egg-info\top_level.txt
reading manifest file 'scapy.egg-info\SOURCES.txt'
writing manifest file 'scapy.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
warning: install_lib: 'build\lib' does not exist -- no Python modules to install

installing package data to build\bdist.win-amd64\egg
running install_data
error: can't copy 'doc\scapy.1': doesn't exist or not a regular file

**Comment by guedou** [comment]
Please use the issue template.
