### ISSUE TITLE
sniff function does not catch the association response after sending association request

### ISSUE THREAD

**Issue by Kubika77** [secdev/scapy#2369]
Scapy sniff is not able to capture association response message after sending association request.
(both actions, sending and sniffing being done in parallel using multiprocessing).

I can see the association response messages on a different opened sniffer, but somehow the sniff operation does not catch them.

sniff command is:
"pkts = sniff(iface=self.mon_ifc, lfilter=lambda x: x.haslayer(Dot11AssoResp),
               stop_filter=self.check_assoc,
               timeout=10)"

Both Processes (1.send association request/ 2.receive association response) are being handled by:
"
        jobs = list()
        result_queue = multiprocessing.Queue()
        receive_process = multiprocessing.Process(
            target=self.mon_ifc.search_assoc_resp,
            args=(result_queue,))
        jobs.append(receive_process)
        time.sleep(1)
        
        send_process = multiprocessing.Process(
            target=self.mon_ifc.send_packet,
            args=(packet, "AssoReq", ))
        jobs.append(send_process)

       for job in jobs:
           job.start()
        for job in jobs:
            job.join()
"

Association request is being sent by:
"sendp(packet, iface=self.mon_ifc)"

Interface is a WiFi dongle connected to PC.

My direction was that maybe Dongle is not fast enough to send and immediately receive the response.

Or maybe I did not do the multiprocessing in an idle way.

**Comment by guedou** [comment]
Please use the issue template.
