### ISSUE TITLE
dot11 key handshake message3

### ISSUE THREAD

**Issue by AnnabellBrocker** [secdev/scapy#2370]
When using PMF, there will be the 4 way handshake authentication in order to connect a client to an access point

Every of the four messages is a Dot11QoS package, but I am not able to rebuild one of the messages separately from the other ones. When sending an authentication package, the 4 way handshake is automatically generated, but I want to spearately resend message 3. thereofre I need to build my own message 3 package of the 4 way handshake

Does anyone has any ideas how to create your own message3 package?

**Comment by guedou** [comment]
Please use the issue template, and keep in mind that this is not a forum. Please use gitter to ask questions.
