### ISSUE TITLE
Add can_xcp-scanner for finding open ports on CAN Bus

### ISSUE THREAD

**Issue by Ita1pu** [secdev/scapy#2372]
Since XCP is widely used in automotive environment I am currently working on a scanner for open Ports on CAN bus.

It works pretty much like the [isotpscanner](https://github.com/secdev/scapy/blob/master/scapy/tools/automotive/isotpscanner.py) 

By sending a connect message on a defined area of CAN Ids and listening for responses the open ports are detected.

I will make a PR as soon as the scanner is finished.

**Comment by guedou** [comment]
No associated PR. Feel free to re-open.
