### ISSUE TITLE
Remove references to crypto_valid_advanced?

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#2398]
Since support for cryptography < 2.0 tests were removed in #2260, should we remove references to `crypto_valid_advanced` at these locations?
```
$ git grep crypto_valid_advanced
scapy/config.py:    crypto_valid_advanced = isCryptographyAdvanced()
scapy/layers/tls/automaton_cli.py:            if conf.crypto_valid_advanced:
scapy/layers/tls/automaton_cli.py:                            if conf.crypto_valid_advanced:
scapy/layers/tls/automaton_cli.py:        if conf.crypto_valid_advanced:
scapy/layers/tls/crypto/cipher_aead.py:if conf.crypto_valid_advanced:
scapy/layers/tls/crypto/cipher_aead.py:        # if conf.crypto_valid_advanced:
scapy/layers/tls/crypto/cipher_aead.py:if conf.crypto_valid_advanced:
scapy/layers/tls/crypto/cipher_aead.py:            if (conf.crypto_valid_advanced and
scapy/layers/tls/crypto/cipher_aead.py:                if (conf.crypto_valid_advanced and
scapy/layers/tls/crypto/cipher_aead.py:                    if (conf.crypto_valid_advanced and
scapy/layers/tls/crypto/cipher_aead.py:if conf.crypto_valid_advanced:
scapy/layers/tls/crypto/cipher_aead.py:        # if conf.crypto_valid_advanced:
scapy/layers/tls/crypto/cipher_aead.py:if conf.crypto_valid_advanced:
scapy/layers/tls/keyexchange_tls13.py:if conf.crypto_valid_advanced:
scapy/layers/tls/keyexchange_tls13.py:                if conf.crypto_valid_advanced:
scapy/layers/tls/keyexchange_tls13.py:                if conf.crypto_valid_advanced:
scapy/layers/tls/record.py:if conf.crypto_valid_advanced:
scapy/layers/tls/record.py:            if (conf.crypto_valid_advanced and
```

**Comment by gpotter2** [comment]
`crypto_valid_advanced` is about X25519 support. Doesn't it require a certain OpenSSL version or something ?

**Comment by guedou** [comment]
You are right. It is mostly used for X25519. In `cipher_aead.py, and `tls_record.py` it is also used to import AESCM and ChaCha20Poly1305. I will check if these algorithms need a specific suppor in OpenSSL or are implemented in Python.

**Comment by guedou** [comment]
I seems that `cryptography` supports OpenSSL >= 1.01 (from https://cryptography.io/en/latest/hazmat/backends/openssl/). This version supports AES CCM and ChaCha20Poly1305 (https://www.openssl.org/docs/man1.1.0/man1/ciphers.html).

**Comment by guedou** [comment]
It might be better to change `crypto_valid_advanced` to something more explicit and related to the algorithms. Another alternative is to use `openssl_version_text()` (https://cryptography.io/en/latest/hazmat/backends/openssl/#openssl_version_text) to decide which algorithms can be used.
