### ISSUE TITLE
global name 'wrpcap' is not defined

### ISSUE THREAD

**Issue by purplex88** [secdev/scapy#2402]
While trying to use sendpfast function, I get an error: global name 'wrpcap' is not defined

I am using:

-   Scapy version: 2.4.3
-   Python version: 2.7 (Requirement)
-   Operating System: Ubuntu LTS

Here's my small code:

```
from scapy.all import *
sendpfast(Ether()/IP(src="192.168.1.103",dst="127.0.0.1")/UDP(sport=80, dport=4040)/"Hello", pps=1000, iface="eth0")
```

Here's the result:

> Traceback (most recent call last):
>   File "/media/sf_Test/ScapyTest.py", line 15, in <module>
>     sendpfast(Ether()/IP(src="192.168.1.103",dst="127.0.0.1")/UDP(sport=80, dport=4040)/"Hello", pps=1000, iface="eth0")
>   File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 289, in sendpfast
>     wrpcap(f, x)
> NameError: global name 'wrpcap' is not defined
> 

I have tcpdump and tcpreplay installed already.

**Comment by guedou** [comment]
I cannot reproduce the issue on v2.4.3 and master. It seems that you are not using v2.4.3 as there is no call to wrpcap() at line 289:
```
git grep -n wrpcap scapy/sendrecv.py
scapy/sendrecv.py:24:from scapy.utils import get_temp_file, tcpdump, wrpcap, \
scapy/sendrecv.py:408:    wrpcap(f, x)
scapy/sendrecv.py:857:                    wrpcap(filename, offline)
```
