### ISSUE TITLE
Is there any documentation on how to construct a Netflow v9 packet?

### ISSUE THREAD

**Issue by sidney-pham** [secdev/scapy#2412]
Hi, hopefully this is the right place to ask this question!

(Please bear with me, I'm new to scapy.)

I'm trying to build a Netflow v9 packet with my own flow data in order to export it to a collector, but I can't exactly find any documentation on how I can use scapy to do so. I'm currently just reading the [Netflow v9 docs](https://www.cisco.com/en/US/technologies/tk648/tk362/technologies_white_paper09186a00800a3db9.html) to guess which of the layers in [scapy.layers.netflow](https://scapy.readthedocs.io/en/latest/api/scapy.layers.netflow.html) might be applicable, but my attempt isn't working.

Here's my attempt so far, in case I'm really close:
```python

    data = IP(dst=COLELCTOR_IP) / UDP(dport=COLLECTOR_PORT)

    header = netflow.NetflowHeaderV9(unixSecs=A_TIMESTAMP)

    template = netflow.NetflowTemplateV9(
        templateID=256,
        template_fields=[
            netflow.NetflowTemplateFieldV9(fieldType=1),  # IN_BYTES
            netflow.NetflowTemplateFieldV9(fieldType=2),  # IN_PKTS
            netflow.NetflowTemplateFieldV9(fieldType=4),  # PROTOCOL
            netflow.NetflowTemplateFieldV9(fieldType=8),  # IPV4_SRC_ADDR
            netflow.NetflowTemplateFieldV9(fieldType=12),  # IPV4_DST_ADDR
        ],
    )
    templateFS = netflow.NetflowFlowsetV9(templates=[template])

    dataFS = netflow.NetflowDataflowsetV9(
        templateID=256,
        records=[ # Some random data.
            netflow.NetflowRecordV9(fieldValue=12),
            netflow.NetflowRecordV9(fieldValue=42),
            netflow.NetflowRecordV9(fieldValue=6),
            netflow.NetflowRecordV9(fieldValue="192.168.0.10"),
            netflow.NetflowRecordV9(fieldValue="192.168.0.11"),
        ],
    )

    data /= header / templateFS / dataFS

    send(data)
```

I'm just struggling to use this netflow layer, and would appreciate any advice on how to be self-sufficient.

Thanks! 😺

**Comment by sidney-pham** [comment]
I'd also add the "question" label if I could, but I can't. Apologies! 😄

**Comment by guedou** [comment]
Sorry, we won't be able to help you more than pointing you to the following unit test: https://github.com/secdev/scapy/blob/master/test/regression.uts#L6706

**Comment by gpotter2** [comment]
It wouldn't hurt to have an example though.
I'll add that to the doc when I get the time

**Comment by gpotter2** [comment]
@sidney-pham You're almost there, you're just missing a `NetflowHeader()`. 😄 

It should be 

```python
header = netflow.NetflowHeader()/netflow.NetflowHeaderV9(unixSecs=A_TIMESTAMP)
```

**Comment by sidney-pham** [comment]
Thanks all, the example code really helped. I have one question. In the example:
```python
     # Let's first build the template. Those need an ID > 255
     flowset = NetflowFlowsetV9(
         templates=[NetflowTemplateV9(
             template_fields=[
                 NetflowTemplateFieldV9(fieldType=1, fieldLength=1),  # IN_BYTES
                 NetflowTemplateFieldV9(fieldType=2, fieldLength=4),  # IN_PKTS
                 NetflowTemplateFieldV9(fieldType=4),  # PROTOCOL
                 NetflowTemplateFieldV9(fieldType=8),  # IPV4_SRC_ADDR
                 NetflowTemplateFieldV9(fieldType=12),  # IPV4_DST_ADDR
             ],
             templateID=256,
             fieldCount=5)
         ],
         flowSetID=0
     )
     # Let's generate the record class. This will be a Packet class
     # In case you provided several templates in ghe flowset, you will need
     # to pass the template ID as second parameter
     recordClass = GetNetflowRecordV9(flowset)
     # Now lets build the data records
     dataFS = NetflowDataflowsetV9(
         templateID=256,
         records=[ # Some random data.
             recordClass(
                 IN_BYTES=b"\x12",
                 IN_PKTS=b"\0\0\0\0",
                 PROTOCOL=6,
                 IPV4_SRC_ADDR="192.168.0.10",
                 IPV4_DST_ADDR="192.168.0.11"
             ),
             recordClass(
                 IN_BYTES=b"\x0c",
                 IN_PKTS=b"\1\1\1\1",
                 PROTOCOL=3,
                 IPV4_SRC_ADDR="172.0.0.10",
                 IPV4_DST_ADDR="172.0.0.11"
             )
         ],
     )
```
I noticed that `fieldLength` is explicitly set for `IN_BYTES` and `IN_PKTS` — is there a specific reason why this is the case?

**Comment by gpotter2** [comment]
The spec allows you to change the default values if you want. If not specified, Scapy will "guess" the default but in some cases there are none.
I'd say it's safer to always specify it

**Comment by sidney-pham** [comment]
Gotcha. Silly question — is there any reason why we do `IN_BYTES=b"\x0c"` instead of `IN_BYTES=12`?

**Comment by gpotter2** [comment]
The fields StrFields by default so they expect bytes.
