### ISSUE TITLE
Regarding error when executing replay pcap python script using scapy

### ISSUE THREAD

**Issue by santikris2003** [secdev/scapy#2417]
#### Brief description
I have the following python script importing scapy , when I execute this script getting the following error , I have attached the traffic_gen1.py script , Im using Kali Linux Rolling Release 2019.4 , my pcaps Trafficset1.pcap has TLS1.2 traffic

root@kali:~# python  traffic_gen1.py 
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
.
Sent 1 packets.
Traceback (most recent call last):
  File "traffic_gen1.py", line 43, in <module>
    send_packet(pkt_reader, src_ip, dst_ip, count)
  File "traffic_gen1.py", line 17, in send_packet
    new_pkt[IP].dst = dst_ip
  File "/usr/lib/python2.7/dist-packages/scapy/packet.py", line 1171, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [IP] not found

#### Environment

-   Scapy version: 2.4
-   Python version: 2.7
-   Operating System: Kali Linux Rolling 2019.4

#### How to reproduce

Executing python traffic_gen1.py and getting the above error

#### Actual result

Getting above error

#### Expected result

python script traffic_gen1.py should replay the Trafficset1.pcap without generating above error
#### Related resources

Attaching the screenshot and traffic_gen1.py 
[screenshot_and_script_attached.zip](https://github.com/secdev/scapy/files/4077145/screenshot_and_script_attached.zip)

python script of error displayed when executing the traffic_gen1.py

**Comment by gpotter2** [comment]
The issue is in your code as the error shows. Please note that isn't a forum but a bug tracker
