### ISSUE TITLE
OSError("Cannot find libpcap.so library")

### ISSUE THREAD

**Issue by mengelsen** [secdev/scapy#2421]
#### Brief description
I am receiving an error ("OSError: Cannot find libpcap.so library.") after running the following command:
sniff(prn=arp_display, filter="arp", store=0, count=0)

#### Environment
-   Scapy version: v2.4.3
-   Python version: 2.7.16
-   Operating System: Raspbian GNU/Linux 10

> Further information:
I am trying to reproduce a behavior that another person documented here:
[Amazon Dash Button to control Philips Hue lights](http://joshprewitt.com/2016/03/24/using-an-amazon-dash-button-to-control-philips-hue-lights/)
Search for the key phrase "_put it all together_" on this blog post.

#### How to reproduce
Run the following python script. The **last line** is where I'm running into issues.
```
#!/usr/bin/env python
from scapy.all import *
import requests,json

bridgeIP = "10.13.0.10"                    #IP Address of your Bridge
user = "UserID_Hash_Here"    #Username you generated
dashMac = "68:37:E9:34:47:B0"                #MAC address of your Dash button
lightID = "2"                                #ID of the light you want to control

def toggle(lightID):
 url = "http://"+bridgeIP+"/api/"+user+"/lights/"+lightID
 r = requests.get(url)
 data = json.loads(r.text)
 if data["state"]["on"] == False:
  r = requests.put(url+"/state",json.dumps({'on':True}))
 elif data["state"]["on"] == True:
  r = requests.put(url+"/state",json.dumps({'on':False}))

def arp_display(pkt):
 if pkt[ARP].op == 1:
  if pkt[ARP].psrc == '0.0.0.0':
   if pkt[ARP].hwsrc == dashMac:
    toggle(lightID)

print (sniff(prn=arp_display, filter="arp", store=0, count=0))
```

#### Result
```
Traceback (most recent call last):
  File "toggle.py", line 26, in <module>
    print (sniff(prn=arp_display, filter="arp", store=0, count=0))
  File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.dev90c8d82070-py2.7.egg/scapy/sendrecv.py", line 1036, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.dev90c8d82070-py2.7.egg/scapy/sendrecv.py", line 904, in _run
    *arg, **karg)] = iface
  File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.dev90c8d82070-py2.7.egg/scapy/arch/linux.py", line 452, in __init__
    attach_filter(self.ins, filter, iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.dev90c8d82070-py2.7.egg/scapy/arch/linux.py", line 139, in attach_filter
    bp = compile_filter(bpf_filter, iface)
  File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.dev90c8d82070-py2.7.egg/scapy/arch/common.py", line 78, in compile_filter
    from scapy.libs.winpcapy import (
  File "/usr/local/lib/python2.7/dist-packages/scapy-git_archive.dev90c8d82070-py2.7.egg/scapy/libs/winpcapy.py", line 47, in <module>
    raise OSError("Cannot find libpcap.so library")
OSError: Cannot find libpcap.so library
```
#### Expected result
The script is designed to use the "sniff" command to identify when an Amazon Dash button sends-out an ARP request & attempts to pull an IP address (which occurs when the IoT device powers on).
If this event occurs the toggle() function is called which used the Philips API to turn ON/OFF a Philips Hue bulb.

#### Related resources
I can send any supplemental resources that you require.

**Comment by wataash** [comment]
```
apt search libpcap
sudo apt install libpcap0.8  # or another version found in above
```

might solve the problem.

**Comment by mengelsen** [comment]
> `sudo apt-get install tcpdump` (written in [manual](https://scapy.readthedocs.io/en/latest/installation.html#platform-specific-instructions)) might solve the problem.

That worked! I am now able to run the python script (error-free).

I just needed to install libpcap0.8 and libpcap0.8-dev.
`$ sudo apt install libpcap0.8-dev`

However I now believe that there is something wrong with my sniff() function.

When I turn on my "Dash Button" the network sniffer should intercept the ARP packet (containing the MAC address of the Dash button). When this happens my toggle() function should be called.

However, when I cancel the python script, this is the output that I get:
```
pi@raspberrypi:~/Documents/PhilipsHUE $ sudo python togglev2.py 
^C<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
```

Any thoughts or ideas on what might be going wrong?

(Wireshark recognizes the ARP packet & DHCP request.)

**Comment by gpotter2** [comment]
Make sure you're sniffing on the good interface using `iface="eth0"` (...)

> OSError: Cannot find libpcap.so library

I thought this was pretty explicit TBH

**Comment by mengelsen** [comment]
This Raspberry Pi 3 only has 1 network interface.

```
pi@raspberrypi:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.13.0.7  netmask 255.255.255.128  broadcast 10.13.0.127
        inet6 fe80::3879:715c:e2d1:8b59  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:b3:8b:98  txqueuelen 1000  (Ethernet)
        RX packets 73747  bytes 44515454 (42.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 38672  bytes 8880796 (8.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 9  bytes 524 (524.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 524 (524.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Where do I need to identify the network interface? Should it be within the sniff() function?

**Comment by gpotter2** [comment]
See https://scapy.readthedocs.io/en/latest/api/scapy.sendrecv.html

**Comment by mengelsen** [comment]
Thanks! I just reviewed the section of the article that focuses on the "scapy.sendrecv.sniff()" function.
https://scapy.readthedocs.io/en/latest/api/scapy.sendrecv.html#scapy.sendrecv.sniff

I was added the iface parameter, to filter the results. 
`sniff(iface="eth0", prn=arp_display, filter="arp", store=0, count=0)`

However the output that I receive (after stopping the script) has not changed.
`<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>`

**Comment by mengelsen** [comment]
Is there anything wrong with my arp_display function?

```
**def arp_display(pkt):**
 if pkt[ARP].op == 1:
  if pkt[ARP].psrc == '0.0.0.0':
   if pkt[ARP].hwsrc == 00:1B:44:11:3A:B7:
    toggle(lightID)

print (sniff(iface="eth0", **prn=arp_display**, filter="arp", store=0, count=0))
```

**Comment by gpotter2** [comment]
Please note that this is a bug tracker and not a forum. Please ask further questions on our gitter or stackoverflow
