### ISSUE TITLE
_recv_raw is breaking ISOTPNativeSockets

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2425]
@gpotter2 
Hi, on some hardware in the loop tests, we discovered the following error:
```
WARNING: Socket <scapy.contrib.isotp.ISOTPNativeSocket object at 0x7319dc70> failed with 'unpack requires a buffer of 16 bytes'. It was closed.
```
We assume this error is fired from this line:
https://github.com/secdev/scapy/blob/ae6b93b9263cab4319be463527b92d1edf13ce43/scapy/supersocket.py#L109

Unfortunately, I don't know exactly whats going on here, but my ISOTPNativeSockets get closed on a receive.

**Comment by polybassa** [comment]
On a virtual CAN interface, I can't reproduce the error. It only happens on a real CAN interface

**Comment by gpotter2** [comment]
Could you print out the content of `cmsg_data` ?
This is the most accurate way to get the packet timestamp

**Comment by gpotter2** [comment]
It sounds like the driver of the CAN interface does not support this or did not implement it properly.

**Comment by polybassa** [comment]
Here's the content of `cmsg_data` `b'\x11\xe1&^+\xfb\xbb\x16'`
It's very likely that the driver implements something not properly

**Comment by polybassa** [comment]
this output is generated from `print(cmsg_data)`

**Comment by gpotter2** [comment]
Alright it seems so.

We ask for nanosecond precision (because why not) using `SO_TIMESTAMPNS`, but the driver answers with normal precision.

Let's just add a check that choses between the two depending on the length

**Comment by polybassa** [comment]
Awesome! Thanks for your support.

**Comment by gpotter2** [comment]
Could you try out https://github.com/secdev/scapy/pull/2426

**Comment by polybassa** [comment]
it's fixed! Thanks
