### ISSUE TITLE
Replace PyCrypto by cryptography

### ISSUE THREAD

**Issue by robin-jarry** [secdev/scapy#243]
Hi all,

as you may know, _scapy_ uses _PyCrypto_ for some (optional but useful) features.

As stated by _PyCrypto_'s maintainer, [this project is _almost_ dead](https://lists.dlitz.net/pipermail/pycrypto/2014q1/000782.html). It has [not received any activity since june 2014](https://github.com/dlitz/pycrypto/commits/master).

On 2014-02-06 09:51:39, Dwayne Litzenberger wrote:

> I'm thinking of merging with the folks at https://cryptography.io/,  which is covered by an Apache 2.0 license.

Some python libs have started to move from _PyCrypto_ to _cryptography_: https://github.com/paramiko/paramiko/pull/394

Indeed, _cryptography_ is much more active. It has detailed documentation and is based on _openssl_. I also supports pypy, and installation on windows is easier. https://cryptography.io/en/latest/ https://pypi.python.org/pypi/cryptography

It would be a good thing to use _cryptography_ instead of PyCrypto. This concerns the IPsec and TLS layers, mostly.

What do you think?

**Comment by p-l-** [comment]
As I understand it, cryptography does not work with Python 2.5, so that change will be possible after we drop support for that (old) Python version. FYI @guedou and I plan that the next release will be the last one with Python 2.5 (and 2.6?) support.

**Comment by robin-jarry** [comment]
If you are willing to drop python < 2.7 support, some good cleanup can be performed :-)

When do you plan to cut the next release?

**Comment by guedou** [comment]
We try to do at least a release for Christmas. However, we can do one before as soon as we are confident that _everything_ works fine on Python 2.5.

At first, my goal was to merge the BPF support before stopping supporting Python 2.5. As, I am struggling with Mac OS X support on Travis, we can try to release 2.3.3 in the next weeks.

**Comment by robin-jarry** [comment]
@guedou commented 33 minutes ago 
> We try to do at least a release for Christmas. However, we can do one before as soon as we are confident that everything works fine on Python 2.5.

I saw that the automatic tests only run on 2.6, 2.7 and pypy. Do you plan on adding checks for 2.5?

> At first, my goal was to merge the BPF support before stopping supporting Python 2.5. As, I am struggling with Mac OS X support on Travis, we can try to release 2.3.3 in the next weeks.

Ok, and what about dropping 2.6 support too as @p-l- mentioned?

Do you have anything in mind concerning a global code cleanup if you decide to only support 2.7? Maybe it could be a good reason to begin thinking about python 3 support (using [six](https://pypi.python.org/pypi/six) for compat' layer)?

But that is another subject :-)

About the porting from PyCrypto to cryptography, I think that @Motsah has a draft commit ready (at least for the IPsec layer). He should be creating a PR soon(tm) so you can discuss the details with him.

**Comment by guedou** [comment]
Unfortunately, Travis CI does not support 2.5. I used to play with [this repository ](https://github.com/guedou/scapy-python2.5) that uses docker to get a 2.5 environnement. However, I don't know if it still works.

I am also fine with dropping 2.6.

**Comment by kinap** [comment]
I came looking to open this issue myself. _cryptography_ is much more robust, active, and supports additional algorithms that I'd like to use in the IPSec layer.

**Comment by guedou** [comment]
I updated the `Dockerfile` from my [scapy-python2.5](https://github.com/guedou/scapy-python2.5) repository. It can be used as follows:
```
$ docker build -t guedou/scapy-python2.5:v0.2 .
$ docker run --rm -it guedou/scapy-python2.5:v0.2 bash
```

Then, you can clone scapy manually and run the tests.

However, the `mock` and `ecdsa` modules do not work with Python 2.5. As as consequence, some part of `regression.uts` and `cert.uts` can not be tested at all. I don't think that we should spend more time into supporting Python 2.5. So, I think we can do a release soon and kill Python2.5. Folks, what's your opinion ?

I submitted PR #268 that fix a small issue.

**Comment by mtury** [comment]
I've been working on a TLS implementation and I think it would make sense to switch from pycrypto to python-cryptography.

Although the sources of pycrypto provide support for both GCM and CCM encryption modes, it does not seem that they have been packaged (at least not for Debian). It wouldn't be realistic to ask scapy users to retrieve the sources and build pycrypto in order to get this support.

python-cryptography provides direct support for GCM, but does not offer CCM yet. I should try to submit a first PR there in order to add this support.

**Comment by robin-jarry** [comment]
@guedou wrote:
> I don't think that we should spend more time into supporting Python 2.5. So, I think we can do a release soon and kill Python2.5. Folks, what's your opinion ?

Yes yes kill it :)

What do you plan to do to drop python 2.5 (and 2.6?) support? Maybe this could be a good opportunity to make scapy compatible with python 3.

**Comment by mtury** [comment]
Regarding my last comment: after further examination, I'm not sure I could easily provide the robust CCM support I was hoping for. As python-cryptography relies on openssl, I fear its implementation entails oblique API calls which I'm not familiar with.

Aside from that, the next release should offer support for ChaCha20-Poly1305. I guess the best thing to do here is switching to python-cryptography after the release suggested by @guedou, and hoping that their next release will be here soon.

**Comment by guedou** [comment]
@robin-jarry first thing first =) First, I need to sync with @p-l- to make the release happen.

**Comment by mtury** [comment]
Hum. I'm not as enthused by python-cryptography as I was yesterday. It seems that CCM implementation is a bit far down the road, as the API has not been designed for handling AEAD ciphers in a generic enough way.

I've been watching [pycryptodome](https://github.com/Legrandin/pycryptodome). It's a fork from pycrypto which has received several improvements since 2013. It provides a handful of recent functions and it's properly packaged. Also the primitives may be edited independently from openssl, which might be something we prefer to scapy having a 'robust' crypto library (I don't believe scapy should be used for sensitive production contexts anyway).

The main problem being that there's no community as for python-cryptography. Does it offer the algorithms you're looking for, @kinap? Not sure what's the best approach here.

**Comment by kinap** [comment]
@mtury pycryptodome does support all of the algorithms I'm interested in (AEAD algorithms for IPSec). It looks like it may be easier to integrate too.

**Comment by robin-jarry** [comment]
The only problem I see with pycryptodome is that it looks like a one man project (exactly like pycrypto). There is a chance that it does not receive as much care as python-cryptography. Also, there is a chance that the maintainer drops it.

@mtury, @kinap, if CCM support is not satisfactory, wouldn't it be a good thing to contribute to improve it? I understand that relying on openssl has downsides but maybe we can propose evolutions in python cryptography to support new algorithms not supported by openssl.

What do you think?

**Comment by mtury** [comment]
I do appreciate the fact that pycryptodome does not provide the same insurance as cryptography. However, after some examination of the code and explanation from the main maintener, it does not seem like I have enough time at my disposal to offer a valuable contribution to the project.

If anyone should add CCM support to cryptography (and maybe the other AEAD modes @kinap needs), even after the near release of the TLS module, I'd have no problem rewriting the appropriate parts. 

In the meantime, as TLS 1.3 has drastically reduced the number of cipher suites allowed, with CCM still in the game, I think I'd rather favour pycryptodome.

**Comment by kinap** [comment]
@robin-jarry I agree it would be best to use pycryptography for the reasons you listed and have a preference towards it.

Let me scope what it would take to contribute a CCM implementation to their project. Not sure if I have time but I don't know that yet. @mtury

**Comment by mtury** [comment]
A link to the main issue: [https://github.com/pyca/cryptography/issues/2968](url)

**Comment by guedou** [comment]
While reading the discussions, two technical requirements arise:
* AEAD modes (precisely CCM and GCM)
* _new_ algorithms (ChaCha20 and Poly1305)
Moreover, it seems that cryptography is more active and easier to install.

Unfortunately, none of the three discussed modules cover these requirements =/


As one of the project maintainer, I would like that:
* Scapy works out of the box without any dependencies
* when dependencies are required, they must be easy to install, and Scapy should not fail when they are not. A `warning()` must be display to the user stating that functionalities are disabled.

To sum up, my immediate choice is to keep using pycrypto and document howto install 2.7a1 to use advanced Scapy feature.

In the mean time, we could evaluate the cost of moving to cryptography. If CCM is not ready yet, we could implement it ourselves in Scapy.

Does this sound fair ?
Feel free to comment =)

**Comment by robin-jarry** [comment]
That sounds like what I had in mind.

About the cost of moving to cryptography: @Motsah proposed a patch that does it. See PR #263

**Comment by guedou** [comment]
@robin-jarry thanks. I did not see this PR =/

**Comment by gpotter2** [comment]
Small note: on windows, PyCrypto is completly broken, so if you manage to install it many functions return error codes...

**Comment by johnthagen** [comment]
FWIW, PyCrypto also apparently has at least one known vulnerability: https://github.com/dlitz/pycrypto/issues/176
