### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-p9nki1_9/scapy/

### ISSUE THREAD

**Issue by snood1205** [secdev/scapy#244]
There is seemingly an egg error within scapy as installation fails both with `pip install scapy` and `pip3 install scapy`.

**Comment by guedou** [comment]
Cruel you give use more details ?
This might be related to PR#224.

Thanks.

**Comment by guedou** [comment]
Fixed in 2.3.3
```
virtualenv scapy
source scapy/bin/activate
pip install scapy
python -c 'from scapy.all import VERSION; print VERSION'
2.3.3
```

**Comment by 0x69676f72** [comment]
C:\WINDOWS\system32>pip install scapy
Collecting scapy
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IGORMO~1\AppData\Local\Temp\pip-build-5nl5rwcy\scapy\setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\IGORMO~1\AppData\Local\Temp\pip-build-5nl5rwcy\scapy\

C:\WINDOWS\system32>

**Comment by 0x69676f72** [comment]
```

C:\WINDOWS\system32>pip install scapy
Collecting scapy
  Using cached scapy-2.3.3.tgz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\IGORMO~1\AppData\Local\Temp\pip-build-5nl5rwcy\scapy\setup.py", line 36
        os.chmod(fname, 0755)
                           ^
    SyntaxError: invalid token

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\IGORMO~1\AppData\Local\Temp\pip-build-5nl5rwcy\scapy\

C:\WINDOWS\system32>
```

**Comment by gpotter2** [comment]
Hi, please retry using the online github version

https://github.com/secdev/scapy/archive/master.zip

Then install it
`python setup.py install`
