### ISSUE TITLE
TLS Certificate Verify decoding issue

### ISSUE THREAD

**Issue by sylvainpelissier** [secdev/scapy#2450]
#### Description

When decoding a TLS Certificate Verify packet I have the following results:

```python
from scapy.all import rdpcap
from scapy.layers.tls.record import TLS

packets = rdpcap('certificate-verify.pcapng')

for packet in packets:
    if packet.haslayer(TLS):
        print(packet[TLS].show())
```

```
###[ TLS ]### 
  type      = handshake
  version   = TLS 1.2
  len       = 80    [deciphered_len= 80]
  iv        = b''
  \msg       \
   |###[ Raw ]### 
   |  load      = '\x0f\x00\x00L\x04\x03\x00H0F\x02!\x00\xcf\xf1\xd0:1\xb8\xe4JCU\x00\x8c\xcdg\xf9=g\x84\xa3h;V@\xfd\xd1\\\xf0\xc4f\xfa\x18\xdc\x02!\x00\x82\x1dF\xc1\xd1\xab\x86\xaa\xb9"\x0eA\xf2\xc3Rj\xd7\xf1\xe9\xaf\x9b\xa5?R\n\xca\x15\xfe)\xa9j\x84'
  mac       = b''
  pad       = b''
  padlen    = None

None
```

However, the class **TLSCertificateVerify** should return a decoded signature not raw bytes.

#### Environment

-   Scapy version: `2.4.3.dev259`
-   Python version: `3.7.5`
-   Operating System: `Ubuntu 19.04`

#### How to reproduce

> pcap is attached: [certificate-verify.zip](https://github.com/secdev/scapy/files/4134036/certificate-verify.zip)

#### Related resources

>  It seems to be related to #945

**Comment by guedou** [comment]
Thanks for reporting the issue. PR #2455 fixes it.
