### ISSUE TITLE
Openflow3 & behaviour of oxm fields with "_mask" in fields

### ISSUE THREAD

**Issue by Anginer** [secdev/scapy#2454]
#### Brief description

In the file openflow3.py, if you want to create an oxm_fields (like OFBIPv4Src) and add to it a mask, you cannot put mask value inside.

line 282 of openflow3.py :
if i % 2:
      ofp_oxm_fields[i].append(BitField(org[1] + "_mask", 0, 8 * org[2]))

but, in our case, i = 23 

#### Environment

-   Scapy version: 2.4.2
-   Python version: 3.7
-   Operating System: Linux Debian 9

#### How to reproduce

Exemple :
match = openflow3.OFBIPv4Src(ipv4_dst='192.168.0.1')
match.hasmak = True

and ... how to add mask value ? 

#### Expected result

you should have : match = openflow3.OFBIPv4Src(ipv4_dst='192.168.0.1', ipv4_dst_mask=VALUE)

**Comment by guedou** [comment]
According to the source code, you need to use `OFBIPv4SrcHM()` (HM is for HAS Mask) instead:
```
>>> ls(OFBIPv4SrcHM)                                                                                                           
class      : ShortEnumField                      = (32768)
field      : BitEnumField  (7 bits)              = (11)
hasmask    : BitField  (1 bit)                   = (1)
len        : ByteField                           = (8)
ipv4_src   : IPField                             = ('0')
ipv4_src_mask : BitField  (32 bits)                 = (0)
>>> OFBIPv4SrcHM(ipv4_src='192.168.0.1', ipv4_src_mask=2807)                                                                   
<OFBIPv4SrcHM  ipv4_src=192.168.0.1 ipv4_src_mask=2807 |>
>>> ls(OFBIPv4SrcHM)                                                                                                           
class      : ShortEnumField                      = (32768)
field      : BitEnumField  (7 bits)              = (11)
hasmask    : BitField  (1 bit)                   = (1)
len        : ByteField                           = (8)
ipv4_src   : IPField                             = ('0')
ipv4_src_mask : BitField  (32 bits)                 = (0)
```

**Comment by Anginer** [comment]
Hum... very nice.

Thank you !!

Sorry for my bad code reading
