### ISSUE TITLE
Setting up test environment info is not complete

### ISSUE THREAD

**Issue by panjacek** [secdev/scapy#2479]
#### Brief description
I was trying to setup scapy test env, here it mentions that no external deps are required when using tox: https://scapy.readthedocs.io/en/latest/development.html#using-tox-to-test-scapy

It's unclear what is required to perform local testing from the documentation. 

I saw that there is a travis config which installs these items:
```bash
# Install wireshark data       
if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_SUDO" = "true" ]
then
  sudo apt-get update          
  sudo apt-get -qy install tshark 
  sudo apt-get -qy install can-utils build-essential linux-headers-$(uname -r);
fi
  
# Install pcap & dnet          
if [ ! -z $SCAPY_USE_PCAPDNET ] && [ "$TRAVIS_OS_NAME" = "linux" ] 
then
  $SCAPY_SUDO apt-get -qy install libdumbnet-dev libpcap-dev
fi

```

#### Environment
-   Scapy version: 4e5480eee37b3d84bb974b3de8e5291228eccd69
-   Python version: 3.7.5 or 3.7.6
-   Operating System:  Ubuntu 19.10 or Debian 10.2 (docker image python:3.7-slim)

Due to tests using root, I decided to create dockerfile and try to run them inside
```Dockerfile

FROM python:3.7-slim

RUN pip install --no-cache-dir \
        tox

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update &&\
    apt-get install --no-install-recommends -qy\
        can-utils \
        build-essential \
        iproute2 \
#        linux-headers-$(uname -r) \
        libdumbnet-dev libpcap-dev \
        openssh-server \
        sudo \
        tcpdump \
        tshark &&\
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash scapy

# ADD . /app
WORKDIR /app
        
USER scapy

```
#### How to reproduce

Follow the https://scapy.readthedocs.io/en/latest/development.html#using-tox-to-test-scapy:
`tox -- -K vcan_socket -K tcpdump -K tshark -K nmap -K manufdb -K crypto`

#### Actual result
Multiple tests failing

#### Expected result
Test are ok.

Is it possible to get bare minimum install instruction for testing or better a Dockerfile recipe to run isolated tests on any linux platform?

**Comment by guedou** [comment]
Could you provide the tox output and the list of tests that are failing ?

**Comment by guedou** [comment]
The following works without any error:
```
$ vagrant init bento/ubuntu-19.10
$ vagrant up
$ vagrant ssh
$ sudo apt update
$ sudo apt install tox net-tools
$ git clone https://github.com/secdev/scapy/
$ cd scapy/
$ tox -- -K vcan_socket -K tcpdump -K tshark -K nmap -K manufdb -K crypto
```

**Comment by panjacek** [comment]
### Vagrant VMs vs docker
I have no idea whats inside the vagrant, is this some special virtual machine? 
Is there source code for it?

I was expecting some issues if root testing is used. On docker not everything can work there.

### root testing
The tests by default tries to elevate via sudo at some stage, so I tried to run `TOXENV=py37-linux_non_root tox` like in .travis.yaml jobs and it failed at first, but passed on second try when I redirected stdout to log file ;).

Sadly it tries to elevate even when I am root, so I had to install sudo.

`TOXENV=py37-linux_root tox`
and 
`tox -- -K vcan_socket -K tcpdump -K tshark -K nmap -K manufdb -K crypto`

I can't get tests to pass the test next after this one, it was stuck on it for 15 min with 0% CPU usage.
`passed 3B4095F3 000.00s Building SSLv2 packets - ClientHello with automatic length computation`


When run as root stuck at taps creation due to lack of `iproute2` package.

Next root error was on iptables.

Ok another interface creation error :/ it fails on modprobe even when vcan is there. I've inserted it on host. I will try tomorrow after work to skip vcan or change to check lsmod first.
```python
Regression tests for ISOTP
-- Run Wed Feb 19 23:02:47 2020 from [test/contrib/isotp.uts] by UTscapy

Passed=102
Failed=35


###(002)=[failed] Initialize a virtual CAN interface

>>> if 0 != call("cansend %s 000#" % iface0, shell=True):
...     # vcan0 is not enabled
...     if 0 != call("sudo modprobe vcan", shell=True):
...         raise Exception("modprobe vcan failed")
...     if 0 != call("sudo ip link add name %s type vcan" % iface0, shell=True):
...         print("add %s failed: Maybe it was already up?" % iface0)
...     if 0 != call("sudo ip link set dev %s up" % iface0, shell=True):
...         raise Exception("could not bring up %s" % iface0)
... 
Traceback (most recent call last):
  File "<input>", line 5, in <module>
Exception: modprobe vcan failed

```



### tshark
If I dont add tshark to container I get multiple errors were due to missing tshark (tcpdump is present in the standard ubuntu) e.g.
```python
Traceback (most recent call last):
  File "/app/scapy/utils.py", line 1788, in tcpdump
    stderr=stderr,
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tshark': 'tshark'
```

**Comment by guedou** [comment]
Have a look at https://www.vagrantup.com/ It works perfectly to test Scapy.

The errors that you are reporting are likely related to your environment as the related tests are supposed to be discarded using the `-K` flags.

**Comment by rifen** [comment]
So what you are saying is don't use docker. Use vagrant? I have been using docker for a few weeks now for this and I have been having weird issues. Like traceroute outputting the same IP instead of each hop.

**Comment by guedou** [comment]
I don't use Docker, and I never had any issue with Vagrant to launch Scapy unit tests. That's how we test the release on *BSD.

**Comment by polybassa** [comment]
I made some tests with docker and CAN in the past. Since docker uses the network and kernel modules of the host OS, an abstraction of interfaces wasn't possible for me. I assume this is similar to other network interfaces, as well. In my opinion, this leads to the conclusion, that all tests which depend on the network or on kernel modules are not abstract-able by docker containers.

**Comment by panjacek** [comment]
Vagrant failed on this:
```python
###(115)=[failed] Field Deprecation test

>>> class TestPacket(Packet):
...     fields_desc = [
...         ByteField("a", 0),
...         LEShortField("b", 15),
...     ]
...     deprecated_fields = {
...         "dpr": ("a", "1.0"),
...         "B": ("b", "1.0"),
...     }
... 
>>> pkt = TestPacket(a=2, B=3)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/vagrant/scapy/scapy/base_classes.py", line 266, in __call__
    i.__init__(*args, **kargs)
  File "/home/vagrant/scapy/scapy/packet.py", line 170, in __init__
    fname = self._resolve_alias(fname)
  File "/home/vagrant/scapy/scapy/packet.py", line 339, in _resolve_alias
    ), DeprecationWarning
DeprecationWarning: B has been deprecated in favor of b since 1.0 !

ERROR: InvocationError for command '/usr/bin/sudo -E /home/vagrant/scapy/.tox/linux_warnings/bin/python -Werror -m scapy.tools.UTscapy -c ./test/configs/linux.utsc -K random_weird_py3 -K vcan_socket -K tcpdump -K tshark -K nmap -K manufdb -K crypto' (exited with code 1

  py37-linux_non_root: commands succeeded
  py37-linux_root: commands succeeded
ERROR:   linux_warnings: commands failed
```
I think I saw this as false fail before. Nope failed on retest as well.


As I said before non root tests can be run in docker.
> The errors that you are reporting are likely related to your environment as the related tests are supposed to be discarded using the -K flags.
Yes I tried to run tests same as in travis jobs as I wrote before, just plain tox.
