### ISSUE TITLE
can_isotp kernel module changed ioctl

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2481]
Hi, 
I just found out, that a change in Hartkopps Kernel module, which I need for NativeISOTPSockets, broke the `get_last_packet_timestamp` function.

The following change removed the support of ioctl for the kernel module, on recent Kernels:
https://github.com/hartkopp/can-isotp/commit/ff85005831d472e2e2a3b444abad58c915193ca7

Do you know, how this can be fixed?

**Comment by polybassa** [comment]
At least, I assume that this is the problem, why the unit tests are failing. 
Is it possible to call this function `sock_gettstamp` from python?

**Comment by polybassa** [comment]
I have to investigate the changes closer. This might not be the problem.

**Comment by polybassa** [comment]
See #2482

**Comment by gpotter2** [comment]
To fix that you just need to split the try/catch in two. Something like
```python
try:
    self.ins.setsockopt(SOL_PACKET, PACKET_AUXDATA, 1)
    self.auxdata_available = True
except OSError:
    pass

try:
    self.ins.setsockopt(
        socket.SOL_SOCKET,
        SO_TIMESTAMPNS,
        1
    )
    self.auxdata_available = True
except OSError:
    pass
if not self.auxdata_available:
    warning("...")
```

If you get the time, feel free to try it out and/or submit a PR.
