### ISSUE TITLE
ISOTPNativeSockets are broken from auxdata_available

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2482]
@guedou Your commit d81bd862f3f7ac087df004a2b519c6490f3638a3 broke the unit tests for `ISOTPNativeSockets`. If I add ```auxdata_available = True``` the unit test is fixed. But I don't know the consequences of this change and if it's safe to apply.

**Comment by guedou** [comment]
Sorry about that. I did not see any failing tests when testing the PR. Can you share the error message?

**Comment by polybassa** [comment]
Hi, the error message is here: https://travis-ci.com/secdev/scapy/jobs/287828075#L4300
#2483 should fix it (I hope).

**Comment by guedou** [comment]
If my understanding is correct, `get_last_packet_timestamp()` cannot be called on a `PF_CAN` socket. That is the core issue.

**Comment by polybassa** [comment]
It should be possible to call it. Hartkopp has a command line application, where he calls `ioctl` on a `PF_CAN` socket: https://github.com/linux-can/can-utils/blob/da65fdfe0d1986625ee00af0b56ae17ec132e700/isotpsniffer.c#L98

**Comment by polybassa** [comment]
Can the changes in #2483 have negative effects?

**Comment by guedou** [comment]
If #2483 fixes the issue, that's good to me =)
