### ISSUE TITLE
Cannot Talk to My Host on the Same Interface

### ISSUE THREAD

**Issue by falhumai96** [secdev/scapy#2492]
#### Brief description

Cannot talk to my host from a custom MAC address and IP address on the same interface and the same machine.

#### Environment

-   Scapy version: scapy-2.4.3.dev325.
-   Python version: 3.8.
-   Operating System: Windows 10.

#### How to reproduce

I have created a custom ARP spam script to talk to hosts in one network through my host's interface on that network. Here's the code snippet `custom_arp.py`:

```
import scapy.all
import threading
import time
import argparse


def arp_sender(iface, host_ip, guest_ip, guest_mac):
    arp_req = scapy.layers.l2.ARP(psrc=guest_ip, pdst=host_ip)
    bcast = scapy.layers.l2.Ether(
        src=guest_mac, dst='ff:ff:ff:ff:ff:ff')
    arp_req_bcast = bcast / arp_req
    while True:
        time.sleep(2)
        scapy.all.sendp(arp_req_bcast, iface=iface)


if __name__ == "__main__":
    pasrer = argparse.ArgumentParser()
    pasrer.add_argument('--iface', '-i', required=True)
    pasrer.add_argument('--host-ip', required=True)
    pasrer.add_argument('--guest-ip', required=True)
    pasrer.add_argument('--guest-mac', required=True)
    args = pasrer.parse_args()
    th = threading.Thread(target=arp_sender, args=(
        args.iface, args.host_ip, args.guest_ip, args.guest_mac
    ))
    th.start()
    th.join()
```

Let's say my host's IP address on the network is `192.168.1.116`, another host on the same network has an IP of `192.168.1.108`, and for my custom device I will choose the IP address of `192.168.1.151` and a MAC address of `54:43:23:76:67:22`. I then run the above script from an admin shell to talk to my original host and the other host from my custom ARP requester using the following commands, respectively:

- `python custom_arp.py --iface Ethernet --host-ip 192.168.1.116 --guest-ip 192.168.1.151 --guest-mac 54:43:23:76:67:22`.

- `python custom_arp.py --iface Ethernet --host-ip 192.168.1.108 --guest-ip 192.168.1.151 --guest-mac 54:43:23:76:67:22`.

#### Actual result

Observed using Wireshark, my machine now receives ARP responses from the other host in the network (with IP address of `192.168.1.108`), but not from my original host (with IP address of `192.168.1.108`). Here's screen captures of the results for talking to my host and talking to the other host, respectively:

![Talk to My Host](https://user-images.githubusercontent.com/16661128/75117644-310f7a80-5628-11ea-9379-119367a4b0d3.PNG)

![Talk to Another Host](https://user-images.githubusercontent.com/16661128/75117651-379df200-5628-11ea-8c8b-a49564817c16.PNG)

You can see from the screen captures above, I can get responses from `192.168.1.108`, but not from `192.168.1.116`. Just a reminder, both of `192.168.1.116` (my original host's IP address) and `192.168.1.151` (the custom "machine" with custom MAC address that sends ARP requests (e.g. similar to a VM)) are on the same interface, but `192.168.1.108` is on another interface, since it is a an actual physical host on my network.

#### Expected result

`192.168.1.151` should get responses from `192.168.1.116` and `192.168.1.108`.

#### Questions

Why would this issue exists? is it a result of how Scapy injects the packets? Or, is it a firewall issue (I even disabled my firewall)? Also, how would virtual machines managers, like VirtualBox and VMWare, implement adapters such as bridged networking where the owner host can talk to a VM, and a VM can talk to the host, on the same interface?

**Comment by gpotter2** [comment]
Make sure you're selecting the correct interface.
this really doesn't look like a scapy issue, but something to do with your config..
