### ISSUE TITLE
Pickling UDP or TCP with no underlayer triggers a warning

### ISSUE THREAD

**Issue by natedogith1** [secdev/scapy#2499]
- Scapy version: 2.4.3
- Python version: 3.7.3

Pickling a UDP without a IP layer triggers a warning.
```python
>>> import pickle, scapy.all, logging
>>> logging.basicConfig()
>>> pickle.dumps(scapy.all.UDP())
WARNING:scapy.runtime:No IP underlayer to compute checksum. Leaving null.
b'\x80\x03cscapy.layers.inet\nUDP\nq\x00)Rq\x01C\x08\x005\x005\x00\x08\x00\x00q\x02\x85q\x03b.'
```

It also causes volatile values to become static:
```python
>>> a = scapy.all.UDP(chksum=scapy.volatile.RandShort())
>>> a
<UDP  chksum=4183 |>
>>> a
<UDP  chksum=3212 |>
>>> a
<UDP  chksum=9549 |>
>>> a
<UDP  chksum=55565 |>
>>> a = pickle.loads(pickle.dumps(scapy.all.UDP(chksum=scapy.volatile.RandShort())))
>>> a
<UDP  sport=domain dport=domain len=8 chksum=0x3b7c |>
>>> a
<UDP  sport=domain dport=domain len=8 chksum=0x3b7c |>
>>> a
<UDP  sport=domain dport=domain len=8 chksum=0x3b7c |>
>>> a
<UDP  sport=domain dport=domain len=8 chksum=0x3b7c |>

```

**Comment by guedou** [comment]
The warning is expected, if you don't assign a checksum. Pickling the Packet constructs a complete valid Packet with all fields computed: here you can see that the length was computed by Scapy. The volatile value is converted to a real value.

**Comment by natedogith1** [comment]
That seems like an issue with the pickling implementation.  Pickling and unpickling should generally produce the same state as copying an object.
