### ISSUE TITLE
Warning logged on import on system without an IPv6 default route.

### ISSUE THREAD

**Issue by natedogith1** [secdev/scapy#2505]
* Scapy version: 2.4.3
* Python version: 3.7.3

Importing scapy causes a warning on systems without an IPv6 default route.

```python
>>> import logging
>>> logging.basicConfig()
>>> import scapy.all
WARNING:scapy.runtime:No route found for IPv6 destination :: (no default route?)
```

The issue seems to be caused by scapy.route6 trying to set conf.iface6 to the default route on import.

**Comment by guedou** [comment]
This is not an issue. This message is meant to indicate that Scapy won't work correctly for IPv6 packets injection.

**Comment by natedogith1** [comment]
I wouldn't expect a warning, given that I'm not creating any IPv6 packets and I'm not sending them.  (I also wouldn't expect any issues with IPv6 if there's a non-default route that's applicable for them)
