### ISSUE TITLE
inet defragment() crash with Attribute Error

### ISSUE THREAD

**Issue by YayaTour3** [secdev/scapy#2510]
#### Brief description

Calling the function `defragment(pkts)`  with a list of fragments, that cannot be reassembled,  crash with ```AttributError``` instead of returning a one list of packets.

Has anyone else already encountered this problem (IPv4) ? 

`AttributeError: 'list' object has no attribute '_defrag_pos'`

#### Environment

-   Scapy version: `2.4.3rc4`
-   Python version: `2.7`

#### How to reproduce
```python
>>> pkts = fragment(IP(dst="10.0.0.5")/ICMP()/("X"*60000))
>>> defragment(pkts[1:])
```
#### Actual result
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-10-4cb9be065ce9> in <module>()
----> 1 defragment(pkts[1:])

/usr/local/lib/python2.7/dist-packages/scapy/layers/inet.pyc in defragment(plist)
   1111 def defragment(plist):
   1112     """defragment(plist) -> plist defragmented as much as possible """
-> 1113     return _defrag_logic(plist, complete=True)
   1114 
   1115 

/usr/local/lib/python2.7/dist-packages/scapy/layers/inet.pyc in _defrag_logic(plist, complete)
   1091         final.extend(defrag2)
   1092         final.extend(missfrag)
-> 1093         final.sort(key=lambda x: x._defrag_pos)
   1094         if hasattr(plist, "listname"):
   1095             name = "Defragmented %s" % plist.listname

/usr/local/lib/python2.7/dist-packages/scapy/layers/inet.pyc in <lambda>(x)
   1091         final.extend(defrag2)
   1092         final.extend(missfrag)
-> 1093         final.sort(key=lambda x: x._defrag_pos)
   1094         if hasattr(plist, "listname"):
   1095             name = "Defragmented %s" % plist.listname

AttributeError: 'list' object has no attribute '_defrag_pos'
```

#### Expected result
One list containing all packets

#### Related resources
https://github.com/secdev/scapy/blob/3d231b120762b31c65930fd35997e88f69e62ce0/scapy/layers/inet.py#L1042
https://github.com/secdev/scapy/blob/3d231b120762b31c65930fd35997e88f69e62ce0/scapy/layers/inet.py#L1027

#### Possible Fix
replace `missfrag.append(lst)` with `missfrag.extend(lst)`

Regards
Alex

**Comment by elijose55** [comment]
Can I work on this issue?

**Comment by YayaTour3** [comment]
Hi elijose55,
yes, you can work on it.
Alex
