### ISSUE TITLE
recognition of wpa 3 beacons

### ISSUE THREAD

**Issue by mstekker** [secdev/scapy#2511]
Hi,

I am using Scapy to test the security of APs (kind of encryption) in this way:
nstats = pkt[Dot11Beacon].network_stats()

Works great, but it shows WPA3 APs as WPA2. Are there any solutions?

Thanks and with kind regards,

Mart

**Comment by p-l-** [comment]
I don't think this is supported (yet). Could you provide examples? (PCAP files with WPA3 beacons)
