### ISSUE TITLE
I try to send icmp packets through ppp link, but sr can't receive the reply, and tcpdump ppp0 is ok!

### ISSUE THREAD

**Issue by hltttabc** [secdev/scapy#2513]
sh-4.2# tcpdump -i ppp0 -n icmp
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode  
listening on ppp0, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
23:52:58.595117 IP 219.240.73.152 > 106.120.159.142: ICMP echo request, id 10915, seq 1, length 8
23:52:58.618401 IP 106.120.159.142 > 219.240.73.152: ICMP echo reply, id 10915, seq 1, length 8

My code is as follows，and result is timeout！Scapy Version is 2.4.3
-----------------------------------------------------------------------------------------
import os  
from scapy.all import *

conf.route.resync()  
packet = IP(dst="www.baidu.com")/ICMP(id=10915, seq=1)  
ans,unans = sr(packet, filter='icmp', verbose=0, timeout=3)  
if ans is None or len(ans) <= 0:  
&ensp;&ensp;&ensp;&ensp;result = {"ans": len(ans), "unans": len(unans), "error": "timeout"}    
&ensp;&ensp;&ensp;&ensp;print(result)  
&ensp;&ensp;&ensp;&ensp;return

tx = ans[0][0]  
rx = ans[0][1]  
time = '%.2f' % ((rx.time-tx.sent_time) * 1000)   
ip = rx.sprintf("%IP.src%")   
result = {"ip": ip, "time": time}  
print(result)

**Comment by guedou** [comment]
This is a known bug: https://scapy.readthedocs.io/en/latest/troubleshooting.html#bpf-filters-do-not-work-i-m-on-a-ppp-link

Can you try with `ans,unans = sr(packet, nofilter=True verbose=0, timeout=3)` instead?

**Comment by hltttabc** [comment]
thank you！ I just tried it ，but it still not work！

**Comment by hltttabc** [comment]
it works! I add nofilter=True and iface="ppp0", thank you very much!

**Comment by guedou** [comment]
FTR, this is fixed in master. The following now works fine:
```
>>> a, u = sr(IP(dst="10.0.0.2")/ICMP(), filter="icmp", iface="ppp0"); a.summary()
Begin emission:
Finished sending 1 packets.
*
Received 1 packets, got 1 answers, remaining 0 packets
IP / ICMP 10.0.0.1 > 10.0.0.2 echo-request 0 ==> IP / ICMP 10.0.0.2 > 10.0.0.1 echo-reply 0
```
