### ISSUE TITLE
TCP fragment flags

### ISSUE THREAD

**Issue by steevenlee** [secdev/scapy#2518]
Hi all,

I found the fragment() function simply split payload, TCP fields like flags are not changed accordingly.
a=Ether()/IP()/TCP()/("a"*10000)
b=fragment(a)
each TCP segments in b keep same flag, is TCP fragment supported officially?

Thanks,
Steeven

**Comment by gpotter2** [comment]
"IP fragmentation" is done on the.... IP layer, not TCP.
