### ISSUE TITLE
How can I use sniff to get a packet from tunnels

### ISSUE THREAD

**Issue by GlKorol** [secdev/scapy#2523]
my code:
```
from scapy.all import *

def call_me(packet):
    print(packet.summary())
    print(packet.show())

mysocket = socket.socket()
mysocket.connect(("127.0.0.1",1234))
supersocket = scapy.supersocket.StreamSocket(mysocket)
sniff(opened_socket=supersocket,store=False, prn=call_me)

```
for gets traffic, for my local machine execute:
`tcpdump -s0 -i any -w - | nc -lp 1234`

output:
```
Raw
###[ Raw ]### 
  load      = '~\xd3|,\x94v\x19\x9e\x18cPE+#\xe8\xaa\xd7}
```
I want to receive packages from stdin or from tunnel as in this example
`tcpdump -s0 -i any -w - |  wireshark -k -i -
`

**Comment by guedou** [comment]
This is a bug tracker not a forum. Please ask your question on the proper channel.
