### ISSUE TITLE
The scappy PPTPStartControlConnectionRequest protocol_version field

### ISSUE THREAD

**Issue by sei-vsarvepalli** [secdev/scapy#2530]
Looks like the field protocol_version is actually a floating point with two bytes to represent the integer value and two bytes for the decimal portion.  So for the protocol version to be 1.0 this byte value is actually 256, to get PPTP to work properly I have to basically start this 

`     
python shell
>>> send(IP()/TCP()/PPTPStartControlConnectionRequest())
.
Sent 1 packets.
>>> send(IP()/TCP()/PPTPStartControlConnectionRequest(protocol_version=256))
.
Sent 1 packets.

tcpdump view 

>>127.0.0.1.20 > 127.0.0.1.1723: Flags [S], cksum 0xdf7e (correct), seq 0:156, win 8192, length 156: pptp Length=156 CTRL-MSG Magic-Cookie=1a2b3c4d CTRL_MSGTYPE=SCCRQ PROTO_VER(0.1) FRAME_CAP() BEARER_CAP() MAX_CHAN(65535) FIRM_REV(256) HOSTNAME(linux) VENDOR()
02:31:30.855945 IP (tos 0x0, ttl 64, id 1, offset 0, flags [none], proto TCP (6), length 196)

 >> 127.0.0.1.20 > 127.0.0.1.1723: Flags [S], cksum 0xde7f (correct), seq 0:156, win 8192, length 156: pptp Length=156 CTRL-MSG Magic-Cookie=1a2b3c4d CTRL_MSGTYPE=SCCRQ PROTO_VER(1.0) FRAME_CAP() BEARER_CAP() MAX_CHAN(65535) FIRM_REV(256) HOSTNAME(linux) VENDOR()`

Can you please update the protocol_version to be correct by default 256 and be presented to the user as 1.0 to match protocol specs.

Thanks
Vijay

**Comment by guedou** [comment]
Could you submit a patch, or a PR?

**Comment by sei-vsarvepalli** [comment]
Hello Guillaume,

I will be happy to. I want to make sure I am reusing the available code.  I am trying to read through your Fields class in scapy/fields.py, I am a bit unsure of the best method that I can reuse to convert from a decimal value to this version and revision octets representation.   

Here is the note from the RFC:

 The Start-Control-Connection-Request and -Reply messages determine
   which version of the Control Connection protocol will be used.  The
   version number field carried in these messages consists of a version
   number in the high octet and a revision number in the low octet.
   Version handling is described in section 2. The current value of the
   version number field is 0x0100 for version 1, revision 0.
