### ISSUE TITLE
IKEv2 SA_AUTH negotiation fails

### ISSUE THREAD

**Issue by Zq1993Zq** [secdev/scapy#2533]
#### Things to consider
Hello:
   I'm learning how to use Scapy and in order to trying to establish an IKEv2 handshake with my equitments
   Completed IKE_INIT of negotiation, I also try to create an IKE_AUTH initiator request based on IKE_INIT, but negotiation fail, the reason is IKE_AUTH Initiator of packet ICD is bad, can you help me look up my create packet and give me some suggests.
    this is my create IKE_AUTH initiator:
	

`

    transform_auth_1 = IKEv2_payload_Transform(next_payload='Transform', transform_type='Encryption',
                                               transform_id="3DES", key_length=0xa8)
    transform_auth_2 = IKEv2_payload_Transform(next_payload='Transform', transform_type='Integrity',
                                               transform_id="SHA2-256-128")
    transform_auth_3 = IKEv2_payload_Transform(next_payload='last', transform_type='Extended Sequence Number',
                                               transform_id="No ESN")
    ts_i = IPv4TrafficSelector(IP_protocol_ID="All protocols", starting_address_v4='10.9.206.115',
                               ending_address_v4='10.9.206.115', length=16)
    ts_r = IPv4TrafficSelector(IP_protocol_ID="All protocols", starting_address_v4='10.9.203.213',
                               ending_address_v4='10.9.203.213', length=16)

    encry_packet = IKEv2_payload_IDi(next_payload='AUTH', IDtype='IPv4_addr', load= binascii.unhexlify("0a09ce73") ) / \
                   IKEv2_payload_AUTH(next_payload='SA', auth_type='Shared Key Message Integrity Code',) / \
                   IKEv2_payload_SA(next_payload='TSi',
                                    prop=IKEv2_payload_Proposal(next_payload='last', SPI=b'\xc1\x90]\xd1',
                                                                SPIsize=4,
                                                                proto="ESP", trans_nb=3,
                                                                trans=transform_auth_1 /
                                                                      transform_auth_2 /
                                                                      transform_auth_3, )) / \
                   IKEv2_payload_TSi(next_payload='TSr', number_of_TSs=1, traffic_selector=ts_i) / \
                   IKEv2_payload_TSr(next_payload='Notify', number_of_TSs=1, traffic_selector=ts_r) / \
                   IKEv2_payload_Notify(next_payload='None', proto='Reserved', length=8,
                                        type='MULTIPLE_AUTH_SUPPORTED')

    packet_auth = IP(dst='10.9.203.213', src='10.9.206.115') / \
                  UDP(sport=500, dport=500) / \
                  IKEv2(init_SPI=init_spi, resp_SPI=ans[IKEv2].resp_SPI, next_payload='Encrypted', exch_type='IKE_AUTH',
                        flags='Initiator', id=1) / \
                  IKEv2_payload_Encrypted(next_payload='IDi', load=encry_packet)
    ans_auth = sr1(packet_auth, timeout=1, iface="init")`

				
 ##### Questions:
	

1.  When I choose auth_type is 'Shared Key Message Integrity Code' on IKEv2_payload_AUTH, but I don't know the Shared Secret of PSK should be where?  Because accord to 2.15 on rfc7296,  Load of  IKEv2_payload_AUTH is base on Shared Secret.
2.  ICD is bad, may be two reasons: 
              -  Load of  IKEv2_payload_AUTH is bad
            -   Sk_ai and Sk_ei is bad

#### Environment

-   Scapy version:  2.4.2
-   Python version: 3.7
-   Operating System:  50~16.04.1-Ubuntu

**Comment by guedou** [comment]
Asking the same questions two days in a row without waiting for an answer is harassment! Scapy is an open-source project mainly developed on our spare time and your behavior is not respectful.

**Comment by Zq1993Zq** [comment]
So Sorry for my ignorance，but I'll hope help form you. Thanks.
