### ISSUE TITLE
Revert print of skip message

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2551]
Reminder: This changes have to be reverted. The purpose of subprocess.call was to display this message in the output of UTScapy. sys.stderr is redirected, and will not fulfill this purpose.

_Originally posted by @polybassa in https://github.com/secdev/scapy/pull/2459/review_comment/create_

**Comment by akorb** [comment]
Thanks that you created this PR.

One question:
Could be this
`subprocess.call("printf \"%s\r\n\" > /dev/stderr" % err, shell=True)`
replaced with a simpler
`subprocess.call("echo '%s' > /dev/stderr" % err, shell=True)`

**Comment by polybassa** [comment]
Might be possible, but I didn't tested it, yet
