### ISSUE TITLE
creating gtp  version2 pcaket

### ISSUE THREAD

**Issue by prujan** [secdev/scapy#2553]
Hi,
I am using scapy  2.4.3.dev404, python 3.6.
![gtv2_create_session_req](https://user-images.githubusercontent.com/49917340/77832572-38a2d180-7148-11ea-9311-03007cf4210d.PNG)
![gtv2_code](https://user-images.githubusercontent.com/49917340/77832693-f29a3d80-7148-11ea-9ce1-a3081cdc9fef.PNG)

I create gtp v2 Create Session Request Message and writing to pcap.
When i open pcap via wireshark i got "Packet size limited during capture".
The attached code and pcap below.

Thanks in advance.

**Comment by guedou** [comment]
Please provide a simple example that we can reproduce and that exhibits an issue with Scapy and not in your code.

**Comment by prujan** [comment]
payload = IE_IMSI(ietype='IMSI', length=8, IMSI='20801123456700')
        payload = payload/IE_FTEID(length=9, ipv4_present=1,
ipv4='1.1.1.1', GRE_Key=0x1111, InterfaceType=10)
        payload = payload/IE_FTEID(length=9, ipv4_present=1,
ipv4='40.1.1.1', GRE_Key=0x3333, InterfaceType=7)
        pkt = Ether(src='01:02:03:04:05:06',
dst='11:12:13:14:15:16')/IP(src=self.tunnelSrc, dst=self.tunnelDst)
        pkt = pkt/UDP(sport=2123, dport=2123)/GTPHeader(gtp_type=32,
length=12 + len(payload))/GTPV2CreateSessionRequest()
        pkt = pkt/payload
        writer = PcapWriter("/tmp/test/gtp.pcap", append=False, sync=True)
        writer.write(pkt)

**Comment by prujan** [comment]
>>> payload = IE_IMSI(ietype='IMSI', length=8, IMSI='20801123456700')
>>> payload = payload/IE_FTEID(length=9, ipv4_present=1, ipv4='1.1.1.1',
GRE_Key=0x1111, InterfaceType=10)
>>> pkt = Ether(src='01:02:03:04:05:06',
dst='11:12:13:14:15:16')/IP(src='1.1.1.1', dst='2.2.2.2')
>>> pkt = pkt/UDP(sport=2123, dport=2123)/GTPHeader(gtp_type=32, length=12+
len(payload))
>>> pkt = pkt/payload
>>> sendp(pkt)

**Comment by guedou** [comment]
I don't understand how this example exhibits an issue with Scapy. Provide an explanation, otherwise the issue will be closed.

**Comment by prujan** [comment]
Hi,
Could please show me how to create simple GTP version2 packet.
I need to create GTPv2 Create Session Request,
Thanks

**Comment by prujan** [comment]
Hi,
I understood, how to create packets, please close the issue.
