### ISSUE TITLE
Problem with func 6 of Modbus

### ISSUE THREAD

**Issue by salwaalem** [secdev/scapy#2563]
I have a problem with func 6 of Modbus.

I want to get the list of the registers numbers and the registers values. It works for the other functions but not for func 6 and 5 I have all the time 0 for the list of registers number and values/flow . Here is my code in my parser.py:

    def reg_no_list(s):
	r = []
	for p in s:
		if p.haslayer('ModbusADURequest'):
			try:
				r.append(p['ModbusADURequest'][1].registerAddr)
			except AttributeError:
				pass
	return r

    def reg_val_list(s):
	v = []
	for p in s:
		if p.haslayer('ModbusADUResponse'):
			try:
				v += p['ModbusADUResponse'][1].registerValue
			except AttributeError:
				pass
	return v

In my modbus.py:
    
    class ModbusPDU06WriteSingleRegisterRequest(Packet):
    name = "Write Single Register"
    fields_desc = [XByteField("funcCode", 0x06),
                   XShortField("registerAddr", 0x0000),
                   XShortField("registerValue", 0x0000)]

    def extract_padding(self, s):
        return b"", None

    class ModbusPDU06WriteSingleRegisterResponse(Packet):
    name = "Write Single Register Response"
    fields_desc = [XByteField("funcCode", 0x06),
                   XShortField("registerAddr", 0x0000),
                   XShortField("registerValue", 0x0000)]

    class ModbusPDU06WriteSingleRegisterError(Packet):
    name = "Write Single Register Exception"
    fields_desc = [XByteField("funcCode", 0x86),
                   ByteEnumField("exceptCode", 1, _modbus_exceptions)]

Do you have any idea please ?

**Comment by guedou** [comment]
This is not a forum but a bug tracker. This does not like a Scapy issue.
