### ISSUE TITLE
Data packet is considered as Malformed

### ISSUE THREAD

**Issue by vladinko0** [secdev/scapy#2564]
#### Brief description

I am trying to send WLAN data pcaket containg zero this way:
```
dot11 = Dot11(type=2, subtype=0, addr1="01:00:00:00:00:00",
              addr2=str(RandMAC()), addr3=str(RandMAC()))
data = '0'
frame = RadioTap() / dot11 / data
sendp(frame, iface="wlan0")
```
But if I capture this packet with wireshark, I see it is Malformed Packet:

![imageedit_4_8983305168](https://user-images.githubusercontent.com/16008547/78105815-8c7c1780-73e1-11ea-841a-467f1655bb00.png)

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.7`
-   Operating System: `Ubuntu 18.04 LTS`

#### Expected result
![imageedit_2_2350298165](https://user-images.githubusercontent.com/16008547/78106365-c4d02580-73e2-11ea-8886-6ca9c8dc4b0b.png)

**Comment by guedou** [comment]
This is a bug tracker not a forum. This is unlikely a Scapy bug: you need a wireless card in monitoring mode and pretend a RadioTap() header.

**Comment by vladinko0** [comment]
But my card is in monitor mode.
