### ISSUE TITLE
External IP

### ISSUE THREAD

**Issue by habi498** [secdev/scapy#2566]
Scapy works fine.

but when it comes to same IP, it not working.

It is a linux system.i am looping through a pcap file and use sendp to send the packets. but when the destination of packets in pcap file is the 207.180.*.*. which is the external ip address of the same computer, scapy fails. 

what should i do, should i do sendp( packet, iface="lo") or 
packet[IP].dst='127.0.0.1' 
or conf.L3socket = L3RawSocket

i have been trying all this. all day along, pls help me.

**Comment by guedou** [comment]
Stop. This is harassment! Your behavior is not acceptable. Asking the same question over and over on multiple channels won't make us answer your question faster. You are wasting our time!
