### ISSUE TITLE
How can I add a field in class modbus response

### ISSUE THREAD

**Issue by salwaalem** [secdev/scapy#2569]
Hi,

I used this function published in :

class ModbusPDU03ReadHoldingRegistersResponse(Packet):
    name = "Read Holding Registers Response"
    fields_desc = [XByteField("funcCode", 0x03),
                   BitFieldLenField("byteCount", None, 8,
                                    count_of="registerVal",
                                    adjust=lambda pkt, x: x * 2),
                   FieldListField("registerVal", [0x0000],
                                  ShortField("", 0x0000),
                                  count_from=lambda pkt: pkt.byteCount)]

And I need to add another field for registerNum. I want to do something like 
FieldListField("registerNum", [0x0000],
                                  ShortField("", 0x0000),
                                  count_from=lambda ....)
But I ignore what I have to put in the ....
My goal is to get the list of the register values and number. For Values it is okay I can do a function which retrieves the liste of registerVal because this field exists already in the classe but for getting the list of registerNum I can't do because the field doesn't exist. I have to add it

Any help please ?

**Comment by guedou** [comment]
Please don't harass us on different mediums and keep in mind that is an issue tracker not a forum! You are wasting our time.

I did have time to read this issue and you already created another one on another repository https://github.com/guedou/scapy-python2.5/issues/1  !

**Comment by salwaalem** [comment]
Sorry It was not goal. It will be never occur again
