### ISSUE TITLE
Cannot defragment packet with sniff

### ISSUE THREAD

**Issue by JackKuo-tw** [secdev/scapy#2575]
#### Brief description

Cannot defragment packet with `sniff()`

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7.6
-   Operating System:  macOS 10.15.4

#### How to reproduce

`pkts = sniff(offline="./post.pcap", session=TCPSession)`

#### Actual result

Not defragment the packets.

#### Expected result

It should defragment the packets.

#### Related resources

- [The problem pcap file](https://www.dropbox.com/s/cepr8sqysmg5u2r/post.pcap?dl=0)

**Comment by guedou** [comment]
The `sniff()` function returns packets. You can use the `defragment()` must to defragment the packets that you need.

**Comment by JackKuo-tw** [comment]
Well... 
In `_defrag_logic()`, I found that `defrag` and `missfrag` are empty with my pcap file.
Perhaps, I miss something essential.

```python
pkts = sniff(offline="./post.pcap", session=TCPSession)
a = defragment(pkts)
print(a[0].payload)
```
