### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by j0ck3r2004** [secdev/scapy#2583]
Hey guys,
i just started using scapy to capture DNS packets.I use `pkt=sniff(iface='lan',filter='version 4 and port 53',prn=dnshandler`.I am using version 4 as a filter because i dont want the ip's in 6 version but i cannot get any DNS layer when i am using this filter.When i just close the IPv6 prototol it work fine without the version filter. Please help me, i am thinking and trying so hard but i cant find nothing

**Comment by guedou** [comment]
This is not a forum but a bug tracker. Please ask your question on gitter instead.

**Comment by j0ck3r2004** [comment]
@guedou Thank you
