### ISSUE TITLE
What is the upper bound of sendpfast's rate? Why the delay occur?

### ISSUE THREAD

**Issue by caopeirui** [secdev/scapy#2587]
We want to control traffic rate as precisely as possible.  The code is shown below.
```
    pkt_list = []
    for i in range(2000):
        message = str(time.time()) + ',' + src_ip + ',' + dst_ip + ',' + flag + ','
        message = message.ljust(1472, 'f')
        tmp_pkt = pkt / message
        pkt_list.append(tmp_pkt)

    # sendpfast(pkt_list, pps=2000)
    sendpfast(pkt_list, mbps=0.8)
```
Before sending packets, we added the timestamp flag into packets' message. 
When receiving packets by sniff, we also added the timestamp flag into logfile.
We discovered that the difference between the two timestamps in every packet is too large.

What is the upper bound of sendpfast's rate? Why the delay occur?

**Comment by p-l-** [comment]
Hi,

The issues should be used to track issues or request new features. You may want to ask your question on gitter.

Thanks!
