### ISSUE TITLE
netstat route information parsing error in FreeBSD

### ISSUE THREAD

**Issue by ahsanbarkati** [secdev/scapy#2591]
* Brief Information
The output of FreeBSD-head for the utility netstat has changed. The column names for the command `netstat -rnW` has been altered which causes scapy to unable to parse it. This needs to be fixed on either the FreeBSD end or in scapy.

* How to reproduce
The output of the function read_routes()  in /usr/local/lib/python3.7/site-packages/scapy/arch/unix.py should be
[(0, 0, '172.16.2.1', 'vtnet0', '172.16.2.42', 1), (2130706433, 4294967295, '0.0.0.0', 'lo0', '127.0.0.1', 1), (2886730240, 4294967040, '0.0.0.0', 'vtnet0', '172.16.2.42', 1), (2886730282, 4294967295, '0.0.0.0', 'lo0', '127.0.0.1', 1)] 

for the following routing table.
```
Routing tables
Internet:
Destination        Gateway            Flags       Use    Mtu      Netif Expire
default            172.16.2.1         UGS      459207   1500     vtnet0
127.0.0.1          link#2             UH          332  16384        lo0
172.16.2.0/24      link#1             U           216   1500     vtnet0
172.16.2.42        link#1             UHS           0  16384        lo0
```
but it comes out to be [(0, 0, '172.16.2.1', '1500', '0.0.0.0', 1), (2130706433, 4294967295, '0.0.0.0', '16384', '0.0.0.0', 1), (2886730240, 4294967040, '0.0.0.0', '1500', '0.0.0.0', 1), (2886730282, 4294967295, '0.0.0.0', '16384', '0.0.0.0', 1)]

This can be easily reproduced by running the above function in the latest version of freebsd

The name of the interface is replaced by the MTU value.

**Comment by guedou** [comment]
Please use the issue template. We did not write it for you to ignore.

**Comment by guedou** [comment]
It seems that this issue is not present in master. Please update the ticket with relevant information if not correct.
