### ISSUE TITLE
No Module Named scapy.all

### ISSUE THREAD

**Issue by gfleetwood** [secdev/scapy#2599]
I'm on Ubuntu 18.04 using Python 3.6.10 in a conda virtual enviroment and installed scapy 2.4.3. My goal is  to detect a button press from an Amazon Dash button. This is my script:

```
from scapy.all import *

def detect_button(pkt):
    if pkt.haslayer(DHCP) and pkt[Ether].src == "MAC_ADDRESS":
            print("Button Press Detected")

sniff(prn = detect_button, filter = "(udp and (port 67 or 68))", store = 0)
```
When I do `sudo python script.py` I get the error:

```
Traceback (most recent call last):
  File "script.py", line 40, in <module>
    from scapy.all import *
ImportError: No module named scapy.all
```
I tried both by installing scapy with pip and with conda. Nothing worked.

**Comment by guedou** [comment]
This does not look like a Scapy issue. Please ask you question on gitter instead.

**Comment by im-high** [comment]
Even i have faced same problem while creating a network scanning tool in Kali  (ImportError: No module named scapy.all)

**SOLUTION:**
 Install python 3.8 
Open terminal
Pip install scapy 

![4705D398-E242-4F9F-860B-08B332FADDD7](https://user-images.githubusercontent.com/74088194/98433751-04d15680-20f0-11eb-8945-01e1f9d14f1e.jpeg)
