### ISSUE TITLE
Homeplug-AV - HPtype Little Endian instead of Big Endian

### ISSUE THREAD

**Issue by wastene** [secdev/scapy#2606]
Hi, 

I don't now the exact specifications for the homeplug-av protocol, but should the HPtype at HomePlug-AV not be Little Endian instead of Big-Endian?

**Actual results:**
HPtype = 0x00A0

**Expected results:**
HPtype = 0xA000

**Suggested solution:**
I changed following code snippet (scapy/contrib/homeplugav.py) in class MACManagementHeader from:
```
fields_desc = [ByteEnumField("version", 0, HPAVversionList),
                   EnumField("HPtype", 0xA000, HPAVTypeList, "<H")]
```

to:
```
fields_desc = [ByteEnumField("version", 0, HPAVversionList),
                   EnumField("HPtype", 0xA000, HPAVTypeList, "H")]
```
This change fixes it for me and the homeplug packets are now recognized by scapy.

(Just changes "<H" to "H" - And just for info, I don't know what that "<H" or "H" mean. This was the first thing I changed and it was working :D).

**Comment by guedou** [comment]
Invoking @FlUxIuS !

**Comment by wastene** [comment]
Sorry was my fault. Was using an false implementation. Other implementation was sending in Little Endian instead of Big Endian.
