### ISSUE TITLE
Instantiation of packet with another packet not working

### ISSUE THREAD

**Issue by lidllohntsich** [secdev/scapy#2609]
tested with Python2.7
scapy version: 2.4.3 dev566

When a packet is instantiated with another packet, the packet can not be built.
example to reproduce the fault:
`p=IPerror(IP())`

What happens if the packet is built:
1. IP() is built first; build of IP() works fine
2. when scapy tries to build the IPerror() layer via the `Packet.__init__()`, scapy detects that the needed information is to be fetched from a packet (i.e. `_pkt` contains the previously generated IP() packet).
3. `Packet.dissect(_pkt)` is triggered and fails, as `Packet.dissect()` can only handle strings or bytes (Python3) respectively

General comment:
this handling is not covered via the regression.uts

**Comment by gpotter2** [comment]
I don't know where you've read that this should work, but it shouldn't.
You would rather
```
p = IP(bytes(IPerror()))
```

**Comment by lidllohntsich** [comment]
At least it was working in earlier versions. e.g. 2.4.3.dev241

**Comment by gpotter2** [comment]
I see what you mean. This was a side effect of us supporting string on Python 3.

You used to be able to do `IP("blablabla")` on Python 3, which makes no sense (you should to `IP(b"blablabla")`). This conversion was a waste of processing time so it was removed.

**Comment by lidllohntsich** [comment]
sorry to come back again:
The point is not the string, the point is the following:
`P=IPerror(IP())`
here IPerror accepted an instance of scapy.layers.init.IP

IMHO i think it would be nice to support such an interface.
Think about the situation that you sniff a packet and you want to return an ICMP with 'destination unreachable' including the IPerror(). The IPerror() should contain a copy of the sniffed packet's IP layer. The only thing you had to do to support this mechanism is to provide a python version specific cast to str/bytes as indicated in my original post
