### ISSUE TITLE
Sessions can crash Scapy

### ISSUE THREAD

**Issue by py2010** [secdev/scapy#2616]
load_layer("http")
python3.* 
scapy 2.4.3
scapy.sessions.StringBuffer.append()
https://github.com/secdev/scapy/blob/master/scapy/sessions.py
line 148:
`            self.content += b"\x00" * (seq - self.content_len + data_len)`
seq = 800MB ~ 2GB

**Packet Loss** (reduce, conf.use_pcap = True)
scapy.sessions.StringBuffer._process_packet()
_20 minutes_  metadata["tcp_end"] = False

**Comment by py2010** [comment]
**metadata[relative_seq]** ??!!
```
{'tcp_end': True, 'detect_unknown': False, 'pay_class': <class 'scapy.layers.http.HTTP'>, 'relative_seq': 3796913349, 'detect_end': <function HTTP.tcp_reassemble.<locals>.<lambda> at 0x7f66a54b6268>}
{'tcp_end': True, 'detect_unknown': False, 'pay_class': <class 'scapy.layers.http.HTTP'>, 'relative_seq': 1403028956, 'detect_end': <function HTTP.tcp_reassemble.<locals>.<lambda> at 0x7f66a54b6e18>}
{'tcp_end': True, 'detect_unknown': False, 'pay_class': <class 'scapy.layers.http.HTTP'>, 'relative_seq': 2424758834, 'detect_end': <function HTTP.tcp_reassemble.<locals>.<lambda> at 0x7f66a541e048>}
...
```

**Comment by py2010** [comment]
self.tcp_frags[ident]
**4 ip**
```
                 https                 4 ip    http (scapt)
Browser Client ========>> Nginx ==>> Balancer =============>> WebServer

```

**Comment by guedou** [comment]
I don't understand the issue, neither how we can reproduce it. Could you share an example?

**Comment by py2010** [comment]
rewrite
scapy.sessions.StringBuffer.append()
scapy.sessions.StringBuffer._process_packet()
I solved it,
thank you

**Comment by thelittleRoru** [comment]
How did you solve it? 
I encounterd the same problem, is it a bug of scapy? 
Can you share the code you rewrited?
Thank you!
