### ISSUE TITLE
gdk_cursor_new_for_display: crash with simple script

### ISSUE THREAD

**Issue by Obyka** [secdev/scapy#2617]
#### Brief description

When starting a simple script importing latest scapy version on my Raspberry Pi 3, it crashes.

#### Environment
I'm connecting to my raspberry pi via SSH

-   Scapy version: `2.4.3`
-   Python version: `3.7.3`
-   Operating System: `Linux raspberrypi 4.19.97-v7l+`

#### How to reproduce

Here is the script I'm trying to launch

```python
import argparse
from scapy.all import *
import datetime
import time

parser = argparse.ArgumentParser(description="Scan for probes request")
parser.add_argument('-i', help="interface wifi en monitor")
args = parser.parse_args()
```

#### Actual result
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Impossible de se connecter : Connection refused

(scanProb.py:959): Gdk-CRITICAL **: 15:44:36.081: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(scanProb.py:959): Gdk-CRITICAL **: 15:44:36.084: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
```

#### Expected result

No error

**Comment by gpotter2** [comment]
Scapy has no GUI. This is unrelated

**Comment by Obyka** [comment]
> 
> 
> Scapy has no GUI. This is unrelated

I certainly was aware. But as soon as I comment scappy importation, the code does run.

Would you have any guidance for me ?

**Comment by gpotter2** [comment]
Have you installed a special version of scapy?
`scanprob.py:959` is not a file i'm Scapy.
Without more infos it's hard to see what's really going on.
