### ISSUE TITLE
Why do I have to place a delay in my Python code for SYN scan to work properly

### ISSUE THREAD

**Issue by xyplex** [secdev/scapy#2618]
I am learning to write a SYN Scanner in Python and I am farly new to Python language. I am using Scapy module and sr1 command to send the packet but I have written this code using Python Socket module and I have the same issue.

The code will send packets out with packet flags set to 'S'. If there is no packet response then do nothing and continue the 'For' loop and take in the next port number to scan from list in variable List "common_ports".

If a packet response is received I check for TCP flags is set to "SA" and if so print "Port is Open", then the Open port is stored in List "open-ports".

My Issue when running the program it will find the first Open port 80 and displays it but will not find any consecutive Open ports. When I ran this through Pycharm debugger it worked fine and found port 80 as well port 443.
After trying to figure this out I added a time.sleep(7) statement and all works fine but if I change this 7 to a lower number the code does not find the second port number 443.

My question is why do I have to add a delay in the program to get it to work? (7 second delay is excessive). I have noticed that some other sites I can reduce the delay to say 3 and the code will work.

`# -*- coding: utf-8 -*-
"""
Created on Mon Apr 13 23:08:11 2020

@author: xyplex

"""
import logging
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)

from scapy.all import *
import time

host_address = "www.hackthissite.org"
open_ports = []

common_ports = [23, 80, 443]

print('Scanning '+host_address+' for open TCP ports')

start_time = time.time()

for x in common_ports:
    packet = IP(dst=host_address)/TCP(dport=x, flags='S')
    response = sr1(packet,timeout=0.5,verbose=0)
    if response != None:
        if TCP in response and response[TCP].flags == 'SA':
            print('\nPort '+str(x)+' is open')
            open_ports.append(x)
            sr1(IP(dst=host_address)/TCP(dport=response.sport,flags='R'),timeout=0.5,verbose=0)
            **time.sleep(7)**

print('\nScan is Complete !!!!!\n')

if open_ports:
    print("\n\nOpen Ports Found: -----> ", sorted(open_ports))
else:
    print("Sorry, No open ports found.!!!")

print('\nTotal Time to Execute = %s' % (time.time() - start_time) + ' Seconds')

`

**Comment by guedou** [comment]
Please ask your question on gitter instead. This is a bug tracker not a forum.
