### ISSUE TITLE
Not support handle AVP for L2TP protocol

### ISSUE THREAD

**Issue by docker0406** [secdev/scapy#2623]
#### Things to consider

1.  Please check that you are using the latest scapy version, e.g. installed via:

    `pip install --upgrade git+git://github.com/secdev/scapy`

2.  If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: <https://gitter.im/secdev/scapy>

3.  Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: <https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde>

#### Environment

-   Scapy version: `Version git-archive.devfed58ff0ab`
-   Python version: `3.7.7`
-   Operating System: `ubuntu 14.04`

#### How to reproduce
[l2tp.zip](https://github.com/secdev/scapy/files/4568105/l2tp.zip)

1. pkt=rdpcap('l2tp.pcap')
2. pkt[0].show()
3. check AVP of L2TP in output

#### Actual result

###[ Ethernet ]###
  dst= 00:0c:29:8e:b3:28
  src= 00:17:10:10:c7:d7
  type= IPv4
###[ IP ]###
     version= 4
     ihl= 5
     tos= 0xc0
     len= 124
     id= 218
     flags=
     frag= 0
     ttl= 64
     proto= udp
     chksum= 0xc504
     src= 200.90.22.1
     dst= 192.168.20.207
     \options\
###[ UDP ]###
        sport= l2f
        dport= l2f
        len= 104
        chksum= 0x1a7c
###[ L2TP ]###
           hdr= sequence+length+control
           version= L2TPv2
           len= 96
           tunnel_id= 0
           session_id= 0
           ns= 0
           nr= 0
###[ PPP Link Layer ]###
              proto= 32776
###[ Raw ]###
                 load= '\x00\x00\x00\x00\x00\x01\x80\r\x00\x00\x00\x07client0\x80\x0f\x00\x00\x00\x08CASA vBNG\x80\x08\x00\x00\x00\x02\x01\x00\x80\n\x00\x00\x00\x03\x00\x00\x00\x03\x80\x08\x00\x00\x00\t\x00\x01\x80\x16\x00\x00\x00\x0b\xa7\xde\x83J$\x8e\xdf6#\xf0g\xa9\x9e\xad6y'

>>>

#### Expected result
support AVP,like wireshark tools

Layer 2 Tunneling Protocol
    Packet Type: Control Message Tunnel Id=0 Session Id=0
    Length: 96
    Tunnel ID: 0
    Session ID: 0
    Ns: 0
    Nr: 0
    Control Message AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0000 1000 = Length: 8
        Vendor ID: Reserved (0)
        AVP Type: Control Message (0)
        Message Type: Start_Control_Request (1)
    Host Name AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0000 1101 = Length: 13
        Vendor ID: Reserved (0)
        AVP Type: Host Name (7)
        Host Name: client0
    Vendor Name AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0000 1111 = Length: 15
        Vendor ID: Reserved (0)
        AVP Type: Vendor Name (8)
        Vendor Name: CASA vBNG
    Protocol Version AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0000 1000 = Length: 8
        Vendor ID: Reserved (0)
        AVP Type: Protocol Version (2)
        Version: 1
        Revision: 0
    Framing Capabilities AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0000 1010 = Length: 10
        Vendor ID: Reserved (0)
        AVP Type: Framing Capabilities (3)
        .... .... .... .... .... .... .... ..1. = Async Framing Supported: True
        .... .... .... .... .... .... .... ...1 = Sync Framing Supported: True
    Assigned Tunnel ID AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0000 1000 = Length: 8
        Vendor ID: Reserved (0)
        AVP Type: Assigned Tunnel ID (9)
        Assigned Tunnel ID: 1
    Challenge AVP
        1... .... .... .... = Mandatory: True
        .0.. .... .... .... = Hidden: False
        .... ..00 0001 0110 = Length: 22
        Vendor ID: Reserved (0)
        AVP Type: Challenge (11)
        CHAP Challenge: a7de834a248edf3623f067a99ead3679

**Comment by gpotter2** [comment]
This protocol isn't implemented. Feel free to contribute !
We won't make it for your but will gladly review any PR you can provide 😄
