### ISSUE TITLE
Specify interface for http_request()

### ISSUE THREAD

**Issue by GrigorDimitrov** [secdev/scapy#2634]
#### Brief description

http_request function does not take interface argument. I cannot use this function because I have two interfaces on my VM.

#### How to reproduce
Kali Linux
eth0 - Host Only
eth1 - NAT

#### Related resources
https://scapy.readthedocs.io/en/latest/api/scapy.layers.http.html#scapy.layers.http.http_request

**Comment by GrigorDimitrov** [comment]
![image](https://user-images.githubusercontent.com/32209024/81472852-5d33a400-91f2-11ea-899d-fa399bbcff41.png)
I think problem is that after the initial SYN, http_request() is sniffing on wrong interface.
Code:
def sql(dest_ip):
    load_layer("http")
    ans = http_request(dest_ip, "/ insert into ")

**Comment by gpotter2** [comment]
Hi & thanks for the suggestion.
What do you think of https://github.com/secdev/scapy/pull/2650 ? thanks
