### ISSUE TITLE
How to get information about parameters

### ISSUE THREAD

**Issue by alexrebell** [secdev/scapy#2643]
Good afternoon. Please tell me how I can get information on each parameter of a package? For example, I look at what parameters the IP packet has:
`ls(IP)`
outcome:
`version    : BitField (4 bits)                   = (4)`
`ihl        : BitField (4 bits)                   = (None)`
`tos        : XByteField                          = (0)`
`len        : ShortField                          = (None)`
`id         : ShortField                          = (1)`
`flags      : FlagsField (3 bits)                 = (<Flag 0 ()>)`
`frag       : BitField (13 bits)                  = (0)`
`ttl        : ByteField                           = (64)`
`proto      : ByteEnumField                       = (0)`
`chksum     : XShortField                         = (None)`
`src        : SourceIPField                       = (None)`
`dst        : DestIPField                         = (None)`
`options    : PacketListField                     = ([])`

My question is, how can I get information about the parameter ` ihl, tos, if,` and so on... i.e., what can I specify in these parameters, what values a particular parameter supports?
Thank you very much.

**Comment by gpotter2** [comment]
Hi, please note that this is a bug tracker and not a forum.
Moreover, this is greatly covered in the doc: http://scapy.readthedocs.io/
