### ISSUE TITLE
Pickling corrupts timestamp (pkt.time) and order of packets

### ISSUE THREAD

**Issue by TheOkeland** [secdev/scapy#2648]
#### Brief description

Hello, I encountered strange behavior while multiprocessing packets. As dar as I understood the packet's time field, its value is either the receive-time or the capture-time. When reading a pap-file, this holds true. However, after pickling and unpicking a packet, the current time is assigned to the packet and the original timestamp is lost.

Due to multiprocessing, not only the absolute time is corrupted, but depending on scheduling differences, the order of the complete capture is lost and might differ on each execution.

#### Environment

-   Scapy version: `2.4.3.dev554`
-   Python version: `3.7.7`
-   Operating System: `macOS 10.15.4`

#### How to reproduce

1. Read pcap file
2. Use pickling (e.g., via pool.imap) to transfer packet to a different process
3. Compare original and new pkt.time

#### Actual result

The unpickled packet's `.time` field has the current time (time.time() - timestamps)

#### Expected result

The original timestamp from the capture is displayed on calling pkt.time

**Comment by gpotter2** [comment]
Hi, you're pretty right: pickle support isn't great.
We should add the storage of time, wirelen...
