### ISSUE TITLE
Still have PicklingError issue when save_session

### ISSUE THREAD

**Issue by enzochiau** [secdev/scapy#265]
Try to follow the tutorial "Quick Demo" and has the same issue mentioned [here](https://bitbucket.org/secdev/scapy/issues/213/session-save-does-not-work) and [here](https://bitbucket.org/secdev/scapy/issues/340/cannot-save-session-using-s-option).

Error Message:

```
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup builtin.function failed
```

Env:
Python: 2.7.5
scapy:   2.3.2

**Comment by kamakazikamikaze** [comment]
Also seeing this. At first I thought it was from trying to save modules:

    ERROR: [copy] (<type 'module'>) can't be saved.
    ERROR: [binascii] (<type 'module'>) can't be saved.
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/scapy/main.py", line 129, in save_session
    cPickle.dump(to_be_saved, f, pickleProto)
    PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

but after removing them with `del()`, it still has issues.

    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/scapy/main.py", line 129, in save_session
    cPickle.dump(to_be_saved, f, pickleProto)
    PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

Python 2.7.10 (via `brew`)
OS X Yosemite 10.11.6
Scapy v2.3.2

**Comment by guedou** [comment]
I took my a while to come with a fix. Could you try PR #284  ?
Thanks.
