### ISSUE TITLE
npcap does not work well .

### ISSUE THREAD

**Issue by kerwinxu** [secdev/scapy#2652]
#### Things to consider

win10 , anaconda, python3 , pip install scapy ， or conda install scapy

winpacp : work well 
npcap : does not work 

for example :
ans,unans=srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst="192.168.0.0/24"),timeout=2)
winpcap  : 
>>> ans,unans=srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst="192.168.0.0/24"),ti ...: meout=2)
Begin emission:
........................................................................*..............................................................................................................................................................................Finished sending 256 packets..
............
Received 260 packets, got 1 answers, remaining 255 packets

but npcap  : 

Begin emission:
Finished sending 256 packets.

Received 0 packets, got 0 answers, remaining 256 packets

1.  Please check that you are using the latest scapy version, e.g. installed via:

    `pip install --upgrade git+git://github.com/secdev/scapy`

2.  If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: <https://gitter.im/secdev/scapy>

3.  Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: <https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde>

#### Environment

-   Scapy version: `scapy version and/or commit-hash`
-   Python version: `e.g. 3.5`
-   Operating System: `e.g. Minix 3.4`

**Comment by gpotter2** [comment]
Make sure you properly installed npcap, that it's compatible with your OS (try using wireshark) and that you properly uninstalled winpcap.

This is very likely not an issue with Scapy
