### ISSUE TITLE
scapy_iface_getmacbyip_get_if_hwaddr_errror

### ISSUE THREAD

**Issue by Ymigmli** [secdev/scapy#2654]
![image](https://user-images.githubusercontent.com/47731874/82306326-7e19a780-99f1-11ea-828a-2d7dc9197108.png)

![image](https://user-images.githubusercontent.com/47731874/82306338-82de5b80-99f1-11ea-8777-c4aa77c281f1.png)

![image](https://user-images.githubusercontent.com/47731874/82306362-8d005a00-99f1-11ea-8aba-37c8c36e8647.png)

![image](https://user-images.githubusercontent.com/47731874/82306376-912c7780-99f1-11ea-8bdb-2581125af700.png)

![image](https://user-images.githubusercontent.com/47731874/82306398-98538580-99f1-11ea-8a33-2e5dee264357.png)

pip install,python 2.7.5
for windows 10,Normal before patch update，abnormal after update，iface can't find interface
Linux,mac normal

**Comment by gpotter2** [comment]
This is unsalvageable as is. Please fill the issue template and use understandable english.

**Comment by Ymigmli** [comment]
emmm...sorry
