### ISSUE TITLE
modbuspdu01readcoilsresponse error

### ISSUE THREAD

**Issue by salwaalem** [secdev/scapy#2655]
found a problem with function 01 of modbus. I want to extract the value of the coil/register according to the function number from a pcap file. It works for function 3 but not for func 1: 

Here is my function

```
def reg_val_list(s):
    v = []
    for p in s:
        if p.haslayer('ModbusADUResponse'):
            try:
                if p['ModbusADUResponse'][1].funcCode == 6:
                    a = p['ModbusADUResponse'][1].registerValue
                    v.append(p['ModbusADUResponse'][1].registerValue)
                elif p['ModbusADUResponse'][1].funcCode == 5:
                    v.append(p['ModbusADUResponse'][1].outputValue)
                elif p['ModbusADUResponse'][1].funcCode == 1:
                    v += p['ModbusADUResponse'][1].coilStatus
                elif p['ModbusADUResponse'][1].funcCode == 3:
                    v.extend(p['ModbusADUResponse'][1].registerVal)
                else:
                    v += p['ModbusADUResponse'][1].registerVal
            except AttributeError:
                pass
        elif p.haslayer('ModbusADURequest'):
            try:
                a = p['ModbusADURequest'][1]
                if p['ModbusADURequest'][1].funcCode in [15, 16]:
                     v += p['ModbusADURequest'][1].outputsValue
            except AttributeError:
                pass
    return v
```

**Comment by p-l-** [comment]
Could you please follow the issue template **and** provide a PCAP sample so that we can have a chance to understand the problem?

**Comment by salwaalem** [comment]
Instead of getting bits in base 8 we get a decimal number when I use this function in my parser (see picture of excel)

![image](https://user-images.githubusercontent.com/40567501/82674808-2757dc00-9c44-11ea-97a6-b670d112b7c4.png)

![image](https://user-images.githubusercontent.com/40567501/82674765-17d89300-9c44-11ea-9cee-eadebf3d9107.png)

![image](https://user-images.githubusercontent.com/40567501/82675257-d4caef80-9c44-11ea-9ad5-5b437b31744c.png)

Maybe instead of using ByteField in the modbuspdu01readcoilsresponse we have to use BitField or Bitarray but I'm not sure
