### ISSUE TITLE
Instable label for UTscapy?

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2659]
I discovered, that some unit tests are frequently failing on the continuous integration systems. Some of this test are related to automotive stuff, and I'm really sorry about that. But I also see tests from TLS or Regression with network access, which fail frequently.

Do you think it makes sense to mark these tests as instable and implement a feature in UTscapy to allow failures of this tests? Or is this approach leading to a worse code and test quality?

**Comment by gpotter2** [comment]
> Or is this approach leading to a worse code and test quality?

There shouldn't be unreliable tests. The few unreliable tests we do have are tests that access remote servers. In the case of automotive tests which are fully offline, it is certain that with proper timings / locks, it is possible to make them reliable.
Allowing unreliable tests would burst our code coverage..

**Comment by polybassa** [comment]
Alright. Then I drop this idea. I will keep an eye on failing tests and try to improve them. thanks for your reply.
