### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by jcmartins** [secdev/scapy#266]
I'm run archlinux and
Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602] on linux

collecting scapy
  Using cached scapy-2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-gnjx2y32/scapy/setup.py", line 35
        os.chmod(fname,0755)
                          ^
    SyntaxError: invalid token

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-gnjx2y32/scapy/

**Comment by robin-jarry** [comment]
scapy does not support python 3. You should use python 2.

**Comment by shyamabhuvanendran** [comment]
pip3 install scapy-python3

This worked for me!

**Comment by guedou** [comment]
That’s a silly fix! scapy-python3 is a different project ...

Please try with pip install —pre scapy instead
