### ISSUE TITLE
'GDK_IS_DISPLAY (display)' failed in python3

### ISSUE THREAD

**Issue by ankycooper** [secdev/scapy#2666]
GDK error when using python3 and importing scapy, works with python2.7

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.8`
-   Operating System: `kali 2020.2`

#### How to reproduce
in python3 import scapy
`import scapy.all`

#### Actual result

`Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(myfile.py:965): Gdk-CRITICAL **: 05:48:12.106: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
`
#### Expected result

No GDK error

**Comment by guedou** [comment]
Sorry I could not reproduce the issue.

**Comment by gpotter2** [comment]
See https://github.com/BVLC/caffe/issues/861#issuecomment-70124809
