### ISSUE TITLE
Dessecting SD message from bytearray -> cannot see all entries in the entry_array

### ISSUE THREAD

**Issue by HousInfo** [secdev/scapy#2677]
```
## SCAPY from scapy.all import * 
from scapy.contrib.automotive.someip import SOMEIP 
from scapy.contrib.automotive.someip_sd import *

# SD message with multiple entries (from wireshark)
localPayload = [0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x06, 0x00, 0x00, 0x10, 0xb0, 0x91, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x30, 0x21, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0xd5, 0x01, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0xd5, 0x38, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x33, 0x91, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x33, 0x91, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x02, 0x06, 0x00, 0x00, 0x10, 0xe2, 0xb5, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x20, 0x35, 0x61, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x02, 0x00, 0x10, 0x35, 0x48, 0x00, 0x02, 0x02, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x31, 0x20, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x12, 0x78, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x82, 0xb6, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x81, 0xb8, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x02, 0x00, 0x10, 0x75, 0x42, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x30, 0x1e, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x24, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7, 0x10, 0x00, 0x11, 0xfe, 0x0d, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7, 0x10, 0x00, 0x11, 0x77, 0x1b, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7, 0x10, 0x00, 0x11, 0xf5, 0xbd]

my_sd = SD(bytearray(localPayload))
for sd_entry in my_sd.getfieldval("entry_array"):
      print(sd_entry.getfieldval('srv_id'))
      print(repr(sd_entry))
```

**Comment by HousInfo** [comment]
- we cannot iterate the entry_array (len == 1) (or didn't I get it?)
- the first block 
![image](https://user-images.githubusercontent.com/8048421/84454445-d479af00-ac5a-11ea-8e22-69256529b579.png) looks ok if we ignore the fact that there is no minor_ver
- All values in next ###[ Service Entry ]### are not correct

**Comment by HousInfo** [comment]
Hi @polybassa,
Thanks for your help, please find the wireshark screenshot
![SD_multiple_entries_2020-06-15 105349](https://user-images.githubusercontent.com/8048421/84638152-e1b2ca00-aef6-11ea-91d1-f56ef6443d85.png)

`
>>> from scapy.all import *
>>> from scapy.contrib.automotive.someip import SOMEIP
>>> from scapy.contrib.automotive.someip_sd import *
>>> my_payload = [0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x60, 0x01, 0x00, 0x00, 0x10, 0xb0, 0x91, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x10, 0x30, 0x58, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x10, 0x31, 0x20, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x10, 0x81, 0xb8, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x10, 0x75, 0x42, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x10, 0x30, 0x1e, 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7, 0x5d, 0x00, 0x11, 0x77, 0x25]
>>> my_sd = SD(bytearray(my_payload))
>>> my_sd.show()
###[ SD ]###
  flags     = 64
  res       = 0x0
  len_entry_array= 96
  \entry_array\
   |###[ _SDEntry ]###
   |  type      = 1
   |  index_1   = 0
   |  index_2   = 0
   |  n_opt_1   = 1
   |  n_opt_2   = 0
   |  srv_id    = 45201
   |  inst_id   = 1
   |  major_ver = 1
   |  ttl       = 0x3
   |###[ Service Entry ]###
   |     type      = 0
   |     index_1   = 0
   |     index_2   = 0
   |     n_opt_1   = 0
   |     n_opt_2   = 0
   |     srv_id    = 256
   |     inst_id   = 16
   |     major_ver = 48
   |     ttl       = 0x580001
   |     minor_ver = 16777219
   |###[ Service Entry ]###
   |        type      = 0
   |        index_1   = 0
   |        index_2   = 0
   |        n_opt_1   = 0
   |        n_opt_2   = 0
   |        srv_id    = 256
   |        inst_id   = 16
   |        major_ver = 49
   |        ttl       = 0x200001
   |        minor_ver = 16777219
   |###[ Service Entry ]###
   |           type      = 0
   |           index_1   = 0
   |           index_2   = 0
   |           n_opt_1   = 0
   |           n_opt_2   = 0
   |           srv_id    = 256
   |           inst_id   = 16
   |           major_ver = 129
   |           ttl       = 0xb80001
   |           minor_ver = 16777219
   |###[ Service Entry ]###
   |              type      = 0
   |              index_1   = 0
   |              index_2   = 0
   |              n_opt_1   = 0
   |              n_opt_2   = 0
   |              srv_id    = 256
   |              inst_id   = 16
   |              major_ver = 117
   |              ttl       = 0x420001
   |              minor_ver = 16777219
   |###[ Service Entry ]###
   |                 type      = 0
   |                 index_1   = 0
   |                 index_2   = 0
   |                 n_opt_1   = 0
   |                 n_opt_2   = 0
   |                 srv_id    = 256
   |                 inst_id   = 16
   |                 major_ver = 48
   |                 ttl       = 0x1e0001
   |                 minor_ver = 16777219
   |###[ Service Entry ]###
   |                    type      = 0
   |                    index_1   = 0
   |                    index_2   = 0
   |                    n_opt_1   = 0
   |                    n_opt_2   = 0
   |                    srv_id    = 0
   |                    inst_id   = 0
   |                    major_ver = 0
   |                    ttl       = 0x0
   |                    minor_ver = 0
  len_option_array= 12
  \option_array\
   |###[ _SDOption ]###
   |###[ IP4 EndPoint Option ]###
   |     len       = 9
   |     type      = 4
   |     res_hdr   = 0
   |     addr      = 160.48.199.93
   |     res_tail  = 0
   |     l4_proto  = UDP
   |     port      = 30501

>>> print(my_sd.getfieldval("entry_array"))
[<_SDEntry  type=1 index_1=0 index_2=0 n_opt_1=1 n_opt_2=0 srv_id=45201 inst_id=1 major_ver=1 ttl=0x3 |<SDEntry_Service  type=0 index_1=0 index_2=0 n_opt_1=0 n_opt_2=0 srv_id=256 inst_id=16 major_ver=48 ttl=0x580001 minor_ver=16777219 |<SDEntry_Service  type=0 index_1=0 index_2=0 n_opt_1=0 n_opt_2=0 srv_id=256 inst_id=16 major_ver=49 ttl=0x200001 minor_ver=16777219 |<SDEntry_Service  type=0 index_1=0 index_2=0 n_opt_1=0 n_opt_2=0 srv_id=256 inst_id=16 major_ver=129 ttl=0xb80001 minor_ver=16777219 |<SDEntry_Service  type=0 index_1=0 index_2=0 n_opt_1=0 n_opt_2=0 srv_id=256 inst_id=16 major_ver=117 ttl=0x420001 minor_ver=16777219 |<SDEntry_Service  type=0 index_1=0 index_2=0 n_opt_1=0 n_opt_2=0 srv_id=256 inst_id=16 major_ver=48 ttl=0x1e0001 minor_ver=16777219 |<SDEntry_Service  type=0 index_1=0 index_2=0 n_opt_1=0 n_opt_2=0 |>>>>>>>]
>>> print(len(my_sd.getfieldval("entry_array")))
1
`

**Comment by polybassa** [comment]
Thanks for the screenshot, I will look into it
--

**Comment by polybassa** [comment]
It looks like the first block is interpreted with the wrong class

**Comment by polybassa** [comment]
@HousInfo Can you please check the current version of SOMEIP (on github) against your case?
I think your issue has been closed already in the past, but the latest release still has the old code.

here is my output:
```
>>> load_contrib("automotive.someip")                                                                  
>>> ## SCAPY from scapy.all import *  
...: from scapy.contrib.automotive.someip import SOMEIP  
...:  
...: # SD message with multiple entries (from wireshark) 
...: localPayload = [0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x06, 0x00, 0x00, 0x10, 0xb0, 0x91
...: , 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x30, 0x21, 
...: 0x00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0xd5, 0x01, 0x
...: 00, 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0xd5, 0x38, 0x00
...: , 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x33, 0x91, 0x00, 
...: 0x01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x33, 0x91, 0x00, 0x
...: 01, 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x02, 0x06, 0x00, 0x00, 0x10, 0xe2, 0xb5, 0x00, 0x01
...: , 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x20, 0x35, 0x61, 0x00, 0x01, 
...: 0x01, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x02, 0x00, 0x10, 0x35, 0x48, 0x00, 0x02, 0x
...: 02, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x31, 0x20, 0x00, 0x01, 0x01
...: , 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x12, 0x78, 0x00, 0x01, 0x01, 
...: 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x82, 0xb6, 0x00, 0x01, 0x01, 0x
...: 00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x81, 0xb8, 0x00, 0x01, 0x01, 0x00
...: , 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x02, 0x00, 0x10, 0x75, 0x42, 0x00, 0x01, 0x01, 0x00, 
...: 0x00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x06, 0x00, 0x00, 0x10, 0x30, 0x1e, 0x00, 0x01, 0x01, 0x00, 0x
...: 00, 0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x24, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7
...: , 0x10, 0x00, 0x11, 0xfe, 0x0d, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7, 0x10, 0x00, 0x11, 0x77, 
...: 0x1b, 0x00, 0x09, 0x04, 0x00, 0xa0, 0x30, 0xc7, 0x10, 0x00, 0x11, 0xf5, 0xbd] 
...:  
...: my_sd = SD(bytearray(localPayload)) 
...: for sd_entry in my_sd.getfieldval("entry_array"): 
...:       print(sd_entry.getfieldval('srv_id')) 
...:       print(repr(sd_entry)) 
...:                                                                                                   
45201
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0xb091 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
12321
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x3021 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
54529
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0xd501 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
54584
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0xd538 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
13201
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x3391 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
13201
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x3391 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x2 |>
58037
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0xe2b5 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
13665
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x2 n_opt_2=0x0 srv_id=0x3561 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
13640
<SDEntry_EventGroup  type=0x6 index_1=0x2 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x3548 inst_id=0x2 major_ver=0x2 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
12576
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x3120 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
4728
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x1278 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
33462
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x82b6 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
33208
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x81b8 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
30018
<SDEntry_EventGroup  type=0x6 index_1=0x2 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x7542 inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>
12318
<SDEntry_EventGroup  type=0x6 index_1=0x0 index_2=0x0 n_opt_1=0x1 n_opt_2=0x0 srv_id=0x301e inst_id=0x1 major_ver=0x1 ttl=0x3 res=0x0 cnt=0x0 eventgroup_id=0x1 |>

```

**Comment by HousInfo** [comment]
Thanks @polybassa, I took last SOME/IP version from master and it work fine
