### ISSUE TITLE
Inaccurate parsing of 802.11 element "RSN Information"

### ISSUE THREAD

**Issue by giladbeeri** [secdev/scapy#2683]
I'm parsing an 802.11 frame that contains some tag elements, specifically, "RSN Information" (48).

"RSN Information" is parsed with a conditional field of PMKID, but I think the condition is not accurate, and in addition, there's another field afterwards called "Group Management Cipher Suite" (4 bytes).
https://github.com/secdev/scapy/blob/master/scapy/layers/dot11.py#L880

-   Scapy version: latest (https://github.com/secdev/scapy.git@f2a111e6d4821c199a0cf5f42bc5bb5dcbe6ff04)
-   Python version: 3.8.2
-   Operating System: Ubuntu 16.04#### How to reproduce

#### Steps to Reproduce
`python -c "from scapy.all import rdpcap; f = rdpcap('scapy.pcap'); p = f[0]; beacon = p.getlayer(5); print(beacon.network_stats()['ssid'])"`

#### Actual result

(some garbage which is data from the packet)

`\xddP\xf2\x81\xa4'\xa4BT^a2/\xdd\xa0\xc6`

#### Expected result

The real SSID: `ROUTE-821E295`

![correct_ssid](https://user-images.githubusercontent.com/6613822/84741881-6285ca80-afb8-11ea-8b2e-d56f568eb3eb.png)

#### Related resources
 
The frame that reproduces the issue:

[scapy.pcap.zip](https://github.com/secdev/scapy/files/4784765/scapy.pcap.zip)

Wireshark's parsing of the RSN Information element:

![correct_rsn_info](https://user-images.githubusercontent.com/6613822/84741789-3d915780-afb8-11ea-9b0f-b4108ad4baae.png)

**Comment by guedou** [comment]
Closed by #2685

**Comment by giladbeeri** [comment]
@guedou I don't think this one should be closed. #2685 is a solution that resolves the issue of the improper SSID overriding, which is a result of this issue.
This issue, of the wrong RSN Information element parsing, is still relevant (it just won't create SSID overriding anymore, but the parsing is still wrong).
