### ISSUE TITLE
Scapy should stop parsing SSID values once it found one

### ISSUE THREAD

**Issue by giladbeeri** [secdev/scapy#2684]
As a follow up to https://github.com/secdev/scapy/issues/2683,
scapy parses the information element tags one by one, and updates the SSID every time it finds an SSID element.
But: The SSID element is always the first and should be only one instance of it per frame. So it doesn't make sense to update the SSID once it was already set.
The bug described in https://github.com/secdev/scapy/issues/2683, an incorrect parsing of an information element, resulting in a wrong SSID, could have been prevented (the SSID parsing issue, not the RSN parsing issue) if scapy wouldn't have overridden the SSID after it was set.

**Comment by guedou** [comment]
Thanks for reporting and tracking this. Could you provide a reference that states that the SSID is the first element?

**Comment by giladbeeri** [comment]
I found statements stating that the information elements are ordered by ID. Since the SSID has an ID of 0, it can be concluded that it is the first element.

1. Official, IEEE 802.11-2007 writes (page 80): "The frame body consists of the fields followed by the information elements defined for each management
frame subtype. All fields and information elements are mandatory unless stated otherwise and appear in the
specified, relative order"
1. https://dox.ipxe.org/group__ieee80211__ie.html: "Information elements are required to be sorted by ID"
1. https://www.oreilly.com/library/view/80211-wireless-networks/0596100523/ch04.html: " 802.11 mandates the order in which information elements appear, but not all elements are mandatory. This book shows all the frame building blocks in the specified order" (it later shows a table of the information elements ordered by ID).
1. https://pdfs.semanticscholar.org/23ff/53fda0a8f30564603072115bfca6cddfbedf.pdf: " Information Elements appear in a fixed relative
order and are identified by respective unique Element ID"
