### ISSUE TITLE
ZigBee traffic not properly detected

### ISSUE THREAD

**Issue by beiqil** [secdev/scapy#2689]
#### Things to consider

1.  Please check that you are using the latest scapy version, e.g. installed via:

    `pip install --upgrade git+git://github.com/secdev/scapy`

2.  If you are here to ask a question - please check previous issues and online resources, and consider using gitter instead: <https://gitter.im/secdev/scapy>

3.  Please understand that **this is not a forum** but an issue tracker. The following article explains why you should limit questions asked on Github issues: <https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde>

#### Brief description

After loaded the example ZigBee captures listed [here](https://wiki.wireshark.org/SampleCaptures) (`zigbee-join-authenticate.pcap` after gunzipping. Download listed below.) with `rdpcap()` and use the `show()` method of each packet to display the details. The ZigBee protocol did not seem to get detected properly. Instead they are being decoded as `6LoWPAN` or did not get decoded at all (stay as raw).

#### Environment

-   Scapy version: `51c6d80a6449ea3e987702bb654e8168b0334f24`
-   Python version: `3.8.3`
-   Operating System: `Fedora 32`

#### How to reproduce

```python
from scapy.all import rdpcap

pcap = rdpcap('zigbee-join-authenticate.pcap')
for p in pcap:
    p.show()
```

#### Actual result

All ZigBee packets didn't get decoded properly. Instead they are shown as 6LoWPAN or just raw despite the `layers` package does appear has ZigBee support.

#### Expected result

All ZigBee packets should be decoded properly as ZigBee traffic.

#### Related resources

PCAP: https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=zigbee-join-authenticate.pcap.gz

**Comment by guedou** [comment]
The `rdpcap()` function returns the following warnings:
```
>>> rdpcap("zigbee-join-authenticate.pcap")
WARNING: Please set conf.dot15d4_protocol to select a 802.15.4 protocol. Values must be in the list: ['sixlowpan', 'zigbee'] Defaulting to SixLoWPAN
WARNING: Please set conf.dot15d4_protocol to select a 802.15.4 protocol. Values must be in the list: ['sixlowpan', 'zigbee'] Defaulting to SixLoWPAN
WARNING: more Please set conf.dot15d4_protocol to select a 802.15.4 protocol. Values must be in the list: ['sixlowpan', 'zigbee'] Defaulting to SixLoWPAN
<zigbee-join-authenticate.pcap: TCP:0 UDP:0 ICMP:0 Other:54>
```

You shall load the pcap using:
```
>>> conf.dot15d4_protocol = "zigbee"
>>> rdpcap("zigbee-join-authenticate.pcap")
```
