### ISSUE TITLE
Scapy cannot parse vendor IE well(it can just parse the Radiotap and the 802.11 header right in some way)

### ISSUE THREAD

**Issue by AmandaYaoYao** [secdev/scapy#2693]
Here is my packet. The scapy cannot parse the probe response frame well when to parse the vendor ie. But other frame can parse well.
[test.zip](https://github.com/secdev/scapy/files/4818568/test.zip)

**Comment by guedou** [comment]
Please fill the issue template if you want us to provide an answer.
