### ISSUE TITLE
Performance Problem with (too) many file descriptors / sockets

### ISSUE THREAD

**Issue by Chamaeleon-** [secdev/scapy#2695]
`Select` can only handle 1024 file descriptors, makes 1024 sockets. With more sockets you will get an `ValueError: filedescriptor out of range in select()` in this line
https://github.com/secdev/scapy/blob/cb13a5fa19d877924826cc5bb87599978cbe57cb/scapy/arch/linux.py#L379
Since platform compatibility don't seem to be an issue here, I want to propose using `epoll` instead. 
What do you think?

**Comment by guedou** [comment]
Could you use the template issue?
