### ISSUE TITLE
`0x0807: "ed25519"` and `0x0808: "ed448" not supported?

### ISSUE THREAD

**Issue by SurienDG** [secdev/scapy#2699]
#### Brief description

Are `0x0807: "ed25519"` and `0x0808: "ed448"` not supported?

![image](https://user-images.githubusercontent.com/18398584/86325299-d2798f00-bc0d-11ea-97e5-62c63d13b39d.png)

Since, if verify is called on them the split method will fail as there is no plus in the names?

From keyexchange.py:
![image](https://user-images.githubusercontent.com/18398584/86325397-f341e480-bc0d-11ea-8bc5-02bd6e743e7d.png)

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7

**Comment by gpotter2** [comment]
Yeah i don't think they're implemented. Looks like this was copy pasted from the rfc https://tools.ietf.org/html/rfc8446

```
enum {
          /* RSASSA-PKCS1-v1_5 algorithms */
          rsa_pkcs1_sha256(0x0401),
          rsa_pkcs1_sha384(0x0501),
          rsa_pkcs1_sha512(0x0601),

          /* ECDSA algorithms */
          ecdsa_secp256r1_sha256(0x0403),
          ecdsa_secp384r1_sha384(0x0503),
          ecdsa_secp521r1_sha512(0x0603),

          /* RSASSA-PSS algorithms with public key OID rsaEncryption */
          rsa_pss_rsae_sha256(0x0804),
          rsa_pss_rsae_sha384(0x0805),
          rsa_pss_rsae_sha512(0x0806),

          /* EdDSA algorithms */
          ed25519(0x0807),
          ed448(0x0808),

          /* RSASSA-PSS algorithms with public key OID RSASSA-PSS */
          rsa_pss_pss_sha256(0x0809),
          rsa_pss_pss_sha384(0x080a),
          rsa_pss_pss_sha512(0x080b),

          /* Legacy algorithms */
          rsa_pkcs1_sha1(0x0201),
          ecdsa_sha1(0x0203),

          /* Reserved Code Points */
          private_use(0xFE00..0xFFFF),
          (0xFFFF)
      } SignatureScheme;
```

it probably needs very little work to fix.

**Comment by Asmeble** [comment]
this needs to be fixed immediately.

**Comment by gpotter2** [comment]
Hi,
Support was added in https://github.com/secdev/scapy/pull/4463
(Yeah, it might sound a bit ridiculous to report on that 4y later -_-', but better late than never)
