### ISSUE TITLE
Registering layers for embedded usage without importing "star"

### ISSUE THREAD

**Issue by Zopieux** [secdev/scapy#270]
I am using scapy as a library within a wider project – rather than the scapy tutorial workflow of a “REPL” session. As such, I don't want to _pollute_ my project scope with this statement:

```python
from scapy.all import *
```

Thing is, this statement seems to be the only way of registering layers for payload detection, as the various layers have `bind_layers()` declaration in their root module context. In other words:

```
>>> from scapy.layers.l2 import Ether

>>> # without importing
>>> Ether(raw_bytes)
<Ether  dst=00:05:5d:21:99:4c src=00:16:ce:6e:8b:24 tags=<Untagged  |> type=0x0800
  |<Raw  load="<snip>" |>>

>>> # with import-all
>>> from scapy.all import *
>>> Ether(raw_bytes)
<Ether  dst=00:05:5d:21:99:4c src=00:16:ce:6e:8b:24 tags=<Untagged  |> type=0x0800
  |<IP  version=4 ihl=5 tos=0x00 len=59 id=7975 flags= frag=0 ttl=128 proto=udp chksum=0x67c1 src=192.168.0.114 dst=205.152.37.23 options=[]
    |<UDP  sport=1060 dport=domain len=39 chksum=0x036d
      |<DNS  <snip>>
```

Is it possible to trigger the layer registration without “importing all”?

**Comment by guedou** [comment]
It is unfortunately not possible, and I think that it will never be without a drastic change to Scapy core.

`bind_layers()` calls are performed where layers are defined. In your example, it will be in `inet.py` and `dns.py`. When you are importing, `Ether` there is no way to guess all possible layers that you will need.

**Comment by Zopieux** [comment]
Thanks for the reply. I guess it's status quo then.
