### ISSUE TITLE
`gmt_unix_time` not set in `TLS13ClientHello` so `tls_session_update` fails

### ISSUE THREAD

**Issue by SurienDG** [secdev/scapy#2700]
#### Brief description

If I try to parse a TLS 1.3 client hello packet with `scapy.layers.tls.record.TLS` the message type of the packet is scapy.layers.tls.handshake.TLSClientHello instead of scapy.layers.tls.handshake.TLS13ClientHello.

So, I tried setting the advertised_tls_version in a session as shown below:

```Python
tls_session.advertised_tls_version = 772
tls_packet = TLS(raw_packet.load, tls_session=tls_session)
```

This causes it to correctly try to parse it as `TLS13ClientHello` however this fails because it calls the `tls_session_update` function for its super class (`TLSClientHello`) which expects `gmt_unix_time` to be set,

![image](https://user-images.githubusercontent.com/18398584/86386142-632c8b00-bc5f-11ea-9d10-63f4ffe729cc.png)

However, we know it isn't set because `gmt_unix_time` is not a field for `TLS13ClientHello` like it is for `TLSClientHello`:

![image](https://user-images.githubusercontent.com/18398584/86386361-a4249f80-bc5f-11ea-9031-ec228deb8f99.png)

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7
-   Operating System: MacOS

**Comment by gpotter2** [comment]
Could you provide a full example that reproduces the issue ?
Thanks

**Comment by SurienDG** [comment]
Sure. The following code will show that when parsing the raw bytes of a ClientHello for TLS 1.3 we get back a `TLSClientHello` rather than a `TLS13ClientHello` object.  Also, if we force it to try to parse it as `TLS13ClientHello` by setting the advertised TLS version in `tls_session` we get an exception which is because of the property of `gmt_unix_time` not being defined as shown in the output below.


### Code:
```
clientHellowRawPacket = b"\x16\x03\x01\x00\xe6\x01\x00\x00\xe2\x03\x03\x81G\xc1f\xd5\x1b\xfaK\xb5\xe0*\xe1\xa7\x87\x13\x1d\x11\xaa\xc6\xce\xfc\x7f\xab\x94\xc8b\xad\xc8\xab\x0c\xdd\xcb o\x9d\x07\xf1\x95>\x99\xd8\xf3m\x97\xee\x19\x0b\x06\x1b\xf4\x84\x0b\xb6\x8f\xcc\xde\xe2\xd0-k\x0c\x1fRS\x13\x00\x08\x13\x02\x13\x03\x13\x01\x00\xff\x01\x00\x00\x91\x00\x00\x00\x0c\x00\n\x00\x00\x07dogfish\x00\x0b\x00\x04\x03\x00\x01\x02\x00\n\x00\x0c\x00\n\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00\r\x00\x1e\x00\x1c\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08\n\x08\x0b\x08\x04\x08\x05\x08\x06\x04\x01\x05\x01\x06\x01\x00+\x00\x07\x06\x7f\x1c\x7f\x1b\x7f\x1a\x00-\x00\x02\x01\x01\x003\x00&\x00$\x00\x1d\x00 /5\x0c\xb6\x90\n\xb7\xd5\xc4\x1b/`\xaaV{?q\xc8\x01~\x86\xd3\xb7\x0c)\x1a\x9e[8?\x01r"
            tls_session = tlsSession()
            try:
                tls_session.advertised_tls_version = 772
                tls_packet = TLS(clientHellowRawPacket)
                print(isinstance(tls_packet.msg[0], TLS13ClientHello))
                print(isinstance(tls_packet.msg[0], TLSClientHello))
                tls_packet = TLS(clientHellowRawPacket, tls_session=tls_session)
                print(isinstance(tls_packet.msg[0], Raw))
            except Exception as e:
                print(e)
```


### Output:
```
False
True
gmt_unix_time
```

### Packet capture file where TLS Hello packet is defined:
https://www.cloudshark.org/captures/a044d58b77aa

**Comment by SurienDG** [comment]
@gpotter2 
Also, the specific `tls_session_update` for for `TLS13ClientHello` calls the super method of it (my screen shot in my original post) which needs `gmt_unix_time` to be defined.

###  `TLS13ClientHello`  version of  `tls_session_update` 
![image](https://user-images.githubusercontent.com/18398584/86995834-1e7d8400-c178-11ea-871a-e5a50afdd95f.png)

### Super definition of method called in the `TLS13ClientHello`  version of  `tls_session_update`:
![image](https://user-images.githubusercontent.com/18398584/86995892-3bb25280-c178-11ea-9297-34a45efa61d7.png)

**Comment by gpotter2** [comment]
This is already fixed in the github version. Please please please ALWAYS try using the github version first as marked in the issue template......

**Comment by SurienDG** [comment]
@gpotter2 

Well I'm pretty sure I am using that  version. 

I did a diff with the handshake.py version on the github found here (https://github.com/secdev/scapy/blob/v2.4.3/scapy/layers/tls/handshake.py) - which is version 2.4.3 and my local version in my pipenv.

This is the result:

https://www.diffchecker.com/FaSoT5WV

The only difference is some changing to the amount of whitespace on the last line. So, I don't believe this is fixed in the current git version. If you try doing running my example in https://github.com/secdev/scapy/issues/2700#issuecomment-654945554 I think you will find the same results.

**Comment by gpotter2** [comment]
Your example can not be reproduced on master.

**Comment by SurienDG** [comment]
Sorry I didn't notice a particular change. I think its working on master.
