### ISSUE TITLE
sniff() on prerecorded PCAP file with BPF filter applied on macOS

### ISSUE THREAD

**Issue by cfanatic** [secdev/scapy#2702]
#### Brief description

Filter options for `sniff()` in offline mode with a prerecorded PCAP file do not seem to work on my macOS system. I also tried to run the ipython3 session with sudo, no luck either. The same command works on my Debian virtual machine, though! So I am sure it must be related to macOS somehow.

Further information: I can call `tcpdump` from the terminal successfully, but I don't have the libpcap library installed via homebrew.

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.7.3
-   Operating System: macos 10.15.3

#### How to reproduce

```
In [11]: plist = sniff(filter="ip host 192.168.0.3 or ip host 192.168.0.4", offline="data/vsomeip_client_cf12fb22.pcapng")
reading from PCAP-NG file data/vsomeip_client_cf12fb22.pcapng
```

#### Actual result

```
In [12]: plist
Out[12]: <Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
```

#### Expected result

```
In [14]: plist
Out[14]: <Sniffed: TCP:0 UDP:37 ICMP:0 Other:0>
```

#### Related resources

https://github.com/cfanatic/vsomeip-testing/blob/master/trace/vsomeip_client_cf12fb22.pcapng

**Comment by guedou** [comment]
Could you try the same `sniff()` call using `sudo ./run_scapy` on the master branch?

**Comment by gpotter2** [comment]
Closed for inactivity

**Comment by michaelbrandeis** [comment]
Bumping this issue because it still exists in scapy 2.4.4.dev97

In my own testing I found that converting the pcapng file to plain pcap does result in packets being returned. I posted a bunch of details in https://gitter.im/secdev/scapy#

pcapng

```
python mojo.py --pcap example.pcapng
WARNING: No IPv4 address found on bridge0 !
WARNING: No IPv4 address found on p2p0 !
WARNING: more No IPv4 address found on awdl0 !
reading from PCAP-NG file example.pcapng
```

plain pcap

```
python mojo.py --pcap example.pcap
WARNING: No IPv4 address found on bridge0 !
WARNING: No IPv4 address found on p2p0 !
WARNING: more No IPv4 address found on awdl0 !
Ether / IP / UDP 5.188.125.46:intecom_ps1 > 192.168.8.114:63285 / Raw
Ether / IP / UDP 192.168.8.114:63285 > 5.188.125.46:intecom_ps1 / Raw
```

both called with

```
sniff(prn=handle_packet, filter='udp', offline=pcap)
```

**Comment by michaelbrandeis** [comment]
```
    def read_packet(self, size=MTU):
        """Read blocks until it reaches either EOF or a packet, and
        returns None or (packet, (linktype, sec, usec, wirelen)),
        where packet is a string.

        """
        print("READ NG")
        while True:
            print(".")
            try:
                blocktype, blocklen = struct.unpack(self.endian + "2I",
                                                    self.f.read(8))
            except struct.error:
                print("EOF")
                raise EOFError
```

```
python mojo.py --pcap bank.pcapng
reading from PCAP-NG file bank.pcapng
READ
READ NG
.
EOF
```

it appears to try to call read_packet once and fails with a struct.error and silently raises an EOFError
