### ISSUE TITLE
Unable to create a TLSClientHello packet.

### ISSUE THREAD

**Issue by Akuhyo** [secdev/scapy#2704]
#### Brief Description

My main issue is that I'm not able to send a TLSClientHello packet with an SNI extension. I'm not even
sure if I'm doing this correctly and I'm unable to find a reference that could help me.

#### Environment

-   Scapy version: `Latest`
-   Python version: `3.7.5`
-   Operating System: `Win10`

#### How to Reproduce

`packet = IP(src="192.168.1.88"/TLS()/TLSClientHello()/TLS_Ext_ServerName()/ServerName(servername='mysite.com')`

#### Actual Result

Whenever I send the packet, I see it come through in Wireshark as a malformed ipv6 hop-by-hop packet.

#### Expected Result

I was expecting to see the packet go through as a TLSClientHello where I could see the SNI extension.

**Comment by gpotter2** [comment]
That's not at all how you build a TLS packet. You should do

```
packet = IP()/TLS(msg=[TLSClientHello(ext=[TLS_Ext_ServerName(servernames=[ServerName(servername="mysite.com")])])])
```

**Comment by Akuhyo** [comment]
> That's not at all how you build a TLS packet. You should do
> 
> ```
> packet = IP()/TCP()/TLS(msg=[TLSClientHello(ext=[TLS_Ext_ServerName(servernames=[ServerName(servername="mysite.com")])])])
> ```

Thank you so much! I'm not too experienced with Scapy so this helped a lot.
