### ISSUE TITLE
Missing Ethertype for 6loWPAN encapsulation (RFC7973) -> Feature Request

### ISSUE THREAD

**Issue by Chamaeleon-** [secdev/scapy#2716]
#### Brief description
Ethertype 0xA0ED from 6loWPAN encapsulation in RFC7973 is missing in scapy

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.7.7`
-   Operating System: `Ubuntu 18.04 LTS`

#### How to reproduce

Sniff some packets which use RFC7973 6loWPAN encapsulation. e.g. from RIOT-OS native 6loenc enabled networking example (possible setup is described in the testing setup of https://github.com/RIOT-OS/RIOT/pull/10667)

#### Actual result

scapys Packet.show() output of a sniffed packet
```
###[ Ethernet ]### 
  dst       = ff:ff:ff:ff:ff:ff
  src       = 50:51:52:67:15:69
  type      = 0xa0ed
###[ Raw ]### 
     load      = '~;\x02\xf0\x1f\x90\x1f\x90\x03Qtesttext2'`
```
You can see scapy don't seem to recognize the Ethernet type and didn't try to decode the 6loWPAN header.
#### Expected result

Wireshark decodes this to:
 `Frame(Ethernet(6lowpan(data)))` with 6lowpan decompressed to IPv6 and UDP headers.
It should be possible to do this in scapy too.

Long form of the wireshark output:
```
Frame 339: 33 bytes on wire (264 bits), 33 bytes captured (264 bits)
Ethernet II, Src: 50:51:52:67:15:69 (50:51:52:67:15:69), Dst: Broadcast (ff:ff:ff:ff:ff:ff)
    Destination: Broadcast (ff:ff:ff:ff:ff:ff)
    Source: 50:51:52:67:15:69 (50:51:52:67:15:69)
    Type: 6LoWPAN (0xa0ed)
6LoWPAN
    IPHC Header
    Source: fe80::5051:52ff:fe67:1569
    Destination: ff02::2
    UDP header compression
    Source port: 8080
    Destination port: 8080
    UDP checksum: 0x0351
Internet Protocol Version 6, Src: fe80::5051:52ff:fe67:1569, Dst: ff02::2
User Datagram Protocol, Src Port: 8080, Dst Port: 8080
Data (9 bytes)
```

#### Related resources
https://tools.ietf.org/html/rfc7973
https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml#ieee-802-numbers-1

**Comment by gpotter2** [comment]
Looks easy enough to fix. Thanks for the report.

Could you provide a packet as raw form so that we can check that the fix works ? thanks

**Comment by Chamaeleon-** [comment]
Same packet like in the original issue hexdumped:
```
0000   ff ff ff ff ff ff 50 51 52 67 15 69 a0 ed 7e 3b
0010   02 f0 1f 90 1f 90 03 51 74 65 73 74 74 65 78 74
0020   32
```

**Comment by gpotter2** [comment]
Great thanks

**Comment by gpotter2** [comment]
Feel free to try out https://github.com/secdev/scapy/pull/2719 and give some feedback. Thanks
