### ISSUE TITLE
Scapy 2.4.4

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#2717]
This issue is to inform that we are (finally) planning on starting the release schedule of **2.4.4**.

Maintainers, feel free to fill the list, which will be used for the final changelog. Users, feel free to _comment below_

### TODO

See https://github.com/secdev/scapy/projects/5

# Main Changes

# Core

- [776 commits to master](https://github.com/secdev/scapy/compare/v2.4.3...master) since this v2.4.3
- fix how timestamps are measured on layer 3 (broken since 2.4.1)
- drop DNET support (deprecated since 2.4.0)
- Scapy will now use `libpcap` instead of `tcpdump` to compile the filters (`tcpdump` is still used to filter pcaps)
- major changes to the online doc: add an automatically generated [API reference](https://scapy.readthedocs.io/en/latest/api/scapy.html) with visual representation of each layer, move to Sphinx 3.0.0, new layer-specific doc...
- *BSD fixes
- more doc to many functions

# Layers

- New layers (homeplug sg, smb2, NSH, RPL, ERSPAN, BFD, ROCE...)
- TLS: TLS 1.3 support & many fixes
- 802.11 improvements / WPA3 detection
- Netflow 9 fixes
- Major refactor & changes of the Automotive layers
- HTTP changes
- DHCPv6 fixes according to revision of the RFC
 - Bluetooth improvements (+BLE)
 - minor fixes to Radius, PPP, GTP, IPsec, CDP, VTP, HTTP/2, ...

**Comment by polybassa** [comment]
Automotive-Related:
- Improvement of OBD-Scanner
- Refactoring of python-can CANSockets to have an identical behaviour between NativeCANSocket and PythonCANSocket
- Implementation of an ISOTP_ENETSocket to allow ISOTP communication over TCP (used by BMW)
- Implementation of a ECU Answering Machine to simulate the communication behaviour of a real ECU
- Utilities for GMLAN
- Bug-Fixes in SOME/IP
- More Unit-Tests

**Comment by guedou** [comment]
2.4.4rc1 is out https://pypi.org/project/scapy/2.4.4rc1/

**Comment by guedou** [comment]
2.4.4rc2 is out https://pypi.org/project/scapy/2.4.4rc2/ 

According to https://github.com/secdev/scapy/projects/5 there is no much to do before the final version.

**Comment by gpotter2** [comment]
@guedou Project is done. Should we do the final release ?

**Comment by guedou** [comment]
No problem, I will make the release on August 24.

**Comment by gpotter2** [comment]
I made a batch of small PRs that fix some various old issues. They all have tests and should be pretty straightforward.

**Comment by guedou** [comment]
v2.4.4 is now released.
