### ISSUE TITLE
Scapy MQTT5

### ISSUE THREAD

**Issue by ivanv6** [secdev/scapy#2720]
Dear all, is MQTT version 5 supported by scapy? By checking the documentation, only MQTT v3.1.1 seems to be supported. Thanks a lot

**Comment by gpotter2** [comment]
Some parts at least. MQTT is incremental. It's also mentioned in the protocol list so I'm assuming some parts do work
https://github.com/secdev/scapy/blob/f49c96a7a1dd4afb3eb445e4bb4e9c1b138eac6a/scapy/contrib/mqtt.py#L109
