### ISSUE TITLE
Corner case in scapy.utils.corrupt_bits()

### ISSUE THREAD

**Issue by Chamaeleon-** [secdev/scapy#2721]
#### Brief description
Function `scapy.utils.corrupt_bits()` can't flip less than one bit, even on low percentages

#### Environment

-   Scapy version: `2.4.3`
-   Python version: `3.7.7`
-   Operating System: `Ubuntu 18.04 LTS`

#### How to reproduce
Call `corrupt_bits("hello")` 5 times.
Call `corrupt_bits("hello", p=0.00001)` 5 times.

#### Actual result
 You will see every time occurs a bit flip with default percentage of `p=0.01` and also with `p=0.00001`

#### Expected result
It should be possible to get 0 bit flips (important in small strings):
https://github.com/secdev/scapy/blob/349259209d4f6292a9644e68a9aced300f32e623/scapy/utils.py#L910 should be altered to         `n = max(0, int(s_len * p))`

OR

https://github.com/secdev/scapy/blob/349259209d4f6292a9644e68a9aced300f32e623/scapy/utils.py#L906 should be altered to     `"""Flip a given percentage (at least one bit) or number of bits from a string"""`

**Comment by gpotter2** [comment]
Good catch.
I'd say this is "by design" and the doc should be updated. I would expect the function to at least do something on each call (?)

**Comment by Chamaeleon-** [comment]
I expected it would calculate the percentage right. But I think it's possibly more useful if it stays like this with updated doc, because otherwise it would be a function which corrupts nothing on a lot of calls.
I searched for a function which corrupts bits with a given probability. It would be more useful for small packets (like my 6lowpan packets from #2716 ), but I think scapy has none like that. Maybe add an other parameter to implement bit error probability too?

**Comment by p-l-** [comment]
@Chamaeleon- maybe you could in the first place submit a PR to update the doc (that we could merge before the next 2.4.4 release). Then, in open another issue (or submit a PR) for your bit error probability idea (which I think should help).
What do you think?
