### ISSUE TITLE
adding a metadata field to the packet in order to match it on the openflow switch table.

### ISSUE THREAD

**Issue by Abdullahalshra3a** [secdev/scapy#2722]
Dear All,
I am using Scapy to add a metadata field to the pkt Scapy . I use mininet as a platform to launch my network simulation.
In fact, I try to  match it on the openflow switch table. But, nothing happens. Could you please guide me , what can I do or what should I learn ?

when I send the pkt I can see the metadata field on the sender(xterm) 
But, I see the metadata field as a Raw with sent data field on the controller, Wireshark or the destination host. 
 
I use the following on the sender
```
from scapy.all import *
from datetime import datetime
class Metadata(Packet):
    name = "Metadata"
    fields_desc = [ XByteField("metadata", 1) ] 

def generatePackets():
      if len(sys.argv) != 4:
        print "Usage: arping2tex <net>\n eg: arping2text 192.168.1.0/24"
        sys.exit(1)
      src= sys.argv[1]
      dst= sys.argv[2]
      x = int(sys.argv[3])
      ip=IP(src= src, dst= dst)
      metadata = Metadata(metadata = 200)
      udp=UDP(sport= 2235, dport=5546)#,
      data = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
      pkt = (ip/udp/metadata/data)
      print pkt.show() / show2()
      send(pkt, count = x)   
    
if __name__ == '__main__':
    generatePackets()
```

-   Scapy 
-   Python version: 2.7
-   Operating System:  mininet, ryu, linux 18.4`

Finally, please accept my apology if my question is not proper.
A.Soliman

**Comment by gpotter2** [comment]
Hi !
Please note that this is more a bug/features tracker than a forum. Unless your question is very technical, you should ask your question on the gitter or on stackoverflow.
Thanks for your interest in scapy :)
