### ISSUE TITLE
vcan regression (Can, SocketCan) 

### ISSUE THREAD

**Issue by roumy** [secdev/scapy#2729]
When trying to setup a virtual can interface vcan0 , i received an error message : "No such Device"

```
>>> load_layer('can')
>>> load_contrib('cansocket')
INFO: Configuration 'conf.contribs['CANSocket'] not found.
INFO: Using native CANSocket.
INFO: Specify 'conf.contribs['CANSocket'] = {'use-python-can': True}' to enable python-can CANSockets.
>>> socket = CANSocket(iface='vcan0')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/scapy/contrib/cansocket_native.py", line 73, in __init__
    self.ins.bind((self.channel,))
OSError: [Errno 19] No such device
```
Problem happens with last git clone installed version 2.4.4rc1.dev13 while it works correctly on Version 2.4.3 
I am running on debian 9.12 with Python 3.5.3

**Comment by polybassa** [comment]
Thanks for your question. Did you created the vcan interface on your terminal, before? 
Please see the documentation: https://scapy.readthedocs.io/en/latest/layers/automotive.html#virtual-can-setup

**Comment by roumy** [comment]
Yep 
I've tested with same PC , same moment with scapy 2.4.3 without pb.
candump vcan0 correctly received frame

**Comment by polybassa** [comment]
Thanks for your reply. I'll try to replicate your issue.

**Comment by polybassa** [comment]
Another question. Does `candump` and `cansend` work?

**Comment by baarse** [comment]
Try channel='vcan0' instead of iface. There was a change:
[https://github.com/secdev/scapy/commit/1ab9a2b145e928eb79032aae201b48177275d5f6#diff-22c25e3d86929306a26b089a4cb2a34c](url)

**Comment by roumy** [comment]
That is the tricks! 
i correct the doc in accordance for next times
https://github.com/roumy/scapy/pull/1
