### ISSUE TITLE
isotpscanner.py --help test failing

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#2736]
This test is failing in some Python 2.7 / PyPy2 tests (it seems to be only on Travis with those two versions): (logs: [Py2.7](https://travis-ci.com/github/secdev/scapy/jobs/364646709), [PyPy2](https://travis-ci.com/github/secdev/scapy/jobs/364646710))

```
###(007)=[failed] Test show help

>>> result = subprocess.Popen([sys.executable, "scapy/tools/automotive/isotpscanner.py", "--help"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>>> std_out, std_err = result.communicate()
>>> expected_output = plain_str(b'Scan for open ISOTP-Sockets.')
>>> 
>>> assert not std_err
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AssertionError
```

@polybassa Sorry to bother, could you have a look at it ? Thanks !

**Comment by polybassa** [comment]
Hi, I will have a look an fix that. Thank you very much for this notice. I will probably do it on Monday. Pretty strange that this fails.

**Comment by polybassa** [comment]
@gpotter2 I tried to reproduce this bug on my local machine. Without success, unfortunately. 
Could you please merge the catch code from PR #2737, which allows me to investigate this error on Travis, if it appears again.

**Comment by polybassa** [comment]
@gpotter2 
I identified the issue:
```
/home/travis/build/secdev/scapy/.tox/pypy-linux_root/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.

  CryptographyDeprecationWarning,
```
Should I add an work-around, or will this issue be fixed in another way?

**Comment by gpotter2** [comment]
We could just drop the test for std_err

**Comment by polybassa** [comment]
Did it.

**Comment by polybassa** [comment]
This can be closed

**Comment by guedou** [comment]
Thanks.
