### ISSUE TITLE
HC1-compressed 6lowpan packets don't get recognized

### ISSUE THREAD

**Issue by beiqil** [secdev/scapy#2748]
#### Brief description

For this [6lowpan sample capture][1], the HC1 payload weren't detected and the `packet.load` still contains the compressed data rather than getting decompressed.

#### Environment

-   Scapy version: `g378b10a`
-   Python version: `3.8.5`
-   Operating System: `Fedora 32`

#### How to reproduce

```python
from scapy.all import rdpcap, conf
conf.dot15d4_protocol='sixlowpan'
pcap=rdpcap('6LoWPAN.pcap.gz')
# The 4th packet contains HC1 compressed payload
pcap[3].show()
```

#### Actual result

There's no `scapy.layers.sixlowpan.LoWPAN_HC1` section in parsed packet and the `load` field contains the raw HC1 compressed data.

#### Expected result

Parsed packet should have a `scapy.layers.sixlowpan.LoWPAN_HC1` section that contains the decompressed payload.

#### Related resources

[Sample PCAP][1]

[1]: https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=6LoWPAN.pcap.gz

**Comment by gpotter2** [comment]
Could you try https://github.com/secdev/scapy/pull/2751

**Comment by beiqil** [comment]
@gpotter2 It seems to work a lot better than before. One thing though: the load field probably shouldn't include the FCS checksum which probably should belong to its own field.
