### ISSUE TITLE
function 'answers' does not work

### ISSUE THREAD

**Issue by Qnner** [secdev/scapy#2753]
#### Brief description
I'm trying match a http request to a http response, I'v see an issue linked:https://github.com/secdev/scapy/issues/2208
Maybe I know what he mean in that issue. he mean that sometimes function 'answers' does not work, a pcap not work when use or not TCPsession, two work when not use TCPsession but no TCPsession worked.
 soon I will give my code & pcaps

#### Environment

-   Scapy version: `scapy version 2.3.4`
-   Python version: `2.7`
-   Operating System: `Windows and Centos 7.6`

#### How to reproduce

```python
requests = []

def test(packet):
   if packet.haslayer(HTTPRequest):
        requests.append(packet)
   elif packet.haslayer(HTTPResponse):
       for p in requests:
           # print p
           if packet.answers(p) != 0:
               print "hit"


if __name__ == '__main__':
    load_layer("http")
    conf.contribs["http"]["auto_compression"] = True
    # sniff(offline=r'both_not_work.pcap', prn=test)
    sniff(offline=r'D:\TCPSession_not_work.pcap', prn=test, session=TCPSession)
    # sniff(offline=r'D:\use_tcpSession_not_work.pcapng', prn=test)
```

#### Actual result
print nothing, not hit output

#### Expected result
print 'hit'

#### Related resources

[pcaps.zip](https://github.com/secdev/scapy/files/5032410/pcaps.zip)

**Comment by Qnner** [comment]
I'v tried a method:
if request's pkt[TCP].seq + len(pkt[TCP].payload) = response's pkt[TCP].ack, them matched.but when a request used more than one tcp, that did not work.
How can I get the first tcp from request's tcp queue for last tcp from response's tcp queue when used TCPsession?

**Comment by gpotter2** [comment]
Sorry but I don't understand what this means:

> he mean that sometimes function 'answers' does not work, a pcap not work when use or not TCPsession, two work when not use TCPsession but no TCPsession worked.

**Comment by Qnner** [comment]
> Sorry but I don't understand what this means:
> 
> > he mean that sometimes function 'answers' does not work, a pcap not work when use or not TCPsession, two work when not use TCPsession but no TCPsession worked.

Sometimes, the ‘answers’ function doesn't work.

When tcpsession is used, the following PCAPs cannot be used normally. When tcpsession is not used, one of the PCAPs cannot be used normally

**Comment by Qnner** [comment]
reply: https://github.com/secdev/scapy/issues/2208
maybe you should use HTTP packet do answers
my code here:
```
from scapy.layers.http import HTTPRequest, HTTPResponse
from scapy.main import load_layer
from scapy.sendrecv import sniff
from scapy.sessions import TCPSession

requests = []


def test(packet):
    if packet.haslayer(HTTPRequest):
        requests.append(packet[HTTPRequest])
    elif packet.haslayer(HTTPResponse):
        for p in requests:
            # print p
            if packet[HTTPResponse].answers(p) != 0:
                print p[HTTPRequest].Path
                print packet[HTTPResponse].payload
                requests.remove(p)
                print '\n----------------------------\n'
        print '===>'


if __name__ == '__main__':
    load_layer("http")
    # sniff(offline=r'both_not_work.pcap', prn=test)
    sniff(offline=r'./pcaps/some_http.pcapng', prn=test, session=TCPSession)
    # sniff(offline=r'D:\use_tcpSession_not_work.pcapng', prn=test)
```
