### ISSUE TITLE
Errror in decoding MCS information in Radiotap header

### ISSUE THREAD

**Issue by Nischals** [secdev/scapy#2758]
#### Brief description

MCS fileds from radiotap header like MCS index, guard interval, BW etc 
![packet_screenshot](https://user-images.githubusercontent.com/2862842/90057508-1b892c80-dcfe-11ea-934b-536b11543d15.PNG)
are not decoded correctly while reading the radiotap header from a wireshark capture
#### Environment

-   Scapy version: Both in 2.4.3 release version and current development version
-   Python version: 3.8.5
-   Operating System: Windows 10

#### How to reproduce

Load a 802.11 pcap/wcap wireshark capture and observe the radiotap header contents
#### Actual result
{'version': 0,
 'pad': 0,
 'len': 44,
 'present': <Flag 1837131 (TSFT+Flags+Channel+dBm_AntNoise+Antenna+ChannelPlus+MCS+A_MPDU)>, 
'Ext': None,
 'mac_timestamp': 60187170,
 'Flags': <Flag 16 (FCS)>, 
'Rate': None,
 'ChannelFrequency': 2412, 
'ChannelFlags': <Flag 1152 (2GHz+Dynamic_CCK_OFDM)>,
 'dBm_AntSignal': None,
 'dBm_AntNoise': -80, 
'Lock_Quality': None, 
'Antenna': 0, 
'RXFlags': None, 
'TXFlags': None, 
'ChannelPlusFlags': <Flag 66688 (2GHz+Dynamic_CCK_OFDM+20MHz)>, 
'ChannelPlusFrequency': 2412,
 'ChannelPlusNumber': 1, 
'knownMCS': <Flag 34 (MCS_index+STBC_streams)>,
 'Ness_LSB': 0, 
'STBC_streams': 0, 
'FEC_type': 1, 
'HT_format': 1, 
**'guard_interval': 1,
 'MCS_bandwidth': 3, 
'MCS_index': 8,**
 'A_MPDU_ref': 1428,
 'A_MPDU_flags': <Flag 4 (KnownLastSubframe)>,
 'KnownVHT': None, 
'PresentVHT': None,
 'VHT_bandwidth': None, 
'mcs_nss': None,
 'GroupID': None, 
'PartialAID': None,
 'timestamp': None,
 'ts_accuracy': None,
 'ts_position': None,
 'ts_flags': None,
 'he_data1': None, 
'he_data2': None, 
'he_data3': None, 
'he_data4': None,
 'he_data5': None,
 'he_data6': None,
 'hemu_flags1': None,
 'hemu_flags2': None, 
'RU_channel1': None,
 'RU_channel2': None,
 'hemuou_per_user_1': None, 
'hemuou_per_user_2': None, 
'hemuou_per_user_position': None,
 'hemuou_per_user_known': None,
 'lsig_data1': None,
 'lsig_length': None,
 'lsig_rate': None, 'notdecoded': b''}
<#### Expected result
MCS information must be decoded correctly

**Comment by guedou** [comment]
Could you share a pcap file that exhibits the issue?

**Comment by Nischals** [comment]
Please find sample trace attached
[packet.zip](https://github.com/secdev/scapy/files/5067131/packet.zip)
