### ISSUE TITLE
IP.route() does not choose correct source IP when there are interface aliases

### ISSUE THREAD

**Issue by prxyg3n** [secdev/scapy#278]
On a linux machine with interface aliases defined, scapy does not always select the correct source IP when routing IP packets.

Scapy loads its routing table in read_routes (scapy/arch/linux.py). Routes are read from /proc/net/route, which doesn't contain source IPs. Instead, source IPs are selected using ioctl with SIOCGIFADDR on the relevant interface, but this doesn't take interface aliases into account.

Steps to reproduce:

``` bash
$ ip tuntap add tun0 mode tun
$ ifconfig tun0 up 10.5.5.1/24
$ ifconfig tun0:1 10.7.7.1/24
$ ip route add 10.6.6.0/24 via 10.5.5.254
$ ip route add 10.8.8.0/24 via 10.7.7.254
$ scapy
>>> iff, src, gw = IP(dst='10.8.8.1').route()
>>> print src # should be 10.7.7.1
10.5.5.1
```

**Comment by p-l-** [comment]
Fixed in #554.
