### ISSUE TITLE
Bug: layers/dhcp.py  DHCPOptions[33] and DHCPOptions[46] duplicate symbol

### ISSUE THREAD

**Issue by anr-private** [secdev/scapy#2786]
DHCPOptions[33] and [46] are both called "static-routes". I believe [33] is correct but [46] is incorrect. Per RFC-2132 sect 8.7, [46] is "NetBIOS over TCP/IP Node Type Option". The error also causes DHCPRevOptions issue (obviously, duplicate symbol/string).

**Comment by gpotter2** [comment]
Thanks for the report, this looks pretty obvious.
Fixed in https://github.com/secdev/scapy/pull/2798
