### ISSUE TITLE
sniff packets wrong order

### ISSUE THREAD

**Issue by lizitong67** [secdev/scapy#2788]
I wanna use the sniff() to capture packets and the _iface_ is an **interface list**. But the order of packets(timestamp is different from what captured by Wireshark) is wrong, how could I resolve the problem?
 
For example, the order of packets captured by Wireshark is 1 2 3, but what captured by sniff() is 3 2 1

`pkts = sniff(filter="proto ospf", iface=veth_list, prn=send_to_analyser) `

**Comment by gpotter2** [comment]
Not sure we can do anything against that without causing some serious performance downgrade..

**Comment by lizitong67** [comment]
Are there any methods that could replace the sniff() so as to capture packets online?

**Comment by gpotter2** [comment]
No there isn't. This issue is specific to sniffing on multiple interfaces and is due to concurrency. There's nothing we can reasonably do, sorry.
