### ISSUE TITLE
Scapy unable to recognize TLS packet with no message

### ISSUE THREAD

**Issue by edunham-443** [secdev/scapy#2791]
#### Brief description

Scapy is unable to recognize a TLS packet that has no message.

#### Environment

-   Scapy version: 2.4.4rc2
-   Python version: `Python 3.6.9`
-   Operating System: `Ubuntu 18.04.4`

#### How to reproduce

load_layer("tls")
pkt = TLS(bytes(TLS()))
pkt.show2()

#### Actual result

###[ Encrypted Content ]### 
  load      = '\x00\x03\x03\x00\x00'

#### Expected result

###[ TLS ]### 
  type      = handshake
  version   = TLS 1.2
  len       = 115    [deciphered_len= 115]
  iv        = b''
  \msg       \
  mac       = b''
  pad       = b''
  padlen    = None

**Comment by gpotter2** [comment]
This is expected, by default `TLS`'s type is `None` (so that it is guessed based on the content of the `msg` field).
For instance:
```python
TLS(bytes(TLS(msg=[TLSClientHello()])))
```
auto-populates the type to 22 = handshake.

A TLS packet, even one that has no content, has at least a type. For instance:

```python
>>> pkt = TLS(bytes(TLS(type=0x17)))
>>> pkt.show2()
###[ TLS ]###
  type= application_data
  version= TLS 1.2
  len= 0    [deciphered_len= 0]
  iv= b''
  \msg\
  mac= b''
  pad= b''
  padlen= None
```
