### ISSUE TITLE
PadField Throws a ZeroDivisionError When Alignment = 0

### ISSUE THREAD

**Issue by sarcasticmonkeys** [secdev/scapy#2800]
Hi, sorry if this is a bit weird and esoteric, I've got the following code:
```python
class DemoPacket(Packet):
    name = 'DemoPacket'
    class DemoBlock(Packet):
        name = 'DemoBlock'
        fields_desc = [
        ]
        def extract_padding(self, s):
            return '', s
            
    blockPadded = PadField(PacketField('block', default=DemoBlock(),cls=DemoBlock),align=0)
    
    fields_desc = [
        blockPadded,
    ]
```
(Yes, it's a silly example, just a minimal example)

When I try to use this Packet I get a ZeroDivisionError exception, because of line:

https://github.com/secdev/scapy/blob/54da22f91ce5fd45d30efd0359305f4d1fa448a9/scapy/fields.py#L412

Now obviously, in this case having an empty PacketField padded to 0 bytes is kind of silly, but it's because I'm generating lots of different packet types that all have this padded section in them, but sometimes the section is empty. In my mind it would be neater to have the section with 0 size, rather than omitting the section entirely in the case where it's empty. What I would like to do is change the referenced padlen function to

```python
    def padlen(self, flen):
        return -flen % self._align if self._align > 0 else 0
```
This would mean that 0 aligned padding would work. I'm new to this, so sorry if I'm stepping on any toes. Does anyone have any input?

**Comment by gpotter2** [comment]
An alignment of 0 means nothing in scapy. That would mean the bytes before this field starting from the beginning of the packet should be a multiple of.... 0
