### ISSUE TITLE
Addition of CAN J1939 socket support analogous to the ISO-TP protocol?

### ISSUE THREAD

**Issue by robynnepiers** [secdev/scapy#2802]
#### Brief description

Scapy supports ISO-TP, which is one of the protocols provided by the SocketCAN drivers, in addition to the raw SocketCAN socket and the interfaces provided by `python-can`. I noticed that on Linux 5.4+, J1939 protocol support was mainlined, and according to the [What's New](https://docs.python.org/3.9/whatsnew/3.9.html#socket), is available on Python 3.9+

Should there be an analogous J1939 socket, much like `scapy/contrib/isotp.py` provides for ISO-TP sockets?

#### Environment

-   Scapy version: `2.4.4`
-   Python version: `3.9`
-   Operating System: `Ubuntu 20.04`

#### Related resources

* [Linux kernel J1939 documentation](https://www.kernel.org/doc/html/latest/networking/j1939.html)
* [eLinux Wiki](https://elinux.org/J1939)
* [Python 3.9 What's New](https://docs.python.org/3.9/whatsnew/3.9.html#socket)

**Comment by polybassa** [comment]
Hi @robynnepiers 
thanks for this question. 

Support for J1939 would be a great addition for Scapy. I personally didn't worked with J1939, yet. If you have experiences with J1939, it would be great, if you could open a Pull Request to support J1939 in Scapy.

From my side, there a some things, which should be considered first.
1. Is it possible to provide J1939 support for Windows, Linux and OS X?
2. Is it possible to implement J1939 for various CAN-Interfaces (Vector, IXXCAT, PEAK) on the different platforms?
3. What about python2 and older kernel versions? Is it possible to have a fallback software implementation?

Cheers, 
Nils

**Comment by robynnepiers** [comment]
> Is it possible to provide J1939 support for Windows, Linux and OS X?

Like ISO-TP, the J1939 socket is used to provide the abstraction. The physical layer is provided by the implementation defined in ISO 11898 (CAN) using extended IDs.

SocketCAN is Linux-only, so the `socket` APIs provided by Python will only exist on Linux. This is the same case currently that Scapy supports for the raw CAN and ISO-TP socket.

> Is it possible to implement J1939 for various CAN-Interfaces (Vector, IXXCAT, PEAK) on the different platforms?

Since the physical layer is CAN, as long as the interface supports extended IDs and the bitrates, theoretically things could be implemented purely on userspace in Python. I believe there's a few J1939 software implementations that leverage `python-can` interfaces, although I am unsure of their maturity (and that seems like a different issue than purely supporting the SocketCAN-provided interface). See [milhead2/python-j1939](https://github.com/milhead2/python-j1939), which looks like it doesn't have a PyPI release and the author has said that they aren't interested in doing so on the issue tracker, and [benkfra/j1939](https://github.com/benkfra/j1939), which has a PyPI release but has not been updated in years.

These all use `python-can` as the interface abstraction.

> What about python2 and older kernel versions? Is it possible to have a fallback software implementation?

For Python 2, since the feature is only present in Linux 5.4+ and on Python 3.9+, the SocketCAN constant will not be present. This is the same thing as Python 2, as the SocketCAN constants were provided in Python 3.3.0. Support could probably be handled via a userspace implementation.

One other thing to consider is that according to their issue tracker, `python-can` will be dropping support for Python 2 as well in the near future for the `4.0.0` release, so if Scapy intends to support Python 2, then `python-can` will need to be pinned.

**Comment by polybassa** [comment]
@robynnepiers 
Thank you very much for your detailed answer.

To summarize this, we would have the following options:
1. We can implement a J1939 protocol description
     This description could immediately be used with existing CANSockets on all platforms
2. We can implement J1939SoftSockets, which use can_filters to improve the performance
3. For Linux and python3 we can implement a J1939NativeSocket
