### ISSUE TITLE
diameter avpCode 432 decode issue

### ISSUE THREAD

**Issue by yunhuaw01** [secdev/scapy#2803]
It seems that the diameter decode has some issue via scapy.

For the diameter pcap file (diameter1.zip), while it is opened via wireshark, we can see that avpCode 456 include sub avpCode 432 (corresponding avp value is 10) , 437, 886, 1249, 1249, 1249.
![wireshark-view](https://user-images.githubusercontent.com/70928416/92457244-90189380-f1f6-11ea-8db9-353d7065b298.jpg)

[diameter1.zip](https://github.com/secdev/scapy/files/5187133/diameter1.zip)

However when I try to read the diameter layer fields via scapy, it has some decode issue for avpCode 432, the value is 0 and no avp Vendor field; while in wireshark, there is avp Vendor field=0, and  value is 10.  This further leads to other avp can't be correctly decoded inside avpCode 456.
I guess for avpCode 432, it can be defined as AVPV_Unsigned32 instead of AVPNV_Unsigned32.

>>> a.getlayer(3).fields
{'avpList': [<AVPNV_StrLenField  avpCode=263 avpFlags=0x40 (-M-) avpLen=0x15 val='355;jjhddhdda' |<Raw  load='\x00\x00\x00' |>>, <AVPNV_StrLenField  avpCode=461 avpFlags=0x40 (-M-) avpLen=0x23 val='VzW-Messaging-V10@vzw3g.com' |<Raw  load='\x00' |>>, <AVPNV_StrLenField  avpCode=264 avpFlags=0x40 (-M-) avpLen=0x25 val='r_pcef1.diam.originRealm1.com' |<Raw  load='\x00\x00\x00' |>>, <AVPNV_StrLenField  avpCode=296 avpFlags=0x40 (-M-) avpLen=0x1a val='r_originRealm1.com' |<Raw  load='\x00\x00' |>>, <AVPNV_StrLenField  avpCode=283 avpFlags=0x40 (-M-) avpLen=0xd val='realm' |<Raw  load='\x00\x00\x00' |>>, <AVP_0_258  avpCode=258 avpFlags=0x40 (-M-) avpLen=0xc val=Diameter_Credit_Control_Application (4) |>, <AVP_0_416  avpCode=416 avpFlags=0x40 (-M-) avpLen=0xc val=EVENT_REQUEST (4) |>, <AVPNV_Unsigned32  avpCode=415 avpFlags=0x40 (-M-) avpLen=0xc val=0 |>, <AVPNV_Unsigned32  avpCode=278 avpFlags=0x40 (-M-) avpLen=0xc val=4294967295 |>, <AVPNV_Grouped  avpCode=443 avpFlags=0x40 (-M-) avpLen=0x24 val=[<AVP_0_450  avpCode=450 avpFlags=0x40 (-M-) avpLen=0xc val=END_USER_E164 (0) |>, <AVPNV_StrLenField  avpCode=444 avpFlags=0x40 (-M-) avpLen=0x10 val='35500005' |>] |>, <AVPNV_Grouped  avpCode=443 avpFlags=0x40 (-M-) avpLen=0x24 val=[<AVP_0_450  avpCode=450 avpFlags=0x40 (-M-) avpLen=0xc val=END_USER_IMSI (1) |>, <AVPNV_StrLenField  avpCode=444 avpFlags=0x40 (-M-) avpLen=0x10 val='35500005' |>] |>, <AVP_0_436  avpCode=436 avpFlags=0x40 (-M-) avpLen=0xc val=CHECK_BALANCE (2) |>, <AVP_0_455  avpCode=455 avpFlags=0x40 (-M-) avpLen=0xc val=MULTIPLE_SERVICES_SUPPORTED (1) |>, <AVPNV_Grouped  avpCode=456 avpFlags=0x40 (-M-) avpLen=0xf4 val=[<AVPNV_Unsigned32  avpCode=432 avpFlags=0x80 (V--) avpLen=0x10 **val=0** |>, <AVP_0_10  avpCode=10 avpFlags=0x0 (---) avpLen=0x1b5 val=2147483680 (Unknown) |<Raw  load='\x00\x00\x00' |>>, <AVP_Unknown  avpCode=1 avpFlags=0xa1 (V-P----x) avpLen=0x800000 avpVnd=Unkown_Vendor (335544320) val='\x00\x00\x00\x00\x00\x00\x00\x00d\x00\x00\x03v\xc0\x00\x004\x00\x00(\xaf\x00\x00\x03\x83\xc0\x00\x00\x10\x00\x00(\xaf\x00\x00\x00\x01\x00\x00\x03\x81\xc0\x00\x00\x16\x00\x00(\xaf9876543210\x00\x00\x00\x00\x04\xe1\xc0\x00\x000\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x12\x00\x00(\xafMMSALL\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x01\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x0e\x00\x00(\xafMT\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x03\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\r\x00\x00(\xaf1\x00\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x02' |>] |>, <AVPNV_Grouped  avpCode=456 avpFlags=0x40 (-M-) avpLen=0xf4 val=[<**AVPNV_Unsigned32  avpCode=432 avpFlags=0x80 (V--) avpLen=0x10 val=0 |**>, <AVPNV_StrLenField  avpCode=11 avpFlags=0x0 (---) avpLen=0x1b5 val='\x80\x00\x00 \x00\x00\x00\x00\x00\x00\x01\xa1\x80\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x00\x00\x03v\xc0\x00\x004\x00\x00(\xaf\x00\x00\x03\x83\xc0\x00\x00\x10\x00\x00(\xaf\x00\x00\x00\x01\x00\x00\x03\x81\xc0\x00\x00\x16\x00\x00(\xaf9876543211\x00\x00\x00\x00\x04\xe1\xc0\x00\x000\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x12\x00\x00(\xafMMSALL\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x01\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x0e\x00\x00(\xafMT\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x03\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\r\x00\x00(\xaf1\x00\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x02' |>] |>, <AVPNV_Grouped  avpCode=456 avpFlags=0x40 (-M-) avpLen=0xf4 val=[<**AVPNV_Unsigned32  avpCode=432 avpFlags=0x80 (V--) avpLen=0x10 val=0 |**>, <AVPNV_Unsigned32  avpCode=12 avpFlags=0x0 (---) avpLen=0x1b5 val=2147483680 |<Raw  load='\x00\x00\x00' |>>, <AVP_Unknown  avpCode=1 avpFlags=0xa1 (V-P----x) avpLen=0x800000 avpVnd=Unkown_Vendor (335544320) val='\x00\x00\x00\x00\x00\x00\x00\x00d\x00\x00\x03v\xc0\x00\x004\x00\x00(\xaf\x00\x00\x03\x83\xc0\x00\x00\x10\x00\x00(\xaf\x00\x00\x00\x01\x00\x00\x03\x81\xc0\x00\x00\x16\x00\x00(\xaf9876543212\x00\x00\x00\x00\x04\xe1\xc0\x00\x000\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x12\x00\x00(\xafMMSALL\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x01\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x0e\x00\x00(\xafMT\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x03\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\r\x00\x00(\xaf1\x00\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x02' |>] |>, <AVPNV_Grouped  avpCode=456 avpFlags=0x40 (-M-) avpLen=0xf4 val=[<**AVPNV_Unsigned32  avpCode=432 avpFlags=0x80 (V--) avpLen=0x10 val=0 |**>, <AVP_0_13  avpCode=13 avpFlags=0x0 (---) avpLen=0x1b5 val=2147483680 (Unknown) |<Raw  load='\x00\x00\x00' |>>, <AVP_Unknown  avpCode=1 avpFlags=0xa1 (V-P----x) avpLen=0x800000 avpVnd=Unkown_Vendor (335544320) val='\x00\x00\x00\x00\x00\x00\x00\x00d\x00\x00\x03v\xc0\x00\x004\x00\x00(\xaf\x00\x00\x03\x83\xc0\x00\x00\x10\x00\x00(\xaf\x00\x00\x00\x01\x00\x00\x03\x81\xc0\x00\x00\x16\x00\x00(\xaf9876543213\x00\x00\x00\x00\x04\xe1\xc0\x00\x000\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x12\x00\x00(\xafMMSALL\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x01\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\x0e\x00\x00(\xafMT\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x03\x00\x00\x04\xe1\xc0\x00\x00,\x00\x00(\xaf\x00\x00\x03_\xc0\x00\x00\r\x00\x00(\xaf1\x00\x00\x00\x00\x00\x04\xe9\xc0\x00\x00\x10\x00\x00(\xaf\xab\x00\x00\x02' |>] |>, <AVPNV_Grouped  avpCode=456 avpFlags=0x40 (-M-) avpLen=0xf4 val=[<**AVPNV_Unsigned32  avpCode=432 avpFlags=0x80 (V--) avpLen=0x10 val=0 |**>, <AVP_Unknown  avpCode=14 avpFlags=0x0 (---) avpLen=0x1b5 val='\x80\x00\x00 \x00\x00\x00\x00\x00\x00\x01\xa1\x80\x00\x00\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00d\x00\x00\x03v\xc0\x00\x004\x00\x00(\xaf\x00\x00\x03\x83\xc0\x00\x00\x10\x00\x00(\xaf\x00\x00' |>] |>], 'drHbHId': 1393509613, 'drCode': 272, 'drAppId': 4, 'version': 1, 'drLen': 5188, 'drFlags': <Flag 128 (R)>, 'drEtEId': 585960214}

**Comment by gpotter2** [comment]
Hi, please **fill the issue template** and format your issue.
This is probably a very valid issue but is currently hardly readable.
Thanks for your understanding
