### ISSUE TITLE
PacketField Does not Fuzz

### ISSUE THREAD

**Issue by sarcasticmonkeys** [secdev/scapy#2804]
If you call fuzz on a layer that contains a PacketField, that fuzz does not recurse down into a PacketField within the layer
```python
class Foo(Packet):
    name='Foo'
    fields_desc=[
        int64("bar"),
    ]
    def extract_padding(self, s):
        return b'', s
        
class demo(Packet):
    name="demo"
    fields_desc = [ PacketField(name="foo",default=Foo(),cls=Foo)]
instance = demo()
print(fuzz(instance).show())
```
Results in:
```
###[ demo ]### 
  \foo       \
   |###[ Foo ]### 
   |  bar       = 0

None
```

What do people think of modifying 
https://github.com/secdev/scapy/blob/54da22f91ce5fd45d30efd0359305f4d1fa448a9/scapy/packet.py#L2252
to add
```python
            elif isinstance(f, PacketField):
                if(f.default is not None):
                    fuzz(getattr(q, f.name),_inplace=1)
```

resulting in 
```
###[ demo ]### 
  \foo       \
   |###[ Foo ]### 
   |  bar       = <RandSLong>

None
```

To me this makes sense, but I'm obviously very new to this.

**Comment by gpotter2** [comment]
This sounds pretty reasonable. Feel free to submit a PR.
You can also use the `holds_packets` field attribute to see if it holds a packet, this is more general than testing for `PacketField` (but watch out `PacketListField`).

Thanks for the suggestion

**Comment by badsketch** [comment]
I'd like to give this a shot if nobody else has claimed it yet 🙂

**Comment by gpotter2** [comment]
@badsketch Sure, have a shot ! Feel free to ask questions If you get stuck somewhere 😄

**Comment by badsketch** [comment]
Bit off more than I could chew, and don't think I can make a valuable contribution very soon. I'll keep working away on it in my own time, but if anyone else can implement this, please go ahead! Apologies for the late update. 😕

**Comment by guedou** [comment]
Sorry, I did not have a look at this earlier. It seems that this works properly.

```
$ cat test_2804.py 
from scapy.all import *

class Foo(Packet):
    fields_desc=[ IntField("bar", 0) ]
        
class Demo(Packet):
    fields_desc = [ PacketField("foo", "", Foo)]

Demo(raw(fuzz(Demo()))).show()

$ python3 test_2804.py
###[ Demo ]### 
  \foo       \
   |###[ Foo ]### 
   |  bar       = 2191684458

$ python3 test_2804.py
###[ Demo ]### 
  \foo       \
   |###[ Foo ]### 
   |  bar       = 2248926700
```
