### ISSUE TITLE
TLS client automaton unit test

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2812]
Hi, I encountered some of the ISOTPScan tests failing more likely at the moment.

One thing which I think is strange here, that some TLS related print message show up during the ISOTPScan tests. 

I assume that some thread is still running in the background and therefore modifying the unit test system in a way that the ISOTPScan tests fail more likely. 

Here is an output:

```
###(022)=[failed] Test extended ISOTPScan(output_format=code)

>>> test_dynamic(test_extended_isotpscan_code)

Filtering background noise...

[+] Found flow-control frame from identifier 0x702 when testing identifier 0x020

[+] Found flow-control frame from identifier 0x703 when testing identifier 0x60320

[+] Found flow-control frame from identifier 0x703 when testing identifier 0x60326

import can

conf.contribs['CANSocket'] = {'use-python-can': False}

load_contrib('cansocket')

load_contrib('isotp')

ISOTPSocket(can0, sid=0x603, did=0x703, padding=False, extended_addr=0x20, extended_rx_addr=0x11, basecls=ISOTP)

ISOTPSocket(can0, sid=0x603, did=0x703, padding=False, extended_addr=0x26, extended_rx_addr=0x11, basecls=ISOTP)

Test failed. Automatically increase sniff time and retry.

Filtering background noise...

[+] Found flow-control frame from identifier 0x702 when testing identifier 0x020

[+] Found flow-control frame from identifier 0x703 when testing identifier 0x020

[+] Found flow-control frame from identifier 0x703 when testing identifier 0x60322

> Peer socket closed !

> Closing client socket...

> Ending TLS client automaton.


```

https://travis-ci.com/github/secdev/scapy/jobs/384576624

**Comment by gpotter2** [comment]
TBF I've actually known about this TLS test staying IDLE for quite some time but because TLS automatons are special, the Automaton engine didn't allow to close them manually.

This will be fixed in https://github.com/secdev/scapy/pull/2813. I however doubt this has anything to do with the ISOTP test failing, unless the latter uses port 4433 or is so sensible to race conditions that using an extra thread makes it freeze.

**Comment by gpotter2** [comment]
The job you are pointing at is running PyPy which is known for changing speeds.. This test likely has some racing issues.

**Comment by gpotter2** [comment]
We should probably make a master list of all unstable tests: each time a test randomly fails, whatever module or part of scapy it is from, it should just be disable and tossed into the pile.

Some tests really are depending on network conditions (tests that call AS resolvers, DNS requests or HTTP requests), but everything that runs locally (for instance, the TLS automatons tests, but they've gotten pretty stable recently) should likely be zero-tolerance.

**Comment by polybassa** [comment]
Hi @gpotter2, from what I know, the main problem with ISOTP related tests is pythons threading system, especially the GIL. I think, the same also applies for pipetools.uts (https://travis-ci.com/github/secdev/scapy/jobs/383622138). 
If the "load" on the CI-machine is to high, either by having stuff running in the background or by a high demand on CI-services, my tests which require threading are more likely to have non-deterministic failures. Somehow context switches between waiting threads are not fast enough at this point, and internal deadlines fail. However, these failures are absolutely not reproduce-able on my local machine. I was running these flaky tests for hours, without a single failure. 

This one test, which spams the log is a valid issue. I will inspect that. 

I totally agree on having a list of flaky tests. At this point, we could do a separation of required tests (non flaky) and optional tests (flaky) which are allowed to fail. 

I don't know, if you have a way as admin of appveyor and travis to download all logs... a simple grep would probably directly indicate problematic tests. 

If we switch to pytest on the long term, there would be a pytest-flaky module which has the similar effect as `retry_test` I guess.
