### ISSUE TITLE
Scapy 2.4.4 p.143 documentation example makes packet time = host time. Bug or feature?

### ISSUE THREAD

**Issue by jbipre2** [secdev/scapy#2818]
While using scapy libraries to replay Bluetooth packet captures, packet timestamps showed host time instead of packet capture time. 
Sample code:

```python
from pathlib import Path
from itertools import chain
from datetime import datetime
from scapy.utils import rdpcap
from scapy.utils import rdpcap
from scapy.packet import bind_layers, split_layers
from scapy.layers.bluetooth import HCI_Hdr, HCI_Command_Hdr, HCI_Event_Command_Complete, HCI_Event_Hdr, HCI_Event_LE_Meta
from scapy.layers.bluetooth import EIR_Hdr, EIR_CompleteList16BitServiceUUIDs, EIR_ServiceData16BitUUID
from scapy.layers.bluetooth import HCI_LE_Meta_Advertising_Reports

pcapfile = Path.cwd() / "nuc_000097"
with pcapfile.open(mode='rb') as f:
    packets = rdpcap(f)

# Collect advertising reports according to Scapy 2.4.4 documentation p.143:
# Rearrange into a generator that returns reports sequentially
reports = chain.from_iterable(p[HCI_LE_Meta_Advertising_Reports].reports for p in packets)
for report in reports:
    print("Scapy packet time: " + str(datetime.fromtimestamp(report.time)))
    print("System current time: " + str(datetime.now()))
    break

# Preserve PCAP packet capture time (e.g. for forensics):
for p in packets:
    print("PCAP packet time: " + str(datetime.fromtimestamp(p.time)))
    print("System current time: " + str(datetime.now()))
    break
```

chain.from_iterable appears to be calling the scapy Packet constructor, which sets packet time to host time, instead of extracting the packet time recorded in the pcap file. For me this behaviour was unexpected, so bug or feature?

I'd upload the capture file, if I knew how :-(

**Comment by gpotter2** [comment]
This is pretty normal. The `time` attribute matches the pcap time only on the link (=first) layer.
The `time` attribute of a sub-layer matches the time this packet was created in Scapy's internal memory. It's not a "feature" or a "bug" per-se, it's just how it currently works.

So you need to do your filtering after catching the timestamp, for instance
```
for pkt in packets:
    pkt.time
    report = pkt[
```

**Comment by jbipre2** [comment]
Got it, thankyou for your prompt reply.

James Bishop

Scientific Officer

European Commission
Directorate-General Joint Research Centre
E.2 Unit

Via E. Fermi 2749, TP 723
I-21027 Ispra (VA), Italy
+39 0332 786225
james.bishop@ec.europa.eu

________________________________
