### ISSUE TITLE
when using "session=TCPSession", cannot get all TCP packets by using pkt.haslayer(TCP)

### ISSUE THREAD

**Issue by Qnner** [secdev/scapy#2824]
#### Brief description

I'm still stuck with matching http request and responses #2817 . A gitter user gived me a suggestion ：
keep all TCP packets and then I can match req & res myself whitout using function "answers".
I found that, when using TCPSession, I cannot get all TCP packets by using pkt.haslayers， it worked without TCPSession.

#### Environment

-   Scapy version: `2.4.4`
-   Python version: `3.6`
-   Operating System: `Centos 7.6`

#### How to reproduce

here's my code
```
# coding=utf-8


from scapy.layers.http import HTTPResponse, HTTPRequest
from scapy.layers.inet import TCP, IP
from scapy.sendrecv import sniff
from scapy.sessions import TCPSession

GRL = []  # global request list
GTL = []  # global TCP list


def packet_parse(pkt):
    """
    This function is executed whenever a packet is sniffed
    """
    if pkt.haslayer(TCP):
        GTL.append(pkt)
    if pkt.haslayer(HTTPRequest):
        print('》》》sniff a request')
        GRL.append(pkt)
        print("len GTL:{}, len GRL: {}".format(len(GTL), len(GRL)))
    elif pkt.haslayer(HTTPResponse):
        print('》》》sniff a request')
        req_pkt = find_request(pkt)
        req_pkt_seq = req_pkt[TCP].seq
        len_GTL = len(GTL)-1
        while len_GTL > 0:
            print("TCP seq: ", GTL[len_GTL][TCP].seq)
            print("TCP ack: ", GTL[len_GTL][TCP].ack)
            print("HTTP TCP seq: ", req_pkt_seq)
            print("》》》")
            len_GTL -= 1


def find_request(pkt):
    """
    """
    if len(GRL) > 20:
        print("=====》 traffic jam! the len of line is ", len(GRL))
    for i in GRL:
        if pkt[HTTPResponse].answers(i) == 1:
            # GRL.remove(i)
            return i


if __name__ == "__main__":
    sniff(
        offline=r'./pcaps/long_request.pcapng',
        prn=packet_parse,
        filter='tcp and (port {})'.format(8080),
        session=TCPSession
    )
```

#### Actual result
I'v removed the same slice
**without TCPSession**:

》》》sniff a request
len GTL:4, len GRL: 1
》》》sniff a request
......SAME SLICE REMOVED......
TCP seq:  3005300363
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005298903
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005297443
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005295983
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005294523
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005293063
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005291603
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3005291603
TCP ack:  3473638400
HTTP TCP seq:  3005291603
》》》
TCP seq:  3473638399
TCP ack:  3005291603
HTTP TCP seq:  3005291603
》》》

**using TCPSession**:

》》》sniff a request
len GTL:4, len GRL: 1
》》》sniff a request
......SAME SLICE REMOVED......
TCP seq:  3005300363
TCP ack:  3473638400
HTTP TCP seq:  3005300363
》》》
TCP seq:  3005291603
TCP ack:  3473638400
HTTP TCP seq:  3005300363
》》》
TCP seq:  3473638399
TCP ack:  3005291603
HTTP TCP seq:  3005300363
》》》
#### Related resources
[long_request.zip](https://github.com/secdev/scapy/files/5254051/long_request.zip)

**Comment by gpotter2** [comment]
Please don't open multiple issues for the same issue.
Please add this info to the previous one

**Comment by gpotter2** [comment]
Please also note that this isn't a forum but a bug tracker.
