### ISSUE TITLE
NameError: global name 'ETH_P_ALL' is not defined

### ISSUE THREAD

**Issue by icecolor-wiattack** [secdev/scapy#2825]
#### Environment

-   Scapy version: `The latest version, just git pull down‘
-   Python version: `python ２７`
-   Operating System: `ubuntu 18.04`

#### How to reproduce

<!NameError: global name 'ETH_P_ALL' is not defined>

I was able to use this code a month ago.

 L2socket(type=ETH_P_ALL, iface=ifname, *arg, **karg

**Comment by guedou** [comment]
Please use the issue template.
