### ISSUE TITLE
NameError: global name 'ETH_P_ALL' is not defined

### ISSUE THREAD

**Issue by icecolor-wiattack** [secdev/scapy#2827]
#### Environment

-   Scapy version: `2.4.4rc2.dev30
`
-   Python version: `python 2.7.17`
-   Operating System: `ubuntu 18.04`

#### How to reproduce

from scapy.config import conf
from scapy.sessions import DefaultSession
 if not sniff_sockets or iface is not None:
            if L2socket is None:
                L2socket = conf.L2listen
            if isinstance(iface, list):
                sniff_sockets.update(
                    (L2socket(type=ETH_P_ALL, iface=ifname, *arg, **karg),
                     ifname)
                    for ifname in iface
                )
            elif isinstance(iface, dict):
                sniff_sockets.update(
                    (L2socket(type=ETH_P_ALL, iface=ifname, *arg, **karg),
                     iflabel)
                    for ifname, iflabel in six.iteritems(iface)
                )
            else:
                sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
                                       *arg, **karg)] = iface
#### Actual result

NameError: global name 'ETH_P_ALL' is not defined

#### Expected result

There is no error message, the program executes normally

No error message should appear, the program can be run directly

**Comment by gpotter2** [comment]
Please note that this is not a forum. If you have an issue within your program and not scapy (as simple as not importing `ETH_P_ALL`: `from scapy.data import ETH_P_ALL`) this is not the place to post it.

You'd rather use stackoverflow or our gitter.

Thanks
