### ISSUE TITLE
Syntax errors in Packet.command output when using VolatileValue

### ISSUE THREAD

**Issue by ThomasFaivre** [secdev/scapy#2828]
Hi all,

VolatileValue class is not handled properly in Packet.command method. This results in syntax errors when using output of command method.

#### Environment

-   Scapy version: Latest (9486bb2cef76)
-   Python version: 3.7.3
-   Operating System: Debian 10

#### How to reproduce

```
>>> eval(ICMPv6NIQueryNOOP().command())                                                                                                                       
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-b772ab6aa3ea>", line 1, in <module>
    eval(ICMPv6NIQueryNOOP().command())

  File "<string>", line 1
    ICMPv6NIQueryNOOP(nonce=<RandBin>)
                            ^
SyntaxError: invalid syntax
```

#### Expected result

This should return an instance of ICMPv6NIQueryNOOP. From v2.4.0:
```
>>> eval(ICMPv6NIQueryNOOP().command())
<ICMPv6NIQueryNOOP  |>
```

#### Related resources

A git bisect gave me this commit:
de079743169414141b24026c656eace4d33e7d78

I can try to fix this, but I am not sure what should be done. Here are solutions I could think of:

 * Generate the value (call to _fix method right?): ICMPv6NIQueryNOOP(nonce='\x21...')
 * return the string required to instance another VolatileValue: ICMPv6NIQueryNOOP(nonce=RandBin())

The first solution loses the 'randomness' for the nonce, which can be bad (?). I don't know nonce for ICMPv6 but I know they are important for security reasons in IPsec so...
The second solution can crash if the VolatileValue is not imported prior to evaluation of the command output. Which is not an issue if using run_scapy or scapy.all.

Keep me posted if you want me to fix this ;-)

**Comment by guedou** [comment]
Thanks for reporting the issue and providing solutions =)

I will prefer #2 as the value was not provided by the user.

**Comment by ThomasFaivre** [comment]
I have a fix available at https://github.com/6WIND/scapy/tree/pr2828
Waiting on #2838 to avoid unnecessary conflicts.
