### ISSUE TITLE
Enhancement: Add ability to print packet contents into C/C++ type array

### ISSUE THREAD

**Issue by peterd-sky** [secdev/scapy#2830]
For example:

<pre>
>>> eth=Ether(dst="88:E0:F3:36:9F:01",src="1C:EA:0B:F8:B6:F8",type=0x8100)
...:vlan1=Dot1Q(vlan=0x200,type=0x8100)
...:vlan2=Dot1Q(vlan=0x100,type=0x86dd)
...:ip=IPv6(dst="20:01::01",src="20:01::02",nh=0x11)
...:udp=UDP(dport=3785,sport=1000,len=24)
...:raw=Raw(load="0123456789abcdef")
...:pkt=eth/vlan1/vlan2/ip/udp/raw
...:gen_array(pkt)
...:
uint8_t raw[] = { 0x88, 0xe0, 0xf3, 0x36, 0x9f, 0x01, 0x1c, 0xea,
                  0x0b, 0xf8, 0xb6, 0xf8, 0x81, 0x00, 0x02, 0x00,
                  0x81, 0x00, 0x01, 0x00, 0x86, 0xdd, 0x60, 0x00,
                  0x00, 0x00, 0x00, 0x18, 0x11, 0x40, 0x00, 0x20,
                  0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                  0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x20,
                  0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                  0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x03, 0xe8,
                  0x0e, 0xc9, 0x00, 0x18, 0xbd, 0x91, 0x30, 0x31,
                  0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39,
                  0x61, 0x62, 0x63, 0x64, 0x65, 0x66 };
</pre>

I have this working if this is seen as a valid enhancement to the tool and it doesn't already exist.

**Comment by guedou** [comment]
We already have the following:
```
chexdump(IPv6() / ICMPv6EchoRequest())
0x60, 0x00, 0x00, 0x00, 0x00, 0x08, 0x3a, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x80, 0x00, 0x7f, 0xbb, 0x00, 0x00, 0x00, 0x00
```

It does the same except the formatting and the variable declaration.

**Comment by peterd-sky** [comment]
That's perfect. Thanks for commenting. I was unaware of that command. This issue can be closed.
