### ISSUE TITLE
libpcap not recognized in Alpine container

### ISSUE THREAD

**Issue by cmulk** [secdev/scapy#2834]
#### Brief description

Libpcap not recognized in Alpine container
When running scapy sniff with a filter inside of an Alpine Linux docker container, filters do not apply and a warning message is printed:
```
WARNING: Cannot set filter: libpcap is not available. Cannot compile filter !
```
I have confirmed that libpcap and tcpdump are installed in the container. Further, this issue does NOT occur if using scapy 2.4.3 (everything else the same). Issue only occurs after upgrading to scapy 2.4.4

#### Environment

-   Scapy version: 2.4.4
-   Python version: 3.8.5
-   Operating System: Alpine (docker container `python:alpine`) on RaspberryPi (armv7)
-   Also confirmed the same behavior in `python:alpine` container on x64 linux host

#### How to reproduce

```
sniff(iface="eth0", filter="arp", count=10)
```

#### Actual result

Warning message and packets are captured without filter

#### Expected result

No warning message and packets should be filtered (to show only ARP in this example)

#### Related resources

![image](https://user-images.githubusercontent.com/17730096/94281555-6197f980-ff14-11ea-9156-6e82c57cf76c.png)

**Comment by gpotter2** [comment]
Hmm, That's weird. We moved from using bash calls to tcpdump to get the filters compiled (which was a bit messy), to calls to libpcap API's directly in 2.4.4.

What happens if you try `import scapy.libs.winpcapy` ?

**Comment by guedou** [comment]
I cannot reproduce the issue on x86_64 with a fresh alpine Docker image.

```
~/scapy # git status -sb
## master...origin/master
~/scapy # apk list libpcap
libpcap-1.9.1-r2 x86_64 {libpcap} (BSD-3-Clause) [installed]
~/scapy # uname -a
Linux d54693d89240 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 Linux
```

**Comment by cmulk** [comment]
Ok I agree, I also cannot reproduce this with plain `alpine:latest` image. There must be something "special" about the `python:alpine` image in particular. I am good with closing this, thanks all!


[python_alpine.txt](https://github.com/secdev/scapy/files/5286758/python_alpine.txt)
