### ISSUE TITLE
http_request not producing web page

### ISSUE THREAD

**Issue by ngiru10** [secdev/scapy#2836]
http_request is unable to open web page and returns with error that a random file that doesnt exist in the "/tmp/" directory was unable to be opened. 

#### Environment

-   Scapy version: 2.4.4
-   Python version: 2.7.18, python3: 3.7.7
-   Operating System: Kali linux 2020.2

#### How to reproduce

load_layer("http")
http_request("10.10.10.10","/test", port=80, display=True)

#### Actual result

"Failed to open URL"file:///tmp/scapyWCU4cO.html". Error when getting information for file 'tmp/scapyBSVkz0.html': No such file or directory."

#### Expected result

Opens browser with the used IP and path used to display contents.

**Comment by guedou** [comment]
This works fine for me. What is the content of `conf.prog.universal_open`? Does it work when `display=False`?

**Comment by gpotter2** [comment]
Closed for inactivity
