### ISSUE TITLE
Automaton errors with runbg()

### ISSUE THREAD

**Issue by EviLDgL** [secdev/scapy#2841]
when an automaton is used with runbg() and crashes (with an exception) there is no way of noticing this in the main thread and the main thread just times out

**Environment**
-scapy version 2.4.4
-python2 version: 2.7 || python3 version:3.6.9
-os: ubuntu

**Problem long term**
recently im working with the scapy automaton as state machines for different protocol stacks and run into some debug difficulties. When an automaton is used via runbg() and it runs into some unexpected error (maybe missing layer ect.) it just throws and exception and stops. In the parent thread there is now the problem that it doesnt see the automaton stopped working and times out after a while.

i think it would be a nice idea to have an mechanism that informs the main thread that the child thread automaton just stopped working. is there any way to implement maybe a state that catches all the "classic" exceptions? its not about recovering the actual automaton working process. with such a mechanism it would be possible to log the path of the automaton and print it out after it stopped working.

**Comment by gpotter2** [comment]
I hear you but I'm not sure what we can do.

All `runbg()` does is basically start the automaton in a new thread. Bringing exceptions back to the main thread would be a giant overhead. You can probably test your automaton using `run()'.

It could be possible to, for instance, use a `logging` logger to print the stacktraces but this should be only done when running `runbg`, and eventually wouldn't actually do more than what's already in place (stacktraces are still shown when running on threads).

This sounds like a `wontfix` but I'm open to discussion.

**Comment by gpotter2** [comment]
Closed for inactivity
