### ISSUE TITLE
Default IPv6 route overwrites "iface" argument of send

### ISSUE THREAD

**Issue by oXis** [secdev/scapy#2879]
#### Brief description
Cannot send an IPv6 packet on a specific interface using `iface` argument of `send`

#### Environment

-   Scapy version: 2.4.4
-   Python version: 3.8.5
-   Operating System: Manjaro (up-to-date)

#### How to reproduce

Install vmware, `vmnet1` should be up. `enp42s0` is the default interface. Fire up wireshark and sniff on `enp42s0`.

#### Actual result
```python
>>> send(IPv6(dst="fe80::2d85:c733:b1:eaf9"), iface="enp42s0")
WARNING: Mac address to reach destination not found. Using broadcast.
.
Sent 1 packets.
```

Works, wireshark reports an IPv6 packet.

```python
>>> send(IPv6(dst="fe80::2d85:c733:b1:eaf9"), iface="vmnet1")
WARNING: Mac address to reach destination not found. Using broadcast.
.
Sent 1 packets.
```

Doesn't work, the packet is actually sent to `enp42s0`, we can see it in wireshark.

#### Expected result

The packet should be sent to `vmnet1`.

#### Related resources

If you remove `enp42s0` and try again, it works, and the packet is sent to `vmnet1` correctly and appears in wireshark.
```python
>>> conf.route6.remove_ipv6_iface("enp42s0")
>>> send(IPv6(dst="fe80::2d85:c733:b1:eaf9"), iface="vmnet1")
WARNING: The conf.iface interface (enp42s0) does not support IPv6! Using vmnet1 instead for routing!
WARNING: The conf.iface interface (enp42s0) does not support IPv6! Using vmnet1 instead for routing!
WARNING: more The conf.iface interface (enp42s0) does not support IPv6! Using vmnet1 instead for routing!
WARNING: Mac address to reach destination not found. Using broadcast.
.
Sent 1 packets.
```

It seems that the packet is always sent to the default route6, even when `iface` is specified. Is it a bug or am I doing something wrong :thinking: ?
I can't find a way to create a default scapy internal route6...

Thanks :+1:

**Comment by gpotter2** [comment]
Hi, could you retry using the master branch ?
If it still doesn't work, could you provide the output of `conf.ifaces`?
Thanks!

**Comment by oXis** [comment]
Tested on master branch, same results.

```python
>>> conf.ifaces
Source  Index  Name      MAC                IPv4           IPv6                    
sys     1      lo        00:00:00:00:00:00  127.0.0.1      ::1                     
sys     2      enp42s0   Micro-St:3b:c5:c5  192.168.0.150  fe80::3538:7f84:e10:e62a
sys     3      virbr0    RealtekU:20:db:af  192.168.122.1                          
sys     5      vmnet1    VMware:c0:00:01    172.16.237.1   fe80::250:56ff:fec0:1   
sys     6      vmnet8    VMware:c0:00:08    192.168.155.1  fe80::250:56ff:fec0:8   
sys     7      vboxnet0  0a:00:27:00:00:00  192.168.56.1   fe80::800:27ff:fe00:0
```

**Comment by gpotter2** [comment]
Sorry could you also provide the output of `conf.route6` ? Feel free to anonymize some entries (same for the above message) but please make sure it remains consistent. thanks

**Comment by oXis** [comment]
```
>>> conf.route6
Destination                   Next Hop  Iface     Src candidates            Metric
::1/128                       ::        lo        ::1                       256   
fe80::/64                     ::        enp42s0   fe80::3538:7f84:e10:e62a  100   
fe80::/64                     ::        vmnet1    fe80::250:56ff:fec0:1     256   
fe80::/64                     ::        vmnet8    fe80::250:56ff:fec0:8     256   
fe80::/64                     ::        vboxnet0  fe80::800:27ff:fe00:0     256   
::1/128                       ::        lo        ::1                       0     
fe80::250:56ff:fec0:8/128     ::        vmnet8    fe80::250:56ff:fec0:8     0     
fe80::800:27ff:fe00:0/128     ::        vboxnet0  fe80::800:27ff:fe00:0     0     
fe80::3538:7f84:e10:e62a/128  ::        enp42s0   fe80::3538:7f84:e10:e62a  0
```

IPv6 addresses are link-local so it shouldn't be an issue with disclosing unwanted data, I think xD

**Comment by gpotter2** [comment]
What's `resolve_iface("vmnet1")` and `resolve_iface('vmnet1").l3socket()` ?

**Comment by gpotter2** [comment]
I'm pretty sure you should be using a layer 2 socket to specify the socket. On BSD, using a layer 3 socket re-guesses the destination address on each packet sent:

https://github.com/secdev/scapy/blob/e3462561c7301605d177734a58176dfdb3c4136c/scapy/arch/bpf/supersocket.py#L362-L383

I'm pretty sure this is the expected behavior. If you wanted to force an interface, you would have used something like

```python
sendp(Ether()/IPv6()...., iface="eth0")
```

I however agree that this is less than clear. Maybe we should just drop the `iface=` argument for layer 3 sockets... What do you think @guedou @p-l-. This is very similar to what was discussed in https://github.com/secdev/scapy/pull/2356

**Comment by oXis** [comment]
It works when adding an Ethernet layer. Thanks :+1:

**Comment by oXis** [comment]
So I was using the wrong function and should have used `sendp` instead of `send`. `iface=` is ignore with `send`.
Thanks :+1:

**Comment by gpotter2** [comment]
Yes but this is very unclear. We shouldn't allow `iface=` if it does nothing... we need to clarify this

**Comment by p-l-** [comment]
> Yes but this is very unclear. We shouldn't allow `iface=` if it does nothing... we need to clarify this

My "point of view" on this is clear: `p`-functions (`sendp`, `srp`, etc.) send L2 packets to `conf.iface` which can be overridden using the `iface=` parameter. non-`p`-functions (`send`, `sr`, etc.) send L3 packets using the routing table `conf.routes`. We might want to offer to use an alternate routing table or route using a `route=` and/or `routes=` parameter(s).

**Comment by guedou** [comment]
I agree with @p-l- analysis.

The behavior with link-local addresses is a bit counter intuitive as a link-local prefix exists per interface and Scapy `conf.iface` and `iface=` are not synced.

**Comment by p-l-** [comment]
There is indeed those link-local addresses. Technically, we could have the same kind of issues with IPv4 network 169.254.0.0/16, but it is far less used (and needed).

**Comment by guedou** [comment]
Except that link-local addresses are used in IPv6 to MAC resolution =/

**Comment by p-l-** [comment]
FWIW that's also the case for multicast IPv4 addresses (which, also, may be exceptions to the routing table I believe).

So I can see two options there, for link-local or multicast destination addresses:
* we accept the `%iface` suffix in destination addresses
* we accept an `iface=` parameter for l3 commands (that is only used for link-local addresses or multicast destinations, and for the sniffing thread of `sr*` functions)

What do you think?

**Comment by guedou** [comment]
I like the idea of using the interface identifier `%` !
