### ISSUE TITLE
Guide to scapy/contrib or new protocols

### ISSUE THREAD

**Issue by kallolkk** [secdev/scapy#289]
Hi,
There are a lot of new protocols included in scapy/contrib folder. But there is not enough instruction on how to use them. Can anyone suggest where i can find them.
Thanks 

Best regards
Kallol

**Comment by guedou** [comment]
Thanks for your interest in Scapy.

Some `contrib/` layers have a corresponding `.uts` file that provides some examples (has `gtp.uts`).
