### ISSUE TITLE
Issue with DADict hasattr call

### ISSUE THREAD

**Issue by Matthewar** [secdev/scapy#2896]
#### Brief description

`DADict` class always returns true for `hasattr` calls, even if the attribute isn't included.

#### Environment

-   Scapy version: `2.4.4`
-   Python version: `2.7` (I think the issue is for all versions though)
-   Operating System: `RHEL 7.5`

#### How to reproduce

https://github.com/secdev/scapy/blob/bfd9c52af61978ac872d3c0bf5eef81168d88ca9/scapy/dadict.py#L109-L115
There is no check for if the `__getattr__` function reaches the end without returning, I think in those cases it should raise an `AttributeError`

**Comment by gpotter2** [comment]
Funny that you report this now, this was found (and fixed) in https://github.com/secdev/scapy/pull/2865.
We should have it merged soon enough, thanks for the report !
