### ISSUE TITLE
UDS MultipleTypeField problem

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2897]
In this packet, I have two ConditionalFields with the same name. https://github.com/secdev/scapy/blob/720200b623b3b2700e8622a8a90fb4d5fc7c7ba1/scapy/contrib/automotive/uds.py#L920-L939

My problem here is, that I don't know how I can replace these ConditionalFields with one MultipleTypeField, since the ConditionalFields are in different positions of the packet. 

Could you please give me hint, how to solve this?

**Comment by gpotter2** [comment]
Put `DTCSeverityMask` before the first `DTCStatusMask` and extend the condition of the first `ConditionalField` to also include the second one. Then delete the second one

**Comment by polybassa** [comment]
Thanks. Didn't saw that :-)
-- 
Viele Grüße

Nils Weiß
