### ISSUE TITLE
PacketField should not take the remain parameter in __init__ 

### ISSUE THREAD

**Issue by rscharp** [secdev/scapy#2902]
I was reviewing some of the lovely Scapy code. Thx a lot for contributing this project to the FOSS world.

This is not a major issue, so need to worry or hurry. It's just something I was wondering when reading the code.

While looking into the PacketField implementation that extends StrField, I was wondering why the remain parameter from StrField.__init__() is kept also inside the PacketField.__init(). All the methods from StrField that make use of remain are overwritten. In the other sub-classes of StrField the remain part was dropped. So I think it would be consistent to do so for the  PacketField, too.

Ralph

**Comment by gpotter2** [comment]
Thanks for the note.
It might be easier if you simply submit a PR. 😄

**Comment by rscharp** [comment]
Ok, my company has some rules for that I need to find out first. But let's just do it ;)

**Comment by rscharp** [comment]
Can you please have a short look on the PR I did as draft. With the BGP protocol, I ran into some broken code. I gave details in the PR text.

Please let me now if it is ok to have 3 commits or if things should be squashed into a single one. I never did git rebase, but perhaps it is time to start with it ;)
