### ISSUE TITLE
Discussion: fix RawVal

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#2917]
I'm currently typing stuff. What's the purpose of `RawVal` ? Same for `field_pos_list`.
It's pretty annoying to type and is NEVER used within Scapy, the doc or any example. The only clue we have is this part:

https://github.com/secdev/scapy/blob/9897371226fca14e153774741987b32cdde3af3a/scapy/packet.py#L662-L668

@guedou @p-l- do you mind if we remove `RawVal` without further notice ? I don't think someone ever figured what I just did here since this was never documented anywhere..

**Comment by p-l-** [comment]
Fine for me. Maybe we should ask @phil777?

**Comment by gpotter2** [comment]
Thanks for the quick answer. @phil777 @guedou Do you have an opinion on this?

**Comment by guedou** [comment]
The commit is quite interesting:
```
git log --stat a02b520d2 -1
commit a02b520d25c946d272ef9ec757edd5418172fe38
Author: Phil <phil@secdev.org>
Date:   Thu Oct 22 15:43:33 2009 +0200

    Added RawVal object that ca be assigned to any packet field and will inserted as-is in the packet string
    
    ex:
    >>> a=IP(len=RawVal("####"))
    >>> str(a)
    'F\x00####\x00\x01\x00\x005\xb5\x00\x00\x7f\x00\x00\x01\x7f\x00\x00\x01\x00\x00'

 scapy/packet.py | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)
```

I have never seen it in action, and I guess that @phil777 might know. I am ok to remove it: the commit is 11 years old, and we don't have a use for this code =)

**Comment by gpotter2** [comment]
Oh that feature is actually pretty cool. I don't think it's possible as of right now to inject custom bytes or string in a field that doesn't support it. This is almost certainly broken as of right now, but I think it's worth fixing.
