### ISSUE TITLE
TLS1.3 Extension for SignatureAlgorithmsCert is using wrong Type value

### ISSUE THREAD

**Issue by GSBhub** [secdev/scapy#2930]
**Brief description**
"Type" is set to 0x31 (PostHandshakeAuth), should be using 0x32 (SignatureAlgorithmsCert).

https://github.com/secdev/scapy/blob/e79833e46ec33be0880447a1983e3840676302fe/scapy/layers/tls/extensions.py#L658-L667

**Comment by gpotter2** [comment]
This is, according to https://tools.ietf.org/html/rfc8446#section-4.2, very correct. Thanks for the report
