### ISSUE TITLE
Bluetooth Low Energy Packet SM_Public_Key received via BluetoothUserSocket is incomplete

### ISSUE THREAD

**Issue by byte-arts** [secdev/scapy#2942]
Hello,

i am not totally sure but i think i found a bug within the scapy Bluetooth SM_Public_Key packet.
The only way to make this reproducible is "a bit" complicated and requires the use of the ble_mitm module of mirage. Maybe some scapy expert has an idea how to reproduce this scenario in scapy.

I know this is not very easy to reproduce, if you have any idea how to verify this more easily or need more information please let me know! Thanks in advance!

#### Brief description
After receiving a SM_Public_Key packet via BluetoothUserSocket the packet is incomplete, the key_x field contains only 22 bytes instead of 32 and the key_y field is empty. See btmon log for correct values.

#### Actual result

>###[ HCI header ]### 
  type      = ACL Data
###[ HCI ACL header ]### 
     BC        = 0
     PB        = 2
     handle    = 0
     len       = 27
###[ L2CAP header ]### 
        len       = 65
        cid       = 6
###[ SM header ]### 
           sm_command= 12
###[ Public Key ]### 
              key_x     = '\x1a\xd7\xa2\xe6\xcf\x8a*\xea\x01\xe1\x02\xe4u\xdd~\xb9j\xd5d\xdd\xd3\xd3'
              key_y     = ''

#### Expected result
In btmon:
>> ACL Data RX: Handle 0 flags 0x01 dlen 15                                            #1011 6582.158318
      SMP: Pairing Public Key (0x0c) len 64
        X: 1ad7a2e6cf8a2aea01e102e475dd7eb96ad564ddd3d327d5dcd2afb6311b3a63
        Y: 341fbed237c849dfa006fd854902a6c28d63b483f17bdbbdf70938fd8a24085f

#### Environment

-   Scapy version: 2.4.4.dev156
-   Python version: Python 3.8.5
-   Operating System: Ubuntu 20.04 LTS
-   Mirage version: 1.1 (https://github.com/RCayre/mirage)
-   bluez version: 5.53

#### How to reproduce

Requirements:
- 2 Bluetooth Low Energy (BLE) HCI devices with Bluetooth version > 4.2
- BLE slave device which supports Secure Connections Pairing*
- BLE master device which supports Secure Connections Pairing**

*I used another Bluetooth Dongle and bluetoothctl with the following configuration:
Start bluetoothctl and select the required device via BDADDR:
>sudo bluetoothctl
select AA:BB:CC:DD:EE:FF

Configure a slave device by inserting the following code:
>menu advertise
manufacturer 0xffff 0x12 0x34
name myDevice
back
menu gatt
register-service e2d36f99-8909-4136-9a49-d825508b297b
yes
register-characteristic 0x1234 read
0x42
register-characteristic 0x4567 read,write
0x41
register-application
back
pairable on
advertise on

** I used a smartphone and nRF Connect App

Clone mirage repository:

>git clone https://github.com/RCayre/mirage

To printout the packet directly after receiving add following code in line 93 of file <mirage_install_folder>/libs/bt.py:
>if SM_Public_Key in recv:
        recv.show()

Install mirage:
>sudo python3 setup.py install

Start ble_mitm module with the following command:
>sudo mirage ble_mitm TARGET=AA:BB:CC:DD:EE:FF CONNECTION_TYPE=random INTERFACE1=hci1 INTERFACE2=hci2 SLAVE_SPOOFING=yes MASTER_SPOOFING=yes

(How to start this module depends on the capability of your hci device, e.g. able to change BDADDR or the use of random or public address)

Start btmon for the HCI device which you provided as INTERFACE2 in the previous step. So in my case:
>sudo btmon -i 2 (-w filename.pcap)

Scan and connect to the device and force bonding with master device. mirage ble_mitm module will terminate after this, since the handling of this messages is not implemented(It is not important for this issue) .

See printed SM_Public_Key message in console and compare to btmon log.

**Comment by gpotter2** [comment]
That's totally possible. Could you please share a pcap containing a packet that replicates the issue?
Thanks for the report !

**Comment by byte-arts** [comment]
Thank you for the fast reply. Attached two pcap files.

[btmon1.pcap.txt](https://github.com/secdev/scapy/files/5500181/btmon1.pcap.txt)
[scapy.pcap.txt](https://github.com/secdev/scapy/files/5500183/scapy.pcap.txt)

By verifying my pcap files, i recognized what could cause the issue. The SM_Public_Key packet is originally transmitted in 3 packets (No. 75, 76, 77), reassembled in packet No. 77. From the Scapy log it seems that the first of this three packets is used to generate the scapy SM_Public_Key Packet, which therefore is incomplete. 
![btmon](https://user-images.githubusercontent.com/73175682/98347520-c9635900-2017-11eb-9242-43d3aa8cd91e.png)

![scapy](https://user-images.githubusercontent.com/73175682/98346883-efd4c480-2016-11eb-8e72-a8b8dd9cf07d.png)

Note: I saved only the received scapy packets with wrpcap until the condition "SM_Public_Key in recv" applies, thats why btmon log contains more packets.
From bt.py
```
def _recv(self):
    self.recvLock.acquire()
    recv = self.socket.recv()
    self.pkts.append(recv)
    if SM_Public_Key in recv:
        wrpcap("scapy.pcap", self.pkts)
    self.recvLock.release()
        return recv

**Comment by gpotter2** [comment]
I don't think we've implemented bluetooth packet reassembly. That's likely the issue here

**Comment by byte-arts** [comment]
Can i do anything to help fixing this?

**Comment by gpotter2** [comment]
Thanks for the example !
