### ISSUE TITLE
Issue: Man in the middle attack and TCP handshake

### ISSUE THREAD

**Issue by Antonio-Dominguez** [secdev/scapy#2958]
Hi, I am using scapy to perform a Man-in-the-middle attack between two machines (A and B) in my WLAN. I have verified the configuration using Wireshark in the victim's machine and it seems that I am able to sniff packets and spoof MAC addresses. 
Machine A is hosting a server and machine B tries to connect to it. However, the TCP handshake does not work for some reason that I do not know. A and B receive the TCP packets with the spoofed MACS but they keep retransmitting the SYN request and SYN ACK. It seems that the server receives the SYN packet but never receives the client's ACK response. This can be seen in the attached screenshot from machine A.
I thought it was a checksum problem but it does not work either... Does anyone know how to solve this?

Thank you in advance!

-   Scapy version: Version 2.4.4
-   Python version: Python 3.8.6
-   Operating System: Kali Linux

<img width="1280" alt="Screen Shot 2020-11-16 at 3 46 51 AM" src="https://user-images.githubusercontent.com/48263822/99207485-5f3c7800-27be-11eb-8348-88537db92cd5.png">

`

def processingpacket(pckt):

    poison(IP_victim, MAC_victim, IP_dest, MAC_dest, own_MAC)

    try:
        if pckt.haslayer(IP):
            #print("IP")
            #print("from {} to {}".format(pckt[IP].src, pckt[IP].dst))

            if pckt.haslayer(TCP):
                #print("TCP")
                if pckt.haslayer(Raw):
                    #print("Raw")
                    payload = pckt[Raw].load

            if pckt[IP].dst == IP_victim:
                pckt[Ether].dst = MAC_victim
            elif pckt[IP].dst == IP_dest:
                pckt[Ether].dst = MAC_dest

            del(pckt[Ether].chksum)
            del(pckt[IP].chksum)
            del(pckt[TCP].chksum)
            print("checksum")
            print(pckt[TCP].chksum)

        sendp(pckt, verbose=0)

    except KeyboardInterrupt :
        print("Reverting MAC spoofing")
        # revert(IP_victim, IP_gateway, MAC_victim, MAC_gateway)
        revert(IP_victim, IP_dest, MAC_victim, MAC_dest)

`

**Comment by gpotter2** [comment]
Hi and thanks for your interest in Scapy.
Please note that this a bug tracker, and not a forum. You should ask these kind of questions on forums like stackoverflow.
Have a good day
