### ISSUE TITLE
Adding support for MUD URL option in DHCP layer

### ISSUE THREAD

**Issue by JKRhb** [secdev/scapy#2961]
I recently wanted to test if the [MUD URL DHCP Option](https://tools.ietf.org/html/rfc8520#section-10) is correctly set by a DHCPv6 client but realized that the option is not yet supported by scapy, [as it seems](https://github.com/secdev/scapy/blob/308327f0bea599846c3f6f412c747df58b11eea3/scapy/layers/dhcp6.py). I therefore wanted to open this issue as a feature request or rather ask if the implementation of this option is desired. If so, I would probably try to implement it myself :)

**Comment by gpotter2** [comment]
Hi & thanks for your interest in Scapy.
We don't really track feature requests on here, because this is a bug tracker. If you want to implement it yourself, we'll be happy to review the PR, and eventually merge it !
I'll be closing this.

**Comment by JKRhb** [comment]
Thank you for your answer and sorry for the wrong usage of the issues! I will open a PR then once I have implemented a first version and I'm looking forward to your feedback :)
