### ISSUE TITLE
read_block_idb is not properly documented

### ISSUE THREAD

**Issue by rus-kilian** [secdev/scapy#2972]
While trying to stand up a minimal code to read a PCAPNG, update the IDB to set the interface name and ID and write back the PCAPNG file, it seems there is neither sample code nor any good documentation on how to use read_block_idb. Please add some minimal example on how to work with PCAPNG and IDB.

**Comment by p-l-** [comment]
Hi,

Thanks for your interest in Scapy and your question.

I'm not sure to understand what you want / need to do. PcapNg support in Scapy is very limited and can only be used to read files (there is a `PcapNgReader()` class, but no `PcapNgWiter()`, at least for now; `help(rdpcap)` will tell you you can read a PCAP or PCAPNG file, while `help(wrpcap)` will tell you you can write a PCAP file).

There is no way to manipulate the IDB for that reason: the sole purpose of this code is to read packets from a PCAPNG file, either via an iterator (`PcapReader()`) or via a `PacketList()` returned by `rdpcap()`.

**Comment by rus-kilian** [comment]
Hi Pierre,

* Pierre Lalet <notifications@github.com> [2020-11-22 18:25:15 -0800]:
>Thanks for your interest in Scapy and your question.
>
>I'm not sure to understand what you want / need to do. PcapNg support in
>Scapy is very limited and can only be used to read files (there is a
>`PcapNgReader()` class, but no `PcapNgWiter()`, at least for now;
>`help(rdpcap)` will tell you you can read a PCAP or PCAPNG file, while
>`help(wrpcap)` will tell you you can write a PCAP file).
>
>There is no way to manipulate the IDB for that reason: the sole purpose of
>this code is to read packets from a PCAPNG file, either via an iterator
>(`PcapReader()`) or via a `PacketList()` returned by `rdpcap()`.

Thanks for the explanation. Probably I just assumed that just because the
Reader is capable to producing both PCAP and PCAPNG, the writer would do
just the same. As said, I was just starting to try and come up with some
first code and found even the read IDB not even sufficiently well documented
to get the read loop together.

What I'm tring to achieve is also very easily answered: we have a dataplane
chain of forwarding hops that seem to be dropping packets along the way.
Thus, we want to "single pane of glass" to visualize where in the flow the
packets are getting dropped and refine our debugging there. What's already
available is the mergecap which will produce some single PCAPNG to look at
in wireshark. What we lack though is a good update tool for the IDB to
replace each "eth0" with something more meaningful to have a good way of
reading the produced output.

Of course we could also put all of the above business logic into a single
python scapy script, but initially we just wanted to have a combined PCAPNG
and discuss this with the vendor TAC before digging deeper with more
elaborate python-scapy code.

Best regards,
Kilian

**Comment by p-l-** [comment]
In that case, I think Scapy will not help you since you would have to write a PCAPNG file, which Scapy cannot do at this time.
I hope you'll find another way!
Pierre
