### ISSUE TITLE
Write multiple packets bytes to temporary PCAP file and sort it by timestamp

### ISSUE THREAD

**Issue by m-peko** [secdev/scapy#2976]
Hi there,

I would like to know if it is possible to write multiple packets bytes to temporary PCAP file? I know I can write a single packet bytes to PCAP file but what about batch of packets bytes? How can I sort this generated PCAP file by packet timestamps?

Thank you very much

**Comment by guedou** [comment]
Please ask your question on gitter. This is a bug tracker, not a forum.
