### ISSUE TITLE
TLS1.2 parsed as TLS1.3

### ISSUE THREAD

**Issue by plutec** [secdev/scapy#2978]
#### Brief description

sniff function doesn't parse TLSServerHello correctly

#### Environment

-   Scapy version: `commit 9d5827f3`
-   Python version: `python 3.7.5`
-   Operating System: `Ubuntu 19.10`

#### How to reproduce

Parsing a pcap with sniff function. The pcap contain the TLS communication of a connection to a webpage. It exchanges also the Certificates. The TLS connection is 1.2 (according Wireshark and also analyzing the data exchanged). 
The TLSServerHello is parsed as 'scapy.layers.tls.handshake.TLS13ServerHello' instead TLSServerHello (because is TLS1.2)

Also, I think related, the TLSCertificate is not parsed and detected as 'scapy.packet.Raw'

#### Actual result

The TLSServerHello is not well parsed.

**Comment by gpotter2** [comment]
Hi,
Without a pcap, there's very little we can do. TLS is a complex protocol
Thanks for your interest in scapy.

**Comment by plutec** [comment]
I cannot publish that pcap, but I'm going to try to reproduce the behavior this evening at home.

**Comment by plutec** [comment]
Sorry, at home I'm not able to reproduce it. Maybe it's a problem with the machine which i'm working on.

Thanks for all your efforts!!
