### ISSUE TITLE
save RTP packet in pcap file

### ISSUE THREAD

**Issue by alexrc20** [secdev/scapy#2980]
I have this code to write a RTP packet in a pcap:
`client = "192.168.10.1"
server = "192.168.10.5"
client_port = 5061
server_port = 5060

rtp = { 
        "sequence": 1,
        "timestamp": 1,
        "marker": 1,
        "payload_type": 17
    }

pkt= Ether()/IP(src=client, dst=server)/UDP(sport=client_port, dport=server_port)/RTP(**rtp)

wrpcap("rtp_pkt.pcap",pkt)`

The problem is that I see the packet as UDP in wireshark and not RTP. I can see it with SIP structures so I don't know where is the problem.

**Comment by gpotter2** [comment]
Hi, thanks for your interest in Scapy.
Please note that this is a bug tracker and not a forum. Please ask this kind of question on stackoverflow or on the gitter.
