### ISSUE TITLE
Discussion: Travis CI

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#2984]
Hi, since Scapy ran out of Travis-CI credits, would it make sense to consider some different CI-System for Linux root tests?

I checked the documentation of Gitlab, and it might be possible to connect Gitlab CI to Github.

**Comment by guedou** [comment]
It is possible but AFAIK we need to self host gitlab to do so. I am looking into running tests in parallels.

Do you think that it is possible to make the automotive tests run faster while achieving the same coverage?

**Comment by gpotter2** [comment]
We've actually talked about this internally.
The plan would be to reduce the travis load and ask for more credits (we can get OSS-only credits/month).

We would have already migrated everything to Github CI (but now I'm pretty happy that we're using various providers), but they block a few services that we use for our tests (ICMP...).

**Comment by polybassa** [comment]
@guedou AFAIK we could use gitlab.com, if Scapy get's accepted as OpenSource project. Than we would get gitlab CI credits for free and could connect our own runners to it. https://docs.gitlab.com/ee/ci/ci_cd_for_external_repos/github_integration.html

**Comment by polybassa** [comment]
@guedou I will try to make automotive tests faster, but it's kind of a balance between stability and duration.

**Comment by gpotter2** [comment]
Based on our current use of Travis, we would need something like 50k extra credits each month (we havea base of 10k).
(~50builds \* 60minutes \* 10credits/minutes=30k for linux builds + 50 \* 10 \* 50=25k for OSX). I'm going to contact the support. Fine with this @guedou @p-l- ?

We can also potentially move the OSX tests to Github CI, I will look into that.

**Comment by guedou** [comment]
@gpotter2 perfect plan!

**Comment by polybassa** [comment]
IMO 50 builds is to optimistic if we consider that most PRs require at least one change, sometimes even more.

**Comment by gpotter2** [comment]
Just removed the OSX builds from Travis, this increases to 83 builds. (we still haven't received the credits...)
We can always ask more later, I'm guessing it will be easier to ask for an increase once they have verified the validity of our project (could be wrong)

**Comment by gpotter2** [comment]
FEAR NOT, THEY JUST ANSWERED 😄

We've been granted 25k credits and they were kind enough to provide the metrics

```
Credits Consumption Metric
OS.              # CREDITS PER STARTED BUILD MINUTE
Linux.          10
Experimental FreeBSD.         10
Windows.         20
MacOS.         50
```

That's obviously not enough for our test suite but who knows. We could try out FreeBSD

**Comment by guedou** [comment]
Testing on FreeBSD will be super cool!
