### ISSUE TITLE
how to addIng two vlan tag to pcap file

### ISSUE THREAD

**Issue by hdihd9162** [secdev/scapy#2987]
hello
i have a pcap file i need to add two vlan tag to this pcap but i cant find solution
i found this

tcprewrite --enet-vlan=add --enet-vlan-tag=40 --enet-vlan-cfi=1 --enet-vlan-pri=4 --infile=input.pcap --outfile=output.pcap

but not work for two vlan tag its work for one vlan tag
can you help me?

**Comment by guedou** [comment]
This is not a forum but a bug tracker.
