### ISSUE TITLE
DNS compression fails if name being compressed is '.'

### ISSUE THREAD

**Issue by artrasmussen** [secdev/scapy#2989]
Created a reply to a query for A-record; it contains "ar=scapy.DNSRROPT(rrname=b'.', ...")  -- details below. When Scapy's dns_compress() function is applied, the one-byte name (single dot, '.') causes an exception.

Tested against latest development Scapy obtained Dec 1, 2020 using 'git clone https://github.com/secdev/scapy.git'
Python 3.6.9  Ubuntu 18.04.5 LTS 
(Believe the Python version and O/S have minimal relevance to the problem.)

The code sample below reproduces the problem. The code was created by capturing (using Wireshark) some DNS traffic and using the bytes captured by cutting and pasting to Python source file. Created a Scapy pkt using 'pkt = scapy.Ether(capturedBytes)'. Then used pkt.command() to create Python Scapy source to re-create the packet. Captured the output of the Python code pkt.command() and pasted into a new Python source file. Invoked dns_compress() on the result of re-creating the packet. Exception is show below.

SUGGESTED FIX: Do not attempt to apply compression to a name of length less than 2.
This is a possible fix - scapy/layers/dns.py   Lines 178-181 are the new code:
(My apologies - I don't know how to get a code block to show proper indentation)
I have not studied the code to see if there is a better repair.

`
...

176     for current, name, dat in field_gen(dns_pkt):
177         for part in possible_shortens(dat):
178             # Do not try to compress very short names
179             if len(part) <= 1: continue
180                 ### Moved the 'continue' to same line as 'if' -- Don't know how to indent in this code block, sorry.
181                 ###continue
182             # Encode the data
183             encoded = dns_encode(part, check_built=True)
...
`

`
  File "try_scapy_dns_compress_2.py", line 12, in <module>
    ar=scapy.DNSRROPT(rrname=b'.', type=41, rclass=1280, extrcode=0, version=0, z=0, rdlen=None)))
  File "/home/art/git/art/src/python/scapy_dns_compress_bug/.scapy_dns_compress_bug_venv/lib/python3.6/site-packages/scapy/layers/dns.py", line 193, in dns_compress
    pointer = chb(fb_index) + chb(sb_index)
  File "/home/art/git/art/src/python/scapy_dns_compress_bug/.scapy_dns_compress_bug_venv/lib/python3.6/site-packages/scapy/compat.py", line 275, in chb
    return struct.pack("!B", x)
struct.error: ubyte format requires 0 <= number <= 255

`

`
import scapy.all as scapy

pkt = scapy.dns_compress(
scapy.Ether(dst='70:85:c2:39:ae:94', src='cc:32:e5:4a:c6:e4', type=2048)/
scapy.IP(version=4, ihl=5, tos=0, len=83, id=64207, flags=2, frag=0, ttl=64, 
  proto=17, chksum=13288, src='192.168.69.1', dst='192.168.69.144')/
scapy.UDP(sport=53, dport=56554, len=63, chksum=46549)/
scapy.DNS(length=None, id=25156, qr=1, opcode=0, aa=0, tc=0, rd=1,
  ra=1, z=0, ad=0, cd=0, rcode=0, qdcount=1, ancount=1, nscount=0, arcount=1,
  qd=scapy.DNSQR(qname=b'hilton.com.', qtype=1, qclass=1),
  an=scapy.DNSRR(rrname=b'hilton.com.', type=1, rclass=1, ttl=300, rdlen=None, rdata='167.187.200.23'),
  ns=None,
  ar=scapy.DNSRROPT(rrname=b'.', type=41, rclass=1280, extrcode=0, version=0, z=0, rdlen=None)))

`

**Comment by artrasmussen** [comment]
A couple of minor tweaks to the suggested 'fix'.

**Comment by gpotter2** [comment]
Readable reproducible example
```
dns_compress(DNS(qd=DNSQR(qname=b'scapy.'), an=DNSRR(rrname=b'scapy.'), ar=DNSRROPT(rrname=b'.')))
```
