### ISSUE TITLE
Unexpected "Packet type: Multicast (2)"

### ISSUE THREAD

**Issue by triple-it** [secdev/scapy#3010]
#### Brief description

Unexpected "Packet type: Multicast (2)"

#### Environment
-   Scapy version: git-archive.dev304758016
-   Python version: Python 3.6.8
-   Operating System: Centos8

#### How to reproduce

from scapy.all import *
answer  = sr1(Ether()/IP(src=sys.argv[1],id=0,dst=sys.argv[2])/UDP(sport=RandShort(), dport=53)/DNS(ad=1,id=RandShort(
),rd=1,qd=DNSQR(qtype="A",qname="example.com")),verbose=1, timeout=10)
print(answer[DNS].summary())

#### Actual result

```
~~
root@# python3 t.py <local_ip> 8.8.8.8
Begin emission:
Finished sending 1 packets.

Received 96 packets, got 0 answers, remaining 1 packets
Traceback (most recent call last):
  File "t.py", line 3, in <module>
    print(answer[DNS].summary())
TypeError: 'NoneType' object is not subscriptable
root@#
~~

```

```
Frame 1: 87 bytes on wire (696 bits), 87 bytes captured (696 bits) on interface 0
    Interface id: 0 (any)
        Interface name: any
    Encapsulation type: Linux cooked-mode capture (25)
    Arrival Time: Dec 10, 2020 17:13:08.101198054 CET
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1607616788.101198054 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 87 bytes (696 bits)
    Capture Length: 87 bytes (696 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: sll:ethertype:ip:udp:dns]
Linux cooked capture
    Packet type: Multicast (2)                                     <--------- (Why???)
    Link-layer address type: 772
    Link-layer address length: 6
    Source: 00:00:00:00:00:00
    Unused: 0000
    Protocol: IPv4 (0x0800)

```
#### Expected result

Linux cooked capture
    Packet type: Unicast to us (0)

**Comment by triple-it** [comment]
Maybe related:
[https://stackoverflow.com/questions/48494885/how-to-send-packet-through-ppp-link-by-scapy](url)

**Comment by gpotter2** [comment]
You got no answer out of your `sr` call (it was none). You can't assume you'll get one.

Other than that the rest of the issue is extremely unclear (why are you throwing this random stackoverflow issue ?). Feel free to reopen when you can confirm this is a bug and not a misusage.
