### ISSUE TITLE
Integration with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [secdev/scapy#3039]
We've found [two issues( https://github.com/secdev/scapy/issues?q=author%3AGoogle-autofuzz ) while fuzzing scappy internally, and now are now working on getting it [into OSS Fuzz]( https://github.com/google/oss-fuzz/pull/4897 ).

It this something that would interest the project? We would only need an email address to send the crashes to.

Thanks

**Comment by guedou** [comment]
Thanks a lot for your proposal. That is really useful for the project. You can send the reports to guillaume@valadon.net
