### ISSUE TITLE
scapy srp method raise exception " can't concat str to bytes".

### ISSUE THREAD

**Issue by MUHAMMAD0KASHIF** [secdev/scapy#3050]
Hi,
**Environment:**
Scapy : 2.4.4
Python: 3.6
os: ubuntu
**Description**
I am using scapy for ARP ping but sometimes on a specific network it raises  can't concat str to bytes exception. I tried to find the issue but not getting it, one thing I observed is ARP packets from another smart tv on my network is it possible that it is creating issue  due conflict or something else. ISsue does not have defined pattern most of the time exception is raised while arp ping such ip that does not even has any connected device. Any help will be appreciated.

**Comment by guedou** [comment]
Please use gitter to ask your question.

By the way, the goal of the issue template is to be issued not deleted.
