### ISSUE TITLE
NTP TimeStampField causes loss of decimal precision

### ISSUE THREAD

**Issue by fdebrabander** [secdev/scapy#3052]
#### Brief description
The TimeStampField cannot be copied between NTP packets without it loosing decimal precision. This is likely caused by the python time library being used to convert values back and forth.

#### Environment
-   Scapy version: `2.4.4`
-   Python version: `3.6`
-   Operating System: `Ubuntu 18.04.5 LTS`

#### How to reproduce

```
pkt = NTP(orig=3819600631.703241999)
pkt2 = NTP(orig=pkt.orig)
assert bytes(pkt) == bytes (pkt2)
```

This is a problem because if you want to create an NTP reply, according to the RFC you need to copy the 'sent' field to the 'orig' field. 

```
response = NTP(orig=request.sent)
```

If you send this response with scapy, the 'sntp' command (tool from ntp.org) it will not accept the response with error "response org expected to match sent xmt".

#### Related resources
https://tools.ietf.org/html/rfc1769

**Comment by gpotter2** [comment]
I might be wrong but that looks to me like it's working as intended. The `sent` timestamp is calculated based on the packet creation time when not specified:
```python
NTP(bytes(NTP())).sent
```
it will change on every call, so it seems expected to me that the bytes representation differ.
Moreover
```python
NTP(bytes(NTP(orig=3819600631.703241999))).orig == NTP(bytes(NTP(orig=3819600631.703241999))).orig
```
so it doesn't look like the "issue" here is timefloat precision

**Comment by gpotter2** [comment]
I can't really replicate:
```python
NTP(bytes(NTP(orig=3819600631.703241999))).orig == 3819600631.703241999
```
returns True, it doesn't look to me like this is a loss in timefloat precision.
Your reproducible example looks wrong because the `sent` field is re-calculated based on `time.time()` on every build, because you didn't specify any. I'm not sure I understand what the issue is here

**Comment by fdebrabander** [comment]
Your example indeed returns True. But so does

```
NTP(bytes(NTP(orig=3819600631.703241999))).orig == 3819600631.703241911
```

**Comment by guedou** [comment]
Can you elaborate on the issue? It seems that you don't understand each other.

**Comment by fdebrabander** [comment]
I'm not very familiar with how scapy Fields work, so it's not very easy for me to pin point the exact bug in the source. My guess is the following;

- Receive an NTP packet with scapy (sniff)
- Scapy parses the timestamps in NTP packet to an internal format (maybe ntp.py line 83 ?), some decimals are dropped
- Create a reply packet, copy field from source packet to reply packet, as with ``reply = NTP(orig=request.orig)``
- Copied field is not bit-wise exactly the same, when reply is serialized
