### ISSUE TITLE
Dot11EltVendorSpecific has bug in some way

### ISSUE THREAD

**Issue by AmandaYaoYao** [secdev/scapy#3060]
Dot11EltVendorSpecific has bug in some way.

Hi, please parse the packet I give in attachment use Dot11EltVendorSpecific. You will not parse all of venfor ies.
In fact, this is some problem happen with Dot11EltCountry.
Because when I add this code will fix the parse problem.

```
for i, v in enumerate(Dot11EltCountry.fields_desc):
    if isinstance(v, ConditionalField):
        Dot11EltCountry.fields_desc[i] = ConditionalField(
            ByteField("pad", 0),
            lambda pkt: 0
            )
```

[test.pcap.tar.gz](https://github.com/secdev/scapy/files/5834101/test.pcap.tar.gz)

**Comment by guedou** [comment]
Please use and fill the issue template if you want an answer.
