### ISSUE TITLE
Scapy not parsing

### ISSUE THREAD

**Issue by stryngs** [secdev/scapy#3066]
Using Kali Linux (newest) on a Raspberry Pi and attempting to run scapy yields a sniff obj that isn't parsed out.  As an example:

>>> p[0]
<Raw  load='\x00\x00\x12\x00.H\x00\x00\x00\x0c\x85\t\xc0\x00\xb1\x01\x00\x00\xc4\x00|\x00`\xd2H\xf2\xd2\xb7' |>

That same obj created as a pcap and interpreted on a non-kali machine:
<RadioTap  version=0 pad=0 len=18 present=Flags+Rate+Channel+dBm_AntSignal+Antenna+RXFlags Flags= Rate=12 ChannelFrequency=2437 ChannelFlags=OFDM+2GHz dBm_AntSignal=-79 dBm Antenna=1 RXFlags= notdecoded='' |<Dot11  subtype=12 type=Control proto=0 FCfield= ID=31744 addr1=60:d2:48:f2:d2:b7 |>>

^ converted to hex for the compare:
In [9]: hexstr(f[0])                                                                                                                                                                                               
Out[9]: '00 00 12 00 2E 48 00 00 00 0C 85 09 C0 00 B1 01 00 00 C4 00 7C 00 60 D2 48 F2 D2 B7  .....H..............|.`.H...'

I tried this in Python3.9 and Python3.8 but the results were identical.  Where should I look to figure out why it isn't parsing correct?

**Comment by guedou** [comment]
Please use the issue template.

**Comment by stryngs** [comment]
If this was for a bug bounty sure; but the problem I listed above is pretty straight forward.  If it gets fixed, cool; if not no worries; I can always use a different OS.

Just wanted to report as it seemingly affects a lot of would-be scapy users.

Cheers.
