### ISSUE TITLE
mqtt connect message no response

### ISSUE THREAD

**Issue by higher75** [secdev/scapy#3080]
MQ Telemetry Transport Protocol, Connect Command
    Header Flags: 0x12, Message Type: Connect Command
        0001 .... = Message Type: Connect Command (1)
        .... 0010 = Reserved: 2
    Msg Len: 49
    Protocol Name Length: 4
    Protocol Name: MQTT
    Version: MQTT v3.1.1 (4)
    Connect Flags: 0x16, QoS Level: Exactly once delivery (Assured Delivery), Will Flag, Clean Session Flag
        0... .... = User Name Flag: Not set
        .0.. .... = Password Flag: Not set
        ..0. .... = Will Retain: Not set
        ...1 0... = QoS Level: Exactly once delivery (Assured Delivery) (2)
        .... .1.. = Will Flag: Set
        .... ..1. = Clean Session Flag: Set
        .... ...0 = (Reserved): Not set
    Keep Alive: 5
    Client ID Length: 10
    Client ID: myclientid
    Will Topic Length: 7
    Will Topic: /TopicA
    Will Message Length: 16
    Will Message: keepalive expiry

How to write the Reserved field in Header Flags?
and I can't find the method in scapy
can you help me ..
thankes

**Comment by guedou** [comment]
Please ask your question on gitter. This is not a forum.
