### ISSUE TITLE
Invalid ZigBee APS Data packet content.

### ISSUE THREAD

**Issue by omicronns** [secdev/scapy#3084]
#### Brief description

scapy seem to incorrectly parse zigbee APS data payloads.

#### Environment

-   Scapy version: `python-scapy 2.4.3-4`
-   Python version: `python 3.9.1`
-   Operating System: `Manjaro 20.2.1`

#### How to reproduce

```
from binascii import unhexlify
from scapy.layers import zigbee
zigbee.ZigbeeAppDataPayload(unhexlify("00ff01010401011f100e001000")).show()
```

#### Actual result

```
###[ Zigbee Application Layer Data Payload (General APS Frame Format) ]### 
  frame_control= 
  delivery_mode= unicast
  aps_frametype= data
  counter   = 255
###[ Zigbee Cluster Library (ZCL) Frame ]### 
     reserved  = 0
     disable_default_response= 0
     direction = 0
     manufacturer_specific= 0
     zcl_frametype= cluster-specific
     transaction_sequence= 1
     command_identifier= write_attributes_response
###[ Raw ]### 
        load      = '\x01\x01\x1f\x10\x0e\x00\x10\x00'
```

#### Expected result

![image](https://user-images.githubusercontent.com/6955179/106788922-e1b43580-6651-11eb-8974-6f30678b7978.png)

**Comment by gpotter2** [comment]
Hi,
this looks likes it was fixed on master ? Could you please try it out ?
Thanks !

**Comment by omicronns** [comment]
Thank you! It works.
