### ISSUE TITLE
Scapy can't be used without winpcap

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#309]
I am playing around with [AppVeyor](https://www.appveyor.com/) in add Windows unit tests to the project. My current playground is available in [this git repository](https://github.com/guedou/scapy-appveyor/). It is quite simple but I aim to run all Scapy unit tests at some point.

The script currently launched by AppVeyor contains:

``` python
from scapy.all import *
print conf
```

It failed with `WindowsError: [Error 126] The specified module could not be found` as winpcap is not installed.

Is this the expected behaviour on Windows (i.e. there is no way Scapy will work without winpcap) ? Or, shall we modify Scapy avoid this crash ?

**Comment by p-l-** [comment]
Scapy won't be able to send or sniff packets without Winpcap. However, it might still be useful to read PCAP files, dissect packets and play with them. So my guess is we should handle this crash and display a clear warning (like when Crypto module is missing).

**Comment by gpotter2** [comment]
@guedou Hey ! If that was answered with https://github.com/secdev/scapy/issues/365, maybe you can close it ?
