### ISSUE TITLE
NetflowV9/V10 decode incorrectly adds padding between datasets.

### ISSUE THREAD

**Issue by JoshLitt** [secdev/scapy#3101]
#### Brief description

Dissecting a Netflow V10 packet with multiple flowsets, where padding was not used, seems to result in the second flowset being misaligned.  It appears the dissector assumes there must have been padding in the first flowset, though there was not.  I see the dissector beginning the next flowset 3 bytes too deep (where 3 bytes is the amount of padding the packet writer could have used, but did not).

#### Environment

-   Scapy version: 2.4.4
-   Python version: 3.7.3
-   Operating System: MacOS Catalina

#### How to reproduce

The pcap I have is proprietary, so I will attempt to get a simple 1 record pcap that demonstrates the problem and post it.

But, given a pcap  where the first packet has the issue, it can be seen by:

```
from scapy.all import rdpcap, bind_layers
from scapy.layers.inet import UDP
from scapy.layers.netflow import NetflowHeader

bind_layers(UDP, NetflowHeader, dport=dest_port)
packets = rdpcap(filename)
for pkt in packets:
    netflow = pkt['NetflowDataflowsetV9']
    while netflow:
        print(f"templateID: {netflow.fields['templateID']}")
        print(f"length: {netflow.fields['length']}")
        netflow = netflow.payload
```
If the length of the first flowset is not a multiple of 4, then the next flowset will start incorrectly and the templateID and length shown will be wrong (compare to wireshark dissection).

#### Related resources

I'll come back with a pcap and a bit more code to demonstrate.

**Comment by JoshLitt** [comment]
I've attached an example NF pcap with a single record. This is a valid netflow packet, and displays as such with wireshark.
However, scapy is confused because the NetflowDataflowsetV9 records are not padded. You can see this as follows.

I'll read the pcap and get the first (only) packet and dissect it. The NF packet includes a template to make it more clear, and includes 3 identical records corresponding to the same template.
```
$ python3
Python 3.7.3 (default, Dec 13 2019, 19:58:14) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> pkts = rdpcap('example3.pcap')
>>> pkt = pkts[0]
>>> netflow = pkt[NetflowDataflowsetV9]
>>> netflow.show()
###[ Netflow DataFlowSet V9/10 ]### 
  templateID= 257
  length    = 17
  \records   \
   |###[ Netflow DataFlowset Record V9/10 ]### 
   |  fieldValue= '\x00\x00\x00\x00\x06\xc0\xa8\x00\n\xc0\xa8\x00\x0b'
###[ Netflow DataFlowSet V9/10 ]### 
     templateID= 4352
     length    = 0
     \records   \
      |###[ Netflow DataFlowset Record V9/10 ]### 
      |  fieldValue= '\x00\x06\xc0\xa8\x00\n'
###[ Netflow DataFlowSet V9/10 ]### 
        templateID= 11
        length    = None
        \records   \

>>> pkt.show()
###[ Ethernet ]### 
  dst       = ff:ff:ff:ff:ff:ff
  src       = 00:00:00:00:00:00
  type      = IPv4
###[ IP ]### 
     version   = 4
     ihl       = 5
     tos       = 0x0
     len       = 102
     id        = 1
     flags     = 
     frag      = 0
     ttl       = 64
     proto     = udp
     chksum    = 0x7c84
     src       = 127.0.0.1
     dst       = 127.0.0.1
     \options   \
###[ UDP ]### 
        sport     = iop
        dport     = iop
        len       = 82
        chksum    = 0xeea2
###[ Netflow Header ]### 
           version   = 10
###[ IPFix (Netflow V10) Header ]### 
              length    = 72
              ExportTime= Thu, 01 Jan 1970 00:00:00 -0500 (0)
              flowSequence= 0
              ObservationDomainID= 0
###[ Netflow FlowSet V9/10 ]### 
                 flowSetID = 0
                 length    = 24
                 \templates \
                  |###[ Netflow Flowset Template V9/10 ]### 
                  |  templateID= 257
                  |  fieldCount= 4
                  |  \template_fields\
                  |   |###[ Netflow Flowset Template Field V9/10 ]### 
                  |   |  enterpriseBit= 0
                  |   |  fieldType = IN_PKTS
                  |   |  fieldLength= 4
                  |   |###[ Netflow Flowset Template Field V9/10 ]### 
                  |   |  enterpriseBit= 0
                  |   |  fieldType = PROTOCOL
                  |   |  fieldLength= 1
                  |   |###[ Netflow Flowset Template Field V9/10 ]### 
                  |   |  enterpriseBit= 0
                  |   |  fieldType = IPV4_SRC_ADDR
                  |   |  fieldLength= 4
                  |   |###[ Netflow Flowset Template Field V9/10 ]### 
                  |   |  enterpriseBit= 0
                  |   |  fieldType = IPV4_DST_ADDR
                  |   |  fieldLength= 4
###[ Netflow DataFlowSet V9/10 ]### 
                    templateID= 257
                    length    = 17
                    \records   \
                     |###[ Netflow DataFlowset Record V9/10 ]### 
                     |  fieldValue= '\x00\x00\x00\x00\x06\xc0\xa8\x00\n\xc0\xa8\x00\x0b'
###[ Netflow DataFlowSet V9/10 ]### 
                       templateID= 4352
                       length    = 0
                       \records   \
                        |###[ Netflow DataFlowset Record V9/10 ]### 
                        |  fieldValue= '\x00\x06\xc0\xa8\x00\n'
###[ Netflow DataFlowSet V9/10 ]### 
                          templateID= 11
                          length    = None
                          \records   \
```
You can see from the template in the packet that the record has 4 fields, totaling 13 bytes. The first record is shown correctly. But the next 2 are not, because padding has been assumed in the dissection.  In a Netflow DataFlowSet, the "length" field includes the header (2-byte template ID and 2-byte length), the complete record data, AND any padding.  The length of the first DataFlowSet is 17 (13 bytes record + 4 bytes header). This means the second DataFlowSet should begin exactly 17 bytes after the first.  Yet the second DataFlowSet is dissected with ID 4352 (0x1100), because Scapy assumed an additional 3 bytes _between_ the flowsets, leading it to being dissecting the second one on the second byte of the 2-byte length field (0x11 = 17).

See https://tools.ietf.org/html/rfc7011#section-3.3.1 and section-3.3.2

Padding is optional:
> _Padding:_  The Exporting Process MAY insert some padding octets, so that the subsequent Set starts at an aligned boundary.

> _Length:_  Total length of the Set, in octets, including the Set Header, all records, and the optional padding.  Because an individual Set MAY contain multiple records, the Length value MUST be used to determine the position of the next Set.

In the `NetflowDataflowsetV9` class, removing the `PadField()` wrapper for the `PacketListField("records", ...)`, and changing the `adjust` lambda to be `adjust=lambda pkt, x: x + 4` seems sufficient to get the dissection correct, and probably to produce unpadded fields. Clearly the length field must never be less that the length of the records field + 4.  I'm less certain how to correctly apply padding on packet generation, if that's the desired default behavior.  The padding must be part of the records field, not after it.

[example-pcap.zip](https://github.com/secdev/scapy/files/6013655/example-pcap.zip)

**Comment by gpotter2** [comment]
Hi & thanks for the report.
This should be fixed in https://github.com/secdev/scapy/pull/3154
