### ISSUE TITLE
[Feature Request] Packet.as_json_dict method

### ISSUE THREAD

**Issue by flapili** [secdev/scapy#3106]
Hi, for my usecase I have to send a packet as valid json to a frontend and I'm wondering if introduce this fonctionnality in the source code of scapy could be a good idea ?

The implementation could be a method "as_json_dict" wich should return a dict of shape
```py
{
"layer_1": {
    "field_1": "value as string or int",
    "field_2": "value as string or int",
    "...": "...",
    },
"layer_2": {
    "field_1": "value as string or int",
    "field_2": "value as string or int",
    "...": "...",
    },
}
```

if you think it's a good idea I could implement it and open a PR :)

**Comment by guedou** [comment]
I am not against the idea of adding a way to export the packet as JSON, but this raises some questions regarding Scapy field types conversion to JSON types. Importing from JSON seems quite complicated.

From an API point of view, it will be better to be able to write the following to export any Packet as JSON:
```
import json
json.dumps(IP() / UDP())
```

**Comment by flapili** [comment]
Hi, thanks for your reply,

> Importing from JSON seems quite complicated
For that usercase I think pcap file are better


> From an API point of view, it will be better to be able to write the following to export any Packet as JSON:
> ```py
> import json
> json.dumps(IP() / UDP())
> ```

Have you any idea about how implement it ? from what I saw there is no way to do that without touching the `__iter__` method or via passing a custom cls inherited from json.JSONEncoder to dumps.

nothing prevent to do `json.dumps((IP() / UDP()).to_json())`
also, use a method could allow us to customize the output, we can imagine as example a kwarg "raw_format" which could take an enum bytearray / base64 / ect ...


about the field type conversion do you have any idea or hint ?

**Comment by guedou** [comment]
`json.dumps()` accepts as `dict` and attempts to convert it to a valid JSON document. That could be a way to implement the conversion.

I afraid that this JSON conversion feature is too specific and difficult to get it right. For instance, the simple following implementation raises question related to type conversions:
```
p = IP() / UDP()

d = {}
while p:
    d[p.name] = { f.name: p.getfieldval(f.name) for f in p.fields_desc }
    p.summary()
    p = p.payload
```
