### ISSUE TITLE
Why scapy need to sniff, send, or receive packet as root? Is there a way to do this without root privilege?

### ISSUE THREAD

**Issue by clediscover** [secdev/scapy#3108]
I have a phone, which is NOT rooted (I can't root it because it needs bootloader code). I am using Termux as terminal, but every time I run this, I got permission denied.

```
_socket.socket.__init__(self, family, type, proto, fileno)                 
PermissionError: [Errno 13] Permission denied
```

I hope you can help me with this problem.

Thanks!

**Comment by guedou** [comment]
Unfortunately, you cannot sniff without privileged access.

**Comment by clediscover** [comment]
Why?
