### ISSUE TITLE
802.11 RSN Tag corrupts rest of frame.

### ISSUE THREAD

**Issue by asianrider** [secdev/scapy#3115]
In all my captures, the 802.11 RSN tag corrupts the following tags because it uses too many bytes. The culprit is the group_management_cipher_suite, which does not appear in Wireshark.  

In the current code, it depends only on mfp_capable. I don't have the full 802.11 spec, but a search in internet revealed that, apparently, both mfp_capable and mfp_required must be set for the descriptor to be present.

It affects all Beacon frames, from APs from different manufacturers, so I assume the construction of those frames are compliant.

Can somebody with access to the spec confirm, or design a better fix ?

Environment: Ubuntu 20.04, Thinkpad P50 with wifi a/c card in monitor mode.

PR: Fix condition for inclusion of group_management_cipher_suite

Laurent

**Comment by gpotter2** [comment]
Hi & thanks for the report !

It would be great if you could share a pcap with a packet that reproduces the issue: correctly dissected on Wireshark but not on Scapy.

Thanks
