### ISSUE TITLE
IPv6ExtHdrSegmentRoutingTLV still based on draft and not RFC8754

### ISSUE THREAD

**Issue by louisna** [secdev/scapy#3117]
#### Brief description

The IPv6ExtHdrSegmentRoutingTLV class is based on draft 06 (https://tools.ietf.org/html/draft-ietf-6man-segment-routing-header-0) and not on RFC 8754. The encoding of the TLV is different now.

It leads to two unusued added bytes when using Scapy to add TLVs (`flags` and `reserved`).

https://github.com/secdev/scapy/blob/f0e3e4452ec63618b09bad30b459b7eba09ebd6b/scapy/layers/inet6.py#L903-L909

#### Environment

-   Scapy version: master branch from GitHub
-   Python version: 3.8
-   Operating System: Ubuntu 20.04

#### Actual result

The TLV is currently composed of:
- type: 8 bites field
- len: 8 bits field
- **reserved: 8 bits field**
- **flags: 8 bits field**
- value: `len` bytes field

#### Expected result

The TLV should only contain:
- type: 8 bits field
- len: 8 bits field
- value: `len` bytes field

#### Related resources

TLV: definition from RFC 8754
![TLv definition from RFC 8754](https://user-images.githubusercontent.com/37408317/109387891-1b502780-7904-11eb-856f-dd1efde274ec.png)

TLV definition used in Scapy from draft 06:
![TLV definition used in Scapy from draft 06](https://user-images.githubusercontent.com/37408317/109387914-3f136d80-7904-11eb-972e-4d219880b5f4.png)

**Comment by gpotter2** [comment]
Hi & thanks for the report.

I've put https://github.com/secdev/scapy/pull/3153 together but it would be super cool if you could test it or provide a pcap containing test packets, so that I could make sure it works.

Thanks
