### ISSUE TITLE
changing checksum of a commit

### ISSUE THREAD

**Issue by blshkv** [secdev/scapy#3121]
Hi, 

This is a bit unusual, so I'm not going to use a provided template.

At Pentoo, we could not wait for a release due to a critical functionality (please release it btw) and decided to provide a current snapshot of scapy. Here is an example how it is done:
https://github.com/pentoo/pentoo-overlay/commit/ce4040b0083f63cba0325fe9ea70b3ba4426de13

In short, we download it from the following location, as an example:
https://github.com/secdev/scapy/archive/f0e3e4452ec63618b09bad30b459b7eba09ebd6b.tar.gz
(notice the hash f0e3e4452e)

However, we noticed it changes later as it was reported in our issue tracker:
https://github.com/pentoo/pentoo-overlay/issues/703

I compared what changed exactly and figured it out. The problem with the following line:
https://github.com/secdev/scapy/blob/master/scapy/__init__.py#L99

it changes from:
```git_archive_id = 'f0e3e4452e  (HEAD -> master)'```
to
```git_archive_id = 'f0e3e4452e '```

Could you adjust that format, so it won't be happening?

Thanks

**Comment by blshkv** [comment]
Apparently, this bug was fixed before, but you got it back
https://github.com/secdev/scapy/issues/1520

Can also add a comment "do not use %d here" ? ;-)

**Comment by gpotter2** [comment]
This is too old for me to remember anything 😄 
I think this was discussed in https://github.com/secdev/scapy/pull/1521

**Comment by p-l-** [comment]
We want to have the `git_archive_id` (because we use it). This makes archives linked to a specific commit unstable (the exact content will differ between when that specific commit is the current HEAD and when more commits have been added), which I understand may be a concern **but** I think the only correct way to address that is:
1. we make a release, and
2. people use pypi archives.

**Comment by blshkv** [comment]
can you add a condition, something like if ```tag``` is "release" then add %d?

**Comment by p-l-** [comment]
Do you know how/if this would be possible?

**Comment by blshkv** [comment]
Honestly, I had no idea that even the current implementation is be possible. I was pretty sure that the archive based on a commit is stable and should not change. I haven't looked at it, but you implemented a hack probably.
Can you have a look at the official way https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release? Just an idea, I never used it. There are other hooks too.

**Comment by p-l-** [comment]
Since this is far from being a priority for the project, I do not plan to work on it. If someone is willing to spend time on this issue, please reopen this issue to keep track of your work, and submit a pull request.

Thanks!

**Comment by blshkv** [comment]
Please keep it open until it is fixed. The open but doesn't bite, and somebody with wore time may fix it.

Also, please release a new version

**Comment by gpotter2** [comment]
I wish I could help but I don't understand the issue.

**Comment by blshkv** [comment]
Ok, rip

**Comment by guedou** [comment]
Follow #3100 to follow the release of v2.4.5 that will have the Python 3.9 fix. I am planning to release this week.

**Comment by gpotter2** [comment]
This should be fixed with https://github.com/secdev/scapy/pull/3546, feel free to try it out @blshkv
