### ISSUE TITLE
Buggy in testing pdflatex

### ISSUE THREAD

**Issue by ssxcxS45XT** [secdev/scapy#3122]
https://github.com/secdev/scapy/blob/master/scapy/extlib.py#L57

When pdflatex is not available, the following line is called

```
log_loading.info("Can't import PyX. Won't be able to use psdump() or pdfdump().")
```

instead of the following line.

```
        log_loading.info("PyX dependencies are not installed ! Please install TexLive or MikTeX.")  # noqa: E501
```

When I installed pdflatex, then the error message is gone. So there is an error in the error message to show. This is a bug that should be fixed.

**Comment by gpotter2** [comment]
No that's not what happens. When pdflatex is missing, it shows PyX dependencies are not installed ! Please install TexLive or MikTeX
