### ISSUE TITLE
Incorrect MCS_index reported for multicast

### ISSUE THREAD

**Issue by andreasdotzler** [secdev/scapy#3131]
#### Brief description

The MCS_index of a packet read from a recorded pcapng file is reported to be 0, while 10 is correct. 

#### Environment

-   Scapy version: `scapy-2.4.4.dev319`
-   Python version: `3.9`
-   Operating System: `Linux 4.15.0`

#### How to reproduce

```
from scapy.all import *
scapy_cap = rdpcap("multicast.pcapng")
print(scapy_cap[0].MCS_index)
```

#### Actual result

```
bash -c 'pip install --upgrade git+git://github.com/secdev/scapy; python -c "from scapy.all import *; scapy_cap = rdpcap(\"multicast.pcapng\"); print(scapy_cap[0].MCS_index)"'
... 
Successfully installed scapy-2.4.4.dev319
0
```

#### Expected result

The MCS_index reported should be 10, as in Wireshark or scapy version 2.4.3

```
bash -c 'pip install scapy==2.4.3; python -c "from scapy.all import *; scapy_cap = rdpcap(\"multicast.pcapng\"); print(scapy_cap[0].MCS_index)"
...
Successfully installed scapy-2.4.3
10
```

#### Related resources
[multicast.pcapng.TXT](https://github.com/secdev/scapy/files/6111196/multicast.pcapng.TXT)

**Comment by gpotter2** [comment]
Thanks for the report & sorry for the delay,
This should be fixed in https://github.com/secdev/scapy/pull/3187
