### ISSUE TITLE
delayed packet reception 

### ISSUE THREAD

**Issue by CanCanRep** [secdev/scapy#3142]
Hi all,

while working with SCAPY we have identified a delay of the received packets of up to 30s using the Scapy sniff function. The measurement of the delay is done within the queue_packet function where we compare the time of the received packet with the Windows time.

I´ve tried several different filter with the same result. Unfortunately I couldn´t find any related topics on on git nor stackoverflow.
Did anyone of you had a similar issue ?

Thank you very much in advance

Envrionment
-   Scapy version: 2.4.4
-   Python version: 3.7.7
-   Operating System: Windows 10

Script
```
from scapy.all import *


def queue_packet(packet):
    print(f"received queue {packet.time} diff: {time.time() - packet.time} ")

sniffer_ports=[42514, 42557, 42558]
filter = lambda x: (x.haslayer(UDP) and x[UDP].dport in sniffer_ports) or (x.haslayer(ICMPv6ND_NS)) and x.haslayer(Dot1Q)


socket = conf.L2listen(type=ETH_P_ALL)
sniff(
    prn=queue_packet,
    opened_socket=socket,
    lfilter=filter,
    iface="TestingNetwork", 
    store=0,
)


```

**Comment by gpotter2** [comment]
Have a look at https://scapy.readthedocs.io/en/latest/usage.html#performance-of-scapy
You should try using BPF filters.

Have a great day
