### ISSUE TITLE
Selected interface addresses are not used while sending packets on Windows

### ISSUE THREAD

**Issue by AgainPsychoX** [secdev/scapy#3146]
#### Brief description

Selected interface addresses are not used while sending packets on Windows.

#### Environment

-   Scapy version: `2.4.4.dev329` (just updated to test once more before submiting the issue here)
-   Python version: `3.8.6`
-   Operating System: `Windows` (using newest `npcap 1.20`)

![image](https://user-images.githubusercontent.com/23557839/111675494-78613e00-881d-11eb-8015-77810593e6fb.png)

#### How to reproduce

On Windows machine I have multiple connections to the same network, via ethernet cable and wifi card. I am trying to use the wi-fi card at the moment, and the cable for other card is disconnected.

WiFi interface gets IP address from DHCP - currently it got `.1.104` -, and ethernet (cable) have set static `.1.240`.

I try to send simple packets 
```py
packet = ARP(op="who-has", pdst="192.168.1.100")
ans, _ = sr(packet, timeout=5)
```

#### Expected result

While trying to send packets using various commands, while not specifying exact interface by passing `iface = XXA`, the function should use `conf.iface` ([as stated in docs](https://scapy.readthedocs.io/en/latest/api/scapy.config.html#scapy.config.Conf.iface)) to determine output interface, and it sure does use the selected interface (as Wireshark on the screenshot above is looking at it).

I assume, if I don't specify exact source addresses, it should use the provided (or default from `conf.iface`) interface addresses (`iface.mac`, `iface.ip`). I feel it's only logical option...

As I didn't specified the `iface` argument for `sr()` it should use `conf.iface`. As I didn't specified the `hwsrc` and `psrc` it should use `iface.mac` and `iface.ip` respectively. Also, the underlying Ether packet created by `sr()` should use the same source address (`src` = `iface.mac`).

#### Actual result

The default source/sender addresses (both IP/MAC for Ether/ARP parts) are set to other interface, despite it's not even connected. 

In result, I get no response to the packet, or response is directed to invalid MAC address.

It's weird to be honest: why does it default to some other random interface addresses?? 

#### Related resources

I found way around, I have just specify everything strictly (btw, it does not help if I simply set only `iface=conf.iface`):
```py
packet = Ether(src=conf.iface.mac, dst="ff:ff:ff:ff:ff:ff") / ARP(op="who-has", pdst="192.168.1.100", psrc=conf.iface.ip, hwsrc=conf.iface.mac)
ans, _ = srp(packet, timeout=5)
```

Note, this does not work (underlying Ether packet is still using some random other interface addresses):
```py
packet = ARP(op="who-has", pdst="192.168.1.100", psrc=conf.iface.ip, hwsrc=conf.iface.mac)
ans, _ = sr(packet, timeout=5)
```

Anyways, even if it does not to be considered as a bug (some might argue), in case there is no source addresses se, it would be more logical to fallback to provided `iface` or `conf.iface` instead of using random interface that might be down.

**Comment by gpotter2** [comment]
Hi and sorry for the delay. This is mostly *by-design*: when using layer 3 (`send`, `sr`... without the `-p`), Scapy will use it's routing table (https://scapy.readthedocs.io/en/latest/usage.html#routing) to guess what interface it should be using. This mimics what your OS would do.

The interface isn't random, it's the same as

```
conf.route.route("192.168.1.100")
```

You can see the full routes on `scapy.route`. (try that in a console). Those routes are obtained from your operating system directly, which means your computer configured this IP address to go through this specific interface.
