### ISSUE TITLE
svg in 'Introduction' section of documentation causes Chrome >100% CPU

### ISSUE THREAD

**Issue by ropg** [secdev/scapy#3147]
#### Brief description

Viewing the webpage [Introduction](https://scapy.readthedocs.io/en/latest/introduction.html) on ReadTheDocs in Chrome causes Chrome to take over 100% CPU.

#### Environment

I have the latest version of Chrome (89.0.4389.90 (Official Build) (x86_64)) on my MacBookPro15,1 running MacOS 10.14.6.

#### How to reproduce

Load the web page.

#### Actual result

![Screenshot 2021-03-22 at 10 51 43](https://user-images.githubusercontent.com/343196/111972402-b8664080-8afd-11eb-99fa-d10881a3d99b.png)

#### Expected result

No blazing fan, just a web page.

#### Related resources

CPU usage sinks to normal levels if I use Chrome DevTools to remove this element from the page:

```html 
<img alt="_images/animation-scapy-demo.svg" class="align-center" src="_images/animation-scapy-demo.svg">
```

I think it's fair to say that SVG for large animations like this is not handled gracefully by all browsers. (Safari does not seem to be bothered by it.) Given the popularity of Chrome, the animation should probably be replaced by a GIF equivalent.

&nbsp;

*(Thank you for scapy. Amazing work.)*

**Comment by gpotter2** [comment]
That's cool but not sure that's a scapy bug.
Svg animations are super lightweight compared to gif :/

**Comment by ropg** [comment]
Naturally it would be nice if Google made Chrome handle SVG animations better. But for the time being this happens to some massive fraction of the people looking at the docs. I'd want to replace it in my project so I figured I'd tell you.
