### ISSUE TITLE
Which field type could be used

### ISSUE THREAD

**Issue by rainmanwy** [secdev/scapy#315]
Hello,

I am trying to implement mqtt protocol.

One problem i met is how to define "Remaining Length" in mqtt protocol.
The length of this field is variable. 
http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html

I have checked "FieldLenField", i am not sure whether this type is suitable for "Remaining Length".
Or i should define a new field type?

Thank you very much!

**Comment by dark-lbp** [comment]
Haven't found a good solution, if you just want to generate the packet you can try this.

```python
from scapy.all import *


class MQTTField(Packet):
    name = "MQTTField"
    fields_desc = [
        ByteField('Byte1', 0x00),
        ByteField('Length1', None),
        ConditionalField(XByteField("Length2", None), lambda pkt: True if len(
            pkt[MQTTField].RemainData) > 127 == 1 else False),
        ConditionalField(XByteField("Length3", None), lambda pkt: True if len(
            pkt[MQTTField].RemainData) > 16383 == 1 else False),
        ConditionalField(XByteField("Length4", None), lambda pkt: True if len(
            pkt[MQTTField].RemainData) > 2097151 == 1 else False),
        StrField("RemainData", "")
        ]

    def cacl_length(self, length):
        output = ''
        while length > 0:
            digit = length % 128
            length /= 128
            if length > 0:
                digit |= 0x80
            output += chr(digit)
        return output

    def post_build(self, p, pay):
        if self.Length1 is None:
            l = len(self.RemainData)
            rl = self.cacl_length(l)
            p = p[:1] + rl + p[2:]
        return p + pay


>>> a=MQTTField()
>>> a.show()
###[ MQTTField ]###
  Byte1     = 0
  Length1   = None
  RemainData= ''

>>> a.RemainData='A'*128
>>> str(a)[:8].encode('hex')
'0080014141414141'
>>> a.RemainData='A'*16383
>>> str(a)[:8].encode('hex')
'00ff7f4141414141'
>>> a.RemainData='A'*16384
>>> str(a)[:8].encode('hex')
'0080800141414141'
>>> a.RemainData='A'*2097151
>>> str(a)[:8].encode('hex')
'00ffff7f41414141'
>>> a.RemainData='A'*2097152
>>> str(a)[:8].encode('hex')
'0080808001414141'
>>> a.RemainData='A'*268435455
>>> str(a)[:8].encode('hex')
'00ffffff7f414141'
```

**Comment by rainmanwy** [comment]
@dark-lbp , thanks for the information. I want to implement a layer for mqtt protocol.
I have tried to create a new field for this. But not sure my understand about scapy is correct.

> class RemainingLengthCalc(object):

    @staticmethod
    def decode(byteList):
        length = 1
        digit = ord(byteList[0])
        multiplier = 1
        value = 0
        value += (digit & 127) * multiplier
        multiplier *= 128
        for i in range(len(byteList))[:-1]:
            if (ord(byteList[i]) & 128) != 0:
                value += (ord(byteList[i + 1]) & 127) * multiplier
                multiplier *= 127
                length += 1
            else:
                break
        return value, length

    @staticmethod
    def encode(remainingLength):
        digit = remainingLength % 128
        remainingLength = remainingLength / 128
        if (remainingLength > 0):
            digit = digit | 0x80
        encodeStr = chr(digit)
        while (remainingLength > 0):
            digit = remainingLength % 128
            remainingLength = remainingLength / 128
            if (remainingLength > 0):
                digit = digit | 0x80
            encodeStr += chr(digit)
        return encodeStr

class RemainingLengthField(StrField):


    def addfield(self, pkt, s, val):
        encodeV = RemainingLengthCalc.encode(int(val))
        return s + self.i2m(pkt, encodeV)


    def getfield(self, pkt, s):
        print 's: %s' % s
        v, l = RemainingLengthCalc.decode(s)
        self.remain = len(s[l:])
        if self.remain == 0:
            return "", 0
        else:
            return s[-self.remain:],v
        #return self.m2i(pkt, s[l:]), s[:l]



class MQTT(Packet):

    name = 'MQTT'
    fields_desc = [
        BitEnumField('type', 1, 4, mqtt_types),
        BitField('dup_flag', 0, 1),
        BitEnumField('qos', 0, 2, mqtt_qos),
        BitField('retain', 0, 1),
        RemainingLengthField('remaining_length', 0),
    ]

    def post_build(self, p, pay):
        self.remaining_length = len(pay)
        p = p[:-1] + RemainingLengthCalc.encode(self.remaining_length)
        p += pay
        return p

I will try to implement other part, then have a try in real env, and use wireshark to check that my implementation is correct.

But i am sure that inherit "StrField" is correct solution.

**Comment by ttannhaeuser** [comment]
any progress on the MQTT implementation at all?

**Comment by guedou** [comment]
MQTT was added in #638
