### ISSUE TITLE
run scapy without sudo

### ISSUE THREAD

**Issue by prRZ5F4LXZ** [secdev/scapy#3151]
#### Brief description

run scapy without sudo but still can listen to receive packets.

#### Environment

-   Scapy version: not relevant.
-   Python version: not relevant
-   Operating System: Any OS with this https://man7.org/linux/man-pages/man7/capabilities.7.html

#### How to reproduce

NA

#### Actual result

NA

#### Expected result

Already described.

#### Related resources

ping can receive packets without root permission because of this.

```
$ getcap $(which ping)
/usr/bin/ping cap_net_raw=ep
```

**Comment by p-l-** [comment]
Unless I'm missing something here, you would probably need to give cap_net_raw to the Python interpreter, which most people do not want...
