### ISSUE TITLE
SomeIP-TP dissert error

### ISSUE THREAD

**Issue by TianjiaoXu** [secdev/scapy#3156]
![image](https://user-images.githubusercontent.com/45891367/112963352-dc6af700-9179-11eb-91cb-c72e35434388.png)

in this image: the first message is someip-tp first frame, and the second one is second frame. First frame length is 1388, which means the second frame's offset is set to 1388, but actually it is 86.
Maybe bit field in someip dissertor code takes error, because 86 in hex view is 0x56, and 1388 is 0x56C, "56" is the same.
Please check.

**Comment by guedou** [comment]
Please use the issue template if you expect an answer.

**Comment by TianjiaoXu** [comment]
I notice that this offset multiplex 16 equals to the real result.
This step can be done in application level.
