### ISSUE TITLE
Question: Translating the documentation in Hebrew

### ISSUE THREAD

**Issue by rayahazi** [secdev/scapy#3162]
Hello, I would like to add a translation of the documentation in Hebrew. 
Do you need something like this?
This is my first contribution so I wanted to start with documentation instead of coding.

**Comment by p-l-** [comment]
I think helping on the documentation side, and making Scapy's documentation available to non-English speaking people is a good idea. I like it, thanks!

**Comment by gpotter2** [comment]
@p-l- How would it be stored though? I'm not sure if we can realistically maintain both.. :/

**Comment by p-l-** [comment]
@gpotter2 fair point. We probably want to have a look at how other projects handle that.

**Comment by guedou** [comment]
IMHO, the best solution is that @rayahazi translates the documentation in her own repository. Once over, we could store it in `secdev/scapy-doc-i18n` for example.
