### ISSUE TITLE
Unclear license and possible license violations

### ISSUE THREAD

**Issue by vincentmacri** [secdev/scapy#3165]
#### Description

From [the license file](https://github.com/secdev/scapy/blob/master/LICENSE) and [this issue](https://github.com/secdev/scapy/issues/3031) I assume that `scapy` is under the GPLv2 license (and not GPLv2 or later).

However, [this file](https://github.com/secdev/scapy/blob/master/scapy/contrib/ife.py) in `scapy` says (emphasis added):

> This module is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, **_or (at your option) any later version_**.

[Other files](https://github.com/secdev/scapy/blob/master/scapy/all.py) just say "This program is published under a GPLv2 license".

So I'm not sure if `scapy` is under GPLv2 only or GPLv2 or later.

Furthermore, in your other repo [awesome-scapy](https://github.com/secdev/awesome-scapy) there are links to projects using `scapy` that would violate the `scapy` license if `scapy` is under GPLv2 only but be fine if `scapy` is under GPLv2 or later. For example, https://github.com/epsylon/ufonet [is under GPLv3](https://github.com/epsylon/ufonet/blob/master/docs/LICENSE) and [according to gnu.org](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) a GPLv2 only library cannot be used in GPLv3 software.

In the [awesome-scapy repo](https://github.com/secdev/awesome-scapy), there are also links to [MIT licensed software](https://github.com/calebmadrigal/trackerjacker) using `scapy`. To the best of my knowledge of how the GPL works, you cannot use a GPLv2 library in MIT software. Same applies to BSD-3-Clause licensed software, which [is also linked to](https://github.com/fportantier/habu) in the [awesome-scapy repo](https://github.com/secdev/awesome-scapy).

There are also links to [Apache-2.0 licensed software](https://github.com/secureworks/flowsynth). [The Apache Software Foundation discusses GPL and Apache compatibility](https://www.apache.org/licenses/GPL-compatibility.html), and it boils down to GPLv2 is completely incompatible with Apache-2.0 (both ways) but Apache-2.0 software can be used in GPLv3 software (but not the other way around). So this seems to be another violation of the `scapy` license. This was discussed by `scapy` [here](https://github.com/secdev/scapy/issues/1547) as well.

From this, it seems that the `scapy` project is aware of (what seems to be) projects that violate their GPL license, so I'm confused as to what this project is actually licensed under. From all this, it seems the current approach is to just not enforce the license at all.

I don't mean to single-out any of the projects that were linked to in [awesome-scapy](https://github.com/secdev/awesome-scapy), I just used the first project I found there for each GPL-incompatible license to use as an example. This not an exhaustive list of all projects in the repo potentially violating the license either. I highly doubt any of these projects are maliciously violating the `scapy` license.

Disclaimer: Not a lawyer, not legal advice, just someone who is interested in software licensing and wants to know the conditions under which I may use `scapy`.

#### Actual result

The license of `scapy` is unclear (conflicting information on if it is GPLv2 or GPLv2 or later).

#### Expected result

The license of `scapy` is clearly stated as either GPLv2 only, GPLv2 or later (or something else).

#### Related resources

[GPL compatibility chart](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility)

[Apache and GPL compatibility explanation](https://www.apache.org/licenses/GPL-compatibility.html)

[GPLv2 license](https://www.gnu.org/licenses/old-licenses/gpl-2.0.html)

[GPLv3 license](https://www.gnu.org/licenses/gpl-3.0.html)

**Comment by polybassa** [comment]
Thanks for mention that issue. 

I've made a quick check. The following four files don't comply with GPLv2
```
contrib/ibeacon.py:# This program is published under a GPLv2 (or later) license
contrib/altbeacon.py:# This program is published under a GPLv2 (or later) license
contrib/exposure_notification.py:# This program is published under a GPLv2 (or later) license
contrib/eddystone.py:# This program is published under a GPLv2 (or later) license
```
Besides that, one file is licensed with MPL 2.0

```
grep -r "MPL 2.0"
arch/windows/structures.py:# published under a MPL 2.0 License (GPLv2 compatible)
```

Is it possible to change the license of the four not complying files?

**Comment by vincentmacri** [comment]
> I've made a quick check. The following four files don't comply with GPLv2
> 
> ```
> contrib/ibeacon.py:# This program is published under a GPLv2 (or later) license
> contrib/altbeacon.py:# This program is published under a GPLv2 (or later) license
> contrib/exposure_notification.py:# This program is published under a GPLv2 (or later) license
> contrib/eddystone.py:# This program is published under a GPLv2 (or later) license
> ```

I believe these files are compatible with GPLv2, and `scapy` would be using these files under the GPLv2 license. GPLv2 (or later) means OR later, not AND later so you should be fine here. [GNU discusses this here](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility). On using GPLv2 (or later) code in a GPLv2 project they say:

> You must follow the terms of GPLv2 when incorporating the code in this case. You cannot take advantage of terms in later versions of the GPL.

On using GPLv2 code in a GPLv2 (or later) project they say:

> While you may release your project (either your original work and/or work that you received and modified) under GPLv2-or-later in this case, note that the other code you're using must remain under GPLv2 only. As long as your project depends on that code, you won't be able to upgrade the license of your project to GPLv3-or-later, and the work as a whole (any combination of both your project and the other code) can only be conveyed under the terms of GPLv2.

(I'm still not a lawyer and this is still isn't legal advice.)

For certainty, can a project maintainer explicitly state whether `scapy` is under `GPLv2 only` or `GPLv2 or later`?

**Comment by polybassa** [comment]
AFAIK, than Scapy is under GPLV2 only, since most of the files are using this license.

**Comment by guedou** [comment]
Scapy is released under GPLv2 only as can be seen in https://github.com/secdev/scapy/blob/master/LICENSE. The files mentioned in this thread are compatible with this license. In the future, I believe that we must be more vigilant to the license used in new files.

Concerning the license violations, I was not aware of them. I personally don't have any the time to contact these projects and make them aware too.
