### ISSUE TITLE
npcap 1.30 was released

### ISSUE THREAD

**Issue by AgainPsychoX** [secdev/scapy#3170]
It seems the new npcap version 1.30 (released just few days ago) fixes issue where on Windows npcap was not able to work in raw mode.

> Restore raw WiFi frame capture support, which had been broken in a few ways
since Npcap 0.9983. Additional improvements enable PacketSetMonitorMode()
for non-admin-privileged processes, allowing Wireshark to correctly enable
monitor mode via checkbox without requiring WlanHelper.exe.
>
> Fixed WlanHelper.exe to correctly set modes and channels for adapters, if run
with Administrator privileges. Fixes https://github.com/nmap/npcap/issues/122.

(npcap 1.30 release notes https://github.com/nmap/npcap/releases/tag/v1.30)

Maybe its worth to update note about npcap in docs - instead using old version now we can use 1.30, as the issue is fixed.

> If you are using Npcap: please note that Npcap npcap-0.9983 broke the 802.11 util back in 2019. It has yet to be fixed (as of Npcap 0.9994) so in the meantime, use npcap-0.9982.exe

The doc page to be updated: https://scapy.readthedocs.io/en/latest/troubleshooting.html

_Sorry for not using issue form, it's not really "issue", just suggestion. Maybe someone should run tests with new npcap?_

**Comment by gpotter2** [comment]
Thanks for the report, I am aware of this but haven't got the time to test this new npcap version to check if it actually resolves the issue. Did you have the chance to try it out?

**Comment by PsychoXIVI** [comment]
I consider myself as noobie with Python and networking, I don't know sharp corners around the scapy - I don't feel like I have suitable experience and knowledge to run required tests. 

It solved one error I was running into while ~~working~~ experimenting with the scapy few days ago. I ran into another problem however, but I don't know whenever it was my lack of knowledge, other bug lying inside scapy, another bug introduced in npcap or maybe some incompatibility with new npcap version from scapy point of view.

At the moment of writing this I don't really remember/I don't have access to the script I was working with. I can maybe get closer look in few days and maybe then post my experiences here.

**Comment by guedou** [comment]
Do not hesitate to reopen the issue if you manager to confirm that this new version fixes the issue.
