### ISSUE TITLE
Error while trying to send binary in bytes as TCP payload, new ifconfig warnings?

### ISSUE THREAD

**Issue by jpl1337** [secdev/scapy#3171]
#### Brief description

I'm trying to read a binary in specific byte sizes and send them in the payload of TCP packets. Supersocket seems to have an I/O error, likely from the payload. 

#### Environment

-   Scapy version: `scapy-2.4.4 and then scapy-2.4.5rc1.dev7`
-   Python version: `Python 3.9.4`
-   Operating System: `MacOS 10.15.7`

#### How to reproduce

Code snippet of where it seems to have an issue:
```
payload_pkt = Ether(src = src_mac, dst = dst_mac)/IP(src = src_ip, dst = dst_ip)/TCP(sport = src_port, dport = dst_port, flags = 'PA', seq = seq, ack = ack)
with open(file, 'rb') as f:
    message = f.read(1200).hex() 
    payload_pkt = payload_pkt/message
    sendp(payload_pkt, iface='en5')
```

#### Actual result

This is the error I got originally with scapy-2.4.4:

>    sendp(payload_pkt, iface=iface)
  File "/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py", line 377, in sendp
    results = __gen_send(socket, x, inter=inter, loop=loop,
  File "/usr/local/lib/python3.9/site-packages/scapy/sendrecv.py", line 308, in __gen_send
    s.send(p)
  File "/usr/local/lib/python3.9/site-packages/scapy/arch/bpf/supersocket.py", line 338, in send
    return os.write(self.outs, raw(x))
OSError: [Errno 5] Input/output error
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

It seems Scapy doesn't like what I'm putting in the payload? Not sure if it's a size issue or what...

This is the error I got after upgrading to scapy-2.4.5rc1.dev7:

> WARNING: Failed to execute ifconfig: (ifconfig: interface vboxnet does not exist)
WARNING: Failed to execute ifconfig: (ifconfig: interface vboxnet does not exist)
WARNING: No IPv4 address found on en1 !
WARNING: No IPv4 address found on en2 !
WARNING: more No IPv4 address found on en3 !

It appears that Scapy is now trying to figure out my interfaces, by using ifconfig without prompt, during import and sniffing even though I'm specifying an interface. 

#### Expected result

I should be able to add the data I'm reading from the binary into the payload of the TCP packet.

**Comment by guedou** [comment]
Could you try to come up with a shorter reproducer?

**Comment by guedou** [comment]
Closed due to no answer.
