### ISSUE TITLE
Travis CI is failing

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#3172]
Hi, I've discovered Travis CI failing. 
Here  is a link to the relevant job: https://travis-ci.com/github/secdev/scapy/jobs/498682274

**Comment by gpotter2** [comment]
Thanks for the note. Will have a look at it

**Comment by gpotter2** [comment]
Wait the travis tests kicked back in? had missed that ^^'

**Comment by gpotter2** [comment]
Good catch thanks for the report. I've rewritten the tests in https://github.com/secdev/scapy/pull/3182 and they are now much more stable.

**Comment by polybassa** [comment]
Speaking about Travis, as soon as a build machine on Github or Travis runs Linux Kernel 5.10, we don't require a dedicated test environment for can-isotp anymore. can-isotp got merged into mainline Linux in 5.10. Just to let you know, that we can remove all the can-isotp related installation code, once we have Kernel 5.10 available on Travis or Github

**Comment by gpotter2** [comment]
That's great news. Eventually we entent to focus the travis tests on more specific taks such as FreeBSD.
By the way, I was wondering if you would mind if we disabled automotive tests on PyPy. We would still let it run on the rest of the test suite, but because PyPy tend to mess with delays a lot, it's harder to keep the tests stable.

**Comment by polybassa** [comment]
I'm fine if you remove automotive stuff from PyPy. 
I can do it, so that only the tests with network communication are removed. Simple build and dissect tests shouldn't matter.
I just discovered strange behaviors between PyPy compared to Python one time. An I can still manually execute automotive related tests on pypy. 

Do you think it's possible to find an intermediate solution. Like disable all automotive tests on PyPy if the build is executed on the master branch. But this would not help much. It would be better, to have something "TAG" based or change based. So that PyPy automotive test will only be executed, if automotive files were touched. 

I will think about a better way. For now, I'm totally fine with disabling them. I will do a PR in the next days.

**Comment by gpotter2** [comment]
I fixed the tuntap tests, those are now stable.

Travis CI is however failing on ISOTP native sockets quite consistently :/ Would be great if you could have a look.

Thanks

**Comment by polybassa** [comment]
I started debugging. It's related to the answers function of ISOTP somehow. I need some more time to find the proper fix. Basically sendrcv is not finding a match. 
-- 
Viele Grüße

Nils Weiß

**Comment by polybassa** [comment]
Something weird is going on there. Even a basic answers function which just does self.__class__ == other.__class__ fails, even when both classes are from ISOTP.

**Comment by polybassa** [comment]
@gpotter2 I'm still debugging. I've see this behavior:

```
>>> assert(rx == msg)
<class 'scapy.contrib.isotp.ISOTP'>
<class 'scapy.contrib.isotp.ISOTP'>
['time', 'sent_time', 'name', 'default_fields', 'fields', 'fieldtype', 'overload_fields', 'overloaded_fields', 'packetfields', 'original', 'explicit', 'raw_packet_cache', 'raw_packet_cache_fields', '_pkt', 'post_transforms', 'payload', 'underlayer', 'name', '_answered', 'direction', 'sniffed_on', 'wirelen', 'src', 'dst', 'exsrc', 'exdst']
['time', 'sent_time', 'name', 'default_fields', 'fields', 'fieldtype', 'overload_fields', 'overloaded_fields', 'packetfields', 'original', 'explicit', 'raw_packet_cache', 'raw_packet_cache_fields', '_pkt', 'post_transforms', 'payload', 'underlayer', 'name', '_answered', 'direction', 'sniffed_on', 'wirelen', 'src', 'dst', 'exsrc', 'exdst']
not same class
```

produced by this __eq__ function of Packet:
```
 def __eq__(self, other):
        # type: (Any) -> bool
        if not isinstance(other, self.__class__):
            print(other.__class__)
            print(self.__class__)
            print(other.__slots__)
            print(self.__slots__)
            print("not same class")
            return False
        for f in self.fields_desc:
            ....
```
The bug was introduced in this commit: 12445543bac7dbe5301ea3842724809941bf3878

Do you have an idea, why this basic type compare fails?

**Comment by polybassa** [comment]
Apparently, #3188 fixes Travis.

**Comment by gpotter2** [comment]
Sorry I won't have the time to dig into this anytime soon :/

**Comment by polybassa** [comment]
Here my theory why this failed.

I imported the isotp layer including ISOTP and the socket. In the socket, the recv function uses the basecls ISOTP. 


Later I reload the isotp import. 

Now in my test, a ISOTP instance created for comparison is not the same class as retuned from a sockets recv. Therefore answers fails.

Just a hypothesis.
