### ISSUE TITLE
How to remove a Packet from a PCAP file using Scapy ?

### ISSUE THREAD

**Issue by MariMari7** [secdev/scapy#3173]
In Scapy documentation, I found only remove_payload. However I need to remove a complete packet from a PCAP file.

**Comment by MariMari7** [comment]
Hello Mr. Guillaume Valadon,

I want to know why you closed my question ?

Thank you. Regards

**Comment by polybassa** [comment]
This is an issue board and not a forum. 

We have gitter for questions.
-- 
Best regards,

Nils Weiß
