### ISSUE TITLE
I want to use sendpfast to make packet loss

### ISSUE THREAD

**Issue by Yan0981181511** [secdev/scapy#3174]
#### Brief description

I want to use scapy to create 10 Mpbs traffic, because the link bandwidth is only 1 Mpbs.
 I want it to generate packet loss, but the sendpfast speed will drop due to the link bandwidth. 
Is there any way to solve it?

#### Environment

-   Scapy version: 2.4.3
-   Python version: 3.5.2
-   Operating System: Lubuntu16.04

#### Actual result

     pkt_list = [  ]
     for i in range(15000):
           tmp_pkt = pkt 
           pkt_list.append(tmp_pkt)
     sendpfast(pkt_list, mbps=10)

**Comment by gpotter2** [comment]
Scapy won't go faster than your physical device. Likely, no it's not possible
