### ISSUE TITLE
Incorrect example for `BitFields`

### ISSUE THREAD

**Issue by jpollard-jumptrading** [secdev/scapy#3176]
https://github.com/secdev/scapy/blob/d680d279a9fd37629d5116433af34429a8095576/scapy/fields.py#L2116-L2131

`BitField("a", 0, 9, tot_size=-16)` etc. should read `BitField("a", 0, 9, tot_size=-2)` (16 -> 2), since this is measured in bytes, not bits.

[Unfortunately I cannot raise a PR right now.]

**Comment by gpotter2** [comment]
Thanks a lot for the report, that's indeed a mistake.
Sorry you had to go through all the troubleshooting steps ^^'
