### ISSUE TITLE
Scapy performance on listening packets

### ISSUE THREAD

**Issue by BMWE** [secdev/scapy#3177]
Hello,
 
I'd like to use scapy as part of my python application for real time data analysis and dashboard generation.

I'd like to know the performance of scapy. Part of it: what is the throughput of packets that can be processed, jitter for processing, etc.

**Comment by polybassa** [comment]
Thanks for your interest in Scapy and your question.

First, this is an issue board and bug tracker. So please close this issue and use gitter for discussions. 

Regarding your question. As far as I know, the performance of scapy is highly dependent on your system. The main influencing properties from my understanding are: number of cores, operating system, interpreter and finally your code.


-- 
Best regards,

Nils Weiß
