### ISSUE TITLE
Calling RawPcapReader for a pcap throws a NameError in scapy 2.4.5

### ISSUE THREAD

**Issue by Marc2508** [secdev/scapy#3179]
#### Brief description
After upgrade to scapy 2.4.5 there is a Python name error when using RawPcapReader.

#### Environment
-   Scapy version: 2.4.5
-   Python version: Python 3.6.10
-   Operating System: Ubuntu 18.4

#### How to reproduce
We want to read all packets from a pcap file via:

from scapy.all import *

for (pkt_data, pkt_metadata,) in RawPcapReader("./dummy.pcap"):
    pass

#### Actual result
File "dummy.py", line 1141, in check_for_packets_in_pcap_file
          for (pkt_data, pkt_metadata,) in RawPcapReader("./dummy.pcap"):
File "../lib/python3.6/site-packages/scapy/utils.py", line 1241, in next
          return self.read_packet()
File "../lib/python3.6/site-packages/scapy/utils.py", line 1264, in read_packet
          Packet,
      NameError: name 'Packet' is not defined

#### Expected result
No name error as it was before in 2.4.4. Going back to 2.4.4 solves the issue.

**Comment by robgom** [comment]
Is there going to be a 2.4.6 (or equivalent) release?

**Comment by gpotter2** [comment]
Yeah we'll very likely have to make a 2.4.5.1 or something

**Comment by guedou** [comment]
The fix will be in 2.5.0 or 2.4.6. However, either versions won’t be released soon.

**Comment by robgom** [comment]
Out of curiosity, why not release something sooner? Currently 2.4.5 is on pypi with introduced regression, right? Is 2.4.5.1 not in line with project release policy? Or is there something technical? Personally I'd think about making a branch out of 2.4.5, cherry-pick bugfix and make a release out of it.
