### ISSUE TITLE
AsyncSniffer isn't really async

### ISSUE THREAD

**Issue by github-sys-admin** [secdev/scapy#3184]
```
In [63]: bt = BluetoothHCISocket(1)

In [64]: t = AsyncSniffer(opened_socket=bt)

In [65]: t.start()

In [66]: t.results

In [67]: t.stop()
Out[67]: <Sniffed: TCP:0 UDP:0 ICMP:0 Other:14>

In [68]: t.results
Out[68]: <Sniffed: TCP:0 UDP:0 ICMP:0 Other:14>

In [69]: 
```

This provides no added benefit compared to the synchronous method which is to just: 
```
n [69]: bt = BluetoothHCISocket(1)

In [70]: results = bt.sniff()
^C
In [71]: results?
Type:            PacketList
String form:     <Sniffed: TCP:0 UDP:0 ICMP:0 Other:286>
Length:          286
```

Moreover, if the thread must be stopped before results are updated then there's no point in using it, but ideally this would not be the case and results would be available (perhaps using a queue: https://docs.python.org/3/library/queue.html) as the scanner continued to run.

**Comment by polybassa** [comment]
Hi, thanks for your interest in Scapy. 
IMHO the intention of AsyncSniffer is exactly what you've described. AsyncSniffer runs the sniffer in a background thread, which gives a user the possibility to send packets (or do other stuff) on the main thread. If you want to compute on packets while there are sniffed, you should use the `prn` callback. This can also be added to the AsyncSniffer, which would allow you to put every incoming packet into a queue.

**Comment by github-sys-admin** [comment]
ayyyyy
```
In [74]: import queue

In [75]: pq = queue.Queue()

In [76]: bt = BluetoothHCISocket(1)

In [77]: t = AsyncSniffer(opened_socket=bt, prn = lambda p: pq)

In [78]: t = AsyncSniffer(opened_socket=bt, prn = lambda p: pq.put_nowait(p))

In [79]: t.start()

In [80]: pq
Out[80]: <queue.Queue at 0x7fd86534f6d0>

In [81]: pq.get()
Out[81]: <HCI_Hdr  type=Event |<HCI_Event_Hdr  code=0x3e len=57 |<HCI_Event_LE_Meta  event=13 |<Raw  load='\x01\x13\x00\x01\\xbf\\xfbS\\xbf$\\xe3\x01\x00\\xff\x7f\\xaf\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1f\x02\x01\x06\x16\\xffL\x00\x061\x01\\xb5\\xe1P\\xec\x0e\\xa5\x06\x00\x10\x00\x01\x02\\xd7ܼB\x04\x08A94' |>>>>

In [82]: 
```
thanks a bunch!

**Comment by polybassa** [comment]
You're welcome. Can you please close this issue. 
also... You may want to add the argument `store_results=False` to AsyncSniffer.

**Comment by polybassa** [comment]
and you could do
```
AsyncSniffer(opened_socket=bt, prn = pq.put_nowait)
```

**Comment by github-sys-admin** [comment]
thanks, closing
