### ISSUE TITLE
scapy crashes on v2.4.5

### ISSUE THREAD

**Issue by verthais** [secdev/scapy#3185]
#### Brief description

After upgrading to 2.4.5 from 2.4.4 the folloing [error occurs](#actual-result).

#### Environment

-   Python version: 3.9.2
-   Operating System: Debian 5.10.28-1

#### How to reproduce

```
sudo rm /usr/bin/python
sudo ls -s /usr/bin/python /usr/bin/python3
python
>>> import scapy.arch.pcapdnet
```

#### Actual result

```
Traceback (most recent call last):
  File "./martha/martha.py", line 52, in <module>
    import scapy.arch.pcapdnet

ModuleNotFoundError: No module named 'scapy.arch.pcapdnet'
```

#### Expected result

successfuly import submodule

#### Related resources

n/a

**Comment by gpotter2** [comment]
This module is an internal module and was renamed since we dropped support for dnet.
You shouldn't need to import it. This is by design
