### ISSUE TITLE
EnumFields not raising KeyError

### ISSUE THREAD

**Issue by martingalloar** [secdev/scapy#3200]
#### Brief description

Starting with Scapy 2.4.5 and in Python 2.7, `EnumField`s are not raising `KeyError` when provided with a value not defined as part of the enum and not corresponding to any key.

#### Environment

-   Scapy version:  2.4.5
-   Python version: 2.7
-   Operating System: *

#### How to reproduce

```
class Test(Packet):
    fields_desc = [
        ByteEnumField("enum", 0, {0: "zero", 1: "one"})
    ]

Test(enum=0).show()
Test(enum=1).show()
Test(enum=2).show()
Test(enum="zero").show()
Test(enum="one").show()
Test(enum="two").show()
```

#### Actual result

```
###[ Test ]### 
  enum      = zero

###[ Test ]### 
  enum      = one

###[ Test ]### 
  enum      = 2

###[ Test ]### 
  enum      = zero

###[ Test ]### 
  enum      = one

###[ Test ]### 
  enum      = 'two'
```

#### Expected result

(from Scapy 2.4.4)
```
###[ Test ]### 
  enum      = zero

###[ Test ]### 
  enum      = one

###[ Test ]### 
  enum      = 2

###[ Test ]### 
  enum      = zero

###[ Test ]### 
  enum      = one

Traceback (most recent call last):
  File "enum_test.py", line 15, in <module>
    Test(enum="two").show()
  File "/home/martin/workspace/scapy/scapy/base_classes.py", line 266, in __call__
    i.__init__(*args, **kargs)
  File "/home/martin/workspace/scapy/scapy/packet.py", line 170, in __init__
    self.fields[fname] = self.get_field(fname).any2i(self, value)
  File "/home/martin/workspace/scapy/scapy/fields.py", line 1808, in any2i
    return self.any2i_one(pkt, x)
  File "/home/martin/workspace/scapy/scapy/fields.py", line 1787, in any2i_one
    x = self.s2i[x]
KeyError: 'two'
```

#### Related resources

I think this was introduced somehow in https://github.com/secdev/scapy/commit/f04b0ae1acf0cb72ce71103c52abbbc020405c68#diff-330de0527046a0fc8af1b24fbea040a50e66ca5fcf47b1c9296e48591b383074R2251

**Comment by gpotter2** [comment]
I'm not sure I understand the issue.
This was indeed a bug that we fixed

**Comment by gpotter2** [comment]
Thanks for the report. This will be fixed in https://github.com/secdev/scapy/issues/3218

**Comment by martingalloar** [comment]
Your welcome! I wasn't sure what was the right way to fix it, appreciate you taking a look! Bests.
