### ISSUE TITLE
Wrong Modbus response code / class match

### ISSUE THREAD

**Issue by JulienBedel** [secdev/scapy#3202]
#### Description

Modbus PDUs are determined by function codes. 
Example : a _Read Coils_ PDU is associated with the code _0x01_.

If the received code is superior to _0x80_, then it is interpreted as an exception code. 
Example : a _Read Coils exception PDU_ is associated with the exception code _0x81_.

Scapy's Modbus contrib module associates codes to the appropriate Packet class in various dictionaries.
Example :
```
_modbus_response_classes = {
    0x01: ModbusPDU01ReadCoilsResponse,
    0x02: ModbusPDU02ReadDiscreteInputsResponse,
    0x03: ModbusPDU03ReadHoldingRegistersResponse,
   ...
}
```

In Scapy version: 2.4.4.dev318, some code associations do not fit Modbus specifications. 
For example _ModbusPDU08DiagnosticsResponse_ class is associated with the exception code _0x88_ instead of the response code _0x08_. 
Therefore, when the _0x88_ exception code is received, it is badly interpreted as a Raw payload instead of Modbus PDUs (this is determined in see _ModbusADUResponse_'s _guess_payload_class_ method). 
Similarly, _ModbusPDU0BGetCommEventCounterResponse_ is associated with code _0x8B_ instead of _0x0B_.

I am opening a PR to fix the issue.

#### How to reproduce

```python
>>> from scapy.contrib.modbus import ModbusADUResponse
>>> pkt = ModbusADUResponse(b"\x00\x00\x00\x00\x00\x03\x00\x88\x01")
>>> pkt.show2()
```

#### Actual result

```python
###[ ModbusADU ]### 
  transId   = 0x0
  protoId   = 0x0
  len       = 3
  unitId    = 0x0
###[ Raw ]### 
     load      = '\x88\x01'
```

#### Expected result

```python
###[ ModbusADU ]### 
  transId   = 0x0
  protoId   = 0x0
  len       = 3
  unitId    = 0x0
###[ Diagnostics Exception ]### 
     funcCode  = 0x88
     exceptionCode= Illegal Function Code
```

#### Related resources

Modbus Specifications : https://modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf (sections 6.8 and 6.9)

Packet capture : [modbus_exceptions.zip](https://github.com/secdev/scapy/files/6421496/modbus_exceptions.zip)

**Comment by guedou** [comment]
Fixed in #3203
