### ISSUE TITLE
Pipetools is failing on appveyor

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#3206]
@gpotter2 I looked a little bit into the current errors on appveyor. The reason for the failed tests is the changed value of the ``remainms`` parameter in these lines: https://github.com/secdev/scapy/blob/db698d2ddebb1a0b3fa53247117f0fb6ef9950bc/scapy/automaton.py#L104-L113
But I've to less understanding of windows to figure out whats going on here.

_Originally posted by @polybassa in https://github.com/secdev/scapy/issues/3197#issuecomment-830645927_

**Comment by gpotter2** [comment]
Yeah I investigated a bit but it's driving me crazy.

It seems like the WaitForX methods don't like it when you spam them with a timeout > 0. If the timeout is 0 and they don't actually start waiting and just poll, and it works just fine.

I have to dig further

**Comment by polybassa** [comment]
Let me know, if you want me to try workarounds. I see two possibilities:
1. A while loop with sleep and poll with 0
2. A background thread with fires a stop event after remain and wait INFINITE for objects

**Comment by gpotter2** [comment]
Heh, funny you mention that.

Historically, Automaton on Windows went through option 1 then option 2, in that order. The whole point of this new implementation was to not do that.

**Comment by polybassa** [comment]
funny :-D
I don't like both approaches, though.. 
Just wanted to support you.

**Comment by polybassa** [comment]
Congratulations!
