### ISSUE TITLE
AsyncSniffer start isnt really the start

### ISSUE THREAD

**Issue by splitice** [secdev/scapy#3208]
Lets say scapy is used with a pattern like:

```
t = AsyncSniffer(filter=filter, count=1, timeout=1, iface='qemubr0')
t.start()
send(localpkt)
t.join()
response = t.results
if len(response) != 0:
    print("Expected no packet (1)")
    exit(1)
```

In this case after receiving localpkt the remote server responds with a packet quickly. For the sake of this example persume its reflection. I'm using this pattern for unit testing pattern using scapy.

What I've found is that AsyncSniffer.start can return before the sniffing session is ready. As on establishment of the sniffing session a packet is sent immediately if the remote end replies quickly enough (in this case over a bridge to a Virtual Machine) the response packet can be lost.

For now I've been working around this by adding a small sleep after the `.start` however the more reliable fix would be to have AsyncSniffer wait on the establishment of a sniffing session in the underlying thread. I think this is what everyone who uses the API would expect.

**Comment by gpotter2** [comment]
This is working as intended: you're missing out on `started_callback`.

You should be doing

```python
t = AsyncSniffer(
    filter=filter,
    count=1,
    timeout=1,
    iface='qemubr0',
    started_callback=lambda: send(localpkt)
)
t.start()
t.join()
```
