### ISSUE TITLE
unknown.version in egg.info and in the banner

### ISSUE THREAD

**Issue by danieljakots** [secdev/scapy#321]
Hi,

I'm porting 2.3.3 to OpenBSD. I had two issues:
1. after the install with setuptools, the .egg-info generated is called 'lib/python2.7/site-packages/scapy-unknown.version-py2.7.egg-info'

I patched setup.py to hardcode the version then it worked
```
--- setup.py.orig       Tue Oct 18 10:44:43 2016
+++ setup.py    Mon Oct 31 17:19:45 2016
@@ -47,7 +47,7 @@ if os.name == "nt":
 
 setup(
     name='scapy',
-    version=__import__('scapy').VERSION,
+    version='2.3.3',
     packages=[
         'scapy',
         'scapy/arch',

```
I now have lib/python2.7/site-packages/scapy-2.3.3-py2.7.egg-info

2. running scapy it says "Welcome to Scapy (unknown.version)" even with the setup.py change. I went through scapy-2.3.3/scapy/main.py but I didn't find anything suspicious.

**Comment by p-l-** [comment]
Can you check if the code provided in #326 fixes the problem? Thanks!

**Comment by danieljakots** [comment]
Both problem are still there with your diff.

**Comment by p-l-** [comment]
OK I think I understand. You're getting the archive from a Github link and are not using `git clone`, are you?

**Comment by danieljakots** [comment]
That's it, it fetches https://github.com/secdev/scapy/archive/v2.3.3/scapy-2.3.3.tar.gz

**Comment by p-l-** [comment]
Then the updated PR contains a patch for `scapy/__init__.py` that should work for you.

**Comment by danieljakots** [comment]
With just scapy/__init__.py patch, the .egg-info is solved.
I still have the greeting "Welcome to Scapy (unknown.version)".
So what should I do in your opinion? Backport only the __init__.py or also the setup.py?
What should I expect to be fixed? Only the .egg-info thing or also the greeter?

**Comment by robin-jarry** [comment]
Hi @danieljakots,

you should use this URL:

https://pypi.python.org/packages/ac/14/c792a14b9f8bc4bb9c74c0594c167a2da36e31964098d9e27202142cbd7d/scapy-2.3.3.tgz#md5=65939356f08760ebef836796d3320b3b

instead of github.

The version will be correct.

**Comment by robin-jarry** [comment]
New archives should be downloaded from here: https://pypi.python.org/simple/scapy/

**Comment by danieljakots** [comment]
Hey @robin-jarry fetching them through pypi removes the need to patch the setup.py but I still have "Welcome to Scapy (unknown.version)"

**Comment by robin-jarry** [comment]
I am not familiar with OpenBSD ports system. How is scapy "installed" into `lib/python2.7/site-packages/`from the `.tgz` archive?

Normally, it should be as follows:

```sh
curl "https://pypi.python.org/packages/ac/14/c792a14b9f8bc4bb9c74c0594c167a2da36e31964098d9e27202142cbd7d/scapy-2.3.3.tgz#md5=65939356f08760ebef836796d3320b3b" | tar zxf - &&
cd scapy-2.3.3/ &&
python ./setup.py install
```

**Comment by danieljakots** [comment]
Indeed, it was my fault: Welcome to Scapy (2.3.3)
Thanks!

**Comment by robin-jarry** [comment]
Glad I could help :)

**Comment by p-l-** [comment]
Thanks again @robin-jarry!
