### ISSUE TITLE
Unable to suppress new warnings in 2.4.5

### ISSUE THREAD

**Issue by kprovost** [secdev/scapy#3216]
FreeBSD uses scapy for (some of) its network tests.
With the recent update to 2.4.5 we started seeing regression test failures due to new warnings from scapy, such as:

```
WARNING: No IPv4 address found on epair2b !
WARNING: No IPv4 address found on epair0b !
WARNING: more No IPv4 address found on epair1b !
WARNING: No route found for IPv6 destination ff02::1:ff02:9cab (no default route?)
```

I can work around them using this patch: https://reviews.freebsd.org/D30214 but that’s hardly an ideal solution.

I assume that these warnings have been deliberately introduced, and for good reasons, but they’re somewhat annoying to us. Especially as it often warns about interfaces we’re not even trying to use at the time.

Is there a sane way to tell Scapy to not emit those warnings?
I'm happy to modify our tests to set a 'do_not_complain' flag or something, but I'd prefer to not have to teach them to ignore all stderr output from Scapy.

**Comment by guedou** [comment]
Does using this piece of code https://scapy.readthedocs.io/en/latest/extending.html?highlight=logging#configuring-scapy-s-logger <https://scapy.readthedocs.io/en/latest/extending.html?highlight=logging#configuring-scapy-s-logger> before loading Scapy solve the issue ?

**Comment by kprovost** [comment]
It doesn't no.

I've been experimenting with that as well as trying to add a filter class to the 'scapy.runtime' log (which appears to be the one producing the warnings) without success. I may be misunderstanding something about the Python logging class.

**Comment by guedou** [comment]
Could you share a small script that reproduce the issue?

The following works ok:
```
import logging
logging.getLogger("scapy").setLevel(logging.CRITICAL)

from scapy.all import *

pkt = IPv6()
```

**Comment by kprovost** [comment]
Ah, that was the clue I needed. I was trying to configure the logger after importing scapy, and that doesn't work. Somewhat counterintuitive, but that's probably my own problem rather than a scapy problem.

I think I can work with this. I'm inclined to add a custom filter to ignore irrelevant warnings rather than change the log level, but either one should work.

Thanks!
