### ISSUE TITLE
SuperSocket vlan reconstruction assumes 802.1Q

### ISSUE THREAD

**Issue by washley** [secdev/scapy#3217]
#### Brief description
On Linux, the kernel removes the outermost vlan header on received packets. ```SuperSocket``` reconstructs that header using ```tpacket_auxdata``` to get the original vlan tag. However, it assumes that the tag was an 802.1Q tag, which results in an inaccurate reconstruction for, for example, 802.1AD QinQ tags.

Here's an example of a packet as seen by tcpdump, showing outer tag protocol 802.1AD and inner tag protocol 802.1Q):
```
19:57:56.758891 36:83:6e:c1:c5:e7 > d6:7d:4f:6f:7d:6c, ethertype 802.1Q-QinQ (0x88a8), length 62: vlan 999, p 0, ethertype 802.1Q, vlan 13, p 0, ethertype IPv4, (tos 0x0, ttl 64, id 1, offset 0, flags [none], proto UDP (17), length 40)
    10.10.10.10.42 > 8.8.8.8.53: [udp sum ok] 0+ [0q] (12)
	0x0000:  d67d 4f6f 7d6c 3683 6ec1 c5e7 88a8 03e7  .}Oo}l6.n.......
	0x0010:  8100 000d 0800 4500 0028 0001 0000 4011  ......E..(....@.
	0x0020:  56a1 0a0a 0a0a 0808 0808 002a 0035 0014  V..........*.5..
	0x0030:  da43 0000 0100 0000 0000 0000 0000       .C............
```
and here is the packet captured by Scapy with an AsyncSniffer, showing both tag protocols being 802.1Q:
```
<Ether  dst=d6:7d:4f:6f:7d:6c src=36:83:6e:c1:c5:e7 type=VLAN |<Dot1Q  prio=0 id=0 vlan=999 type=VLAN |<Dot1Q  prio=0 id=0 vlan=13 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=40 id=1 flags= frag=0 ttl=64 proto=udp chksum=0x56a1 src=10.10.10.10 dst=8.8.8.8 |<UDP  sport=nameserver dport=domain len=20 chksum=0xda43 |<DNS  id=0 qr=0 opcode=QUERY aa=0 tc=0 rd=1 ra=0 z=0 ad=0 cd=0 rcode=ok qdcount=0 ancount=0 nscount=0 arcount=0 |>>>>>>
```

Note that the vlan *tags* are fine, it's the protocol that's inaccurate.

In kernel 3.14 the tpacket_auxdata was augmented to contain the original tag protocol. It can be used by Scapy to more accurately reconstruct vlan tags. (https://github.com/torvalds/linux/commit/a0cdfcf39362410d5ea983f4daf67b38de129408)

#### Environment

-   Scapy version: 2.4.4 (no different in 2.4.5)
-   Python version: 3.9
-   Operating System: Linux

**Comment by washley** [comment]
I will need time to get set up to submit a proper PR, but for anyone looking, this is a patch that takes advantage of the tp_vlan_tpid to improve vlan header reconstruction:
```
--- a/scapy/supersocket.py
+++ b/scapy/supersocket.py
@@ -40,6 +40,7 @@ class _SuperSocket_metaclass(type):
 PACKET_AUXDATA = 8
 ETH_P_8021Q = 0x8100
 TP_STATUS_VLAN_VALID = 1 << 4
+TP_STATUS_VLAN_TPID_VALID = 1 << 6
 
 
 class tpacket_auxdata(ctypes.Structure):
@@ -50,7 +51,7 @@ class tpacket_auxdata(ctypes.Structure):
         ("tp_mac", ctypes.c_ushort),
         ("tp_net", ctypes.c_ushort),
         ("tp_vlan_tci", ctypes.c_ushort),
-        ("tp_padding", ctypes.c_ushort),
+        ("tp_vlan_tpid", ctypes.c_ushort),
     ]
 
 
@@ -108,9 +109,12 @@ class SuperSocket(six.with_metaclass(_SuperSocket_metaclass)):
                     if auxdata.tp_vlan_tci != 0 or \
                             auxdata.tp_status & TP_STATUS_VLAN_VALID:
                         # Insert VLAN tag
+                        tpid = ETH_P_8021Q
+                        if auxdata.tp_status & TP_STATUS_VLAN_TPID_VALID:
+                            tpid = auxdata.tp_vlan_tpid
                         tag = struct.pack(
                             "!HH",
-                            ETH_P_8021Q,
+                            tpid,
                             auxdata.tp_vlan_tci
                         )
                         pkt = pkt[:12] + tag + pkt[12:]
```

**Comment by gpotter2** [comment]
Thanks for that report, that sounds like a super fair request. A PR would be very welcomed !

**Comment by guedou** [comment]
@washley does #3241 fixes your issue?

**Comment by washley** [comment]
Thanks for submitting that PR! It looks good, but I have been unable to run scapy in my wsl environment at home, which prevented me from testing my proposed change back when I reported this, and I haven't had time to figure out that problem since then.

I will try to test this in my actual usage scenario (very different environment at work) and let you know.

**Comment by washley** [comment]
I verified the PR's changes against my real environment and am now getting the expected packet out of the AsyncSniffer
```
<Ether  dst=46:28:bf:9f:60:86 src=3a:bf:94:65:f0:22 type=802_AD |<Dot1AD  prio=0 id=0 vlan=999 type=VLAN |<Dot1Q  prio=0 id=0 vlan=13 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=40 id=1 flags= frag=0 ttl=64 proto=udp chksum=0x56a1 src=10.10.10.10 dst=8.8.8.8 |<UDP  sport=nameserver dport=domain len=20 chksum=0xda43 |<DNS  id=0 qr=0 opcode=QUERY aa=0 tc=0 rd=1 ra=0 z=0 ad=0 cd=0 rcode=ok qdcount=0 ancount=0 nscount=0 arcount=0 |>>>>>>
```

This looks good to me!

**Comment by washley** [comment]
That changed was merged, thanks guys!
