### ISSUE TITLE
Add support for non-English paths

### ISSUE THREAD

**Issue by xun-mi-git** [secdev/scapy#3222]
#### Brief description

Does not support non-English path console calling scapy

#### Environment

-   Scapy version: `2.4.5`
-   Python version: `3.8`
-   Operating System: `Windows10`

#### How to reproduce

Call `scapy` when there is a non-English path (for example: c:\chinese\中文)

#### Actual result

The console will prompt: `failed to create process.`

**Comment by guedou** [comment]
Could you provide an example that will allow us to reproduce the issue?

**Comment by gpotter2** [comment]
Most likely not a scapy issue
