### ISSUE TITLE
BTLE_ADV can't set 'Length' > 0x3f

### ISSUE THREAD

**Issue by JiaDuo** [secdev/scapy#3226]
In Ble5.0 BTLE_ADV().Length can be 1-255（8bit）  ,but in the BTLE_ADV  ，it is just 6bit . this is wrong .
this mean you can't create BTLE_ADV() with Length > 0x3f .

https://github.com/secdev/scapy/blob/fdfb7dcd10ab3e84ecfa7f0f10a87581d64dc3c4/scapy/layers/bluetooth4LE.py#L236
https://github.com/secdev/scapy/blob/fdfb7dcd10ab3e84ecfa7f0f10a87581d64dc3c4/scapy/layers/bluetooth4LE.py#L246

**Comment by gpotter2** [comment]
Yeah, it looks like this was updated in BTLE 5 and onwards. I've updated that in https://github.com/secdev/scapy/pull/3242
