### ISSUE TITLE
sniff  Layer [DNSRR] not found

### ISSUE THREAD

**Issue by IsaacLiang** [secdev/scapy#3230]
#### Environment

-   Scapy version: 2.4.5
-   Python version: 3.8
-   Python IDE :spyder
-   Operating System: ubuntu 20.04  

####  Description

i want to sniff  the ip of baidu.com , but some thing error when i run the script. but the same script i run in ubuntu 18.4 & python version 2.76 & scapy 2.4.5

from scapy.all import *
import sys
import time

serverip="10.21.80.99"
result={}
def packetHandler(pkt):
    if pkt.haslayer(DNSQR):	
        if pkt[DNSQR].qname[0:-1] in result.keys():
            result[pkt[DNSQR].qname[0:-1]]=result[pkt[DNSQR].qname[0:-1]]+1
        else:
            result[pkt[DNSQR].qname[0:-1]]=1

def printResult():
    final=sorted(result,key=lambda x: result[x])
    print ("No Of Times Visited"+"   "+"Domain Visited")
    for x in final:
        print ("     "+str(result[x])+"                 "+x	)
find_domain='baidu.com'

def liveView(pkt):
    if pkt.haslayer(DNSQR):
        testt=pkt[DNSQR].qname[0:-1]
        if 'baidu.com' in str(testt):
            print ('the DNS is:'+ str(pkt[DNSQR].qname[0:-1])+'  IP is: '+str(pkt[DNSRR].rdata))

sniff(filter="udp port 53 and ip src "+str(serverip),prn=liveView)
printResult()

####Error info
runfile('/home/pytool/Documents/untitled11.py', wdir='/home/pytool/Documents')
Traceback (most recent call last):

  File "/home/pytool/Documents/untitled11.py", line 43, in <module>
    sniff(filter="udp port 53 and ip src "+str(serverip),prn=liveView)

  File "/root/anaconda3/lib/python3.8/site-packages/scapy/sendrecv.py", line 972, in sniff
    sniffer._run(*args, **kwargs)

  File "/root/anaconda3/lib/python3.8/site-packages/scapy/sendrecv.py", line 925, in _run
    session.on_packet_received(p)

  File "/root/anaconda3/lib/python3.8/site-packages/scapy/sessions.py", line 47, in on_packet_received
    result = self.prn(pkt)

  File "/home/pytool/Documents/untitled11.py", line 39, in liveView
    print ('the DNS is:'+ str(pkt[DNSQR].qname[0:-1])+'  IP is: '+str(pkt[DNSRR].rdata))

  File "/root/anaconda3/lib/python3.8/site-packages/scapy/packet.py", line 1171, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)

IndexError: Layer [DNSRR] not found

**Comment by guedou** [comment]
That is an error in your code. You need to access pkt[DNS].an to retrieve answers. Next time please ask your question on goûter. Thanks
