### ISSUE TITLE
upstream http request 

### ISSUE THREAD

**Issue by erfanask** [secdev/scapy#3237]
hi !
i try to snif HTTP request behind nginx 
for example my app working on port 3000 behind nginx on 443 and 80 .
i try to bind 3000 to HTTP  , thats working when i try to accesss 3000 but when i try to use port 80 or 443 
I can't see requests between nginx and my app on port 3000 .

**Comment by guedou** [comment]
Thanks for your interest in Scapy. Please ask your question on gitter. This is a big tracker.
