### ISSUE TITLE
Frame with a RadioTap header are being parsed incorrectly

### ISSUE THREAD

**Issue by carcigenicate** [secdev/scapy#3238]
#### Brief description

`RadioTap` packets are being parsed improperly, which is causing the rest of the data to be parsed incorrectly as well.

In my specific case, a UDP datagram is being misinterpreted as a Dot11 Reassociation Response.

#### Environment

-   Scapy version: `2.4.5rc1.dev35`
-   Python version: `3.9`
-   Operating System: `ParrotOS` (`Linux parrot 5.10.0-6parrot1-amd64 #1 SMP Debian 5.10.28-6parrot1 (2021-04-12) x86_64 GNU/Linux`)

The capture is being done with a [BrosTrend adapter](https://www.amazon.ca/gp/product/B01BV91L7Y/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1).

#### How to reproduce

Either `sniff` or load a `pcap` using `PcapReader` that contains certain "Radio Tap" headers. Some packets parse fine, many don't.

```python
from scapy.all import *
RadioTap(b'\x00\x00\x15\x00*H\x08\x00\x10\x00v\t\x80\x04\xec\x00\x00\x00\x00\x00\x0e\x88\x010\x00\x00&Z\xfd\x8a\x08\xa0\xc9\xa0\x9d\xaa\xb9\x00&Z\xfd\x8a\x08P\x01\x00\x00\xaa\xaa\x03\x00\x00\x00\x08\x00E\x00\x00KO\xb6@\x00@\x11\xa35\xc0\xa8cd\xc0\xa8c\x01X1\x005\x007\xf4\x97D|\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x11connectivitycheck\x07gstatic\x03com\x00\x00\x01\x00\x01\x8f\x86\x1bH')

<RadioTap  version=0 pad=0 len=21 present=Flags+Channel+dBm_AntSignal+Antenna+RXFlags+MCS Flags=FCS ChannelFrequency=2422 ChannelFlags=2GHz+Dynamic_CCK_OFDM dBm_AntSignal=-20 dBm Antenna=0 RXFlags= knownMCS=MCS_index+guard_interval+HT_format Ness_LSB=1 STBC_streams=0 FEC_type=BCC HT_format=greenfield guard_interval=Long_GI MCS_bandwidth=20MHz MCS_index=1 notdecoded='' |<Dot11FCS  subtype=Reassociation Response type=Management proto=0 FCfield= ID=38 addr1=5a:fd:8a:08:a0:c9 (RA=DA) addr2=a0:9d:aa:b9:00:26 (TA=SA) addr3=5a:fd:8a:08:50:01 (BSSID/STA) SC=0 fcs=0x481b868f |<Dot11ReassoResp  cap=res9+res11+DSSS-OFDM+res15+IBSS+CFP-req+short-preamble+agility status=3 AID=0 |<Dot11Elt  ID=8 len=0 info='' |<Dot11Elt  ID=69 len=0 info='' |<Dot11Elt  ID=SSID len=75 info='O\\xb6@\x00@\x11\\xa35\\xc0\\xa8cd\\xc0\\xa8c\x01X1\x005\x007\\xf4\\x97D|\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x11connectivitycheck\x07gstatic\x03com\x00\x00\x01\x00\x01' |>>>>>>
```

or from a capture (included at the end):

```python
from scapy.all import *

ngRdr = PcapReader("badDNS.pcap")

for pkt in ngRdr:
    print(pkt.show())

###[ RadioTap ]### 
  version   = 0
  pad       = 0
  len       = 21
  present   = Flags+Channel+dBm_AntSignal+Antenna+RXFlags+MCS
  Flags     = FCS
  ChannelFrequency= 2422
  ChannelFlags= 2GHz+Dynamic_CCK_OFDM
  dBm_AntSignal= -20 dBm
  Antenna   = 0
  RXFlags   = 
  knownMCS  = MCS_index+guard_interval+HT_format
  Ness_LSB  = 1
  STBC_streams= 0
  FEC_type  = BCC
  HT_format = greenfield
  guard_interval= Long_GI
  MCS_bandwidth= 20MHz
  MCS_index = 1
  notdecoded= ''
###[ 802.11-FCS ]### 
     subtype   = Reassociation Response
     type      = Management
     proto     = 0
     FCfield   = 
     ID        = 38
     addr1     = 5a:fd:8a:08:a0:c9 (RA=DA)
     addr2     = a0:9d:aa:b9:00:26 (TA=SA)
     addr3     = 5a:fd:8a:08:50:01 (BSSID/STA)
     SC        = 0
     fcs       = 0x481b868f
###[ 802.11 Reassociation Response ]### 
        cap       = res9+res11+DSSS-OFDM+res15+IBSS+CFP-req+short-preamble+agility
        status    = 3
        AID       = 0
###[ 802.11 Information Element ]### 
           ID        = 8
           len       = 0
           info      = ''
###[ 802.11 Information Element ]### 
           ID        = 69
           len       = 0
           info      = ''
###[ 802.11 Information Element ]### 
           ID        = SSID
           len       = 75
           info      = 'O\\xb6@\x00@\x11\\xa35\\xc0\\xa8cd\\xc0\\xa8c\x01X1\x005\x007\\xf4\\x97D|\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x11connectivitycheck\x07gstatic\x03com\x00\x00\x01\x00\x01'


```

This is supposed to be a DNS query (note the `connectivitycheck\x07gstatic\x03com` near the end). Wireshark parses it properly:

![image](https://user-images.githubusercontent.com/18216244/120085771-29931880-c098-11eb-9b8a-3e9abfa1323f.png)

Most of the `RadioTap` header parses fine, but you can see that by the end, the MCS Index is wrong:

![image](https://user-images.githubusercontent.com/18216244/120085831-9c9c8f00-c098-11eb-97d4-76454461dca2.png)

After that it gets worse. It thinks the next layer down is a Reassociation Response, when it should be a `Dot11QoS` (I believe):

![image](https://user-images.githubusercontent.com/18216244/120085861-d2417800-c098-11eb-9c07-2e1fb9c3fbae.png)

#### Related resources

[Sample PCAP](https://drive.google.com/file/d/1HKchuz2v6HsQrudjmGoRT4YvSDqNENQb/view?usp=sharing)

**Comment by gpotter2** [comment]
Could you try out https://github.com/secdev/scapy/issues/3238

**Comment by carcigenicate** [comment]
@gpotter2  Thank you very much. `scapy-2.4.5rc1.dev42` did indeed fix it.

**Comment by gpotter2** [comment]
Great. Closing
