### ISSUE TITLE
clarify scapy (extras or not) requirements

### ISSUE THREAD

**Issue by danieljakots** [secdev/scapy#324]
Hi,

While porting scapy on a system it's a bit a pain to know what depends I should add. For instance if you install scapy from pip:

`
danj@odessa:/usr/local/venv$ . venvscapy/bin/activate                                                                                 
(venvscapy) danj@odessa:/usr/local/venv$ pip install scapy
Collecting scapy
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 333kB/s 
Building wheels for collected packages: scapy
  Running setup.py bdist_wheel for scapy ... done
  Stored in directory: /home/danj/.cache/pip/wheels/bd/cf/05/d5abc9b4434f39ffe231517dfb8dab96241fef6a99459051f9
Successfully built scapy
Installing collected packages: scapy
Successfully installed scapy-2.3.3
(venvscapy) danj@odessa:/usr/local/venv$ scapy                                                                                        
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
ERROR: Unable to import pcap module: No module named pcap/No module named pcapy
ERROR: Unable to import dnet module: No module named dumbnet
INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
Welcome to Scapy (2.3.3)
>>> 
`

Can you add what libraries scapy mandatory needs and what extras requires could be usefull?
Currently on OpenBSD there is

RUN_DEPENDS=    math/py-gnuplot \
                net/libdnet,-python \
                net/py-libpcap \
                security/py-crypto \
                security/py-ecdsa

though I don't know if math/py-gnuplot is really needed as the warning talks about matplotlib.

Doing that would be a great help for packagers! :)

**Comment by guedou** [comment]
Good idea. What is the best way to provide this information ?

Our goal is to limit mandatory dependencies to the strict minimum, i.e. send & receive packets.
Depending on the operating system, there is only a mandatory dependency on dnet and pcap.

PR#221 will make Scapy usable without any dependency on all *BSD.

**Comment by danieljakots** [comment]
Well I'm not a python 'upstream' maintainer, I only package python stuff for OpenBSD and when I want to know what depends a package needs, I usually `grep req setup.py` and that gives enough information (at worse I have to grep -R import *).

As a package maintainer, we usually don't want to provide the strict minimum depends but rather the most we can offer without depending on monster. For instance in the case of scapy we'll probably not depends on py-matplotlib as the message is clear when it's not there, but depending on ecdsa and crypto is not a big deal (but I'm not the scapy maintainer so...).

Let's see after #221 is merged (it seems it moved forward a few days ago) and maybe I'll do a PR if I think of anything.

**Comment by guedou** [comment]
Do you need more than this http://scapy.readthedocs.io/en/latest/installation.html#platform-specific-instructions ?
We could also work on the warning messages if you believe that they are not good enough.

**Comment by danieljakots** [comment]
See #330 to update this page. For now I don't have much more ideas, I'd prefer to wait after #221 :)

**Comment by guedou** [comment]
Thanks. Let's reopen this issue if needed.
