### ISSUE TITLE
Enhancement: New Field to specify packet or payload length ?

### ISSUE THREAD

**Issue by trou** [secdev/scapy#3245]
Hello,
I've been trying to implement a `Packet` with fields which containt:

* the length of the `Packet` itself
* the total length of `Packet`+payload

Which is a common pattern in network protocols.
Looking at `fields.py` and various layers. I could not find a `Field` which would do as described. Most implementations in `layers`  use variations in `post_build` do directly modify `pkt`, which is both error-prone and not expressive.

My knowledge of scapy internals is too limited to identify if this is a design limitation or a missing contribution.

Example code:
```python
class TestPacket(Packet):
    fields_desc = [
        IntField("full_len", 0),
        IntField("self_len", 0),
        XIntField("dummy", default=10)
    ]

    def post_build(self, pkt, pay):
        if not self.full_len:
            full_len = len(pkt)+len(pay)
            pkt = struct.pack('>i', full_len) + pkt[4:]
        if not self.self_len:
            self_len = len(pkt)
            pkt = pkt[:4] + struct.pack('>i', self_len) + pkt[8:]
        return pkt
```
What would be "nice to have":
```python
class TestPacket(Packet):
    fields_desc = [
        PacketPayloadLen("full_len", default=0, fldtype=IntField),
        PacketLen("self_len", default=0, fldtype=IntField),
        XIntField("dummy", default=10)
    ]
```

I hope is this suitable for an issue, please close if not.

**Comment by gpotter2** [comment]
This could have been nice but it would have required to be a special field because how fields work in scapy (they don't have access to the whole constructed packet while being built because.... the packet is being built..), so it's not doable nicely.
`post_build` is also more flexible. This is a wontfix
