### ISSUE TITLE
pdfdump fails to open tmp file

### ISSUE THREAD

**Issue by Lapin-Blanc** [secdev/scapy#325]
Trying to use pkt.pdfdump() fires an error about "random_filename.pdf.pdf" not found.
If I change line 417 in packet.py
    `subprocess.Popen([conf.prog.pdfreader, fname+".pdf"])`
to
    `subprocess.Popen([conf.prog.pdfreader, fname])`
then it works fine. I guess it has to do with the autoext argument used above this line

Hope this will help...

**Comment by Lapin-Blanc** [comment]
Sure !
OS = Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
IPython = IPython 5.1.0
Scapy = Scapy 3.0.0 (installed with pip)

Hope it helps !

**Comment by guedou** [comment]
Unfortunately, that's a Scapy 3 issue (it's a fork). That's why I can't reproduce your issue.

**Comment by Lapin-Blanc** [comment]
Ok ! Sorry, is there a pip version of yours so that I can use it, or should I go with git ?

**Comment by guedou** [comment]
`pip install scapy` will work.

**Comment by dark-lbp** [comment]
The Problem is Scapy default use acroread as pdf reader.If we didn't install acroread on our os pdfdump will raise this problem because there is no acroread file.
```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scapy/packet.py", line 417, in pdfdump
    subprocess.Popen([conf.prog.pdfreader, fname+".pdf"])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I am using osx so this code is work for me.
```python
Welcome to Scapy (2.3.3.dev6)
>>> conf.prog.pdfreader = 'open'
>>> a.pdfdump()
KeyboardInterrupt
>>> a=TCP()
>>> a.pdfdump()
WARNING: No IP underlayer to compute checksum. Leaving null.
Ignoring line 17070 in mapping file 'pdftex.map': Unknown token '<MinLibBol'
Ignoring line 17071 in mapping file 'pdftex.map': Unknown token '<MinLibBol'
Ignoring line 17072 in mapping file 'pdftex.map': Unknown token '<MinLibBol'
Ignoring line 17073 in mapping file 'pdftex.map': Unknown token '<MinLibBolIta'
Ignoring line 17074 in mapping file 'pdftex.map': Unknown token '<MinLibBolIta'
Ignoring line 17075 in mapping file 'pdftex.map': Unknown token '<MinLibBolIta'
Ignoring line 17076 in mapping file 'pdftex.map': Unknown token '<MinLibIta'
Ignoring line 17077 in mapping file 'pdftex.map': Unknown token '<MinLibIta'
Ignoring line 17078 in mapping file 'pdftex.map': Unknown token '<MinLibIta'
Ignoring line 17079 in mapping file 'pdftex.map': Unknown token '<MinLibReg'
Ignoring line 17080 in mapping file 'pdftex.map': Unknown token '<MinLibReg'
Ignoring line 17081 in mapping file 'pdftex.map': Unknown token '<MinLibReg'
>>>
```
May be we should try auto find pdfreader applications or we just check default reader exists and warning if conf.prog.pdfreader is not exists?

**Comment by dark-lbp** [comment]
Sorry, not the same problem, will open new issue.
