### ISSUE TITLE
isis ISIS_P2PAdjacencyStateTlv construction

### ISSUE THREAD

**Issue by minto-dev** [secdev/scapy#3254]
Seeing below issue when  create ISIS IIH packet with point to point tlv(ISIS_P2PAdjacencyStateTlv). Other tlvs are working fine. Wondering what im doing wrong.

Here is a simple code.

#! /usr/bin/env python3

import sys

from scapy.all import *
from scapy.all import sr1,IP,ICMP
from scapy.contrib.isis import *
from scapy.fields import  MACField
from time import  sleep

def buildiih():
    isis_all_is_macaddr = "09:00:2b:00:00:05"
    packet = Dot3(dst=isis_all_is_macaddr, src='56:68:a3:52:3d:b7') / LLC() / ISIS_CommonHdr() / ISIS_P2P_Hello(
        holdingtime=900, sourceid='0520.9316.8108', localcircuitid=3,
        tlvs=[
            ISIS_ProtocolsSupportedTlv(nlpids=["IPv4", "IPv6"]),
            ISIS_AreaTlv(areas=[ISIS_AreaEntry(areaid="49.1000")]),
            ISIS_IpInterfaceAddressTlv(addresses=['1.2.0.2']),
            ISIS_IsNeighbourTlv(neighbours=['56:68:a3:52:3d:68']),
            ISIS_P2PAdjacencyStateTlv(state="Up",extlocalcircuitid=3,neighboursystemid='1280.5303.9165',
                                      neighbourextlocalcircuitid=2)
        ])

    sendp(packet, iface='ens4f2')

buildiih()

  File "/usr/lib/python3.6/logging/__init__.py", line 1413, in makeRecord
    sinfo)
RecursionError: maximum recursion depth exceeded

**Comment by minto-dev** [comment]
Incorrect usage.

**Comment by SimonTina** [comment]
Hello, any ideas? I have the same issue.
