### ISSUE TITLE
No Ips get answered 

### ISSUE THREAD

**Issue by h3cker10632** [secdev/scapy#3265]
i and new to scapy and was trying to make a arp scanner and i had gotten it to work by following a tutorial so i can learn it and it worked the first time not everytime i try and run it again i receive  no answers anyone have any idea why??
here is the code
import sys
from scapy.all import sr1,IP,ICMP
import logging
from scapy.themes import ColorOnBlackTheme
from scapy.all import ARP, Ether, srp

target = "192.168.1.1/24"
#creates a ARP packet which is basically a packet that sends a request on the network which ask who owns this ip address 
arp = ARP(pdst = target)
# ff:ff:ff:ff:ff:ff MAC address indicates broadcasting
ether  = Ether(dst="ff:ff:ff:ff:ff:ff")
#stackss them / combines both packets
packet = ether/arp
#this sends the packets at layer 2 and the timeout is set at 3 seconds so the script wont not work
result = srp(packet, timeout=5)[0]
# a list of clients, we will fill this in the upcoming loop
clients = []
for sent, received in result:
    # for each response, append ip and mac address to `clients` list
    clients.append({'ip': received.psrc, 'mac': received.hwsrc})
#this is going to show the ip address and who they belong to 
print("Available devices in the network:")
print("IP" + " "* 18 + "MAC")
for client in clients:
    print("{:16}    {}".format(client['ip'], client['mac']))

Thank you

**Comment by gpotter2** [comment]
Hi, please **fill the issue template**.

**Comment by h3cker10632** [comment]
#### Brief description

scapy arp program isnt returning any answers from anyother devices besides my own

#### Environment

-   Scapy version: scapy==2.4.5
-   Python version: 3.9
-   Operating System: Windows 10 20H2


#### How to reproduce
the script sends a arp scan to my network which should return the ips of all connected devices on my home network. Example ip 192.168.1.242, 192.168.1.112

#### Actual result

Begin emission:
Finished sending 256 packets.
...................................................................................................................................................................................................*...............................................................................
Received 275 packets, got 1 answers, remaining 255 packets
Available devices in the network:
IP                  MAC
192.168.1.194       94:b8:6d:7f:7c:d1

#### Expected result

Begin emission:
Finished sending 256 packets.
...................................................................................................................................................................................................*...............................................................................
Received 275 packets, got 1 answers, remaining 255 packets
Available devices in the network:
IP                  MAC
192.168.1.194       94:b8:6d:7f:7c:d1

#### Related resources

**Comment by h3cker10632** [comment]
Brief description
scapy arp program isnt returning any answers from anyother devices besides my own

Environment
Scapy version: scapy==2.4.5
Python version: 3.9
Operating System: Windows 10 20H2
How to reproduce
the script sends a arp scan to my network which should return the ips of all connected devices on my home network. Example ip 192.168.1.242, 192.168.1.112

Actual result
Begin emission:
Finished sending 256 packets.
...................................................................................................................................................................................................*...............................................................................
Received 275 packets, got 1 answers, remaining 255 packets
Available devices in the network:
IP MAC
192.168.1.194 94:b8:6d:7f:7c:d1

Expected result
Begin emission:
Finished sending 256 packets.
...................................................................................................................................................................................................*...............................................................................
Received 275 packets, got 1 answers, remaining 255 packets
Available devices in the network:
IP                           MAC
192.168.1.194    94:b8:6d:7f:7c:d1
192.168.1.143    94:b8:6d:7f:7c:d1
192.168.1.243    94:b8:6d:7f:7c:d1
192.168.1.76      94:b8:6d:7f:7c:d1

**Comment by h3cker10632** [comment]
but without the same MAC addresses

**Comment by h3cker10632** [comment]
wait its working now. I dont under stand this i didnt even touch the code and i got it working????? if someone could explain a reason why it may have stopped working for a period of time please let me know thank you
