### ISSUE TITLE
DNSRR parser don't set rdlen

### ISSUE THREAD

**Issue by PhilippTakacs** [secdev/scapy#3269]
#### Brief description

Parsing a DNS Packet don't set rdlen

#### Environment

-   Scapy version: `2da3800b87702178a0f60598aebdd7335ce5603d`
-   Python version: `3.8.5`
-   Operating System: `Ubuntu 20.04.2 LTS`

#### How to reproduce

```
p = DNS(DNS(qd=[DNSQR()],an=[DNSRR()]).build())
print(p.an[0].rdlen)
```

#### Actual result

```
None
```

#### Expected result

```
4
```

**Comment by guedou** [comment]
It is a expected side effect of the way in which Scapy manages the DNS compression.

DNS message are decompressed, but Scapy does not know how to compress back. Setting `rdlen` to None ensure that Scapy will recompute the length if you modify the packet (i.e. calling `raw()` on an unmodified packet will return the compressed version that is stored in an internal cache).

I had a look at the code and there is indeed a bug: `rdlen` is always set to None. I will submit a PR that keep the value is no decompression was involved, and if the RR type does not deal with DNS names.

**Comment by PhilippTakacs** [comment]
This wouldn't solve my problem. I want to extract the unmodified rdata and rdlength of a given DNS Packet. Compressed rdata is the relevant part.

**Comment by Asmeble** [comment]
this needs to be fixed immediately.
