### ISSUE TITLE
[Feature Request] Extensible Record Format (ERF) Support

### ISSUE THREAD

**Issue by dawidjaja** [secdev/scapy#3276]
#### Brief description

Me and my colleague would like to request for Extensible Record Format (ERF) support for Scapy. Specifically, the second type, TYPE_ETH, which is used for the ethernet captures. 
Previously when we want to read an ERF capture file, we convert the ERF file to pcap using wireshark or tshark and pass the pcap to scapy. We think it would be nice if there is direct support for this type is available in Scapy.
Do you know whether this feature already existed previously or has anyone requested for it? We hope we could help contribute to supporting the read and write of the ERF packet.

We would like to hear what do you think about this!

#### Related resources

https://www.endace.com/erf-extensible-record-format-types.pdf

**Comment by guedou** [comment]
Thanks for your message. This sounds like a good idea.

Nobody requested this future before. Feel free to contribute and submit a PR.
