### ISSUE TITLE
How to fuzz based on existing well-formed packet?

### ISSUE THREAD

**Issue by fouzhe** [secdev/scapy#3278]
Hi, all!
In the `Fuzz` function, those fields without pre-assigned values will be randomly generated, as is referred in the [usage](https://github.com/secdev/scapy/blob/430f8942fe086553fcd6ad1444e886a343bfd658/doc/scapy/usage.rst#fuzzing).
However, in general, fuzzing a packet `p` means randomly modify some fields of `p`. 
So, as for a well-formed packet `p`, how to generate a malformed packet `p'` based on `p` using `Fuzz` function, or in other ways?
Thanks!

**Comment by guedou** [comment]
Please ask your question on Gitter. This is a bug tracker, not a forum. Thanks.

**Comment by fouzhe** [comment]
@guedou Got it! Thanks!
