### ISSUE TITLE
Can't sniff Wifi with awus036ach

### ISSUE THREAD

**Issue by victordetarragon** [secdev/scapy#3280]
My issue is simple : I can't sniff at all with this card. This card is working fine with airodump. update & upgrade uptodate. 
When using another card like the 036NHA, I have no issue.

Enviromment : 5.10.0-kali9-amd64 #1 SMP Debian 5.10.46-1kali1 (2021-06-25) x86_64 GNU/Linux
Scapy version : 2.4.4
Driver of the card : latest

Do you have an idea of how can I debug and investigate the issue ?

```
└─$ sudo python3                                               
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
>>> from scapy.all import *
>>> sniff(count=4, iface="wlan1mon")
<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
>>> sniff(count=4, iface="wlan1mon")
<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
>>> exit()
```

**Comment by guedou** [comment]
Please ask you question on gitter. Thanks.
