### ISSUE TITLE
The `post_build` doesn't work sometimes

### ISSUE THREAD

**Issue by grandnew** [secdev/scapy#3282]
### Brief description

The `post_build` doesn't work sometimes. 
For those initialized packets, when some fields are set to other values, those late evaluated fields (like checksums, length, etc.) won't be updated.
For example, for one `IP` packet `p`, when the `frag` of `p` is set another value, the `chksum` field won't be recalculated.
The reason is that those fields won't be recalculated when they owns value (like [this](https://github.com/secdev/scapy/blob/master/scapy/layers/inet.py#L529)).

### Scapy version

2.4.5

### Python version

2.7

### Operating system

Ubuntu 18.04 LTS

### How to reproduce

```python
pkt=IP(hex_bytes("450001e0a5764000401148bec0a86488c0a864ff"))
pkt.show2()
setattr(pkt, 'frag', 1)
pkt.show2()
```

### Actual result

```
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 480
  id        = 42358
  flags     = DF
  frag      = 0
  ttl       = 64
  proto     = udp
  chksum    = 0x48be
  src       = 192.168.100.136
  dst       = 192.168.100.255
  \options   \

###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 480
  id        = 42358
  flags     = DF
  frag      = 1
  ttl       = 64
  proto     = udp
  chksum    = 0x48be
  src       = 192.168.100.136
  dst       = 192.168.100.255
  \options   \
```

### Expected result

```
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 480
  id        = 42358
  flags     = DF
  frag      = 1
  ttl       = 64
  proto     = udp
  chksum    = 0x48bd
  src       = 192.168.100.136
  dst       = 192.168.100.255
  \options   \
```

**Comment by guedou** [comment]
Please ask your question on gitter.

**Comment by grandnew** [comment]
@guedou Actually, I think it may be a bug.
