### ISSUE TITLE
Query a Nameserver Directly

### ISSUE THREAD

**Issue by AlexandertheG** [secdev/scapy#3285]
### Brief description

Hello,

How do I make a DNS request in scapy similar to dig NS org. @l.root-servers.net?
In short, I need to be able to query nameservers authoritative  for a zone directly.

Thanks,
Alex

### Scapy version

2.4.5

### Python version

3.9.2

### Operating system

5.10.25

### How to reproduce

```
#!/usr/bin/env python3
from scapy.all import DNS, DNSQR, IP, sr1, UDP, DNSRR

dns_req = IP(dst='199.7.83.42')/UDP(dport=53)/DNS(qd=DNSQR(qname='org.', qtype='NS'))
answer = sr1(dns_req, verbose=0)

print(answer[DNS].summary())
```

### Actual result

`DNS Ans`

### Expected result

```
a0.org.afilias-nst.info.
a2.org.afilias-nst.info.
b0.org.afilias-nst.org.
b2.org.afilias-nst.org.
c0.org.afilias-nst.info.
d0.org.afilias-nst.org.
```

**Comment by guedou** [comment]
Closing as the question was asked on gitter.
