### ISSUE TITLE
CRITICAL: UTScapy not evaluating negative tests

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#3298]
This doesn't look right: https://github.com/secdev/scapy/pull/3297/checks?check_run_id=3101689141#step:5:344

_Originally posted by @polybassa in https://github.com/secdev/scapy/issues/3297#issuecomment-882325754_

**Comment by polybassa** [comment]
https://github.com/secdev/scapy/pull/3297/files#diff-1b4da539cb05c0c5be1b43cb1272f8b4336df1ad54b854a66c09505084067600R51-R55

This is the code

**Comment by gpotter2** [comment]
Thanks for the catch. I missed that
