### ISSUE TITLE
pdfdump fails to run due to missing dependencies missing in installation process

### ISSUE THREAD

**Issue by Johnny-Five1982** [secdev/scapy#3301]
### Brief description

Looking into source of the problem it mentioned that `TexLive` or `MikTeX` need to be installed as "Extra" dependencies. After trying to install either, it fails.  I did notice that neither the source nor requirements listed the versions. Worse, the requirement.txt is missing.

What is the required version for either one of these dependencies to enable **pdfump()** to work as it should be?

### Scapy version

2.4.5

### Python version

3.9.0

### Operating system

Windows 10

### How to reproduce

```
from scapy.all import sniff
try:
    import pyx
except ImportError as e:
    print(f"ImportError: {e}")

iface = "Intel(R) Dual Band Wireless-AC 3168"
pkts = sniff(count=5, iface=iface)
print(pkts.summary())
print(pkts[0].pdfdump())
```

### Actual result

```
>>> pkts[0].pdfdump()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\guest\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\base_classes.py", line 464, in pdfdump
    canvas = self.canvas_dump(**kargs)
  File "C:\Users\guest\AppData\Local\Programs\Python\Python39\lib\site-packages\scapy\packet.py", line 752, in canvas_dump
    raise ImportError("PyX and its dependencies must be installed")
ImportError: PyX and its dependencies must be installed
```

### Expected result

See the pdf dump?

### Related resources

n/a

**Comment by Johnny-Five1982** [comment]
After commenting out lines `49, 754-755` in `packet.py`, was able to execute. 

This allowed it to run as it should. The problem was it it not importing pxy as it was supposed too. 
```
#from scapy.extlib import PYX
import pyx
```
```
        #if PYX == 0:
        #    raise ImportError("PyX and its dependencies must be installed")
```

Further analysis shows that it is a problem with pxy itself. Seems to be missing latex executable. 

```
  File "C:\Users\guest\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified 
  File "C:\Users\guest\AppData\Local\Programs\Python\Python39\lib\site-packages\pyx\text.py", line 1078, in _execute
    self.texoutput.expect(None)
AttributeError: 'SingleTexEngine' object has no attribute 'texoutput'

```
texoutput is not instantiated and latex is not loaded.

**Comment by polybassa** [comment]
Thanks for your report. This is an intended behavior and not a bug. Since Tex is a huge package, it's not desired to put this into the requirements of the scapy package. Otherwise ever user of scapy would be required to download multiple gigabytes of data in order to use scapy.

This lazy import is used to have Tex as an optional dependency.

**Comment by Johnny-Five1982** [comment]
Thanks for getting back on this. Can this information be placed in the error message linking to github wiki page instructing how this is to be done instead of just lazy passing? It is not clear how this is enabled and installed.

**Comment by gpotter2** [comment]
Yeah we could just run pyx and let it crash into oblivion but we instead added an additional check to make sure `tex` is properly installed and show an error message. This is also written in the doc: https://scapy.readthedocs.io/en/latest/installation.html#optional-dependencies
