### ISSUE TITLE
A question regarding PROFINET I/O

### ISSUE THREAD

**Issue by santoshpanda1989** [secdev/scapy#3304]
Hi,

I am very much new to Scapy. I want to create a program which will sniff PROFINET traffic and then process them according to its corresponding GSD.
I want to know, how should I start?

Thanks in advance,
Santosh

**Comment by polybassa** [comment]
Please note that this is a bug tracker. Feel free to ask your question on gitter and please close this issue.

**Comment by santoshpanda1989** [comment]
Ok. will do that.
