### ISSUE TITLE
MPLS EOS Guessing payload

### ISSUE THREAD

**Issue by nranns** [secdev/scapy#331]
Guessing the payload class of an MPLS header should return 'MPLS' when the end-of-stack bit is not set;

diff --git a/scapy/contrib/mpls.py b/scapy/contrib/mpls.py
index 640a0c5..8165f5b 100644
--- a/scapy/contrib/mpls.py
+++ b/scapy/contrib/mpls.py
@@ -17,7 +17,9 @@ class MPLS(Packet):
                     ByteField("ttl", 0)  ]
 
    def guess_payload_class(self, payload):
-       if len(payload) >= 1:
+      if not self.s:
+         return MPLS;
+      if len(payload) >= 1:
            ip_version = (ord(payload[0]) >> 4) & 0xF
            if ip_version == 4:
                return IP

**Comment by gpotter2** [comment]
@p-l- Fixed in https://github.com/secdev/scapy/pull/576. May close this.
