### ISSUE TITLE
FieldLenField usage

### ISSUE THREAD

**Issue by LensHunnel** [secdev/scapy#3319]
Hi,
I'm new to Scapy and I'm trying to extract data from pfsync packet in a pcap file. I want to  create  Scapy packets class that match PFSYNC traffic. I'm actually stuck because of the structure of PFsync Packet. A packet contains :
an Ethernet header -> IP Header (with proto field value 240)->  PFSync Header  -> PFSync subheader (That one contains a field action and another field count,  The value of action field of subheader says which type of the next header and the value of count says how many of that header)  -> N x PfSync State[TYPE] (with N equal count field and TYPE depending on field action).

an extract of my code: https://gist.github.com/LensHunnel/3fe393f6f26a09669b20d5bbba334a05

When I execute my code, It seems like Scapy is not using the FieldLenField "count" to stop dissecting more PfSyncStateInsert Packet. 

an example of a pcap file : [pfsync_example.zip](https://github.com/secdev/scapy/files/6917592/pfsync_example.zip)

**Comment by polybassa** [comment]
Hi, 

This is a bug tracker.
Could you please ask your question on gitter and close this issue.
--
