### ISSUE TITLE
[UTscapy] xunit output format is undocumented and broken

### ISSUE THREAD

**Issue by zabbal** [secdev/scapy#3330]
### Brief description

The code for 'xunit' output format is present in UTscapy but is not documented in '--help' output and is broken under py3.

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Ubuntu 21.04

### Additional environment information

GNU/Linux, scapy installed via pip3.

### How to reproduce

python3 -m scapy.tools.UTscapy -c test.utsc -f xunit -o utscapy.xml -N
python3 -m scapy.tools.UTscapy -h

### Actual result

...
output += ' <testcase classname="%s"\n' % testset.name.encode("string_escape").replace('"', ' ')  # noqa: E501
LookupError: unknown encoding: string_escape

### Expected result

...
✓ All campaigns executed. Writing output...
UTscapy ended successfully

### Related resources

The string_escape encoder is absent in python 3 because the strings are always utf. Simply dropping the .encode() call fixes it. It would still be nice to get the supported format properly documented though.

**Comment by Asmeble** [comment]
this needs to be fixed
