### ISSUE TITLE
RFC error (from stack over flow)

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#334]
What do you guys think of this:
http://stackoverflow.com/a/39439585/5459467

> That struct.pack has no chance of working, it at least should be:
> 
> return struct.pack("HH", *self.mladdr)+self.payload.hashnet()
> So that struct.pack has no chance of receiving the two arguments needed for "HH". That is a bug.

**Comment by p-l-** [comment]
That's clearly a bug. My guess is that `self.mladdr` being an IPv6 address, the proposed fix (`using *self.mladdr`) won't work either. PR #335 uses the IPv6 address itself in the hash (I'm not sure whether this was intended in the current code).
