### ISSUE TITLE
Send/Receive loop is not working over WWAN interface

### ISSUE THREAD

**Issue by zabbal** [secdev/scapy#3341]
### Brief description

I've got WWAN interface up and running. I can ping through it, I can run nmap scans over it. The interface is set up with the help of qmi-network and systemd-netword in raw-ip mode. Physical side of things is USB-connected QMI-controlled modem with unlocked SIM.

The trivial scapy example:
`ans, unans = srloop(IP(dst = "8.8.8.8") / ICMP(), iface = "wlan0", count = 4, timeout = 4)`
works like a charm, packets (both requests and replies) are visible in wireshark.

The same example on WWAN interface:
`ans, unans = srloop(IP(dst = "8.8.8.8") / ICMP(), iface = "wwan0", count = 4, timeout = 4)`
fails - there're no packets in wireshark, not even requests.

How can I debug this further?
Have somebody used scapy with WWAN interfaces?
Could it be somehow related to raw-IP vs 802.3 encapsulation?

### Scapy version

2.4.4

### Python version

3.9

### Operating system

Ubuntu 21.04

### How to reproduce

Try to send some packets over WWAN interface.

### Actual result

Nothing happens - wireshark register no packets from scapy.

### Expected result

Packets being sent.

### Related resources

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/net/usb/qmi_wwan.c?id=32f7adf633b9f99ad5089901bc7ebff57704aaa9

**Comment by gpotter2** [comment]
You might want to retry on layer 2 first (`srploop`, but add the proper l2 layer first).. I never tried to use one of those with Scapy, but if it works in linux it should also work here :/

**Comment by zabbal** [comment]
Tried working with L2 directly - it's a bit better but still broken:
`
# Baseline - works over regular wi-fi as expected:
ans, unans = srploop(Ether() / IP(dst = "8.8.8.8") / ICMP(), iface = "wlan0", count = 4, timeout = 4)

# Expected failure - produce packets which wireshark fails to decode:
ans, unans = srploop(Ether() / IP(dst = "8.8.8.8") / ICMP(), iface = "wwan0", count = 4, timeout = 4)

# Results in proper outgoing packets in wireshark but no response is received:
ans, unans = srploop(IP(dst = "8.8.8.8") / ICMP(), iface = "wwan0", count = 4, timeout = 4)
`
So simply stripping off Ethernet header is not enough - something is still broken. Could it be smth in the receive path?

The only difference I could spot between scapy's ping and regular ping on the same WWAN interface is that former has ID and SEQ equals 0.

**Comment by gpotter2** [comment]
The L2 layer is very likely not Ether when working on `wwan`. In this case you can probably remain on layer 3 (it looks like Scapy is doing its job properly). You could try `conf.L2socket(iface="wwan0").LL` to see the linktype.

You said in your initial issue that

> Nothing happens - wireshark register no packets from scapy.

However you now just mentioned that

> Results in proper outgoing packets in wireshark

So what is it? If you do see outgoing packets in Wireshark, it means Scapy is doing it's job properly and this is not a bug.

**Comment by zabbal** [comment]
Indeed, the L2socket is `scapy.layers.inet.IP`.

The bug is about `sr*loop()` not working properly over such (WWAN) interface. Fixing sending is good but it takles half of the problem - the lack of ping response means that smth is still broken in srploop: the same code works fine with different interface.

I can make a separate ticket or I can adjust the name of this one to better describe the problem.

**Comment by zabbal** [comment]
Doh! No idea how I missed it but the problem should have been obvious - by default scapy picks up wrong src IP - when using wwan0 interface via srploop the IP is taken from different interface. Specifying the proper IP fixed the issue.

No idea why the wrong IP is selected by default - is it worth creating separate issue about it?

**Comment by guedou** [comment]
Could you share the output of `conf.route`?

**Comment by zabbal** [comment]
Here it is:

```
>>> conf.iface
'wlan0'
>>> conf.route
Network      Netmask          Gateway      Iface            Output IP    Metric
0.0.0.0      0.0.0.0          192.168.0.1  wlan0            192.168.0.7  600
0.0.0.0      0.0.0.0          10.203.48.2  wwan0            10.203.48.1  4096
10.0.3.0     255.255.255.0    0.0.0.0      lxcbr0           10.0.3.1     0
10.203.48.0  255.255.255.252  0.0.0.0      wwan0            10.203.48.1  0
10.203.48.2  255.255.255.255  0.0.0.0      wwan0            10.203.48.1  4096
127.0.0.0    255.0.0.0        0.0.0.0      lo               127.0.0.1    1
169.254.0.0  255.255.0.0      0.0.0.0      wlan0            192.168.0.7  1000
172.17.0.0   255.255.0.0      0.0.0.0      docker0          172.17.0.1   0
172.18.0.0   255.255.0.0      0.0.0.0      br-8448aabc4e32  172.18.0.1   0
192.168.0.0  255.255.255.0    0.0.0.0      wlan0            192.168.0.7  600

```

**Comment by guedou** [comment]
To reach out, Scapy will select both default routes. As a tie-break, it uses the value from the Metric column. Here, `wlan0` will be selected.

Could alter you routing table with the following command before sending the packet?
```
conf.routes.route = [r for r in conf.route.routes if r[3] != "wlan0" and r[0] != 0]
```

**Comment by zabbal** [comment]
I see, so current `conf.iface` and the `iface` argument for `sr*()` are not taken into account when selecting src IP? Seems counter-intuitive to me - perhaps it makes sense to document this?

**Comment by guedou** [comment]
This `iface` values are used to specify the output interface. This is separated from the routing table, to leave users the opportunity to build any packet they want.
Here, your issue is caused by the Metric value on the wwan0 default route.
