### ISSUE TITLE
After fuzzing the copied packet, the original packet is also modified

### ISSUE THREAD

**Issue by waeva** [secdev/scapy#3347]
### Brief description
here's my code
```
from scapy.all import *

class TEST2(Packet):
    name = "TEST2"
    fields_desc = [
        ByteField("type2", 0x1),
    ]
    
class TEST(Packet):
    name = "TEST"
    fields_desc = [
        PacketListField("packlist", TEST2(), TEST2),
    ]
    
d1 = TEST()
d2 = d1.copy()

hexdump(d1)
fuzz(d2)
hexdump(d1)
```
The running results are different in python2 and python3.
In python3, after fuzzing d2 packet, d1 is modified.
```
usr@test:~/WorkSpace$ python3 test.py 
0000  01                                               .
0000  8A                                               .
```
In python2, after fuzzing d2 packet, d1 has not been modified.
```
usr@test:~/WorkSpace$ python2 test.py 
0000  01                                               .
0000  01                                               .
```
For PacketListField, the results of the copy() method running with python2 and python3 seem to be different.
I found the definition of do_copy() in fields.py
```
def do_copy(self, x):
    # type: (I) -> I
    if hasattr(x, "copy"):
        return x.copy()  # type: ignore
    if isinstance(x, list):
        x = x[:]  # type: ignore
        for i in range(len(x)):
            if isinstance(x[i], BasePacket):
                x[i] = x[i].copy()
    return x
```
In python3, the list data type has a copy attribute, ```hasattr(list, "copy") ```returns true.
```
usr@test:~/WorkSpace$ python3
Python 3.8.10 (default, Jun  2 2021, 10:49:15)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> list = []
>>> hasattr(list, "copy")
True
>>>
```
In python2, the list data type has no copy attribute, ```hasattr(list, "copy") ```returns false.
```
usr@test:~/WorkSpace$ python2
Python 2.7.12 (default, Mar  1 2021, 11:38:31) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> list = []
>>> hasattr(list, "copy")
False
>>>
```
so I guess this is the reason why copy() method runs differently in python2 and python3.

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Ubuntu 20.04

### How to reproduce

see brief description

### Actual result

After fuzzing the copied packet, the original packet is modified.

### Expected result

After fuzzing the copied packet, the original packet has not been modified.

**Comment by guedou** [comment]
Good catch! Will you mind providing a fix?
