### ISSUE TITLE
p0f unit test is failing

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#3353]
### Brief description

p0f unit test is failing:

Here is a debug output:
```
######
## Tests for p0f_impersonate
######


###(009)=[failed] Check that the impersonated packet is properly detected by p0f

>>> pkt = p0f_impersonate(IP()/TCP(), osgenre="Linux", osdetails="3.11 and newer")
>>> print(p0f(pkt))
(('g', 'unix', 'Linux', '2.2.x-3.x'), 0, False)
>>> assert p0f(pkt) == (("s", "unix", "Linux", "3.11 and newer"), 0, False)
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AssertionError
```

Here the link to the test machine: https://github.com/secdev/scapy/pull/3352/checks?check_run_id=3459093701

### Scapy version

latest version at github

### Python version

3.9

### Operating system

ubuntu-latest libpcap 3.9 root 

### How to reproduce

Fails sometimes on CI

**Comment by guedou** [comment]
I am currently investigating this issue in #3364
