### ISSUE TITLE
Cannot send IPv6 packet to loopback

### ISSUE THREAD

**Issue by lewis1ee** [secdev/scapy#3357]
### Brief description

I successfully send packet to loopback using IPv4 and see it in wireshark.
but I failed to reproduce it using IPv6.
Ping to "::1" success.

### Scapy version

2.4.5

### Python version

3.9.1

### Operating system

Windows 10 x64 20H2

### Additional environment information

>>> conf.route6
Destination                    Next Hop  Iface                                       Src candidates             Metric
::1/128                        ::        Software Loopback Interface 1               ::1                        331
fe80::/64                      ::        Realtek PCIe GbE Family Controller          fe80::d151:508b:32c5:ca77  261
fe80::/64                      ::        Realtek PCIe GbE Family Controller #2       fe80::811d:90f6:b77e:910a  261
fe80::/64                      ::        Bluetooth Device (Personal Area Network)    fe80::444b:1fc1:52f4:179e  321
fe80::/64                      ::        Intel(R) Wi-Fi 6 AX200 160MHz               fe80::5457:6869:6276:8d77  301
fe80::/64                      ::        VMware Virtual Ethernet Adapter for VMnet1  fe80::5dbc:cb5d:28:89bc    291
fe80::/64                      ::        VMware Virtual Ethernet Adapter for VMnet8  fe80::fcf1:50ae:cadc:b72d  291
fe80::/64                      ::        Microsoft Wi-Fi Direct Virtual Adapter      fe80::cd7c:1ac:7cb4:8875   281
fe80::/64                      ::        Microsoft Wi-Fi Direct Virtual Adapter #2   fe80::cceb:b6a6:b303:5195  281
fe80::444b:1fc1:52f4:179e/128  ::        Bluetooth Device (Personal Area Network)    fe80::444b:1fc1:52f4:179e  321
fe80::5457:6869:6276:8d77/128  ::        Intel(R) Wi-Fi 6 AX200 160MHz               fe80::5457:6869:6276:8d77  301
fe80::5dbc:cb5d:28:89bc/128    ::        VMware Virtual Ethernet Adapter for VMnet1  fe80::5dbc:cb5d:28:89bc    291
fe80::811d:90f6:b77e:910a/128  ::        Realtek PCIe GbE Family Controller #2       fe80::811d:90f6:b77e:910a  261
fe80::cceb:b6a6:b303:5195/128  ::        Microsoft Wi-Fi Direct Virtual Adapter #2   fe80::cceb:b6a6:b303:5195  281
fe80::cd7c:1ac:7cb4:8875/128   ::        Microsoft Wi-Fi Direct Virtual Adapter      fe80::cd7c:1ac:7cb4:8875   281
fe80::d151:508b:32c5:ca77/128  ::        Realtek PCIe GbE Family Controller          fe80::d151:508b:32c5:ca77  261
fe80::fcf1:50ae:cadc:b72d/128  ::        VMware Virtual Ethernet Adapter for VMnet8  fe80::fcf1:50ae:cadc:b72d  291
ff00::/8                       ::        Software Loopback Interface 1               ::1                        331

>>> conf.ifaces
Source   Index  Name                                        MAC                IPv4             IPv6
libpcap  1      Software Loopback Interface 1               00:00:00:00:00:00  127.0.0.1        ::1
libpcap  11     Realtek PCIe GbE Family Controller #2       LCFCHeFe:73:d7:52  169.254.145.10   fe80::811d:90f6:b77e:910a
                                                                               192.168.23.146
libpcap  12     VMware Virtual Ethernet Adapter for VMnet1  VMware:c0:00:01    192.168.204.1    fe80::5dbc:cb5d:28:89bc
libpcap  14     WAN Miniport (IPv6)
libpcap  18     Microsoft Wi-Fi Direct Virtual Adapter      IntelCor:30:e8:8d  169.254.136.117  fe80::cd7c:1ac:7cb4:8875
libpcap  20     VMware Virtual Ethernet Adapter for VMnet8  VMware:c0:00:08    192.168.11.1     fe80::fcf1:50ae:cadc:b72d
libpcap  21     Intel(R) Wi-Fi 6 AX200 160MHz               IntelCor:30:e8:8c  10.33.94.44      fe80::5457:6869:6276:8d77
libpcap  4      Realtek PCIe GbE Family Controller          LCFCHeFe:73:d7:53  169.254.202.119  fe80::d151:508b:32c5:ca77
libpcap  5      Microsoft Wi-Fi Direct Virtual Adapter #2   ca:e2:65:30:e8:8c  169.254.81.149   fe80::cceb:b6a6:b303:5195
libpcap  6      Bluetooth Device (Personal Area Network)    IntelCor:30:e8:90  169.254.23.158   fe80::444b:1fc1:52f4:179e
libpcap  7      WAN Miniport (IP)
libpcap  9      WAN Miniport (Network Monitor)

### How to reproduce

IPv6 send loopback code[FAILED]:
```
from scapy.all import *

iface = "Software Loopback Interface 1"

p = IPv6() / (b"a" * 0x10)

p.show()
"""
###[ IPv6 ]###
  version   = 6
  tc        = 0
  fl        = 0
  plen      = None
  nh        = No Next Header
  hlim      = 64
  src       = ::1
  dst       = ::1
###[ Raw ]###
     load      = 'aaaaaaaaaaaaaaaa'
"""

send(p, iface=iface)
```

IPv4 send loopback code[SUCCESS]:
```
from scapy.all import *

p = IP() / (b"a" * 0x10)
send(p)
```

### Actual result

packet not found in wireshark

### Expected result

packet found in wireshark

**Comment by guedou** [comment]
Could you share the Wireshark output for IPv4?

**Comment by lewis1ee** [comment]
> Could you share the Wireshark output for IPv4?

Thanks for your reply, here is the wireshark output.

![image](https://user-images.githubusercontent.com/12009842/131944879-0ad31395-ae96-4211-911f-139d04bccabc.png)

**Comment by guedou** [comment]
Thanks. Are you certain that it is the result of injecting `p = IPv6() / (b"a" * 0x10)`?

The bytes show in the screenshot correspond to an IPv4 packet.

**Comment by lewis1ee** [comment]
No, it is the result of `p = IP() / (b"a" * 0x10)`, maybe I misunderstand your last reply.

There is no pakcet captured in wireshark when I injecting `p = IPv6() / (b"a" * 0x10)`

**Comment by guedou** [comment]
Sorry for the misunderstanding! I cannot test this right now as I don't have access to a Windows VMs.

Does using `ping6 ::1` works? Can you share the corresponding Wireshark output?

**Comment by guedou** [comment]
It seems that a specific Link Layer header need to be used. I successfully inject a frame on my Windows 10 loopback using:
```
>>> sendp(b"\x18\x00\x00\x00" + raw(IPv6() / ICMPv6EchoRequest(data="Scapy was there!")))
  
>>> sendp(b"\x02\x00\x00\x00" + raw(IP(dst="127.0.0.1") / ICMP() / b"Scapy was there!"))
```

@gpotter2 do you know how we can force the addition of this "Loopback Layer" for Windows? This looks exactly like https://github.com/secdev/scapy/blob/513f2dacaeefcc45c01fabce70f70d228ee5a194/scapy/layers/l2.py#L625

**Comment by guedou** [comment]
FTR, this patch makes Scapy inject correctly with `sr1(IPv6 / ICMPv6EchoRequest())`:

```
diff --git a/scapy/layers/inet6.py b/scapy/layers/inet6.py
index 7ee7f58c..ac88ea67 100644
--- a/scapy/layers/inet6.py
+++ b/scapy/layers/inet6.py
@@ -4071,7 +4071,7 @@ bind_layers(Ether, IPv6, type=0x86dd)
 bind_layers(CookedLinux, IPv6, proto=0x86dd)
 bind_layers(GRE, IPv6, proto=0x86dd)
 bind_layers(SNAP, IPv6, code=0x86dd)
-bind_layers(Loopback, IPv6, type=socket.AF_INET6)
+bind_layers(Loopback, IPv6, type=0x18)
 bind_layers(IPerror6, TCPerror, nh=socket.IPPROTO_TCP)
 bind_layers(IPerror6, UDPerror, nh=socket.IPPROTO_UDP)
 bind_layers(IPv6, TCP, nh=socket.IPPROTO_TCP)
```

**Comment by lewis1ee** [comment]
Thank you @guedou very much! That's the problem and the solution!

I have tested `sendp(b"\x18\x00\x00\x00" + raw(IPv6() / ICMPv6EchoRequest(data="Scapy was there!")))` and it worked.

**Comment by guedou** [comment]
I will leave the issue open until this fix is merged.
