### ISSUE TITLE
InvocationError on py39-bsd_root

### ISSUE THREAD

**Issue by polybassa** [secdev/scapy#3376]
### Brief description

I've discovered InvocationErrors on py39-bsd_root CI machines. Here is an example:
https://github.com/secdev/scapy/pull/3328/checks?check_run_id=3732737538#step:5:6150

### Scapy version

current

### Python version

3.9

### Operating system

OS X

### How to reproduce

This bug seems sporadic

**Comment by guedou** [comment]
I really don't know what is causing this.

**Comment by guedou** [comment]
Have you seen this error often?

**Comment by polybassa** [comment]
I observed it a couple of times.
-- 
Viele Grüße

Nils Weiß

**Comment by gpotter2** [comment]
I've identified the issue. It appears that the new timeout failure isn't actually displaying the timeout message before closing

**Comment by guedou** [comment]
Coud we close this issue? It seems that it was fixed by #3397

**Comment by gpotter2** [comment]
fixed in https://github.com/secdev/scapy/pull/3399
