### ISSUE TITLE
Gitbub Actions & macOS Big Sur

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#3398]
Some unit tests related to `ctypes.util.find_library("pcap")` fail on macOS Big Sur. This is likely related to this issue https://bugs.python.org/issue41179 as the Python interpreters used by Github Actions does not seem to be the ones shipped by Apple.

Scapy is [currently](https://github.com/secdev/scapy/pull/3393) only tested on 10.15.

**Comment by gpotter2** [comment]
This was fixed ages ago.
