### ISSUE TITLE
NetBIOS QUESTION_NAME always have space padding instead end with \x00

### ISSUE THREAD

**Issue by Neutree** [secdev/scapy#3405]
### Brief description

When use `NBNSQueryRequest` to send NetBIOS query request,  when I set QUESTION_NAME  to` b'*'`, but the final bytes always have space padding instead end with \x00, like `b'*              '`

Is this a feature or bug? If a bug, I fixed it [here](https://github.com/Neutree/scapy/commit/3695a9f0ac7b820f33dc7b5d9ea12d4b0c8b6c7f), I can create a PR

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Win10 and Manjaro latest

### How to reproduce

```
p=NBNSQueryRequest(QUESTION_NAME= '*', QUESTION_TYPE='NBSTAT')
raw(p)
```

### Actual result

```
b'\x00\x00\x01\x10\x00\x01\x00\x00\x00\x00\x00\x00 CKCACACACACACACACACACACACACACAAA\x00\x00!\x00\x01'
```

### Expected result

```
b'\x00\x00\x01\x10\x00\x01\x00\x00\x00\x00\x00\x00 CKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\x00\x00!\x00\x01'
```

**Comment by gpotter2** [comment]
As mentionned in https://datatracker.ietf.org/doc/html/rfc1002#section-4.1, the padding for Netbios names is
> space characters (0x20)

You can try the example from the RFC out using
```pycon
>>> z = NetBIOSNameField("", "")
>>> z.i2m(True, b"FRED")
b' EGFCEFEECACACACACACACACACACACA'
```

to see that this is perfectly expected.

**Comment by Neutree** [comment]
ok I got it, thanks very much

I just misunderstood the software `nbtscan`'s meant, it just send content end with `\x00`, not the protocol

![image](https://user-images.githubusercontent.com/8625829/138198027-09d3155c-b349-4572-81df-1718fd5ab2bf.png)
