### ISSUE TITLE
OSError: [Errno 92] Protocol not available

### ISSUE THREAD

**Issue by comicom** [secdev/scapy#3426]
### Brief description

in python 3.9.5, OSError: [Errno 92] Protocol not available occurs in File "/home/python-someip-event/scapy/arch/linux.py", line 186, in set_promisc
but in python 3.6.9,  It dosen't  occur

### Scapy version

3.4.5

### Python version

3.9.5

### Operating system

windriver linux lts 21

### How to reproduce

Next is someip example code in python 3.9.5
`
bash-5.1# sudo python3
Python 3.9.5 (default, Oct 20 2021, 02:04:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> 
>>> from scapy.all import *
>>> 
>>> load_contrib('automotive.someip')
>>> 
>>> offerService_ip = IP(src="127.0.0.1",dst="127.0.0.1")
>>> offerService_udp = UDP(sport=30490,dport=30490)
>>> sip = SOMEIP(srv_id=0xffff,method_id=0x8100,client_id=0x0000)
>>> 
>>> sd = SD()
>>> offer = SDEntry_Service(type=0x01,index_1=0x00,index_2=0x00,n_opt_1=0x0,n_opt_2=0x2,srv_id=27,inst_id=1,major_ver=1,ttl=16777215,minor_ver=0)
>>> stopOffer =SDEntry_Service(type=0x01,index_1=0x00,index_2=0x00,n_opt_1=0x0,n_opt_2=0x2,srv_id=27,inst_id=1,major_ver=1,ttl=0,minor_ver=0)
>>> sd_optionEP_TCP = SDOption_IP4_EndPoint(addr="127.0.0.1",l4_proto=0x06,port=10010)>>> sd_optionEP_UDP = SDOption_IP4_EndPoint(addr="127.0.0.1",l4_proto=0x11,port=10010)>>> 
>>> sd.set_entryArray(stopOffer)
>>> sd.set_optionArray([sd_optionEP_TCP,sd_optionEP_UDP])
>>> 
>>> pkt = offerService_ip/offerService_udp/sip/sd
>>> 
>>> 
>>> sendp(pkt)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python-someip-event/scapy/sendrecv.py", line 458, in sendp
    return _send(
  File "/home/python-someip-event/scapy/sendrecv.py", line 394, in _send
    socket = socket or _func(iface)(iface=iface, **kargs)
  File "/home/python-someip-event/scapy/arch/linux.py", line 501, in __init__
    set_promisc(self.ins, self.iface)
  File "/home/python-someip-event/scapy/arch/linux.py", line 186, in set_promisc
    s.setsockopt(SOL_PACKET, cmd, mreq)
OSError: [Errno 92] Protocol not available
`

Next is someip example code in python 3.6.9
`
bash-5.1# sudo python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> load_contrib('automotive.someip')
>>> 
>>> offerService_ip = IP(src="127.0.0.1",dst="127.0.0.1")
>>> offerService_udp = UDP(sport=30490,dport=30490)
>>> sip = SOMEIP(srv_id=0xffff,method_id=0x8100,client_id=0x0000)
>>> 
>>> sd = SD()
>>> offer = SDEntry_Service(type=0x01,index_1=0x00,index_2=0x00,n_opt_1=0x0,n_opt_2=0x2,srv_id=27,inst_id=1,major_ver=1,ttl=16777215,minor_ver=0)
>>> stopOffer =SDEntry_Service(type=0x01,index_1=0x00,index_2=0x00,n_opt_1=0x0,n_opt_2=0x2,srv_id=27,inst_id=1,major_ver=1,ttl=0,minor_ver=0)>>> sd_optionEP_TCP = SDOption_IP4_EndPoint(addr="127.0.0.1",l4_proto=0x06,port=10010)
>>> sd_optionEP_UDP = SDOption_IP4_EndPoint(addr="127.0.0.1",l4_proto=0x11,port=10010)
>>> 
>>> sd.set_entryArray(stopOffer)
>>> sd.set_optionArray([sd_optionEP_TCP,sd_optionEP_UDP])
>>> 
>>> pkt = offerService_ip/offerService_udp/sip/sd
>>> 
>>> send(pkt)
.
Sent 1 packets
`

Why "OSError: [Errno 92] Protocol not available message" occurs in python 3.9.5?

**Comment by gpotter2** [comment]
Sadly, it would appear that your OS is not supported :/
