### ISSUE TITLE
Cannot create attributes in Packet sub-classes

### ISSUE THREAD

**Issue by stevielavern** [secdev/scapy#343]
Since scapy-2.3.3 (and the master branch), it is no longer possible to create attributes in the Packet class:

```
from scapy.all import *
class MyPacket(Packet):
    pass

p=MyPacket()
p.test=1
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-1f7958a7f061> in <module>()
----> 1 p.test=1

/Users/user/scapy-git/scapy/packet.py in __setattr__(self, attr, val)
    219         except AttributeError:
    220             pass
--> 221         return object.__setattr__(self, attr, val)
    222
    223     def delfieldval(self, attr):

AttributeError: 'MyPacket' object has no attribute 'test'
```

This breaks a lot of existing scripts.
This seems to be because Packet's `__setattr__` directly calls `object`'s `__setattr__`, which refuses to add an non-existent attribute.
Why doesn't Packet use `super(Packet, self).__setattr__` instead?

**Comment by p-l-** [comment]
Many objects in Scapy use [slots](https://docs.python.org/2/reference/datamodel.html#slots) since #11 has been merged, to reduce the memory footprint and improve performances. You have to declare that your subclass' instances will need an extra attribute:

```Python
from scapy.all import *
class MyPacket(Packet):
    __slots__ = ["test"]

p = MyPacket()
p.test = 1
```

Can you use this for your existing scripts?

**Comment by stevielavern** [comment]
Ok, I didn't know about slots. It makes sense :).
I can indeed add the desired fields in `__slots__`, or even do `__slots__=['__dict__']` to make dynamic affectation possible.
Thanks for the quick answer!

**Comment by p-l-** [comment]
Yep, but I would not recommend dynamic affectation (as you would loose the benefits of the slots mechanism). You probably (should) have a static set of attributes you want to use.

Anyway I'm closing this issue, feel free to re-open it.

**Comment by AlexanderSpirin** [comment]
@p-l- , I have problem with suggested workaround, because it become impossible to access Ether fields. 
``` python
from scapy.all import *
class MyPacket(Ether):
    __slots__ = ["test"]

    def __init__(self, _pkt=""):
        super(MyPacket, self).__init__(_pkt)


p = MyPacket(bytes(Ether()))
p.test = 1
print(Ether in p)
print(p[Ether].dst)
```
``` pycon
False
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    print(p[Ether].dst)
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 817, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [Ether] not found
```
