### ISSUE TITLE
Inconsistent type handling when calculating ICMP packet hash

### ISSUE THREAD

**Issue by v-p-b** [secdev/scapy#3433]
### Brief description

The ICMP class sets the `seq` and `id` fields only if `type` is present in a list of acceptable values:
 
https://github.com/secdev/scapy/blob/master/scapy/layers/inet.py#L879

```py
ConditionalField(XShortField("id", 0), lambda pkt:pkt.type in [0, 8, 13, 14, 15, 16, 17, 18]),  # noqa: E501
ConditionalField(XShortField("seq", 0), lambda pkt:pkt.type in [0, 8, 13, 14, 15, 16, 17, 18]),  # noqa: E501
```

When calculating the packet hash, a different, broader set of values determines if the `id` and `seq` fields are referenced:

https://github.com/secdev/scapy/blob/master/scapy/layers/inet.py#L908

```py
    def hashret(self):
        if self.type in [0, 8, 13, 14, 15, 16, 17, 18, 33, 34, 35, 36, 37, 38]:
            return struct.pack("HH", self.id, self.seq) + self.payload.hashret()  # noqa: E501
        return self.payload.hashret()
```

This can result in conversion from `None` to integer, that results in an exception. 

### Scapy version

e28aa57033219de5690f11513b694e854bbab52a

### Python version

Came up with 2.7, should be the same on 3

### Operating system

Linux 5.4.0

### How to reproduce

```py
ans,unans=sr(IP(dst=target_ip)/ICMP(type=range(0,40),code=range(0,40)),timeout=0.5)
```

### Actual result

An exception is thrown when the hash value of ICMP packets with certain types are requested.

### Expected result

No exception is thrown on hash calculation, the presence of packet fields are determined based on the same rules in all parts of the ICMP class.

**Comment by guedou** [comment]
Nice catch!
