### ISSUE TITLE
Enum fields fail to catch invalid enum

### ISSUE THREAD

**Issue by dweidenkopf** [secdev/scapy#3439]
If an EnumField is initialized with an invalid enum value, it accepts the invalid value. I would expect it to fail. Here is a diff for the test to expose the problem.

diff --git a/test/fields.uts b/test/fields.uts
index 06381d5a..fc726e0e 100644
--- a/test/fields.uts
+++ b/test/fields.uts
@@ -944,6 +944,7 @@ assert(f.any2i_one(None, 'Foo') == 0)
 assert(f.any2i_one(None, 'Bar') == 1)
 assert(f.any2i_one(None, 2) == 2)
 expect_exception(KeyError, 'f.any2i_one(None, "Baz")')
+expect_exception(KeyError, 'f.any2i_one(None, 4)')
 
 assert(rf.any2i_one(None, 'Foo') == 0)
 assert(rf.any2i_one(None, 'Bar') == 1)

**Comment by gpotter2** [comment]
An enum field can take both an integer value or its string representation.
This is not an issue

**Comment by dweidenkopf** [comment]
That is surprising behavior for an Enum. I understand changing that behavior might break code. Is there another class that I should use to enforce a numerical value in a field?

**Comment by gpotter2** [comment]
No because Scapy's mindset is to allow you to input *any* value, even if invalid. Enums display a "nice" display name but that stops there.

**Comment by dweidenkopf** [comment]
Ok, thanks.
