### ISSUE TITLE
Route w/o metric causes: ValueError: not enough values to unpack (expected 6, got 5)

### ISSUE THREAD

**Issue by darless** [secdev/scapy#3450]
https://github.com/secdev/scapy/blob/8a94cc421bc1355c15b91b4169e2011b6c256a63/scapy/route.py#L178

There was a route in `self.routes` which only had 5 entries instead of 6.

Example of a normal route seen by scapy:
```
(3221291520, 4294967040, '0.0.0.0', 'enp9s4', '1.2.3.4', 0)
```

Failed route seen by scapy which caused the failure.
```
(0, 0, '1.2.3.1', 'enp9s4, '1.2.3.4') 
```

```
>>> scapy.VERSION
'2.4.4'
```

The failed route only has 5 entries instead of 6. The code in question does not do any validation on the routes. 
In the route above, the metric is not in place.

Workaround for me:
```diff
diff --git a/route.py b/route.py
index ce2343b..beb4454 100644
--- a/route.py
+++ b/route.py
@@ -125,6 +125,16 @@ class Route:
         the_net = the_rawaddr & the_msk
         self.routes.append((the_net, the_msk, '0.0.0.0', iff, the_addr, 1))
 
+    def fix_routes(self):
+      for ix in range(len(self.routes)):
+        route = self.routes[ix]
+        if len(route) == 5:
+          print(f"ERROR: Route {route} is invalid")
+          new_route = list(route)
+          # Add a metric that we have seen can be missing
+          new_route.append(0)
+          self.routes[ix] = tuple(new_route)
+
     def route(self, dst=None, verbose=conf.verb):
         """Returns the IPv4 routes to a host.
         parameters:
@@ -135,6 +145,7 @@ class Route:
          - output_ip: the outgoing IP that will be used
          - gateway_ip: the gateway IP that will be used
         """
+        self.fix_routes()
         dst = dst or "0.0.0.0"  # Enable route(None) to return default route
         if isinstance(dst, bytes):
             try:
```

Ideally, this would not be needed if any route that was added would use the add function and not call routes. append itself. That is all throughout the codebase which seems error-prone.

**Comment by guedou** [comment]
How does this entry ended up in `self.routes`? The `add()` and `make_route()` methods are designed to add new entries.

**Comment by darless** [comment]
Closing this as the issue was in  helper script that was being used with scapy and not scapy itself.
