### ISSUE TITLE
If iface is set to None in Trunk mode, can't listen on all nics?

### ISSUE THREAD

**Issue by janus1345** [secdev/scapy#3458]
### Network adapter configuration：
* vmbr0 Connects to the trunk port of the switch

     ```
   auto vmbr0.10                                                                                            
     iface vmbr0.10 inet static                                                                                  
          address 192.168.192.3/18                                                                                  
          gateway 192.168.192.1                                                                                
          vlan-raw-device vmbr0  
    
    atuo vmbr101
    iface vmbr101 inet static
        address 10.10.1.10/21
        bridge-ports none
        bridge-stp off
        bridge-fd 0
        bridge-vlan-aware yes
        bridge-vids 2-4094
    ```
iface=None cannot listen to vmbr101 nic data

### Scapy version

2.4.5

### Python version

2.7

### Operating system

Linux pve 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64 x86_64 x86_64 GNU/Linux

### How to reproduce

`sniff(iface=None, prn=lambda pkt: pkt.summary(), filter="net 192.168.192.3/32")
`
ping -I vmbr101 192.168.192.3

### Actual result

There is no output but tcpdump can listen

### Expected result

```
ping -I vmbr0.10 10.10.1.10


In [20]: sniff(iface=None, prn=lambda pkt: pkt.summary(), filter="net 10.10.1.10/32")


Ether / ARP who has 10.10.1.10 says 192.168.192.3
Ether / ARP who has 10.10.1.10 says 192.168.192.3
Ether / ARP who has 10.10.1.10 says 192.168.192.3
Ether / ARP who has 10.10.1.10 says 192.168.192.3
Ether / ARP who has 10.10.1.10 says 192.168.192.3
Ether / ARP who has 10.10.1.10 says 192.168.192.3
```

**Comment by gpotter2** [comment]
`iface=None` selects `conf.iface` by default. Probably not what you want
You should specify all the interfaces you want to sniff on, there isn't a "native" way to say "sniff on everything" although you can do

`sniff(iface=get_if_list())`

**Comment by Miao-jh** [comment]
> `iface=None` selects `conf.iface` by default. Probably not what you want You should specify all the interfaces you want to sniff on, there isn't a "native" way to say "sniff on everything" although you can do
> 
> `sniff(iface=get_if_list())`

it's not work for me and raise AttributeError: 'list' object has no attribute 'encode'.
system: windows 10 64bit
python version: 3.6 64bit
scapy version: 2.4.5
