### ISSUE TITLE
Hexdump issues with byte aligned packet

### ISSUE THREAD

**Issue by urbrex** [secdev/scapy#3466]
I am working on project that uses scapy to dissect packets containing custom protocol
We would need to dissect list of records, that are not byte aligned and we are getting following error when we try to hexdump packet with one record:

TypeError: can only concatenate tuple (not "bytes") to tuple

Our packet looks like this:
fields_desc = [
        ShortField("LinkInstanceId", 0),
        BitEnumField("linkStatus", 0, 3, PREFERENCES_LINK_STATUS),
        BitField("sameFlag", 0, 1),
]

Same error as above happens when we try to duplicate fields (then packet is byte aligned - total length 40 bit). Packet after field duplication looks like this:

    fields_desc = [
        ShortField("LinkInstanceId", 0),
        BitEnumField("linkStatus", 0, 3, PREFERENCES_LINK_STATUS),
        BitField("sameFlag", 0, 1),
        ShortField("LinkInstanceId2", 0),
        BitEnumField("linkStatus2", 0, 3, PREFERENCES_LINK_STATUS),
        BitField("sameFlag2", 0, 1),
    ]

However when we add manual padding to packet and align it to 24 or 40 bit, error does not happen. 
    fields_desc = [
        ShortField("LinkInstanceId", 0),
        BitEnumField("linkStatus", 0, 3, PREFERENCES_LINK_STATUS),
        BitField("sameFlag", 0, 1),
        BitField("padding", 0, 4),

**Comment by guedou** [comment]
That is expected. Scapy does not work with fields that are not bytes aligned, except when using successive BitField that ends up being byte-aligned.

**Comment by urbrex** [comment]
Thank you for quick reply. In our protocol there can be arbitrary number of these preference packets in succession. In case of uneven number of preferences last packet is padded with 0. Is it possible to interpret these kind of packets in scapy then?
```
class BasicPreferences(Packet):
    """Packet specification

    Examples:
     0                   1                   2                   3
     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |         LinkInstanceId        | lin.|S|
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

    """

    name = "Basic Preferences Record"
    fields_desc = [
        ShortField("LinkInstanceId", 0),
        BitEnumField("linkStatus", 0, 3, PREFERENCES_LINK_STATUS),
        BitField("sameFlag", 0, 1)
    ]

```

**Comment by guedou** [comment]
If preferences follow each other leading on a non byte alignment, Scapy cannot deal with them automatically, an you will have to code the encoding/decoding yourself.

If the padding happens after each preference, Scapy will work fine.
