### ISSUE TITLE
Scapy doesn't find the correct interface when sending from Linux NetNS

### ISSUE THREAD

**Issue by nabaco** [secdev/scapy#3467]
### Brief description

This is a follow up ticket from https://github.com/larsks/python-netns/issues/4.
When trying to send traffic, by switching network namespace programmatically with `netns` package, I get the following error: `OSError: [Errno 19] No such device`.

Quoting @larsks - https://github.com/larsks/python-netns/issues/4#issuecomment-983997350:
> it looks like some scapy variables are initialized probably when you import scapy, so even though your function call is running inside the appropriate network namespace, scapy "knows" about interfaces in the global namespace. Even when passing iface="myinterface", when scapy tries to send a packet it determines the outbound interface in https://github.com/secdev/scapy/blob/master/scapy/arch/linux.py#L605, where it seems to refer to interfaces in the global namespace.

### Scapy version

2.4.5

### Python version

3.8.10

### Operating system

Ubuntu 20.04.3 LTS - Linux Kernel 5.4.0-90-generic

### Additional environment information

The namespace contains one interface `ens256` and `lo`, both are up. `ens256` is provisioned through DHCP. Routing is present, and regular ping works (e.g. `sudo ip netns exec red ping 192.168.0.1`).
Running the following code from within the netns (e.g. `sudo ip netns exec red ./ping.py 192.168.0.1`) also works:
```py
#!/usr/bin/env python3
from scapy.all import sr1,IP,ICMP,send
import sys

p=sr1(IP(dst=sys.argv[1])/ICMP())
if p:
    p.show()
```

### How to reproduce

Create a namespace:
```sh
sudo ip netns add red
sudo ip link set netns red dev ens256
sudo ip netns exec red ip link set lo up
sudo ip netns exec red ip link set ens256 up
sudo ip netns exec red dhclient ens256
```

Run the following code with sudo:
```py
#!/usr/bin/env python3
import netns
from scapy.all import sr1,IP,ICMP,send
import sys

with netns.NetNS(nsname="red"):
    p=sr1(IP(dst=sys.argv[1])/ICMP())
    if p:
        p.show()
```

### Actual result

```sh
Traceback (most recent call last):
  File "./ping.py", line 16, in <module>
    p=sr1(IP(dst=sys.argv[1])/ICMP())
  File "/usr/local/lib/python3.8/dist-packages/scapy/sendrecv.py", line 648, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 501, in __init__
    set_promisc(self.ins, self.iface)
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 181, in set_promisc
    mreq = struct.pack("IHH8s", get_if_index(iff), PACKET_MR_PROMISC, 0, b"")
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/linux.py", line 401, in get_if_index
    return int(struct.unpack("I", get_if(iff, SIOCGIFINDEX)[16:20])[0])
  File "/usr/local/lib/python3.8/dist-packages/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
OSError: [Errno 19] No such device
```

### Expected result

```sh
Begin emission:
Finished sending 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets
###[ IP ]###
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 28
  id        = 63529
  flags     =
  frag      = 0
  ttl       = 64
  proto     = icmp
  chksum    = 0x11f
  src       = 192.168.0.1
  dst       = 192.168.0.71
  \options   \
###[ ICMP ]###
     type      = echo-reply
     code      = 0
     chksum    = 0xffff
     id        = 0x0
     seq       = 0x0
     unused    = ''
###[ Padding ]###
        load      = '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by guedou** [comment]
Can you try to remove the first Scapy import, and do this instead:
```
with netns.NetNS(nsname="red"):
   from scapy.all import *
```

**Comment by gpotter2** [comment]
It might be worth to also try something like
```python
from scapy.config import conf

with netns.NetNS(nsname="red"):
    conf.ifaces.reload()  # Reload interface list
    conf.route.resync()  # Reload IPv4 routes
    [...]
```

**Comment by nabaco** [comment]
> Can you try to remove the first Scapy import, and do this instead:
>
> ```py
>    with netns.NetNS(nsname="red"):
>       from scapy.all import *
>        p=sr1(IP(dst=sys.argv[1])/ICMP())
>        if p:
>            p.show()
> ```


I tried that and it works. But feels somewhat hacky, especially if I'll want to repeat the action in different namespaces.

> It might be worth to also try something like
>
> ```py
> from scapy.config import conf
> 
> with netns.NetNS(nsname="red"):
>    conf.ifaces.reload()  # Reload interface list
>    conf.route.resync()  # Reload IPv4 routes
>    [...]
> ```

This works good, thank you! I'll use it for now.
Given Scapy's design, I would suggest a small change:
Upon import, remember in which namespace we're located. Before sending the actual traffic, re-check the namespace, and if it changed, run the above commands.
Feel free to close the ticket.

**Comment by gpotter2** [comment]
I would mark this as `wontfix` assuming the above workaround is acceptable. We can't reasonably re-check all interfaces & routes on each IO action. (wireshark doesn't for instance)

@guedou Your call

**Comment by guedou** [comment]
@gpotter2 I agree. That is something that Scapy cannot check efficiently
without killing the performances.
