### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by flokli** [secdev/scapy#347]
Hey,

are there any plans to bring [secdev/scapy](https://github.com/secdev/scapy) and [phaethon/scapy](https://github.com/phaethon/scapy) back together, into a lib that supports both python versions?

I'd like to contribute (most of my code is running on python3 though). What about having tests for both python versions and slowly bringing dual compatibility in?

I dislike the idea of contributing to two slowly diverging projects…

/cc @phaethon

**Comment by phaethon** [comment]
First, we would need to come up with an idea how to make it feasible - e.g. how to overcome differences in str and bytes between python2 and python3 in a way that is friendly to a user/programmer. Second, we would need core maintainers of secdev/scapy to recognize existence of phaethon/scapy and its python3 compatibility. Putting a single link somewhere would be a good start. Does not sound to happen any-time soon unfortunately.

**Comment by p-l-** [comment]
We have no short-term plan to bring Python 3 compatibility, even though recent Python 2.{5,6} support drop would make it easier.

As you mentioned, the projects are diverging and the work to merge them would be huge.
