### ISSUE TITLE
Ether layer ignores when sending SYN packet.

### ISSUE THREAD

**Issue by vodkar** [secdev/scapy#3472]
### Brief description

When I try to scan my local machine ports (using ip/tcp components for SYN scan) and set Ethernet mac destination simultaneously, packet is formed not right.
Looks like, it's ignoring Ether layer.

### Scapy version

2.4.5

### Python version

3.10.0

### Operating system

Linux 5.13.19-2-MANJARO

### Additional environment information

I'd made some debug and find out following code:

https://github.com/secdev/scapy/blob/90c255d255eb6c4ea074eecece654fc9b515ad3a/scapy/arch/linux.py#L615-L621

`ll(x)` call returns: `<Ether  type=IPv4 |<IP  flags=DF frag=0 proto=tcp dst=192.168.221.128 |<TCP  sport=13199 dport=ipps flags=S |<Ether  dst=00:00:00:00:00:00 |>>>>`
But `x` was `<IP  flags=DF frag=0 proto=tcp dst=192.168.221.128 |<TCP  sport=<RandShort> dport=ipps flags=S  |<Ether  dst=00:00:00:00:00:00 |>>>`

It's stack new `Ether` layer over old.

### How to reproduce

```
sport = RandShort()
sr1(
    IP(dst="192.168.221.128", flags=2) # ip address of local machine
    / TCP(
        sport=sport,
        dport=631,
        flags="S",
    )
    / Ether(dst="00:00:00:00:00:00"),
    timeout=2,
    verbose=0,
)

```

### Actual result

Wireshark dump:
![Wireshark dump](https://user-images.githubusercontent.com/28678409/144586553-c2bbe70a-546a-4db3-b735-a00482869444.png)

### Expected result

If I avoid `ll(x)` calling, then I receive this result:
![изображение](https://user-images.githubusercontent.com/28678409/144587344-8490ee69-cd96-49cc-aa66-d2514bb6a926.png)

**Comment by guedou** [comment]
Please ask your question on gitter. It looks like you are not using Scapy correctly: Ether is below IP.
