### ISSUE TITLE
Licensing of ldp.py

### ISSUE THREAD

**Issue by hyandell** [secdev/scapy#3478]
Hi Scapy folk,

I wanted to note that scapy/contrib/ldp.py is licensed under the GPL-3.0 rather than GPL-2.0 as with the rest of the project. This felt a little unusual given the care that's shown on licensing (for example this earlier issue #3165). I know it's in contrib/, but I'm wondering if relicensing is possible or perhaps if the file could be omitted in the PyPI release.

**Comment by gpotter2** [comment]
Thanks for the report, this was not forgotten.

@fduraffourg @phil777  Hi there, sorry for bothering. Would you mind if we re-licensed this file to GPL 2? Thanks a lot !

**Comment by fduraffourg** [comment]
> Thanks for the report, this was not forgotten.
> 
> @fduraffourg @phil777 Hi there, sorry for bothering. Would you mind if we re-licensed this file under GPL 2+? Thanks a lot !

Hey! I'm OK with the re-licensing.

**Comment by gpotter2** [comment]
Thanks a lot for the quick answer !
