### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by gladman88** [secdev/scapy#3482]
### Brief description

Hello! 
I have problem with CPU load with scapy. Doesn't matter which filter I set up, scapy always use 12.5 percent of CPU when sniffing. I have intel core i7.

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Windows 10

### How to reproduce

Hello! 
I have problem with CPU load with scapy. Doesn't matter which filter I set up, scapy always use 12.5 percent of CPU when sniffing. I have intel core i7. 
Even if i didn't get any packets at all - 12,5% of CPU usage. Why it's happening?

for example:
```
sniff_filter = "tcp[tcpflags] & (tcp-syn|tcp-fin) != 0 and dst port 443"
sniff(filter=sniff_filter, prn=self._packet_callback, store=0)
```

or even:
sniff_filter = "dst port 2"
No any packets, nut CPU load 12,5% by python process.

**Comment by polybassa** [comment]
Hi, thanks for your message.

I might be wrong here, but I highly assume this behavior is caused by windows not having a select. AFAIK, sniff has to constantly look for new packets. Therefore you end up with one core 100% utilized.

To double check if this is not a new issue, do older versions of scapy behave different?

**Comment by gladman88** [comment]
> Hi, thanks for your message. I might be wrong here, but I highly assume this behavior is caused by windows not having a select. AFAIK, sniff has to constantly look for new packets. Therefore you end up with one core 100% utilized. To double check if this is not a new issue, do older versions of scapy behave different?

Which one you can recommend? 2.4.3? Or older?

**Comment by gladman88** [comment]
Problem resolved!

scapy version 2.4.4. CPU Usage almost 0 now.

Thanks to **polybassa**

**Comment by polybassa** [comment]
Ok, thanks for your feedback. So this is a valid issue, then.

**Comment by polybassa** [comment]
Could you please double check on the latest version in GitHub? So that we know if this issue is present in the current development version.

**Comment by gladman88** [comment]
>Successfully installed scapy-2.4.5rc1.dev162
Problem still there

**Comment by polybassa** [comment]
Thanks!
--

**Comment by guedou** [comment]
@gladman88 do you feel like tracking the commits that introduce the issue?

You could do it using `git bisect`(see https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git).

In a nutshell, it involves:
- calling `git bisect bad` on the current HEAD commit
- calling `git bisect good v2.4.4`
- launching your script and identify CPU usage. If OK, type `git bisect good`, if not `git bisect bad`
- start again, until git is happy, then share the commit id.

**Comment by nadaverez** [comment]
@guedou also encountered the issue, after checking the commit is `880d0487c6885a5ddd0c5f747f6a9e0461a35278`

**Comment by gpotter2** [comment]
Could y'all retry with master? Thanks !
