### ISSUE TITLE
PPP Header missing a byte in v2.4.5 (Compared to v2.4.0)

### ISSUE THREAD

**Issue by adiel91** [secdev/scapy#3484]
### Brief description

Hi All,
We encountered the following difference between PPP Header used in our environment -

**Scapy 2.4.0:**
```
>>> PPP().build()
'\x00!'
```

**Scapy 2.4.5:**
```
>>> PPP().build()
b'!'
```

As you can see - the PPP Header built with 2.4.5 is missing \x00 byte.

From looking at PPP Implementation, we see the following diff is what causes the diff above:
**Scapy 2.4.0:scapy/layers/ppp.py:208**
```fields_desc = [ ShortEnumField("proto", 0x0021, _PPP_proto) ]```

**Scapy 2.4.5:scapy/layers/ppp.py:323**
```fields_desc = [_PPPProtoField("proto", 0x0021, _PPP_PROTOCOLS)]```

Is that a bug in 2.4.5 version? Or actually in 2.4.0? 
Or is there any other reason for this behavior change?
Tagging change owner: @gpotter2 

Appreciate your input and/or answers
Thanks!

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Linux (Any)

### How to reproduce

PPP().build()
using scapy 2.4.5, same when using scapy 2.4.0

**Comment by gpotter2** [comment]
The first field of `PPP` can be of length 1 or 2, according to the spec.
There used to be a `PPP` class and a `PPP_` class to account for this difference, this was merged in https://github.com/secdev/scapy/commit/834309f91c1d51eaaae481fa45faebcf6803cd09

This is an expected behavior

**Comment by adiel91** [comment]
> The first field of `PPP` can be of length 1 or 2, depending on the parity of its value, according to the spec. There used to be a `PPP` class and a `PPP_` class to account for this difference, but this got simplified in [834309f](https://github.com/secdev/scapy/commit/834309f91c1d51eaaae481fa45faebcf6803cd09)
> 
> This is an expected behavior

Thanks @gpotter2  for your answer.
Where can I find information about "parity of its value"? I've checked RFC https://datatracker.ietf.org/doc/html/rfc1661 and couldn't find any reference to parity of the value.

**Comment by gpotter2** [comment]
sect 2

> The structure of this field is consistent with the ISO 3309
      extension mechanism for address fields.  All Protocols MUST be
      odd; the least significant bit of the least significant octet MUST
      equal "1".  Also, all Protocols MUST be assigned such that the
      least significant bit of the most significant octet equals "0".
      Frames received which don't comply with these rules MUST be
      treated as having an unrecognized Protocol.

**Comment by adiel91** [comment]
> sect 2
> 
> > The structure of this field is consistent with the ISO 3309
> > extension mechanism for address fields.  All Protocols MUST be
> > odd; the least significant bit of the least significant octet MUST
> > equal "1".  Also, all Protocols MUST be assigned such that the
> > least significant bit of the most significant octet equals "0".
> > Frames received which don't comply with these rules MUST be
> > treated as having an unrecognized Protocol.

Thanks for the swift response!
