### ISSUE TITLE
Wrong RadioTap.ChannelFrequency

### ISSUE THREAD

**Issue by s0i37** [secdev/scapy#3486]
### Brief description

Scapy detect illegal frequency channel on wifi monitor. In this case should 2ch but 1ch.

`sniff(iface='wlan0mon', lfilter=lambda p:p.haslayer(Dot11Beacon) and p[Dot11Elt].info==TestEssid',prn=lambda p:p[RadioTap].ChannelFrequency)`
2412
2412
2412
2412

`airodump-ng`
BSSID              PWR RXQ  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID
00:11:22:33:44:55  -60   0       65        0    0   2  130  WPA2 CCMP   PSK  TestEssid

### Scapy version

2.4.5

### Python version

3.9.2

### Operating system

Kali GNU/Linux Rolling x64 / 5.4.8-rt3

### How to reproduce

sniff(iface='wlan0mon', lfilter=lambda p:p.haslayer(Dot11Beacon) and p[Dot11Elt].info==b'TestEssid',prn=lambda p:p[RadioTap].ChannelFrequency)
airodump-ng wlan0mon -c 1

**Comment by gpotter2** [comment]
Hi, what's the issue?

**Comment by s0i37** [comment]
Scapy incorrect define channel num.
It should 2ch instead of 1ch in my example.

**Comment by gpotter2** [comment]
What does "It should 2ch" mean? You are missing a verb

**Comment by s0i37** [comment]
I expected capture 2nd channel number in `p[RadioTap].ChannelFrequency` but it captured as 1st channel.

**Comment by gpotter2** [comment]
Why would you expect that? Did you configure your network card properly? Aren't you also asking for the first channel with `-c 1` ?

**Comment by s0i37** [comment]
I run `airodump-ng wlan1 -c 1` on fixed channel (1st channel in this example).
If I listen some channel I can hear packets from 2-4 neighbors channel (2nd channel for this problem).

**Comment by gpotter2** [comment]
This is called channel overlap.
![](https://upload.wikimedia.org/wikipedia/commons/8/8c/2.4_GHz_Wi-Fi_channels_%28802.11b%2Cg_WLAN%29.svg)

**Comment by s0i37** [comment]
I know this.
But why scapy can't determine channel right? Airodump-NG can it.

**Comment by gpotter2** [comment]
Yes it can just read `ChannelFrequency`

**Comment by s0i37** [comment]
Hence there is no way to filter overlapped AP?

**Comment by gpotter2** [comment]
Of course you can, just use a filter in your sniff.

**Comment by s0i37** [comment]
you mean `sniff(filter/lfilter)` ?

**Comment by gpotter2** [comment]
yes

**Comment by s0i37** [comment]
The right answer is 
`p[Dot11EltDSSSet].channel`
It seems that this is exactly how the airodump-ng determines the correct channel when overlapping.
