### ISSUE TITLE
Error in UDP checksum calculation

### ISSUE THREAD

**Issue by ihavequestions** [secdev/scapy#350]
I used version 2.3.2, so this might be fixed already.

I read packets from a pcap file and recalculated their checksums by calling
```
packet = packet.__class__(str(packet))
```
The RFC for UDP(v4) states that if a checksum is calculated as zero, it should be set to 0xffff instead, since 0 indicates that the (optional) checksum is not used. Since this was not implemented in scapy, I had to add
```
if packet[UDP].chksum == 0:
  packet[UDP].chksum = 0xffff
```
to my script.

Source: [RFC 768](https://www.ietf.org/rfc/rfc768.txt)
> If the computed  checksum  is zero,  it is transmitted  as all ones (the
equivalent  in one's complement  arithmetic).   An all zero  transmitted
checksum  value means that the transmitter  generated  no checksum  (for
debugging or for higher level protocols that don't care).

**Comment by guedou** [comment]
Thanks for reporting this issue. Does PR#364 work for you ?

**Comment by ihavequestions** [comment]
Yes, thank you!
