### ISSUE TITLE
vendored six module raises ImportWarning with Python 3.10 and 3.11a3

### ISSUE THREAD

**Issue by grayjk** [secdev/scapy#3502]
### Brief description

In Python 3.10 and 3.11a3, importing from scapy raises an ImportWarning:
```
$ python3.11 -W default
Python 3.11.0a3 (main, Jan  6 2022, 09:16:02) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy import base_classes
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:673: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
```

The version of six (scapy/modules/six.py) in scapy is 1.10.0 which is missing implementations of find_spec and exec_module.

The fall back methods were deprecated beginning in Python 3.10: https://docs.python.org/3.10/whatsnew/3.10.html#deprecated

six version 1.16.0 includes the missing methods.

### Scapy version

2.4.5

### Python version

3.11a3

### Operating system

Ubuntu 18.04

### How to reproduce

```
$ python3.11 -W default
Python 3.11.0a3 (main, Jan  6 2022, 09:16:02) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy import base_classes
<frozen importlib._bootstrap>:1049: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:673: ImportWarning: _SixMetaPathImporter.exec_module() not found; falling back to load_module()
```

**Comment by David-OConnor** [comment]
Same; python 3.10.1.

**Comment by yuanxpy** [comment]
but i use python 3.10.1；six 1.16.0，also have the warnings……

**Comment by p-l-** [comment]
For the record, Scapy no longer ships (or use) the `six` module. @wuzue this is Scapy repository, I don't think you project uses it.

**Comment by PabloCastellano** [comment]
I found this nice blog post explaining the root of this mysterious issue https://blog.pecar.me/six-warnings
