### ISSUE TITLE
Enhancement: faster startup times by skipping route and interface discovery

### ISSUE THREAD

**Issue by Lekensteyn** [secdev/scapy#3504]
I would like to build a script to visualize some raw bytes using one of the parsers in Scapy and do not need any send/recv functionality. However, simply importing that layer results in a significant slowdown. This slowdown has been reported before in #2327, #2133, and perhaps some others.

```
$ time python3 -c 'from scapy.layers.tls.record import TLS'
WARNING: No IPv4 address found on en5 !
WARNING: No IPv4 address found on ap1 !
WARNING: more No IPv4 address found on en3 !

real	0m1.436s
user	0m0.666s
sys	0m0.763s
```

## Potential solutions

- Expose an option to disable/defer loading of interface info. For example, an environment variable, a `scapy.config.conf` option, etc.
- Defer loading interface info until send/recv actually needs it.
- ...

## Workaround
As a workaround, I tried to patch the library to prevent the slow code from being executed. An initial attempt failed, but has a stacktrace with the affected code:

```
$ time python3 -c 'from scapy.config import conf; conf.route="dummy to disable init"; print("food"); from scapy.layers.tls.record import TLS'
food
WARNING: No IPv4 address found on en5 !
WARNING: No IPv4 address found on ap1 !
WARNING: more No IPv4 address found on en3 !
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy/layers/tls/record.py", line 25, in <module>
    from scapy.layers.inet import TCP
  File "scapy/layers/inet.py", line 26, in <module>
    from scapy.layers.l2 import Ether, Dot3, getmacbyip, CookedLinux, GRE, SNAP, \
  File "scapy/layers/l2.py", line 18, in <module>
    from scapy.arch import get_if_addr, get_if_hwaddr
  File "scapy/arch/__init__.py", line 131, in <module>
    conf.use_bpf = True
  File "scapy/config.py", line 117, in __set__
    val = self.hook(self.name, val, old, *self.args, **self.kargs)
  File "scapy/config.py", line 658, in _socket_changer
    _set_conf_sockets()
  File "scapy/config.py", line 616, in _set_conf_sockets
    conf.ifaces.reload()
  File "scapy/interfaces.py", line 240, in reload
    self.load_confiface()
  File "scapy/interfaces.py", line 228, in load_confiface
    conf.iface = get_working_if()
  File "scapy/interfaces.py", line 358, in get_working_if
    routes = conf.route.routes[:]
AttributeError: 'str' object has no attribute 'routes'
```

Another attempt was somewhat successful, but it relies on private internals:
```
$ time python3 -c 'from scapy import config; config.conf.route = "dummy"; config._set_conf_sockets = lambda: 0; from scapy.layers.tls.record import TLS'

real	0m0.478s
user	0m0.346s
sys	0m0.125s
```

## Environment
* scapy git master, commit 65089071da1acf54622df0b4fa7fc7673d47d3cd
* Python 3.9.9
* OS: macOS 12.1
* Hardware: MacBook Pro (15-inch, 2019), 2.6 GHz 6-Core Intel Core i7

**Comment by gpotter2** [comment]
A proper workaround woule be to simply start Scapy in a [ip namespace](https://man7.org/linux/man-pages/man8/ip-netns.8.html), this way you can precisely control what it has access to on boot.

I don't really think that there should be a way of disabling routes loading. It IS the expected behavior to load and process all routes it has access to. Sure it would be nice if it were Faster, which we're keeping in the back of our minds, but feel free to provide a PR.

**Comment by gpotter2** [comment]
Lets continue this topic in https://github.com/secdev/scapy/issues/3423 if you want
