### ISSUE TITLE
scapy in windows xp is broken

### ISSUE THREAD

**Issue by badrelmers** [secdev/scapy#3509]
### Brief description

scapy in windows xp is broken in python3.4 while python2.7 works fine.
after installing scapy with pip in python 3.4, I run scapy and it return 1700 line of errors. 
I tested all scapy versions from 2.3.3 to 2.4.5 they are all broken in xp in python 3.4. is there a solution? 
scapy 2.4.5 works fine in python 3.4 in windows 7!

### Scapy version

2.4.5

### Python version

3.4

### Operating system

Windows XP

### How to reproduce

in windows xp, install python 3.4 ,install WinPcap_4_1_3
install scapy with:
```
pip install --upgrade git+git://github.com/secdev/scapy
```
or
``` 
pip install scapy
```
run  scapy

### Actual result

I attached here the errors printed in my console.
[scapy_lastDev.txt](https://github.com/secdev/scapy/files/7913938/scapy_lastDev.txt)

**Comment by gpotter2** [comment]
Sorry we stopped providing support for Windows XP. Feel free to provide a patch but you'll have to debug it yourself
