### ISSUE TITLE
IPv6 routes are not added to conf.route6 unless they follow RFC-defined networks

### ISSUE THREAD

**Issue by joey-dube** [secdev/scapy#3519]
### Brief description

scapy.arch.read_routes6() will not add IPv6 routes into conf.route6 unless they follow RFC defined networks.
The function defining those RFC routes is scapy.utils6.construct_source_candidate_set().
This behaviour drops important IPv6 routes I have on my host.

### Scapy version

2.4.5

### Python version

3.9.7

### Operating system

Ubuntu 20.04

### Additional environment information

- Host A is a client with Scapy (IPv6: fe00::2/80)
- Host B is a DNS server (IPv6: fe00::100/80)

Host A has a default gateway of fe00::1 (but I turned off the fe00::1 device)

### How to reproduce

- Host A is a client with Scapy (IPv6: fe00::2/80), default gateway of fe00::1
- Host B is a host (IPv6: fe00::100/80)

Start interactive Scapy on Host A
`getmacbyip6("fe00::100")` Returns nothing

### Actual result

Nothing

### Expected result

The mac address of fe00::100

### Related resources

The ICMPv6 NDP packets are sent to fe00::1 even if the subnet is the same for both Host A and Host B. This is because conf.route6 lists fe00::1 as the proper route instead of ::

scapy.arch.read_routes6() uses scapy.utils6.construct_source_candidate_set() when reading the host's IPv6 routes on Linux.

Construct_source_candidate_set() then check if the IP found in the route fits some RFC-defined subnets and drops any mismatch (in my case, fe00::/80 is dropped, while the hosts has a route to it set as: `::`).
It only allows:

- 2000::/3
- fc00::/7
- fe80::/10
- ff01::/16
- ff0e::/16
- ff02::/16
- ff05::/16
- ::

**Comment by guedou** [comment]
This behavior is based on https://datatracker.ietf.org/doc/html/rfc6724 We need to follow it.

Your use case is specific, and you should add this prefix manually: 
`conf.route6.routes.append(('fe00::', 64, 'fe80::ff67:414f:3b8a:d2c4', 'eth0', ['fe80::ff67:414f:3b8a:d2c4'], 1))`

Here `fe80::ff67:414f:3b8a:d2c4` is your interface link-local address.
