### ISSUE TITLE
Certificate manipulation tools disabled

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#354]
Certificate manipulation tools are all disabled when the ecda Python module is not installed. This is not the expected behavior. Some tools still need to work.

The error message is the following:
```shell
$ ./run_scapy
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
```

Invoking @mtury !

**Comment by mtury** [comment]
The latest commit in PR #294 should fix this!

**Comment by gpotter2** [comment]
Sidenote, Now located at https://github.com/secdev/scapy/issues/354

**Comment by mtury** [comment]
This issue can be closed now.
