### ISSUE TITLE
checksum changed within the same scapy version (2.4.5)

### ISSUE THREAD

**Issue by fcolista** [secdev/scapy#3540]
### Brief description

Hi.
I'm the maintainer of scapy package for [Alpine Linux](https://git.alpinelinux.org/aports/tree/community/scapy/APKBUILD)

I noticed that the sha512sum of the tar.gz (https://github.com/secdev/scapy/archive/v2.4.5.tar.gz), that in automated computed and checked when the package is built, has changed for an already tagged version.

I don't know if this was intentional or not, but please, versions released should keep the checksum, in order to be sure, downstream, that the package is not changed, or corrupted.

Thanks.

.: Francesco

### Scapy version

2.4.5

### Python version

3.10

### Operating system

Alpine Linux 

### How to reproduce

```
$ wget https://github.com/secdev/scapy/archive/v2.4.5.tar.gz
$ sha512sum v2.4.5.tar.gz
```

### Actual result

```
1cf36bb256e72e55b6524c37dea68da103dc6050af56e57aa9beeb521583537aeb9fbe1b8eae0629a6f2d381f368c
5b8f5b45dd9e285277477e0dd168ce55325
```

### Expected result

```
b5ccd689f7bd4fbbb86921a35360b94ec7a738b494f16e4764828689835296016bc476825add798406e4d32761d8df90b41ce7e38049afdabf98397b1bf5982a
```

### Related resources

[Downstream package logs](https://git.alpinelinux.org/aports/log/?qt=grep&q=scapy)

https://git.alpinelinux.org/aports/commit/?id=f9494ed508a14443aacde31e026ec7801009bd6c

Here you see that the upgrade of Scapy package has been done on April 20th, 2021.

**Comment by guedou** [comment]
My question might sound dumb but are you sure that it worked with the previous hash (b5ccd689f7bd4fbbb86921a35360b94ec7a738b494f16e4764828689835296016bc476825add798406e4d32761d8df90b41ce7e38049afdabf98397b1bf5982a) ?

**Comment by guedou** [comment]
It seems that this is a recurring issue with github https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745. Scapy maintainers are not managing these files =/

**Comment by guedou** [comment]
We did not modify anything on our side. More important, we don't silently modify a release.

For example https://github.com/secdev/scapy/releases/tag/v2.4.1 was tagger but never meant to be used. If I recall correctly, I was broken and immediately replaced with https://github.com/secdev/scapy/releases/tag/v2.42

**Comment by blshkv** [comment]
oh wow, it took you 3 years and 3 bug reports to fixed finally, see:
https://github.com/secdev/scapy/issues/1520
https://github.com/secdev/scapy/issues/3121

Don't mess it up again.

**Comment by gpotter2** [comment]
Yeah sorry for the delay. To be fair with us the `%(describe)` option didn't exist in git at the time of the first issue :/
Thanks for your patience 😅
