### ISSUE TITLE
Error "ModuleNotFoundError: No module named 'scapy'" appears when starting scapy with sudo

### ISSUE THREAD

**Issue by Propland** [secdev/scapy#3545]
### Brief description

Hello together, when I try to start scapy with sudo the Output is:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/scapy", line 5, in <module>
    from scapy.main import interact
ModuleNotFoundError: No module named 'scapy'

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Ubuntu 20.04.4 LTS

### How to reproduce

Hello together,

first of all, Scapy starts normally. I can start Scapy with "scapy -H" or "/home/ubuntu/.local/bin/scapy" (I found out the path with "which scapy" or "which scapy -H (later you see I had to) ("which scapy" and "which scapy -H" give the same result)).
Then scapy starts it says "INFO: PyX dependencies are not installed ! Please install TexLive or MikTeX.", but I don't think that is relevant here.

But I think I need to start Scapy with sudo to open pcap files for examples.

When I type "sudo scapy" or "sudo scapy -H" (as you have it in https://scapy.readthedocs.io/en/latest/usage.html) displays the command bar "sudo: scapy: command not found".

So I tried "sudo /home/ubuntu/.local/bin/scapy" and "sudo /home/ubuntu/.local/bin/scapy -H". Both with the following output:
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/scapy", line 5, in <module>
    from scapy.main import interact
ModuleNotFoundError: No module named 'scapy'

I tried to edit the path line 5 in "/home/ubuntu/.local/bin/scapy", but I do not know how exactly and so far it has not worked yet.

I really hope you guys can help me.
Thanks a lot in advance.

**Comment by guedou** [comment]
It seems `scapy` is not installed for your root user. Please use gitter to ask further questions.
