### ISSUE TITLE
WARNING: Calling str(pkt) on Python 3 makes no sense!

### ISSUE THREAD

**Issue by viponedream** [secdev/scapy#3548]
### Brief description

from scapy.all import *

ip_obj = IP()
tcp_obj = TCP()

when i debug this simple code, it says:

WARNING: Calling str(pkt) on Python 3 makes no sense!
WARNING: Calling str(pkt) on Python 3 makes no sense!
WARNING: Calling str(pkt) on Python 3 makes no sense!

how to fix this, please

### Scapy version

last

### Python version

last

### Operating system

last

### Additional environment information

no

### How to reproduce

from scapy.all import *

ip_obj = IP()
tcp_obj = TCP()

when i debug this simple code, it says:

WARNING: Calling str(pkt) on Python 3 makes no sense!
WARNING: Calling str(pkt) on Python 3 makes no sense!
WARNING: Calling str(pkt) on Python 3 makes no sense!

how to fix this, please

### Actual result

wrong

### Related resources

no

**Comment by guedou** [comment]
Please read the documentarion and ask your questions on gitter. This is a bug tracker not a forum.

**Comment by David-OConnor** [comment]
Where in the documentation is this? A search on several relevant pages, and using the default search function didn't turn up a result. Why doesn't calling `str` on a packet make sense?

**Comment by SandroMartens** [comment]
> Please read the documentarion and ask your questions on gitter. This is a bug tracker not a forum.

What do you think this is?

**Comment by shrddr** [comment]
I think the problem is scapy intended usage is commandline as opposed to inside IDE and assumes you are consciously calling str() on packets. But PyCharm for example calls str() automatically when debugging to show all local variable contents. You can disable this behavior in "Debug toolbar | Settings | Variables" but of course that's not a good solution because you will now be debugging blind.

**Comment by kamichal** [comment]
> This is a bug tracker not a forum.

This is an issue with `scapy` and it's silly warning. Please get rid of this annoying, pointless message.

**Comment by p-l-** [comment]
Yes sure we will do as your will. Thank you for your message.
