### ISSUE TITLE
Accept bytearray as a valid Packet() parameter ?

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#3549]
While experimenting with Scapy, a colleague discovered the following issue while passing a `bytearray`  to the `Ether` constructor.

```
>>> raw(Ether(bytearray(b"\x00" * 14)))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-92197f130b79> in <module>
----> 1 raw(Ether(bytearray(b"\x00" * 14)))

~/Projects/Scapy/scapy.git/scapy/compat.py in raw(x)
    292         This function is and will always be cross-version compatible
    293         """
--> 294         return bytes(x)
    295 
    296     def bytes_encode(x):

TypeError: __bytes__ returned non-bytes (type bytearray)
```

Here is the expected result:
```
>>> raw(Ether(bytearray(b"\x00" * 14)))
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
```

Shall we modify Scapy to accept such type as a valid input for the constructor ?

**Comment by wh14h** [comment]
I think a more general issue is that you cannot cast an Ether packet created from a bytearray as bytes:

1-line example:

`` import scapy.all; bytes(scapy.all.Ether(bytearray(bytes(scapy.all.Ether()))))``

returns

> WARNING: Mac address to reach destination not found. Using broadcast.
> \---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> ~/test/ipython.py in <module>
> \----> 1 import scapy.all; bytes(scapy.all.Ether(bytearray(bytes(scapy.all.Ether()))))
> 
> TypeError: __bytes__ returned non-bytes (type bytearray)

**Comment by gpotter2** [comment]
Is this really worth it? You could just convert it back to bytes:
```python
Ether(bytes(bytearray(b"\0"*14)))
```
