### ISSUE TITLE
Probe Response Tag iteration walks into FCS

### ISSUE THREAD

**Issue by kevinenglish-keyw** [secdev/scapy#3553]
### Brief description

When iterating the tags of a WiFi beacon response (wlan.fc.type_subtype ==5) , using a while loop like:
```
    while p:
        if type(p).__name__ == "Raw":
            inc_nested_counter(Tags, ["Raw", "len", len(p.load)])
        else:            
            id = p.ID
            inc_nested_counter(Tags, [p.ID, "_count"])
        p = p.payload
```
The 4-byte Frame Check Sequence (FCS) at the end of the packet is treated as if it were a Tag element.

### Scapy version

2.4.5rc1.dev211

### Python version

3.8

### Operating system

Ubuntu 20.04.4 LTS

### Additional environment information

The collector of the packets I am working with provided Per Packet Information (PPI) wrapped WiFi Frames.

### How to reproduce

Iterate through tags on any 802.11 Probe Response packet (possibly must be wrapped in PPI)

**Comment by polybassa** [comment]
Thanks for the issue.

Could you please provide a pcap file to reproduce your issue.

**Comment by gpotter2** [comment]
Closed for inactivity

**Comment by kevinenglish-keyw** [comment]
Sorry, this is a mostly abandoned email account and I just noticed this.

I do not have a PCAP file handy at the moment, but this should be apparent
with any beacon response WiFi packet.  It does not error out, it returns
invalid data for every WiFi beacon response parsed.
