### ISSUE TITLE
Using in windows: AttributeError: 'module' object has no attribute 'plist'

### ISSUE THREAD

**Issue by fallenreaper** [secdev/scapy#358]
I was doing some simple arp poisoning scripting and bumped into this on my windows machine.

Seems that when I try to do

`import scapy.plist as plist` it doesnt like it and kicks back this attribute error.

Traceback (most recent call last):
  File "arp.py", line 3, in <module>
    import scapy.plist as plist
  File "C:\Python27\lib\site-packages\scapy\plist.py", line 18, in <module>
    from scapy.arch import plt, MATPLOTLIB_INLINED, MATPLOTLIB_DEFAULT_PLOT_KARGS
  File "C:\Python27\lib\site-packages\scapy\arch\__init__.py", line 83, in <module>
    from scapy.arch.windows import *
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 20, in <module>
    import scapy.plist as plist
AttributeError: 'module' object has no attribute 'plist'

When i tried to see what version of scapy i had, by just well... entering: scapy it kicked back

INFO: Can't load Python libreadline or completer
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
INFO: Could not get readline console. Will not interpret ANSI color codes.
INFO: No IPv6 support in kernel
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
Welcome to Scapy (2.3.3)
☺←[34m←[1m☻>>> ☺←[0m☻
☺←[34m←[1m☻>>> ☺←[0m☻
☺←[34m←[1m☻>>> ☺←[0m☻

Seems like command prompt on windows is a bit..... finicky.
Anything I am doing wrong which is preventing plist from being used?

I normally do something like: `from scapy.all import *` just to cover my bases, but it seems that is still throwing issues with `global name 'log_runtime' not being defined` and noticing that your error imports were not being imported that something within scapy might be off.

**Comment by gpotter2** [comment]
Ok, i do agree that it's a bit hidden, but look at this before : 
http://scapy.readthedocs.io/en/latest/installation.html#windows

If you find the command prompt finicky, you shall probably start with that 😄

**Comment by gpotter2** [comment]
@guedou That can be closed. It has been resolved a quite long time ago
