### ISSUE TITLE
Current documentation uses unsupported ranges and wildcards

### ISSUE THREAD

**Issue by 6r1d** [secdev/scapy#3582]
### Brief description

Looking at [Read the Docs](https://scapy.readthedocs.io/en/latest/index.html), we can see the demo of using ranges for [TCP](https://scapy.readthedocs.io/en/latest/usage.html?highlight=TCP#tcp-ping) and [ICMP](https://scapy.readthedocs.io/en/latest/usage.html?highlight=ICMP#icmp-ping) pings, but those seem to be no more available.

### Scapy version

44e4121

### Python version

3.10.2

### Operating system

Linux 5.16.14

### How to reproduce

Try examples from the docs.

TCP:

```python
ans, unans = sr( IP(dst="192.168.1.*")/TCP(dport=80,flags="S") )
```

ICMP:

```python
ans, unans = sr(IP(dst="192.168.1.1-254")/ICMP())
```

### Actual result

Generally, the errors you'll see are:

```
scapy.error.Scapy_Exception: Wildcards are no longer accepted in Net()
```

and 

```
scapy.error.Scapy_Exception: Ranges are no longer accepted in Net()
```

### Expected result

Pings working.

**Comment by matsievskiysv** [comment]
Speaking about documentation, in section [generating-sets-of-packets](https://scapy.readthedocs.io/en/latest/usage.html#generating-sets-of-packets) one should explicitly wrap lists  in `PacketList` in order for listed methods to work.

**Comment by 6r1d** [comment]
> Speaking about documentation, in section [generating-sets-of-packets](https://scapy.readthedocs.io/en/latest/usage.html#generating-sets-of-packets) one should explicitly wrap lists in `PacketList` in order for listed methods to work.

Can you add a working example, please? Possibly, it's worthwhile to add another issue to demonstrate what breaks and how it does break.

**Comment by matsievskiysv** [comment]
> it's worthwhile to add another issue to demonstrate what breaks and how it does break

It's not like examples are broken, but rather misleading. In the [documentation](https://scapy.readthedocs.io/en/latest/usage.html#generating-sets-of-packets) after the lines
```python
b=IP(ttl=[1,2,(5,9)])
```
there's a list of methods that do not work on these objects.
```python
b.nsummary() # does not work
```
These should be wrapped in `PacketList` in order to work, which should probably be indicated in documentation
```python
PacketList(b).nsummary()
```

Additionally, there are occasional python2 style `print`s.

I'll create a PR later.
