### ISSUE TITLE
How to use HTTPResponse

### ISSUE THREAD

**Issue by jeffjohnahan** [secdev/scapy#3584]
### Brief description

There is allot of documentation on using HTTPRequest, but not response. I found this script to create a packet as a reply to a http request, `packet = scapy.IP(src=server_ip, dst=target_ip)/scapy.TCP() / HTTP() / HTTPResponse(Server=server_ip) / "<html><p>Hi</p></html>"`, this packet however does not work when sent and I am in need of some help. Thanks in advance. How could you change the script above to make it work as a response to a HTTP request

### Scapy version

2.4.5

### Python version

3.9

### Operating system

Kali Linux

### How to reproduce

Send the packet

**Comment by guedou** [comment]
Please ask your question on gitter.
