### ISSUE TITLE
Scapy doesn't recognize DNS layers when port != 53

### ISSUE THREAD

**Issue by yetanotherf0rked** [secdev/scapy#3598]
### Brief description

Hello.

I'm trying to manipulate DNS packets for a ctf. I use nfqueue to intercept a DNS query I send to a DNS server with dig. The intercepted packet, when given to Scapy, has Raw load not interpreted as a DNS layer (neither DNSQR)

Thank you.

### Scapy version

2.4.5

### Python version

3.10

### Operating system

5.17.5-arch1-1

### Additional environment information

I use scapy 2.4.5 (arch-linux package) and python 3.10. Pacman output:
```
local/python-scapy 2.4.5-4
    Powerful interactive packet manipulation program written in Python (library)
local/scapy 2.4.5-4
    Powerful interactive packet manipulation program written in Python (tools)
```

### How to reproduce

```python
#!/usr/bin/python3
from netfilterqueue import NetfilterQueue
from scapy import *
import os

S_ADDR = "SERVER"

output_rule = f"iptables -A OUTPUT --destination {S_ADDR} -j NFQUEUE"
flush_rules = "iptables -F OUTPUT && iptables -F INPUT"
os.system(output_rule)

def callback(pkt):
    p = IP(pkt.get_payload())
    if p.haslayer(UDP): # I use haslayer(UDP) since DNS isn't recognized
        # modify, update chcksums and show
        p.show2()
        pkt.set_payload(bytes(p))
    pkt.accept()

# Init nfqueue
q = NetfilterQueue()
q.bind(0, callback)
try:
    q.run()
except KeyboardInterrupt:
    q.unbind()
    os.system(flush_rules)
```

With dig :
`dig @challenge.nahamcon.com -p 31944 nahamcon.com`

When I use `DNS(bytes(p))` I manage to get the DNS layer. But I didn't manage to get the DNSQR layer.

### Actual result

Output:
```
###[ IP ]### 
  version   = 4
  ihl       = 5
  tos       = 0x0
  len       = 58
  id        = 25677
  flags     = 
  frag      = 0
  ttl       = 64
  proto     = udp
  chksum    = 0x3c0e
  src       = SRCIP
  dst       = DSTIP
  \options   \
###[ UDP ]### 
     sport     = 41129
     dport     = 31944
     len       = 38
     chksum    = 0xafcc
###[ Raw ]### 
        load      = '\\xe9\\xc1\x01 \x00\x01\x00\x00\x00\x00\x00\x00\x08nahamcon\x03com\x00\x00\x01\x00\x01
```

tshark output:
```bash
❯ sudo tshark -f "host challenge.nahamcon.com"
...
   9 924.814463617 SRCIP → DSTIP DNS 72 Standard query 0xe9c1 A nahamcon.com
   10 925.025073068 DSTIP → SRCIP UDP 60 31944 → 41129 Len=12
```

### Expected result

A DNSQR layer.

**Comment by p-l-** [comment]
Hi,

Based on the ports of the UDP layer, this is totally expected. Scapy uses source and destination ports to know which dissector to apply. I'm not sure why thark finds DNS layer, I'd have expected {t,wire}shark to use the same heuristic.

Pierre

**Comment by yetanotherf0rked** [comment]
> Based on the ports of the UDP layer, this is totally expected. Scapy uses source and destination ports to know which dissector to apply. I'm not sure why thark finds DNS layer, I'd have expected {t,wire}shark to use the same heuristic.

Thanks for your answer. Is there a way to still reconstruct the DNS and DNSQR layers with a port different than 53 ?

**Comment by p-l-** [comment]
You need to call `bind_layers(UDP, DNS, dport=31944)`
