### ISSUE TITLE
How to bind PacketField layers inside a Packet

### ISSUE THREAD

**Issue by pudii** [secdev/scapy#360]
Here my situation: I have two classes and in the testPacket-class is a PacketField defined. (let's assume PF1 and PF2 are also implemented, but due to save space not shown here). If I receive a packet, `output = headerPacket(request)` and the request is long enough to fill all the fields, then all is displayed correctly except the overflow from the PF1-Packet.
How can I achieve the output I want? Can somebody help me?

```
class headerPacket(Packet):
    name = "headerPacket"
    fields_desc = [
        ByteField("Name", 0),
        ByteField("Type", 0)]


class testPacket(Packet):
    name = "testPacket"
    fields_desc = [
        ByteField("Name", 0)
        PacketField("PF1", PF1(), PF1),
        PacketField("PF2", PF2(), PF2)]

bind_layers(headerPacket, testPacket)
```

My output:

```
###[ headerPacket ]### 
     Name     = 0
     Type      = 0
###[ testPacket ]### 
        Name       = 0
        \PF1       \
         |###[ PF1 ]### 
         |  Name        = 1
         |###[ Raw ]### 
         |     load      = '\x2'
        \PF2  \
         |###[ PF2 ]### 
         |  Name        = None
```

The output I want:

```
###[ headerPacket ]### 
     Name     = 0
     Type      = 0
###[ testPacket ]### 
        Name       = 0
        \PF1       \
         |###[ PF1 ]### 
         |  Name        = 1
        \PF2  \
         |###[ PF2 ]### 
         |  Name        = 2
```

**Comment by dark-lbp** [comment]
You can ``use guess_payload_class``
This is the example
```python
class headerPacket(Packet):
    name = "headerPacket"
    fields_desc = [
        ByteField("Name", 0),
        ByteField("Type", 0)]

    def guess_payload_class(self, payload):
        if self.Type == 0:
            return testPacket
        else:
            return None


class testPacket(Packet):
    name = "testPacket"
    fields_desc = [
        ByteField("Name", 0)
        PacketField("PF1", PF1(), PF1),
        PacketField("PF2", PF2(), PF2)]

bind_layers(headerPacket, testPacket)
```

**Comment by pudii** [comment]
Thank you for the answer, but that is not the solution for my problem. The binding between the `headerPacket` and the `testPacket` works fine. But the problem is the overload from the `PF1` field. The overload from the `PF1` field should be in the `PF2` field. If I bind the layers `PF1` and `PF2`, the result is the following. 

```
###[ headerPacket ]### 
     Name     = 0
     Type      = 0
###[ testPacket ]### 
        Name       = 0
        \PF1       \
         |###[ PF1 ]### 
         |  Name        = 1
         |###[ PF2 ]### 
         |     Name     = 2
        \PF2  \
         |###[ PF2 ]### 
         |  Name        = None
```

**Comment by dark-lbp** [comment]
Would you mind post all you code? I think the problem is in PF1() class.

**Comment by p-l-** [comment]
You should simply add, at the end of your code, another `bind_layers()` call, to let Scapy know that `PF1` does not "transport" another layer:
```Python
bind_layers(PF1, Padding)
```

**Comment by pudii** [comment]
Thank you p-l- ! This solved my problem.

**Comment by dark-lbp** [comment]
@pudii you can also add this code to PF1 packet. this should fix this problem too.
```python
    def extract_padding(self, p):
        return "", p
```

**Comment by p-l-** [comment]
@dark-lbp that would work but I cannot see a reason to do that. Using `bin_layers()` is the correct (Scapyest ;-)) way to have the code work.

**Comment by dark-lbp** [comment]
@p-l- Before you tell us we can do this with `bind_layers`, i always overwrite the `extract_padding` to make this work.
But when i use `PacketField` or  `PacketListField` i need to add `bind_layers` or rewrite`extract_padding` for all this field. Is there some case we need keep PacketField "transport" another layer?
