### ISSUE TITLE
python scapy 2.4.5 failed to resolve DNS response with SRV records

### ISSUE THREAD

**Issue by douyao1982** [secdev/scapy#3605]
i used python with scapy 2.4.5 to process my wireshark capture
here is my script:
from scapy.all import *
from scapy.utils import PcapReader
packets = rdpcap("dns_srv.pcap")
for packet in packets:
    print("packets#", number)
    if DNS in packet:
        if (DNSQR in packet) and (DNSRR not in packet):
            pass
        if DNSRR in packet:
            # print(get_dns_response(packet))
            print(packet[DNSRR]) 

here is the output:
b'\x04test\x03com\x00\x00\x02\x00\x01\x00\x00\x00<\x00\x0e\x03ns2\x04test\x03com\x00\x04test\x03com\x00\x00\x02\x00\x01\x00\x00\x00<\x00\x0e\x03ns1\x04test\x03com\x00'

the "packet[DNSRR]" returned section "Authoritative nameservers" instead of section "Answers"
not sure why, anything wrong
![dns_srv](https://user-images.githubusercontent.com/105473251/168207070-bd679aca-da19-40ef-a904-96bb0874339e.png)
 with my script or the scapy?

**Comment by guedou** [comment]
Please ask your question on gitter.
