### ISSUE TITLE
Typo in 802.11 Frame Types, Deauthentification instead of Deauthentication

### ISSUE THREAD

**Issue by sudarshan-suresh** [secdev/scapy#3609]
### Brief description

While working on Radiotap, the Deauthentication Frame Subtype is shown incorrectly as 'Deauthentification'. 

### Scapy version

2.4.4

### Python version

3.6.9

### Operating system

MacOS Big Sur 11.6.2

### Additional environment information

NA

### How to reproduce

1. Created an open wlan.
2. Enabled all radios of AP.
3. Associated a client with the wlan and passed continuous ICMP traffic to external n/w.
4. Started wireless pcap with filter 'subtype deauth'.

### Actual result

_Deauthentification_ 

### Expected result

_Deauthentication_

### Related resources

The issue is caused because of a typo. 
_Deauthentification_ => _Deauthentication_

https://github.com/secdev/scapy/blob/2da3800b87702178a0f60598aebdd7335ce5603d/scapy/layers/dot11.py#L595 
as per wiki I believe it should be 
<img width="797" alt="Screenshot 2022-05-18 at 3 03 43 PM" src="https://user-images.githubusercontent.com/10371118/169008145-f4ece6cf-b14c-4dbf-89ee-173e6a1deff9.png">

**Comment by p-l-** [comment]
You can read that: [CONTRIBUTING / submitting-pull-requests](https://github.com/secdev/scapy/blob/master/CONTRIBUTING.md#submitting-pull-requests)

**Comment by sudarshan-suresh** [comment]
PR : https://github.com/secdev/scapy/pull/3611
