### ISSUE TITLE
Custom array of Extension

### ISSUE THREAD

**Issue by vovabush** [secdev/scapy#3617]
### Brief description

Can't send my array of Extension in Client Hello packet SSL.

### Scapy version

2.4.5rc1.dev245

### Python version

3.10.4

### Operating system

Windows 10

### How to reproduce

1. Install Tomcat>9.0.50 and setup sslProtocol="TLS" in server.xml.
2. Try to connect with server by python script. 

Hello, I'm trying to send my extension in a hello client package. I do this with the following code:

```python
from scapy.layers.tls.handshake import *
from scapy.layers.tls.automaton_cli import TLSClientAutomaton
from scapy.layers.tls.extensions import *
supported_groups = ["secp384r1", "x448"]
supported_groups.append("x25519")
ext1 = [
  TLS_Ext_ExtendedMasterSecret(len=0),
  TLS_Ext_SupportedVersion_CH(versions=["TLS 1.3"]),
  TLS_Ext_RenegotiationInfo(renegotiated_connection=0),
  TLS_Ext_SupportedGroups(groups=supported_groups)
  ]
a = TLS13ClientHello(ciphers=[0x1301, 0x1302, 0x1303, 0x1304, 0x1305, 0x1306], ext=ext1)
t = TLSClientAutomaton(server="192.168.252.132", dport=443, client_hello=a, version="tls13")
t.run()
```

But in Client Hello i saw this Extensions:

![image](https://user-images.githubusercontent.com/3701803/169791185-6cf3de34-ab63-4d5e-bdc7-776039d37c83.png)

And in console output i saw "Missing TLS 1.3 EncryptedExtensions message!":

![image](https://user-images.githubusercontent.com/3701803/169792239-ca88a9de-b517-488d-a5ef-dae320275c97.png)

I already read [this issue](https://github.com/secdev/scapy/issues/2673), but my server is Tomcat with `sslProtocol="TLS"` and when i try to connect with it in TLS v1.2 I get Handshake Error.

Question: How can I send my arrya of Extension?

**Comment by Loris1123** [comment]
I'm having a similar issue. I'm creating a ClientHello for a TLS1.2 client in the same issue, as you do. But the only extension I can see is `signature_algorithms`.

```
            Extensions Length: 8
            Extension: signature_algorithms (len=4)
                Type: signature_algorithms (13)
                Length: 4
                Signature Hash Algorithms Length: 2
                Signature Hash Algorithms (1 algorithm)
                    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                        Signature Hash Algorithm Hash: SHA256 (4)
                        Signature Hash Algorithm Signature: RSA (1)
```

Even if I specify `ext=[]` or `ext=None` the extension will be there.

**Comment by Loris1123** [comment]
This could be related to https://github.com/secdev/scapy/issues/4247
