### ISSUE TITLE
[Enhancement] Inflexible Automaton timeout configuration

### ISSUE THREAD

**Issue by matsievskiysv** [secdev/scapy#3624]
### Brief description

The current implementation of `Automaton_metaclass` creates a `timeout` list in `__new__`, which means that timeout values are set during code sourcing and can only be changed by modifying `self.timeout` manually. Meanwhile, many protocols (e.g. ERPS) require timeout configuration. This could be supported by allowing functions as `ATMT.timeout` arguments and expanding them during `__init__`. 
I'll try to implement it if this feature is approved.

### Scapy version

6d7184e8bec5102dfa66bcc10432a30a7e0dcf3a

### Python version

3.10

### Operating system

All

### How to reproduce

-

**Comment by gpotter2** [comment]
Hi !

Cant you just dynamically create the python class? For instance

```
def create(timeout):
    class A(Automaton):
        [...]
        @ATMT.timeout(timeout)
        def tmout(self):
            pass
```

**Comment by matsievskiysv** [comment]
Maybe a timeout class would be better? Then lazy timeout sort could be done, allowing runtime reconfiguration.

**Comment by gpotter2** [comment]
This does sound a bit like bloat. Feel free to try to prototype something.. It's hard to see an actual useful casd
