### ISSUE TITLE
Padding Hex data is not working if its a character a,b,c,d,e,f 

### ISSUE THREAD

**Issue by devisxreagan** [secdev/scapy#3626]
Hi Team ,

I am new to scapy and I am trying to add my own hex data as padding to form my own packet  , but when I try to add any hex values from 1-9 it just added properly and sent on to the other side of the interface , but when I add "abcdef" one of these , it always comes other side with some improper values  . Ref below , pls do help on this issue

In my example , I try to send packet using interface eno12399 and this interface is looped backed to eno12409 in which I do a tcpdump .

Working case [When using 1-9] :
======================

Scapy side :

>>> pad = Padding()
...: pad.load = "\x12\x34\x56\x78"
...: b=Ether(src="aa:bb:cc:c7:4f:dd", dst="ff:ff:ff:ff:ff:ff", type=0x88f8)/raw(pad)
>>> hexdump(b)
...:
0000  FF FF FF FF FF FF AA BB CC C7 4F DD 88 F8 12 34  ..........O....4                  <<<<< It comes correct as 12345678
0010  56 78                                            Vx
>>>
>>> sendp(b, iface="eno12399")
...:
.
Sent 1 packets.
>>>

Tcpdump side:

18:06:16.588354 aa:bb:cc:c7:4f:dd (oui Unknown) > Broadcast, ethertype Unknown (0x88f8), length 60:
        0x0000:  1234 5678 0000 0000 0000 0000 0000 0000  .4Vx............                           <<<<< It comes correct as 12345678
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............

Non - Working case [When using a,b,c,d,e,f] :
=============================

>>> pad = Padding()
...: pad.load = "\xaa\xbb\xcc\xdd"
...: b=Ether(src="aa:bb:cc:c7:4f:dd", dst="ff:ff:ff:ff:ff:ff", type=0x88f8)/raw(pad)
...:
>>> hexdump(b)
0000  FF FF FF FF FF FF AA BB CC C7 4F DD 88 F8 C2 AA  ..........O.....              <<<< It suppose to come as AABBCCDD but not
0010  C2 BB C3 8C C3 9D                                ......
>>> sendp(b, iface="eno12399")
...:
.
Sent 1 packets.
>>>

18:08:20.043390 aa:bb:cc:c7:4f:dd (oui Unknown) > Broadcast, ethertype Unknown (0x88f8), length 60:
        0x0000:  c2aa c2bb c38c c39d 0000 0000 0000 0000  ................                 <<<< It suppose to come as AABBCCDD but not
        0x0010:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0020:  0000 0000 0000 0000 0000 0000 0000       ..............

Thanks,
Devis

**Comment by devisxreagan** [comment]
Is this could be a bug in scapy ? Pls advice

**Comment by gpotter2** [comment]
You're confusing Python3's strings and bytes
![image](https://user-images.githubusercontent.com/10530980/174113253-8d312b87-c6de-46b3-a8cf-8a0ae5d273c8.png)
