### ISSUE TITLE
send/receive HTTP 1.X  example not working

### ISSUE THREAD

**Issue by tanaxer01** [secdev/scapy#3627]
### Brief description

I have been having some issues working with HTTP1.x on scapy. After testing with various enviroments (Mostly VMs), I haven't been able to fix this issue. When sending tráfic through a `TCP_client.tcplink`,  scapy hangs waiting for a response that has already arrived.

### Scapy version

2.4.5rc1.dev245

### Python version

3.10.4

### Operating system

Linux 5.17.3

### How to reproduce

Just follow the example present on the scapy docs.
```python
load_layer("http")
req = HTTP()/HTTPRequest(
    Accept_Encoding=b'gzip, deflate',
    Cache_Control=b'no-cache',
    Connection=b'keep-alive',
    Host=b'www.secdev.org',
    Pragma=b'no-cache'
)
a = TCP_client.tcplink(HTTP, "www.secdev.org", 80)
answer = a.sr1(req)
a.close()
with open("www.secdev.org.html", "wb") as file:
    file.write(answer.load)
```

### Actual result

After runing the code, scapy doesnt get a response.
```
>>> load_layer("http")
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()
>>> req = HTTP()/HTTPRequest(
...     Accept_Encoding=b'gzip, deflate',
alive',
...     Cache_Control=b'no-cache',
    Host=b'www....     Connection=b'keep-alive',
...     Host=b'www.secdev.org',
 Pragma...     Pragma=b'no-cache'
... )
>>> a = TCP_client.tcplink(HTTP, "www.secdev.org", 80)
/usr/lib/python3.10/site-packages/scapy/automaton.py:740: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  _t.setDaemon(True)
/usr/lib/python3.10/site-packages/scapy/automaton.py:746: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  self.threadid = threading.currentThread().ident
>>> answer = a.sr1(req)
Begin emission:
Finished sending 1 packets.
```
The tráfic generated by this example was the following:
![image](https://user-images.githubusercontent.com/2672077/170586396-638d15e1-9a4f-40f1-8d74-e921b3d662eb.png)

### Expected result

The expected outcome would be a correct tcp handshake and a HTTP transaction.

**Comment by gpotter2** [comment]
You're getting a RST from your OS, this is expected. For this example to work you'd need something like
```sh
sudo iptables -A INPUT -s 217.25.178.5 -p tcp -j DROP
```
