### ISSUE TITLE
WARNING: Could not get the source MAC: invalid literal for int() with base 16: ''

### ISSUE THREAD

**Issue by WillianBR** [secdev/scapy#3629]
Folks,

I'm writing a Py3 script to scan my home network, get all hosts and MAC-Address to catalog (manufacture, etc.).

But when I call the `scapy.srp()` the output console print an annoing warning message!

Call:
`answered_list = scapy.srp(broadcast_ether_arp_req_frame, timeout = 2, verbose = False)[0]`

Output:
**WARNING: Could not get the source MAC: invalid literal for int() with base 16: ''**

I had tried to redirect sys.stderr  and sys.stdout to a buffer (io.StringIO), but nothing is working.

The code block with redirection is:
```
bufWarning = ""
with StringIO() as buffStdOut, redirect_stdout(buffStdOut):
    answered_list = scapy.srp(broadcast_ether_arp_req_frame, timeout = 2, verbose = False)[0]
    bufWarning = buffStdOut.getvalue()
print(f"bufWarning = {bufWarning}")
```

The outputs are:
```
> python network_scanner.py -t 192.168.0.1/24
WARNING: Could not get the source MAC: invalid literal for int() with base 16: ''
WARNING: Could not get the source MAC: invalid literal for int() with base 16: ''
bufWarning =
-----------------------------------
IP Address      MAC Address
-----------------------------------
192.168.0.1     60:a4:b7:f1:8f:64
192.168.0.152   44:3b:32:e0:63:ac
192.168.0.10    80:fb:f0:30:c0:d1
192.168.0.197   d6:e1:5e:1b:4d:89
192.168.0.180   a4:63:a1:00:19:f4
192.168.0.158   ea:25:0d:d7:68:be

```

As we can see the the bufWarning is empty!

**And yes, I had redirected stderr and stdout and both are empty!**

**How I can supress this message?**

Does anyone has a slight idea, how to trap the warning?

**Comment by guedou** [comment]
Please use the issue template if you want us to give you an answer.
