### ISSUE TITLE
Putting down an interface causes sniff() to get stuck on the ObjectPipe

### ISSUE THREAD

**Issue by Zalewa** [secdev/scapy#3631]
### Brief description

`sniff()` gets stuck forever when the eth interface it sniffs on is brought down. There's no notification to the caller that the sniffing is dead, even though `sniff()` internally knows about that.

### Scapy version

2.4.5

### Python version

3.6.9

### Operating system

4.15.0-143-generic

### How to reproduce

1. Open a terminal, in this terminal run a Python script:
```
from scapy.all import sniff
sniff(iface="eth0")
```
Replace "eth0" with your own interface if needed. 
The script should now get stuck in the sniffing loop inside `sniff()`, which is correct and expected.
Leave this terminal open and the script running.

2. Open another terminal, run: `sudo ip link set eth0 down`

### Actual result

Entering the `sniff()` as presented in step 1. creates an `AsyncSniffer` object from the `sendrecv` module. There it opens 2 "selectables": a `scapy.arch.linux.L2ListenSocket` and a `scapy.automaton.ObjectPipe`. The `ObjectPipe` is opened because the `L2ListenSocket` is determined to be blocking and with the `ObjectPipe` we can stop the sniffing by calling the `stop()` method. Both of these "selectables" are put on the `sniff_sockets` list which is then passed to the blocking `select_func()`. So far so good.

But then we put the `eth0` interface down by doing step 2. This correctly triggers the `select_func()` on the `L2ListenSocket` which is detected to be EOF and then marked as dead and put on the `dead_sockets` list. The `L2ListenSocket` is subsequently removed from the `sniff_sockets` list. As there are no more actual sockets to sniff on, the `sniff()` should stop now. Right? But that doesn't happen. 

The dummy `ObjectPipe` still remains on the `sniff_sockets` list and because the `while` loop checks if there is anything (**anything!** so the dummy `ObjectPipe` counts) on this list, the loop will get stuck on `select_func()` indefinitely - or at least until `stop()` on the `AsyncSniffer` is called, but when you call the `sniff()` function directly there's no reference to `AsyncSniffer` available.

`sniff()` doesn't return and doesn't raise any error either. Moreover, even if the eth device is brought back up, `sniff()` will not resume sniffing. It doesn't help even if I bypass `sniff()` and create `AsyncSniffer` myself then call `AsyncSniffer._run()` directly, because the eth up/down status is usually controlled by outside means, so there's no easy way to determine when `AsyncSniffer.stop()` should be called.

### Expected result

I need a way to resurrect the sniffing after the interface is brought down and then back up. I need a way to detect that the old sniffing has died so that I can create a new sniffer on the same interface.

Pardon me if I'm incorrect but can non-blocking sockets raise the EOFError too? If yes then I don't think the behavior with a blocking socket should be different from the non-blocking socket. When the sniffed socket is non-blocking, the `ObjectPipe` is never created and never put on the `sniff_sockets` list, thus as soon as the main socket is determined to be dead, `sniff_sockets` list will become empty and `sniff()` will end and return to the caller. I think that when the sniffed interface is brought down and its socket is determined as dead then `sniff()` should end.

**Comment by gpotter2** [comment]
Thank you for the very complete bug report. This is indeed a bug, and will be fixed in #3663

**Comment by Benature** [comment]
May I ask when will the fixed version released? Looking forward to it.

**Comment by p-l-** [comment]
@Benature you can track the progress here: https://github.com/secdev/scapy/issues/3564
