### ISSUE TITLE
Move the DSL used in Scapy close to Construct and Kaitai Struct

### ISSUE THREAD

**Issue by KOLANICH** [secdev/scapy#3667]
Of the 2 it is now closer to Construct than to raw KS, but in some distant future we may want to use raw KS. But for now it is proposed to move it closer to Construct

1. payload should be not a field, but an alias to some another field with an own name.
2. `LenField` should be replaced with a proper integer field, and instead the payload field should refer the length field
3. the need to redefine the methods in order to build the most of packets dissectors should be eliminated
4. we need a way to pass parameters to packets without dirty hacks with zero-size defaults in multiple types fields with the lambda returning `False`
5. Ideally we should have a one simple function creating a wrapper to KSC-generated Construct spec. And maybe translate the existing definitions into Construct one by one.

**Comment by gpotter2** [comment]
This is currently way out of scope and out of our roadmap. We likely aren't going to move away from current internals.
