### ISSUE TITLE
defragmented IP Packet has wrong packet.time

### ISSUE THREAD

**Issue by shenmintao** [secdev/scapy#3673]
### Brief description

When I use sniff() with session option to parse a pcapng file which has some fragmented IP packets, I found that the defragmented packets give the wrong time. It's the current time, not the arrival time in Wireshark.
I don't know if this is a bug, but it's annoying me. Maybe we could assign packet.time to defragmented_packet before returning defragmented_packet?

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Windows 11 x64

### How to reproduce

Use Wireshark to capture some packets including fragmented IP packets, and use the sniff function with the IPSession option to parse these packets, then print packets time.

**Comment by p-l-** [comment]
This would probably make sense, yes. The only question is: which time value would you then use? The one from the first packet? From the last one? From one in the middle? A mean or median value of all packets?

**Comment by shenmintao** [comment]
> This would probably make sense, yes. The only question is: which time value would you then use? The one from the first packet? From the last one? From one in the middle? A mean or median value of all packets? I would chose either the first one or the last one.

Maybe the last packet time is a good choice, for the last packet time suggests that all fragments has been received and the full datagram has been fully reassembled.
