### ISSUE TITLE
bluetooth.HCI_ACL_Hdr fields parsed incorrectly

### ISSUE THREAD

**Issue by tkuester** [secdev/scapy#368]
The Bluetooth HCI ACL Header has a nasty little field that scapy currently fails to parse correctly. From my brief understanding of code, it seems that the problem stems from not being able to handle little endian short bitfields.

### Reference Material
From page 676 of the Bluetooth 4.0 Core Spec PDF:

![acl_hdr](https://cloud.githubusercontent.com/assets/6379955/20801250/41e9c2f2-b7b6-11e6-8666-3cadb6b7e809.png)

A live packet captured from Wireshark:

![wireshark_hci_acl](https://cloud.githubusercontent.com/assets/6379955/20801401/bdda5d40-b7b6-11e6-8f36-8b82db12e44f.png)

In this instance, the field has the char buffer value `[0x4c, 0x00]`, which as a short would be `0x004c`. You can parse the sub fields like so.

```python
(val, ) = struct.unpack('<H', '\x4c\x00')
handle = val & 0x0fff
pb_flag = (val & 0x3000) >> 12
bc_flag = (val & 0xc000) >> 14
```

### Scapy's Current Handling
This incorrectly treats the handle and flags as 8-bit values.

```python
class HCI_ACL_Hdr(Packet):
    name = "HCI ACL header"
    fields_desc = [ ByteField("handle",0), # Actually, handle is 12 bits and flags is 4.
                    ByteField("flags",0),  # I wait to write a LEBitField
                    LEShortField("len",None), ]
    def post_build(self, p, pay):
        p += pay 
        if self.len is None:
            l = len(p)-4
            p = p[:2]+chr(l&0xff)+chr((l>>8)&0xff)+p[4:]
        return p
```

Interestingly enough, the pb/bc_flags are treated differently depending on whether the packet is going Host -> Device or Device -> Host.

### Temporary Fix
I first tried using `fields.BitField` and `BitEnumField`, but I learned these work left to right. Since the field is a little endian short, the pb/bc flags split up the handle, rendering this approach useless.

The current method provides incorrect information for both fields, and only preserves the length field. This method lets us access the field as a unit, and delegates separating the sub-fields to the user. Not very scapy-like, but it restores some functionality to the code.

```python
    # ...
    fields_desc = [ LEShortField("hflags",0), # Mask with 0x0fff to get handle
                    LEShortField("len",None), ]
    # ...
```

### Proposal
Could you make a custom `class ACLHandleFlags(LEShortField)` under `layers.bluetooth` that handles this using `__slots__`?

Or perhaps something like this?
```python
fields_desc = [LEBitField(width=16, {'pb_flag': (15, 14, {0: 'first flushable...'}),
                                     'bc_flag': (13, 12, {0: 'more enum stuff...'),
                                     'handle':  (11, 0, int)}),
               LEShortField("len", None)]
```

Unfortunately, I don't quite understand scapy's meta-programming to contribute!

**Comment by gpotter2** [comment]
@tkuester Hi ! (sorry for the delay)
It seems that scapy has been updated since them, current code is:
```
class HCI_ACL_Hdr(Packet):
    name = "HCI ACL header"
    fields_desc = [ ByteField("handle",0), # Actually, handle is 12 bits and flags is 4.
                    ByteField("flags",0),  # I wait to write a LEBitField
                    LEShortField("len",None), ]
    def post_build(self, p, pay):
        p += pay
        if self.len is None:
            p = p[:2] + struct.pack("<H", len(pay)) + p[4:]
        return p
```
Could you confirm that your bug remains ?

**Comment by tkuester** [comment]
@gpotter2 Hey, here's a quick little test case.

```python
#!/usr/bin/python
from scapy.layers import bluetooth
bytz = '4caf0b0007000400100100ffff0028'.decode('hex')

pkt = bluetooth.HCI_ACL_Hdr(bytz)

print "Handle (should be 0xf4c): 0x%03x" % pkt.handle
print "Flags (should be 0xa): 0x%x" % pkt.flags
```

In my understanding, [0x4c, 0x0f] should be a short: 0x0f4c. The flags are the first nibble(0x0), and the handle is the next three. (0xf4c).

Currently, the program prints out this:

```
Handle (should be 0xf4c): 0x04c
Flags (should be 0xa): 0xaf
```

**Comment by gpotter2** [comment]
@tkuester Alright.
Easiest way would be a trick like
```
diff --git a/scapy/layers/bluetooth.py b/scapy/layers/bluetooth.py
index 4f63e0f2..c4174436 100644
--- a/scapy/layers/bluetooth.py
+++ b/scapy/layers/bluetooth.py
@@ -79,9 +79,18 @@ class HCI_Hdr(Packet):

 class HCI_ACL_Hdr(Packet):
     name = "HCI ACL header"
-    fields_desc = [ ByteField("handle",0), # Actually, handle is 12 bits and flags is 4.
-                    ByteField("flags",0),  # I wait to write a LEBitField
-                    LEShortField("len",None), ]
+    fields_desc = [ BitField("handle",0,12),    # TODO: Create and use LEBitField
+                    BitField("flags",0,4),      # They are recieved as a **combined** LE Short
+                    LEShortField("len",None), ] # Handle is 12 bits, flags is 4 bits.
+
+    def pre_dissect(self, s):
+        # Turn data into LE, then into:
+        # .... 1111 0100 1100 = handle
+        # 1010 .... .... .... = flags
+        hf = socket.ntohs(struct.unpack("!H", s[:2])[0])
+        r = ((hf & 0x0fff) << 4) + (hf >> 12)
+        return struct.pack("!H", r) + s[2:]
+
     def post_build(self, p, pay):
         p += pay
         if self.len is None:
@@ -689,7 +698,7 @@ bind_layers( HCI_Hdr,       HCI_ACL_Hdr,        type=2)
```
And I guess the best way of doing this would be to create

**Comment by gpotter2** [comment]
Fixed in https://github.com/secdev/scapy/pull/685
