### ISSUE TITLE
How to sniff the packets faster or how to dump all the packets(1000 packets) to file in order to process it later? 

### ISSUE THREAD

**Issue by nagmat1** [secdev/scapy#3694]
I am sending a file from Host A to server B using python sockets. The file size is around 4 MB. While sending the file I am mirroring the packets to Host C where I am sniffing the packets. Total number of packets for 4 MB file is around 1000 packets. The maximum performance I got on Host C using tcpdump is 400 packets out of 1000 packets. With Scapy sniffing I am getting maximum 200 packets only on Host C. My question is how can I sniff all the packets on Host C faster and get all 1000 packets on Host C? 

My sniffer code is : 
```
def get_if():
    ifs=get_if_list()
    iface=None
    for i in get_if_list():
        if "enp1s0f1" in i:
            iface=i
            break;
    if not iface:
        print("Cannot find eth0 interface")
        exit(1)
    return iface


def handle_pkt(pkt):
    global file_hash
    global counter
    try :
        setir = pkt[IP].load
    except :
        setir = ""
    if "<SEPARATOR>" in str(setir):
        setir = ""
    if setir!="" :
        file_hash.update(setir)
    print("{}. Hash = {} ".format(counter,file_hash.hexdigest()))
    #pkt.show2()
    sys.stdout.flush()
    counter = counter +1

def main():
    ifaces = [i for i in os.listdir('/sys/class/net/') ]
    iface = get_if()
    print(("sniffing on %s" % iface))
    sys.stdout.flush()
    sniff(filter='tcp and port 5201',iface = iface,
          prn = lambda x: handle_pkt(x))

if __name__ == '__main__':
    main()
```

The problem is socket transfer rate is too high, that's why I included :  
``` 
time.sleep(0.001)
```
on Server side. When I am slowing down the transfer either on Host A or Server B I can sniff all the packets on Host C. 
My questions are:
1. How can I sniff the packets faster than I am getting now? 
2. Can I establish a socket connection on Host C without handshake and get all the packets from mirrored port?

**Comment by polybassa** [comment]
Hi, please note that this is an issue board and bug tracker. Please ask your questions on gitter: https://gitter.im/secdev/scapy
