### ISSUE TITLE
Timestamp Scapy Sniff() produces current timestamp

### ISSUE THREAD

**Issue by Mitsj0l** [secdev/scapy#3724]
### Brief description

Hi all, it seems when using the sniff function, timestamps are returned of the current time, instead of the original timestamp of the packet. I see this packet from version 2.4.3-2.5.0rc0.

`scapy_cap = rdpcap('input/1688.com_11.pcap')
test = sniff(lfilter=lambda x: UDP in x, offline=scapy_cap)
sniff(offline=scapy_cap)
| <Sniffed: TCP:0 UDP:127 ICMP:0 Other:0>
test[0].time
| 1661866415.282953
scapy_cap[0].time
| Decimal('1661350730.946522')`

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Windows 11 and macOS

### How to reproduce

scapy_cap = rdpcap('input/1688.com_11.pcap')
test = sniff(lfilter=lambda x: UDP in x, offline=scapy_cap)
[1688.com_11.pcap.zip](https://github.com/secdev/scapy/files/9459266/1688.com_11.pcap.zip)

sniff(offline=scapy_cap)
| <Sniffed: TCP:0 UDP:127 ICMP:0 Other:0>
test[0].time
| 1661866415.282953
scapy_cap[0].time
| Decimal('1661350730.946522')

### Actual result

`test = sniff(lfilter=lambda x: UDP in x, offline=scapy_cap)
sniff(offline=scapy_cap)
| <Sniffed: TCP:0 UDP:127 ICMP:0 Other:0>
test[0].time
| 1661866415.282953`

### Expected result

`scapy_cap[0].time
| Decimal('1661350730.946522')`

**Comment by guedou** [comment]
That is the expected behavior. You should use rdpcap() to read packets then call the filter() method.

**Comment by okridgway** [comment]
> That is the expected behavior. You should use rdpcap() to read packets then call the filter() method.

Why is this expected behavior?
