### ISSUE TITLE
sr seems to not work properly on my end?

### ISSUE THREAD

**Issue by StormPug** [secdev/scapy#3727]
I wrote the following function which yields no results:

```
def SynScanner(host):
        #use the sr function
        for port in range(80,445):
            reply,noreply = sr(IP(dst=host)/TCP(dport=port, flags="S"),timeout=0.1,verbose=0)
        
        #output the responses
        print(reply)   #This outputs <Results: TCP:0 UDP:0 ICMP:0 Other:0>

        print("Open ports are:")

        for(s,r) in reply:
            print(s[TCP].dport)
    
    host = "Enter IP address here"
    SynScanner(host)
```

Could you please let me know if this is working on your end?

**Comment by gpotter2** [comment]
Note this is a bug tracker and not a forum. (ask on stackoverflow). I'll be closing this.

Just to help you a bit, it's 100% expected: you're not keeping the `reply,noreply` variables but instead keep writing over them... you should do
instead of your for loop something like
```
reply,noreply = sr(IP(dst=host)/TCP(dport=(80,445), flags="S"), timeout=3, verbose=0)
```
