### ISSUE TITLE
CryptographyDeprecationWarnings emitted when using scapy 2.4.5 with cryptography 38.0.1 and python 3.10.4

### ISSUE THREAD

**Issue by AlexanderRavenheart** [secdev/scapy#3731]
### Brief description

We notice the following warnings being emitted when using scapy 2.4.5 with python 3.10.4 and cryptography 38.0.1:
```
.venv/lib/python3.10/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
    cipher=algorithms.Blowfish,
.venv/lib/python3.10/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
    cipher=algorithms.CAST5
```

### Scapy version

2.4.5

### Python version

3.10.4

### Operating system

Linux 5.14.0-1046-oem (Xubuntu 22.04)

### How to reproduce

Any script that imports directly or indirectly anything from the ipsec.py module should trigger the deprecation warnings.

**Comment by gpotter2** [comment]
As per the template, please retry using the latest dev version. This is already fixed https://github.com/secdev/scapy/pull/3645
