### ISSUE TITLE
The padding and CRC of Ethernet II frames are included in the TCP length

### ISSUE THREAD

**Issue by yafeng-Soong** [secdev/scapy#3733]
### Brief description

The padding and CRC of Ethernet II frames are included in the TCP length, when I tried to get the length of TCP payload with the following code.
```python
with PcapNgReader(pcap_path) as preader:
        for p in preader:
            ip = p.payload
            if not isinstance(ip, scapy.layers.inet.IP):
                continue
            tcp = ip.payload
            p_len = len(tcp.payload) # There is a problem with the value of p_len
```
Ethernet II specifies that the minimum amount of data is 46 bytes. If it does not meet the requirements, 0 bytes will be filled. Therefore, when the TCP payload is length 0, there will be 6 bytes of padding, and 4 bytes of CRC check code.Here, the value of p_len is 10 instead of the 0. 

### Scapy version

2.4.5

### Python version

3.10

### Operating system

Windows 11

### How to reproduce

Useing following code to parse the report.pcapng file in related resources
```python
with PcapNgReader(pcap_path) as preader:
    for p in preader:
        ip = p.payload
        if not isinstance(ip, scapy.layers.inet.IP):
            continue
        tcp = ip.payload
        p_len = len(tcp.payload)
        print(p_len)
```

### Actual result

10

### Expected result

0

### Related resources

[report.zip](https://github.com/secdev/scapy/files/9533493/report.zip)

**Comment by guedou** [comment]
As you can see in the last packet of the provided pcap, Scapy correctly identifies data after the TCP header as padding:
```
>>> l[-1]
<Ether  dst=54:36:9b:32:e2:b0 src=44:d7:91:53:07:f0 type=IPv4 |<IP  version=4 ihl=5 tos=0x0 len=40 id=59035 flags=DF frag=0 ttl=64 proto=tcp chksum=0xeb6d src=192.168.1.74 dst=58.216.107.252 |<TCP  sport=57570 dport=https seq=551677774 ack=3757663694 dataofs=5 reserved=0 flags=A window=1929 chksum=0x6ef urgptr=0 |<Padding  load='\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' |>>>>
```
