### ISSUE TITLE
`sniff()` not capturing ARP responses and pings

### ISSUE THREAD

**Issue by CITIZENDOT** [secdev/scapy#3745]
### Brief description

I have a mininet network with a simple topology. A switch s1, three hosts h1, h2, h3, and another host named attacker. From the attacker's interface, I'm sniffing the packets using `sniff()`. But when I ping h2 from h1, anything from anything, I'm noticing only a few packets are getting captured. whereas Wireshark is capturing a lot many. Especially, I noticed not a single ARP reply is captured.

_I am attaching two screenshots. Will provide any other information if required._
![image](https://user-images.githubusercontent.com/52322531/192446254-42ded212-9332-4754-86eb-e29daff9647e.png)
On the left, I'm pinging hosts from other hosts. On the right, I have the sniffer that prints packet summaries. As shown, Only ARP requests are printed.

![image](https://user-images.githubusercontent.com/52322531/192446280-64986278-635b-414f-b4b7-994904f89818.png)
But Wireshark is logging all the packets properly.

### Scapy version

2.4.3

### Python version

3.8

### Operating system

Linux 5.4.0

### How to reproduce

- In the mininet VM, Create a new topology with the script: [custom_topology.py](https://pastebin.com/d7JsQT2n)
- Run this script: [arpspoof_sniff.py](https://pastebin.com/2daGLSfF) in the `attacker` shell

### Actual result

Only 3 packets (all are ARP Requests)

### Expected result

- Multiple ARP Requests and Responses
- ICMP packets

**Comment by guedou** [comment]
Please call ask your question on gitter instead. This is not a forum but a bug tracker.
