### ISSUE TITLE
scapy 2.5.0rc1 and 2.4.5 do not support cryptography versions >= 38.0

### ISSUE THREAD

**Issue by dijital20** [secdev/scapy#3749]
### Brief description

The pkcs1 module appears to be accessing the register_interface API, which has been removed in cryptography 38.

This does not occur if you force cryptography to a version below 38, but the following advisory from [pipenv check](https://docs.pipenv.org/advanced/#detection-of-security-vulnerabilities) will very quickly force me to need to upgrade:

> 51159: cryptography <39.0.0 resolved (37.0.0 installed)!
> Cryptography 39.0.0 drops support for C library "LibreSSL" < 3.4, as these versions are not receiving security support anymore.

### Scapy version

2.4.5 (also 2.5.0rc1)

### Python version

3.10

### Operating system

Windows 10

### How to reproduce

1. Install `scapy` 2.4.5 (or 2.5.0rc1).
2. Install `cryptography` 38.0.1
3. Launch the REPL and try:
  ```python
from scapy.layers.tls.all import TLS, SSLv2
```

### Actual result

```
AttributeError: module 'cryptography.utils' has no attribute 'register_interface'. Did you mean: 'verify_interface'?
```

### Expected result

Import works without issue.

**Comment by gpotter2** [comment]
Hi, this is already fixed on master since https://github.com/secdev/scapy/commit/bb1ed01d469a2b155910f4b689cb1d0c7837225e

**Comment by dijital20** [comment]
When will this be fixed in a release?

**Comment by guedou** [comment]
I just tagged and published https://pypi.org/project/scapy/2.5.0rc2/
