### ISSUE TITLE
SOMEIP / SD - the sub_id field is altering the value of the method/event id

### ISSUE THREAD

**Issue by public-src-code** [secdev/scapy#3750]
### Brief description

The field **sub_id** is only used to differentiate between **METHOD_ID** and **EVENT_ID**.
The value of the METHOD/EVENT id should still be calculated on 16bits and not on 15bits
This makes the usage for the end user more complex.
example:
event id = 0x8100 is dissected: sub_id=EVENT_ID, event_id=0x100
event id = 0xa100 is dissected: sub_id=EVENT_ID, event_id=0x2100

The users have to take scapy logic into consideration and this makes the usage more complex.
Is it possible to check the first bit without moving the offset and then read the value of the method/event id on 16bit?

### Scapy version

all

### Python version

any

### Operating system

any

### How to reproduce

frame = Ether(raw(payload))
print(frame)

The payload is a list of bytes from Wireshark.

**Comment by polybassa** [comment]
Thanks for your request. Could you please provide a reference to the standard, which describes the usage of the MSB to distinguish between EVENT_ID and MEHTOD_ID

**Comment by HousInfo** [comment]
The current implementation is following the requirement
[AUTOSAR_PRS_SOMEIPProtocol.pdf](https://www.autosar.org/fileadmin/user_upload/standards/foundation/21-11/AUTOSAR_PRS_SOMEIPProtocol.pdf)
section 4.1.2.2 and 4.1.2.3

But users are always focusing on the fact that Message ID = (Service ID / Method ID) [32 bit] (= 0xFFFF 8100 )
https://www.autosar.org/fileadmin/user_upload/standards/foundation/1-2/AUTOSAR_PRS_SOMEIPServiceDiscoveryProtocol.pdf
section 4.1.2.1 / Figure 4.1: SOME/IP-SD Header Format
and
_[PRS_SOMEIPSD_00152] d Service Discovery messages shall use the Method-ID (16
Bits) of 0x8100._

**Comment by polybassa** [comment]
I don't see a simple solution to make your change possible in Scapy. 

One possibility would be, to remove the field "event_id" or "method_id" entirely and only support one or the other. 

In this way, you obtain one 16bit wide field. This sub_id field could be removed. Is this a desired change, in your opinion?

**Comment by gpotter2** [comment]
@polybassa Hi, what's the state of this issue?
