### ISSUE TITLE
Sending ARP packet while using PCAP on Mac OS hangs (i.e. doesn't return)

### ISSUE THREAD

**Issue by summerlinryan** [secdev/scapy#3762]
### Brief description

Sending ARP packet while using PCAP on Mac OS freezes. The srp1() call is what freezes and after debugging stepping into the library, it seems the following select call in the `automation.py` scapy file is what's hanging. 

```
if not WINDOWS:
        return select.select(inputs, [], [], remain)[0]
```

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Mac OS 12.2.1

### Additional environment information

I'm using PyCharm Professional Edition 2022.2.3 for development. I've tried running the script as sudo and that did not make a difference.

### How to reproduce

The following script can reproduce the issue in my environment. Of course the dst MAC address and psrc IPv4 will need to be valid for your environment. The "finishing sending packet" never logs.

```
from scapy.config import conf

conf.use_pcap = True

from scapy.layers.l2 import Ether, ARP
from scapy.sendrecv import srp1

packet = Ether(dst="0:1c:42:c3:9c:0") / ARP(op="is-at", psrc="192.168.4.1")
print('sending packet')
srp1(packet)
print('finished sending packet')
```

### Actual result

The srp1() hangs indefinitely.

### Expected result

srp1() call sends packet and returns first response.

**Comment by guedou** [comment]
This does not seem like a Scapy issue as I cannot reproduce the issue. Does the `arping` function work?

**Comment by luckman212** [comment]
@summerlinryan Did you ever figure this out? Having the same issue, scapy 2.5.0, macOS 13.4 on M1.

**Comment by gpotter2** [comment]
> @summerlinryan Did you ever figure this out? Having the same issue, scapy 2.5.0, macOS 13.4 on M1.

It's not like we didn't try. 2 maintainers got in touch asking questions and got no replies. And now you're not being useful at all by just saying "I have the same problem" and not answering those questions either.

Please open a new issue if required.
