### ISSUE TITLE
p0fv2 and p0f read from the same location.

### ISSUE THREAD

**Issue by nikhilnayak98** [secdev/scapy#3765]
### Brief description

The _p0fpaths in https://github.com/secdev/scapy/blob/master/scapy/modules/p0f.py#L27 and https://github.com/secdev/scapy/blob/master/scapy/modules/p0fv2.py#L31 are the same, hence in a scenario of using p0fv2 and p0fv3 this fails.

### Scapy version

2.5.0

### Python version

3.10

### Operating system

Ubuntu 22.04

### How to reproduce

`Have p0fv2 and p0fv3 signatures in /etc/p0f/p0f.fp`

### Expected result

```
Create separate _p0fpaths
for p0fv2  _p0fpaths = /etc/p0fv2
for p0f (which is basically p0fv3) _p0fpaths = /etc/p0fv3 or  /etc/p0f
```

**Comment by gpotter2** [comment]
By design. You're supposed to `apt install p0f` in which case the files end up here in both cases.
You can always replace `conf.p0f_base*`
