### ISSUE TITLE
[Windows] Unit tests

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#377]
Hey,
I'm trying to make the unit tests work on a windows computer, but the tests sticks on 
`failed C9EAA3A4 Automaton test same action for many conditions
`
So after some tests, the following make the unit tests never end:
```
Automaton test io event
Automaton test io event from external fd
```

After some researches, it appears that this:
`a.run(wait=False)`
causes the thing... setting wait to true will actually make the test fail (crash) but won't be stuck on it...

**Comment by guedou** [comment]
I am also working on this topic =)

See, my playground at https://github.com/guedou/scapy-appveyor/ More specifically, you might be interested in https://github.com/guedou/scapy-appveyor/blob/master/appveyor.yml that show the current unit tests being launched. 

I choose to disable automaton and mock unit tests. As of today, two unit tests are still failing in regression.uts see https://ci.appveyor.com/project/guedou/scapy-appveyor
Do you know how they can be fixed ?

**Comment by gpotter2** [comment]
Nice one, i'm gonna check that...

**Comment by gpotter2** [comment]
Oh yeah the first one is easy, replace this:
`get_if_raw_addr(conf.iface).encode("hex")`

 by this:

```
if WINDOWS:
    get_if_raw_addr(conf.iface.name).encode("hex")
else:
    get_if_raw_addr(conf.iface).encode("hex")
```

As interfaces are not working the same way on windows

**Comment by gpotter2** [comment]
And the other one works on my computer...

**Comment by gpotter2** [comment]
Apart from that, the other one is weird:
It crashed because this:
`conf.route.route("0.0.0.0")[2]`
shall definatly not return 

> '0.0.0.0'

On my computer:
```
>>> conf.route.route("0.0.0.0")[2]
'192.168.0.254'
```

Are you sure you got the latest version of the route file ? cause i know we did some changes not that long ago...

**Comment by guedou** [comment]
Do you know why `get_if_raw_hwaddr() `and `get_if_raw_addr()` works differently ? It looks weird. I think that we should fix this to have the same behaviors for the two functions.

On my Windows machine, independently of the routing issue`arping() `is broken.

**Comment by gpotter2** [comment]
Well on windows `get_if_raw_hwaddr` needed the "pcap_name" iface name, why is kinda different from the normal "name", so it definatly needs the conf.iface.

And the `get_if_raw_addr` isn't modified when running on windows...

**Comment by guedou** [comment]
Thanks for this detailed answer. I think that it is a better to change the way `get_if_raw_addr` currently works. Adding a Windows test [here](https://github.com/secdev/scapy/blob/d3d79785f662fe5b1c8ea80d5f0dbb0b31d60082/scapy/arch/pcapdnet.py#L78) and modyfing [this](https://github.com/secdev/scapy/blob/7ecb14818154254a846b047727b2fb29055c8254/scapy/arch/windows/__init__.py#L239) call seems enought.

What do you think ?

By the way, did you manage to reproduce the `arping` issue ?

**Comment by gpotter2** [comment]
Looks good.

And i'm not able to reproduce the issue... But i got 2 questions:

- Are you sure that you are on a /24 network ? what about appveyor ?
- Have you got all the depedencies installed ?

**Comment by gpotter2** [comment]
BTW, i've just noticed:
https://github.com/secdev/scapy/blob/d3d79785f662fe5b1c8ea80d5f0dbb0b31d60082/scapy/arch/pcapdnet.py#L95
This can be used as we do not support Python 2.5 anymore...

**Comment by guedou** [comment]
@gpotter2 does [this](https://github.com/guedou/scapy-appveyor/commit/ea7e3dfc00b8d80547d2745370a017d57a4c3d60) look good to you ?

**Comment by gpotter2** [comment]
Isn't pcapdnet used by something else than windows ?
Cause if yes, it won't work for them

**Comment by gpotter2** [comment]
Well [it](https://github.com/search?l=&q=get_if_raw_addr++user%3Asecdev+repo%3Ascapy&ref=advsearch&type=Code&utf8=%E2%9C%93)
looks ok. Looks fine for me
