### ISSUE TITLE
Site local address space has been deprecated？

### ISSUE THREAD

**Issue by jiuyuan-light** [secdev/scapy#3778]
In rfc4291, it seems that only Site Local IPv6 Unicast Addresses are abandoned?
Why is Site Local IPv6 Multicast Addresses also abandoned in the scapy (as shown in the figure)? 
![image](https://user-images.githubusercontent.com/89025318/200098769-16ee62c9-0140-4419-ba34-dad67c9262cf.png)

For example, the address ff05:: 1:3 mentioned in rfc8415 is valid? Please let me know if anyone knows the relevant information. Thank you very much.

**Comment by guedou** [comment]
This function test if an address is part of the site-local prefix. There is no need to remove it.

**Comment by jiuyuan-light** [comment]
Thank you for your reply, but I wonder if any rfc mentioned to discard "Site Local IPv6 Multicast Addresses" rather than "Site Local IPv6 Unicast Addresses"?
![image](https://user-images.githubusercontent.com/89025318/200116698-2e511f0a-12a7-4e33-87f8-53497c4ccd1f.png)
![image](https://user-images.githubusercontent.com/89025318/200117066-91b0f8ae-26df-49ba-a331-929b17b144f5.png)
The "send" call will report the error "no default route?" And the message cannot be sent. "sendp" reports an error, but the message can be sent. I expect that "send" can send multicast messages normally.
