### ISSUE TITLE
The dBm_AntNoise is None

### ISSUE THREAD

**Issue by 2076625923** [secdev/scapy#3789]
### Brief description

I can get the dBm_AntNoise value when I try to sniff my network interfaces(monitor mode) with scapy

### Scapy version

2.4.5

### Python version

3.8

### Operating system

ubuntu20.04

### How to reproduce

this is my code:
#!~/Project/python/venv/bin/python3
from scapy.all import *
from scapy.config import conf
from scapy.layers.dot11 import Dot11

conf.use_pcap = True

def call_back(pkg):
    if pkg.haslayer(Dot11):
        if pkg.type == 0 and pkg.subtype == 8:
            print("dBm_AntSignal=", pkg.dBm_AntSignal)
            print("dBm_AntNoise=", pkg.dBm_AntNoise)

interface = 'wlp1s1'
sniff(iface=interface, monitor='True', prn=call_back)

### Actual result

/home/chowhao/Project/python/venv/bin/python /home/chowhao/Project/python/snf/main/sniff4.py 
/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
  cipher=algorithms.Blowfish,
/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
  cipher=algorithms.CAST5,
Traceback (most recent call last):
  File "/home/chowhao/Project/python/snf/main/sniff4.py", line 18, in <module>
    sniff(iface=interface, monitor='True', prn=call_back)
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 1127, in _run
    sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 379, in __init__
    self.ins = open_pcap(iface, MTU, self.promisc, 100,
  File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 250, in __init__
    raise OSError("Could not activate the pcap handler", code)
OSError: [Errno Could not activate the pcap handler] -1

Process finished with exit code 1

### Expected result

something like this:
dBm_AntSignal -87
dBm_AntNoise= -89
dBm_AntSignal -83
dBm_AntNoise= -89

### Related resources

#!~/Project/python/venv/bin/python3
from scapy.all import *
from scapy.config import conf
from scapy.layers.dot11 import Dot11

conf.use_pcap = True

def call_back(pkg):
    if pkg.haslayer(Dot11):
        if pkg.type == 0 and pkg.subtype == 8:
            print("dBm_AntSignal=", pkg.dBm_AntSignal)
            print("dBm_AntNoise=", pkg.dBm_AntNoise)

interface = 'wlp1s1'
sniff(iface=interface, monitor='True', prn=call_back)

**Comment by guedou** [comment]
Your script received « OSError: [Errno Could not activate the pcap handler] -1 ». This is not likely related to Scapy.Please ask your question on gitter. This is a bug tracker, not a forum.Sent from my iPhoneOn 13 Nov 2022, at 08:33, 2076625923 ***@***.***> wrote:﻿
Brief description
I can get the dBm_AntNoise value when I try to sniff my network interfaces(monitor mode) with scapy
Scapy version
2.4.5
Python version
3.8
Operating system
ubuntu20.04
Additional environment information
No response
How to reproduce
this is my code:
#!~/Project/python/venv/bin/python3
from scapy.all import *
from scapy.config import conf
from scapy.layers.dot11 import Dot11
conf.use_pcap = True
def call_back(pkg):
if pkg.haslayer(Dot11):
if pkg.type == 0 and pkg.subtype == 8:
print("dBm_AntSignal=", pkg.dBm_AntSignal)
print("dBm_AntNoise=", pkg.dBm_AntNoise)
interface = 'wlp1s1'
sniff(iface=interface, monitor='True', prn=call_back)
Actual result
/home/chowhao/Project/python/venv/bin/python /home/chowhao/Project/python/snf/main/sniff4.py
/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/layers/ipsec.py:471: CryptographyDeprecationWarning: Blowfish has been deprecated
cipher=algorithms.Blowfish,
/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/layers/ipsec.py:485: CryptographyDeprecationWarning: CAST5 has been deprecated
cipher=algorithms.CAST5,
Traceback (most recent call last):
File "/home/chowhao/Project/python/snf/main/sniff4.py", line 18, in 
sniff(iface=interface, monitor='True', prn=call_back)
File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 1263, in sniff
sniffer._run(*args, **kwargs)
File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/sendrecv.py", line 1127, in _run
sniff_sockets[L2socket(type=ETH_P_ALL, iface=iface,
File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 379, in init
self.ins = open_pcap(iface, MTU, self.promisc, 100,
File "/home/chowhao/Project/python/venv/lib/python3.8/site-packages/scapy/arch/libpcap.py", line 250, in init
raise OSError("Could not activate the pcap handler", code)
OSError: [Errno Could not activate the pcap handler] -1
Process finished with exit code 1
Expected result
something like this:
dBm_AntSignal -87
dBm_AntNoise= -89
dBm_AntSignal -83
dBm_AntNoise= -89
Related resources
#!~/Project/python/venv/bin/python3
from scapy.all import *
from scapy.config import conf
from scapy.layers.dot11 import Dot11
conf.use_pcap = True
def call_back(pkg):
if pkg.haslayer(Dot11):
if pkg.type == 0 and pkg.subtype == 8:
print("dBm_AntSignal=", pkg.dBm_AntSignal)
print("dBm_AntNoise=", pkg.dBm_AntNoise)
interface = 'wlp1s1'
sniff(iface=interface, monitor='True', prn=call_back)
