### ISSUE TITLE
Documentation: Shell demo should not use ICMP without payload

### ISSUE THREAD

**Issue by vbrozik** [secdev/scapy#3790]
### Brief description

The *Shell demo* section in [`README.md`](https://github.com/secdev/scapy/blob/e3e843114c0bcc048290db6d1b94b53329310770/README.md#shell-demo) should not use ICMP echo request without a payload because such packets are likely to be blocked by a firewall. See for example:

* https://advisories.checkpoint.com/advisory/cpai-2004-20/
* https://forum.avast.com/index.php?topic=59992.0
* https://thwack.solarwinds.com/product-forums/network-performance-monitor-npm/f/forum/83445/8-5-1---null-payload-echo-request

I encountered this problem when I was checking if Scapy could be useful and I spend a lot of time figuring out if Scapy works at all. `ping` was working fine, Scapy was failing and I had to check what were all the differences. ICMP echo without payload is so rare that I was not aware of the problem.

I have almost gave it up rejecting Scapy as too unreliable or too difficult to set up correctly.

I suggest to add a payload to the demo code - for example:
``` python
>>> p = IP(dst="github.com")/ICMP()/Raw("payload")
```

### Scapy version

2.5

### Python version

3.10

### Operating system

Linux 5.10.102

### How to reproduce

See the docuemntation.

**Comment by guedou** [comment]
Thanks for your interest in Scapy. As you have probably figure out, we tested this example and it works fine most of the time.

The goal of this example is not to be 100% accurate but to be simple and concise.

Feel free to submit a PR to change the README. Yet, I will suggest to change ICMP() to TCP() to keep the example simple and concise.
