### ISSUE TITLE
What is the difference between padding() and nzpadding() ?

### ISSUE THREAD

**Issue by mjnd88** [secdev/scapy#3794]
```import scapy.all as scapy
pkt = scapy.sr(scapy.IP(src='192.168.1.1', dst='192.168.1.1')/scapy.Padding())

pkt[0].padding()
pkt[0].nzpadding()```

result:

```0000 13:20:44.712291 192.168.1.1 > 192.168.1.1 ip / Padding ==> 192.168.1.1 > 192.168.1.1 ip / Padding
0000 00 .
0000 13:20:44.712291 192.168.1.1 > 192.168.1.1 ip / Padding ==> 192.168.1.1 > 192.168.1.1 ip / Padding
0000 00```

what is the difference between padding() and nzpadding() ?

please don't close it without answering me i have been search for 4 days now

**Comment by mjnd88** [comment]
please answer me the difference between the two functions i get the same result from both functions what do you mean by non zero ? i assume that you mean only none empty padding layers but i do get empty layers when i use it and you say padding is for all none and not none padding layer please answer me thank you

**Comment by guedou** [comment]
This is not a forum, but a bug tracker. Stop harassing us with our question and ask it on gitter instead.
