### ISSUE TITLE
"FCS" type of Bug when using sendp()

### ISSUE THREAD

**Issue by stryngs** [secdev/scapy#3807]
### Brief description

When testing injection concepts I found a situation where Scapy informs the user from a hexstr() aspect that the FCS exists on the tail end of the frame.  This is further confirmed using show2() where the FCS is generated as well as the .build() technique.

When using sendp() and listening on a 3rd party node, the FCS is absent.

### Scapy version

2.5.0rc2

### Python version

3.10.6

### Operating system

Linux 6.0.6

### Additional environment information

The NIC used for injection as well as the NIC used for 3rd party sniffing were identical AWUS036NEH NICs.
phy1    wlan1mon        rt2800usb       Ralink Technology, Corp. RT2870/RT3070

### How to reproduce

def wiPeep():
    bList = [b'\x00\x01\x00']
    bStr = bytes()
    for i in range(1):
        bList.append(b'\xff')
    for b in bList:
        bStr += b
    return RadioTap()\
           /Dot11FCS(type = 0,
                     subtype = 8,
                     addr1 = 'ff:ff:ff:ff:ff:ff',
                     addr2 = macGw,
                     addr3 = macGw)\
           /Dot11Beacon()\
           /Dot11Elt(ID = 0,
                     info = essid,
                     len = len(essid))\
           /Dot11EltRates(rates = rates)\
           /Dot11EltDSSSet(channel = channel)\
           /Dot11Elt(ID = 5,
                     info = bStr)

macGw = 'aa:bb:cc:dd:ee:ff'
essid = 'testing'
rates = [2, 4, 11, 22, 12, 18, 24, 36]
channel = 6
f = wiPeep()
sendp(f, iface = 'wlan1mon')

### Actual result
```
hexstr(pkts[7], onlyhex = 1)
Out[13]: '00 00 12 00 2E 48 00 00 00 02 85 09 A0 00 F1 01 00 00 80 00 00 00 FF FF FF FF FF FF AA BB CC DD EE FF AA BB CC DD EE FF 00 00 00 00 00 00 00 00 00 00 64 00 00 00 00 04 41 45 53 31 01 08 02 04 0B 16 0C 12 18 24 03 01 06 05 04'
```

### Expected result
```
In [8]: hexstr(f, onlyhex = 1)
Out[8]: '00 00 09 00 02 00 00 00 10 80 00 00 00 FF FF FF FF FF FF AA BB CC DD EE FF AA BB CC DD EE FF 00 00 00 00 00 00 00 00 00 00 64 00 00 00 00 04 41 45 53 31 01 08 02 04 0B 16 0C 12 18 24 03 01 06 05 04 00 01 00 FF F0 A1 D4 E3'
```
### Related resources

I think I can assist in fixing this bug in a way that won't break other things, but I need to experiment as bit.  Slapping an FCS on the end of a frame for injection has been achieved in the past using 2.4.5 and below.

https://github.com/stryngs/packetEssentials/blob/main/SRC/packetEssentials/lib/utils.py#L31
https://github.com/stryngs/packetEssentials/blob/main/SRC/packetEssentials/lib/utils.py#L167
https://github.com/stryngs/packetEssentials/blob/main/SRC/packetEssentials/lib/utils.py#L207

I will do some testing using the above techniques and report back.

**Comment by stryngs** [comment]
When debugging this some of the upper layers ought be ignored.  Look at the above as:
```
Out[17]: 'FF FF FF FF FF FF AA BB CC DD EE FF AA BB CC DD EE FF 00 00 00 00 00 00 00 00 00 00 64 00 00 00 00 04 41 45 53 31 01 08 02 04 0B 16 0C 12 18 24 03 01 06 05 04 00 01 00 FF F0 A1 D4 E3'

In [18]: 'FF FF FF FF FF FF AA BB CC DD EE FF AA BB CC DD EE FF 00 00 00 00 00 00 00 00 00 00 64 00 00 00 00 04 41 45 53 31 01 08 02 04 0B 16 0C 12 18 24 03 01 06 05 04'
```
The missing piece is the DTIM and I suspect that forcing the FCS technique ought work.

**Comment by mspncp** [comment]
Innocent bystander comment: considering all the effort you put into this well written issue, it might be worth it to put just a little more effort into it and find a more  expressive title than just  "Scapy"?  :wink:

**Comment by stryngs** [comment]
@mspncp I didn't even realize I had done that.  Can't seem to edit title =/

**Comment by stryngs** [comment]
First interesting find is that this seems to have something to do with my laptop itself and not Scapy.  

To determine this I downgraded to a version I knew that works previously well with Injection.  On both the listening node (rpi) and the injection node (laptop) I flipped roles.  Each time the rpi sniffed a frame sent from the laptop the FCS issue exists.  Each time the laptop would sniff a frame sent from the Pi there was no FCS issue.

Further interesting is the layers of both received frames, they are the same:
```
scapy.layers.dot11.RadioTap,
 scapy.layers.dot11.Dot11,
 scapy.layers.dot11.Dot11Beacon,
 scapy.layers.dot11.Dot11Elt,
 scapy.layers.dot11.Dot11EltRates,
 scapy.layers.dot11.Dot11EltDSSSet,
 scapy.layers.dot11.Dot11Elt
 ```
 When looking at the frame that is to be sent:
 ```
 scapy.layers.dot11.RadioTap,
 scapy.layers.dot11.Dot11FCS,
 scapy.layers.dot11.Dot11Beacon,
 scapy.layers.dot11.Dot11Elt,
 scapy.layers.dot11.Dot11EltRates,
 scapy.layers.dot11.Dot11EltDSSSet,
 scapy.layers.dot11.Dot11Elt
```
 Somehow Dot11FCS turns to Dot11 on both injection nodes from a receive standpoint.  The laptop fails to include the same last four bytes though and so Wireshark correctly interprets it as a Malformed packet.  The Pi doesn't strip these out and even though the Dot11FCS is also turned to a Dot11, because the 4 bytes on the tail end make the math work, Wireshark correctly sees there is no FCS... but there should be.
 
My next step will be to try and force my laptop to send the extra four bytes and determine if there is a workaround.  I would go so far as to say "driver issues" but they are identical NICs, though the host OS arch is diff ofc.  Will definitely have to test with a second laptop.

**Comment by stryngs** [comment]
The workaround did indeed result in the expected scenario.  Calculate FCS for the frame (or cheat and just use .build()...) and slap on with Raw(load = b'your bytes here').

This does not solve the bug, but it does allow hardware that cuts the bytes to append them and make the frame work as expected.

The above being said, I think there are now two defined bugs:
- Some architectures chop the bytes, why unknown.
- Scapy transmissions are being received where Dot11FCS is converted to Dot11, confirmed in scapy and tcpdump.

More testing to follow shortly.

**Comment by stryngs** [comment]
Doing some pcap comparisons online I can see there are APs which use FCS and APs which don't.  My own AP which is running a type of dd-wrt does not use FCS.

That being said we can exclude caring about FCS by virtue of the fact that multiple examples on both sides exist.  We can further assume the client doesn't care (perhaps in odd circumstances, but no it would seem, FCS == optional).

When I did the flip of the source code provided above and changed Dot11FCS to Dot11, the byte chop stopped.  As both test nodes have the same output I am assuming this affects Dot11FCS only.  Somehow the arch is tied in but I do not know the root cause yet.

**Comment by gpotter2** [comment]
Having a FCS or not depends on your networks card (as you have probably figured by now). Not related to a scapy bug :p
