### ISSUE TITLE
Scapy reacts different from python3 to python2 and also in different versions of Scapy!!

### ISSUE THREAD

**Issue by thecowmilk** [secdev/scapy#3812]
### Brief description

I'm trying to build a packer sniffer using scapy but it is all turning into a mess!
To begin, I cannot decode scapy's tcp traffic. At this point I know that `HTTPS` is not supported yet but I thought I'd listen using this tool to different ports and protocols except `HTTP`.

When I was using this tool i saw something very strange, with `python2` scapy works very well but it lacks with `python3`. On scapy version 2.4.5 from `pypi` I see this output:
```
WARNING: Calling str(pkt) on Python 3 makes no sense!
b'l;k\x05MVP/\x9bo\x1fb\x08\x00E\x00\x01\xda\\\x94@\x00@\x06K\xf2\xc0\xa8\xfd\xca\xbc\xb8\x15l\xc5\x04\x00P\xbcp\x18\x04\xc5 F\xae\x80\x18\x01\xf6\x92d\x00\x00\x01\x01\x08\n}\xdf\x0bQ\x8b"\x0c\xca
```

and so I thought this would be fixed in the github version but it gets worse. Now in the github version I see only this:
```
Ether / IP / TCP / HTTP / 'GET' '/' 'HTTP/1.1'
```

For each request.

### Scapy version

2.4.5

### Python version

3.8

### Operating system

Linux

### How to reproduce

```
import scapy.all as scapy
from scapy.layers import http
import optparse

parser = optparse.OptionParser()
parser.add_option('-i', '--interface', dest='interface', help='Interface to be sniffed.')
opt, args = parser.parse_args()

sniff_interface = opt.interface

def sniff(interface):
    scapy.sniff(iface=interface, store=False, prn=packet_process)

def packet_process(packet):
    if packet.haslayer(http.HTTPRequest):
        print(packet)

sniff(sniff_interface)
```

I used this script to have those two outputs

### Related resources

Well one result I'd except is a request without gibberish data.

**Comment by gpotter2** [comment]
Please remain nice and read the doc.
