### ISSUE TITLE
Invalid return of `EnumField.i2repr` method

### ISSUE THREAD

**Issue by kamichal** [secdev/scapy#3828]
### Brief description

Implementation of `i2repr` for `EnumField` is incorrect. It doesn't call `repr(value)` after getting it from the enumerations mapping. It returns just the value of the mapping, not the repr of this value.

However - funny fact - if the value does not exist in the enumeration mapping, then the `repr(value)` is properly executed.

The bug is located in `scapy/fields.py` in method `i2repr_one` of `_EnumField` class:

```python
    def i2repr_one(self, pkt, x):
        # type: (Optional[Packet], I) -> str
        if self not in conf.noenum and not isinstance(x, VolatileValue):
            if self.i2s:
                try:
                    return self.i2s[x]  # <- THIS IS INCORRECT, THIS IS THE BUG, It should be return repr(self.i2s[x])
                except KeyError:
                    pass
            elif self.i2s_cb:
                ret = self.i2s_cb(x)
                if ret is not None:
                    return ret
        return repr(x)  # <- THIS IS CORRECT
```
To fix it - you just need to change the `return self.i2s[x]` into `return repr(self.i2s[x])`.

### Scapy version

2.4.5

### Python version

3.10

### Operating system

Linux 5.15.85

### How to reproduce

```python
from scapy.fields import ByteField, EnumField
from scapy.packet import Packet


class PacketWithEnum(Packet):
    fields_desc = [
        ByteField("num", 0),
        EnumField("val", None, {1: "First Enum", 2: "Second Enum"}, "B"),
    ]

p = PacketWithEnum(num=1, val=2)
reprs = [p.get_field(field_name).i2repr(None, value) for field_name, value in p.fields.items()]
assert reprs == ["1", "'Second Enum'"]   # this fails
```

### Actual result

`["1", "Second Enum"] `

### Expected result

`["1", "'Second Enum'"] `

For the first element, we get `<type: str>`, `"1"`, which is a valid `__repr__` of an integer.
For the second one we also get `str`, but without quotes, which is invalid `__repr__` of a string `"Second Enum"`.

Expected result for the second element is `"'Second Enum'"` as `__repr__` is supposed to work.

**Comment by gpotter2** [comment]
This is a choice we made, i.e. by-design.

It's prettier to have:
```
>>> p.show()
###[ PacketWithEnum ]###
  num       = 1
  val       = Second Enum
```

**Comment by kamichal** [comment]
But it's not how `__repr__` is supposed to work. Btw, why is the `repr(x)` called at the end of the function? It's inconsistent and it's a bug. Once you call it, once not.

Furthermore, as you noticed. The only one, questionable downside of fixing it would be result of `.show()` command:
```
###[ PacketWithEnum ]### 
  num       = 1
  val       = 'Second Enum'
```
