### ISSUE TITLE
Answers and IP in IP

### ISSUE THREAD

**Issue by johnarnold** [secdev/scapy#383]
Hi,

Using IP in IP packets is a useful way to "route" packets across specific paths in a network. I'm sending IP+ICMP packets with an IP in IP (ip protocol 4) wrapper, and getting the ICMP response back according to tcpdump:

```
19:10:40.158647 IP (tos 0x0, ttl 255, id 1, offset 0, flags [none], proto IPIP (4), length 48)
    10.20.30.93 > 10.0.99.1: IP (tos 0x0, ttl 255, id 1, offset 0, flags [none], proto ICMP (1), length 28)
    10.20.30.93 > 10.20.0.207: ICMP echo request, id 0, seq 1, length 8
19:10:40.228185 IP (tos 0x0, ttl 48, id 26655, offset 0, flags [none], proto ICMP (1), length 28)
    10.20.0.207 > 10.20.30.93: ICMP echo reply, id 0, seq 1, length 8
```

However, the response doesn't match so I don't get an "answer" when using `srp()`.  Is there any way to "ignore" the ip-in-ip layer when calculating the hashret(), or otherwise "make it match"?

Thanks,
John

**Comment by p-l-** [comment]
Can you check if #387 works for you? You'll have to add `conf.checkIPinIP = False` before using `sr()`.

**Comment by johnarnold** [comment]
Hi,

Thanks for making this change.  Code makes sense.

I patched in the change, and set conf.checkIPinIP = False.   Unfortunately it's not working.  Basic debugging shows that it's executing this part:

        elif not conf.checkIPinIP and self.proto == 4:  # IPIP
            return self.payload.hashret()

but not any clause in this part:

        elif not conf.checkIPinIP:  # IPIP
            if self.proto == 4:
                return self.payload.answers(other)
            if other.proto == 4:
                return self.answers(other.payload)

**Comment by johnarnold** [comment]
Looks like it's matching on

        if conf.checkIPaddr:
            if other.dst == "224.0.0.251" and self.dst == "224.0.0.251":  # mDNS
                return self.payload.answers(other.payload)
            elif (self.dst != other.src):
                return 0

and it never gets to

        elif not conf.checkIPinIP:  # IPIP

**Comment by johnarnold** [comment]
Can confirm, re-ordering the clauses fixes it:

    def answers(self, other):
        if not isinstance(other,IP):
            return 0
        if not conf.checkIPinIP: #IPIP
            if self.proto == 4:
                return self.payload.answers(other)
            if other.proto == 4:
                return self.answers(other.payload)
        if conf.checkIPaddr:
            if other.dst == "224.0.0.251" and self.dst == "224.0.0.251":  # mDNS
                return self.payload.answers(other.payload)
            elif (self.dst != other.src):
                return 0
        if ( (self.proto == socket.IPPROTO_ICMP) and
             (isinstance(self.payload, ICMP)) and
             (self.payload.type in [3,4,5,11,12]) ):
            # ICMP error message
            return self.payload.payload.answers(other)
        else:
            if ( (conf.checkIPaddr and (self.src != other.dst)) or
                 (self.proto != other.proto) ):
                return 0
            return self.payload.answers(other.payload)

**Comment by p-l-** [comment]
I don't get it, how is that different from what is actually in the PR?

**Comment by johnarnold** [comment]
Ah, I think that was my bad -- I think *I* patched it in out of order the first time.  More coffee required. Carry on, works fine as written.   Thanks!

**Comment by johnarnold** [comment]
Probably should add checkIPinIP to the docstring for class Conf() as well.

**Comment by p-l-** [comment]
@johnarnold if I understand what you mean correctly, that's already done in the PR.
