### ISSUE TITLE
Cannot use the pdfdump() feature : display/X server issue

### ISSUE THREAD

**Issue by PauloHeaven** [secdev/scapy#3835]
### Brief description

When I try to dump the content of a packet graphically, it works with PostScript, but when I try with PDF (`var.pdfdump(layer_shift=1)`), it fails.

With a comprehensive research, I came accross several reasons such an error can be encountered. I tried to add another cookie with the `xauth add` command. I read that the root user could be missing some settings some programs need, as opposed to a regular user. I found a way to add some information to the X server init file, but Ubuntu now is on Wayland, and I didn't find any equivalent.

### Scapy version

2.5.0rc2

### Python version

3.10

### Operating system

Ubuntu 22.04

### Additional environment information

This is a virtual machine, with Ubuntu 22.04. I installed Scapy and PyX with pip. Everything is up-to-date.

As far as the network configuration, 2 NICs are set up on this machine: the first one is on VB's internal network, to talk to a server I use to experiment with DNS, Active Directory and many other services. The server was shut down at the moment. The second one is a bridged interface. This is the one that is used to access internet and receives IP addresses and DNS via DHCP and RA for IPv6. The machine can properly access Internet.

2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000

    link/ether 08:00:27:6c:9d:27 brd ff:ff:ff:ff:ff:ff
    inet 192.168.108.135/23 brd 192.168.109.255 scope global noprefixroute enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::9f65:7e71:242f:a8f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000

    link/ether 08:00:27:f3:e2:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.20/24 brd 192.168.1.255 scope global dynamic noprefixroute enp0s8
       valid_lft 82226sec preferred_lft 82226sec
    inet6 2a01:cb04:17d:xxxx:xxxx:38d2:ab48:ea9b/64 scope global temporary dynamic 
       valid_lft 86397sec preferred_lft 597sec
    inet6 2a01:cb04:17d:xxxx:xxxx:8db5:83c8:c1f0/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 86397sec preferred_lft 597sec
    inet6 fe80::8127:314b:600:40ac/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

### How to reproduce

1. Assigning any PDU to a variable, like for example what I did last, which is listening to the answer to a TCP segment I sent to a server:
```
>>> b = IPv6(src="2a01:cb04:17d:xxxx:xxxx:38d2:ab48:ea9b", dst="milkywan.fr")/TCP(sport=53477, dport="https")/"GET /services/ HTTP/2.0 \n\n"

>>> rep = sr1(b)

Begin emission:

Finished sending 1 packets.

*

Received 1 packets, got 1 answers, remaining 0 packets

>>>
```
2. Checking whether the answer is relevant
```
>>> rep.show2()

###[ IPv6 ]### 

  version   = 6

  tc        = 0

  fl        = 561749

  plen      = 24

  nh        = TCP

  hlim      = 51

  src       = 2a0b:xxxx:xxxx:14::1

  dst       = 2a01:cb04:xxxx:xxxx:e4f4:38d2:ab48:ea9b

###[ TCP ]### 

     sport     = https

     dport     = 53477

     seq       = 3900642932

     ack       = 1

     dataofs   = 6

     reserved  = 0

     flags     = SA

     window    = 64800

     chksum    = 0x7f54

     urgptr    = 0

     options   = [('MSS', 1440)]


```
3. Attempt exporting it to PDF:
```
>>> rep.pdfdump(layer_shift=1)

/usr/lib/python3.10/subprocess.py:1070: ResourceWarning: subprocess 16757 is still running

  _warn("subprocess %s is still running" % self.pid,

ResourceWarning: Enable tracemalloc to get the object allocation traceback



>>> Authorization required, but no authorization protocol specified

Cannot parse arguments: Cannot open display :
```

### Actual result

With extensive testing, it works when I run Scapy as a regular user. There is still a warning message:

```
>>> b.pdfdump(layer_shift=1)

/usr/lib/python3.10/subprocess.py:1070: ResourceWarning: subprocess 16492 is still running

  _warn("subprocess %s is still running" % self.pid,

ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

but the PDF is indeed created and it opens right up afterwards.

The problem is I can export PDFs, but I can't do anything with the network, as that requires elevated privileges. So this is more or less useless for my use cases as such.

When I run Scapy as root, this happens:

```
>>> rep = sr1(b)

Begin emission:

Finished sending 1 packets.

.*

Received 2 packets, got 1 answers, remaining 0 packets

>>> rep.pdfdump(layer_shift=1)

/usr/lib/python3.10/subprocess.py:1070: ResourceWarning: subprocess 16566 is still running

  _warn("subprocess %s is still running" % self.pid,

ResourceWarning: Enable tracemalloc to get the object allocation traceback



>>> Authorization required, but no authorization protocol specified

Cannot parse arguments: Cannot open display :
```

It stays like that indefinitely, until one presses Enter. Ctrl+C doesn't work.

### Expected result

I don't know what the expected result would look like exactly, but according to the way the psdump() function works, there should be no error message and the file should open automatically.

**Comment by tinyhare** [comment]
is the **ResourceWarning: subprocess 16566 is still running**  a problem？

I also see it when I use sniff  with **offline** and **filter** argument the same time

```
>>> packets = sniff(offline='test.pcap', filter="tcp")
/usr/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 1525002 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
reading from file test.pcap, link-type EN10MB (Ethernet)
>>> packets
<Sniffed: TCP:2 UDP:0 ICMP:0 Other:0>
>>> 
```

**Comment by PauloHeaven** [comment]
Hello, sorry for the late answer. Yes, I still run into this exact issue.

**Comment by gpotter2** [comment]
Not a Scapy bug (but some X configuration issue).
