### ISSUE TITLE
FlagsField example with dict is incorrect/misleading

### ISSUE THREAD

**Issue by BrianSipos** [secdev/scapy#3839]
The example use of dict names in the [FlagsField docs](https://scapy.readthedocs.io/en/latest/api/scapy.fields.html#scapy.fields.FlagsField) implies that the dict keys are bit masks for each flag, but the actual use are bit _position_ index (zero being the LSbit). It would be helpful if the docs made this more clear, and if the example agreed with the use (e.g. instead of masks `0x0001` and `0x0008` they should be positions '0' and '3' respectively).

**Comment by gpotter2** [comment]
Are you using Scapy 2.5.0? This behavior changed

**Comment by gpotter2** [comment]
Closed for inactivity
