### ISSUE TITLE
Scapy 2.5.0 not detecting some packets

### ISSUE THREAD

**Issue by Javinator9889** [secdev/scapy#3844]
### Brief description

After upgrading to Scapy `2.5.0` some packets are not being detected while performing some reading. In this case, the scenario we are testing (Scapy runs inside a test environment) is a simple DHCP scenario with some DHCP options defined on the server side.

Scapy was used to analyze captured packets and to make sure expected options are in there. The options we currently got are:

```python
('message-type', 2)
('server_id', '192.168.1.1')
('lease_time', 30)
('subnet_mask', '255.255.255.0')
('time_zone', 7200)
('router', '192.168.1.1')
('domain', b'my.business')
('name_server', '192.168.1.1')
(119, b'\x03dev\x02my\x08business\x00')
('NetBIOS_server', '192.168.1.77')
('classless_static_routes', ['192.168.2.0/24:192.168.1.1'])
(249, b'\x18\xc0\xa8\x02\xc0\xa8\x01\x01')
('capwap-ac-v4', '192.168.1.22')
('POP3_server', '192.168.1.55')
('SMTP_server', '192.168.1.66')
('NIS_domain', b'nis.my.business')
('NIS_server', '192.168.1.44')
('NISplus_domain', b'nisplus.my.business')
('NISplus_server', '192.168.1.88')
('boot-file-name', b'hugo')
(252, b'http://proxy.my.business')
('tftp_server_name', b'tftp.my.business')
('tftp_server_address', '192.168.1.99')
(120, b'\x00\x07example\x03net\x00\x07example\x03com\x00')
```

Nevertheless, there is a missing option `121` which was present when running with the previous version of Scapy:

```python
(121, b'\x18\xc0\xa8\x02\xc0\xa8\x01\x01')
```

**Note** - the options above are obtained using the following code snippet:

```python
dhcp = pkt["Ether"]["IP"]["UDP"]["BOOTP"]["DHCP"]
# match DHCP offer and ack from server
if dhcp.options[0][1] in {2, 5}:
    # print out dhcp options, the interesting options are tuples
    for option in dhcp.options:
        if isinstance(option, tuple):
            print(option)
```

There have been no changes either on DHCP application or DHCP client or infrastructure (apart from upgrading Scapy).

### Scapy version

2.5.0

### Python version

3.11.1

### Operating system

Debian Bullseye 11.6

### Additional environment information

![image](https://user-images.githubusercontent.com/25952165/211503275-d044a8aa-9880-4ca9-b3c6-45ee339af65c.png)

### How to reproduce

1. Create a DHCP server with a bunch of options but in particular, the `121` option that defines a Classless Static Route.
2. Capture the traffic using `tshark` for further analysis with Scapy.
3. Look for the key `121` inside the captured data for the DHCP options.

### Actual result

No option for key `121`

### Expected result

Key `121` contains bytes `\x18\xc0\xa8\x02\xc0\xa8\x01\x01`

### Related resources

[dhcp_options.pcap.zip](https://github.com/secdev/scapy/files/10380717/dhcp_options.pcap.zip)
![image](https://user-images.githubusercontent.com/25952165/211504311-6ed6692f-4fa4-44cc-b72f-ed17de59ab4b.png)

**Comment by evverx** [comment]
Looks like `121` turned into `classless_static_routes` because of https://github.com/secdev/scapy/commit/f5b718881441637e9f8cab75515981b32247f707. In this particular case
```
(121, b'\x18\xc0\xa8\x02\xc0\xa8\x01\x01')
```
was replaced with
```
('classless_static_routes', ['192.168.2.0/24:192.168.1.1'])
```
as far as I can see.

**Comment by Javinator9889** [comment]
Oh, I see! Thanks for the fast response. As you're in here, do you know if there's a kind of "standard" way to access such properties to avoid having potentially the same problem in the future? Because this has been a situation we had some time ago but I didn't realize it was likely the same as this one.

**Comment by evverx** [comment]
> do you know if there's a kind of "standard" way to access such properties to avoid having potentially the same problem in the future?

Not that I know of but it should probably look a lot like [`DHCPOptionsField.i2m`](https://github.com/secdev/scapy/blob/0ea948f2e7651ddfff6019a9d2833f964f8b7cfc/scapy/layers/dhcp.py#L472) (where the `DHCPRevOptions` dictionary is used to handle dhcp options if they aren't numbers).

**Comment by p-l-** [comment]
Since the initial question has been answered, I'll close this issue. Thanks @evverx for finding the issue!
