### ISSUE TITLE
scapy fuzz does not fuzz a custom protocol

### ISSUE THREAD

**Issue by Everlastdg** [secdev/scapy#3849]
### Brief description

While fuzzing a custom protocol the copy attribute is lacking

File "pathname/scapy/packet.py", line 2499, in fuzz
p = p.copy()
AttributeError: 'XXX' object has no attribute 'copy'

### Scapy version

2.5

### Python version

3.9.6

### Operating system

MacOS Monterey 12.6

### Additional environment information

I have a protocol XXX, defined as:

class XXX(Packet):
    name = "XXX"
    field_descr = [ XByteField("message", 0), 
                    XByteField("message2", 1)]

File "pathname/scapy/packet.py", line 2499, in fuzz
p = p.copy()
AttributeError: 'XXX' object has no attribute 'copy'

Also tried with dpkt and the result was the same
class XXX(dpkt.Packet):
    __hdr__ = (
        ('message'B', 0),
        ('other_message', 'B', 0),
    )

### How to reproduce

from scapy.all import *

class AAA(Packet):
    name = "AAA"
    field_descr = [ XByteField("message", 0), 
                    XByteField("message2", 1)]

def aaa():
    print("Start fuzzing aaa")
    while True:
        p = raw(fuzz(AAA()))
        try:
            AAA(p)
            AAA(p).show()
        except Exception as e:
            AAA(p).show()
            raise e

aaa()

### Actual result

File "pathname/scapy/packet.py", line 2499, in fuzz
p = p.copy()
AttributeError: 'XXX' object has no attribute 'copy'

### Expected result

Fuzzing machine goes brrrr

**Comment by evverx** [comment]
> field_descr = ...

`field_descr` should be replaced with `fields_desc`: https://scapy.readthedocs.io/en/latest/build_dissect.html#simple-example

**Comment by Everlastdg** [comment]
you were right about both, no need to use dpkt at all actually, while the fields_desc solves the issue

**Comment by gpotter2** [comment]
Thanks a lot evverx
