### ISSUE TITLE
FlagsField behavior changed in v2.5.0

### ISSUE THREAD

**Issue by reprographix** [secdev/scapy#3850]
### Brief description

In pre-2.5.0, Scapy FlagsFields dicts were using bit indexes (starting at 0). In 2.5.0 this behavior has changed, dicts keys are now the flags values (0 becomes 1, 1 becomes 2, 2 becomes 4, and so on).

I'm not against this change of behavior, but this hasn't been documented properly anywhere since the introduction of the change, so before updating my code base I was wondering if FlagsField is going to continue as-is, or is going to get rollback to the previous behavior?

### Scapy version

2.5.0

### Python version

3.8

### Operating system

Ubuntu 20.04 LTS

### How to reproduce

Write a field description using FlagFields similar to this one:

```python
class MyCustomField(FlagsField):
    def __init__(self, name, default):
        super().__init__(name, default, 8, {
            0: "foo",
            1: "bar",
        })
```

### Actual result

```
.venv/lib/python3.8/site-packages/scapy/fields.py:3032: in __init__
     tmp[int(math.floor(math.log(i, 2)))] = v
 E   ValueError: math domain error
```

**Comment by gpotter2** [comment]
Hi,
You are right, the behavior did change and we didn't really document it. Sorry about that !

To be fair the previous behavior wasn't really documented either, but it was also trash. It did not bring much feature-wise compared to using a list of flags (you can still do `["A", "B", "C"...]` or `"ABC"`). No real life RFC gives info on flags as "its the 1st bit", and it was confusing some people, so we switched to the new approach which is much closer to what can be found in actual RFCs. Another think is that the support for dictionaries in `FlagsField` is relatively new (Scapy-speaking), so I felt that it was acceptable to trash it.

To give a real life example, it makes a lot of sense for something like this:

[FileFsAttributeInformation](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/ebc7e6e5-4650-4e54-b17c-cf60f6fbeeaa#Appendix_A_Target_138)
![image](https://user-images.githubusercontent.com/10530980/212379843-143ad5ca-00ce-4673-94d3-1fa6a207730d.png)

to be written as:
```
class FileFsAttributeInformation(Packet):
    fields_desc = [
        FlagsField("FileSystemAttributes", 0x80000f, -32, {
            0x02000000: "FILE_SUPPORTS_USN_JOURNAL",
            0x01000000: "FILE_SUPPORTS_OPEN_BY_FILE_ID",
            0x00800000: "FILE_SUPPORTS_EXTENDED_ATTRIBUTES",
            0x00400000: "FILE_SUPPORTS_HARD_LINKS",
            0x00200000: "FILE_SUPPORTS_TRANSACTIONS",
            0x00100000: "FILE_SEQUENTIAL_WRITE_ONCE",
            0x00080000: "FILE_READ_ONLY_VOLUME",
            0x00040000: "FILE_NAMED_STREAMS",
            0x00020000: "FILE_SUPPORTS_ENCRYPTION",
            0x00010000: "FILE_SUPPORTS_OBJECT_IDS",
            0x00008000: "FILE_VOLUME_IS_COMPRESSED",
            0x00000100: "FILE_SUPPORTS_REMOTE_STORAGE",
            0x00000080: "FILE_SUPPORTS_REPARSE_POINTS",
            0x00000040: "FILE_SUPPORTS_SPARSE_FILES",
            [...]
```

> FlagsField is going to continue as-is

Yup. This should be final !

**Comment by gpotter2** [comment]
I added this as a breaking change to the [2.5.0 changelog](https://github.com/secdev/scapy/releases/tag/v2.5.0).

**Comment by reprographix** [comment]
Hi,

Thanks for the clarification, I'll update my code to go with the 2.5.0 way.

I'm not agreeing however with `No real life RFC gives info on flags as "its the 1st bit"`: I'm coming from the EE world where it's nearly always the case, see https://www.onsemi.com/pdf/datasheet/fusb301-d.pdf, page 8 as an example. With that said, I think it's perfectly fine to describe bit flags with either methods, as long as we settle on one :smiley:

**Comment by gpotter2** [comment]
Oh hey you're right ^^ I guess I'm biased by what RFCs I usually look at.
Thanks for your understanding !

**Comment by CAoTx** [comment]
How could I achieve the old behavior? 
Tried this implementation, but does not the trick:

```python
class ZeroBasedFlagsField(FlagsField):
    def __init__(self, name, default, size, names):
        # Add a dummy flag at the start of the list to shift all the other flags by one
        names = [] + names
        super().__init__(name, default, size, names)

    def i2repr_one(self, pkt, x):
        # Shift the bit position back by one when displaying the flag
        return super().i2repr_one(pkt, x - 1)
```

I thought i could circumvent that behavior with an dict, where the values (also 0x0) are specified, like here:
```python
F_CODE_TYPES = {
    0x0: "0x0 - Process data (16-bit)",
    0x1: "0x1 - Process data (32-bit)",
    0x2: "0x2 - Process data (64-bit)",
    0x3: "0x3 - Process data (128-bit)",
    0x4: "0x4 - Process data (256-bit)",
    0x5: "0x5 - Process data (512-bit)",
    0x6: "0x6 - Process data (1024-bit)",
    0x7: "0x7 - Process data (2048-bit)",
    0x8: "0x8 - Process data (4096-bit)",
    0x9: "0x9 - Process data (8192-bit)",
    0xa: "0xa - Process data (16384-bit)",
    0xb: "0xb - Process data (32768-bit)",
    0xc: "0xc - Process data (65536-bit)",
    0xd: "0xd - Process data (131072-bit)",  
    0xe: "0xe - Process data (262144-bit)", 
    0xf: "0xf - Process data (524288-bit)" 
}
class xy(Packet):
    name = "xy packet"

    fields_desc = [
        FlagsField(name='f_code', default=0x0, size=4, names=F_CODE_TYPES),
        ...
    ]
```
But this does not work, it does somehow not accept this dict. 
When I use a list like this:
```python
F_CODE_TYPES = [
    "0x0 - Process data (16-bit)",
    "0x1 - Process data (32-bit)",
    "0x2 - Process data (64-bit)",
    "0x3 - Process data (128-bit)",
    "0x4 - Process data (256-bit)",
    "0x5 - Process data (512-bit)",
    "0x6 - Process data (1024-bit)",
    "0x7 - Process data (2048-bit)",
    "0x8 - Process data (4096-bit)",
    "0x9 - Process data (8192-bit)",
    "0xa - Process data (16384-bit)",
    "0xb - Process data (32768-bit)",
    "0xc - Process data (65536-bit)",
    "0xd - Process data (131072-bit)",  
    "0xe - Process data (262144-bit)", 
    "0xf - Process data (524288-bit)" 
]
```
The Flagsfield does accept the list, but the index is off (starts with 1).
Additionally, as soon as the value is higher than 4 (extends 1 bit), it combines several entries, so 0x5 becomes:
```bash
f_code    = 0x0 - Process data (16-bit)+0x2 - Process data (64-bit)
```

@gpotter2 could you help / explain here?

**Comment by gpotter2** [comment]
You're looking for an Enum field, not a Flags field.
bit 0 on a flags field makes no sense.
