### ISSUE TITLE
TypeError: IPint.__init__() got an unexpected keyword argument 'dst'

### ISSUE THREAD

**Issue by Artemis-Arrow** [secdev/scapy#3855]
### Brief description

the line causing the issue is
`pkt = sr1(IP(dst=target)/TCP(sport=sport, dport=port, flags="S"), timeout=1, verbose=0)`
the error message is
`TypeError: IPint.__init__() got an unexpected keyword argument 'dst'`
had to post it here cause gitter is barely active

### Scapy version

2.5.0

### Python version

3.10.9

### Operating system

Garuda Linux

### How to reproduce

`pkt = sr1(IP(dst=target)/TCP(sport=sport, dport=port, flags="S"), timeout=1, verbose=0)`

### result

`TypeError: IPint.__init__() got an unexpected keyword argument 'dst'`

### Note
this issue is only occuring in scripts, I can do everything normally from interactive shell, in scripts I can do `ip = IP(data='192.168.1.1')` without issues, in interactive shell that will return an error, also in scripts I can't do ip.show() for some reason
what is going on here?

**Comment by gpotter2** [comment]
How did you install scapy?
Please at least give the full stack trace (but there is no such thing as `IPint` in scapy so it's a bad start)

**Comment by evverx** [comment]
> this issue is only occuring in scripts

My guess would be that some other module provides `IP` and that module is probably imported after `scapy` with something like `from module import *`.

**Comment by Artemis-Arrow** [comment]
> My guess would be that some other module provides IP and that module is probably imported after scapy with something like from module import *.

I'm only importing scapy with `from scapy.all import *`



> How did you install scapy? Please at least give the full stack trace (but there is no such thing as `IPint` in scapy so it's a bad start)

`sudo pip install scapy`

**Comment by gpotter2** [comment]
Most likely you are using an external script that overwrites `IP`. Anyways this isn't a Scapy bug so please use the gitter or ask your question on stackoverflow.
