### ISSUE TITLE
Variable used before assignment 

### ISSUE THREAD

**Issue by alexpyattaev** [secdev/scapy#3856]
There is a problem in error handling for restart() function in scapy/utils.py, where res_code may be undefined in the finally clause

https://github.com/secdev/scapy/blob/9a2a3819c2834aabcde87d80dd1ed1a707b95e6a/scapy/utils.py#L239-L250
Very trivial bug, probably no big deal, but still good to fix.

A similar issue exists in scapy/arch/linux.py, where the try block does not have a blanket except, which can cause similar problems with crash at line 143.
https://github.com/secdev/scapy/blob/9a2a3819c2834aabcde87d80dd1ed1a707b95e6a/scapy/arch/linux.py#L133-L150

**Comment by gpotter2** [comment]
Hi, thanks for the report. Do you have reproducible examples that can trigger these kind of bugs? (or are you using a tool to generate those reports).

**Comment by mspncp** [comment]
In theory, the first report  (i.e., `res_code` is used before assignment) would be valid if `subprocess.call()` could fail with an unhandled exception.

https://github.com/secdev/scapy/blob/9a2a3819c2834aabcde87d80dd1ed1a707b95e6a/scapy/utils.py#L246

It is not obvious from static code analysis whether this can happen, but looking at the implementation of `suprocess.call()` it seems that this is not the case.

- [subprocess.call()](https://github.com/python/cpython/blob/main/Lib/subprocess.py#L381-L395)
- [subprocess.Popen.wait()](https://github.com/python/cpython/blob/main/Lib/subprocess.py#L1257-L1278)
- [subprocess.Popen._wait()](https://github.com/python/cpython/blob/main/Lib/subprocess.py#L1535-L1548)

I agree with @gpotter2 that the second report is a mistake: if the open() command fails the function exits either with an uncaught exception or returns in line  141. In either case, line 142 is unreached.

**Comment by mspncp** [comment]
BTW: the code in `_get_if_list()` appears unnecessarily complicated. See #3859.

**Comment by alexpyattaev** [comment]
For the first case:
``` Python
try:
    res=subprocess.call("/bin/blobZ")
except KeyboardInterrupt:
    print("kbd")
finally:
    print(res)
```
results in NameError: name 'res' is not defined
which is clearly odd and not what was intended in the code=)

For the second case, python's open function actually raises OSError (as of python3.11)
https://docs.python.org/3/library/functions.html#open
It so happens that OSError is not an instance of IOError. 
```python
>>> isinstance(OSError, IOError)
False
```

As a result, the function in second case would simply crash instead of doing any cleanup whatsoever (i.e. the entire try/except thing is doing nothing).

These reports are both by-products of compilation with nuitka (I used it for performance more than for static analysis, just figured it would be nice to get these bugs addressed).  Naturally, I have validated both cases manually to be legitimate before posting.

**Comment by gpotter2** [comment]
Do you mean
```
>>> issubclass(OSError, IOError)
True
```

> Naturally, I have validated both cases manually to be legitimate before posting.

Would you mind sharing your test cases?

**Comment by mspncp** [comment]
Actually, I just learned that [IOError is identical with OSError](https://docs.python.org/3/library/exceptions.html?highlight=oserror#OSError) since Python version 3.3, and that the latter is the preferred name.
```
>>> IOError is OSError
True
```

**Comment by mspncp** [comment]
@alexpyattaev I wasn't questioning the fact that the `subpocess.call()` could fail in general, just pointing out that this would be very unlikely to happen in the case of a restart, unless the exutable has been renamed or is some sort of resource exhaustion.
```
             res_code = subprocess.call([sys.executable] + sys.argv) 
```
However, I agree that for the sake of defensive programming (and to please static code analyzers) it would be sensible to initialize `res_code` before the try block.

**Comment by mspncp** [comment]
> However, I agree that for the sake of defensive programming (and to please static code analyzers) it would be sensible to initialize `res_code` before the try block.

See #3863

**Comment by mspncp** [comment]
@gpotter2 does Scapy still support minor versions below 3.3? If not, I could offer to cleanup the except clauses to remove the legacy names, in particular in clausees like `except (IOError, OSError)`.

![grafik](https://user-images.githubusercontent.com/11467854/213796348-ace72c11-f3bb-49f1-8f6c-b21dcffe8088.png)

**Comment by mspncp** [comment]
> Yeah we dropped everything below 3.7 since the 2.5.0 release, so yeah feel free to cleanup that.
Done, see #3864.

> Anyway _this_ issue feels, looks, and tastes somewhat like a waste of time.
Fortunately, it was only me who wasted his time. ;-)

**Comment by mspncp** [comment]
@alexpyattaev I hopt that with  #3859 #3863 and #3864 all your issues will be resolved. If not, please let us know.

**Comment by alexpyattaev** [comment]
Sure they will be=) Thanks!
