### ISSUE TITLE
scapy.modules.six issue

### ISSUE THREAD

**Issue by edaustin** [secdev/scapy#3858]
### Brief description

ModuleNotFoundError: No module named 'scapy.modules.six'

I get this error running from an Ubuntu 22.04 Python notebook using VSC and the command line (bash shell) (Python 3.9 and 3.10) in a conda installed environment on multiple machines, everything is imported ok.

### Scapy version

2.5.0

### Python version

3.9 / 3.10

### Operating system

Ubuntu 22.04 LTS

### Additional environment information

scapy
scapy_p0f

### How to reproduce

Simply try and import the modules
fails at importing scapy_p0f

### Actual result

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_13324/3361348617.py in <module>
  
          1 from scapy.all import *
 ---->  2 import scapy_p0f

/data/anaconda3/envs/py310/lib/python3.10/site-packages/scapy_p0f/__init__.py in <module>
----> 1 from .p0fv3 import p0f, p0f_impersonate, prnp0f, fingerprint_mtu, p0fdb
      2 
      3 __version__ = "1.0.5"
      4 
      5 __all__ = ["p0f", "p0f_impersonate", "prnp0f", "fingerprint_mtu", "p0fdb"]

/data/anaconda3/envs/py310/lib/python3.10/site-packages/scapy_p0f/p0fv3.py in <module>
     14 from scapy.volatile import RandByte, RandShort, RandString
     15 from scapy.error import warning
---> 16 from scapy.modules.six import string_types, integer_types
     17 
     18 from scapy_p0f.utils import lparse

ModuleNotFoundError: No module named 'scapy.modules.six'

**Comment by edaustin** [comment]
Ahh... this probably the issue?

**scapy-p0f supports Python 2.7 and Python 3 (3.4 to 3.7).**

[](https://pypi.org/project/scapy-p0f/)

**Comment by evverx** [comment]
> using VSC

`scapy.modules.six` was moved to `scapy.libs.six` in a0a19f4caa272d7d49ad0ad3a441d71b22e5e064 so `scapy-p0f` can't import it. Having said that `scapy-p0f` stopped using `scapy.modules.six` in https://github.com/Nisitay/pyp0f/commit/d0cbb78 and bumping it to `0.1.2` should probably fix the issue.

**Comment by evverx** [comment]
> bumping it to 0.1.2 should probably fix the issue

Just to clarify as far as I can see https://pypi.org/project/scapy-p0f/ is out of date, no longer maintained and was removed from https://github.com/Nisitay/pyp0f/. It can't be bumped so if it isn't possible to edit the scripts `scapy` should be rolled back to `2.4.0`. The new module is called `pyp0f` to judge from https://github.com/Nisitay/pyp0f#pyp0f and that's where `scapy.modules.six` isn't used.

**Comment by gpotter2** [comment]
`scapy-p0f` is unmaintained because it was contributed by its author in https://github.com/secdev/scapy/pull/3259

Just use `scapy.modules.p0f` instead
