### ISSUE TITLE
doc/scapy NonCommercial license

### ISSUE THREAD

**Issue by charles2910** [secdev/scapy#3870]
Hi, I'm opening this issue because there are a couple files under `doc/scapy` and a commit that states the license as CC-By-NC-SA-2.5 (and I can't reopen issues :-). As [pointed out in the comment](https://github.com/secdev/scapy/issues/3321#issuecomment-1398738672) in #3321, it makes these files unsuitable for Debian. I'll paste the snippets of the files for the record.

`doc/scapy/index.rst`:

```rst
.. Scapy documentation master file, created by sphinx-quickstart on Mon Sep  8 19:37:39 2008.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.
 
Welcome to Scapy's documentation!
=================================
 
.. image:: graphics/scapy_logo.png
   :scale: 20
   :align: center
 
:Version: |version|
:Release: |release|
:Date: |today|
 
This document is under a `Creative Commons Attribution - Non-Commercial 
- Share Alike 2.5 <http://creativecommons.org/licenses/by-nc-sa/2.5/>`_ license.
```

`doc/scapy/layers/automotive.rst`:

```rst
.. note:: This document is under a `Creative Commons Attribution - Non-Commercial - Share Alike 2.5 <http://creativecommons.org/licenses/by-nc-sa/2.5/>`_ license.

#################################
Automotive-specific Documentation
#################################

.. sectionauthor:: Nils Weiss <nils@we155.de>
```

And the commit mentioning the license is 652baabe1fffc3dff6c3f11d37763e529ee3cb8f. Which says:

> Added several tutorial sections, one-liners and recipes by Peter Kacherginsky
>
> Peter had written a very nice tutorial on his web site
> http://thesprawl.org/memdump/doku.php?id=tools:scapy
> and kindly allowed me to add it to our docs under the
> CC BY-NC-SA-2.5 license.

Things are a little gray since most of the docs files don't have a license boilerplate, but looking the online documentation landing page it seems to imply everything is under CC-By-NC-SA-2.5 in my opinion (I'm not an lawyer or expert on the matter though):

![image](https://user-images.githubusercontent.com/34252251/214704356-af638d97-0b5e-4317-8c34-4223d4b9e670.png)

_Originally posted by @charles2910 in https://github.com/secdev/scapy/issues/3031#issuecomment-1404305628_

**Comment by gpotter2** [comment]
This is clarified in https://github.com/secdev/scapy/pull/4254.

**Comment by charles2910** [comment]
Hey, I'm gonna bother you guys again about this matter. The way it's worded after #4254 implies everything under `doc/` is licensed under CC BY-NC-SA 2.5 and I agree with [the comment](https://github.com/secdev/scapy/pull/4254#issuecomment-1925749648).

This means though the manpage is also CC BY-NC-SA 2.5 and will prevent it being shipped with the scapy package (on Debian at least). From the comment, I think the idea is preventing the html documentation being rebranded (but I don't think that makes much sense for a manpage), so maybe you guys would consider licensing the manpage as GPLv2 like the rest of the code.

**Comment by gpotter2** [comment]
Hi. You're right, this is a mistake. `scapy.1` is under GPLv2.
See https://github.com/secdev/scapy/pull/4337
