### ISSUE TITLE
Bad error handling when sending packets without administrator or Winpcap/npcap

### ISSUE THREAD

**Issue by DragonlordNewb** [secdev/scapy#3873]
### Brief description

Tried to use the `send` function which I know shouldn't work without either administrator access or winpcap/npcap; got the following error:
```
send(IP(src="127.0.0.1", dst="127.0.0.1")/UDP(sport=7777, dport=7777))
WARNING: No route found (no default route?)
Exception ignored in: <function SuperSocket.__del__ at 0x000001A966F41990>
Traceback (most recent call last):
...
  File "...", line 114, in __init__
    self.ins = socket.socket(af,
  File "C:\Program Files\Python310\lib\socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```
which I expected, but looking through the source code it looks like there is a code block on line 114 of `scapy/arch/windows/native.py` that's supposed to handle the PermissionError. It isn't handling the error right and it's getting raised instead of telling the user that they need to install winpcap/npcap. And yes, I checked and the error isn't caused by the port already being in use.

This shouldn't affect anything major, but just to point out the error handling in some places needs fixing.

### Scapy version

2.5.0

### Python version

3.10.6

### Operating system

Windows 10

### Additional environment information

No environment was installed; running Python raw. Notably, I **do not** have winpcap/npcap installed, and wasn't using admin access.

### How to reproduce

On a Windows machine without winpcap/npcap and running without adminstrator access:
```py
>>> from scapy.all import *
>>> send(IP(src="127.0.0.1", dst="127.0.0.1")/UDP(sport=7777, dport=7777)) # or whatever port you want
```

### Actual result

```
Traceback (most recent call last):
...
  File "...", line 114, in __init__
    self.ins = socket.socket(af,
  File "C:\Program Files\Python310\lib\socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
```

### Expected result

```
Traceback (most recent call last):
...
OSError: Windows native L3 Raw sockets are only usable as administrator ! Install Winpcap/Npcap to workaround !

### Related resources

_No response_

**Comment by Sajadsanamzadeh** [comment]
> ### Brief description
> 
> Tried to use the `send` function which I know shouldn't work without either administrator access or winpcap/npcap; got the following error:
> ```
> send(IP(src="127.0.0.1", dst="127.0.0.1")/UDP(sport=7777, dport=7777))
> WARNING: No route found (no default route?)
> Exception ignored in: <function SuperSocket.__del__ at 0x000001A966F41990>
> Traceback (most recent call last):
> ...
>   File "...", line 114, in __init__
>     self.ins = socket.socket(af,
>   File "C:\Program Files\Python310\lib\socket.py", line 232, in __init__
>     _socket.socket.__init__(self, family, type, proto, fileno)
> PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
> ```
> which I expected, but looking through the source code it looks like there is a code block on line 114 of `scapy/arch/windows/native.py` that's supposed to handle the PermissionError. It isn't handling the error right and it's getting raised instead of telling the user that they need to install winpcap/npcap. And yes, I checked and the error isn't caused by the port already being in use.
> 
> This shouldn't affect anything major, but just to point out the error handling in some places needs fixing.
> 
> ### Scapy version
> 
> 2.5.0
> 
> ### Python version
> 
> 3.10.6
> 
> ### Operating system
> 
> Windows 10
> 
> ### Additional environment information
> 
> No environment was installed; running Python raw. Notably, I **do not** have winpcap/npcap installed, and wasn't using admin access.
> 
> ### How to reproduce
> 
> On a Windows machine without winpcap/npcap and running without adminstrator access:
> ```py
> >>> from scapy.all import *
> >>> send(IP(src="127.0.0.1", dst="127.0.0.1")/UDP(sport=7777, dport=7777)) # or whatever port you want
> ```
> 
> ### Actual result
> 
> ```
> Traceback (most recent call last):
> ...
>   File "...", line 114, in __init__
>     self.ins = socket.socket(af,
>   File "C:\Program Files\Python310\lib\socket.py", line 232, in __init__
>     _socket.socket.__init__(self, family, type, proto, fileno)
> PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
> ```
> 
> ### Expected result
> 
> ```
> Traceback (most recent call last):
> ...
> OSError: Windows native L3 Raw sockets are only usable as administrator ! Install Winpcap/Npcap to workaround !
> 
> ### Related resources
> 
> _No response_
