### ISSUE TITLE
PcapReader not able to catch up and throws error when reading continuous stream

### ISSUE THREAD

**Issue by souravs17031999** [secdev/scapy#3884]
### Brief description

Hi team, 

I am working on a usecase where I am using PcapReader to read packet by packet in a continuos stream (which can be abrupt meaning it can be stopped and started), PcapReader is able to read the packets for some time but if stream is stopped and restarted again, then PcapReader doesn't prints anything and throws exception.

can you help me in understanding if this is a bug in scapy ?

### Scapy version

2.5.0

### Python version

3.7

### Operating system

Ubuntu 20.04

### How to reproduce

sample code : 

```
input = os.getenv('INPUT_STREAM')

reader = PcapReader(input)
batch_size=10
```

```
while True:
        try:
            batch = []
            while len(batch) != batch_size:
                packet = reader.read_packet()
                if packet is None:
                    continue
                batch.append(packet)
            
            print(plist.PacketList(batch).sessions(get_sessions))
        except Exception as e:
            print(e)
```
When pressed KeyboardInterrupt, it stucks at https://github.com/secdev/scapy/blob/master/scapy/utils.py#L1250
Note: I am using tshark CLI to dump continous stream in format pcap.

### Actual result

It throws the exception as soon as stream is stopped but doesn't print anything in print(e) part under exception block.

### Expected result

Ideally It should start reading as soon as next packet arrives when stream restarts.

**Comment by souravs17031999** [comment]
any ideas @gpotter2 @guedou @p-l-  if I am doing something wrong ?

**Comment by p-l-** [comment]
Hey sorry but this is more a question than a bug, so it's probably better asked on the [Gitter](https://gitter.im/secdev/scapy) than in an issue. Also, please avoid `@`-mentioning maintainers as they don't owe you their time.

**Comment by souravs17031999** [comment]
Hi @p-l- sorry for mentioning, it's a bit urgent issue for me but that's fine.
I will ask on Gitter then, thanks for understanding !
