### ISSUE TITLE
Request: return self for simpler usage

### ISSUE THREAD

**Issue by PhilipDeegan** [secdev/scapy#3886]
Hey I was wondering if you might consider modifying a function to streamline it's use?

here:
https://github.com/secdev/scapy/blob/e834fa305fba6700171483c51faca5a3163a2d41/scapy/sendrecv.py#L1277

so rather than currently doing

```
a = AsyncSniffer(...)
a.start()
a.join()
```

it could be 

```
AsyncSniffer(...).start().join()
```

**Comment by gpotter2** [comment]
The thing is, `AsyncSniffer` is supposed to be stored. If you were to do the above, you'd just call `sniff(...)` instead and get the same result
