### ISSUE TITLE
Receiving ICMPv6 packet in raw format unlike other packets

### ISSUE THREAD

**Issue by PriyaKuche** [secdev/scapy#3916]
Hello, 

I am facing two issues regarding reading the packets using Scapy. And both the issues are mainly for "dest-unreach".
Scapy - version = "2.5.0"
1. The ICMPExtensionHeader(IPv4) does not show up in the packet and using decode_payload_as is giving a different output when compared to wireshark. 

3. I was trying to debug a case in which I can collect the ICMPv6 details but the packet is showing up in raw format. And also the packet can be viewed on wireshark but when reading via script it is showing as Raw.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/126627479/222007217-421ff066-94f9-4911-b6f7-f8bda026d57c.png">

2023-02-28 10:34:06,293 - INFO - Incoming packet is Raw [] 
2023-02-28 10:34:06,293 - INFO - Incoming packet number is 66 [] 

As I found these in our organization code base, I can't share the code snippet or the file.
Let me know if more details are required. 

Thanks

**Comment by guedou** [comment]
Unless you share the code and fill the issue template there is no way to help you. Also, please you gitter for such questions.
