### ISSUE TITLE
`RawPcapReader` is missing `__enter__` method

### ISSUE THREAD

**Issue by wesley-smith** [secdev/scapy#3918]
### Brief description

Hi,

On version 2.4.4., the `scapy.utils.RawPcapReader` class supported the `__enter__` context manager method, but in 2.4.5, that method was moved [from `RawPcapReader`](https://github.com/secdev/scapy/commit/fdded351f3c50236a1e43194df5dd8c6dbe92084#diff-7e53ee1d39af61ab3112ba2d0a9d80a60ad922575a8091f889c19ea7b2621eddL1284-L1287) to the [`PcapReader` subclass](https://github.com/secdev/scapy/commit/fdded351f3c50236a1e43194df5dd8c6dbe92084#diff-7e53ee1d39af61ab3112ba2d0a9d80a60ad922575a8091f889c19ea7b2621eddR1336-R1339). This breaks a portion of our code which uses a `RawPcapReader` in a `with` statement block.

### Scapy version

2.4.5

### Python version

3.6.9

### Operating system

MacOS 13.2.1

### How to reproduce

```(python)
with RawPcapReader(some_pcap_file) as reader:
    # do something with the packets, e.g.:
    first_packet = next(reader, None)
``` 

### Actual result

```
AttributeError: __enter__
```

### Expected result

Successful processing of pcap.

**Comment by guedou** [comment]
Thanks for reporting this issue! This was not catched by any unit test. I pushed a possible fix.

**Comment by wesley-smith** [comment]
Hi all, any chance this can be added to a release soon?

Thanks for your support.
