### ISSUE TITLE
X86_64 is incorrect when running a 32bit binary under 64bit machine

### ISSUE THREAD

**Issue by weyou** [secdev/scapy#392]
I packed my program by PyInstaller under 32bit python.  When run it under 64bit machine. Got the following error:
```
  File "scapy/sendrecv.py", line 593, in sniff
  File "scapy/arch/linux.py", line 496, in __init__
  File "scapy/arch/linux.py", line 157, in attach_filter
  File "socket.py", line 224, in meth
socket.error: [Errno 22] Invalid argument
```
I checked the source code of scapy,  the X86_64 is set to True, cause a wrong offset for the BPF in attach_filter is set .  

In this case,  I think the program should treat the runtime platform totally as a 32bit platform.

I googled this issue and find some old issues are filed several years ago. But obviously, it has not get resolved.
https://bitbucket.org/secdev/scapy/issues/486/scapy-misdetects-the-current-architecture
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=594261

Here is the patch for X86 platform:
```
file: scapy/arch/consts.py
@@ -5,6 +5,7 @@

 import os
 from sys import platform
+import platform as pf

 LINUX = platform.startswith("linux")
 OPENBSD = platform.startswith("openbsd")
@@ -20,7 +21,8 @@
     ARM_64 = False
 else:
     uname = os.uname()
-    X86_64 = uname[4] == 'x86_64'
+    X86_64 = pf.architecture()[0] == '64bit'
     ARM_64 = uname[4] == 'aarch64'

 LOOPBACK_NAME = "lo" if LINUX else "lo0"
```

**Comment by p-l-** [comment]
Sounds good to me. Care to submit a pull request?

**Comment by gpotter2** [comment]
@p-l- I guess this can be added manually...

**Comment by p-l-** [comment]
@weyou I have chosen a different way to address that issue, based on Python documentation. Could you tell us if the patch proposed in #484 works for you? Thanks.
