### ISSUE TITLE
Does rdpcap support read a pcap from an offset?

### ISSUE THREAD

**Issue by YichuanSun** [secdev/scapy#3943]
### Brief description

For example, read pcap file begining from the 100th packet. 
I need this function in a use case, while I find that rdpcap is only support read from the begining of the pcap file.
If scapy does not support such function, maybe I will add a PR later.

### Scapy version

2.4.3

### Python version

3.10.4

### Operating system

windows 10

### How to reproduce

.

**Comment by guedou** [comment]
You can use RawPcapReader to iterate over a pcap, skip the first packets, then parse others with Scapy.

Please continue the discussion ont gitter if needed.
