### ISSUE TITLE
doc: Link from TCP to Automata is broken

### ISSUE THREAD

**Issue by wdoekes** [secdev/scapy#3950]
### Brief description

See this:

https://github.com/secdev/scapy/blob/43582d36fe202916fab4f36f0fd10d697eabd8a5/doc/scapy/layers/tcp.rst#scapys-tcp-client-automaton

There is a link `(see Automata's documentation)` but it points to https://github.com/secdev/scapy/blob/master/doc/scapy/advanced_usage which does not exist. Should probably be +`.rst`.

On RTD ( https://scapy.readthedocs.io/en/latest/layers/tcp.html ) it looks like:
https://scapy.readthedocs.io/en/latest/advanced_usage#automata
which should be:
https://scapy.readthedocs.io/en/latest/advanced_usage.html#automata

### Scapy version

.

### Python version

.

### Operating system

.

### How to reproduce

.

**Comment by evverx** [comment]
Looks like it was fixed in https://github.com/secdev/scapy/pull/4189

**Comment by gpotter2** [comment]
Indeed, thanks @evverx.
