### ISSUE TITLE
warning: no files found matching 'scapy/VERSION'

### ISSUE THREAD

**Issue by evverx** [secdev/scapy#3955]
When `python3 -m build -s` or `python3 setup.py sdist` is run "warning: no files found matching 'scapy/VERSION'" is produced. It's somewhat harmless in the sense that it doesn't affect the sdist and the wheel but it would be better if it wasn't there. I think the problem is that apart from the python packaging various distributions can rely on this logic somehow (for example Debian seems to add `scapy/VERSION` after it unpacks the tarball while Fedora relies on the archive tag) and it isn't clear (to me at least) how to fix it without breaking them.

Looks like this warning was introduced in 915fe2d207b0f91768de2a25d576767a4cf2efaf
> Do not try to generate the scapy/VERSION file when importing scapy
anymore but generate it by overriding the sdist command in setup.py and
write it to the temp folder used for the source archive generation

and since `scapy/VERSION` is included in `MANIFEST.in` the warning is generated. It should be possible to "fix" it by removing it from `MANIFEST.in` but it would break the wheel in the sense that `VERSION` would no longer be included in the wheel generated from the sdist. @rjarry could you take a look? I can't say I fully understand all the corner cases there and I don't want to break it accidentally.

_Originally posted by @evverx in https://github.com/secdev/scapy/issues/3945#issuecomment-1482182552_

**Comment by evverx** [comment]
> Debian seems to add scapy/VERSION after it unpacks the tarball 

Looking at https://salsa.debian.org/pkg-security-team/scapy/-/commit/5cb0a080dca71b03f23e9e3c3162abc4401c568f it seems at the time the build system didn't use the tag. It seems it should be possible to just ask the maintainers to remove that part to decouple the package from `scapy/VERSION`. It should make it easier to start exploring the suggestion from https://github.com/secdev/scapy/pull/3945#issuecomment-1482130095.

**Comment by rjarry** [comment]
Hi there,

I forgot to remove that file from `MANIFEST.in` in my patch.

I don't think removing `scapy/VERSION` from it will break `sdist` nor `bdist_wheel` since `scapy/VERSION` is now generated directly into the folder that will be used to generate the archives.

**Comment by rjarry** [comment]
hmm, my bad then. It looks like we must also override the build_py command. I have made a quick & dirty patch which seems to work:

```diff
diff --git a/MANIFEST.in b/MANIFEST.in
index cdf9a3018f0c..49b8951efd21 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -1,4 +1,3 @@
 include MANIFEST.in
 include LICENSE
 include run_scapy
-include scapy/VERSION
diff --git a/setup.py b/setup.py
index 925e65cc9b34..a19a83e86947 100755
--- a/setup.py
+++ b/setup.py
@@ -6,6 +6,7 @@ Distutils setup file for Scapy.
 
 try:
     from setuptools import setup, find_packages
+    from setuptools.command.build_py import build_py
     from setuptools.command.sdist import sdist
 except:
     raise ImportError("setuptools is required to install scapy !")
@@ -40,13 +41,24 @@ class SDist(sdist):
             f.write(__import__('scapy').VERSION)
 
 
+class BuildPy(build_py):
+
+    def build_package_data(self):
+        super().build_package_data()
+        # ensure there's a scapy/VERSION file
+        version = os.path.join(self.build_lib, 'scapy', 'VERSION')
+        if not os.path.isfile(version):
+            with open(version, 'w') as f:
+                f.write(__import__('scapy').VERSION)
+
+
 # https://packaging.python.org/guides/distributing-packages-using-setuptools/
 setup(
     name='scapy',
     version=__import__('scapy').VERSION,
     packages=find_packages(),
     data_files=[('share/man/man1', ["doc/scapy.1"])],
-    cmdclass={'sdist': SDist},
+    cmdclass={'sdist': SDist, 'build_py': BuildPy},
     # Build starting scripts automatically
     entry_points={
         'console_scripts': [
```

What do you think?

**Comment by evverx** [comment]
That being said with this patch applied the warning is still generated:
```
$ python3 ./setup.py -q sdist
...
warning: no files found matching 'scapy/VERSION'
```

**Comment by rjarry** [comment]
Debian (and other downstream) packaging should export `SCAPY_VERSION` to ensure no conflicts with downstream tags.

**Comment by evverx** [comment]
I think as long as `scapy/VERSION` works it shouldn't be necessary to switch to `SCAPY_VERSION`. Gentoo uses `scapy/VERSION` too: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/scapy/scapy-2.5.0.ebuild#n47 and I suspect there are other distributions where it has been used for years without having to set any environment variables.

**Comment by rjarry** [comment]
If scary/VERSION is removed from MANIFEST.in then overriding its contents will not be possible directly. The only way is to export SCAPY_VERSION.

**Comment by evverx** [comment]
`setup.py` calls `__import__('scapy').VERSION` and it reads `scapy/VERSION` if it's present so as far as I can see it's still possible to inject it into sdists:
```sh
$ sed -i '/VERSION/d' MANIFEST.in
$ echo 10.0.0 >scapy/VERSION
$ python3 -m build -s
...
Successfully built scapy-10.0.0.tar.gz
 
$ tar xzvf dist/scapy-10.0.0.tar.gz
$ cat scapy-10.0.0/scapy/VERSION
10.0.0
```
and I think it should keep working because it's what already used de-facto to enforce downstream versions.

**Comment by rjarry** [comment]
Ok by bad. I shouldn't reply from my phone :)

**Comment by gpotter2** [comment]
My proposal: https://github.com/secdev/scapy/pull/3958

drop the VERSION file and use the now more standard [`importlib.metadata`](https://docs.python.org/3/library/importlib.metadata.html) method to access the package metadata and get the version. Kudos for having this feature years before everyone else
