### ISSUE TITLE
eapol_key fields appear reversed

### ISSUE THREAD

**Issue by lts-rad** [secdev/scapy#3957]
https://github.com/secdev/scapy/blob/358f5465ddbf6149bcfe9cad8fef2f4b925dd173/scapy/layers/eap.py#L439

When trying to use this structure I found that the bitfields were out of order for me for decoding data off the wire. The following worked. im also not sure if key_mic is conditional or not, but the below code is what worked for me. 

i'm not suggesting to take this code directly but mainly that EAPOL_KEY needs fixing.

```python
class EAPOL_KEY(Packet):
    name = "EAPOL_KEY"
    fields_desc = [
        ByteEnumField("key_descriptor_type", 1, {1: "RC4", 2: "RSN"}),
        # Key Information
        BitField("reserved2", 0, 2),
        BitField("smk_message", 0, 1),
        BitField("encrypted_key_data", 0, 1),
        BitField("request", 0, 1),
        BitField("error", 0, 1),
        BitField("secure", 0, 1),
        BitField("has_key_mic", 1, 1),
        BitField("key_ack", 0, 1),
        BitField("install", 0, 1),
        BitField("key_index", 0, 2),
        BitEnumField("key_type", 0, 1, {0: "Group/SMK", 1: "Pairwise"}),
        BitEnumField("key_descriptor_type_version", 0, 3, {
            1: "HMAC-MD5+ARC4",
            2: "HMAC-SHA1-128+AES-128",
            3: "AES-128-CMAC+AES-128",
        }),
        #
        LenField("len", None, "H"),
        LongField("key_replay_counter", 0),
        XStrFixedLenField("key_nonce", b"\x00"*32, 32),
        XStrFixedLenField("key_iv", b"\x00"*16, 16),
        XStrFixedLenField("key_rsc", b"\x00"*8, 8),
        XStrFixedLenField("key_id", b"\x00"*8, 8),
        XStrFixedLenField("key_mic", b"\x00"*16, 16),  # XXX size can be 24
        LenField("key_length", None, "H"),
        ConditionalField(
          XStrLenField("key", b"\x00"*16,
                     length_from=lambda pkt: pkt.key_length),
          lambda pkt: pkt.key_length and pkt.key_length > 0)
    ]
    ```

**Comment by gpotter2** [comment]
Hi & thanks f lot for the report !
Regarding the order of the fields, you're absolutely right this is a bug.

>  im also not sure if key_mic is conditional or not

What do you mean? Would you by any chance have a pcap containing a packet that didn't match because of this?

Thanks a lot !

**Comment by lts-rad** [comment]
I see about the key mic. in case its helpful here is a pcap produced with hostapd & wpa client + mac80211_hwsim


[handshake-mic.zip](https://github.com/secdev/scapy/files/11074148/handshake-mic.zip)
