### ISSUE TITLE
Scapy import

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#396]
Small note, this:
`from scapy.all import *`
which is verrrrryyyy slow, is being used in
[bluetooth.py](https://github.com/secdev/scapy/blob/cce88a93b006775957757bd2d311649f4d423863/scapy/layers/bluetooth.py#L15)

I guess the proper imports should be set instead

**Comment by gpotter2** [comment]
I've added it to my "todo" list: https://github.com/secdev/scapy/issues/399

**Comment by p-l-** [comment]
For the record, #403.
