### ISSUE TITLE
sr() timeout is incorrect when system time changes

### ISSUE THREAD

**Issue by argold97** [secdev/scapy#3964]
In scapy/supersocket.py, timeout for the `sr()` and related functions use `time.time()` to determine a start time, current time, and timeout time. However, `time.time()` is affected by changes to the system clock (on Linux at least). This causes the apparent timeout when using `sr()` to be wrong if the system time changes during the call (either manually or via NTP).

To reproduce:
run
```python
sr([IP(dst="<an IP that doesn't respond to pings>")/ICMP()], timeout=10)
```
while running, in another terminal change the system time (may have to temporarily disable your OS's NTP):
```bash
sudo date -s "-1 minute"
```
The `sr()` call will take 60-70s to return, instead of 10s.

scapy/supersocket.py should probably use `time.monotonic()` for this kind of calculation.

**Comment by gpotter2** [comment]
Thanks for the report !
Should be fixed in https://github.com/secdev/scapy/pull/3977
