### ISSUE TITLE
send() ignores its iface argument on linux

### ISSUE THREAD

**Issue by cedric-sun** [secdev/scapy#3973]
### Brief description

`send()` in linux.py currently ignores whatever interface specified by upper caller, and ask the packet subclass to recompute its route triplet followed by an unconditional `bind()`:

https://github.com/secdev/scapy/blob/cb619e534d6684c86fd2e00a90ce2b69a8f77ef1/scapy/arch/linux.py#L598-L604

Consider this code and call path:

```py
def send_iface_not_respected():
    a = ARP(pdst="192.168.31.88")
    send(a, iface="enp6s0")
```

```
send, linux.py:600
__gen_send, sendrecv.py:376
_send, sendrecv.py:414
send, sendrecv.py:444
send_iface_not_respected, tmp.py:8
<module>, tmp.py:12
```

If `ARP.route()[0]` resolves to any device name other than `enp6s0` (e.g.  `lo`), `iface` argument to `send` will be ignored.

I'm unsure about Windows and MacOS.

### Scapy version

git master cb619e534d6684c86fd2e00a90ce2b69a8f77ef1

### Python version

3.10.10

### Operating system

linux 6

### How to reproduce

1. Choose any packet whose `route()[0]` gives a device name `X`
2. send it with `iface=Y`
3. Observe with wireshark or tcpdump that the packet is *not* sent to interface `Y`.

### Actual result

`send(iface=)` is not respected.

### Expected result

`send(iface=)` should be respected.

**Comment by cedric-sun** [comment]
Also I think that using `bind()` together with `sendto()` violates the kernel's model of socket. (See `send(2)` and `bind(2)` man page)

**Comment by guedou** [comment]
The ARP protocol must be encapsulated on top of Ethernet. `send()` works as expected. I just tested `arping()` and it works as expected.
