### ISSUE TITLE
WARNING when using send() to send via pppoe interface

### ISSUE THREAD

**Issue by stark131** [secdev/scapy#3974]
### Brief description

Scapy ver: 2.5.0

Issue description: 
I created a packet with the simple following elements: 
```
ip=IP(dst=dst_ip,version=4) ### the dst_ip looks like "1.1.1.1", which is a valid IPv4 address. 
pac=ip/tcpdata/Raw(load=data)
pac.show()
send(ip,verbose=1)
```
When I try to call send() to an address that goes through the Ethernet interface, it was all fine. 
However, when I try to call send() to an address that goes through the pppoe interface, this warning comes up: 
```
WARNING: Incompatible L3 types detected using <class 'scapy.layers.inet.IP'> instead of <class 'scapy.layers.inet6.IPv46'> !
```

I am not sure if this is bug or feature but I am pretty sure that the packet is created properly. 

### Scapy version

2.5.0

### Python version

3.9

### Operating system

Linux 5.15.102

### How to reproduce

The same as in "Brief Description"

**Comment by hcavoliveira** [comment]
Hi, good evening! Did you ever find a solution to this problem? I just got that same warning while running scapy
