### ISSUE TITLE
scapy.net comes up as a blank page on an iPad

### ISSUE THREAD

**Issue by Twilight-Logic** [secdev/scapy#3980]
I tried to read some of the documentation linked on scapy.net on my iPad Air yesterday and couldn't because the website came up as a blank page. The site works OK on a PC running Linux/Chromium/Firefox and Windows/Edge.

UPDATE: a little after posting this, I discovered that the problem seems to be down to using older iPad Air with iOS 12. When accessed on a more up-to-date iPad with the latest iOS, the page came up just fine.
Looks like I need a new iPad....

I guess this can be closed/deleted as appropriate.

**Comment by p-l-** [comment]
Thank you for letting us know. I'm not sure we want to do something about it. I'm closing this issue. @gpotter2 @guedou re-open if you consider we should fix that.
