### ISSUE TITLE
NTP packets have invalid reference timestamps

### ISSUE THREAD

**Issue by perina98** [secdev/scapy#3995]
### Brief description

When reading NTP packets, ref, orig, recv and sent attribute values are not correct when reading them directly.
Values appear to be correct when using packet[NTP].show(), but not using packet[NTP].orig for example, which shows unix timestamp of 3613294654. Am I doing something wrong or is this a bug? Iam attaching screenshot, and example pcap file. Iam using scapy in simple python script to read pcap files.
[nntp.zip](https://github.com/secdev/scapy/files/11304521/nntp.zip)

![ntppaket](https://user-images.githubusercontent.com/48447041/233857631-58c52fcc-91d1-4a26-94de-f3082f1fb90d.png)

### Scapy version

2.5.0

### Python version

3.8.10

### Operating system

Ubuntu 20.04, Windows 10

### How to reproduce

Read pcap file using python scapy library
print / show NTP packet orig/sent timestamps

**Comment by gpotter2** [comment]
NTP timestamps are not based on epoch. I encourage you to read the RFC
