### ISSUE TITLE
sendpfast not passing float to tcpreplay

### ISSUE THREAD

**Issue by jbreed** [secdev/scapy#4006]
### Brief description

When sending a float for a fractional PPS, nothing is sent. Taking a look, I noticed tcpreplay doesn't get started. When I sent a PPS with a float of 10.5, I see tcpreplay start with a PPS of just 10.

Looking at the code:
Line 516 has the following
"--pps %i" % pps

If doing something like: f"--pps {pps}" instead, it will pass the float as intended to the call. I verified I can run the tcpreplay command manually using 10.5 no issues, but using sendpfast it doesn't pass to tcpreplay properly.

### Scapy version

2.5.0

### Python version

3.7

### Operating system

Linux 4.14 Amazon EC2 AMI

### How to reproduce

Pass a fractional float into the PPS value of sendpfast. Under 1 I don't believe tcpreplay starts at all. Over 1, I notice it rounds it instead of using the full float passed.

### Actual result

tcpreplay with 10 as PPS

### Expected result

tcpreplay with 10.5 as PPS

**Comment by jbreed** [comment]
Could simply change %i to %f to allow passing a float.

**Comment by KhazAkar** [comment]
After this change, have you checked behavior thoroughly when using integer instead, with %f?

**Comment by jbreed** [comment]
> After this change, have you checked behavior thoroughly when using integer instead, with %f?

Not yet. I did verify doing a sed on my site packages to change this results in the code starting tcpreplay with the float inserted. The tcpreplay docs as well as scrapy docs state this value to be a float. Tomorrow I’ll be running large traffic generation tests to confirm it properly generates the traffic.

**Comment by jbreed** [comment]
> After this change, have you checked behavior thoroughly when using integer instead, with %f?

Ran some tests this morning and looks good using a float, which both sendpfast and tcpreplay say the PPS field to be a float. Tested using a UDP stream with .5 PPS and verified in tcpdump I seen one packet every other second. I'm calling it good and will leave my sed patch in place for now. I imagine most using scapy aren't looking at this low level amount of packets sent, but in my project we are generating traffic to match other traffic profiles we have for network testing. If using this for security testing, likely not going to come up.

**Comment by guedou** [comment]
@jbreed thanks for testing! do you feel like sending a PR?

**Comment by jbreed** [comment]
> @jbreed thanks for testing! do you feel like sending a PR?

Sorry, forgot to check back on this. Our Dockerfile has been doing a sed to replace this, which I have continued to use for our traffic generators. Given this is used to mock up traffic based on traffic profiles needed that fine control to properly analyze traffic flows.

I will try and get a request submitted this evening to update it.

**Comment by jbreed** [comment]
@guedou Sorry, completely forgot about this. Just randomly came over to look at my github notifications and remembered I should push this fix to the repo so our dockerfile can avoid doing the sed once merged in.
