### ISSUE TITLE
VLAN tag has incorrect field name

### ISSUE THREAD

**Issue by alexforencich** [secdev/scapy#4008]
### Brief description

The 802.1Q VLAN tag object (`Dot1Q`) has an incorrectly-named field.  According to the IEEE specs, the fields are PCP, DEI, and VID.  Scapy uses `prio` and `vlan` for PCP and VID, which are reasonable.  But the DEI bit is called `id`, which is incorrect and could be confused for the VLAN ID `vlan`.  So, `id` should probably be renamed either `drop` or `dei` as the meaning of the bit is "drop eligible indicator".  For reference, wireshark decodes the fields in the UI as "PRI" or "Priority", "DEI", and "ID".

### Scapy version

2.4.4

### Python version

3.10

### Operating system

Arch Linux

### How to reproduce

N/A

**Comment by p-l-** [comment]
Makes perfect sense, thanks for this suggestion!
