### ISSUE TITLE
[Windows] global name 'LOOPBACK_NAME' is not defined

### ISSUE THREAD

**Issue by weyou** [secdev/scapy#401]
The constant LOOPBACK_NAME is referenced in the function get_working_if() which defined in file C:\Python27\Lib\site-packages\scapy\arch\windows\__init__.py.  But it didn't get defined in that file.

Add the follow line to the head of file:
```
from scapy.arch.consts import LOOPBACK_NAME
```

**Comment by gpotter2** [comment]
That will be fixed in https://github.com/secdev/scapy/pull/398
