### ISSUE TITLE
ikev2 logging issues - can't suppress unnamed logger in the ikev2 contrib package

### ISSUE THREAD

**Issue by marcelApps** [secdev/scapy#4028]
### Brief description

ikev2 (scapy/contrib/ikev2) using logging without defined logger name (see https://docs.python.org/3/library/logging.html#logging.getLogger), so when I want to suppress these logs, I need to suppress/mock whole logging instead of disabling specific logger.

### Scapy version

2.5.0

### Python version

3.8

### Operating system

Windows 10

### How to reproduce

1. Use sniffer and capture ikev2 packets
2. Try to suppress logging from the scapy/contrib/ikev2

### Expected result

Logging in the scapy/contrib/ikev2 named like in other scapy's packages (see https://docs.python.org/3/library/logging.html#logging.getLogger)

**Comment by mspncp** [comment]
I assume you are talking about those debug log messages here?

https://github.com/secdev/scapy/blob/9473f77d8b548c8e478e52838bdd4c12f5d4f4ff/scapy/contrib/ikev2.py#L436-L447

The are already gone in the master branch, they have been removed in commit 012110a960fcea8b812532f2115bb27c836246ee.

**Comment by marcelApps** [comment]
Yes, this is what I am talking about. Thank you for information. I'll wait for next release.

**Comment by marcelApps** [comment]
Do you know when next release will be available?

**Comment by marcelApps** [comment]
@gpotter2 , @guedou , @p-l- do you know possible date of the next Scapy release?

**Comment by p-l-** [comment]
There is a gitter chat if you want to ask questions. **Please do not** `@`-mention maintainers, we have enough GH notifications and really don't need that.

**Comment by marcelApps** [comment]
Sure, I'm sorry about that.
