### ISSUE TITLE
Unable to send custom UDS request after using UDS_Scanner

### ISSUE THREAD

**Issue by sa-isd** [secdev/scapy#4035]
### Brief description

I have a DoIPSocket over which I can send a UDS request and receive a reply. If I instantiate the UDS_Scanner class (even without running the scan), I get an error trying to reuse my previous DoIPSocket. 

I am not sure if I am missing something and this is expected behaviour?

### Scapy version

2.5.0

### Python version

3.11.2

### Operating system

Linux krake 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

### How to reproduce

My test program
```
from scapy.contrib.automotive.uds import *
from scapy.contrib.automotive.uds_scan import *
from scapy.contrib.automotive.doip import *

ipv4_addr = "169.254.98.64"

socket = DoIPSocket(ipv4_addr)

def send_request():
    pkt = DoIP(payload_type=0x8001, source_address=0xe80, target_address=0x3107)/UDS()/UDS_RDBI(identifiers=0x0194)
    response = socket.sr1(pkt, verbose=False, timeout=2, retry=1)
    print(f"{response}\n")

print("sending first UDS request")
send_request()


def reconnect():
    return UDS_DoIPSocket(ip=ipv4_addr,port=13400)

es = [UDS_ServiceEnumerator]

s = UDS_Scanner(reconnect(), reconnect_handler=reconnect,
                reset_handler=None, test_cases=es, debug=True,
                UDS_ServiceEnumerator_kwargs={
                    "scan_range": range(0x40, 0x44), "timeout": 10, "retry_if_none_received":True}
                )

print("sending second UDS request")
send_request()
```

stdout
```
INFO: Routing activation successful! Target address set to: 0x3107
sending first UDS request
DoIP / UDS / UDS_NR

INFO: Routing activation successful! Target address set to: 0x3107
sending second UDS request
ERROR: --- Error sending packets
Traceback (most recent call last):
  File "/home/krake/.test_case_venv/lib/python3.11/site-packages/scapy/sendrecv.py", line 248, in _sndrcv_snd
    self.pks.send(p)
  File "/home/krake/.test_case_venv/lib/python3.11/site-packages/scapy/supersocket.py", line 110, in send
    return self.outs.send(sx)
           ^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
None
```

### Actual result

![image](https://github.com/secdev/scapy/assets/115094878/200cdd18-ec8c-4cbb-910e-039dec608fdd)

**Comment by polybassa** [comment]
Hi, thanks for reaching out. Your code example has a couple of issues. Since these issues are not related to bugs in Scapy, could you please reach out to me via mail, and we can discuss your use-cases and solve the issues in your code. 

I suggest to close this issue and solve if outside of github.
