### ISSUE TITLE
scapy/base_classes.py duplicated 'reserved' field!

### ISSUE THREAD

**Issue by ashok5141** [secdev/scapy#4039]
### Brief description

base_classes.py has a duplicated 'reserved' field!

### Scapy version

2.5.0

### Python version

3.9.2

### Operating system

Linux 6.1.21-v8+ 

### Additional environment information

OS:- Raspberry PI OS kernel-Linux 6.1.21-v8+
Raspbee II head using zigbee network
their are using scapy library. Getting an error with duplicated fields while using base_classes.py even tried to change but issue. Can provide me alternative way avoid this error. 

### How to reproduce

If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !

### Actual result

This error message while running script **rasp@raspberrypi:~/zigdiggity $ python3 listen.py -c 15**
/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py:319: SyntaxWarning: Packet 'ZigbeeNWKCommandPayload' has a duplicated 'reserved' field ! If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !
  warnings.warn(war_msg, SyntaxWarning)
/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py:319: SyntaxWarning: Packet 'ZigbeeNWKCommandPayload' has a duplicated 'multicast' field ! If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !
  warnings.warn(war_msg, SyntaxWarning)
/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py:319: SyntaxWarning: Packet 'ZigbeeNWKCommandPayload' has a duplicated 'route_request_identifier' field ! If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !
  warnings.warn(war_msg, SyntaxWarning)
/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py:319: SyntaxWarning: Packet 'ZigbeeNWKCommandPayload' has a duplicated 'path_cost' field ! If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !
  warnings.warn(war_msg, SyntaxWarning)
/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py:319: SyntaxWarning: Packet 'ZigbeeNWKCommandPayload' has a duplicated 'destination_address' field ! If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !
  warnings.warn(war_msg, SyntaxWarning)
/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py:319: SyntaxWarning: Packet 'ZigbeeNWKCommandPayload' has a duplicated 'epid' field ! If you are using several ConditionalFields, have a look at MultipleTypeField instead ! This will become a SyntaxError in a future version of Scapy !
  warnings.warn(war_msg, SyntaxWarning)
Traceback (most recent call last):
  File "/home/rasp/zigdiggity/listen.py", line 9, in <module>
    import zigdiggity.observers.utils as observer_utils
  File "/home/rasp/zigdiggity/zigdiggity/observers/utils.py", line 2, in <module>
    from zigdiggity.observers.key_finder_observer import KeyFinderObserver
  File "/home/rasp/zigdiggity/zigdiggity/observers/key_finder_observer.py", line 1, in <module>
    from zigdiggity.packets.utils import get_extended_source, extended_address_bytes, get_pan_id
  File "/home/rasp/zigdiggity/zigdiggity/packets/utils.py", line 3, in <module>
    from scapy.layers.zigbee import *
  File "/home/rasp/.local/lib/python3.9/site-packages/scapy/layers/zigbee.py", line 291, in <module>
    class ZigbeeNWKCommandPayload(Packet):
  File "/home/rasp/.local/lib/python3.9/site-packages/scapy/base_classes.py", line 339, in __new__
    dct["__signature__"] = inspect.Signature([
  File "/usr/lib/python3.9/inspect.py", line 2843, in __init__
    raise ValueError(msg)
ValueError: duplicate parameter name: 'reserved'

### Expected result

List of zigbee channels

### Trying to capture zigbee packets and then manupate using scapy
OS:- Raspberry PI OS kernel-Linux 6.1.21-v8+
Raspbee II head using zigbee network

Resource using:- https://github.com/BishopFox/zigdiggity

**Comment by evverx** [comment]
It seems `scapy` is patched there with https://github.com/BishopFox/zigdiggity/blob/master/patch/zigbee.py and that patch doesn't seem to be in sync with scapy in the sense that cfe00d5c952e9048a40150390e0025b5ceff7228 has never made it into that repository. It should probably be possible to "fix" it by downgrading scapy to `2.4.4` but the right fix would probably be to update that patch there. Either way it isn't a scapy issue.

**Comment by gpotter2** [comment]
We only provide support for the version of Scapy hosted on this github, not on 'zigdiggity'.
