### ISSUE TITLE
Determine a Way to Avoid Running OS-Dependent Tests on the Wrong Platforms

### ISSUE THREAD

**Issue by xee5ch** [secdev/scapy#404]
I started playing with `UTScapy` to get acquainted and begin my work on #403.  I noticed the last few attempts some tests were not passing consistently.

```
[me@computer Code]$ uname -a
Linux computerwad 4.8.11-1-ARCH #1 SMP PREEMPT Sun Nov 27 09:26:14 CET 2016 x86_64 GNU/Linux
[me@computer Code]$ cd scapy/test/
[me@computer test]$ ./run_tests
passed 14F389A8 Get conf
...
failed A9C2ECFF Truncated netstat -rn output on OS X
failed E08493A5 Preliminary definitions
failed 407C7355 Mac OS X 10.9.5
failed 8D6AE4A6 Mac OS X 10.9.5 with global IPv6 connectivity
failed 36E966E3 Mac OS X 10.10.4
failed 325F96BE FreeBSD 10.2
failed 589FFE1A OpenBSD 5.5
failed 4A4C793D NetBSD 7.0
...
Campaign CRC=DF4214BE  SHA=926CD6FC8BEA81515D3129E7BFB3E7341680E0D6
PASSED=872 FAILED=16
```
I am intrigued because i noticed you guys have CI on Travis and AppVeyor.  CI on Travis says something like `secdev/scapy` does not exist, so perhaps it's not public. AppVeyor is clearly Windows builds, and there is no mentioed of any of the BSD-flavored tests in the campaign.

I will review the `UTScapy` code tomorow.  I just read [the testing with UTScapy docs](https://scapy.readthedocs.io/en/latest/development.html#testing-with-utscapy).  Is there a profile or condition that lumps all Unixy operating systems together?  Is there any desire in me trying to imrpove this?  It is more a learning exercise for me to better know the project.  If you prefer I do not play here, you can close it and I will let it go.

**Comment by gpotter2** [comment]
Nah don't worry, that code crashes when you're not on the good operating system, or when you're missing depedencies, it's fine 😄 

Then, [here](https://travis-ci.org/secdev/scapy/) is the scapy travis-ci repo.

Finally, let me explain you how UTscapy works:
- UTScapy itself is an interpreter: you give him code, he'll run it for you and check if any errors occure. It actually parses, manages and runs "test campaigns".
- The "test campaigns" are the ".uts" files. the main one is "regression.uts" and are located mostly in [/test/](https://github.com/secdev/scapy/tree/master/test).

So don't review UTscapy. That's useless, unless you really know what you're doing. You can review the .uts files (especially regression.uts), but once again this is not a bug.

Moreover, when you get something like you've shown over, so only a single line:

> failed A9C2ECFF Truncated netstat -rn output on OS X

It means that the full error log will be shown later in the script. So scroll down to the full error code. You will probably see that a depedency is missing or something like that, which will explain that it does not run on your computer 😃

**Comment by xee5ch** [comment]
I guess I misinterpreted the output to be a much simpler issue than I should have perceived.  That is why the CI passes confused me.  In that case, I guess we're done here.  Sorry!
