### ISSUE TITLE
IPython completion lists files instead of methods

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#4056]
Trying to autocomplete an object not yet created will list all files in the current directory.

<img width="950" alt="Screenshot 2023-07-05 at 13 03 11" src="https://github.com/secdev/scapy/assets/11683796/af7e0d46-c0e4-4f1c-bf65-7926411ad4ce">

**Comment by mspncp** [comment]
The fact that dot-files are listed among the methods seems to be a generic IPython phenomenon, see screenshot. The question in your case is: why doesn't it list the methods of the IP class?

![grafik](https://github.com/secdev/scapy/assets/11467854/457f3b40-d7ea-4826-ae81-61ec33e74a8f)

**Comment by mspncp** [comment]
My guess: can it be that IPythons autocompletion fails because of some problem in the Packet metaclass? Or did it work previously?

![grafik](https://github.com/secdev/scapy/assets/11467854/5966cd46-bf93-4ca2-8bc7-c076706669a2)

**Comment by mspncp** [comment]
Weird... when I load scapy manually from IPython, it works. 🤔 


![grafik](https://github.com/secdev/scapy/assets/11467854/a82d6fc9-eb16-408b-94ca-3b6123ddd612)

**Comment by guedou** [comment]
This patch fixes the issue:
```
 git diff
diff --git a/scapy/main.py b/scapy/main.py
index 25860a94..6a3c5dfd 100644
--- a/scapy/main.py
+++ b/scapy/main.py
@@ -694,7 +694,6 @@ def interact(mydict=None, argv=None, mybanner=None, loglevel=logging.INFO):
                                                                   conf.version)
                 # As of IPython 6-7, the jedi completion module is a dumpster
                 # of fire that should be scrapped never to be seen again.
-                cfg.Completer.use_jedi = False
             else:
                 cfg.TerminalInteractiveShell.term_title = False
             cfg.HistoryAccessor.hist_file = conf.histfile
```

@gpotter2 What's your suggestion?

**Comment by gpotter2** [comment]
I got cold feet at the idea of tweaking completion at this point.

To give some context I have reaallly tried making Scapy/jedi work over there: https://github.com/ipython/ipython/pull/11804 but ended up coming to the same conclusion as Spyder's (the project): jedi completion is just terribly inefficient.

At the time at least you'd feel a HUGE difference in responsiveness pressing tab with and without jedi, this becoming much much worse if the snippet you're trying to complete was somewhat larger. Maybe Jedi improved since then, but in any case the IPython/Jedi integration remains absolute trash (Carreau agreed with me it probably required a complete rewrite..)

So using Jedi might fix some (in my opinion), very minor issues as the one we're discussing here, but this would require some very thorough testing.

**Comment by guedou** [comment]
I agree. Thanks for your answer. Shall we consider adding conf.ipython.use_jedi to configure this behavior ?

**Comment by gpotter2** [comment]
Another thing that's broken with jedi: parameters do not come first.

without: nice !
![image](https://github.com/secdev/scapy/assets/10530980/40c175c4-1f74-4735-be59-8978d4973be8)

with jedi: annoying
![image](https://github.com/secdev/scapy/assets/10530980/79424da1-ca63-4dff-83fa-35ce73f14509)

Honnestly if you try it for more than 10minutes, you eventually realise it's annoyingly slow and broken.

**Comment by mspncp** [comment]
Do I understand your discussion correctly? With jedi, tab completion is slow and buggy and without it, it's fast and buggy as well (e.g, this issue)?

**Comment by guedou** [comment]
Well, my issue only happens with non instantiated object. This is a corner case of the prompt usage. TBH, I don’t think that we need to change the current default behavior.Sent from my iPhoneOn 9 Jul 2023, at 20:34, Matthias St. Pierre ***@***.***> wrote:﻿
Do I understand your discussion correctly? With jedi, tab completion is slow and buggy and without it, it's fast and buggy as well (e.g, this issue)?

**Comment by gpotter2** [comment]
> Shall we consider adding conf.ipython.use_jedi to configure this behavior ?

It seems like a reasonable idea to let the user configure that. If you don't mind letting me PR that, I have some other CLI-related changes coming up.

**Comment by guedou** [comment]
@gpotter2 I am fine if you do the changes.

**Comment by gpotter2** [comment]
See https://github.com/secdev/scapy/pull/4073
