### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by whxloveyrh** [secdev/scapy#407]
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    ans, unans=srp(Ether(dst="FF:FF:FF:FF:FF:FF")/ARP(pdst=lan),timeout=2)
  File "D:\Python27\lib\site-packages\scapy\sendrecv.py", line 383, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "D:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line # **128**, in sndrcv
    os.write(# **1**,, ".")

what it means? '1' indicates ???

**Comment by whxloveyrh** [comment]
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    ans, unans=srp(Ether(dst="FF:FF:FF:FF:FF:FF")/ARP(pdst=lan),timeout=2)
  File "D:\Python27\lib\site-packages\scapy\sendrecv.py", line 383, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "D:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 128, in sndrcv
    os.write(1, ".")

**Comment by p-l-** [comment]
Which version of Scapy are you using?

**Comment by gpotter2** [comment]
@whxloveyrh Please check that you have installed pyreadline.

**Comment by whxloveyrh** [comment]
Traceback (most recent call last):
  File "E:\PythonProject\macaddress.py", line 12, in <module>
    ans, unans = srp(Ether(dst="FF:FF:FF:FF:FF:FF") / ARP(pdst=lan), timeout=2)
  File "D:\Python27\lib\site-packages\scapy\sendrecv.py", line 383, in srp
    a,b=sndrcv(s ,x,*args,**kargs)
  File "D:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 123, in sndrcv
    os.write(1, ".")
# OSError: [Errno 9] Bad file descriptor

--------------------------------------------------------------------------------------------
$pip list
pyreadline (2.1)
scapy (2.3.2)
pcapy (0.10.10)

**Comment by whxloveyrh** [comment]
my python program can run on console, but can't run on python GUI!!!!!
for example:
# lan = '10.10.10.0/24''
ans, unans = srp(Ether(dst="FF:FF:FF:FF:FF:FF") / ARP(pdst=lan), timeout=2)

------
If I add the codes to a python file ,then to run the python file . I can find a error information. but if I direct run the codes, it's right. 

why ?

**Comment by gpotter2** [comment]
> pyreadline (2.1)
> scapy (2.3.2)

First, please update your scapy version to 2.3.3-dev
- download it from github and run `python setup.py install`

Then running python from python GUI is tough, because python close instantly once the programm is finished. You won't actually have time to read the error codes. 
So your programm chashes, that's why you cannot run it from Python GUI.

**Comment by gpotter2** [comment]
@p-l- That can be closed...

**Comment by michalfita** [comment]
@p-l- This problem still exists in 2.3.3... I changed that line to:
`sys.stderr.write("*")`
Which sounds more portable and works in IDLE.

**Comment by gpotter2** [comment]
@michaelharo You should retry using the latest dev version:
https://github.com/secdev/scapy/archive/master.zip

**Comment by ilqxejraha** [comment]
Don't run scapy program in IDLE editor.

**Comment by gpotter2** [comment]
As an update: this thread is outdated. Current scapy dev version has dropped pyreadline to ipython
