### ISSUE TITLE
Undefined method in ASN1 code

### ISSUE THREAD

**Issue by p-l-** [secdev/scapy#408]
Simple test to trigger the bug: `ASN1F_SEQUENCE_OF("test", [], ASN1_INTEGER).randval()`
```
>>> ASN1F_SEQUENCE_OF("test", [], ASN1_INTEGER).randval()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/asn1fields.py", line 370, in randval
    return packet.fuzz(self.asn1pkt())
AttributeError: 'ASN1F_SEQUENCE_OF' object has no attribute 'asn1pkt'
```

**Comment by gpotter2** [comment]
Bad boy: https://github.com/secdev/scapy/commit/c97307f24380a900f09d77458ea262989fac0401#diff-76476b6564a32727e0ed540656418b84R319

**Comment by p-l-** [comment]
Well @mtury was the `ans1pkt` argument supposed to stay, or should we simply use `self.cls()` instead of `self.asn1pkt()`? BTW what type `cls` is supposed to have? Thanks!

**Comment by mtury** [comment]
Indeed using `self.cls()` is fine in this case. `cls` should be a subclass of `ASN1_Packet`.

This is fixed with PR #438.

**Comment by mtury** [comment]
This has become valid: `ASN1F_SEQUENCE_OF("test", [], ASN1P_INTEGER).randval()`

The issue can be closed now.

**Comment by guedou** [comment]
Thanks !
