### ISSUE TITLE
Scapy expands packet when overwriting existing field

### ISSUE THREAD

**Issue by bkoblenz** [secdev/scapy#4109]
### Brief description

scapy seems to add bytes when rewriting dns packet

### Scapy version

2.5.0

### Python version

3.74

### Operating system

Buster

### How to reproduce

```python
import sys
import binascii
import scapy.all as scapy
base_dns = """
ac81818000010006000d0000046d7174740b77656174686572666c6f7703636f
6d0000010001c00c00050001000000e4003c2177656174686572666c6f772d6d
7174742d3930343536396236613839613961643503656c620975732d65617374
2d3109616d617a6f6e617773c01dc032000100010000003c0004369cffb3c032
000100010000003c0004365127ddc032000100010000003c00042cd9c48ec032
000100010000003c0004035c8c32c032000100010000003c000422ee66660000
02000100045d29001401620c726f6f742d73657276657273036e657400000002
000100045d290004016bc0cb000002000100045d2900040166c0cb0000020001
00045d2900040163c0cb000002000100045d2900040164c0cb00000200010004
5d290004016cc0cb000002000100045d2900040165c0cb000002000100045d29
0004016ac0cb000002000100045d2900040169c0cb000002000100045d290004
016dc0cb000002000100045d2900040161c0cb000002000100045d2900040168
c0cb000002000100045d2900040167c0cb
"""

if __name__ == "__main__":
    dns_l = base_dns.split('\n')
    new_dns = ''.join(dns_l)
    dns_b = binascii.a2b_hex(new_dns)
    dns = scapy.DNS(dns_b)
    b_dns_1 = bytes(dns)
    dns_len_1 = len(b_dns_1)
    #print(dns.show(dump=True))
    dns.an[1].rdata = '10.135.0.1'
    b_dns_2 = bytes(dns)
    dns_len_2 = len(b_dns_2)
    #print(dns.show(dump=True))
    if dns_len_1 != dns_len_2:
        print('mismatch old: ' + str(dns_len_1) + ' new: ' + str(dns_len_2))
        for i in range(0, min(dns_len_1, dns_len_2), 20):
            print('dns1[' + str(i) + ']:', binascii.b2a_hex(b_dns_1[i:i+20]))
            print('dns2[' + str(i) + ']:', binascii.b2a_hex(b_dns_2[i:i+20]))
        sys.exit(1)
    sys.exit(0)
```

### Actual result

The new data structure has 520B more than the old one

    mismatch old: 401 new: 921
    dns1[0]: b'ac81818000010006000d0000046d7174740b7765'
    dns2[0]: b'ac81818000010006000d0000046d7174740b7765'
    dns1[20]: b'6174686572666c6f7703636f6d0000010001    c00c'
    dns2[20]: b'6174686572666c6f7703636f6d0000010001    046d'
    dns1[40]: b'00050001000000e4003c2177656174686572666c'
    dns2[40]: b'7174740b77656174686572666c6f7703636f6d00'

### Expected result

There should be the same length with only be a 4B difference with the new data structure encoding the 0a870001 (the hex representation of 10.135.0.1)

### Related resources

None?

**Comment by gpotter2** [comment]
So to explain the behavior (which is perfectly normal):

- Scapy automatically decompresses a DNS packet when dissecting it.
- As long as you do not modify it, it'll keep the cache when calling `bytes()`
- If you modify it, it'll drop its cache and return the un-compressed DNS packet on build
- To build a compressed DNS packet, you can call `dns_compress` on the packet before building it: `bytes(dns_compress(pkt))`, and you'll recover the initial, compressed packet.

That being said, there's a dumb bug that compresses 1-octet strings into 2-octet strings (so in your case the packet does 401->413), which I just fixed in https://github.com/secdev/scapy/pull/4110

**Comment by bkoblenz** [comment]
This is quite helpful.  Thanks.

I am not quite sure I understand the point of the compression, though.

Is it equally valid to build up layers using compressed and uncompressed dns packets?
Is the fact that my packet (with dns_compress) still grew to 413 a non-issue (at least wrt correctness)?

What started me down this path is that modifying packets (I was initially modifying tcp ack values trying to intercept and filter out some packets) was my modified packets were not visible on the interface using tcpdump.  So I figured I would intercept the dns response, to point to me and create a proxy so I do not have to deal with the tcp acks.  While I could see the dns response on tcpdump, it was not clear to me that the dns requestor was respecting the response so I thought maybe I got the response incorrectly crafted.

thanks
-brian

**Comment by gpotter2** [comment]
> Is it equally valid to build up layers using compressed and uncompressed dns packets?

DNS clients / servers understand both uncompressed and compressed packets. I'm not sure I get your question. They just use compression for efficiency but it's not compulsory.

> still grew to 413 a non-issue

That is a bug. fixed in https://github.com/secdev/scapy/pull/4110. Just unrelated to your initial question.
