### ISSUE TITLE
ignoring static ip neighbour (ARP/NDP) entry

### ISSUE THREAD

**Issue by Thyna9** [secdev/scapy#4122]
### Brief description

ignoring static ip neighbour (ARP/NDP)

### Scapy version

2.5.0.dev152

### Python version

3.11.5

### Operating system

Ubuntu 22.04.3 LTS

### How to reproduce

1. Statically specify the ipv6 neighbor (destination host):
2007::1 dev enp0s8 lladdr 08:00:27:a1:cd:f0 PERMANENT
2. Run the script:
#!/bin/python3

from scapy.all import *
from scapy.contrib.gtp import *

ipv6 = IPv6(src="2007::2",dst="2007::1")
udp = UDP(sport=2152, dport=2152)

while True:
    sendp(Ether()/ipv6/udp/"Hello World!")

### Actual result

“Who has” NDP-packets are sent. After having no answer - broadcast dst MAC-address (ff:ff:ff:ff:ff:ff) is set in Hello-world packet. When sending ping packets who has are not sent.

### Expected result

Hello-world packet is sent with specific dst MAC-address (08:00:27:a1:cd:f0) according to static ip neighbour entry.

**Comment by guedou** [comment]
Scapy does not read the NDP cache from the OS. You need to specify this within Scapy with:
```python
conf.netcache.in6_neighbor[ip6] = mac
```
