### ISSUE TITLE
Duplicate `IP` packet on ICMP Ping

### ISSUE THREAD

**Issue by Newcool1230** [secdev/scapy#4127]
### Brief description

When sending ICMP ping request, an additional localhost IP packet is attached which does not reach the server.

### Scapy version

2.5.0

### Python version

3.10.5

### Operating system

Windows 10 pro 64-bit

### How to reproduce

Trying to make a simple ping request similar to cmd. The request sent via scapy shows up in wireshark with another a localhost packet attached, there is also no reply from the ping. The cmd `ping` command however works like normal. Sends and receives the ping requests.

Python:
```python
resp = sr1(IP(dst='google.com') / ICMP(id=1, seq=RandShort()), timeout=10)
print(resp)
```

CMD:
```
ping google.com
```

### Actual result

```
Begin emission:
Finished sending 1 packets.
.....
Received 7942 packets, got 0 answers, remaining 1 packets
None
```

![Wireshark_FrnwoVS6HH](https://github.com/secdev/scapy/assets/10657253/a55c528d-4914-43c0-ad84-fb35a0e92ac9)

### Wireshark scapy:
![image](https://github.com/secdev/scapy/assets/10657253/f42d9f0e-f9bb-4f4e-8a6d-64c057816092)

### Wireshark cmd ping:
![image](https://github.com/secdev/scapy/assets/10657253/d24a09b9-7b31-4644-b51a-f61b85fa025d)

**Comment by p-l-** [comment]
Hi there!
Thanks for your report. Could you try again with the current development version of Scapy? Also, could you report the output of `conf.route`?

**Comment by ResuUman** [comment]
### Scapy version
2.4.4-4ubuntu1 (also: 2.5.0+dfsg-2)

### Python version
3.10.12-1~22.04.3 (also: 3.11.4)

### Operating system
Ubuntu: bookworm/sid (also Kali)

### Additional environment information
>>> scapy.all.conf.route
Network      Netmask        Gateway      Iface  Output IP      Metric
0.0.0.0      0.0.0.0        192.168.2.1  eno1   192.168.2.103  100
127.0.0.0    255.0.0.0      0.0.0.0      lo     127.0.0.1      1
169.254.0.0  255.255.0.0    0.0.0.0      eno1   192.168.2.103  1000
192.168.2.0  255.255.255.0  0.0.0.0      eno1   192.168.2.103  100

>>> scapy.all.conf.iface
'eno1'

### How to reproduce
sudo python3
>>> from scapy.layers.inet import IP, TCP, ICMP
>>> import scapy.all
>>> restp = scapy.all.sr1(IP(dst='1.1.1.1')/ICMP(), timeout=3)
Begin emission:
Finished sending 1 packets.
.............................
Received 29 packets, got 0 answers, remaining 1 packets

### Expected result
>>> restp = scapy.all.sr1(IP(dst='192.168.2.1')/ICMP(), timeout=3)
Begin emission:
Finished sending 1 packets.
..*
Received 3 packets, got 1 answers, remaining 0 packets

**Comment by gpotter2** [comment]
Not reproducible as-is and too broad. Please make sure you have npcap installed on Windows. Closing.

**Comment by ResuUman** [comment]
> Not reproducible as-is and too broad. Please make sure you have npcap installed on Windows. Closing.

OK, no problem. Have you noticed that on local network it worked for me and for internet it didn't?
