### ISSUE TITLE
scapy.contrib.http2.HPackHdrTable.parse_txt_hdrs should convert string arg to bytes

### ISSUE THREAD

**Issue by aentwist** [secdev/scapy#4130]
### Brief description

The code to reproduce this is taken directly from the [HTTP/2 example](https://github.com/secdev/scapy/blob/master/doc/notebooks/HTTP_2_Tuto.ipynb) (which does not work as-is, but is a *fantastic* starting point).

```python
http2.HPackHdrTable().parse_txt_hdrs(
    """:method GET
:path /
:authority www.google.com
:scheme https
accept-encoding: gzip, deflate
accept-language: en-US
accept: text/html
user-agent: Scapy HTTP/2 Module
""",
    stream_id=1,
    max_frm_sz=1 << 14,
    max_hdr_lst_sz=1 << 16,
    is_sensitive=lambda hdr_name, hdr_val: hdr_name in ["cookie"],
    should_index=lambda x: x
    in [
        "x-requested-with",
        "user-agent",
        "accept-language",
        ":authority",
        "accept",
    ],
)
```

gives

```
Traceback (most recent call last):
  File "/redacted/src/main.py", line 122, in <module>
    qry_frontpage = tblhdr.parse_txt_hdrs(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/redacted/.venv/lib/python3.11/site-packages/scapy/contrib/http2.py", line 2663, in parse_txt_hdrs
    sio = BytesIO(s)
          ^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

this line can be found here

https://github.com/secdev/scapy/blob/4b386fffbbdfcc46f41433e7f96ca00488ac30c6/scapy/contrib/http2.py#L2667

Despite the type hint of string, it appears this really wants bytes as it currently is. Converting seems to solve the problem.

```python
""":method GET
:path /
:authority www.google.com
:scheme https
accept-encoding: gzip, deflate
accept-language: en-US
accept: text/html
user-agent: Scapy HTTP/2 Module
"""
```

to 

```python
bytes(
    """:method GET
:path /
:authority www.google.com
:scheme https
accept-encoding: gzip, deflate
accept-language: en-US
accept: text/html
user-agent: Scapy HTTP/2 Module
""",
    "UTF-8"
)
```

Either correct the type hint or do the conversion? Also, I am just doing some hacking and do not know what encoding the fix should use. I just decided to use the ubiquitous UTF-8.

### Scapy version

2.5.0

### Python version

3.11.5

### Operating system

Debian 12 on WSL2

### How to reproduce

Use the method with a string

### Actual result

TypeError

### Expected result

Conversion from string to byte is done inside the method, if it is necessary. String arguments should work.

**Comment by p-l-** [comment]
Thanks for this report; you are totally right. This will be fixed in #4131 by (documenting and) accepting both `str` and `bytes` for this parameter.
