### ISSUE TITLE
Starting scapy on Windows without a pcap library unconditionally logs a warning

### ISSUE THREAD

**Issue by ctrob67** [secdev/scapy#4171]
### Brief description

I am using scapy for offline processing, without a pcap library installed, and when scapy is imported the message "No libpcap provider available ! pcap won't be used" is logged.

I've looked through the code and I can see that this can only occur if conf.use_pcap is true.  This starts off as false but is unconditionally set to True in line 58 of arch/windows/__init__.py.

I suspect this is a bug as the line is not commented.

It's possible to workaround this by disabling warnings around the first scapy import , which is less than ideal, but the overall impact of this pretty low.

### Scapy version

2.5.0

### Python version

3.12.0

### Operating system

Windows 10

### How to reproduce

>>> from scapy.config import conf
>>> conf.use_pcap = False
WARNING: No libpcap provider available ! pcap won't be used

**Comment by gpotter2** [comment]
I would argue that this is by design. Most users don't read the doc and therefore fail to see they're missing npcap on windows.
You can however disable only loading warnings (after https://github.com/secdev/scapy/pull/4255) which should make this rather acceptable (as other warnings remain):
```
from scapy.config import conf
log_loading.setLevel(logging.ERROR)
```
