### ISSUE TITLE
Binding layers with FlagsField as text results in TypeError when dissecting

### ISSUE THREAD

**Issue by superuserx** [secdev/scapy#4183]
### Brief description

There is an issue when binding layers with a FlagsField and passing the flags argument as text.
Dissecting such a packet results in a 

> TypeError: While dissecting field 'flags': unsupported operand type(s) for &: 'bytes' and 'int'

I'm not sure if this is an issue with CAN class or a general problem. But I couldn't find another packet class with similar FlagsField to test.

### Scapy version

2.5.0.dev15

### Python version

3.8.10

### Operating system

Linxu 5.10

### How to reproduce

```
load_layer('can')
load_contrib('automotive.uds')

bind_layers(CAN, UDS, identifier=0x18fef500, flags=4)
pkt = CAN()/UDS()
hexdump(pkt) # works

bind_layers(CAN, UDS, identifier=0x18fef500, flags='extended')
hexdump(pkt) # Error
```

### Actual result

0000  98 FE F5 00 00 00 00 00 00                       .........
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-fc8fcbd7dbaa> in <module>
      8
      9 bind_layers(CAN, UDS, identifier=0x18fef500, flags='extended')
---> 10 hexdump(pkt) # Error

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/utils.py in hexdump(p, dump)
    275     """
    276     s = ""
--> 277     x = bytes_encode(p)
    278     x_len = len(x)
    279     i = 0

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/compat.py in bytes_encode(x)
    241     if isinstance(x, str):
    242         return x.encode()
--> 243     return bytes(x)
    244
    245

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/packet.py in __bytes__(self)
    585     def __bytes__(self):
    586         # type: () -> bytes
--> 587         return self.build()
    588
    589     def __div__(self, other):

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/packet.py in build(self)
    726         :return: string of the packet with the payload
    727         """
--> 728         p = self.do_build()
    729         p += self.build_padding()
    730         p = self.build_done(p)

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/packet.py in do_build(self)
    706         if not self.explicit:
    707             self = next(iter(self))
--> 708         pkt = self.self_build()
    709         for t in self.post_transforms:
    710             pkt = t(pkt)

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/packet.py in self_build(self)
    685                     except (AttributeError, IndexError):
    686                         pass
--> 687                     raise ex
    688         return p
    689

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/packet.py in self_build(self)
    676             else:
    677                 try:
--> 678                     p = f.addfield(self, p, val)
    679                 except Exception as ex:
    680                     try:

/usr/local/lib/python3.8/dist-packages/scapy-2.5.0.dev15-py3.8.egg/scapy/fields.py in addfield(self, pkt, s, ival)
   2280             v = 0
   2281         v <<= self.size
-> 2282         v |= val & ((1 << self.size) - 1)
   2283         bitsdone += self.size
   2284         while bitsdone >= 8:

TypeError: While dissecting field 'flags': unsupported operand type(s) for &: 'bytes' and 'int'

### Expected result

0000  98 FE F5 00 00 00 00 00 00                       .........
0000  98 FE F5 00 00 00 00 00 00                       .........

**Comment by gpotter2** [comment]
This is a well known issue but be careful of the implications. Binding on a FlagsField means that the value of the entire flag field must be the one you provided. If you bind on `A` and the value is `A+B`, it will not work. This is why we generally never bind on FlagsField but rather use a `guess_payload_class`.

**Comment by superuserx** [comment]
I'm not sure if I understand the issue completely. Is it better to use a numerical value when binding or not binding flags at all and add the needed flag on each packet afterwards?

**Comment by polybassa** [comment]
gpotter2 means, it's in general not a good idea to use a FlagsField in bind_layers. If "your desired" Flag and some other "Flag" is set, bind_layers will not work as intended.

**Comment by superuserx** [comment]
ok, got it. Thanks!
