### ISSUE TITLE
TCP Retransmission causes scapy to exit

### ISSUE THREAD

**Issue by stulle123** [secdev/scapy#4197]
### Brief description

Hi,

I have a  [pcap file](https://github.com/secdev/scapy/files/13478908/bar.zip) where a TCP Retransmission (the 7th packet) causes scapy to exit with the following error message: `WARNING: Socket <scapy.utils.PcapReader object at 0x000001FE8B3192D0> failed with 'not enough values to unpack (expected 3, got 2)'. It was closed.`

Scapy stops processing the pcap file after that.

The bug was introduced with https://github.com/secdev/scapy/pull/4082.

Cheers,

stulle123

### Scapy version

2.5.0.dev157

### Python version

3.11.2

### Operating system

Windows 10

### How to reproduce

```python
from scapy.config import conf
from scapy.main import load_layer
from scapy.sendrecv import sniff
from scapy.sessions import TCPSession

conf.tls_session_enable = True
load_layer("tls")

capture = sniff(
    offline="bar.pcap",
    session=TCPSession,
)
```

**Comment by gpotter2** [comment]
Should be fixed in https://github.com/secdev/scapy/pull/4224
