### ISSUE TITLE
[Windows] Cannot start using scapy.bat

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#420]
Hey, I tried to install python + scapy on another computer, but i've installed python in a **folder with a space in its title**...
Running scapy.bat will crash... Tiny fix, in the file bin/scapy.bat
```
python %~dp0\scapy %*
```
replaced with
```
python "%~dp0\scapy %*"
```
(added quotes)
**And you can do the same thing in UTScapy.bat**

I cannot create a PR right now, and I really don't mind if you fix it yourself :)

**Comment by p-l-** [comment]
I have also changed `tests/run_tests.bat`. Does it look OK?
