### ISSUE TITLE
Why after the first ARP scan with scapy I don't have connectivity to another hosts in the network even to internet?

### ISSUE THREAD

**Issue by uri3l593** [secdev/scapy#4212]
### Brief description

After the first ARP scan with scapy I don't have connectivity to another hosts on the network even to internet. This doesn't happen when performing an ARP ping scan to virtual.

### Scapy version

2.4.4, 2.5.0

### Python version

3.9.2

### Operating system

Linux 6.1.0-1

### How to reproduce

First ARP scan
```
>>> from scapy.all import *
>>> ans, unans = srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst="192.168.1.0/24"), iface=wlan0, timeout=2)
Begin emission:
Finished sending 256 packets.
*****......
Received 11 packets, got 5 answers, remaining 251 packets
>>> ans.summary(lambda s,r: r.sprintf("%Ether.src% %ARP.psrc%") )
28:2e:a4:7f:d0:b6 192.168.1.1
cc:ff:a4:2a:5b:46 192.168.1.2
ce:ae:13:e6:7c:73 192.168.1.7
e0:56:cb:8f:5f:60 192.168.1.11
a0:d3:3a:3f:fa:1e 192.168.1.20
```
Second ARP scan
```
>>> ans, unans = srp(Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(pdst="192.168.1.0/24"), iface=wlan0, timeout=2)
Begin emission:
```

**Comment by gpotter2** [comment]
Looks like your switch is shutting you down (or similar). Not really a Scapy issue, good luck with troubleshooting !
