### ISSUE TITLE
Compressed DNS packets can become malformed if they are edited without calling `clear_cache` first

### ISSUE THREAD

**Issue by evverx** [secdev/scapy#4216]
### Brief description

Compressed DNS packets can become malformed because their raw packet caches don't get fully invalidated when specific resource records are edited.

(It's possible to get it around by calling `clear_cache` explicitly before packets are instantiated though)

### Scapy version

0dd08cd064134bcbf7c6bfbdbd356b69cdee05ac

### Python version

3.11.6

### Operating system

Linux version 6.6.7-100.fc38.x86_64

### How to reproduce

```python
p = DNS(b'\x00\x00\x01\x00\x00\x00\x00\x02\x00\x00\x00\x00\x03H-1\x05local\x00\x00\x05\x00\x01\x00\x00\x00\x00\x00\x06\x03H-2\xc0\x10\xc0!\x00\x05\x00\x01\x00\x00\x00\x00\x00\x02\xc0\x0c')
p[DNS].an[0].rrname = 'H'
```

### Actual result

The packet is malformed because the raw packet cache of the second resource record contains pointers to the original resource record:
```sh
tdecode(Ether()/IP()/UDP()/p)
...
    Answers
        H: type CNAME, class IN, cname H-2.local
            Name: H
            Type: CNAME (Canonical NAME for an alias) (5)
            Class: IN (0x0001)
            Time to live: 0 (0 seconds)
            Data length: 11
            CNAME: H-2.local
[Malformed Packet: DNS]
    [Expert Info (Error/Malformed): Malformed Packet (Exception occurred)]
        [Malformed Packet (Exception occurred)]
        [Severity level: Error]
        [Group: Malformed]
```

### Expected result

The raw packet cache should probably be fully invalidated to let Scapy generate the correct packet
```sh
tdecode(Ether()/IP()/UDP()/p)
...
    Answers
        H: type CNAME, class IN, cname H-2.local
            Name: H
            Type: CNAME (Canonical NAME for an alias) (5)
            Class: IN (0x0001)
            Time to live: 0 (0 seconds)
            Data length: 11
            CNAME: H-2.local
        H-2.local: type CNAME, class IN, cname H-1.local
            Name: H-2.local
            Type: CNAME (Canonical NAME for an alias) (5)
            Class: IN (0x0001)
            Time to live: 0 (0 seconds)
            Data length: 11
            CNAME: H-1.local
```

**Comment by gpotter2** [comment]
Hmm.
I need to think about how to fix this properly. In the very specific case of DNS compression, this is indeed buggy but in other cases it sounds reasonable to have inner packets cached despite changing the outer packet (your example here).
