### ISSUE TITLE
Setting bytes of OCSP_ResponseData() causes BER_decoding_Error when OCSPResponse status is revoked

### ISSUE THREAD

**Issue by wasmachensachen98** [secdev/scapy#4226]
### Brief description

When setting the bytes of OCSP_ResponseData() a BER_decoding_Error occurs when OCSPResponse status is revoked the last bytes of the certStatus in the tbsResponseData.responses are not parsed correctly

### Scapy version

2.5.0

### Python version

3.7.0

### Operating system

Windows 10

### How to reproduce

```python
from scapy.asn1.asn1 import (ASN1_BIT_STRING, ASN1_ENUMERATED, ASN1_OID)
from scapy.layers.x509 import (
    OCSP_Response, OCSP_ResponseBytes, 
    OCSP_ResponseData, X509_AlgorithmIdentifier)
from cryptography.x509.ocsp import load_der_ocsp_response
from scapy.packet import Raw
from scapy.layers.http import HTTP, HTTPResponse
from scapy.layers.inet import TCP, IP, Ether
from scapy.utils import wrpcap


def http_response(ocsp_response: bytes):
    http_response_header = HTTPResponse()
    http_response_data = Raw(ocsp_response)
    
    http_response_header.Status_Code = b'200'
    http_response_header.Content_Type = b'application/ocsp-response'
    http_response_header.Content_Length = f'{len(ocsp_response)}'.encode("utf-8")
    
    http_response = Ether() /IP() / TCP() / HTTP() / http_response_header / http_response_data
    return http_response

der_ocsp_revoked_response_in_hex = (
    '308201550a0100a082014e3082014a06092b06010505073001010482013b3'
    '08201373081dfa2160414117f8e44bbe97fca27fe4790895c18ea0ea52357'
    '180f32303234303132313133333730385a30818e30818b304d300906052b0'
    'e03021a050004140bafcc2324b8b0f8b0322c9a506e395653571414041411'
    '7f8e44bbe97fca27fe4790895c18ea0ea5235702141026996a09aab93ede0'
    '6b62362a9e44741071b32a116180f32303234303132303133333730385aa0'
    '030a0101180f32303234303132313133333730385aa011180f32303234303'
    '132323133333730385aa1233021301f06092b060105050730010204120410'
    'fcb692df5ef3037b09487d129faa135e300a06082a8648ce3d04030203470'
    '0304402207e4a62685c118d8ee360dd40803e3323db2e74416b2e1e8bd177'
    '88696edb18c7022038107a771a115f5cf0d6f5da8307773112ef26c2a9a04'
    '436887fd45b4fd3ceb2'

)
ocsp_reponse_directory = 'ocsp_response'

wrpcap("ocsp_response.pcap", http_response(bytes.fromhex(der_ocsp_revoked_response_in_hex)))
ocsp_resonse_original = load_der_ocsp_response(bytes.fromhex(der_ocsp_revoked_response_in_hex))


OCSP_ResponseData(ocsp_resonse_original.tbs_response_bytes)
``` 

### Actual result

```
### Remaining ###
b'\xa0\x03\n\x01\x01'
```

**Comment by wasmachensachen98** [comment]
I believe it could be caused by setting the revocation reason. Because similarly:
```python
from datetime import datetime, timedelta

new_cert_status = OCSP_RevokedInfo()
revocation_time = datetime.utcnow() - timedelta(days=1)
new_cert_status.revocationTime = ASN1_GENERALIZED_TIME(revocation_time.strftime('%Y%m%d%H%M%SZ'))
# When adding revocationReason the fails to parse when sending
# new_cert_status.revocationReason = X509_ExtReasonCode(cRLReason=ASN1_ENUMERATED(0))
ocsp_cert_status = OCSP_CertStatus(certStatus=new_cert_status)
``` 
With the revocation reason added i get the parsing error when sending the ocsp  

`Error parsing response
19224:error:0D084078:asn1 encoding routines:asn1_template_ex_d2i:explicit tag not constructed:../openssl-1.1.1i/crypto/asn1/tasn_dec.c:489:Field=revocationReason, Type=OCSP_REVOKEDINFO
19224:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1i/crypto/asn1/tasn_dec.c:637:
19224:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../openssl-1.1.1i/crypto/asn1/tasn_dec.c:272:Field=value.revoked, Type=OCSP_CERTSTATUS
19224:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1i/crypto/asn1/tasn_dec.c:646:Field=certStatus, Type=OCSP_SINGLERESP
19224:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1i/crypto/asn1/tasn_dec.c:614:Field=responses, Type=OCSP_RESPDATA
19224:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../openssl-1.1.1i/crypto/asn1/tasn_dec.c:646:Field=tbsResponseData, Type=OCSP_BASICRESP
19224:error:0D0C706E:asn1 encoding routines:ASN1_item_unpack:decode error:../openssl-1.1.1i/crypto/asn1/asn_pack.c:60:`

I hope I could help.

**Comment by gpotter2** [comment]
fixed in https://github.com/secdev/scapy/pull/4240
