### ISSUE TITLE
Regarding warning Unknown crypto suite from ClientMasterKey

### ISSUE THREAD

**Issue by russdm** [secdev/scapy#4248]
### Brief description

Segmented packets are read in and misinterpreted as SSLv2 handshakes.
Packets are often segmented TLS application Data packets when compared to Wireshark.

### Scapy version

2.5.0

### Python version

3.12.1

### Operating system

Windows 11

### Additional environment information

Develop a class in the SSLv2 handshake that recognizes and ignores segmented packets.

### How to reproduce

sniff TLS packets and segmented TLS packets get misinterpreted as SSLv2_handshakes.

**Comment by gpotter2** [comment]
Please provide a pcap and the code you're using to sniff.

**Comment by russdm** [comment]
See the following I've raised the warning for UnknownCipherSuite as an error, and have been logging them in my packet captures. In comparison to the packet captures in Wireshark. Application Data is being read as SSLv2ClientMasterkey.
See the zip file containing code I'm using to capture packets with warning raised as error and logged.
[Tests for unknown cipher suite.zip](https://github.com/secdev/scapy/files/14143146/Tests.for.unknown.cipher.suite.zip)

**Comment by russdm** [comment]
Just a note the first two captures in the log file are in the pcap. To save longevity of analysis. Only meant to do two to save having to analyze a bunch of packets.

**Comment by russdm** [comment]
Information regarding the SSLv2 header if your interested.
[SSLv2 header.txt](https://github.com/secdev/scapy/files/14158359/SSLv2.header.txt)

**Comment by gpotter2** [comment]
Just use
```
from scapy.sessions import TCPSession
sniff(prn=pktsniff, session=TCPSession)
```
