### ISSUE TITLE
README notes support for python3.9, but release 2.5.0 notes support also for 3.10

### ISSUE THREAD

**Issue by PaarthShah** [secdev/scapy#4252]
### Brief description

https://github.com/secdev/scapy/releases/tag/v2.5.0 states that `scapy` has support for python3.10 as well as python3.9.

But the README only says up to 3.9: https://github.com/secdev/scapy/blob/86e176428c55f569585890b466dbd9719c19147c/README.md?plain=1#L29

### Scapy version

N/a

### Python version

N/a

### Operating system

N/a

### How to reproduce

N/a

**Comment by gpotter2** [comment]
fixed in https://github.com/secdev/scapy/commit/3affdba9f3aa1668dd16259fa56e720653114aa9
