### ISSUE TITLE
Windows - WARNING: Mac address to reach destination not found. Using broadcast.

### ISSUE THREAD

**Issue by temp-defualt** [secdev/scapy#427]
hi i just updated to the latest version of scapy and i keep getting this msg for each packet how can i fix this ? is it the normal behavior ?

**Comment by p-l-** [comment]
Hi, more context would be useful here: updated from which version to which version? what is your Windows / Python version? What is the exact command you are using, what is the exact output?

**Comment by temp-defualt** [comment]
sorry my bad :) 
I am using python 2.7.6 UP to 2.7.12 as a portable on windows 10 / 8 / 7 / XP :) 
and never mind the upgrade on a clean install i cant get this to work :(

**Comment by p-l-** [comment]
No, not "never mind", it's much easier to handle this issue if we know which version works and which version is broken for you.

Also, we still need your exact command and output.

**Comment by temp-defualt** [comment]
hi judging by your short answers I'm assuming you did not understand me so lets start fresh.
I recently updated a portable python + scapy installation script to include the latest version of scapy meaning i have machines (100+) running on windows 10 / 8 / 7 / XP with python 2.7.6 mainly and some with other 2.7 versions up to 2.7.12

any packet sent doesn't find a mac address and uses broadcast which is strange...
this raises two main questions :
1) is scapy not having the host arp table the default behavior?  
2) why isnt scapy learning from the answer the desired mac address ?

the code im using (this will fail the packet will be sent but you will never get an ICMP response):
p = IP(dst="www.google.com")/ICMP(type="echo-request")
send(p)

result:
WARNING: Mac address to reach destination not found. Using broadcast.
.
Sent 1 packets.

*** note that adding Ether layer and manually setting the "dst" to routers mac will work

I would like to fix this by at least "teaching" scapy the router mac address dynamically and more preferably to add to scapy arp cache the host arp table ...

**Comment by p-l-** [comment]
By latest version, do you mean latest released version (2.3.3), or current development version?
