### ISSUE TITLE
PythonCANSocket recv_raw function can't pass timout parameter to python-can

### ISSUE THREAD

**Issue by Calmea** [secdev/scapy#4287]
### Brief description

PythonCANSocket recv_raw function can't pass timout parameter to python-can
<img width="641" alt="scapy issue" src="https://github.com/secdev/scapy/assets/31396966/1fa19f91-3023-4fd4-bb33-1df256ce6844">

### Scapy version

2.5.0

### Python version

3.10.11

### Operating system

Windows10

### How to reproduce

<img width="656" alt="example script" src="https://github.com/secdev/scapy/assets/31396966/e1a7cc74-3c23-4b84-92ae-9754380c354f">

### Actual result

see script report a exception

### Expected result

recv(timeout=5) function will return after 5 seconds without receive specified frame message.

**Comment by polybassa** [comment]
Hi, thanks for your issue.

In Scapy, it's not desired to pass `timeout=x` to `recv` of a SuperSocket. If you want to receive with a timeout, use
`can_interface.sniff(timeout=5)`
