### ISSUE TITLE
Documentation about reading pcap is a bit short

### ISSUE THREAD

**Issue by JulienPalard** [secdev/scapy#430]
Doc states that:

```
>>> a=rdpcap("/spare/captures/isakmp.cap")
>>> a
<isakmp.cap: UDP:721 TCP:0 ICMP:0 Other:0>
```

Is enough, but I had to grep to find rdpcap, and importing it as:
```
from scapy.utils import rdpcap
```

Is not enough as the packet module is initializing some configuration and is not imported by utils, so if I don't import it myself like `from scapy import packet` I'm getting:

```
Traceback (most recent call last):
  File "/home/mdk/.local/lib/python3.5/site-packages/scapy/utils.py", line 825, in read_packet
    p = self.reader.LLcls(s)
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wifi.py", line 32, in <module>
    main()
  File "wifi.py", line 29, in main
    print(rdpcap('wifi.cap'))
  File "/home/mdk/.local/lib/python3.5/site-packages/scapy/utils.py", line 557, in rdpcap
    return pcap.read_all(count=count)
  File "/home/mdk/.local/lib/python3.5/site-packages/scapy/utils.py", line 837, in read_all
    res = RawPcapReader.read_all(self, count)
  File "/home/mdk/.local/lib/python3.5/site-packages/scapy/utils.py", line 607, in read_all
    p = self.read_packet()
  File "/home/mdk/.local/lib/python3.5/site-packages/scapy/utils.py", line 831, in read_packet
    p = conf.raw_layer(s)
TypeError: 'NoneType' object is not callable
```

`from scapy.all import rdpcap` works, so it should probably be documented to avoid future users to follow the same path as mine. Yes I know that `scapy.all` *is* documented, but only in "extending" which is after "advanced usage", but most users will probably hit the problem while reading "simple usage".

**Comment by p-l-** [comment]
Hi,

Thanks for reporting this.

The documentation part you are quoting is related to the Scapy shell (that you get when you run `scapy`, not when you run `python` and import Scapy as a module), so you don't need an `import` statement at all.

For this reason I'm closing this issue, but feel free to update it if you disagree or want to discuss this further.

**Comment by JackWzh** [comment]
In 2.4.0(python 3.6.5) there is no module named "utils" in scapy, so where should I get the rdpcap function from in python? @p-l- @JulienPalard 

Is there any documentation about what python apis we can use and its location?

I also wanna know why scapy choose to work in shell style instead of python module style, where does this philosophy come from?
