### ISSUE TITLE
OSError: [Errno 9] Bad file Descriptor

### ISSUE THREAD

**Issue by avdssrk** [secdev/scapy#4316]
I am trying to send packets through Ethernet using scapy in python. When I try to send the packets from Scapy(from terminal) it is reflecting in Wireshark. But when i try to send the data from a python code I am getting this below error.

**WARNING: Wireshark is installed, but cannot read manuf !
Sending 0 packet
Traceback (most recent call last):
  File "C:\Users\.\.\.\Ethernet\eth_test.py", line 27, in <module>
    sendp(npkt)
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\scapy\sendrecv.py", line 478, in sendp
    return _send(
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\scapy\sendrecv.py", line 415, in _send
    results = __gen_send(socket, x, inter=inter, loop=loop,
  File "C:\Users\.\AppData\Local\Programs\Python\Python310\lib\site-packages\scapy\sendrecv.py", line 382, in __gen_send
    os.write(1, b".")
OSError: [Errno 9] Bad file descriptor**

I am using python 3.10.10 and scapy version 2.5.0.
The code I am using
``` 
# Import the packages required
from scapy.all import*
from struct import *
import time
import random

num_packets = 100
udp = 17

# Ethernet hardware address
src_mac = 'aa:bb:cc:dd:ee:ff'
dst_mac = 'ff:a0:ee:b1:cd:ef'

# Network layer
src_ip = '192.168.0.1'
dst_ip = '192.168.0.2'

# layer 2
#dport = 54321


for x in range(0,num_packets):
    random.seed()
    msg = 'Hello World..! Sending the data to virtex-6 fpga. Can you send the acknowledge'
    npkt = Ether(src=src_mac,dst=dst_mac)/IP(src=src_ip,dst=dst_ip,proto=udp)/UDP(dport=54321,sport=15293)/Raw(load = msg)
    print("Sending %i packet"%(x))
    sendp(npkt)

```

Please help me with this issue, what should I do in this case?

**Comment by ralsei38** [comment]
Are you running this piece of code using IDLE by any chance ?
If so, you could try to run this  write this snippet in a python file, and run it from cmd or powershell

**Comment by gpotter2** [comment]
Hi, please **fill the issue template**.

**Comment by avdssrk** [comment]
Thanks for the reply. It is working with cmd.
