### ISSUE TITLE
Send/Receive Problem with ICMPv6 reply packets with IPv6ExtHdrDestOpt

### ISSUE THREAD

**Issue by jeremy-duncan** [secdev/scapy#4324]
Testing with Scapy version 2.5.0.dev302, I noticed that there is an additional test on the received answer if the sent packet has an IPv6 Destination Options header. Per sec 4.2 of RFC 8200 there is absolutely no requirement for a Destination Options Header to have a Home Address Option per the logic below - so the check below doesn't seem to be RFC compliant. This is only when doing Mobile IPv6. There are numerous acceptable types that are not Mobile IPv6.

```        if self.nh == 60 and isinstance(self.payload, IPv6ExtHdrDestOpt):
            foundhao = None
            for o in self.payload.options:
                if isinstance(o, HAO):
                    foundhao = o
            if foundhao:
                nh = self.payload.nh  # XXX what if another extension follows ?`
                ss = foundhao.hoa
```
As you can see there is no other mechanism to set the self.payload.nh if there is no hoa option. This means it an ICMPv6EchoReply won't be caught as an answer as it doesn't see this layer.

We think this might be mistake as there where the statement for self.payload.nh is referenced. We recommend this be changed to show this instead:
```        if self.nh == 60 and isinstance(self.payload, IPv6ExtHdrDestOpt):
            foundhao = None
            for o in self.payload.options:
                if isinstance(o, HAO):
                    foundhao = o
            if foundhao:
                ss = foundhao.hoa
            nh = self.payload.nh  # XXX what if another extension follows ?`
```

**Comment by gpotter2** [comment]
Thanks for the report.  Could you provide an example packet and its (undetected) answer? This will be useful to add some regression tests

**Comment by jeremy-duncan** [comment]
attached is the PCAP.
Also, the scapy string to generate the packet is this:
``srp(Ether(dst='00:50:56:84:1c:14') / IPv6(tc=0, fl=0, nh=60, hlim=255, dst='fe80::250:56ff:fe84:1c14', src='fe80::26', version=6) / IPv6ExtHdrDestOpt(nh=58, len=0, options=Pad1(b'\x00')/Pad1(b'\x00')/Pad1(b'\x00')/Pad1(b'\x00')/Pad1(b'\x00')/Pad1(b'\x00'))/ICMPv6EchoRequest(), iface='ens224', timeout=2)
``
[issue_4324.zip](https://github.com/secdev/scapy/files/14654632/issue_4324.zip)

**Comment by gpotter2** [comment]
Thanks for the report. This should be fixed in https://github.com/secdev/scapy/pull/4333
