### ISSUE TITLE
send(generator) skips first packet

### ISSUE THREAD

**Issue by r3d3** [secdev/scapy#4336]
### Brief description

send() skips first packet when used with generators

### Scapy version

2024.03.24

### Python version

3.11

### Operating system

Linux 6.1

### How to reproduce

```
def g():
  yield IP(dst='127.0.0.1')/ICMP(id=1)
  yield IP(dst='127.0.0.1')/ICMP(id=2)

send(g())
```

### Actual result

Sent 1 packets.

### Expected result

Sent 2 packets.

**Comment by gpotter2** [comment]
This isn't supported. In Scapy you would do:
```python
send(IP(dst='127.0.0.1')/ICMP(id=(1,2)))
```
