### ISSUE TITLE
As of NetBSD 10.0, it is possible to send packets via bpf through loopback devices

### ISSUE THREAD

**Issue by dhgutteridge** [secdev/scapy#4350]
### Brief description

Just mentioning that with NetBSD 10.0, you should be able to send packets via bpf through loopback devices.

This was addressed in these two commits:
[https://github.com/NetBSD/src/commit/39ce7d7534f9a70caff49ab4d8e05f1fffb893f5](https://github.com/NetBSD/src/commit/39ce7d7534f9a70caff49ab4d8e05f1fffb893f5)
[https://github.com/NetBSD/src/commit/bb48f2ad77bf22b8e313fe11ddebbd65c1fef682](https://github.com/NetBSD/src/commit/bb48f2ad77bf22b8e313fe11ddebbd65c1fef682)

So your testing exception won't be necessary when you rebase tests to 10.0.
[https://github.com/secdev/scapy/blob/0a2b2bcff17b45106fc81aeecb9ba48fe75f916c/test/bpf.uts#L149](https://github.com/secdev/scapy/blob/0a2b2bcff17b45106fc81aeecb9ba48fe75f916c/test/bpf.uts#L149)

### Scapy version

git master as of April 11, 2024

### Python version

3.11

### Operating system

NetBSD 10.0

### How to reproduce

(Observe a now relevant test is bypassed by the test suite.)

**Comment by gpotter2** [comment]
Hi, thanks for the notice ! That's good to know.
