### ISSUE TITLE
haslayer with conditional packet fields

### ISSUE THREAD

**Issue by bsullivan19** [secdev/scapy#4354]
### Brief description

haslayer returns true if a Packet has a ConditionalField(PacketField) even when the condition for the conditional field is false.

### Scapy version

2.5.0

### Python version

3.12.2

### Operating system

Windows 10

### How to reproduce

```python
class FizzPacket(Packet):
    fields_desc = [IntField("fizz", 1)]

class BuzzPacket(Packet):
    fields_desc = [IntField("buzz", 1)]

class FooPacket(Packet):
    fields_desc = [IntField("foo", 0),
                   ConditionalField(PacketField("fizzp", FizzPacket(), FizzPacket), lambda p: p.foo == 1),
                   ConditionalField(PacketField("buzzp", BuzzPacket(), BuzzPacket), lambda p: p.foo == 2)]
```

```python shell
>>> pkt = FooPacket(foo=1)
>>> pkt
<FooPacket  foo=1 fizzp=<FizzPacket  |> |>
>>> BuzzPacket in pkt
True
```

### Expected result

Expected 'BuzzPacket in pkt' to return false because the condition for the field buzzp is false.

**Comment by gpotter2** [comment]
This isn't a supported behavior.

The supported ways are either:

- to test whether a field is `None` (when the condition is false)
- to check the condition yourself
