### ISSUE TITLE
[Windows] self.iface = create_string_buffer(device) + plus a few other thoughts

### ISSUE THREAD

**Issue by sgeto** [secdev/scapy#436]
Hey,

1. Not only am I not sure if this is a bug, I'm not even sure whether it is related to scapy or python.
Here's the scenario:

when started interactively, scapy works fine in conjunction with winpcapy, when run from a script (like this [one](https://github.com/kamorin/DHCPig)) I get this error:

```
Exception in thread Thread-3:                                                                                    
Traceback (most recent call last):                                                                               
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner                                            
    self.run()                                                                                                   
  File "pig.py", line 534, in run                                                                                
    sniff(filter=self.filter,prn=self.detect_dhcp,store=0,timeout=3,iface=conf.iface)                            
  File "C:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 197, in sniff                   
    s = L2socket(type=ETH_P_ALL, *arg, **karg)                                                                   
  File "C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 183, in __init__                             
    self.ins = open_pcap(iface, 1600, self.promisc, 100)                                                         
  File "C:\Python27\lib\site-packages\scapy\arch\windows\__init__.py", line 383, in <lambda>                     
    pcapdnet.open_pcap = lambda iface,*args,**kargs: _orig_open_pcap(pcapname(iface),*args,**kargs)              
  File "C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 168, in <lambda>                             
    open_pcap = lambda *args,**kargs: _PcapWrapper_pypcap(*args,**kargs)                                         
  File "C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py", line 132, in __init__                             
    self.iface = create_string_buffer(device)                                                                    
  File "C:\Python27\lib\ctypes\__init__.py", line 65, in create_string_buffer                                    
    raise TypeError(init)                                                                                        
TypeError: None
```

My guess is that winpcapy is not considered when scapy is run from a script. What's also funny is that I replaced 

`self.iface = create_string_buffer(device)` in `C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py`

with

`self.iface = conf.iface`

and it worked. Not sure why. I hope it helps.

2. Another error I have is when I try to come after as many optional features as possible on windows. I got almost all of them running except for two: 2D graphics and Graphs

this test command (for 2D graphics) :
```
>>> p=IP()/ICMP()
>>> p.pdfdump("test.pdf")
```

returns this (and much much more): 
```                                                                                      
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\site-packages\pyx\text.py", line 663, in run
    raise RuntimeError("TeX/LaTeX finished unexpectedly")
RuntimeError: TeX/LaTeX finished unexpectedly

still waiting for tex after 5 (of 60) seconds...
``` 

and this test command (for Graphs) :
```
>>> p=rdpcap("useless.pcap")
>>> p.conversations(type="jpg", target="> test.jpg")
```

returns:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\scapy\plist.py", line 323, in conversations
    return do_graph(gr, **kargs)
  File "C:\Python27\lib\site-packages\scapy\utils.py", line 412, in do_graph
    w.write(graph)
IOError: [Errno 32] Broken pipe
```

Maybe someone experienced the same or the something similar or maybe I'm missing something. To be honest, I am currently not exactly in need for them, but it would be nice to have all supported features working.

3. I find the windows installation guide very outdated. It takes quite a lot of additional research to get it to work these days. I could update the guide the if it's fine with you. Is anyone assign for that?

4. The powershell commands that run in the background every time scapy is started really slow down startup. Is there maybe a better way? I think one of them enumerates all connected devices. Can't this be done in CMD? I'm thinking `getmac /fo csv /v` or `netsh`

5. Lastly, I am not sure what to think of this line `INFO: No IPv6 support in kernel` 
Is it really checking or is this just a leftover from the linux-only days? It's bothering me somehow...

Thanks a lot. Keep up the work!

**Comment by gpotter2** [comment]
@sgeto Hello, and thanks for your report !

I have been working on a lot of stuff that you have reported 😃 actually:

- The Windows Doc IS outdated, and https://github.com/secdev/scapy/pull/378 is related to it
- IPv6 support for Windows is being handled by https://github.com/secdev/scapy/pull/398
- It is true that the powershell is slow, but it supports tons of stuff (like routing, like ipv6) and is easy to parse (we can order it with the `| select <param>` which is really useful and does not truncate anything)

That was for 3, 4, 5

In scapy when you see this bug:
`self.iface = create_string_buffer(device)`
It means that the provided interface is invalid. So either the script is using IPv6 or something not available yet on windows, either your configuration is wrong.

I can't help you with the graphs, as i don't know them that good...

**Comment by sgeto** [comment]
Hey,

no worries with the graphs. I never had any use for them. 
It's nice to see that IPv6 support is on it's way.

This is my `conf.iface` output:
`<NetworkInterface Qualcomm Atheros AR8152 PCI-E Fast Ethernet Controller (NDIS 6.30) {78C244BD-DAC5-422E-AD0B-F7DDFBED8632}>`
I'm using npcap in compatibility mode. If that makes any difference.

Everything seems fine when I use scapy interactively. It's just that script.
And not only is it 3+ years old, it was written with linux and/or dnet in mind.
May I ask what `self.iface` says in the file `C:\Python27\lib\site-packages\scapy\arch\pcapdnet.py` on your copy on scapy?

The error happens in that file `pcapdnet.py`. Scapy on windows doesn't even ask for dnet. Which I think is, except for the issue I am facing, fine, since dnet support on windows is rather meagre. Maybe that's the problem.

I'm maintaining a fairly up-to-date dnet fork [here ](https://github.com/sgeto/libdnet). It builds gracefully on windows (mingw) if you're ever in need for dnet on windows.

**Comment by gpotter2** [comment]
Well, scapy made dnet not necessary under windows... it now uses winpcapy instead, the DOC is not up to date...
So you are using dnet, right ? it's possible that while adding the winpcapy default support (which does not require any library), the dnet one has been broken... I'll use your fork to test that.

Apart from that, your conf.iface looks OK,

**Comment by sgeto** [comment]
wow. thanks. that's more than I expected. Thanks for fixing the script for me.
I have one more tiny question, which a little related and I don't want to open a new issue for it.

Basically I reset my network (restalled all network adapters and npcap). All of them now have different "Transport Names" (\Device\NPF_{blablabla}), but scapy is seems still stuck on the old one. 

In general, how do I tell scapy which interface to use (temporarily and permanently)?

Thanks

**Comment by gpotter2** [comment]
Well, in general, changing `conf.iface` is REALLY not recommanded... There is useally a parameter in the functions to select the interface.
Examples:

`sendp(IP(), iface="lo")`
`sniff(iface=IFACES.dev_from_name(get_windows_if_list()[0]["name"]))`

**Comment by gpotter2** [comment]
About PyX (pdfdump) you had not installed the dependencies.
https://github.com/secdev/scapy/pull/485
Will not print a warning

**Comment by gpotter2** [comment]
@p-l- I've answered all of the questions. This can't now be closed

**Comment by sgeto** [comment]
Yes! Thanks again. I'll open a new issue if there's anything else.
