### ISSUE TITLE
Scapy overides platform

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#4402]
Scapy exports the platform name, and could override the platform module. This is likely the issue: https://github.com/secdev/scapy/blob/b0506a1e22321eba41d5c21d26bba418de04bc8f/scapy/consts.py#L10

Here are the example:

```shell
python issue.py 
<class 'str'>
<class 'module'>
```

```python
import platform
from scapy.all import *
print(type(platform))

import platform
print(type(platform))
```

**Comment by gpotter2** [comment]
Good catch. We should probably add an __all__ to it.
