### ISSUE TITLE
NBNSQueryRequest malformed packet

### ISSUE THREAD

**Issue by lawndoc** [secdev/scapy#4426]
### Brief description

When I broadcast a NBNSQueryRequest the Query section of the packet is malformed (and it looks like maybe the header too). I've attached a pcap that contains both `nbtstat -a testhostname3` valid packets and the malformed ones that are being broadcast from the Scapy host.

[nbtstat.zip](https://github.com/user-attachments/files/15844195/nbtstat.zip)

### Scapy version

2.5.0

### Python version

3.12.3

### Operating system

Ubuntu 24.04 LTS (Linux 6.8.0-35-generic)

### Additional environment information

Both hosts in the pcap are in 172.19.0.0/24

### How to reproduce

```python
from scapy.all import *
from scapy.layers.inet import IP, UDP
from scapy.layers.netbios import NBNSQueryRequest

packet = IP(dst="172.19.0.255")/UDP(sport=137, dport=137)/NBNSQueryRequest(SUFFIX="file server service", QUESTION_NAME="Loremipsumdolorsitamet", QUESTION_TYPE="NB")
response = sr1(packet, timeout=3, verbose=0)
```

**Comment by gpotter2** [comment]
Could you retry with master?

**Comment by lawndoc** [comment]
Just tried with master (`2.6.0rc1.dev28`) and got the same result.

```
$ pip install https://github.com/secdev/scapy/archive/refs/heads/master.zip
Collecting https://github.com/secdev/scapy/archive/refs/heads/master.zip
  Downloading https://github.com/secdev/scapy/archive/refs/heads/master.zip
     / 7.0 MB 11.4 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: scapy
  Building wheel for scapy (pyproject.toml) ... done
  Created wheel for scapy: filename=scapy-2.6.0rc1.dev28-py3-none-any.whl size=2381183 sha256=8b7f16d5397364c3cfa001cddb1c0aedea651a9012eba35367f0e273486be112
  Stored in directory: /tmp/pip-ephem-wheel-cache-d2ziy4ea/wheels/01/cb/e2/efd324976e05067562c40a79122843c7d0a85333521f249e78
Successfully built scapy
Installing collected packages: scapy
  Attempting uninstall: scapy
    Found existing installation: scapy 2.5.0
    Uninstalling scapy-2.5.0:
      Successfully uninstalled scapy-2.5.0
Successfully installed scapy-2.6.0rc1.dev28
```

[nbtstat_try2.zip](https://github.com/user-attachments/files/15844688/nbtstat_try2.zip)

**Comment by lawndoc** [comment]
This is a side by side of a valid packet and a malformed packet. At a glance it looks like maybe the malformed packet is missing the header. The "header" information in the malformed packet looks like it was parsed from a section not intended to be the header.

![image](https://github.com/secdev/scapy/assets/24688343/04cb17b2-316a-47f3-83de-4e16fafbe63c)

**Comment by lawndoc** [comment]
I was right, it was missing the `NBNSHeader` in the packet. The following code will send a valid NBNS query:

```python
from scapy.all import *
from scapy.layers.inet import IP, UDP
from scapy.layers.netbios import NBNSQueryRequest

packet = IP(dst="172.19.0.255")/UDP(sport=137, dport=137)/NBNSHeader(NBNSHeader(OPCODE=0x0, NM_FLAGS=0x11, QDCOUNT=1)/NBNSQueryRequest(SUFFIX="file server service", QUESTION_NAME="Loremipsumdolorsitamet", QUESTION_TYPE="NB")
response = sr1(packet, timeout=3, verbose=0)
```

pcap: [nbtstat_try3.zip](https://github.com/user-attachments/files/15844978/nbtstat_try3.zip)

![image](https://github.com/secdev/scapy/assets/24688343/a551b3bf-910f-4173-89f1-307d54bbfa47)

**Comment by lawndoc** [comment]
I just started using Scapy yesterday, and it seems like this was my fault rather than something I should have expected the library to do for me. I think we are good to close this since I've resolved my issue.

**Comment by lawndoc** [comment]
I just wanted to call out that there are a few previous issues that contained the syntax that was missing the header. A couple of them were reported as working when they were closed. Was there a regression?

#4404 
#1391 
#710 

There is also an article on StackOverflow that has the syntax I tried before:

https://stackoverflow.com/questions/48479848/netbios-name-query-not-working

These sources are what led me to have this problem.

**Comment by gpotter2** [comment]
The behavior has ideed changed.
There is however an example in the new format on the doc: https://scapy.readthedocs.io/en/latest/usage.html#node-status-request-get-netbiosname-from-ip

I agree it's not great, and those changes were breaking. The Netbios file was however written in a very non-Scapy way, and the recent refactors made it much more reliable..

**Comment by lawndoc** [comment]
Thanks for the clarification! In the end my problem was solved, and I got a lot more familiar with Scapy. Hopefully between this issue and the documentation you linked, this change is more visible for people in the future.

Thanks for the work you do on this project!
