### ISSUE TITLE
TLS and cryptography >= 42.0.0 working correctly

### ISSUE THREAD

**Issue by gitbelg** [secdev/scapy#4436]
### Brief description

As described in how to reproduce

### Scapy version

2.5.0

### Python version

3.10

### Operating system

Windows 11

### How to reproduce

User cryptography >= 42.0.0
Importing with `from scapy.layers.tls.record import TLS` throws erros, such as 
`AttributeError: 'cryptography.hazmat.primitives.asymmetric.dh.DHParameterNumbers' object has no attribute '_p'`

**Comment by gpotter2** [comment]
Please retry using master.
