### ISSUE TITLE
Extract keylog for tls1.3 session

### ISSUE THREAD

**Issue by Katyayini23** [secdev/scapy#4448]
### Brief description

I want scapy to create a keylog for each TLS1.3 connection that I am creating, so that I can use that to decrypt the pcap file for evidence purpose.

### Scapy version

2.5.0

### Python version

3.10

### Operating system

Ubuntu22.04

### Additional environment information

I want to understand if there is a way to extract the session keylog similar to what we get when connecting using openssl.
I have a similar requirement , so that I can decrypt the tls1.3 pcap files.

### How to reproduce

Nothing to reproduce. Just need to understand how I can achieve the above requirement.
[tlss_mutual_auth13.zip](https://github.com/user-attachments/files/16068227/tlss_mutual_auth13.zip)

### Actual result

Need a solution for the issue stated above

### Expected result

Working solution to get the keylog when connecting using scapy.

### Related resources

nothing as of now

**Comment by guedou** [comment]
Scapy does not dump NSS Key Log. That is a feature that you could add by extracting the TLS 1.3 keys from the `compute_tls13_*()` functions such as https://github.com/secdev/scapy/blob/master/scapy/layers/tls/session.py#L674

**Comment by Katyayini23** [comment]
Can this TLS1.3 keys extracted from the above function be used to decrypt the pcap by uploading it to wireshark similar to how we can upload the ssl keylog to wireshark to decrypt application data.

**Comment by guedou** [comment]
You need to develop this functionality for Scapy it that will work.

**Comment by Katyayini23** [comment]
Can you please guide me how I can extract the below information from scapy for my tls1.3 connection:

SERVER_HANDSHAKE_TRAFFIC_SECRET
CLIENT_HANDSHAKE_TRAFFIC_SECRET
SERVER_TRAFFIC_SECRET_0
CLIENT_TRAFFIC_SECRET_0
EXPORTER_SECRET

**Comment by guedou** [comment]
That’s what I already did when I pointed you to the functions manipulating the keys =)I won’t do more. You will need to implement the extraction yourself. Feel free to submit a PR when this is ready.Sent from my iPhoneOn 4 Jul 2024, at 07:51, Katyayini23 ***@***.***> wrote:﻿
Can you please guide me how I can extract the below information from scapy for my tls1.3 connection:
SERVER_HANDSHAKE_TRAFFIC_SECRET
CLIENT_HANDSHAKE_TRAFFIC_SECRET
SERVER_TRAFFIC_SECRET_0
CLIENT_TRAFFIC_SECRET_0
EXPORTER_SECRET
