### ISSUE TITLE
The "PrivKey class : resign cert" test seems to be failing on Fedora Rawhide

### ISSUE THREAD

**Issue by evverx** [secdev/scapy#4470]
### Brief description

The test fails with
```python
######
## PrivKey/Pubkey test signatures
######


###(023)=[failed] PrivKey class : resign cert

>>> correct_sha1_sig = c_tosign.signatureValue
>>> c_tosign.x509Cert.signatureValue.val = 512*'0'
>>> 
>>> c_resigned = pkey_sign.resignCert(c_tosign)
>>> assert pkey_sign.verifyCert(c_resigned)
>>> assert raw(c_resigned.signatureValue) == correct_sha1_sig
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AssertionError
```
https://download.copr.fedorainfracloud.org/results/packit/evverx-scapy-2/fedora-rawhide-i386/07751439-scapy/builder-live.log.gz

(As far as I can see it started failing a couple of days ago so given that Fedora Rawhide is kind of unstable it can be a glitch that can fix itself in a week or so)

### Scapy version

f199f916c89a0fbe0fbb836e3f580d1e6a70c955

### Python version

Python 3.13.0~b3-2.fc41

### Operating system

Fedora Rawhide

### How to reproduce

It should be enough to trigger Packit with the master branch.

**Comment by evverx** [comment]
I've just triggered Packit and it seems that the test started failing on all the architectures on Fedora Rawhide: https://copr.fedorainfracloud.org/coprs/packit/evverx-scapy-2/build/7766512/.

**Comment by gpotter2** [comment]
Thanks for the report.
Do you think that this could be related to #4463 ? Do we have a simple way of testing that?

**Comment by evverx** [comment]
I don't think it's related. I rolled back scapy to https://github.com/secdev/scapy/releases/tag/v2.6.0rc1 to exclude the recent PRs and the test failed. I should have mentioned that sorry! My guess would be that it has something to do with either the python prerelease or cryptography (or both).

**Comment by evverx** [comment]
I tracked it down. `openssl` was updated on Fedora Rawhide along with changes like https://src.fedoraproject.org/rpms/openssl/c/e9284f5bee9b3a6ebf87a4a40de5ec48747836b4?branch=rawhide. The packit script didn't set up OPENSSL_CONF using `.config/ci/openssl.py` properly and it fell apart. The test passes with the following patch applied
```diff
diff --git a/.packit.yml b/.packit.yml
index 7636390f..9d4839cc 100644
--- a/.packit.yml
+++ b/.packit.yml
@@ -17,7 +17,7 @@ actions:
     - "git clone https://src.fedoraproject.org/rpms/scapy .packit_rpm --depth=1"
     # Drop the "sources" file so rebase-helper doesn't think we're a dist-git
     - "rm -fv .packit_rpm/sources"
-    - "sed -i '/^# check$/a%check\\n./test/run_tests -c test/configs/linux.utsc -K scanner' .packit_rpm/scapy.spec"
+    - "sed -i '/^# check$/a%check\\nOPENSSL_CONF=$(python3 ./.config/ci/openssl.py) ./test/run_tests -c test/configs/linux.utsc -K scanner' .packit_rpm/scapy.spec"
     - "sed -i '/^BuildArch/aBuildRequires: can-utils' .packit_rpm/scapy.spec"
     - "sed -i '/^BuildArch/aBuildRequires: libpcap' .packit_rpm/scapy.spec"
     - "sed -i '/^BuildArch/aBuildRequires: openssl' .packit_rpm/scapy.spec"
 ```
I'll send it tomorrow.
