### ISSUE TITLE
In the process of attempting to parse the TCP stream, failed to successfully parse TCPSession

### ISSUE THREAD

**Issue by Randark-JMT** [secdev/scapy#4475]
### Brief description

I tried to parse a stream of SQL injection traffic. Due to the nature of the website service, I could see the HTTP response of the successfully executed SQL statements in Wireshark and Scapy:

```plaintext
{"status":"success","data":[]}
```

In fact, by selecting to follow the HTTP stream in Wireshark instead of the TCP stream, you can see:

![图片](https://github.com/user-attachments/assets/b860a28d-88ac-4e49-a767-a7dc5160f9b5)

the pcap file for test:  [output.zip](https://github.com/user-attachments/files/16400633/output.zip)

### Scapy version

2.5.0

### Python version

3.11.6

### Operating system

Linux 6.5.0-17-generic

### How to reproduce

This is the code I used for a simple test:

```python
from scapy.all import *
from scapy.layers.http import *

packets = sniff(offline="./output.pcap", session=TCPSession)

for packet in packets:
    try:
        traffic_data = packet[Raw].load.decode(errors="ignore")
        if "HTTP/1.1 200" in traffic_data:
            print(packet[Raw].load.decode(errors="ignore"))
    except:
        continue
```

**Comment by gpotter2** [comment]
Did you try using master?

**Comment by Randark-JMT** [comment]
Yep, and id didn't work well too
![图片](https://github.com/user-attachments/assets/402de2bb-0679-413b-8df0-0aa25ff9a70e)

**Comment by gpotter2** [comment]
This is normal. "HTTP/1.1 200" is parsed inside the `HTTPResponse` object. `load` only contains the payload.
You'd do:
```

from scapy.all import *
from scapy.layers.http import *

# Bind port 3000 in your case, to HTTP
bind_bottom_up(TCP, HTTP, dport=3000)
bind_bottom_up(TCP, HTTP, sport=3000)

packets = sniff(offline="./output.pcap", session=TCPSession)

for packet in packets:
    if HTTPResponse in packet and packet.Status_Code == b"200":
        traffic_data = packet[Raw].load.decode(errors="ignore")
        print(traffic_data)
```

**Comment by Randark-JMT** [comment]
The problem is that for `sniff(offline=’. /output.pcap’, session=TCPSession)` code, isn't it expected that TCPSession should be rebuilt?

If the TCPSession is parsed correctly, then the HTTPResponse that results from continuing to decode should not be just `"data": []`, but rather `"data": [<json>]`
