### ISSUE TITLE
EDecimal comparison is imprecise.

### ISSUE THREAD

**Issue by Abbath** [secdev/scapy#4488]
### Brief description

EDecimal compares in a wrong way. 

### Scapy version

2.5.0

### Python version

3.10

### Operating system

Kubuntu 22.04

### Additional environment information

The culprit is this cast to float in EDecimal:
```
    def __eq__(self, other):
        # type: (Any) -> bool
        return super(EDecimal, self).__eq__(other) or float(self) == other
```

### How to reproduce

```
from scapy.all import *
pr1 = PcapReader("trouble.pcap")
p1 = pr1.read_packet()
p2 = pr1.read_packet()
print(p1.time < p2.time) # False, they are equal actually
print((p1.time, 0) < (p2.time, 1)) # True <-- should be False like the last one
print(p1.time == Decimal('1722417787.778435252')) # True
print(p2.time == Decimal('1722417787.778435216')) # True
print((Decimal('1722417787.778435252'), 0) < (Decimal('1722417787.778435216'), 1)) # False
```
trouble.pcap is inside the attached .zip file
[trouble.zip](https://github.com/user-attachments/files/16458053/trouble.zip)

### Actual result

1722417787.778435252 == 1722417787.778435216

### Expected result

1722417787.778435252 > 1722417787.778435216

**Comment by Abbath** [comment]
On the other hand, just checked and `p1.time == p2.time`, so the comparison is just not precise enough for nanoseconds.

**Comment by gpotter2** [comment]
Hi ! This should fix your issue: https://github.com/secdev/scapy/pull/4491
