### ISSUE TITLE
CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by allexstorm** [secdev/scapy#4505]
Hello.
Just started using scapy on windows 11 and faced following twice notifications on my scan script run:

...\layers\ipsec.py:512: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.

Script finished sucesfully, just have such 2 warnings every time.

scapy 2.5.0
python 3.12.4
using npcap 1.79

**Comment by gpotter2** [comment]
This is fixed on master.
