### ISSUE TITLE
ICMP fragment messages can only return the first fragment message

### ISSUE THREAD

**Issue by zhuleichina** [secdev/scapy#4507]
### Brief description

I send a no  fragmented ICMP message, The customed message processor returned fragmented messages.
The following code can only obtain the first fragmented message, What should I do to obtain a complete fragmented message.
By using Wireshark to capture packets, the complete message can be seen.

```
def send_icmp_message(dst_ip, msg):
    try:
        icmp_request = ICMP(type='echo-request', id=1, seq=1) / msg
        packet = IP(dst=dst_ip) / icmp_request
        conf.debug_match = True
        response = sr(packet, verbose=1)
        print(debug.recv)
    except Exception as e:
        return f"Error sending/receiving ICMP message: {e}"
```

### Scapy version

2.5.0

### Python version

3.11.9

### Operating system

Windows10

### How to reproduce

I send a no  fragmented ICMP message, The customed message processor returned fragmented messages.

### Actual result

I can only obtain the first fragmented message

### Expected result

 obtain a complete fragmented message.

**Comment by zhuleichina** [comment]
[111.zip](https://github.com/user-attachments/files/16725491/111.zip)

**Comment by gpotter2** [comment]
You can use `IPSession()`. It's pretty easy:

```
sr(packet, timeout=1, session=IPSession())
```

**Comment by zhuleichina** [comment]
It works properly after the modification. Thank you very much.

> You can use `IPSession()`. It's pretty easy:
> 
> ```
> sr(packet, timeout=1, session=IPSession())
> ```
