### ISSUE TITLE
Unable to filter for dot11 Control ACK frames

### ISSUE THREAD

**Issue by ChuckMash** [secdev/scapy#4510]
### Brief description

I seem to be able to correctly filter for management action frames, but I am unable to filter for control ACK frames.
Given the general similarity of the filters, I had expected the ACK filter to work the same as the action filter.

As always, pilot error is a possibility.
My apologies if that is the case.

### Scapy version

2.5.0

### Python version

3.10.12

### Operating system

Linux 6.5.0-35-generic

### How to reproduce

Set interface to monitor mode, then run the following.

```python
import scapy.all as scapy

def parse(packet):
  if packet.haslayer(scapy.Dot11) and packet.type==1 and packet.subtype==13: # Filter in callback
    packet.show()

scapy.sniff(
  iface="XXXXX",
  prn=parse,
  monitor=True,
  #filter="type 0 subtype 0xd0" # Management / Action filter works
  filter="type 1 subtype 0xd0"  # Control / Ack filter does not work
  )

```

```
ERROR: Cannot set filter: Failed to compile filter expression type 1 subtype 0x0d (-1)
```

### Actual result

Unable to compile filter.
However I can still receive the desired packets and filter in the callback.

```
...
...
###[ 802.11-FCS ]### 
     subtype   = Ack
     type      = Control
...
...
```

**Comment by gg-gvaladon** [comment]
This does not seem to be a Scapy related error. Are you able to use or compile the same filter with tcpdump?
