### ISSUE TITLE
Hitting "File exists" on 2.6.0

### ISSUE THREAD

**Issue by almusil** [secdev/scapy#4546]
### Brief description

Scapy doesn't check if the `.config` directory already exists. 
```
    from scapy.all import *  # noqa: F401,F403
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/all.py", line 13, in <module>
    from scapy.data import *
  File "/usr/local/lib/python3.12/site-packages/scapy/data.py", line 415, in <module>
    @scapy_data_cache("ethertypes")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/data.py", line 301, in scapy_data_cache
    from scapy.main import SCAPY_CACHE_FOLDER
  File "/usr/local/lib/python3.12/site-packages/scapy/main.py", line 165, in <module>
    SCAPY_CONFIG_FOLDER = _probe_config_folder("scapy")
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/main.py", line 82, in _probe_config_folder
    return _probe_xdg_folder(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/scapy/main.py", line 76, in _probe_xdg_folder
    path.mkdir(mode=0o700)
  File "/usr/lib64/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/root/.config'
```

### Scapy version

2.6.0

### Python version

3.12

### Operating system

Linux 6.10.6

### How to reproduce

Just importing `from scapy.all import *` is enough.

**Comment by KepptnKool** [comment]
I see a similar Error with the cache directory:

> FileExistsError: [Errno 17] File exists: '/root/.cache'

**Comment by gpotter2** [comment]
> Scapy doesn't check if the .config directory already exists.

Sorry could you elaborate on why you are saying this? The code seemed pretty clear to me:

https://github.com/secdev/scapy/blob/79974f22ee82aa622d22dbe5ff6ab4e3f004880f/scapy/main.py#L71-L76

Maybe I'm missing something. What are the permissions of this folder on your machine?

**Comment by guedou** [comment]
I could not reproduce the issue either.

**Comment by almusil** [comment]
I didn't check the code, but the issue is clearly happening. It might be a race then, which for some reason didn't happen with previous version.

**Comment by gpotter2** [comment]
> What are the permissions of this folder on your machine?

Another thing to check: it's a folder, right?

**Comment by almusil** [comment]
When it happened it was a regular directory, I didn't check the permission, but it's only created by scapy so I would expect that it is `700`.

**Comment by guedou** [comment]
Could you share more information to help us reproduce the issue ? For example, a docker image will be great, or your could isolate the problematic function an execute is outside of Scapy with different folders.

**Comment by KepptnKool** [comment]
I also see the issue in our CI. We run multiple processes that analyze pcap files in parallel. This might be race condition because _if not path.exists():_ and _path.mkdir(mode=0o700)_ are not atomic. Multiple processes can pass the if statement but the actual file system operation has to run sequentially.
I suggest to run mkdir with _exist_ok = True. This should laso work when multiple scapy processes are run in parallel.

**Comment by almusil** [comment]
It is definitely a race condition, I was able to reproduce it after several tries with the following script in `ghcr.io/ovn-org/ovn-tests@sha256:ffe496ad8ecb78cabf7986461645ca29af7078b255e298691bbab2ad34988469` image.


```
#!/bin/bash -e

cat << EOF > repro.py
from scapy.all import *
print("Test")
EOF

rm -rf /root/.config

for i in {0..150}; do
    python3 repro.py &
done
```

**Comment by guedou** [comment]
Thanks for the tests. https://github.com/secdev/scapy/pull/4558 should fix the issue.
