### ISSUE TITLE
Is it preferable to overload self.i2len() or update self.sz in a variable-length field?

### ISSUE THREAD

**Issue by douniwan5788** [secdev/scapy#4551]
Only `StrFixedLenField` updates the `self.sz` based on the `length` and not the `length_from`, which can lead to obtaining an incorrect length for `StrFixedLenField` when using `length_from`. What is the correct approach to update and retrieve a field's length?

**Comment by gpotter2** [comment]
`StrFixedLenField` has a fixed length, as the name suggests.
Use `StrLenField` with `length_from`.

**Comment by douniwan5788** [comment]
I'm trying to modify the code. What is the proper method to update and retrieve a field's length? `self.sz` for fixed fixed and self.i2len for variable-length field?

**Comment by douniwan5788** [comment]
And should we consider removing `length_from` from `StrFixedLenField`?

**Comment by gpotter2** [comment]
Always `i2len`.
