### ISSUE TITLE
_probe_xdg_folder fails if fs permissions do not allow mkdir

### ISSUE THREAD

**Issue by AvihaiSam** [secdev/scapy#4571]
running on container with low fs permissions will crash unless setting XDG env variables to a place with higher fs permissions.

https://github.com/secdev/scapy/blob/b2f6dec77d077908dbc1a7ad84d3a80f01f9b4f6/scapy/main.py#L194-L195
https://github.com/secdev/scapy/blob/b2f6dec77d077908dbc1a7ad84d3a80f01f9b4f6/scapy/main.py#L80-L95
https://github.com/secdev/scapy/blob/b2f6dec77d077908dbc1a7ad84d3a80f01f9b4f6/scapy/main.py#L68-L77

cache isn't and shouldn't be mandatory according to the following, therefore expected to not raise if mkdir fails
https://github.com/secdev/scapy/blob/b2f6dec77d077908dbc1a7ad84d3a80f01f9b4f6/scapy/main.py#L197-L202

https://github.com/secdev/scapy/blob/b2f6dec77d077908dbc1a7ad84d3a80f01f9b4f6/scapy/data.py#L295-L304

**Comment by gpotter2** [comment]
Fair enough, that's fixed in
https://github.com/secdev/scapy/commit/28287eb5c74cd31959660f9df827dc2c8072236a
