### ISSUE TITLE
With a self-manipulated Packet, in the scenario of Adding new protocols, the content of the PacketListField can't be dissected correctly. 

### ISSUE THREAD

**Issue by datadev802** [secdev/scapy#4581]
### Brief description

In case of a PacketListField into the fields_desc list of a Packet subclass, the content of the PacketListField can't be dissected correctly.

### Scapy version

2.6.0

### Python version

3.8.10

### Operating system

windows 11 pro x64

### How to reproduce

Firstly, the class ItemPacket is defined for PacketListField;
Secondly, the class MyProtocol  is defined for this issue;
Finally, the MyProtocal is serialized and deserialized.
Script executed result shows that, the content in the PacketListField dissected as payload one by one recursively!!!
Followed here is the script:
```
from scapy.all import Packet, ByteField, ShortField, IntField, FieldLenField, PacketListField, ls

class ItemPacket(Packet):
    name = "ItemPacket"
    fields_desc = [
        ShortField("id", 0),
        IntField("value", 0),        
    ]

    def guess_payload_class(self, payload):
        return ItemPacket
    #
#


class MyProtocol(Packet):
    name = "MyProtocol"
    fields_desc = [
        ByteField("version", 1),
        FieldLenField("num_items", None, count_of="items", fmt="B"),
        PacketListField("items", [], ItemPacket, count_from=lambda pkt: pkt.num_items)
    ]
#



def serialization_example():
    item1 = ItemPacket(id=1, value=100)
    item2 = ItemPacket(id=2, value=200)
    item3 = ItemPacket(id=3, value=300)
    
    my_pkt = MyProtocol(version=2, items=[item1, item2, item3])
    print("packet to be serialized:")
    my_pkt.show()
    ls(my_pkt)
    
    # serialize the packet
    serialized_pkt = bytes(my_pkt)
    print("\nserialized bytes of packet:", serialized_pkt)    
    return serialized_pkt
#

def deserialization_example(serialized_bytes):
    parsed_pkt = MyProtocol(serialized_bytes)    
    print("\packet after deserialization:")
    parsed_pkt.show()
    ls(parsed_pkt)
#

def main():
    # serialization example
    serialized = serialization_example()
    
    # desrialization example
    deserialization_example(serialized)
#

if __name__ == "__main__":
    main()
#
```

### Actual result
packet to be serialized:
......
serialized bytes of packet: b'\x02\x03\x00\x01\x00\x00\x00d\x00\x02\x00\x00\x00\xc8\x00\x03\x00\x00\x01,'
......
items      : PacketListField                     = [<ItemPacket  id=1 value=100 |<ItemPacket  id=2 value=200 |<ItemPacket  id=3 value=300 |>>>] ('[]')

### Expected result

packet to be serialized:
......
serialized bytes of packet: b'\x02\x03\x00\x01\x00\x00\x00d\x00\x02\x00\x00\x00\xc8\x00\x03\x00\x00\x01,'
......
items      : PacketListField                     = [<ItemPacket  id=1 value=100 |>, <ItemPacket  id=2 value=200 |>, <ItemPacket  id=3 value=300 |>] ('[]')

**Comment by gpotter2** [comment]
Use 
```
    def guess_payload_class(self, payload):
        return conf.padding_layer
```
instead of 
```
    def guess_payload_class(self, payload):
        return ItemPacket
```

**Comment by datadev802** [comment]
thx, now it works correctly!
