### ISSUE TITLE
sendpfast() is not respecting latest flags of tcpreplay (enable-file-cache deprecated)

### ISSUE THREAD

**Issue by dragonmigo** [secdev/scapy#488]
In latest tcpreplay, --enable-file-cache option is already deprecated:

https://github.com/appneta/tcpreplay/issues/17

The latest version only has 
`-K --preload-pcap`
option, which implies` --enable-file-cache`.

So now if scapy.sendpfast() is used with file_cache=True, it won't work.

**Comment by gpotter2** [comment]
So you mean https://github.com/secdev/scapy/blob/master/scapy/sendrecv.py#L289 won't work

**Comment by dragonmigo** [comment]
@gpotter2 Exactly, preload-pcap was originally a superset of --enable-file-cache anyway. So replacing L312 with preload-pcap sounds good.

Thanks a lot!
