### ISSUE TITLE
Creating IKEv2 SA_INIT containing multiple transforms in proposal

### ISSUE THREAD

**Issue by ingm4r** [secdev/scapy#517]
Hi,

using [this ](https://bitbucket.org/secdev/scapy/issues/5138/ikev2_payload_transform-class-problems) code as an example I'm able to create an IKEv2 SA_INIT packet. This packet contains one SA payload which contains one Proposal Payload which contains one transform payload.

I am trying to create a packet which contains multiple transforms inside the Proposal payload (see the screenshot attached).
But all I got so for is separate packets when I specify multiple transforms as tupels.

How can I do this?

![selection_007](https://cloud.githubusercontent.com/assets/6264197/23025953/e6173644-f45f-11e6-9f81-a45428332d60.png)

**Comment by guedou** [comment]
This is not well documented, yet `test/regression.uts` contains an example. Does the following does the job ?

```python
ISAKMP()/ISAKMP_payload_SA(prop=ISAKMP_payload_Proposal(trans=ISAKMP_payload_Transform(transforms=[('Encryption', 'AES-CBC'), ('Hash', 'MD5'), ('Authentication', 'PSK')])/ISAKMP_payload_Transform(res2=12345,transforms=[('Encryption', '3DES-CBC'), ('Hash', 'SHA')])))
```
