### ISSUE TITLE
Multiple items in scapy\arch\windows\compatibility.py cause problems.

### ISSUE THREAD

**Issue by chibill** [secdev/scapy#536]
Quite a few of the examples cause a crash involving a member of scapy\arch\windows\compatibility.py 

> Traceback (most recent call last):
  File "test.py", line 7, in <module>
    sniff(prn=arp_monitor_callback, filter="arp", store=0)
  File "C:\Python27\lib\site-packages\scapy\arch\windows\compatibility.py", line 177, in sniff
    log_runtime.info('Sniffing on %s' % conf.iface)
NameError: global name 'log_runtime' is not defined

for the example of sniffing every arp sent to you. This is on windows 10 x64 using latest pip version of scapy and the version from source on here.

**Comment by gpotter2** [comment]
Hello,
I cannot reproduce that issue at all...

I tried using Windows 10 x64 using the dev version (available on github), 
As you can see, we are importing the correct function: https://github.com/secdev/scapy/blob/master/scapy/arch/windows/compatibility.py#L24
So i cannot understand why it's crashing.

Can give you `scapy.config.conf.version` ?
Thanks !

**Comment by chibill** [comment]
It says unknown.version for some reason.

**Comment by chibill** [comment]
Also it affects 2.3.3. ;(reinstalled from pip)

**Comment by gpotter2** [comment]
Have you correctly followed the doc ?
http://scapy.readthedocs.io/en/latest/installation.html#windows
Can you try with the github version please (uninstall the pip version, then download the master.zip, then unzip and `python setup.py install`) ?

**Comment by chibill** [comment]
Yes I have. Also I first tried that when I in countered the problem on the pip version. No dice.. 

I will try again I guess... I think it could be the examples I am using are broken? Or something like that. But they are the ones that are in the docs.

**Comment by gpotter2** [comment]
Weird...
What command are you using ?

**Comment by chibill** [comment]
For what?

**Comment by gpotter2** [comment]
To trigger the crash

**Comment by chibill** [comment]
I am running the two examples in the docs.

**Comment by chibill** [comment]
Specifically 
`from scapy.all import *

def arp_monitor_callback(pkt):
    if ARP in pkt and pkt[ARP].op in (1,2): #who-has or is-at
        return pkt.sprintf("%ARP.hwsrc% %ARP.psrc%")

sniff(prn=arp_monitor_callback, filter="arp", store=0)`

**Comment by chibill** [comment]
Wait somehow was able to get a new error after unisntalling it and reinstalling it a few times.
Now the error is

> Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from scapy.all import *
  File "C:\Python27\lib\site-packages\scapy\all.py", line 43, in <module>
    from scapy.layers.tls.all import *
  File "C:\Python27\lib\site-packages\scapy\layers\tls\all.py", line 12, in <module>
    from scapy.layers.tls.automaton import *
  File "C:\Python27\lib\site-packages\scapy\layers\tls\automaton.py", line 35, in <module>
    from scapy.layers.tls.handshake import *
  File "C:\Python27\lib\site-packages\scapy\layers\tls\handshake.py", line 22, in <module>
    from scapy.layers.tls.keyexchange import (_tls_named_curves, _tls_hash_sig,
  File "C:\Python27\lib\site-packages\scapy\layers\tls\keyexchange.py", line 24, in <module>
    from scapy.layers.tls.crypto.ffdh import FFDH_GROUPS
  File "C:\Python27\lib\site-packages\scapy\layers\tls\crypto\ffdh.py", line 207, in <module>
    params = pn.parameters(default_backend())
AttributeError: 'DHParameterNumbers' object has no attribute 'parameters'

**Comment by gpotter2** [comment]
Ok i do not think that it's due to the code...

What python version are you using ?
Have you installed winpcap ?
Are you using a special setup (bash on windows/Cygwin...) ?

**Comment by chibill** [comment]
Python 2.7.12
Yes It should also be noted I have WireShark Installed.
No, just normal batch. I do have git bash I can try running it from installed but.

**Comment by gpotter2** [comment]
Can the scapy shell at least start ?

**Comment by chibill** [comment]
No. 

> scapy
WARNING: PyX dependencies are not installed ! Please install TexLive or MikTeX.
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
INFO: Can't import python-cryptography v1.7+. Disabled PKI & TLS crypto-related features.
Traceback (most recent call last):
  File "C:/Python27/Scripts/scapy", line 25, in <module>
    interact()
  File "C:\Python27\lib\site-packages\scapy\main.py", line 359, in interact
    init_session(None, mydict)
  File "C:\Python27\lib\site-packages\scapy\main.py", line 183, in init_session
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "C:\Python27\lib\site-packages\scapy\all.py", line 43, in <module>
    from scapy.layers.tls.all import *
  File "C:\Python27\lib\site-packages\scapy\layers\tls\all.py", line 12, in <module>
    from scapy.layers.tls.automaton import *
  File "C:\Python27\lib\site-packages\scapy\layers\tls\automaton.py", line 35, in <module>
    from scapy.layers.tls.handshake import *
  File "C:\Python27\lib\site-packages\scapy\layers\tls\handshake.py", line 22, in <module>
    from scapy.layers.tls.keyexchange import (_tls_named_curves, _tls_hash_sig,
  File "C:\Python27\lib\site-packages\scapy\layers\tls\keyexchange.py", line 24, in <module>
    from scapy.layers.tls.crypto.ffdh import FFDH_GROUPS
  File "C:\Python27\lib\site-packages\scapy\layers\tls\crypto\ffdh.py", line 207, in <module>
    params = pn.parameters(default_backend())
AttributeError: 'DHParameterNumbers' object has no attribute 'parameters'

maybe I need to install cryptography myself?
And yes.

**Comment by chibill** [comment]
Updating my cryptography  from 1.5.2 to the latest seems to have fixed it. Maybe set a version dependency on cryptography 1.7+ ?

**Comment by gpotter2** [comment]
True, that is required. We shall detect that and print a warning

**Comment by chibill** [comment]
You do print a warning then it crashes. Also the docs do not say its a requirement only that with needed for WEP Encryption.

**Comment by gpotter2** [comment]
@mtury made most of this part. @mtury could you check that error ? 

Thank you !
