### ISSUE TITLE
failed run of scapy3k on Vmware ESX(vsphere) with python 3.5

### ISSUE THREAD

**Issue by heeyeol72** [secdev/scapy#539]
I installed scapy3k for vmware ESX with python 3.5.
There is architecture dependent macros like SIOCGIFCOUNT   
scapy-python3-0.20/scapy/arch/linux.py

I verify all macros are same as ESX system(vmkernel) except SIOCGSTAMP
But still scapy won't work with ESX's vmk I/F which is a special I/F for ESX management purpose like vmotion/VSAN.
Note that scapy3k works in vnic of guest VM.

1.	Issue1
sys.path: ['', '/', '/build/toolchain/lin64/python-3.5.1/lib64/python3.5', '/build/toolchain/lin64/python-3.5.1/lib64/python3.5/lib-dynload', '/build/toolchain/lin64/python-3.5.1/lib/python35.zip', '/build/toolchain/lin64/python-3.5.1/lib64/python3.5/plat-linux', '/build/toolchain/lin64/python-3.5.1/lib64/python3.5/site-packages', '/vmfs/volumes/datastore1 (1)/scapy-python3-0.20']
WARNING: Failed to execute tcpdump. Check it is installed and in the PATH
WARNING: Can't open /proc/net/dev !
WARNING: Can't open /proc/net/route !
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6

Send tcp packets to 10.116.249.100 from source 10.10.10.1
> /vmfs/volumes/datastore1 (1)/scapy-python3-0.20/scapy/arch/linux.py(446)__init__()
-> sa_ll = self.outs.getsockname()
(Pdb) (Pdb) n
OSError: [Errno 95] Operation not supported
There are several warning of tcpdump and /proc/net/dev, router since ESX has tcpdump-uw and doesn't have /proc/net folder. But this simple operation (self.outs.getsockname) complains failure.

     2.  issue2 
> /vmfs/volumes/datastore1 (1)/scapy-python3-0.20/scapy/arch/linux.py(442)__init__()
-> self.ins.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 2**30)
(Pdb) n
OSError: [Errno 95] Operation not supported

setsockopt failed to run, but once I change the third argument to 2*20, it sometime worked or didn’t

Can anyone help me fix these issue on vmware ESX vmk?

Thx

**Comment by gpotter2** [comment]
This is not `scapy3k`, this is scapy. 

We do not support python 3 and won't provide any support for it.

`scapy `has many fixes and new features that are not provided in `scapy3k` (ipv6, networking fixes....). So feel free to get `scapy` instead.

**Comment by heeyeol72** [comment]
Sorry for confusion about scapy3k.
I got package from https://pypi.python.org/pypi/scapy-python3/0.20

May I get help here?

**Comment by gpotter2** [comment]
No sorry :/

The version you are using is a fork from an old version of `scapy`, so the code that is running is not the same...

As this version is more used (as it's the original one), there are more features and tons of fixes that do not exist in scapy3k...

But if you want to stay on scapy3k, you may post an issue on their repo:
https://github.com/phaethon/scapy

Good luck

**Comment by gpotter2** [comment]
Oh, apart from that, your bug is due to os restrictions:
As said in the message, `Operation not supported` means that the protocol or the socket type is not available on the system...

**Comment by heeyeol72** [comment]
ok. I posted my question in https://github.com/phaethon/scapy
