### ISSUE TITLE
[IPv6] time exceeded and fragments

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#551]
Scapy does not accept a time exceeded as a valid answer to a fragment. Therefore, the following example is not working: 

```
sr1(fragment6(IPv6(dst="www.kame.net", hlim=1)/IPv6ExtHdrFragment()/ICMPv6EchoRequest()/("A"*1800), 1500)[0])
```

**Comment by gpotter2** [comment]
Isn't that related to
https://github.com/secdev/scapy/blob/35f97efc53839f6366918c251dba5df2ac553c8d/scapy/layers/inet6.py#L424
(issue 399)

**Comment by guedou** [comment]
Indeed, Scapy handles this situation well:

```
>>> manual = IPv6(dst="www.kame.net", hlim=8)/IPv6ExtHdrFragment(id=1403481355, m=1, offset=32)/"A"
>>> sr1(manual, timeout=2, filter="ip6")
```
