### ISSUE TITLE
Problem with binding PacketField/PacketListField and normal layer

### ISSUE THREAD

**Issue by pudii** [secdev/scapy#560]
Hi all,

let's assume this simplified code. 

```
class Content(Packet):
    name = "Content"
    fields_desc = [
        XByteField("ID", 0x1)]

class headerPacket(Packet):
    name = "headerPacket"
    fields_desc = [
        ByteField("Name", 0),
        ByteField("Type", 0)]


class layer1(Packet):
    name = "layer1"
    fields_desc = [
        ByteField("Address", 0),
        PacketField("Content", Content(), Content)]
```

If Type == 0 I want something like that: packet = headerPacket() / layer1() / layer1() ... 
and my output should look like 

```
###[ headerPacket ]### 
  Name      = 0
  Type      = 0
###[ layer1 ]### 
     Address   = 0
     \Content   \
      |###[ Content ]### 
      |  ID        = 0x1
###[ layer1 ]### 
        Address   = 0
        \Content   \
         |###[ Content ]### 
         |  ID        = 0x1

```

Otherwise, if Type = 1 the goal is only one layer with more contents and looks like: packet = headerPacket() / layer1()
packet.Content = Content() / Content() ...
Output should look like: 
```
###[ headerPacket ]### 
  Name      = 0
  Type      = 1
###[ layer1 ]### 
     Address   = 0
     \Content   \
      |###[ Content ]### 
      |  ID        = 0x1
      |###[ Content ]### 
      |  ID        = 0x1
```

The problem is, to reach the second output I need to define the Content-Field as a Packet**List**Field, but to reach the first I only got to this output with a PacketField. The next problem is, I don't know how to access the "Type"-Field in the _headerPacket_ from _layer1_ or from _content_. A possible workaround for that is maybe to access it at runtime where the whole packet is created to bind the layers after that.
I hope this is more or less understandable and somebody have the knowledge and time for a possible solution. The main problem is, how to get to the two different outputs. I tried a little with different bind_layers, but it didn't work.

EDIT: Maybe if it's possible to determine how much packets/bits should be included in the PacketListField, this could be a solution.

**Comment by guedou** [comment]
To start with, I will suggest to define two separated objects for the different case: Layer1Type0 and Layer1Type1. Then you can implement `headerPacket.guess_payload_class()` to choose the next layer depending on the type value.

Does this work for you?
