### ISSUE TITLE
Scapy - Cannot send packet when source IP and and destination IP is same

### ISSUE THREAD

**Issue by cswarnan** [secdev/scapy#562]
I am using latest code from github, getting message as below:

My source code is 
data = "A"*1460
ans, un_ans = sr(IP(src="192.168.1.135", dst="192.168.1.135") / ICMP()/data)

I am using Windows 7 and Python27

Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix, NextHop
  + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], Comman 
 dNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1

Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix
  + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], Comman 
 dNotFoundException
  + FullyQualifiedErrorId : CommandNotFoundException

Begin emission:
Finished to send 1 packets.
.............................................................................................................................................................................................

It does not send any packet and keep going with these ....
You then need to manually exit the program.

**Comment by gpotter2** [comment]
Could you go in scapy and type:
`conf.prog.powershell`
and give us the result ?

Then could you please try to start a powershell windows on your computer and type 
`Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix`
in it ?

Thanks a lot !

**Comment by cswarnan** [comment]
@gpotter2 - 
Result of conf.prog.powershell is 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'

Result of Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix

Get-NetRoute : The term 'Get-NetRoute' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-NetRoute -AddressFamily IPV6 | select ifIndex, DestinationPrefix
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-NetRoute:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by gpotter2** [comment]
Sounds like you got an old version ow power shell.
Could you update your power shell (lookup on google) then retry ?
Thanks !

**Comment by cswarnan** [comment]
@gpotter2 After upgrading powershell to v4 
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

I am not able to execute conf.prog.powershell
getting error:
The term 'conf.prog.powershell' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1
char:1
+ conf.prog.powershell
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (conf.prog.powershell:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by gpotter2** [comment]
Looks like the current IPv6 implementation isn't working with your windows version.
This is a bug and I will look forward into it, sorry for that.

**Comment by gpotter2** [comment]
@cswarnan Please close all the duplicates that you have created !

**Comment by gpotter2** [comment]
Hello !
Does https://github.com/secdev/scapy/pull/599 fixes it for you ?
Thanks a lot !

**Comment by cswarnan** [comment]
@gpotter2 . Thanks so much. I will check and update you on this.

**Comment by cswarnan** [comment]
@gpotter2 : No that solution doesn't worked at all. 
I am still getting the same problem. When I send 1 packet to different machine, I get successful message : Begin emission:
Finished to send 1 packets.
.......*
Received 8 packets, got 1 answers, remaining 0 packets

However when I send to self, Begin emission:
Finished to send 1 packets.
...................................................................................................................................................................................................................................
and then you need to stop your program execution manually.

**Comment by gpotter2** [comment]
What command(s) do you use ? Since you haven't got any bug, it should be working fine...

**Comment by cswarnan** [comment]
@gpotter2 : 
sr(IP(dst="Your IP address")/ICMP())

**Comment by gpotter2** [comment]
`sr` waits for an answer. What would the answer be ?

**Comment by cswarnan** [comment]
@gpotter2 : Even if I wait for half an hour, it does not respond back. I always see ..... (dots) on my console.

**Comment by gpotter2** [comment]
That's normal, what was expected ? Why would there be an answer ? What would answer ?

**Comment by gpotter2** [comment]
Please also notebook that on windows, pinging is disabled by default in the firewall
