### ISSUE TITLE
Doc at build_dissect.html refers to unexisted function

### ISSUE THREAD

**Issue by egor7** [secdev/scapy#566]
The docs at http://www.secdev.org/projects/scapy/doc/build_dissect.html says that "it is very useful to understand when each function is called when a packet is built:"
>>> hexdump(str(p))
Packet.str=Foo
Packet.iter=Foo
Packet.iter=Bar1
Packet.build=Foo
Packet.build=Bar1
Packet.post_build=Bar1
Packet.post_build=Foo

The function hexdump() don't do this and the function to get this output does not exist.
It seems that the doc only wanted to show which function of which instance were called.

I've spent one day investigating the sources to find the correct one.
So it may be userfull to update this doc to make a point that this output is for just illustration purposes.

**Comment by gpotter2** [comment]
First, please use the up-to-date docs (the ones on secdev.org are a bit outdated): https://scapy.readthedocs.io/en/latest/

Then, what you've specified is not the output of a function, it's only an example.
If you had called the function  `str()` on a packet, that's in this order that the functions would have been called.
