### ISSUE TITLE
Exception when building a packet

### ISSUE THREAD

**Issue by AmedeoSapio** [secdev/scapy#585]
Hi, 
I defined a new packet header with a field of type BitField:

`fields_desc = [ BitField("f1", 0, 1),
                    IntField("f2", 0),
                    IntField("f3", 0)]` 

but when the packet is built I get the following error:

> File "/usr/local/lib/python2.7/dist-packages/scapy/fields.py", line 73, in addfield   
   return s+struct.pack(self.fmt, self.i2m(pkt,val))
   TypeError: can only concatenate tuple (not "str") to tuple

It seems that Packet's function [self_build()](https://github.com/secdev/scapy/blob/master/scapy/packet.py#L352) calls addfield() on all the fields, passing the value "p" received from the previous call. 

The function [BitField.addfield()](https://github.com/secdev/scapy/blob/master/scapy/fields.py#L747) returns either a string or a tuple. 
If it returns a tuple and [Field.addfield()](https://github.com/secdev/scapy/blob/master/scapy/fields.py#L74) gets called for the next field, the return operation

`return s+struct.pack(self.fmt, self.i2m(pkt,val))`
fails because it expects a string for that parameter. 
In fact, it tries to concatenate the 2 strings, resulting in the above error.

**Comment by guedou** [comment]
Scapy can only work with byte-aligned fields. Unfortunately, it can't express what you have in mind.

Adding a 7 bits field work:
  fields_desc = [ BitField("f1", 0, 1), BitField("f1_0", 0, 7), IntField("f2", 0), IntField("f3", 0) ]
