### ISSUE TITLE
NameError: 'LOOPBACK_NAME' when running on iOS

### ISSUE THREAD

**Issue by cclauss** [secdev/scapy#598]
[Pythonista](http://omz-software.com/pythonista) is a iOS full-featured implementation of Python 3.5 and 2.7.  Users can install Scapy on Pythonista but get `NameError: name 'LOOPBACK_NAME' is not defined` as described in this thread: https://forum.omz-software.com/topic/2539/how-can-i-install-scapy  Any advise?

**Comment by guedou** [comment]
Did you try with the current dev version pulled from github ?

Please provide us with more info and smaller code to trigger this issue as we won't be able to test ourselves.

**Comment by gpotter2** [comment]
A single small fix won't be enough if we want to support `Pythonista`...

Subprocess is not supported, I'm not sure that RAW sockets are available on IOS...

If we want to support IOS, we'll have to add a custom support in arch/, but i'm not even sure if that's possible...

**Comment by guedou** [comment]
I am closing this issue, as the port to Pythonista is not likely to happen. @cclauss feel free to reopen it if you have questions about how to implement it yourself.
