### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by stryngs** [secdev/scapy#603]
Curious to know if anyone is interested in me starting a channel on freenode for IRC help with scapy.  There currently exists a channel, #scapy, but the OP hasn't been around in forever and there isn't even a topic.

The reason I bring it up here is that if the IRC channel was advertised on the Github, then folks would be more apt to join it.

Thoughts?

**Comment by Zopieux** [comment]
Freenode staff can takeover the current ownership on `#scapy` but they would like confirmation from a project owner (meaning @p-l- or @guedou) to do so. If neither @p-l- nor @guedou is interested in maintaining  the IRC channel, they can delegate to someone with a Freenode account.

If need be, I can be the delegated owner as the only immediate action is just to add a topic to the channel. Thoughts?

**Comment by stryngs** [comment]
Doesn't matter to me who does what.  Just want to see the channel in use.  Folks come in and ask questions, but without even the topic being set, they don't stick around very long

**Comment by Zopieux** [comment]
Yes, I get your point. Let's wait for feedback from secdev owners 👍

**Comment by guedou** [comment]
I am not against joining the IRC channel, but I am afraid that I will spend most of my time idling =\

If you want to help people on the channel, I will be quite happy to do whatever is necessary to take over it.

**Comment by stryngs** [comment]
I want to help people with scapy very much, but there isn't even a topic set, and no way to have op powers in the channel.  Having something like chanserv with dedicated ops would be a nice way to start things out.  This would allow someone you designate to change topic, act with authority, etc...  Anything to get the ball rolling.

**Comment by Zopieux** [comment]
@guedou Please drop an email at `projects at freenode.net` stating the issue:
* you are a core developer of the open-source scapy project ([proof](https://github.com/orgs/secdev/people))
* the current #scapy channel owner is long gone
* you would like to takeover ownership as [your freenode nickname]

You need a registered freenode nickname of course. If you don't have one, you can delegate. Note that I already noticed them about the issue a few days ago; these instructions are theirs.

**Comment by stryngs** [comment]
Any movement on this yet?

**Comment by guedou** [comment]
I just registered `guedou`, and sent the email.

**Comment by guedou** [comment]
Scapy is back on IRC ! Thanks for your help.

**Comment by stryngs** [comment]
@guedou Is there a way that you can add @Zopieux and myself as Ops?  Theres prolly some others too.  Point being, I'd like to add a bot to help answer and direct questions, etc..

**Comment by guedou** [comment]
As there is not much going on on the IRC channel, I will prefer that you help us answering issues that are related to Scapy misusage. That will help the project a lot, as we will be able to focus on PRs instead.
