### ISSUE TITLE
How to calculate the round-trip time of TCP message？

### ISSUE THREAD

**Issue by JasonLZJ** [secdev/scapy#610]
I use scapy looks like ans,unans=sr(IP(dst="xxx.xxx.xxx.xxx")/TCP(dport=60000, sport=9999, flags='F'))
I want to calculate the round-trip delay, What shall I do? Thanks

**Comment by p-l-** [comment]
Simply use: `ans[0][1].time - ans[0][0].time`.
`ans[0]` is the first (and only, in your example) couple (sent packet, received packet). So `ans[0][1]` is the first received packet, and `ans[0][1].time` is its timestamp.
Feel free to reopen this issue if needed.

**Comment by JasonLZJ** [comment]
What is the difference between time  and sent_time in ans objects?
The value of ans[0][1].time - ans[0][0].time is too large?
