### ISSUE TITLE
about parse pcap of IPSec AH have different result in Fedora 20 and Ubuntu 14.04

### ISSUE THREAD

**Issue by z1yuan** [secdev/scapy#612]
I parse a pcap file with newest Scapy on Fedora and Ubuntu for our test automation system. But the result is different, I am not sure where is the real root cause, so could you help to take a check? I will share my pcap file, env info and execution steps.
## PCAP file:
[yz.zip](https://github.com/secdev/scapy/files/925183/yz.zip)

## Test bed info:
**1. Fedora**
[root@****** scapy]#cat /etc/*-release
**Fedora release 20** (Heisenbug)
NAME=Fedora
VERSION="20 (Heisenbug)"
ID=fedora
VERSION_ID=20
PRETTY_NAME="Fedora 20 (Heisenbug)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:20"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=20
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=20
Fedora release 20 (Heisenbug)
Fedora release 20 (Heisenbug)
[root@****** scapy]#python --version
**Python 2.7.5**

**2. Ubuntu**
y***@******:~/workspace/scaptest/scapy$ cat /etc/*-release
DISTRIB_ID=**Ubuntu**
DISTRIB_RELEASE=**14.04**
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
yuanzhi@yuanzhi-VirtualBox:~/workspace/scaptest/scapy$ python --version
**Python 2.7.6**

## **Execution steps and result:**
1. On Fedora:
[root@****** scapy]#scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
INFO: Can't import python-cryptography v1.7+. Disabled PKI & TLS crypto-related features.
Welcome to Scapy (**2.3.3.dev387**)
>>> packet_list = rdpcap("/root/yz/yz.pcap")
>>> packet_list.show()
0000 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / ISAKMP_payload_SA / ISAKMP_payload_KE / ISAKMP_payload_Nonce / ISAKMP_payload_ID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID
0001 Ether / IP / UDP 1.0.2.1:isakmp > 1.0.3.2:isakmp / ISAKMP / ISAKMP_payload_SA / ISAKMP_payload_KE / ISAKMP_payload_Nonce / ISAKMP_payload_ID / ISAKMP_payload_Hash / ISAKMP_payload_VendorID
0002 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / Raw
0003 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / Raw
0004 Ether / IP / UDP 1.0.2.1:isakmp > 1.0.3.2:isakmp / ISAKMP / Raw
0005 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / Raw
0006 Ether / 1.0.3.2 > 1.0.2.1 **ipv6_auth** / AH / Raw    **<-- the result of this line is wrong**
0007 Ether / 1.0.2.1 > 1.0.3.2 **ipv6_auth** / AH / Raw    **<-- the result of this line is wrong too**
>>> packet_list[6].show()
###[ Ethernet ]###
  dst= fa:16:3e:50:67:23
  src= fa:16:3e:bb:38:4d
  type= IPv4
###[ IP ]###
     version= 4L
     ihl= 5L
     tos= 0x0
     len= 84
     id= 15864
     flags= DF
     frag= 0L
     ttl= 64
     proto= **ipv6_auth**         **<-- the result of this line is wrong**
     chksum= 0xf57c
     src= 1.0.3.2
     dst= 1.0.2.1
     \options\
###[ AH ]###
        nh= tcp
        payloadlen= 4
        reserved= 0
        spi= 0xdd95380a
        seq= 1
        icv= 3c34f4c846fc2a3bd6191f35
        padding=
###[ Raw ]###
           load= '\xff\xff\xff\xff\xdbQ\xb2\xea\x00\x00\x00\x00\xa0\x02r\x10\xad\xa9\x00\x00\x02\x04\x05\xb4\x04\x02\x08\n\xff\xfe\x93\x08\x00\x00\x00\x00\x01\x03\x03\x07'

2. On Ubuntu:
y****@******:~/workspace/scaptest/scapy$ scapy
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
INFO: Can't import python-cryptography v1.7+. Disabled PKI & TLS crypto-related features.
Welcome to Scapy (**2.3.3.dev394**)
>>> packet_list = rdpcap("/media/sf_ubshare/pcap/yz.pcap")
>>> packet_list.show()
0000 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / ISAKMP_payload_SA / ISAKMP_payload_KE / ISAKMP_payload_Nonce / ISAKMP_payload_ID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID / ISAKMP_payload_VendorID
0001 Ether / IP / UDP 1.0.2.1:isakmp > 1.0.3.2:isakmp / ISAKMP / ISAKMP_payload_SA / ISAKMP_payload_KE / ISAKMP_payload_Nonce / ISAKMP_payload_ID / ISAKMP_payload_Hash / ISAKMP_payload_VendorID
0002 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / Raw
0003 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / Raw
0004 Ether / IP / UDP 1.0.2.1:isakmp > 1.0.3.2:isakmp / ISAKMP / Raw
0005 Ether / IP / UDP 1.0.3.2:isakmp > 1.0.2.1:isakmp / ISAKMP / Raw
0006 Ether / 1.0.3.2 > 1.0.2.1 **ah / AH / Raw**    <-- This line is correct
0007 Ether / 1.0.2.1 > 1.0.3.2 **ah / AH / Raw**    <-- This line is correct
>>> packet_list[6].show()
###[ Ethernet ]### 
  dst= fa:16:3e:50:67:23
  src= fa:16:3e:bb:38:4d
  type= 0x800
###[ IP ]### 
     version= 4L
     ihl= 5L
     tos= 0x0
     len= 84
     id= 15864
     flags= DF
     frag= 0L
     ttl= 64
     **proto= ah**                                <-- This line is correct
     chksum= 0xf57c
     src= 1.0.3.2
     dst= 1.0.2.1
     \options\
###[ AH ]### 
        nh= tcp
        payloadlen= 4
        reserved= 0
        spi= 0xdd95380a
        seq= 1
        icv= 3c34f4c846fc2a3bd6191f35
        padding= 
###[ Raw ]### 
           load= '\xff\xff\xff\xff\xdbQ\xb2\xea\x00\x00\x00\x00\xa0\x02r\x10\xad\xa9\x00\x00\x02\x04\x05\xb4\x04\x02\x08\n\xff\xfe\x93\x08\x00\x00\x00\x00\x01\x03\x03\x07'

snapshot of wireshark:
![image](https://cloud.githubusercontent.com/assets/17735279/25084088/5624f5dc-238d-11e7-9b1c-0a1a2b721441.png)

if there are more information needed, please let me know. Thanks.

**Comment by guedou** [comment]
Your are not using the same Scapy version on both computers. The version is newer on Ubuntu ...

**Comment by z1yuan** [comment]
Sorry about the wrong log on the Fedora server before, I have updated the log, please take a check. BTW, i have tested on windows, the result is also correct. 
Thanks.

**Comment by z1yuan** [comment]
@guedou could you re-open the issue and help to take a check please? Thanks!

**Comment by guedou** [comment]
This is not a bug. Fedora contains the following:
```
cat /etc/protocols |grep -i auth
ah	51	AH		# Authentication Header
ipv6-auth	51	IPv6-Auth		# Authentication Header for IPv6 (not in official list)
```

**Comment by z1yuan** [comment]
I do test it, you are right. Now i make a walk-around for my project by comment ipv6-auth in /etc/protocols in Fedora, it works. 
But since ipv6-auth=51 is not in official list, is that possible to let Scapy using ah=51 with high priority? so that Fedora user might be not confused here.   
Thank you very much!
