### ISSUE TITLE
Duplication of dissect in show2() in case Packet was made from buffer.

### ISSUE THREAD

**Issue by ybrustin** [secdev/scapy#619]
Hi,

In case Packet was initialized from buffer (\_\_init__ with _pkt ), dissect was already done.
show2() currently will do the dissect again, which looks redundant to me.
What about idea of adding such conceptual check inside show2():

```
if self.explicit:
    self.show(...)
else:
    self.__class__(...).show(...) # current behaviour
```

EDIT:
It's bad idea "as is", payloads (or payloads of payloads etc.) might have been changed.
It could work however if all the layers of packet are not changed a.k.a. explicit.

Something like adding new function:

```
    def is_whole_explicit(self):
        l = self
        while l:
            if not l.explicit:
                return False
            l = l.payload
        return True
```

...and then, use it as criteria in show2() to determine if we need to use \_\_class__ and dissect again or use the show() on the packet.

Thanks,
Yaroslav.

**Comment by gpotter2** [comment]
Hey,
Is it really a good idea to add tons of metrics, a cache system (that's basically what you want to add), just to avoid re-dissecting a packet ? Also you have to iterate through the packet, what if it's a big one ?

I don't think that we will gain a lot by doing that :/

**Comment by ybrustin** [comment]
Loop on show2 with this "optimisation" (9KB Jumbo packet):

> time python q.py > /dev/null
real    0m3.493s
user    0m3.393s
sys     0m0.026s
                                                                                                                                                                                                                                   > time python q.py > /dev/null
real    0m3.422s
user    0m3.369s
sys     0m0.017s

Without this optimisation:                                                                                                                                                                                                                                   

> time python q.py > /dev/null
real    0m8.533s
user    0m8.441s
sys     0m0.021s
                                                                                                                                                                                                                                   > time python q.py > /dev/null
real    0m8.456s
user    0m8.377s
sys     0m0.023s

I agree that it's probably not the common case to iterate on show2, but still it's x2.4 speedup :)
Cache system is already there by "raw_packet_cache", "explicit", etc.

Actually the reason I've raised this issue is that I'm working on new layers and added many warnings on processing of packets/pcaps.
Same warning are printed again at show2 time.
(Suppressing them via config is not equivalent, because at processing packet from pcap I would like to see all the warnings even coming from same source of code, but upon showing same packet later, IMHO it's not informative duplication of warning.)

**Comment by gpotter2** [comment]
Thanks for your tests !

Well, let's say "why not".
I'll be happy to see you work on layers once you'd have finish it :)
