### ISSUE TITLE
scapy sr1 function does not return answers

### ISSUE THREAD

**Issue by JasonLZJ** [secdev/scapy#621]
I am trying to do a stealth SYN scan using scapy. For example, I've tried to run the follwoing command:
sr1(IP(dst='x.x.x.x')/TCP(dport=61000, sport=60000, flags='S'),timeout=1,verbose=1)
I would have expected to get the following answer, almost immediately:

Begin emission:
  .......*.**.......Finished to send 1 packets.
  **.*.*..*..................
  Received 362 packets, got 1 answers, remaining 0 packets

But in my server, I do the same, sametimes I got this:

  Begin emission:
  Finished to send 1 packets.
  Received 1572 packets, got 0 answers, remaining 1 packets

In my testing environment, I have one network card, but in real server, server ip is in br0.
I run the command: conf
I can see the iface = 'br0'
In tcpdump I can see the packet, but the function sr1 does not have answers.

Some times I can got the answers, But some times not. I want to knew why.

Thanks.

**Comment by gpotter2** [comment]
Hello,
This sounds like it's not a scapy problem, but a problem during the routing or outside the interface...

**Comment by p-l-** [comment]
Does it work better if you use `sr1([...], iface='br0')`?

**Comment by JasonLZJ** [comment]
@p-l- Thank you , I use it by iface='br0' it works
