### ISSUE TITLE
PacketListField non-trivial defaults deepcopy

### ISSUE THREAD

**Issue by mtury** [secdev/scapy#63]
```
Python 2.6.9 (unknown, Feb 15 2016, 02:22:40) 
[GCC 4.6.3] on linux3
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
WARNING: No route found for IPv6 destination :: (no default route?)
>>> load_contrib('gtp')
>>> GTPPDUNotificationRequest()
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.RuntimeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.RuntimeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.RuntimeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.RuntimeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' in <type 'exceptions.RuntimeError'> ignored
<GTPPDUNotificationRequest  |>
>>>
```

```
class GTPPDUNotificationRequest(Packet):
    # 3GPP TS 29.060 V9.1.0 (2009-12)
    name = "GTP PDU Notification Request"
    fields_desc = [ XBitField("seq", 0, 16),
                    ByteField("npdu", 0),
                    ByteField("next_ex", 0),
                    PacketListField("IE_list", [ IE_IMSI(),
                        IE_TEICP(TEICI=RandInt()),
                        IE_EndUserAddress(PDPTypeNumber=0x21),
                        IE_AccessPointName(),
                        IE_GSNAddress(address="127.0.0.1"),
                        ], IE_Dispatcher) ]
```

Providing PacketListFields with a non-empty list of packets as default value seems to make Python 2.6 signal that it came upon recursion loops. Some context as to the printed message :  [http://bugs.python.org/issue5508]

There are few PacketListFields defined in Scapy with non-trivial default value but GTPPDUNotificationRequest contains one of them, with 5 Packets inside the list (as the number of warnings printed). The issue actually does not come from PacketListField _per se_, but from defining a list of Packets as default with any type of Field.

I haven't investigated it fully but the warnings seem to be printed by the test `hasattr(y, '__setstate__')` in `_reconstruct` function of `Lib/copy.py`.
`_reconstruct` is called by `deepcopy` while initializing `defaultfields` in `Packet.do_init_fields()`.

Testing with commits old enough does not show the warnings above. I don't know which exact commit brought this, though.

**Comment by p-l-** [comment]
Thanks a lot for your deep investigation on that issue! I have the feeling this could be another side effect of #11.

I'll have a look as soon as I can.

**Comment by gpotter2** [comment]
@p-l- This has been fixed. Please close.
