### ISSUE TITLE
Type length value display

### ISSUE THREAD

**Issue by mungayree** [secdev/scapy#650]
This ER is filed as a request for enhancement.

TLV field_desc as below -

    class mytlv(Packet):
      fields_desc = [
        FieldLenField("length", None, fmt='B', length_of="value"),
        ByteEnumField("type", None, some_enum),
        StrLenField("value", "ABCDEF", length_from=lambda x:x.length)
     ]
how can I display in show2() as

    ### [ mytlv ] ###
    length=9, type="x", value="abcdefghi"
or directly the type x (which is enum) as -

    ### [ mytlv ] ###
    length=9, x=abcdefghi

**Comment by p-l-** [comment]
`.show()` and `.show2()` are generic `Packet` methods. You may want to implement another method that displays fields the way you like.
