### ISSUE TITLE
NameError: global name 'Gen' is not defined

### ISSUE THREAD

**Issue by hoyeunglee** [secdev/scapy#651]
packets = rdpcap(r'C:\Users\hello\Downloads\dhcp.pcap')
packets[0].show()
packets[0].summary()
responsepkt = sr1(packets[0])

is it possible to send the packet which are from captured packet?

**Comment by guedou** [comment]
Please understand, that we can't help you if you don't provide any detail (OS, Scapy version, etc) ...

This works fine for me. Also please note that you might need to alter the content of packets[0] (like MAC addresses to be able to receive an answer).

**Comment by gpotter2** [comment]
This is like https://github.com/secdev/scapy/issues/312 :)
That was fixed in https://github.com/secdev/scapy/pull/322 then https://github.com/secdev/scapy/pull/421

**Comment by hoyeunglee** [comment]
def custom_action(packet):
    packet[0][Ether].src = '2a:a9:f4:64:cf:75'

send(Ether(src="3a:a9:f4:64:cf:75", dst="ff:ff:ff:ff:ff:ff")/IP(src="10.126.0.160", dst="8.8.8.8")/UDP(dport=53)/b"hello")
sendp(Ether(src="3a:a9:f4:64:cf:75",dst="FF:FF:FF:FF:FF:FF")/ARP(op=2, psrc="0.0.0.0", hwdst="FF:FF:FF:FF:FF:FF")/Padding(load="X"*18))
packets2 = sniff(offline=r'C:\Users\martlee2\Downloads\dhcp.pcap', prn=custom_action)
responsepkt = sr1(packets2[0])


succeed to run after using the fix, 

but when i would like to create a mapping in switch, 
using sh mac-address-table | in 3aa9, there is no result
and after edit mac address of dhcp offer packet , there is no packet return.

**Comment by hoyeunglee** [comment]
succeed to run after fix, 
succeed to create a mapping with fake mac address
when try send dhcp offer, it load a long time

**Comment by ilqxejraha** [comment]
pip install git+https://github.com/secdev/scapy
