### ISSUE TITLE
Matplot problem

### ISSUE THREAD

**Issue by ScrimForever** [secdev/scapy#654]
ucamnet bin # scapy
INFO: Can't import matplotlib. Won't be able to plot.
lstat(./dvips) failed ...
./dvips: No such file or directory
python2.7: ../../../texk/kpathsea/progname.c:316: remove_dots: Assertion `ret' failed.
Aborted

Can help me ???

**Comment by guedou** [comment]
Could you try with the current development version, and give use information about your installation ? I have never seen this message before ...
