### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by hoyeunglee** [secdev/scapy#655]
```
def custom_action(packet):
        packet[Ether].src = '28:d2:44:25:5d:83'
        packet[DHCP].requested_addr = '200.201.202.203'
```

IndentationError: unexpected indent at  packet[DHCP].requested_addr = '200.201.202.203'

i had already pressed space four times, but still has this error

**Comment by guedou** [comment]
That's not how the DHCP layer works. You need to modify the options list:
```
>>> DHCP(options=[("requested_addr", "1.2.3.4")])
>>> p.options[0] = ("requested_addr", "5.6.7.8")
>>> str(p)
'2\x04\x05\x06\x07\x08'
```

Does it work for you?

**Comment by hoyeunglee** [comment]
i can not get to this point,

my current progress is here, please download mp4 video 
https://drive.google.com/file/d/0Bxs_ao6uuBDUZk51SnBCMUdIT2s/view

**Comment by guedou** [comment]
I won't open a video from an unknown source! Your issue is likely Python related and might have nothing to do with Scapy.

Please describe it with *words* and examples or close the issue.

**Comment by hoyeunglee** [comment]
INFO: Can't import matplotlib. Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
INFO: No IPv6 support in kernel
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
Welcome to Scapy (2.3.3)
>>> from scrapy.item import Item, Field
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named scrapy.item
>>> def custom_action(p):
...     p[Ether].src = '82:d2:44:25:5d:83'
>>>     p[DHCP].requested_addr = '10.126.0.38'
  File "<console>", line 1
    p[DHCP].requested_addr = '10.126.0.38'
    ^
IndentationError: unexpected indent

i copy code to the cmd console to run , but get error, i had already used four spaces instead of tab
but return indent error

**Comment by guedou** [comment]
This is error is not related to Scapy.
