### ISSUE TITLE
Inconsistency between packet seen in Scapy and Wireshark

### ISSUE THREAD

**Issue by bsmelo** [secdev/scapy#658]
Hello,

I'm playing with Scapy to develop a tool to use in my masters, and I found an issue, which I'm not sure is an user error from my side, or a possible bug in Scapy (or, most probably, the `contrib` layer I'm using).
The following snippet makes the issue clear:

```python
 $ sudo python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> from scapy.contrib.coap import *
>>> 
>>> random.seed("Let's fuzz CoAP!")
>>> 
>>> conf.L3socket = L3RawSocket
>>> 
>>> fuzz_pattern = fuzz(CoAP(ver=1L, type=RandNum(0, 1), code=RandNum(0, 4), token=RandBin(RandNum(0, 8)), options=[(11L, 'core')], paymark='\xff'+str(RandBin())))
>>> 
>>> randstate=random.getstate()
>>> 
>>> print "Will send this packet:"
Will send this packet:
>>> hexdump(fuzz_pattern)
0000  4601724F414894B7677EB4636F7265FF F.rOAH..g~.core.
0010  D2B29AE4FD7E088931F7368DCFB75730 .....~..1.6...W0
0020  4B55C0E46C703AC965D6269A97AA43BA KU..lp:.e.&...C.
0030  5FA19F61335E3E5517EA94B3744E0781 _..a3^>U....tN..
0040  51DEF2BC4003D7A01DFF9B98CD4508D8 Q...@........E..
0050  90BA19124B7363B6                 ....Ksc.
>>> random.setstate(randstate)
>>> fuzz_pattern.show2()
###[ CoAP ]### 
  ver       = 1L
  type      = CON
  tkl       = 6L
  code      = GET
  msg_id    = 29263
  token     = 'AH\x94\xb7g~'
  options   = [('Uri-Path', 'core')]
  paymark   = '\xff'
###[ Raw ]### 
     load      = '\xd2\xb2\x9a\xe4\xfd~\x08\x891\xf76\x8d\xcf\xb7W0KU\xc0\xe4lp:\xc9e\xd6&\x9a\x97\xaaC\xba_\xa1\x9fa3^>U\x17\xea\x94\xb3tN\x07\x81Q\xde\xf2\xbc@\x03\xd7\xa0\x1d\xff\x9b\x98\xcdE\x08\xd8\x90\xba\x19\x12Ksc\xb6'

>>> random.setstate(randstate)
>>> sr1(IP(dst="127.0.0.1")/UDP(sport=34552, dport=5683)/fuzz_pattern, verbose=20, retry=-1, timeout=2)
Begin emission:
Finished to send 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets
<IP  version=4L ihl=5L tos=0x0 len=38 id=32878 flags=DF frag=0L ttl=64 proto=udp chksum=0xbc56 src=127.0.0.1 dst=127.0.0.1 options=[] |<UDP  sport=5683 dport=34552 len=18 chksum=0xfe25 |<CoAP  ver=1L type=NON tkl=6L code=4.04 Not Found msg_id=837 token='\xb8i\xd4\x9c\xb7J' |>>>
>>> 
```

At this point, I go to Wireshark and see a different packet in there (different values in the coap header fields, such as the Token and Message ID), so I decide to save that capture and import it on the previous session, to see how scapy would react by reading/dissecting the captured pcap:

```python
>>> print "But this is what I see in wireshark (and at the debug output of the target):"
But this is what I see in wireshark (and at the debug output of the target):
>>> pcap_pkt = rdpcap("../captures/endian.pcapng")
>>> hexdump(pcap_pkt[0]['CoAP'])
0000  560498D5B869D49CB74AB4636F7265FF V....i...J.core.
0010  D2B29AE4FD7E088931F7368DCFB75730 .....~..1.6...W0
0020  4B55C0E46C703AC965D6269A97AA43BA KU..lp:.e.&...C.
0030  5FA19F61335E3E5517EA94B3744E0781 _..a3^>U....tN..
0040  51DEF2BC4003D7A01DFF9B98CD4508D8 Q...@........E..
0050  90BA19124B7363B6                 ....Ksc.
>>> 
>>> pcap_pkt[0]['CoAP'].show2()
###[ CoAP ]### 
  ver       = 1L
  type      = NON
  tkl       = 6L
  code      = DELETE
  msg_id    = 39125
  token     = '\xb8i\xd4\x9c\xb7J'
  options   = [('Uri-Path', 'core')]
  paymark   = '\xff'
###[ Raw ]### 
     load      = '\xd2\xb2\x9a\xe4\xfd~\x08\x891\xf76\x8d\xcf\xb7W0KU\xc0\xe4lp:\xc9e\xd6&\x9a\x97\xaaC\xba_\xa1\x9fa3^>U\x17\xea\x94\xb3tN\x07\x81Q\xde\xf2\xbc@\x03\xd7\xa0\x1d\xff\x9b\x98\xcdE\x08\xd8\x90\xba\x19\x12Ksc\xb6'

>>>
```

Notice the packet seen in Scapy is different than the packet seen in Wireshark. How could I solve this? I have a feeling it's something related either to the Rand* functions or to the `contrib`'ed layer itself.

I'd really appreciate some help. Thanks!

**Comment by guedou** [comment]
What are you trying to do ? It seems that your methodology is flawed as you don't hexdump the same packet that you are sending.

Please try something like:

s = str(fuzz_pattern)
hexdump(s)
p = IP()/UDP()/s
sr1(p)

**Comment by bsmelo** [comment]
> What are you trying to do ?

I'm trying to print the packet before it is sent, and I'm using this approach since `sr1` doesn't return the sent packet (unlike `sr`, which returns the tuples either in `ans` or `unans`).

> It seems that your methodology is flawed as you don't hexdump the same packet that you are sending.

That's why I save the state of `random` before every command that would trigger new fuzzed values (I believe `hexdump()` and `show2` calls `str()` at some point, causing the packet to mutate), so I actually deal with the same packet.

I tried what you said, and it does work - and looks better, since it's more clear that `str()` is called only once on that pattern, and thus I'm dealing with the same mutation for sure.
Thanks a lot for the prompt and precise answer! Anyway, if you don't mind, could you tell what's wrong with the reasoning above? I was really expecting that trick of saving the `random` state to work.

**Comment by bsmelo** [comment]
Another weird thing where my mental model seems to be incorrect now, is:

```
>>> resp = sr1(IP(dst="127.0.0.1")/UDP(sport=34552, dport=5683)/fuzzed_pkt, verbose=20, retry=-1, timeout=2)
Begin emission:
Finished to send 1 packets.
......Begin emission:
Finished to send 1 packets.
....
Received 10 packets, got 0 answers, remaining 1 packets
>>> resp
>>> resp = sr1(IP(dst="127.0.0.1")/UDP(sport=34552, dport=5683)/fuzz_pattern, verbose=20, retry=-1, timeout=2)
Begin emission:
Finished to send 1 packets.
.*
Received 2 packets, got 1 answers, remaining 0 packets
>>> resp
<IP  version=4L ihl=5L tos=0x0 len=35 id=54722 flags=DF frag=0L ttl=64 proto=udp chksum=0x6705 src=127.0.0.1 dst=127.0.0.1 options=[] |<UDP  sport=5683 dport=34552 len=15 chksum=0xfe22 |<CoAP  ver=1L type=NON tkl=3L code=4.04 Not Found msg_id=198 token='7`_' |>>>
```
I don't understand why I don't get a `resp` in the first case (sending using `fuzzed_pkt` from `str(fuzz_pattern)`), although I can see the response from the target on Wireshark; and I get `resp` in the second case (sending using the `fuzz_pattern` itself).

**Comment by guedou** [comment]
I did not check but I think that something else than fuzz() is consuming random values from the random module. That is likely why "freezing" the result with str() gives a stable result.

**Comment by guedou** [comment]
I am not familiar with CoAP but Scapy could consider that the response is not valid. 

However, it is more likely that Scapy did not fuzz a correct query.

**Comment by bsmelo** [comment]
> I did not check but I think that something else than fuzz() is consuming random values from the random module. That is likely why "freezing" the result with str() gives a stable result.

That makes a lot of sense. I was mostly inclined to believe some kind of parsing/deconding error was going on because only the first 10 bytes were different between the packet printed by `hexdump()` and the one seen on Wireshark, anyway...

> I am not familiar with CoAP but Scapy could consider that the response is not valid.

Really? Since Scapy has that whole idea of "decoding instead of interpreting" and "You’re free to put any value you want in any field you want, and stack them like you want.", I thought I'd still see an invalid CoAP response, even if it'd show a `Raw()` layer on top of the valid `IP()/UDP()` layers.

Anyway, I believe that's not the case, since the response is valid (I can see it dissected on Wireshark), it seems it's just not reaching Scapy... And it's very weird to me that it doesn't work with the 'pre-assembled' `fuzzed_pkt` but works with the 'post-assembled' `fuzz_pattern`: in both cases I can see valid responses in Wireshark (only the Requests generated by Scapy are invalid, but valid responses containing `BAD_REQUEST` error codes are returned by the target), but only in the second case the response object is returned by `sr1()`.

For now, I have changed my workflow to use `srloop()` instead. I hope it continues to work for me.
Again, thanks a lot for the help and the answers. If I have similar questions, could/should I use this channel or is it better to post to the mailing-list?

**Comment by guedou** [comment]
I am glad that it worked !
