### ISSUE TITLE
[AppVeyor] npcap can't be installed

### ISSUE THREAD

**Issue by guedou** [secdev/scapy#664]
The AppVeyor are currently failing because npcap can't be installed. @gpotter can you have a look ?

**Comment by gpotter2** [comment]
I saw that too. Not our fault
I've pushed an issue to their repo:
https://github.com/nmap/nmap/issues/900

**Comment by gpotter2** [comment]
Should be fixed in https://github.com/secdev/scapy/pull/667

**Comment by p-l-** [comment]
Closed by #667.
