### ISSUE TITLE
Netflow update

### ISSUE THREAD

**Issue by Forzii** [secdev/scapy#672]
I've been working on small traffic generator suite for my team to use, and I'm using scapy as one of the tools. One requested feature was the ability to generate netflow traffic. I see that the dev version of scapy has included netflow V5 on top of V1, which is excellent (I had planned to add it myself if it wasn't). I also want to include netflow V9 in scapy, and have started working on it. 
In the course of working on it I've realized that it's a much larger project than I thought since netflow V9 is highly variable, unlike V1 and V5. I also am not entirely sure where these classes are referenced (haven't looked yet), so I don't believe just adding the classes in the file are enough. Feel free to correct me if I'm wrong and these are only used by the scapy interpreter/CLI. 
My point is, I could use some help. I will continue working on it (probably next week), and I have attached what I have so far (I apologize for the sloppy comment notes, they were for my own benefit). I didn't do a proper branch of scapy (hence the attached file) because I thought it would be a quick addition. Feel free to completely ignore the attached file if you can do better!

Sorry about the .txt, can't upload a .py here.
[netflow.py.txt](https://github.com/secdev/scapy/files/1048558/netflow.py.txt)

Edit: Ignore attached file. Look at @gpotter2 's branch instead!

**Comment by gpotter2** [comment]
Hey !
Here's what I could get so far:
https://github.com/gpotter2/scapy/tree/netflow-v9

There's is a mystery bug that i need to correct, but then we should be able to do stuff like:
```
a = NetflowTemplateV9()
b = NetflowFlowsetV9(templates=[NetflowTemplateV9(templateID=12, template_fields=[NetflowTemplateFieldV9(fieldType=4),NetflowTemplateFieldV9(fieldType=19)])])
c = NetflowDataflowsetV9(templateID=12, records=[NetflowRecordV9(fieldValue=b"\x01"), NetflowRecordV9(fieldValue=b"\x01\x02\x03\x04")])

p = a/b/c
```

**Comment by Forzii** [comment]
That's awesome, thanks so much!

**Comment by gpotter2** [comment]
Could you re-check that the packets match the RFC, and what you need ?

**Comment by Forzii** [comment]
Sure, on it.

**Comment by Forzii** [comment]
Hmm... correct me if I'm missing how something is designed, but this is what I noticed looking through it:
Typo: "NetflowV9TemplateFieldDefaultLenghts" should be "NetflowV9TemplateFieldDefaultLengths"

NetflowTemplateV9 doesn't have Flowset ID and Length.

NetflowRecordV9 is always a short, whereas in the RFC the data type and length change depending on the template, and then padded to a 4-byte aligned boundary at the end.

There is no layer/class for Options Template Flowset (or options data record, but I think we can just use the netflow record for that).

I'm not 100% sure what bind_layers does in scapy, but I'm guessing the various layers need to be bound together in ways that they would appear in correctly formatted traffic. 


Let me know if/how I can help. Looks great otherwise!

**Comment by gpotter2** [comment]
> Typo: "NetflowV9TemplateFieldDefaultLenghts" should be "NetflowV9TemplateFieldDefaultLengths"

Thanks

> NetflowTemplateV9 doesn't have Flowset ID and Length.

That's by design: to build a "Template FlowSet Format" packet, you need to use:
```
NetflowFlowsetV9(templates=[
    NetflowTemplateV9(template_fields=[
        NetflowTemplateFieldV9(),
        NetflowTemplateFieldV9(),
    ]),
    NetflowTemplateV9(template_fields=[...])
])
```

**Comment by gpotter2** [comment]
@Forzii Ok, i've updated my patch. Could you have another look ? Thanks !

**Comment by Forzii** [comment]
@gpotter2 
"NetflowDataflowsetV9" should probably be "NetflowDataFlowsetV9" to match convention.

There are no template layers in the bindings, but I'm guessing that's due to the design you mentioned previously.

I'm still unsure how you're handling the variable field type/length in the NetflowRecordV9.

Options stuff looks good as far as I can tell!

**Comment by gpotter2** [comment]
> I'm still unsure how you're handling the variable field type/length in the NetflowRecordV9.

Im not currently handling it, still looking for a way to do it :/

**Comment by Forzii** [comment]
@gpotter2 
Hmm. I'm sure you have much more experience with scapy than I do, but I was looking through http://scapy.readthedocs.io/en/latest/ to search for a solution. I haven't found anything specific I can recommend yet, but I'll let you know if I do.

**Comment by gpotter2** [comment]
Best option would be to use fields like `StrLenField` with `length_from` and `FieldLenField` with `length_of`, of stuff like that, but it's not possible to select a field out of the layer (here, it's in the previous layer). I'll might have to add support for that

**Comment by Forzii** [comment]
I'm not sure I have any more time today, but I'll dig into it more tomorrow when I can. I'm not sure I'm going to end up being much help, but we'll see.

**Comment by gpotter2** [comment]
@Forzii I've been performing some tests... I have absolutly no idea of how to link fields that are in different packets...
The goal would be that when the packets are as the following:
```
NetflowFlowsetV9(templateID=258, templates=[
    NetflowTemplateV9(template_fields=[
        NetflowTemplateFieldV9(),
        NetflowTemplateFieldV9(),
    ]),
])/NetflowDataflowsetV9(templateID=258, records=[
  NetflowRecordV9(fieldValue="..."),
  NetflowRecordV9(fieldValue="..."),
])
```

Then each `NetflowTemplateFieldV9` gets a `length_from=NetflowRecordV9...` and that each `NetflowRecordV9` gets a `length_of=NetflowTemplateFieldV9...`

@p-l- Hello, have you got any idea of how we could do that ? Or any other way we could avoid doing that...

**Comment by Forzii** [comment]
@gpotter2 Is there any way to allow field/value sharing using bind_layer? I don't see anything that indicates it can be used that way, but the function is supposed to bind two layers together, right?

**Comment by gpotter2** [comment]
Yes but `NetflowTemplateFieldV9` is a inside `NetflowTemplateV9`, inside `NetflowFlowsetV9`, so not directly linked to `NetflowRecordV9`

**Comment by Forzii** [comment]
@gpotter2 Ah, yeah... good point. And to make things more complicated, not every Netflow V9 packet has to have any templates at all... or it could be all templates. Is scapy's packet dissection stateful? I've honestly only used it for packet generation, since that's what I need it for.

**Comment by gpotter2** [comment]
@Forzii Hi !
It's been a long time since we discussed about this,
I got back to it recently and finally found a way to finish the thing :)

Could you check that it seems right (and works ?). I have no idea of how to test those packets :/
