### ISSUE TITLE
nmap_sig on OSX

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#673]
@guedou Hello ! (you're using OSX, right ?)
I have a problem with `nmap_sig`: for a mysterious reason (i don't have any OSX machine), my tests of https://github.com/secdev/scapy/pull/637 are failing for OSX only:
https://travis-ci.org/secdev/scapy/builds/239333860

Have you got any idea why the `nmap.py` `nmap_sig` function is failing ?

Thanks !

**Comment by guedou** [comment]
I rebooted and tested on OS X, and all the tests works fine here =/
