### ISSUE TITLE
Slow Scapy startup

### ISSUE THREAD

**Issue by giladreti** [secdev/scapy#679]
I recently installed Scaly for python 2.7 on windows 10. Every time I try to start it up (whether through importing it inside a code and whether using it directly), it takes more than a minute to load up. I suspect it is due to slow libraries importing or something.  Does anyone has any idea how to solve it?

**Comment by p-l-** [comment]
Can you report the exact version you are using?

**Comment by p-l-** [comment]
@gpotter2 we'll wait for the version information, but do you think this could be somehow related to #622?

**Comment by gpotter2** [comment]
@p-l- I was reported that too. It was fixed in https://github.com/secdev/scapy/pull/678

**Comment by giladreti** [comment]
@gpotter2 thank you so much! I reinstalled Scapy and now it takes only couple of seconds to load up! Thanks!

**Comment by giladreti** [comment]
Hmm... I'm experiencing much faster startup now, but sometimes it takes about 20 seconds, and sometimes less than 5. That's how it should be?

**Comment by p-l-** [comment]
@gpotter2 thanks. I'll wait for the answer from @giladreti before closing the issue. @giladreti Can you:
* report the version you are using,
* get the current development version and report if the problem still exists?

Thanks.

**Comment by giladreti** [comment]
I'm using the latest version. I downloaded it from here today.

**Comment by giladreti** [comment]
It's "a28da9f75"

**Comment by p-l-** [comment]
OK, so @gpotter2 this has **not** been fixed by #678. @giladreti could you try with the latest **stable** version (v2.3.3) and report if you experience the same problem?

**Comment by gpotter2** [comment]
Isn't 5-20 secs a good time ? Due to the powershell loading it has pretty much always been like so... The time has increased a bit with IPv6 support, but that sounds normal to me...

**Comment by giladreti** [comment]
@p-l- I downloaded Scapy 2.3.3, and now I get "list index out of range" problem.

**Comment by gpotter2** [comment]
@guedou This may be closed. Fixed

**Comment by gpotter2** [comment]
@guedou @p-l- No recent updates, fixed, can be closed
