### ISSUE TITLE
SyntaxError on voip.py

### ISSUE THREAD

**Issue by mtury** [secdev/scapy#682]
Calling @gpotter2 to fix non-fatal error in voip.py. I commented on commit https://github.com/secdev/scapy/commit/bf92eb54a3a340a495ce1503182492357410e6b0
I'm unsure how to test this module so I'll leave the PR to you. Hopefully it's very small. Thanks. :)

**Comment by mtury** [comment]
Actually this was removed in a more recent commit. Sorry about the noise to your mailbox. Closing issue.

**Comment by gpotter2** [comment]
@mtury Hey, (no worries for the noise). I also have no idea of how to test the module :/

Could you please have a look at this thread:
https://github.com/pyca/cryptography/issues/3668
This concerns you more than me... Thanks !!!!
