### ISSUE TITLE
Fragmented ICMP packets generates IPv6 Hop-By-Hop Option (0) packets

### ISSUE THREAD

**Issue by macagoule** [secdev/scapy#697]
Hi there,

Just wanted to do some tests with scapy around fragmented icmp packets. I found that non-fragmented packets are sent as ICMP while fragmented ones are send in a IPv6 Hop-By-Hop Option packets.

[Packet_Captures.zip](https://github.com/secdev/scapy/files/1107812/Packet_Captures.zip)

Packets sent : 
IPv6 Option : packet = IP(dst='192.168.154.130') / ICMP() / ('m'*10000)
Good ICMP : packet = IP(dst='192.168.154.130') / ICMP() / ('m'*1000)

Tested with updated Kali linux & scapy 2.3.3-1

root@kali:~/Desktop# dpkg --list |grep scapy
ii  python-scapy                              2.3.3-1                              all          Packet generator/sniffer and network scanner/discovery

Thanks for your help.

**Comment by guedou** [comment]
Could you try again with the current dev version ? I was not able to reproduce the issue, as I don"t really understand it ...

The following works as expected
```
>> packet = IP(dst='192.168.154.130') / ICMP() / ('m'*10000)
>>> IP(str(packet))
<IP  version=4L ihl=5L tos=0x0 len=10028 id=1 flags= frag=0L ttl=64 proto=icmp chksum=0x9f3 src=192.168.46.10 dst=192.168.154.130 options=[] |<ICMP  type=echo-request code=0 chksum=0xb6be id=0x0 seq=0x0 |<Raw  load='mmm
[..]
```

**Comment by macagoule** [comment]
Hi guillaume,

Under scapy 2.3.3-1 it seems the packet is an ICMP one. However, when capturing on the interface tcpdump or PCAP, the IPv4 protocol field changed from  0x01 -> 0x00.

Just tested with dev version and it seems resolved now 👍 

`2.3.3.dev497`

[ICMPOK.pcapng.zip](https://github.com/secdev/scapy/files/1108097/ICMPOK.pcapng.zip)
