### ISSUE TITLE
DNS over TCP doesn't work(DNS layer is displayed as Raw)

### ISSUE THREAD

**Issue by yamakira** [secdev/scapy#705]
I installed latest version of Scapy(2.3.3). I'm trying to read a pcap with DNS AXFR transaction(which is DNS over TCP). Scapy displays the DNS layer as Raw. Scapy works fine with DNS over UDP though. I noticed that this has been patched a while ago https://github.com/phaethon/scapy/pull/118 but why is it that I'm running into the same issue? Am I missing something?

**Comment by guedou** [comment]
It works fine in the current development version:
```
>>> pkt = IP()/TCP()/DNS(qd=DNSQR(qname="secdev.org."))
>>> IP(str(pkt))
<IP  version=4 ihl=5 tos=0x0 len=70 id=1 flags= frag=0 ttl=64 proto=tcp chksum=0x7caf src=127.0.0.1 dst=127.0.0.1 options=[] |<TCP  sport=domain dport=http seq=0 ack=0 dataofs=5 reserved=0 flags=S window=8192 chksum=0x736c urgptr=0 options=[] |<DNS  length=28 id=0 qr=0 opcode=QUERY aa=0 tc=0 rd=1 ra=0 z=0 ad=0 cd=0 rcode=ok qdcount=1 ancount=0 nscount=0 arcount=0 qd=<DNSQR  qname='secdev.org.' qtype=A qclass=IN |> an=None ns=None ar=None |>>>
```
