### ISSUE TITLE
sniff cannot capture all packets on windows

### ISSUE THREAD

**Issue by tt677666** [secdev/scapy#706]
version:2.3.3 windows7 X64 python 2.7

i try to use sniff function get tracffic on my windows machine. the code like this:
sniff(prn=http_header,store=0)

same time i use wireshark sniff traffic,

when couple minutes i found wireshark get packets more than scapy

may be performance problem?

**Comment by gpotter2** [comment]
Hey, could you try using the latest dev version ? (The one on github)

**Comment by tt677666** [comment]
i try it again with "65442c362",its still unsolved
the wiershark get about 30000 packets,and scapy get about 28000

**Comment by guedou** [comment]
Scapy might miss packets compared to wireshark, or similar tools. Filtering specific packets type might help.

**Comment by sunnogo** [comment]
> Scapy might miss packets compared to wireshark, or similar tools. Filtering specific packets type might help.
I got the same issue, if I send packet much faster than sniff callback.
e.g. send 2K packets in 1000 pps, and callback can only consume in 100pps. And finally I only capture 
1164 packets. It's a bad way to drop packets silently, and feel upset to see this reply.

**Comment by py2010** [comment]
Use pypcap (immediate=False + dispatch or readpkts)
immediate=True
无缓存实时模式, item/loop()处理频率更快, 丢包少, 但高并发还是有丢包.
immediate=False
缓存模式, dispatch / readpkts() 批量取, 高并发一个包都不会丢.

capture:
p = pcap.pcap(name='xxxx', immediate=False)
while 1:
    plist = p.readpkts()
    #.........
    #if plist:
    #    mq.put(plist)

========================
worker:

    plist = mq.get()
    if not plist:
        time.sleep(0.2)
        continue
    for ptime, pdata in plist:
        handler(ptime, pdata)

-------------------------

session = TCPSession(handler, False)  # (prn, store)
def handler(ptime, pdata):
    pack = Ether(pdata)
    logger.debug('PKT: %27s %21s ==>> %21s SIZE: %s' % (
        datetime.fromtimestamp(ptime).strftime("%Y-%m-%d %H:%M:%S.%f"),
        '%s:%s' % (pack[IP].src, str(pack[TCP].sport).ljust(5)),
        '%s:%s' % (pack[IP].dst, str(pack[TCP].dport).ljust(5)),
        str(size).rjust(4),
    ))

    pack.time = ptime
    session.on_packet_received(pack)

**Comment by py2010** [comment]
'''
    抓包时若系统数据窗口/缓冲区满, 会丢包.
    1) /etc/sysctl.conf
       /proc/sys/net/core/?mem_*
    2) libpcap库pcap-linux.c源码: opt.buffer_size = 2*1024*1024
    3) pypcap没调用libpcap库的pcap_set_buffer_size()设置缓存, 为默认2M
       (win平台: #define   WIN32_DEFAULT_KERNEL_BUFFER_SIZE 1000000)

    为防止丢包:
    1 所在CPU不能繁忙(100%), 使用子进程, 和封包解析进程分离.
    2 包处理函数能快速处理(不阻塞, 积压), 慢在取包时多线程无效.
    3 CPU各任务繁忙占用率高, 提高抓包进程优先级, 丢包率减少.
    4 CentOS下, 禁用缓存 immediate=True, 实时模式丢包率大大减少, 高并发仍有丢包.
    5 上面问题, 经测试可能是BUG(或为了节省CPU资源), 开启缓存后pypcap处理频率大大降低, 反而丢包多.
      和系统(sysctl.conf)rmem之类配置无关, 估计是pcap本身应用"缓存"满了导致丢包,
      immediate=False开启缓存并改为循环dispatch/readpkts方式批量取包, 高并发不再丢包.
    结论:
        pypcap开启缓存肯定是能容纳缓冲更多封包, immediate=False,
        但处理频率大大降低, 使用dispatch或者readpkts方式批量取包,
        批量取时, 可能多线程有效, 因问题解决未再进一步测试.
    '''

**Comment by gpotter2** [comment]
Hi, could you open a new issue in english ? Thanks
