### ISSUE TITLE
scapy get an error TCP payload length 

### ISSUE THREAD

**Issue by tt677666** [secdev/scapy#707]
version:2.3.3 windows7 X64 python 2.7
i get a packet **length is 60** and tcp payload **length is 4** ,the data from wireshark

i try parse it with scapy  but get wrong length data
code{
pkt = rdpcap('packet60_payload4.pcap')
for p in pkt:
    print len(p),len(p[TCP].payload)
}
result is 60,6
why the wireshark data diff with scapy data

if packet length is 1514 ,scapy work fine
ps: i had upload the packet
[packet60_payload4.zip](https://github.com/secdev/scapy/files/1123712/packet60_payload4.zip)

**Comment by gpotter2** [comment]
Hey could you try using the latest dev version ?

**Comment by tt677666** [comment]
@gpotter2 
 I try it again with "65442c362",its still unsolved,and i recheck the packet(lenth 60),found the packet have 2 Bytes  "padding", if use len(p[TCP].payload) method will incloud it and get wrong result
so i found  some formula from "https://ask.wireshark.org/questions/4178/how-do-i-determine-a-tcp-segments-length",  it's  "Total IP length" - " IP header length" - "TCP header length" and use it get correct result

**Comment by dark-lbp** [comment]
Scapy version: 2.3.3.dev511 
System: OSX 10.12.5
```python
>>> packets = rdpcap('packet60_payload4.pcap')
>>> packets[1].show()
###[ Ethernet ]###
  dst= c8:5b:76:30:db:02
  src= 38:97:d6:9c:dd:50
  type= 0x800
###[ IP ]###
     version= 4
     ihl= 5
     tos= 0x0
     len= 44
     id= 51182
     flags= DF
     frag= 0
     ttl= 57
     proto= tcp
     chksum= 0x88ec
     src= 113.142.80.143
     dst= 192.168.110.43
     \options\
###[ TCP ]###
        sport= http
        dport= 50278
        seq= 2960333006
        ack= 318053979
        dataofs= 5
        reserved= 0
        flags= PA
        window= 548
        chksum= 0xfb86
        urgptr= 0
        options= []
###[ Raw ]###
           load= '\x00\x00\x01\xe4'
###[ Padding ]###
              load= '\x00\x00'
# TCP payload
>>> packet[1][TCP].payload
<Raw  load='\x00\x00\x01\xe4' |<Padding  load='\x00\x00' |>>
>>> len(packet[1][TCP].payload)
6
# TCP load
>>> packet[1][TCP].load
'\x00\x00\x01\xe4'
>>> len(packet[1][TCP].load)
4
```
This packet has 2 bytes padding data.  the packet[1][TCP].load will give you the correct data(with out padding).
![jietu20170727-113856 2x](https://user-images.githubusercontent.com/3477662/28653648-575aa8d8-72c1-11e7-9985-7c6a03d9c857.jpg)

**Comment by tt677666** [comment]
@dark-lbp  thx, i try with 'packet[1][TCP].load',it's work fine
@gpotter2  it's not bug,you can close it! thx

**Comment by Hashim-Mirdad** [comment]
# This is the program which i write for sniffing packet using scapy python library.
from scapy.all import *
# COLORS FOR PRINTING 
BLUE = '\033[94M'
GREEN = '\033[32m'
RED = '\033[91m'
WHITE = '\033[0m'

def sniffPacket(packet):
	if packet.haslayer(IP):
		pckt_src=packet[IP].src
		pckt_dst = packet[IP].dst
		pckt_ttl = packet[IP].ttl
		print(RED +"IP packet:  " +  GREEN + str(pckt_src) + RED + "  is going to  " + GREEN + str(pckt_dst)+ RED + "  and has ttl value  " + GREEN + str(pckt_ttl))

def main():
	print("Custom Packets sniffer")
	sniff(filter="ip", prn=sniffPacket, iface="Target-eth0")

if __name__ == "__main__":
	main()

**Comment by gpotter2** [comment]
Please reopen an issue if necessary
