### ISSUE TITLE
problem with packet size more than 1500 bytes

### ISSUE THREAD

**Issue by GreatBahram** [secdev/scapy#709]
Hi 
I want to capture all DNS packets include: ANY, DNSSEC, RRSIG and so on. But when I run my program it shows me this error: 
`06-Jul-2017 11:45:46.000 client 172.17.2.235#42032: query: weather.gov. IN ALL + (4.2.2.4) 
WARNING: DNS RR prematured end (ofs=1477, len=1460)
DNS RR prematured end (ofs=1477, len=1460)
`
This is because packet size is more than 1500 bytes actually it's about 2300 bytes.
You can test with `dig @4.2.2.4 weather.gov ANY` this command shows message received size that is about 2306 bytes, but when I manipulate the dns.py to see actual size scapy found, that was about 1460 bytes. I was wondering why ? 
I attached simple code for testing. 
By the way I would like to help but when I look at the dns.py there's n't any docstring!
Thanks
[test.txt](https://github.com/secdev/scapy/files/1127032/test.txt)

**Comment by GreatBahram** [comment]
The problem exist in both python2 and python3. I even tried development version it even exist in that too.

**Comment by gpotter2** [comment]
Hi, that very sounds like a bug...

Could you share a pcap with some packets (wireshark) ?

**Comment by GreatBahram** [comment]
*Thanks for answering gpotter2*

 Yeah I'll send a pcap file. Please pay attention to the answers I've got from DNS server, all DNS queries response have UDP length more than ordinary size, because I sent request to get everything about that website (ANY request). 
[udp-dnssec.pcap.pcapng.zip](https://github.com/secdev/scapy/files/1132893/udp-dnssec.pcap.pcapng.zip)
Let me know if you need anything

**Comment by gpotter2** [comment]
Oh, i'm not sure that we support IP defragmentation while sniffing :/ Looks normal then

**Comment by gpotter2** [comment]
My bad, everything's ok.

You just need to defragment what you just have sniffed (use `defrag()` on the pcap)
The DNS packets are then sorted out.

There is a bug with the `defrag`  method: it crashes on real DNS packets. https://github.com/secdev/scapy/pull/712 should fix it.

**Comment by GreatBahram** [comment]
I don't want to save packets with Wireshark then parse them with Scapy. I want to access to each packet then process it. my question is why when I got a packet with size of more than 1500 bytes, Scapy return `WARNING: DNS RR prematured end (ofs=1547, len=1356) DNS RR prematured end (ofs=1547, len=1356)`
I attached two image that shows difference between normal dns response that has packet size lower than 1500 bytes and another image which shows unusual response with packet size more than 1500 bytes. 
I attached simple python code to show this problem. This warning comes from `dns.py` which has function at line 90 named `DNSgetstr` it can't process the response. I'm sure there is a problem. 
![normal response](https://user-images.githubusercontent.com/14103831/27991281-cc4b364c-6486-11e7-89dd-44357a827dc8.png)
![unusual response](https://user-images.githubusercontent.com/14103831/27991282-d2200052-6486-11e7-8093-993eaf44fff1.png)
[udp.txt](https://github.com/secdev/scapy/files/1133551/udp.txt)

**Comment by gpotter2** [comment]
@GreatBahram What is happening here is that the DNS answers are splitted into parts during the transfer. When scapy recieves a part during sniffing, it does not try to combine it with another part, so the data that is loaded is not complete.

We do not support defragmentation directly in sniffing for now. The only way you may defragment the packets is by using `defrag` or `defragment`.
