### ISSUE TITLE
BUG: reconstruct from string stops at Ether layer

### ISSUE THREAD

**Issue by Crossfire55555** [secdev/scapy#711]
Hey all,

There seems to be a problem with reconstructing packets from a hex string. 
![image](https://user-images.githubusercontent.com/8715505/27961420-8b3e7ffa-62fc-11e7-9810-e35c011e2466.png)

As you can see, I make _pack_ from Ether()/IP()/UDP()/DATA() then I make _packstr_ from a str(pack). Then following the example in the documentation, I try to reconstruct the packet into _recon_ using recon=Ether(packstr) but all that comes out is the Ether layer and the rest is in the reconstructed packet's payload. However the functionality is not totally broken. See that when reconstructing recon.load from IP generates the IP/UDP/DATA! that means its just a bug right? 
![image](https://user-images.githubusercontent.com/8715505/27961531-0912f92e-62fd-11e7-8afd-9b5eb3d531c5.png)

Lastly I delete recon.load and then append the separately reconstructed IP/UDP/DATA onto the Ether to create Recon which I then turn into a string with Reconstr and compare to the original packstr which comes back as the same string! 
![image](https://user-images.githubusercontent.com/8715505/27961681-85baf774-62fd-11e7-9084-8df2c61c6f8a.png)

That is the end of the Bug--------------------------------------

-------------My Project------Suggestions would be very appreciated-----------------
I am working on a project to create a program that can be included in other python scripts to quickly create packets in hex to be passed to a router for testing.  So far I have the user create each layer separately then they can pass those into a createPacket() to get a return value of the hex of the packet. I want to allow the user to name packets (just like scapy does) and manipulate parts of hit on the fly. For this I made a dict named Packets{} which holds the name of the packet and then the str(name).encode("HEX") of the packet is stored in association with the name. If the user wants to modify the padding then they should be able to retrieve the hex string from Packet{}, reconstruct it and then modify the padding to be stored back to Packet{}. 

I just started with Python and so far I love it. My background is all from school (I am a rising senior in computer engineering) and most of my experience is in C, C++, and Java. This is still a work in progress but I would love for you python fanatics to rip my code apart with suggestions on better alternatives for data-structures, argument passing, ect. Thanks for the help guys. I am trying to find the above bug but I probably will need some help. Message me with what you think!
![image](https://user-images.githubusercontent.com/8715505/27962367-b5487852-62ff-11e7-99f8-de6a0ff7ddbc.png)
![image](https://user-images.githubusercontent.com/8715505/27962379-c0c63994-62ff-11e7-8d4f-505a8ff04506.png)

**Comment by ThomasFaivre** [comment]
Hello!

I took a quick look at your issue (not at your project yet), and the reason Scapy doesn't find your IP layer is because the type field in the Ether layer doesn't correspond to an IP layer. You set it to 0x9000 but it should be 0x800 for IPv4 and 0x86DD for IPv6.
If you are working with usual protocol such as IPv4 and UDP, you should let Scapy fill in the blanks (here the type field)
Example:
```
>>> Ether()/IP()/UDP()
<Ether  type=0x800 |<IP  frag=0 proto=udp |<UDP  |>>>
```
Ether type and IP proto were filled automatically.

Hope that will help you!
I may take a look at your project this week-end, but I can't promise anything ^^"

Good luck anyway!

**Comment by Crossfire55555** [comment]
Ahhhh thanks that make sense. Oh the networking facepalm is real
