### ISSUE TITLE
Help Creating Custom Layer

### ISSUE THREAD

**Issue by Crossfire55555** [secdev/scapy#718]
Hello again,

I am trying to make my own custom layer so I went into my python dist-packages/scapy/layers and I added ttp.py. I then put "from scapy.all import *" at the top and I made my class. 
![image](https://user-images.githubusercontent.com/8715505/28140876-2e0c591c-6728-11e7-9c39-b58aa0a0bfe4.png)

I have my enums in a separate class named TTPTools(object): 
I saved the file and ran scapy and my custom layer is not recognized. The tutorial says that it should be accessible after this point. 

I know my path is correct. As a further check I put an open bracket in ttp.py and when I run scapy it tells me that it cannot import ttp.py. 

I am running 2.3.3.dev511

**Comment by Crossfire55555** [comment]
I also added "ttp" to conf.load_layers through config.py so the load layer change stays. However Ttp() still is unrecognized.

**Comment by gpotter2** [comment]
You might want to try to use `load_layer("trop")`

**Comment by Crossfire55555** [comment]
Hmmm maybe I over looked it but it seems that my layer file cant be imported because "name '_ttp_type' is not defined". I explicitly copied the format that other layers use. After searching online I noticed that everyone specifies enums in dictionaries as { "end_of_list"":0 } is there a difference? Here is a picture 
![image](https://user-images.githubusercontent.com/8715505/28169343-00a837ce-67b0-11e7-8adb-556db25ff296.png)

**Comment by Crossfire55555** [comment]
That did the trick. Many thanks
