### ISSUE TITLE
VRRPv3 checksum is incorrect

### ISSUE THREAD

**Issue by YagnaPhani** [secdev/scapy#720]
Hi Team

VRRPv3 checksum calculation is incorrect. Wireshark complains about it. Could you please check this issue.

>>> p = Ether(src="00:00:5e:00:02:02",
... dst="01:00:5e:00:00:12")/IP(src="20.0.0.3", dst="224.0.0.18",
... ttl=255)/VRRP(priority=254,vrid=2,version=3,adv=1,addrlist=["20.0.1.2","20.0.1.3"])

Frame 99: 58 bytes on wire (464 bits), 58 bytes captured (464 bits) on interface 0
    Interface id: 0
    WTAP_ENCAP: 1
    Arrival Time: Jul 14, 2017 08:14:36.507479000 PDT
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1500045276.507479000 seconds
    [Time delta from previous captured frame: 0.835974000 seconds]
    [Time delta from previous displayed frame: 0.835974000 seconds]
    [Time since reference or first frame: 72.835964000 seconds]
    Frame Number: 99
    Frame Length: 58 bytes (464 bits)
    Capture Length: 58 bytes (464 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ip:vrrp]
Ethernet II, Src: UscInfor_00:02:02 (00:00:5e:00:02:02), Dst: IPv4mcast_00:00:12 (01:00:5e:00:00:12)
    Destination: IPv4mcast_00:00:12 (01:00:5e:00:00:12)
        Address: IPv4mcast_00:00:12 (01:00:5e:00:00:12)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
    Source: UscInfor_00:02:02 (00:00:5e:00:02:02)
        Address: UscInfor_00:02:02 (00:00:5e:00:02:02)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IP (0x0800)
Internet Protocol Version 4, Src: 20.0.0.3 (20.0.0.3), Dst: 224.0.0.18 (224.0.0.18)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00: Not-ECT (Not ECN-Capable Transport))
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..00 = Explicit Congestion Notification: Not-ECT (Not ECN-Capable Transport) (0x00)
    Total Length: 44
    Identification: 0x0001 (1)
    Flags: 0x00
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 255
    Protocol: VRRP (112)
    Header checksum: 0xc74b [correct]
        [Good: True]
        [Bad: False]
    Source: 20.0.0.3 (20.0.0.3)
    Destination: 224.0.0.18 (224.0.0.18)
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
Virtual Router Redundancy Protocol
    Version 3, Packet type 1 (Advertisement)
        0011 .... = VRRP protocol version: 3
        .... 0001 = VRRP packet type: Advertisement (1)
    Virtual Rtr ID: 2
    Priority: 254 (Non-default backup priority)
    Addr Count: 2
    0000 .... = Reserved: 0
    .... 0000 0000 0001 = Adver Int: 1
    **Checksum: 0xa6f4 [incorrect, should be 0xb256]**
    IP Address: 20.0.1.2 (20.0.1.2)
    IP Address: 20.0.1.3 (20.0.1.3)

**Comment by Crossfire55555** [comment]
What version of scapy are you running?

**Comment by YagnaPhani** [comment]
Welcome to Scapy (2.2.0)

**Comment by Crossfire55555** [comment]
Im no expert but if and when they do get here they will prob ask you to try the dev build. its on the how to doc and chances are there is already a fix it just hasent made it out onto a stable branch yet. 

update to 2.3.3.dev511  give it a go if you need help with that just ask :)

**Comment by YagnaPhani** [comment]
Thanks for the suggestion.
I tried with dev version. Still the issue is same.

Welcome to Scapy (2.3.3.dev519)

>>> p.show2()
###[ Ethernet ]###
  dst= 01:00:5e:00:00:12
  src= 00:00:5e:00:02:02
  type= 0x800
###[ IP ]###
     version= 4
     ihl= 5
     tos= 0x0
     len= 44
     id= 1
     flags=
     frag= 0
     ttl= 255
     proto= vrrp
     chksum= 0xc74b
     src= 20.0.0.3
     dst= 224.0.0.18
     \options\
###[ VRRP ]###
        version= 3
        type= 1
        vrid= 2
        priority= 254
        ipcount= 2
        authtype= 0
        adv= 1
        chksum= 0xa6f4
        addrlist= [20.0.1.2, 20.0.1.3]
        auth1= 0
        auth2= 0

**Comment by gpotter2** [comment]
@YagnaPhani sounds like a bug...

I cannot understand the obscure RFC though :/

> The checksum is the 16-bit one's complement of the one's complement
> sum of the entire VRRP message starting with the version field.  For
> computing the checksum, the checksum field is set to zero.  See RFC
> 1071 for more detail

**Comment by Crossfire55555** [comment]
I checked VRRP's fields and it seems to be correct. 

Validate the checksum() which is in scapy/utils.py line 273.
so if you want to double check vrrp.py in scapy/layers I didnt see anything that was inconsistent with vrrp's definition.

**Comment by YagnaPhani** [comment]
@gpotter2  Yes. They are not clear about it.

**Comment by YagnaPhani** [comment]
@Crossfire55555 

I saw that vrrp.py file and it says only RFC 3768.

Is RFC 5798- VRRPv3 for IPv4 and IPv6 not supported at all?

Other layer checksum doesnt have any problem

**Comment by Crossfire55555** [comment]
I am fairly new to Scapy and do know the inner details of what is supported :/ sorry.

**Comment by gpotter2** [comment]
Seems that VRRPv3 is slightly different, so not supported yet.

**Comment by YagnaPhani** [comment]
Is there any way I can craft the packet for the protocol that is not supported yet?

**Comment by gpotter2** [comment]
@YagnaPhani It is fixed by https://github.com/secdev/scapy/pull/732, not merged yet :) Could you try it ?

**Comment by YagnaPhani** [comment]
@gpotter2 

Thank you for fixing this. With your changes, checksum is correct for IPv4 VRRPv3. 
Could you please let me know if VRRPv3 for IPv6 is supported?

Also, in your code,

VRRP.py line 38 - if self.version >= 3:
I think, this should be only for version 3( not for > 3).

Frame 27: 60 bytes on wire (480 bits), 60 bytes captured (480 bits) on interface 0  
  ...
Internet Protocol Version 4, Src: 20.0.0.3 (20.0.0.3), Dst: 224.0.0.18 (224.0.0.18)
    Version: 4
    Header length: 20 bytes
    Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00: Not-ECT (Not ECN-Capable Transport))
        0000 00.. = Differentiated Services Codepoint: Default (0x00)
        .... ..00 = Explicit Congestion Notification: Not-ECT (Not ECN-Capable Transport) (0x00)
    Total Length: 44
    Identification: 0x0001 (1)
    Flags: 0x00
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 255
    Protocol: VRRP (112)
    Header checksum: 0xc74b [correct]
        [Good: True]
        [Bad: False]
    Source: 20.0.0.3 (20.0.0.3)
    Destination: 224.0.0.18 (224.0.0.18)
    [Source GeoIP: Unknown]
    [Destination GeoIP: Unknown]
Virtual Router Redundancy Protocol
    Version 3, Packet type 1 (Advertisement)
        0011 .... = VRRP protocol version: 3
        .... 0001 = VRRP packet type: Advertisement (1)
    Virtual Rtr ID: 2
    Priority: 254 (Non-default backup priority)
    Addr Count: 2
    0000 .... = Reserved: 0
    .... 0000 0000 0001 = Adver Int: 1
    **Checksum: 0xb256 [correct]**
    IP Address: 20.0.1.2 (20.0.1.2)
    IP Address: 20.0.1.3 (20.0.1.3)

**Comment by YagnaPhani** [comment]
@gpotter2 

VRRP Authentication is removed in VRRPv3. But still we are sending auth1, auth2 data in VRRPv3 packet.

>>> p = Ether(src="00:00:5e:00:02:02",
... dst="01:00:5e:00:00:12")/IP(src="20.0.0.3", dst="224.0.0.18",
... ttl=255)/VRRP(priority=254,vrid=2,version=3,adv=1,addrlist=["20.0.1.2","20.0.1.3"],auth1=8)

tcpdump: listening on vlan191, link-type EN10MB (Ethernet), capture size 65535 bytes
10:13:40.299129 00:00:5e:00:02:02 > 01:00:5e:00:00:12, ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 255, id 1, offset 0, flags [none], proto VRRP (112), length 44)
    20.0.0.3 > 224.0.0.18: vrrp 20.0.0.3 > 224.0.0.18: VRRPv3, Advertisement
	0x0000:  4500 002c 0001 0000 ff70 c74b 1400 0003  E..,.....p.K....
	0x0010:  e000 0012 3102 fe02 0001 b24e 1400 0102  ....1......N....
	0x0020:  1400 0103 0000 **0008** 0000 0000 0000       ..............
 
Is it possible to have separate class for VRRPv3?

**Comment by gpotter2** [comment]
You are really right.
Here's a new version:
https://github.com/secdev/scapy/pull/736
(the PR has changed)

**Comment by YagnaPhani** [comment]
@gpotter2 

Thank you for the fix.

I am able to send VRRPv3 IPv4 packet correctly. 

One note is that, advertisement interval in VRRPv3 is in centi seconds. The default value is 1 sec which is 100 centi seconds.

**Comment by gpotter2** [comment]
@YagnaPhani Thanks for your note, i just fixed it. Thanks for reporting the bug !

**Comment by gpotter2** [comment]
@guedou Can be closed
