### ISSUE TITLE
BitField->reverse(self,val) reverses order of fields... why?

### ISSUE THREAD

**Issue by Crossfire55555** [secdev/scapy#726]
Is there a bug in BitField's reverse()? I have a very unusual cookie that I am trying to make. All the fields are BitFields. Here is the test class I made for easier testing 
![image](https://user-images.githubusercontent.com/8715505/28423177-5b58b6fc-6d38-11e7-911b-4fa712ee4dc0.png)
First with Reverse() active 
![image](https://user-images.githubusercontent.com/8715505/28423594-70fe16c2-6d39-11e7-8b14-f0bace235ddb.png)
This give the output of the types in reverse order
![image](https://user-images.githubusercontent.com/8715505/28423550-55ecce32-6d39-11e7-9e4a-1d4c8f85c0d2.png)

now without reverse active
![image](https://user-images.githubusercontent.com/8715505/28423265-91f5eaae-6d38-11e7-9632-4c42ccec3241.png)
This is the correct output that I was expecting
![image](https://user-images.githubusercontent.com/8715505/28423478-29ad9e28-6d39-11e7-9d10-9b9fbb7447ac.png)

Im using 2.3.3.dev511. I understand that reverse if for systems with a particular endianess but this seems to be resulting a bug where it doesnt reverse the string. Thought I should bring this to your attention since it took me forever to figure out what was going on.

**Comment by Crossfire55555** [comment]
update: Without reverse the order is still scrambled. 
![image](https://user-images.githubusercontent.com/8715505/28424223-0ecbc736-6d3b-11e7-85b7-8c373554b309.png)
![image](https://user-images.githubusercontent.com/8715505/28424251-24cebe6c-6d3b-11e7-9161-1e7a834c4efb.png)

any ideas as to how to make this work properly?

**Comment by p-l-** [comment]
Please avoid screenshots as we cannot copy & paste your code, and use proper markdown formatting instead. Thanks!

**Comment by Crossfire55555** [comment]
This is my actual code that im trying to implement. But the bitfields are screwing up the order of the fields. in this case when I make a generic MPCookie and run a.show() then it orders it as Reserved, StreamNumber, ReorderID, parcel_type. 
```python
class MPCookie(Packet):
    name = "MPCookie "
    fields_desc = { BitEnumField("parcel_type", 0, 4, _mp_parcel_type),
                    BitField("ReorderID", 0, 13),
                    BitField("StreamNumber", 0, 11),
                    ConditionalField(BitField("Reserved", 0, 4)
                        ,lambda p:p.parcel_type!=1),
                    ConditionalField(BitField("Reserved", 0, 6)
                        ,lambda p:p.parcel_type==1),
                    ConditionalField(BitFieldLenField("PacketLength", None, 14)
                        ,lambda p:p.parcel_type==1),
                    ConditionalField(ShortField("Reserved2", 0)
                        ,lambda p:p.parcel_type==1),
                    ConditionalField(LongField("TailHandle", 0)
                        ,lambda p:p.parcel_type==1),
                  }
```

**Comment by Crossfire55555** [comment]
I am asking this question in a little more refined way in a different

**Comment by p-l-** [comment]
Please use simple and reproducible examples: we need `_mp_parcel_type` defined here.

You are using sets (`{...}`) instead of lists (`[...]`) for `fields_desc`. Sets are unordered. Use lists and your code should work as expected.

**Comment by Crossfire55555** [comment]
.... once again defeated again by lack of knowledge of python! Thank you so much @p-l- I was about to rewrite the addfield and getfield function. Thanks for the quick help and explanation
