### ISSUE TITLE
Question to PPP_LCP

### ISSUE THREAD

**Issue by lidllohntsich** [secdev/scapy#729]
hi,

when working with the scapy.layers.ppp.py of the scapy-master branch, I came across the 
following question:

class PPP_LCP() has a data field instead of an option field. Due to this it's not possible to
handle the PPP_LCP_Options properly.

IMHO the following proposal (see python comments) should fix the problem:

```python

class PPP_LCP_Option(Packet):
    name = "PPP LCP Option"
    fields_desc = [ByteEnumField("type", None, _PPP_lcp_optiontypes),
                   FieldLenField("len", None, fmt="B", length_of="data",
                                 adjust=lambda p,x:x+2),
                   StrLenField("data", None, length_from=lambda p:p.len-2)]
                   

    def extract_padding(self, pay):
        return "", pay

    registered_options = {}

    @classmethod
    def register_variant(cls):
        cls.registered_options[cls.type.default] = cls

    @classmethod
    def dispatch_hook(cls, _pkt=None, *args, **kargs):
        if _pkt:
            o = ord(_pkt[0])
            return cls.registered_options.get(o, cls)
        return cls

#class PPP_LCP() moved after PPP_LCP_Option()
class PPP_LCP(Packet):
    name = "PPP Link Control Protocol"
    fields_desc = [ByteEnumField("code", 5, _PPP_lcptypes),
                   XByteField("id", 0),
                   #FieldLenField("len", None, fmt="H", length_of="data",
                   #              adjust=lambda p, x: x + 4),
                   FieldLenField("len", None, fmt="H", length_of="options",
                                 adjust=lambda p, x: x + 4),
                   #StrLenField("data", "",
                   #            length_from=lambda p:p.len-4)]
                   PacketListField("options", [],  PPP_LCP_Option, length_from=lambda p:p.len-4,)] 

```

Comment are welcome.

regards

lidl

**Comment by p-l-** [comment]
Hi,

From what I can read (I'm far from being a PPP expert), PPP_LCP may contain any kind of data. You need to use a `PPP_LCP_Configure` specific subclass, and Scapy does that alone when dissecting PPP frames with code set to 1, 2, 3, or 4.

Does that seem correct to you?

**Comment by lidllohntsich** [comment]
hi,
thanks. you are right.

One thing is still missing within the PPP protocol:
It would be nice to have the PPPoE tags added within the PPPoED (e.g. PADO:
PPPoE Tags
  Tag: Service-Name 
  Tag: AC-Name
    String Data: lpzbr001 
  Tag: Host-Uniq
    Binary Data: (16 bytes)
....)

Comments are welcome.

**Comment by p-l-** [comment]
I have no idea what this is, but I'll have a look if you submit a pull request! Can we close this issue in the meantime?

**Comment by lidllohntsich** [comment]
hi,

ok I will send a pull request.

Thanks
