### ISSUE TITLE
scapy.all

### ISSUE THREAD

**Issue by QwistyS** [secdev/scapy#735]
Hi
In you official example doc`s
from scapy import srp,Ether,ARP,conf

However ARM and Ether located under 
from scapy.layers.l2 import ARP,Ether
from scapy.all import srp, conf

that normal or it`s problem just with me ?

**Comment by p-l-** [comment]
Can you point a link to what you call "official example"? Is that from the repository? Or secdev.org?

**Comment by p-l-** [comment]
[Here](http://www.secdev.org/projects/scapy/build_your_own_tools.html) and [here](https://github.com/secdev/scapy/blob/master/doc/scapy/extending.rst#using-scapy-in-your-tools) I read
```Python
from scapy.all import srp,Ether,ARP,conf
```
And this should actually work, yes.

**Comment by QwistyS** [comment]
there is that
![screen shot 2017-07-25 at 14 20 36](https://user-images.githubusercontent.com/30431487/28569945-99f90690-7144-11e7-8690-b4f7607aaa06.png)

That one working
![screen shot 2017-07-25 at 14 23 23](https://user-images.githubusercontent.com/30431487/28570014-e5dfe862-7144-11e7-9b63-073f4128a3c6.png)

**Comment by p-l-** [comment]
Is it **not working**, or is it just your text editor which is lost here? Can you run your code? What error do you get. BTW, which version of Scapy are you using?

**Comment by QwistyS** [comment]
scapy 2.3.3
Python 2.7.10
sierra 10.12.6

No error or Exeaption was raised, but no valid answer was supplied also.
With that: from scapy.layers.l2 import ARP,Ether
i got list of mac with addresses.

But it`s Ok. i solved my issue already.
Still many many^2^n thx for that fast response
