### ISSUE TITLE
Big-endian & Little-Endian issue

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#737]
Hi everyone,

It seems that we are concerned by:
`https://github.com/phaethon/scapy/issues/183`

I was able to replicate :/

```
>>> raw = b'\x00\x00\x1a\x00/H\x00\x00\xe1\xd3\xcb\x05\x00\x00\x00\x00@0x\x14@\x01\xac\x00\x00\x00'
>>> r = RadioTap(raw)
>>> r.show()
###[ RadioTap dummy ]### 
  version= 0
  pad= 0
  len= 26
  present= TSFT+Flags+Rate+Channel+dBm_AntSignal+Antenna+b14
  notdecoded= '\xe1\xd3\xcb\x05\x00\x00\x00\x00@0x\x14@\x01\xac\x00\x00\x00'
```

@guedou @p-l-

**Comment by p-l-** [comment]
Nice catch! The patch proposed in the issue linked in your message seems reasonable to me. Care to submit a PR?

**Comment by gpotter2** [comment]
Should we also add all missing fields :
`https://github.com/phaethon/scapy/blob/master/scapy/layers/dot11.py#L130`

But in that case, should we copy the `i2dict` system that is behind this ?
Otherwise, how do we reproduce this functionality of `FlagsField` ?

**Comment by p-l-** [comment]
We may add the missing fields, but maybe in a different PR?

About the `i2dict`, I feel like we don't need it, we can replace `lambda pkt: pkt.getdictval('present')['TSFT'])` by `lambda pkt: pkt.present.TSFT` (which looks more readable to me anyway).

**Comment by gpotter2** [comment]
Should Ben fixed in https://github.com/secdev/scapy/pull/759
