### ISSUE TITLE
Can't capture: sent packets via scapy, using wireshark from windows to RPI

### ISSUE THREAD

**Issue by Kash-A** [secdev/scapy#739]
I am trying to send some packets using scapy 2.3.3 from my windows machine (Windows 7, python 2.7.13). My code is very simple. i.e

send(IP(src="192.168.0.254", dst="192.168.0.10", ttl=128)/ICMP()/"HelloWorld")

scapy says that the packet is sent, But I can't really capture it via WireShark. If I try to send packets from my RPI module (IP=192.168.0.10) to my windows machine. Then I can capture those packets.

plus: I am using cmd with administrator rights to use scapy.
Also tried after setting the firewall OFF.

Any thoughts on that.

**Comment by Kash-A** [comment]
Not really a scapy issue. Wrong selection of interface card. With the correct selection of the iface, I was able to do the task.

**Comment by cuong02n** [comment]
are you try to send packet to public IP , is there any diffirence between send() and sendp()
