### ISSUE TITLE
Scapy errors

### ISSUE THREAD

**Issue by nBlueDev** [secdev/scapy#741]
Hello guys,

After installing scapy, I got some Errors here... What is this all about and how to fix those?

`MacBook-Pro:~ bluedev$ scapy`
> INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
> ERROR: Unable to import dnet module: No module named dumbnet
> WARNING: No route found for IPv6 destination :: (no default route?)
> INFO: Can't import python Crypto lib. Won't be able to decrypt WEP.
> INFO: Can't import python Crypto lib. Disabled certificate manipulation tools
> INFO: Can't import python ecdsa lib. Disabled certificate manipulation tools
> Welcome to Scapy (2.3.3)

**Comment by Crossfire55555** [comment]
Error looks like it may be a typo in the latest version. Get the dev branch for the most up to date scapy. The Other stuff is the result of not having optional packages or settings enabled that would let you use some of those scapy features. You can still use most of scapy tho so dont let that discourage you.

**Comment by gpotter2** [comment]
Yeah those are only warnings about disabled functions because of missing dependencies.

You need to install the dependency `python-dumbnet` to send packets.

**Comment by guedou** [comment]
Please have a look at the documentation http://scapy.readthedocs.io/en/latest/installation.html
