### ISSUE TITLE
Loading TLS layer breaks debugger

### ISSUE THREAD

**Issue by rafajot** [secdev/scapy#746]
PyCharm Community Edition 2017.2
Build #PC-172.3317.103, built on July 25, 2017
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1
Scapy: 2.3.3.dev532

Please refer to https://stackoverflow.com/questions/40703435/scapy-module-blocks-pycharm-debugger and Spiceisland analysis with x509 module breaking debugger. This issue I believe has been fixed already but similar issue I can see with the tls module in current version of scapy: 2.3.3.dev532

**Comment by gpotter2** [comment]
Calling @mtury for that...

**Comment by mtury** [comment]
To be closed once PR #760 has been merged.
