### ISSUE TITLE
can i user scapy parse packet in socket sniff

### ISSUE THREAD

**Issue by tt677666** [secdev/scapy#747]
socket sniff use some code like this :
s = socket.socket(socket.AF_INET,socket.SOCK_RAW,socket.IPPROTO_IP)
s.bind(("192.168.1.6",0))
s.setsockopt(socket.IPPROTO_IP,socket.IP_HDRINCL,1)
s.ioctl(socket.SIO_RCVALL,socket.RCVALL_ON)
while True:
	data = s.recvfrom(65535)
        
i try use 'Ether(data[o])' but get some wrong result.what should i do,thx

**Comment by p-l-** [comment]
Given the options you are using, you probably get the `IP` layer, not the `Ether` layer. Use `IP()` instead of `Ether()`.
