### ISSUE TITLE
Error: cannot convert argument to integer

### ISSUE THREAD

**Issue by mge43** [secdev/scapy#749]
Hi,
I have installed scapy 2.3.3 and was able to run gattclient.py in the PyBT project. However, when I typed connect BD_ADDR random in the interactive console, I got the error:
Cannot convert argumetn to integer
The error occurred in scapy/fileds.py when calling s+struct.pack(self.fmt, self.i2m(pkt, val)) function.
Any one using PyBT with Scapy got any idea on this?
Thanks : )

**Comment by p-l-** [comment]
Hi,

Based on PyBT's [README](/mikeryan/PyBT/blob/master/README.md), it seems that it cannot work with Scapy but requires you to use an (outdated) fork with specific patches instead.
