### ISSUE TITLE
is possible to drop the detected packets when sniff with custom function before it send out in window and linux?

### ISSUE THREAD

**Issue by hoyeunglee** [secdev/scapy#754]
is possible to drop the detected packets when sniff with custom function before it send out in window and linux?

i discover port 443 using UDP layer , and hope to drop these kind of packets in port 443

**Comment by p-l-** [comment]
I'm not sure what you're asking, but Scapy is **not** a firewall and cannot prevent a packet from being sent or received by the host's IP stack.

Please re-open this question if needed.
