### ISSUE TITLE
iptables ignore pakage send by scapy

### ISSUE THREAD

**Issue by ddisaster** [secdev/scapy#762]
pakages send by scapy send() are not detected by iptables rules
this is the question in stackoverflow for this Problem:
https://stackoverflow.com/questions/45696288/iptables-ignore-pakage-send-by-scapy

**Comment by p-l-** [comment]
Hi,

Scapy sends packet at a low level and they are not seen by netfilter. If you want to send packets seen by netfilter, either you can send them from another computer, or you can use the regular `socket` API to have the host's IP stack send packets for you.

Hope this helps, good luck!
