### ISSUE TITLE
Unrelevant errors from TLS layer

### ISSUE THREAD

**Issue by rafajot** [secdev/scapy#763]
I'm not quite sure but this might be ms windows specific issue. I have not been able to reproduce it on Linux.
It looks like TLS layer code is engaged where possibly it shouldn't be.

```
scapy version: 2.3.3.dev560
>>> for i in range(500):
...    sr(IP(dst="6.6.6.5") / ICMP(), timeout=0.8,verbose=0)
...
(<Results: TCP:0 UDP:0 ICMP:0 Other:0>, <Unanswered: TCP:0 UDP:0 ICMP:1 Other:0>)
(<Results: TCP:0 UDP:0 ICMP:0 Other:0>, <Unanswered: TCP:0 UDP:0 ICMP:1 Other:0>)
(<Results: TCP:0 UDP:0 ICMP:0 Other:0>, <Unanswered: TCP:0 UDP:0 ICMP:1 Other:0>)
INVALID CERTIFICATE VERIFY SIGNATURE
(<Results: TCP:0 UDP:0 ICMP:0 Other:0>, <Unanswered: TCP:0 UDP:0 ICMP:1 Other:0>)
[...]

```
[scapy_session.txt](https://github.com/secdev/scapy/files/1233455/scapy_session.txt)

**Comment by p-l-** [comment]
A partial is to prevent the TLS layer from being loaded by default. I also think that `print()` calls should be replaced by proper logging calls. @mtury what do you think?

**Comment by p-l-** [comment]
I consider this issue fixed for now, since we will only enable the TLS layer module when it won't try to validate certificates. Please reopen it if needed.
