### ISSUE TITLE
NameError: name 'nmap_sig' is not defined

### ISSUE THREAD

**Issue by hoyeunglee** [secdev/scapy#766]
from scapy.all import *
sig=nmap_sig("202.171.214.10")

>>> sig=nmap_sig("202.171.214.10")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'nmap_sig' is not defined

**Comment by p-l-** [comment]
You have to load the Nmap module (`load_module('nmap')`) before you can call `nmap_sig()`.
