### ISSUE TITLE
SAckOK is work? (in tcp_options)

### ISSUE THREAD

**Issue by mw70830** [secdev/scapy#78]
-previously, my english skil is very weak. sorry.

is SAckOK work? (in tcp_options)

i tried that,
but did not work.
(work means show the options in packet dump)

so i change source like bottom, (in "Layer/inet.py"), 
then work.

but i don't trust myself.

i have question.

like these modify,
is that problem solved?

```diff
@@ -247,6 +247,10 @@ class TCPOptionsField(StrField):
                 opt.append(("NOP",None))
                 x=x[1:]
                 continue
+            if onum == 4:
+                opt.append(("SAckOK",None))
+                x=x[1:]
+                continue
             olen = ord(x[1])
             if olen < 2:
                 warning("Malformed TCP option (announced length is %i)" % olen)

@@ -276,6 +280,9 @@ class TCPOptionsField(StrField):
                 elif oname == "EOL":
                     opt += "\x00"
                     continue
+                elif oname == "SAckOK":
+                    opt += "\x04"
+                    continue
                 elif TCPOptions[1].has_key(oname):
                     onum = TCPOptions[1][oname]
                     ofmt = TCPOptions[0][onum][1]

```

**Comment by p-l-** [comment]
Hi,

You can simply use `TCP(options=[("SAckOK", "")]`, and it should work (at least, the crafted packet is then properly understood by Wireshark).

**Comment by mw70830** [comment]
thank you~

before i try ("SAckOK", None) ...OTL..

thankyou thankyou

**Comment by p-l-** [comment]
@mw70830 you're welcome!
