### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by KamranSyed** [secdev/scapy#783]
I see this from time to time resulting in crash. Scapy is passively listening for management frames of Ethernet.

Traceback (most recent call last):
  File "probemon.py", line 96, in <module>
    main()
  File "probemon.py", line 93, in main
    sniff(iface=args.interface, prn=built_packet_cb, store=0)
  **File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 656, in sniff**
    r = prn(p)
  File "probemon.py", line 59, in packet_callback
    logger.info(delimiter.join(fields))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 1: ordinal not in range(128)

**Comment by gpotter2** [comment]
Hello,
the bug is not from scapy. It's from:
```
File "probemon.py", line 59, in packet_callback
logger.info(delimiter.join(fields))
```

**Comment by KamranSyed** [comment]
Thank you for quick help :)
