### ISSUE TITLE
ARP sniffing issue

### ISSUE THREAD

**Issue by collinsullivanhub** [secdev/scapy#784]
Wrote a script to sniff for gratuitous ARPs (attacker ARP poisoning victim) which uses an ARP op code of 2 (response) to poison a target. However, the odd thing is that when I launch the attack, my prn function says the gratuitous ARP is an _ARP request, or has an op code of 1_. 

In wireshark, it picks up the gratuitous ARP response. Why does scapy sniff the response as a request?

**Comment by collinsullivanhub** [comment]
Code Snippet:

if packet[ARP].op == 2 and packet[ARP].psrc == GATEWAY_IP and packet[Ether].src !=GATEWAY_MAC:
       print "\033[31m[!]WARNING: GATEWAY IMPERSONTATION DETECTED. 

My prn points to this conditional, which is not grabbing it

**Comment by gpotter2** [comment]
Hi,
what's the exact command you're using ?

**Comment by collinsullivanhub** [comment]
sniff(filter = "arp", prn = arp_display)

**Comment by collinsullivanhub** [comment]
accidently closed =P

**Comment by gpotter2** [comment]
Could you provide a working snippet (sniff command + arp_display func...)
Could you also provide your OS, python version, scapy version ?

Also please check that you have installed tcpdump (windump on windows) (check content of `conf.prog.tcpdump`), which is required for string filtering.

**Comment by collinsullivanhub** [comment]
OS: Ubuntu 16.04
Scapy Version: 2.3.3
Python Version: 2.7.12

**Comment by collinsullivanhub** [comment]
https://pastebin.com/fM4gLd9H

**Comment by collinsullivanhub** [comment]
Above is the code snippet. Basically, I ARP the DG for it's L2 address, then save it as the GATEWAY_MAC variable (which you see in the code). If the ARP response says it is coming from the Default Gateway IP, but has a L2 _not_ equal to GATEWAY_MAC, it prints a warning.

I know it's not a tcpdump error, since it grabs the other ARPs just fine based on the "arp" string. It is only when I send gratuitous ARPs that I get the first condition returned saying it sniffed a request

**Comment by gpotter2** [comment]
Well it seems that you are sending a gratuitous ARP request...
`opcode` can be either 1 or 2 if it's a gratuitous ARP request or reply.

Could you also try with the latest dev scapy version (download zip on github then run `python setup.py install`)

If you feel there's a bug, which i really doubt, please link a pcap file (in a zip) containing a packet that would be a gratuitous arp response in wireshark, and a gratuitous arp reply in scapy.
I just tried out and could not experience your bug...

```
# note that my local IP is 192.168.0.10
>>> Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(op="who-has", hwdst="ff:ff:ff:ff:ff:ff", pdst="192.168.0.10")
<Ether  dst=ff:ff:ff:ff:ff:ff type=0x806 |<ARP  op=who-has hwdst=ff:ff:ff:ff:ff:ff pdst=192.168.0.10 |>>
>>> wireshark(_)
# It is an ARP request


>>> Ether(dst="ff:ff:ff:ff:ff:ff")/ARP(op=2, hwdst="ff:ff:ff:ff:ff:ff", pdst="192.168.0.10")
<Ether  dst=ff:ff:ff:ff:ff:ff type=0x806 |<ARP  op=is-at hwdst=ff:ff:ff:ff:ff:ff pdst=192.168.0.10 |>>
# It is an ARP reply
```

**Comment by collinsullivanhub** [comment]
I have also tried:
if packet[ARP].op == 2 and packet[ARP].psrc == GATEWAY_IP and packet[Ether].src !=GATEWAY_MAC:
print "\033[31m[!]WARNING: GATEWAY IMPERSONTATION DETECTED.

with packet[ARP].op==1 and it still does not work

**Comment by collinsullivanhub** [comment]
![screenshot from 2017-08-28 20-01-17](https://user-images.githubusercontent.com/14156390/29798914-15f7f324-8c2e-11e7-9c3b-7b57998a847c.png)

**Comment by collinsullivanhub** [comment]
I'll link pcap as well

**Comment by gpotter2** [comment]
@collinsullivanhub I'll be waiting for it :)

**Comment by collinsullivanhub** [comment]
![screenshot from 2017-08-28 21-07-08](https://user-images.githubusercontent.com/14156390/29799977-71fa80ea-8c35-11e7-93ad-8a2ca10ba35b.png)

**Comment by collinsullivanhub** [comment]
https://github.com/collinsullivanhub/Toucan/blob/master/example.pcap

**Comment by collinsullivanhub** [comment]
In the screenshot (about 70% of the way down the picture), you can see that it picks up the gratuitous response saying 192.168.0.1 (Default Gateway) is at (5c:93:a2:b8:65:d9), which is the attackers layer 2 address.

**So, the good thing is that it picked up the poison response, so that is settled. But why did it not activate the**

_if packet[ARP].op == 2 and packet[ARP].psrc == GATEWAY_IP and packet[Ether].src !=GATEWAY_MAC:
print "\033[31m[!]WARNING: GATEWAY IMPERSONTATION DETECTED._

**condition?**

**Comment by gpotter2** [comment]
Well, if it picked up the poison response, it means that:
`if packet[ARP].op == 2:` (from your code https://pastebin.com/fM4gLd9H)
was triggered.

This means that `and packet[ARP].psrc == GATEWAY_IP and packet[Ether].src !=GATEWAY_MAC:`
is not working.

==> your code is broken.

**Comment by collinsullivanhub** [comment]
NOOOOO!!!! lol

Thank you for your help. Glad it is not a scapy error. Sorry about all that. What is wrong about the conditional statement though? Is is because the other condition gets triggered first?

**Comment by gpotter2** [comment]
Have you checked the content of GATEWAY_MAC and GATEWAY_IP ?
Those two must be wrong i guess

**Comment by collinsullivanhub** [comment]
I did a print GATEWAY_IP and print GATEWAY_MAC in that same function and they print the values they are supposed to. So now I am majorly confused

**Comment by gpotter2** [comment]
You should check that your MITM packets are correctly formed, may also check in your tests `packet[ARP].src` like:
```
if packet[ARP].op == 2 and packet[ARP].psrc == GATEWAY_IP and (packet[Ether].src != GATEWAY_MAC or packet[ARP].src != GATEWAY_MAC):
```

Good luck with that !
PS: please close this issue :)

**Comment by collinsullivanhub** [comment]
thank you
