### ISSUE TITLE
Calculate TCP packet loss rate

### ISSUE THREAD

**Issue by nimafam** [secdev/scapy#788]
I'm trying to calculate and qualify video QoE [Quality of Experience] from youtube. I have a student project and I should calculate MDI [Media Delivery Index], I calculated DF [Delay Factor] by sniff packets and according to RFC 4445. Now I need to calculate MLR too, but there is a problem I used a sequence number of TCP packets to get the number of excepted packages _sent from youtube_ and number of received packets that I stored them in a list.

> MLR = (excepted_packets - receivred_packets)/ interval time

So the problem is the sequence numbers do not increase one by one and there is a big gap between them packets then MRL became a big number.

I will pleasure if you help to know "How to calculate TCP packet loss rate?"

**Comment by nimafam** [comment]
Oh and the packet layers are (Eth > IP > TCP > RAW)

**Comment by p-l-** [comment]
This is not really a Scapy question (more a network question), unless you can explain exactly what you want to do in Scapy (in that case, please reopen).

**Comment by nimafam** [comment]
Hi,
I know that is not exactly Scapy question. I want to know how can I calculate TCP packet loss with Scapy?
