### ISSUE TITLE
How to calculate TCP packet loss with scapy? 

### ISSUE THREAD

**Issue by nimafam** [secdev/scapy#790]
Hi,
I'm trying to get some measurement from packets that sniffed by Scapy.

I write my own function to analyze received packets and one of the measures that I want is Packet loss ratio. For packet loss ratio, I need Number of excerpted packets[that sent from server] and Number of received packets [that received in client]. 

Actually, I should sniff packets from Youtube to analyze video quality, so packets sent from Youtube and I received them.

Are there any options that I calculate packets loss ratio with Scapy?

packets loss ratio = (excepted_packets - received_packets)/interval time

**Comment by gpotter2** [comment]
Duplicated (by you):
- [python - TCP packets loss ratio](https://stackoverflow.com/questions/45952554/tcp-packets-loss-ratio)
- [networking - How to calculate packet loss rate with scapy?](https://stackoverflow.com/questions/45905590/how-to-calculate-packet-loss-rate-with-scapy)
- [Scapy issue 788](https://github.com/secdev/scapy/issues/788)

Well as you said, your packet loss ratio requires `excepted_packets`.
If you were sending ICMPs, you would know how many ping requests you would have send, so how many requests you were expecting for.

But on youtube, how are you supposed to know how many packets are expected ?!  It depends on how many FPS you have, or the quality of your connection/video...

It's neally impossible to calculate a such rate, and no magic scapy function will solve a such problem.
