### ISSUE TITLE
No exception when 'tcpreplay' is not available on the target host

### ISSUE THREAD

**Issue by roysror** [secdev/scapy#791]
Not getting any error message in case that 'tcpreplay' is not installed on the target host, while running 'sendpfast'.

**Comment by guedou** [comment]
I can't reproduce the issue. Here is what I got:
```
>>> sendpfast(rdpcap("test.pcap"))
ERROR: while trying to exec [tcpreplay]: [Errno 2] No such file or directory
```
Can you provide us more details about the OS, and the Scapy version you are using ?

**Comment by roysror** [comment]
LSB_VERSION=base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Red Hat Enterprise Linux Server release 6.5 (Santiago)

[root@dev-r-vrt-242-008 ~]# which tcpreplay
/usr/bin/which: no tcpreplay in (/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin)

>>> import scapy.all
>>> print (scapy.all.VERSION)
2.3.3
>>> packet = scapy.all.Ether(src='aa:aa:aa:aa:aa:aa', dst='bb:bb:bb:bb:bb:bb')
>>> packet = packet/scapy.all.IP(src='1.1.1.1',dst='2.2.2.2')
>>> sendp(packet, iface='eth1')
>>> scapy.all.sendp(packet, iface='eth1')
.
Sent 1 packets.
>>> scapy.all.sendpfast(packet, iface='eth1')
>>>

Thanks,
Roy Sror

**Comment by guedou** [comment]
You need to load Scapy with `from scapy.all import *`.

**Comment by roysror** [comment]
No error message, even with 'from scapy.all import *'

Thanks,
Roy Sror

**Comment by guedou** [comment]
Here is what I did to try to reproduce the issue. Can you use Scapy from github and try again ?
```
$ sudo python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import *
>>> sendpfast(rdpcap("test.pcap"))
>>> 
```

**Comment by roysror** [comment]
Do u have 'tcpreplay' on this host?
If not- you are also not getting any error message or exception

Thanks,
Roy Sror

**Comment by guedou** [comment]
I will try to investigate that today.

**Comment by guedou** [comment]
`git bisect` gives that commit 4d31afe7796aa20d0fdc28a5873882ff20059074 introduces this regression.

**Comment by an15m** [comment]
I encountered the same problem today. 
I use scapy in scripts. 
```
#!/usr/bin/env python
from scapy.all import *

if __name__  == '__main__':
    p = Ether(src='00:00:00:00:00:01', dst='00:00:00:00:00:03', type=2054) / ARP(hwdst='00:00:00:00:00:03', ptype=2048, hwtype=1, psrc='10.0.0.1', hwlen=6, plen=4, pdst='10.0.0.3', hwsrc='00:00:00:00:00:01', op=1)
    sendpfast(p, iface='eth0')
```
After the code was run, nothing happened. At first I thought there was a problem with this function, but then I discovered it because I didn't install tcpreplay.
I think there should be hints here.

**Comment by gpotter2** [comment]
`sendpfast` is extremely effective when sending big packet lists multiple times, but not worth it for a single packet.

However if nothing is printed, you are right, it is something we should improve
