### ISSUE TITLE
python 3.6 use scapy error

### ISSUE THREAD

**Issue by yywf** [secdev/scapy#799]
env: python3.6 mac os.
I was install scapy fallow as:
1. git clone https://github.com/secdev/scapy.git
2. cd scapy
3. python setup.py build && python setup.py install

but, when I exec scapy, it was error, please help me.
<img width="928" alt="2017-09-03 22 09 59" src="https://user-images.githubusercontent.com/4133268/30003814-5dbf9ed8-90f6-11e7-94d9-1b7f3c5448b2.png">

**Comment by p-l-** [comment]
Scapy Python 3 support is ongoing (and tracked on #657).
