### ISSUE TITLE
Packet Loss

### ISSUE THREAD

**Issue by codingbond** [secdev/scapy#801]
Hey guys, i find scapy very interesting and great piece of work but  i have few doubt about scapy
Is scapy support python nogil?
Can scapy handle 2Gbps traffic with octa-core cpu server?
What about packet drop stats, there is no description in documentation?

**Comment by p-l-** [comment]
Scapy won't help you (at least, for now, but I don't know of any concrete plans to improve significantly the performances) handle 2Gbps traffic. There are some tricks to make Scapy faster, depending on the situations, but I think there is no way you can get anywhere close to those figures.

**Comment by py2010** [comment]
#706
