### ISSUE TITLE
Syntax error while installing 

### ISSUE THREAD

**Issue by akhila76** [secdev/scapy#803]
On running "sudo python3  setup.py install", I see the following errors:

.
.
.
byte-compiling /usr/local/lib/python3.5/dist-packages/scapy/automaton.py to automaton.cpython-35.pyc
  File "/usr/local/lib/python3.5/dist-packages/scapy/automaton.py", line 425
    v.sort(lambda (t1,f1),(t2,f2): cmp(t1,t2))
                  ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.5/dist-packages/scapy/sendrecv.py to sendrecv.cpython-35.pyc 
.....
byte-compiling /usr/local/lib/python3.5/dist-packages/scapy/arch/bpf/core.py to core.cpython-35.pyc
  File "/usr/local/lib/python3.5/dist-packages/scapy/arch/bpf/core.py", line 213
    interfaces.sort(lambda (ifname_left, ifid_left),
                           ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python3.5/dist-packages/scapy/arch/bpf/consts.py to consts.cpython-35.pyc
.
.
.

However this issue is not seen on using python2

**Comment by p-l-** [comment]
Support for Python 3 is still under development (See #657).
