### ISSUE TITLE
p0f  file missing, p0f returns error.

### ISSUE THREAD

**Issue by 1black1** [secdev/scapy#81]
Hello,

I have yet to be able to achieve any results from the p0f functionality of scapy. 

For starters, I installed scapy with `sudo apt-get install scapy`.

Scapy is version 2.2.0, and p0f is version 2.0.8, which to my knowledge should be compatible.

Upon installation, I first attempted to use the functionality in a python script, however now I am using the interactive scapy terminal, just for quicker results testing.

My procedure goes as follows:

`sudo scapy`

which returns 

```
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
WARNING: No route found for IPv6 destination :: (no default route?)
Welcome to Scapy (2.2.0)
>>> 
```

followed by:
`load_module("p0f")`

which executes fine, then:

`>>> p = sniff(iface="wlan0", count=5, filter="tcp")`

functions properly, checked by running "p" which shows :

```
>>> p
<Sniffed: TCP:5 UDP:0 ICMP:0 Other:0>

```

so from there, is where i get an error:

```
>>> p0f(p[1])
WARNING: Can't open base /etc/p0f/p0fo.fp
WARNING: p0f base empty.
[]

```

Upon inspection of the /etc/p0f/ directory, i have 
p0f.fp, p0fa.fp, and p0fr.fp

I have tried reinstalling scapy, to the same results, I have also tried installing scapy and installing p0f independently and still, i lack the p0fo.fp file that it is requesting. Is this an error of mine, or is the file genuinely missing? Possibly, the p0f.fp file is supposed to be the p0f.fp but due to an update or some such reason it wasnt modified properly? Hope to hearing how i can fix the issue.

Thanks for your time!

**Comment by p-l-** [comment]
First, `p0f()` does not return an error here, but an empty list (it displays two warnings). The TCP packet you want to analyze is probably neither a SYN, a SYN+ACK, an RST or an RST+ACK packet, and p0fo.fp would be needed. However, this file does not exist on your system, which is a problem related to p0f (and more precisely, to the files included in the p0f package of your distribution).

You can either analyze other packets (p0f works better with SYN packets) or install a version of `p0fo.fp` (but according to the manual, "NOTE: The p0fo.fp database is  very sparsely populated at the moment.").

**Comment by 1black1** [comment]
replied in email, removing issue as not relevant directly to scapy.
