### ISSUE TITLE
Bug: Hexdump fails to display binary data

### ISSUE THREAD

**Issue by emj** [secdev/scapy#813]
I run the latest dev, and with LANG=sv_SE.UTF-8, I have problems using  hexdump('\x81') on scapy3, hexdump(u'\x81') on scapy.

With run_scapy3 

```
>>> hexdump('\x81')
Traceback (most recent call last):
  File "/usr/lib/python3.4/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "scapy/utils.py", line 91, in hexdump
    s += "%02X" % ord(x[i+j])
TypeError: ord() expected string of length 1, but int found

```

With run_scapy

```
>>> hexdump(u'\x81')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "scapy/utils.py", line 84, in hexdump
    x = raw(x)
  File "scapy/compat.py", line 70, in raw
    return str(x)
UnicodeEncodeError: 'ascii' codec can't encode character u'\x81' in position 0: ordinal not in range(128)

```

**Comment by p-l-** [comment]
The purpose of `hexdump()` is to display binary data, so you should use `hexdump(b'\x81')`. The `ord()` call should be replaced by `orb()`, I think @gpotter2 has a PR for that.

**Comment by gpotter2** [comment]
This was fixed in https://github.com/secdev/scapy/pull/738.
Current python 3 support on this repo is in a highly experimental (exists only since a few days), there are many bugs left. You should use python 2.7 in the mean time

**Comment by gpotter2** [comment]
Fixed in latest dev version.
Can be closed.
