### ISSUE TITLE
Unable to parse tcp dns request response

### ISSUE THREAD

**Issue by codingbond** [secdev/scapy#819]
DNS protocol works on udp port 53 as well as tcp port 53.
I am able to parse dns packet of udp port 53 using scapy but unable to parse packets of tcp port 53. Wireshark extract every fields from udp port 53 as well as tcp port 53 packet perfectly.
[Screenshot of wireshark](https://i.stack.imgur.com/EuoSq.png)

Sample Data:-
```
>>> tcp = sample_packet[TCP]
>>> tcp
<TCP  sport=16883 dport=domain seq=1770261319 ack=2968858173 dataofs=8L reserved=0L flags=PA window=65535 chksum=0x6b0d urgptr=0 options=[('NOP', None), ('NOP', None), ('Timestamp', (16314985, 1662519068))] |<Raw  load='\x00(2\xac\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x06rtb-tm\x0beveresttech\x03net\x00\x00\x01\x00\x01' |>>
>>> 

```
Is scapy able to parse these type of packets? If no then any idea how to parse these packets?
Thanx in advance.

**Comment by p-l-** [comment]
Which version of Scapy are you using?

**Comment by codingbond** [comment]
hi, i m using scapy version 2.3.1

**Comment by p-l-** [comment]
OK, please upgrade to the latest version, it should work. Reopen this issue if that's not the case!
