### ISSUE TITLE
Timestamps lacking float precision on sniffed packets

### ISSUE THREAD

**Issue by Kash-A** [secdev/scapy#826]
While capturing packets on Windows 7 x64, timestamps don't seem to have float precision. the code is given below.
`from scapy.all import sniff`
`pkts = sniff(count=10)`
`pkts[0].time`
-> for higher precision output
`print('%.6f'%pkts[0].time)`
**output**
1506009934
1506009934.000000
scapy version is 2.3.3. FYI if working with a pcap file having timestamps in floating points already. Then scapy shows the correct values. I am not sure whether it drops the floating point values while sniffing or when writing the pcap file.

**Comment by Kash-A** [comment]
I installed the new fixed version and now I am into another trouble. I can't get the scapy readable although pyreadline is also installed. see the error below.

C:\Users\ahm2sgm\Downloads\scapy-master>scapy
WARNING: Crypto-related methods disabled for IPsec, Dot11 and TLS layers (needs python-cryptography v1.7+).

> Traceback (most recent call last):
>   File "C:\Python27\lib\logging\__init__.py", line 861, in emit
>     msg = self.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 734, in format
>     return fmt.format(record)
>   File "C:\Python27\lib\logging\__init__.py", line 465, in format
>     record.message = record.getMessage()
>   File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Logged from file error.py, line 76
> WARNING: No route found for IPv6 destination :: (no default route?)
> INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
> INFO: Could not import python-cryptography.Computations for the "authenticator" field (RADIUS packets) and"Message-Authenticator" attribute value field are disabled.
> INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
> WARNING: IPython not available. Using standard Python shell instead. AutoCompletion, History are disabled.
> [32m[1m                                      [0m[34m[1m[0m
> [32m[1m                     aSPY//YASa       [0m[34m[1m[0m
> [32m[1m             apyyyyCY//////////YCa    [0m[34m[1m   |[0m
> [32m[1m            sY//////YSpcs  scpCY//Pp  [0m[34m[1m   | Welcome to Scapy[0m
> [32m[1m ayp ayyyyyyySCP//Pp           syY//C [0m[34m[1m   | Version 134336054[0m
> [32m[1m AYAsAYYYYYYYY///Ps              cY//S[0m[34m[1m   |[0m
> [32m[1m         pCCCCY//p          cSSps y//Y[0m[34m[1m   | https://github.com/secdev/scapy[0m
> [32m[1m         SPPPP///a          pP///AC//Y[0m[34m[1m   |[0m
> [32m[1m              A//A            cyP////C[0m[34m[1m   | Have fun![0m
> [32m[1m              p///Ac            sC///a[0m[34m[1m   |[0m
> [32m[1m              P////YCpc           A//A[0m[34m[1m   | Craft packets like I craft my beer.[0m
> [32m[1m       scccccp///pSP///p          p//Y[0m[34m[1m   |               -- Jean De Clerck[0m
> [32m[1m      sY/////////y  caa           S//P[0m[34m[1m   |[0m
> [32m[1m       cayCyayP//Ya              pY/Ya[0m
> [32m[1m        sY/PsY////YCc          aC//Yp [0m
> [32m[1m         sc  sccaCY//PCypaapyCP//YSs  [0m
> [32m[1m                  spCPY//////YPSps    [0m
> [32m[1m                       ccaacs         [0m
> [32m[1m                                      [0m
> [34m[1m>>> [0m

**Comment by gpotter2** [comment]
In the latest version we have removed pyreadline. You can disable it and switch to IPython :)(the shell will be the same)

**Comment by p-l-** [comment]
@Kash-A: open another issue since this is another problem! @gpotter2: we should have a clean output when iPython is not available anyway...

**Comment by Kash-A** [comment]
@p-l- : I have opened new thread.
@gpotter2  I have tried it without pyreadline before posting the error. It behaves the same way.

**Comment by jc5121** [comment]
Just edit the source code packet.py：

        if sys.platform == 'win32':
            self.time = time.clock()
        else:
            self.time = time.time()
