### ISSUE TITLE
Problem with creating Modbus(TCP) packet.

### ISSUE THREAD

**Issue by MazoSergey** [secdev/scapy#828]
Hello guys!
Please need help... I am a beginner in python and low level networking:)
I am trying to create Modbus request to my PLC simulator and do not succeed. 
Here is my code:

```
#!/usr/bin/python

from scapy.all import *
#from modlib import *
import socket
load_contrib('modbus')

print ('---------------------')

#__Initializtion TCP connection
sock = socket.socket()
sock.connect(("192.168.1.22", 502))
s = StreamSocket(sock, basecls=ModbusADURequest)

#__Sending Modbus request to read Coil Register
ans, unans = s.sr1(ModbusADURequest(unitId=1))/ModbusPDU01ReadCoilsRequest(startAddr=0x0001, quantity=0x0001)
ans.show()

```
But for sure I am doing something wrong, here what I get in Wireshark on PLC Simulator side:

![capture](https://user-images.githubusercontent.com/32014969/30740580-3e1afb4c-9f9a-11e7-9c80-a548d9073b34.PNG)

<img width="370" alt="2017-09-22 13 31 18" src="https://user-images.githubusercontent.com/32014969/30740612-62a9c5f6-9f9a-11e7-964d-f9eb02efca9a.png">

I hope I am writing in right place, sorry if not. Thank you for any kind of help!
Sergey

**Comment by p-l-** [comment]
You have a misplaced parenthesis in the code. Maybe it's a copy & paste error?

You have:
```Python
ans, unans = s.sr1(ModbusADURequest(unitId=1))/ModbusPDU01ReadCoilsRequest(startAddr=0x0001, quantity=0x0001)
```

You should have (the parenthesis before `/ModbusPDU01ReadCoilsRequest` has to be moved to the end of the line):
```Python
ans, unans = s.sr1(ModbusADURequest(unitId=1)/ModbusPDU01ReadCoilsRequest(startAddr=0x0001, quantity=0x0001))
```

**Comment by MazoSergey** [comment]
Hello Pierre!
Thank you very much for your support!
I am using 2.3.3 Scapy.
I fixed a code according to your help and now it is working :) But i still do not get a right answer or i do not understand how to unpack the packet i received.
For example I am trying to read CoilRegister 0x0000 and i put there "True"

In Wireshark i could see:
![capture](https://user-images.githubusercontent.com/32014969/30746432-76244c56-9fb2-11e7-9c75-d96e6623d765.PNG)

But in the "ans" i see ("0000"):
<img width="1433" alt="2017-09-22 16 25 03" src="https://user-images.githubusercontent.com/32014969/30746536-b6453386-9fb2-11e7-858d-dcafba8415a1.png">

Also i changed the function "sr1" to "sr" because I am getting "ValueError: need more than 1 value to unpack". So my code for now is looking like:
```
#!/usr/bin/python

from scapy.all import *
#from modlib import *
import socket
load_contrib('modbus')

print ('---------------------')

#__Initializtion TCP connection
sock = socket.socket()
sock.connect(("192.168.1.22", 502))
s = StreamSocket(sock, basecls=ModbusADURequest)

#__Sending Modbus request to read Coil Register
ans, unans = s.sr(ModbusADURequest(unitId=1)/ModbusPDU01ReadCoilsRequest(startAddr=0x0000, quantity=0x0001)) 
ans.show()
```

Thank you again!!!

**Comment by p-l-** [comment]
Glad it helped. The `sr1` behaviour might be a bug, you should probably create another option

The `0000` is the request / response number.
