### ISSUE TITLE
How to directly access Dot11Elt layers by ID instead of iterating over layers

### ISSUE THREAD

**Issue by MisterBianco** [secdev/scapy#832]
I was looking to efficiently extract some info from the dot11elt layers with ID's 3 and 61 and couldn't find a way to directly access these layers...

if it is even possible.

**Comment by p-l-** [comment]
That's not currently possible, you're stuck with writing a loop. But since this is a very nice-to-have syntax, I've just written a proposal API change. I'll submit a pull request.

**Comment by p-l-** [comment]
@MisterBianco with the proposed patch, you can use `pkt[Dot11Elt::{"ID": 3}]` or `pkt.getlayer(Dot11Elt, ID=61)`. What do you think?

**Comment by MisterBianco** [comment]
I like either way but I appreciate how quick that was. I love the library
and this would make it even better :)
