### ISSUE TITLE
TypeError: not all arguments converted during string formatting. Logged from file error.py, line 76

### ISSUE THREAD

**Issue by Kash-A** [secdev/scapy#835]
I installed the new fixed version and now I am into another trouble. I can't get the scapy readable. see the error below.

C:\Users\ahm2sgm\Downloads\scapy-master>scapy
WARNING: Crypto-related methods disabled for IPsec, Dot11 and TLS layers (needs python-cryptography v1.7+).
Traceback (most recent call last):
File "C:\Python27\lib\logging_init_.py", line 861, in emit
msg = self.format(record)
File "C:\Python27\lib\logging_init_.py", line 734, in format
return fmt.format(record)
File "C:\Python27\lib\logging_init_.py", line 465, in format
record.message = record.getMessage()
File "C:\Python27\lib\logging_init_.py", line 329, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file error.py, line 76
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Could not import python-cryptography.Computations for the "authenticator" field (RADIUS packets) and"Message-Authenticator" attribute value field are disabled.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.
WARNING: IPython not available. Using standard Python shell instead. AutoCompletion, History are disabled.
�[32m�[1m �[0m�[34m�[1m�[0m
�[32m�[1m aSPY//YASa �[0m�[34m�[1m�[0m
�[32m�[1m apyyyyCY//////////YCa �[0m�[34m�[1m |�[0m
�[32m�[1m sY//////YSpcs scpCY//Pp �[0m�[34m�[1m | Welcome to Scapy�[0m
�[32m�[1m ayp ayyyyyyySCP//Pp syY//C �[0m�[34m�[1m | Version 1343360�[0m
�[32m�[1m AYAsAYYYYYYYY///Ps cY//S�[0m�[34m�[1m |�[0m
�[32m�[1m pCCCCY//p cSSps y//Y�[0m�[34m�[1m | https://github.com/secdev/scapy�[0m
�[32m�[1m SPPPP///a pP///AC//Y�[0m�[34m�[1m |�[0m
�[32m�[1m A//A cyP////C�[0m�[34m�[1m | Have fun!�[0m
�[32m�[1m p///Ac sC///a�[0m�[34m�[1m |�[0m
�[32m�[1m P////YCpc A//A�[0m�[34m�[1m | Craft packets like I craft my beer.�[0m
�[32m�[1m scccccp///pSP///p p//Y�[0m�[34m�[1m | -- Jean De Clerck�[0m
�[32m�[1m sY/////////y caa S//P�[0m�[34m�[1m |�[0m
�[32m�[1m cayCyayP//Ya pY/Ya�[0m
�[32m�[1m sY/PsY////YCc aC//Yp �[0m
�[32m�[1m sc sccaCY//PCypaapyCP//YSs �[0m
�[32m�[1m spCPY//////YPSps �[0m
�[32m�[1m ccaacs �[0m
�[32m�[1m �[0m
�[34m�[1m>>> �[0m

**Comment by p-l-** [comment]
I cannot reproduce.

@gpotter2 do you have a Windows machine **without** iPython to see if you get the same issue?

@Kash-A can you install iPython and tell us if that changes something?

**Comment by Kash-A** [comment]
The problem is solved for floating point measurement but error is persistent. Output is:
C:\Users\ahm2sgm\Downloads\scapy-master>scapy
WARNING: Crypto-related methods disabled for IPsec, Dot11 and TLS layers (needs python-cryptography v1.7+).
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 861, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
**TypeError: not all arguments converted during string formatting
Logged from file error.py, line 76**
WARNING: No route found for IPv6 destination :: (no default route?)
INFO: Can't import python-cryptography v1.7+. Disabled WEP decryption/encryption.
INFO: Could not import python-cryptography.Computations for the "authenticator" field (RADIUS packets) and"Message-Authenticator" attribute value field are disabled.
INFO: Can't import python-cryptography v1.7+. Disabled IPsec encryption/authentication.

                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version 134336054
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | Craft packets like I craft my beer.
       scccccp///pSP///p          p//Y   |               -- Jean De Clerck
      sY/////////y  caa           S//P   |
       cayCyayP//Ya              pY/Ya
        sY/PsY////YCc          aC//Yp
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs
                                       using IPython 5.5.0
>>> sniff()
<Sniffed: TCP:4 UDP:17 ICMP:0 Other:1>
>>> a = sniff()
>>> a
<Sniffed: TCP:1 UDP:26 ICMP:0 Other:2>
>>> a[1].time
1506352339.787295
>>>

**Comment by gpotter2** [comment]
Hmm,
I cannot reproduce :/
Could you
- try with https://github.com/secdev/scapy/pull/824 (it has a small error.py fix)
- give your exact python version `sys.version`

**Comment by Kash-A** [comment]
Exact version.
U:\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by gpotter2** [comment]
@Kash-A Hi,
Could you retry using this branch:
https://github.com/gpotter2/scapy/tree/fix-warning-params
This *should* fix the bug :/

**Comment by Kash-A** [comment]
@gpotter2 Unfortunately its still not working. With the branch you mentioned I got the following result. Before installation, I deleted all the traces of scapy from my computer and then reinstalled from the said branch.

C:\Users\ahm2sgm\Downloads\scapy-fix-warning-params>scapy
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 861, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
**TypeError: not all arguments converted during string formatting
Logged from file error.py, line 76**
WARNING: No route found for IPv6 destination :: (no default route?)

```
                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version 93d915cff
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | Craft me if you can.
       scccccp///pSP///p          p//Y   |                   -- IPv6 layer
      sY/////////y  caa           S//P   |
       cayCyayP//Ya              pY/Ya
        sY/PsY////YCc          aC//Yp
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs
                                       using IPython 5.5.0
```
or may be I am doing some mistake which I have no idea about.

**Comment by gpotter2** [comment]
Wait you need to call scapy by running `run_scapy.bat`, not by calling `scapy`

**Comment by gpotter2** [comment]
I've updated https://github.com/gpotter2/scapy/tree/fix-warning-params with debug codes, could you give us the output of scapy when you are starting it ? There will be debug logs with it

**Comment by Kash-A** [comment]
C:\Users\ahm2sgm\Downloads\scapy-fix-warning-params>scapy
WinPcap is now deprecated (not maintened). Please use Npcap instead
(True,)
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 861, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 734, in format
    return fmt.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
**TypeError: not all arguments converted during string formatting
Logged from file error.py, line 78**
No route found for IPv6 destination %s (no default route?)
('::',)
WARNING: No route found for IPv6 destination :: (no default route?)

```
                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version 67b0f217c
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | To craft a packet, you have to be a
       scccccp///pSP///p          p//Y   | packet, and learn how to swim in
      sY/////////y  caa           S//P   | the wires and in the waves.
       cayCyayP//Ya              pY/Ya   |        -- Jean-Claude Van Damme
        sY/PsY////YCc          aC//Yp    |
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs
                                       using IPython 5.5.0
```

**Comment by Kash-A** [comment]
On an unrelated note but an important question I want to ask about scapy. I am trying to replay some pcap files with my own crafted version. Up until now the accuracy I have been able to measure for replaying is not very much accurate. Average jitter is above 15 ms for different scenarios. I am trying to do it in windows and will try on linux as well. But can you tell me about the accuracy scapy offers for replaying the timestamps? I couldn't find any help anywhere.

**Comment by gpotter2** [comment]
OK this is indeed a scapy-related bug.
Could you retry using https://github.com/gpotter2/scapy/tree/fix-warning-params
I've updated the logs.

**Comment by Kash-A** [comment]
Finally you got rid of the bug :)

C:\Users\ahm2sgm\Downloads\scapy-fix-warning-params>scapy
WinPcap is now deprecated (not maintened). Please use Npcap instead
()
WARNING: WinPcap is now deprecated (not maintened). Please use Npcap instead
No route found for IPv6 destination %s (no default route?)
('::',)
WARNING: No route found for IPv6 destination :: (no default route?)

```
                     aSPY//YASa
             apyyyyCY//////////YCa       |
            sY//////YSpcs  scpCY//Pp     | Welcome to Scapy
 ayp ayyyyyyySCP//Pp           syY//C    | Version e7042f67a
 AYAsAYYYYYYYY///Ps              cY//S   |
         pCCCCY//p          cSSps y//Y   | https://github.com/secdev/scapy
         SPPPP///a          pP///AC//Y   |
              A//A            cyP////C   | Have fun!
              p///Ac            sC///a   |
              P////YCpc           A//A   | Craft packets like I craft my beer.
       scccccp///pSP///p          p//Y   |               -- Jean De Clerck
      sY/////////y  caa           S//P   |
       cayCyayP//Ya              pY/Ya
        sY/PsY////YCc          aC//Yp
         sc  sccaCY//PCypaapyCP//YSs
                  spCPY//////YPSps
                       ccaacs
                                       using IPython 5.5.0
```
