### ISSUE TITLE
Sending and receiving packets using multiple interfaces.

### ISSUE THREAD

**Issue by Khan-imran** [secdev/scapy#870]
I am trying to make a script to trace all nodes on a path between two hosts, each having three interfaces. I have simulated the intermediate network using linux virtual machines (Ubuntu) as routers with static routing set up to create custom networks. its a 3x3 network, with 9 paths available. After tracing the each nodes on each path, i will use this info for further work, basically evaluating the validity of a formula. 

My question is, is it possible to use scapy to send and receive packets selecting multiple interfaces on a host by giving source address of each of the 3 interfaces? 

Using `sr1(IP(dst="target")/icmp())` seems to work fine, sent packet has src address of the interface set as gw in _/etc/network/interfaces_. I get a reply too. 
Doing same with 'sr1(IP(src=" GW IP" , dst="target ")/ICMP()) also works since src is the gw.

But when I try 'sr1(IP(src="IP of any of the other 2 interfaces", dst="target")/ICMP())', i see packet sent in scapy , but the reply is not received. Using wireshark I see no packets being sent out from the interface.

The gateway is the default gateway that I have setup in _/etc/network/interfaces_. Actually I have my static routing rules and static ips of the interfaces setup on each host in _/etc/network/interfaces_. The NetworkManager.services is stopped and disabled in order not to conflict with the static IP in _/etc/network/interfaces_. Since I couldnt define multiple gateways in the script, I have added 3 custom routing tables in _/etc/iproute2/rt_tables_ with rules for them set up in _/etc/network/interfaces_ as my static routes.

I guess its my static route setup that is the issue here. But still I want to confirm first whether it is possible to send receive on multiple interfaces with scapy. i will stick to scapy if Yes, otherwise I will shift to socket programming of Python or C.

**Comment by p-l-** [comment]
When using layer 3 commands (which includes `sr1()`), Scapy uses its routing table to determine the output interface to use, based on the **destincation** address (like the "regular" IP stacks); the source address has no influence on that decision. When using layer 2 commands (the equivalent here being `srp1()`), Scapy uses the default interface (from `conf.iface`) or the interface you provide (e.g., `srp1([...], iface="eth0")`).

You have (at least) four options:
* Switch to layer 2 commands (you have to provide the `Ether()` layer).
* Use `L3RawSocket(iface="eth0").sr1()` method.
* Add a Scapy route for the host you want to reach (see `conf.route.add()`), that you can remove when the packet has been sent.
* Override (by patching Scapy's source or using monkey patching) IP.route() to select the appropriate route based on the source address.

**Comment by Khan-imran** [comment]
Thanks. I will go for the first option before trying the rest, that is using layer 2 commands providing the interfaces that I want the packet to be sent from.  Its seems simpler to me. I can test my linux routing table on host as well. Can do it tomorrow only, so I will post the update then. Thanks again. Scapy is awsome tool, should be used in the universities as often as they use wireshark.

**Comment by Khan-imran** [comment]
I fixed my static routes, i can select any src address from my multihomed client( using c socket programming). 

Tried the first method using:

srp1(Ether() / IP( src="IP of int with default gw" , dst="target IP") / ICMP() , iface=' interface name') 
it works, packet is sent and received properly.
while
srp1 (Ether() / IP(src="IP of any of the other 2 interfaces", dst="target") / ICMP(), iface='corresponding interface')

it doesnt work, in wireshark packet is shown as sent, at the gateway interface of the router this interface is connected to (same subnet) I also see the packet arrive, but  not further than that.

trying without iface
srp1 (Ether() / IP(src="IP of any of the other 2 interfaces", dst="target") / ICMP() )

I see packet sent in wireshark, but I dont see any arriving at the gateway interface of the router this interface is connected to (same subnet).


am I making some mistake here in the command? 

since scapy env has its own routing tables... Would it work if i write a code in python (not in scapy env), and run it with scapy API imported in it? as that would be out of the scapy env.

**Comment by rafajot** [comment]
Hi p-l-

This problem is also interesting to me.
Please correct me if I'm wrong but to my understanding the methods you are suggesting allow to enforce outgoing interface while the goal is to send packet using one interface and listen for the response on a different one. 

I tried to use some of your suggestions but unfortunately with no success.

Maybe I'm wrong but by lets say I use Ether layer and overwrite dst using different MAC address. So this way I can enforce non-default gateway but I still will be sending and receiving using the same interface.

Could you please post a simple example of such use case (for example to send packet using eth0, listen for the response on eth1)?

Regards,
Rafał

**Comment by Khan-imran** [comment]
Update: In my case it wasnt possible to use scapy in my code for sending and receiving on multiple interfaces. First two options mentioned by p-l- didnt work, they also didnt work outside the scapy interactive env, i-e by importing the scapy libraries into my python code. My requirement is also to use scpay in a custom tool, that is outside the scapy env. , so thats why I am thinking about trying the last two options. I am switching back to C socket programming.

**Comment by p-l-** [comment]
@rafajot that's not what I understand from the question, and I don't think you can do that with Scapy.

@Khan-imran maybe you could share exactly what didn't work?

**Comment by rafajot** [comment]
@p-l- 
All right, I'm not sure what was the exact intention. Possibly I focused too much on the title and too little on the problem description.
Do you think it would be possible to include such feature on the wish list?
I have some real use case when it would be really useful, described here: https://github.com/netsniff-ng/netsniff-ng/issues/181
I guess it would be cool to have it in the Swiss army knife ;-), on the other hand I'm aware that possibly only few people may need it.

**Comment by p-l-** [comment]
@rafajot if you come with a clean PR, this functionality could probably land in Scapy.
