### ISSUE TITLE
Question: sniff() return at EOF in offline mode?

### ISSUE THREAD

**Issue by chenxiaoqino** [secdev/scapy#876]
I noticed that `sniff(pffline="xxx.pcap")`  will not return after reading the entire pcap file, unless I specify a `count`, which is unknown before I read the pcap file.

My goal is to scan through all packets in the pcap file (using `prn=`) and continue to execute, i.e. `sniff()` will return after reading the entire pcap file. I wonder if there's a supported way to achieve that?

I did a quick read through the source code of `sniff()` and didn't find an obvious way to do this.

**Comment by gpotter2** [comment]
How about using `scapy.utils.rdpcap` ? It does exactly what you need

**Comment by chenxiaoqino** [comment]
The problem of `rdpcap` is it actually reads the packets into memory, which is unacceptable even when reading a pcap file of only ~300MB. Using `sniff(offline="xx.pcap", store=False)` can scan through the pcap file without actually reading it into memory (in a "streaming" fashion), which is very useful.

**Comment by gpotter2** [comment]
I cannot reproduce your bug :/
```
>>> sniff(offline="test.pcap")
<Sniffed: TCP:2 UDP:46 ICMP:0 Other:0>
>>> sniff(offline="test.pcap", prn=lambda x:x.show(), store=False)
###[ Ethernet ]###
  dst= 01:00:5e:00:00:fc
  src= a4:1f:72:90:23:a3
  type= 0x800
###[ IP ]###
.......
<Sniffed: TCP:0 UDP:0 ICMP:0 Other:0>
>>> 
>>> 
```
[test.pcap.zip](https://github.com/secdev/scapy/files/1383921/test.pcap.zip)

A few questions to try to understand:
- What is the exact command that you are using ?
- What scapy version are you using (if not the latest dev version, please try with https://github.com/secdev/scapy/archive/master.zip)

**Comment by chenxiaoqino** [comment]
Oops, it worked perfectly in the latest version. Sorry for not checking the development tree beforehand.
