### ISSUE TITLE
"Cannot find libdnet.so" python3.5

### ISSUE THREAD

**Issue by tbarabanov** [secdev/scapy#88]
Hello, I faced "Cannot find libdnet.so" with python3.5 (probably it doesn't matter). My env is: lindnet1.11 (tried also 1.12) scappy3.0.0, mac os x 10.10.3 (yosemite).

Code I tried to execute.

from scapy.all import *
sniff(filter="tcp port 110 or tcp port 25 or tcp port 143", prn=callback_func, store=0)

def callback_func(pkt):
    pkt.show()
 

I found that

if WIN:
    SOCKET = c_uint
    _lib = CDLL('dnet')
else:
    SOCKET = c_int
    _lib_name = find_library('dnet') _# doesn't find dnet library_
    if not _lib_name:
        raise OSError("Cannot find libdnet.so") _# and throws an exception_
    _lib = CDLL(_lib_name)

I checked libdnet installation log and didn't find dnet artifact. What I found are these files:

mint$ ls /usr/local/lib/ | grep libdnet
libdnet
libdnet.1
libdnet.1.0.1
libdnet.a
libdnet.la

Here is my question. Is the line _find_library('dnet')_ correct? When I changed it to __lib_name = find_library('libdnet') _the error disappeared.

**Comment by p-l-** [comment]
Scapy uses Python 2, so you need to install libdnet for Python 2. Anyway, you should probably get Scapy from the development tree, since it no longer requires libdnet.

**Comment by Silur** [comment]
python3 is 8 years old, _"just use the deprecated and outdated python2"_ is not an answer for a portability problem :hankey:
