### ISSUE TITLE
'IndexError: list index out of range' trying pkt.show()

### ISSUE THREAD

**Issue by elenabdc** [secdev/scapy#892]
I get this error using Debian 9, python 2.7 and scapy, 2.3.3.dev786. I'm trying to use multithreading, I don't know if this is relevant or not.

Packets are management frames from a WiFi AP. It shows the first layer as follows:

    ###[ RadioTap dummy ]###
      version   = 0
      pad       = 0
      len       = 36
      present   = TSFT+Flags+Rate+Channel+dBm_AntSignal+RX_Flags+Reset+Ext
      tsft      = 2080
      flags     = short+failed
       rate      = 22
      channel_freq= 34927
      channel_flags= b2+Turbo
      dbm_antsignal= 0
    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "./concurrent.py", line 39, in run
        print(p.show())
      File "/usr/local/lib/python3.5/dist-packages/scapy/packet.py", line 869, in show
        reprval = f.i2repr(self,fvalue)
      File "/usr/local/lib/python3.5/dist-packages/scapy/fields.py", line 905, in i2repr
        r += [ self.names[i] ]
    IndexError: list index out of range

I think this is a bug and I really appreciate if someone could fix it. Thank you.

**Comment by gpotter2** [comment]
Hey,
It seems wrong, you're getting a python 3 error whereas you said you were using her python 2,7 :/

Apart from that, please retry with the latest dev version (located on GitHub)

**Comment by elenabdc** [comment]
Sorry, you are right, I'm using scapy-python3. I thought the error was inherit for here, but I was wrong. Sorry for bother.

**Comment by p-l-** [comment]
@elenabdc you can use the latest Scapy version (from this repository) with Python 2.7 and 3.3 - 3.6. If you have any issue with it, please report it here!

**Comment by elenabdc** [comment]
@p-l- I'm currently using Scapy on Python 3.5 and it is working without any problems. Thank you :)
