### ISSUE TITLE
os-fingerprinting via nmap

### ISSUE THREAD

**Issue by Ludisposed** [secdev/scapy#893]
I have an error trying to do os-fingerprinting with scapy

```
from scapy.all import *
nmap_fp(target, [oport=80,] [cport=81,])
```

Is yielding me the following error:

```
Begin emission:
...Finished to send 8 packets.
*......
Received 10 packets, got 1 answers, remaining 7 packets
Traceback (most recent call last):
  File "scapy_.py", line 7, in <module>
    ans = nmap_fp(my_phone_ip_2)
  File "/usr/lib/python2.7/dist-packages/scapy/modules/nmap.py", line 189, in nmap_fp
    sigs = nmap_sig(target, oport, cport)
  File "/usr/lib/python2.7/dist-packages/scapy/modules/nmap.py", line 144, in nmap_sig
    ans += map(lambda x: (x,None), unans)
  File "/usr/lib/python2.7/dist-packages/scapy/plist.py", line 89, in _add_
    return self.__class__(self.res+other.res,
AttributeError: 'list' object has no attribute 'res'
```

After trying to figure out why this would'nt work I read the following in `nmap.py`:

"""Clone of Nmap's first generation OS fingerprinting.
This code works with the first-generation OS detection and
nmap-os-fingerprints, which has been removed from Nmap on November 3,
2007 (https://github.com/nmap/nmap/commit/50c49819), which means it is
outdated.
To get the last published version of this outdated fingerprint
database, you can fetch it from
<https://raw.githubusercontent.com/nmap/nmap/9efe1892/nmap-os-fingerprints>.
"""

Maybe silly question, but does this mean os-detection via `nmap_fp` no longer works with scapy?

**Comment by p-l-** [comment]
Can you upgrade to the current development version of Scapy and see if you still have the bug?

The comment means that you have to use the old Nmap fingerprints with Scapy, at least for now.

**Comment by Ludisposed** [comment]
After pulling the latest version of scapy and install

`git pull --rebase https://github.com/secdev/scapy master`
`python setup.py install`

I have another error

```
Begin emission:
.**Finished to send 8 packets.
******
Received 9 packets, got 8 answers, remaining 0 packets
Traceback (most recent call last):
  File "arp_tester.py", line 6, in <module>
    result = nmap_fp(ip)
  File "/usr/local/lib/python2.7/dist-packages/scapy/modules/nmap.py", line 201, in nmap_fp
    return nmap_search(sigs)
  File "/usr/local/lib/python2.7/dist-packages/scapy/modules/nmap.py", line 182, in nmap_search
    for osval, fprint in nmap_kdb.get_base():
TypeError: 'NoneType' object is not iterable
```

**Comment by Ludisposed** [comment]
Or am I misunderstanding how to correctly call `nmap_fp`

This is how I currently do it.
```
from scapy.all import *
load_module("nmap")

target = '192.168.1.68'
result = nmap_fp(target)
```

**Comment by gpotter2** [comment]
Normal, you need to load the nmap database first.
Look how it's done during the tests:

```
try:
    from urllib.request import urlopen
except ImportError:
    from urllib2 import urlopen

open('nmap-os-fingerprints', 'wb').write(urlopen('https://raw.githubusercontent.com/nmap/nmap/9efe1892/nmap-os-fingerprints').read())
conf.nmap_base = 'nmap-os-fingerprints'
```
You can download the file once and for all, then link in your program the path to it.

Nmap scapy samples: https://github.com/secdev/scapy/blob/master/test/nmap.uts

**Comment by Ludisposed** [comment]
Thank you for the help, did indeed resolved the issue.
