### ISSUE TITLE
Scapy: Sending multiple packets in one request

### ISSUE THREAD

**Issue by Kash-A** [secdev/scapy#897]
I am trying to send multiple packets wrapped in single IP()/TCP() frame. I am able to do this with a code snippet of 
```
req_array = []
    for i in range (10):
                req = Request()
                req_Array.append(req)
    pkt_str = "".join(str(pkt) for pkt in req_Array)
    packet = IP()/TCP()/pkt_str
    sr(packet)
```
The problem I am having is `sr` function returns only first response and not all the responses. Is there any workaround by which I can get req, resp pairs such as in normal cases.
By the way I can see all the requests and responses on wireshark.  ScreenShort can be seen on the link below
https://ibb.co/kiOTWR

**Comment by p-l-** [comment]
If you send one packet, you'll get only one response, unless you specify `multi=True` (see `help(sr)`). Then it depends on the protocol you are using: it seems that whatever you call `Request()`, you can send several layers of it concatenated. But your Scapy code has to know what to do with the response and decode it properly.
