### ISSUE TITLE
PicklingError on Scapy packet using multiprocessing.queue

### ISSUE THREAD

**Issue by elenabdc** [secdev/scapy#904]
I'm using a multiprocessing queue to share memory between a producer (scapy sniff or scapy rdpcap) and a consumer (a process to analyze the packet). I'm trying to enqueue each packet, but I get a PicklingError.

Here the code:

    from scapy.all import *
    from multiprocessing import Queue
    pcap = rdpcap("/home/user/cap.pcap")
    pq = Queue()
    for pkt in pcap:
        pq.put(pkt)

And here the error:
> Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

Although, if using a normal queue, I don't get the error. Is there any option on modifying the scapy code to avoid the error?

Thank you.

Edit:
Looking at [python pickle documentation](https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled) I found that only "functions defined at the top level of a module, built-in functions defined at the top level of a module, classes that are defined at the top level of a module" can be pickle. 

Anyone can give a clue on how to fix this?

**Comment by gpotter2** [comment]
You should retry using latest dev version: https://github.com/secdev/scapy/archive/master.zip
It seems to work for me
```
>>> from scapy.all import *
...:from multiprocessing import Queue
...:pcap = sniff(count=10)
...:pq = Queue()
...:for pkt in pcap:
...:    pq.put(pkt)
...:
>>> pq
<multiprocessing.queues.Queue at 0x9198fd0>
```

**Comment by elenabdc** [comment]
That's it, using latest dev version it works. Using latest version on pip (v 2.3.3) it doesn't. Thank you @gpotter2
