### ISSUE TITLE
Not working on win10

### ISSUE THREAD

**Issue by rgom** [secdev/scapy#918]
Interfaces list is empty on win10.
Probably since commit from Oct, 23 - duplicated names in PS query.
Just noticed it, left the comment in the commit, so sorry for very brief bug report.

Robert

**Comment by gpotter2** [comment]
Sorry for that, fixed in https://github.com/secdev/scapy/pull/915

**Comment by gpotter2** [comment]
Fixed in the latest dev version. Please update
