### ISSUE TITLE
Automaton.graph broken on Linux

### ISSUE THREAD

**Issue by commial** [secdev/scapy#922]
Hello,

The `do_graph` function in [scapy.utils](https://github.com/secdev/scapy/blob/master/scapy/utils.py#L467) on `!WINDOWS` will act as:
```Python
...
            target = "| %s" % conf.prog.display
...
    if isinstance(target, str):
        target = open(os.path.abspath(target), "wb")
```

As a result, asking for the graph of an Automaton will lead to the creation of a file named `| display` and no graph displayed.

To reproduce:
```Python
from scapy.all import *

class Test(Automaton):

    @ATMT.state(initial=True)
    def xxx(self):
        pass

Test.graph()
```
This will creates the file mentioned above.

A bisect leads to the commit 1fd5116590e760b8cd43ce41b8aaedec25251bcb which indeed removes the call to `os.popen2`.
This is not a PR because I'm not sure on how to fix this bug without breaking the behavior on others OS...

**Comment by gpotter2** [comment]
@commial
Hi, does #929 properly fixes it in your case ?
It's not creating a temp file, so it should be working good...

**Comment by commial** [comment]
Yes it works ;)
