### ISSUE TITLE
twisted.internet.ssl.CertificateOptions and inspect.getargspec are deprecated

### ISSUE THREAD

**Issue by songww** [secdev/scapy#933]
* python3.6/site-packages/scrapy/core/downloader/contextfactory.py:51: DeprecationWarning: Passing method to twisted.internet.ssl.CertificateOptions was deprecated in Twisted 17.1.0. Please use a combination of insecurelyLowerMinimumTo, raiseMinimumTo, and lowerMaximumSecurityTo instead, as Twisted will correctly configure the method.
* python3.6/site-packages/scrapy/utils/python.py:201: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  func_args, _, _, _ = inspect.getargspec(func)

**Comment by p-l-** [comment]
Please read the "CONTRIBUTING.md" file before opening issues.
