### ISSUE TITLE
DHCP - Option 55: DHCPRequestListField("request-list") commented out

### ISSUE THREAD

**Issue by hreidar** [secdev/scapy#934]
Hi, I noticed that DHCP option 55 in the DHCP layer is commented out. Is there another way for me to ask a DHCP server for specific options?

**Comment by gpotter2** [comment]
Hi,
https://github.com/secdev/scapy/pull/939 should add the missing option :)
Have a good week

**Comment by hreidar** [comment]
Excellent work, I have tried your fix and it works perfectly, thanks.
