### ISSUE TITLE
Doc for scapy layer

### ISSUE THREAD

**Issue by rainmanwy** [secdev/scapy#94]
Hi,

I have created a tool to generate doc(html format) for layers. For me, i think it is useful when i want to create packets.

here is code:
[layer doc generator

](https://github.com/rainmanwy/robotframework-ScapyLibrary/blob/master/src/ScapyLibrary/layerDoc.py)

I am not sure whether there is such kind of tool of doc for layers already. And also not sure whether my understanding about layers and fields is correct.

Could you help to check this? I have attached the generated doc.

Thank you very much!
[scapy_layer.zip](https://github.com/secdev/scapy/files/181896/scapy_layer.zip)

**Comment by p-l-** [comment]
Hi,

Scapy comes with a handy function `ls()` you might want to check out!

Thanks,

Pierre
