### ISSUE TITLE
Explicitly Marking Package as Python 2 inside setup.py File?

### ISSUE THREAD

**Issue by ajstein** [secdev/scapy#95]
Original recommendation came from the [scapy3k](https://github.com/phaethon/scapy.git) developer in the original [BB issue tracker](https://bitbucket.org/secdev/scapy/issues/5129/linking-to-from-scapy3k).

If you are interest, as I too have fallen victim to this like [other](https://github.com/secdev/scapy/issues/88) [users](https://github.com/secdev/scapy/issues/83) here and other projects elsewhere, implement a setup.py check that will throw an explicit error when attempting to install scapy in a Python 3 environment.

I know it is made clear in the documentation file, but I like other somtimes install libraries and utilities from the pip utility before consulting documentation, so maybe this will be helpful, albeit in a very minimal way.

**Comment by p-l-** [comment]
I think the documentation is enough for that.

**Comment by ajstein** [comment]
OK then.
