### ISSUE TITLE
sniff does not work inside a script, however, works alright when used from the interact

### ISSUE THREAD

**Issue by gopchandani** [secdev/scapy#953]
So, I used the exact same sniff command here under the exact same scenario, expecting three packets (which are visible in the tcpdump output) when debugging a program:

`sniff(iface='h1-eth0', prn=lambda x:x.show(), count=3, filter="ether src 00:04:00:00:00:00")`

It works perfectly fine when used in the interact() environment, i.e. from the command line 'scapy'. but when used inside a script, it doesn't. It simply blocks and when the script is terminated, zero packets are seen. 

Any ideas what might be up?

**Comment by gpotter2** [comment]
Hi,
a few questions before we can help you out:
- what OS are you using ?
- what is your scapy version ? If not using the latest **dev** version, please try it here https://github.com/secdev/scapy/archive/master.zip
- what python version are you using ?

Thanks !

**Comment by guedou** [comment]
Closing due to to reply.
