### ISSUE TITLE
from scapy.all import * ImportError: No module named all in scapy 2.3.3

### ISSUE THREAD

**Issue by mimta** [secdev/scapy#955]
Hi
I cant import

>  scapy.all import * 

I am using scapy 2.3.3-dev and python 2.7.12

Also it funny but I cant even use rdpcap or PcapReader class!!

Any help?

**Comment by guedou** [comment]
Could you give us more information (OS, example output, ...)? Thanks.

Also, it might be a typo in your issue but make sure that you type `from scapy.all import *`.

**Comment by mimta** [comment]
hi

`/usr/bin/python2.7 /home/nopo/PycharmProjects/work/scapy.py
Traceback (most recent call last):
  File "/home/nopo/PycharmProjects/work/scapy.py", line 4, in <module>
    from scapy.all import *
  File "/home/nopo/PycharmProjects/work/scapy.py", line 4, in <module>
    from scapy.all import *
ImportError: No module named all`

Ubuntu and using pycharm. also I tried to imported directly  by

> python -c 'from scapy.all import VERSION; print VERSION'

but I got this error

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scapy.py", line 4, in <module>
    from scapy.all import *
ImportError: No module named all
`

**Comment by guedou** [comment]
What is scapy.py ?

**Comment by mimta** [comment]
its my code file. I named it scapy,

**Comment by mimta** [comment]
ok! I changed my file name and it seems that works fine!

Thanks
