### ISSUE TITLE
count number of IPv6 extension headers

### ISSUE THREAD

**Issue by mimta** [secdev/scapy#956]
Hi Guys,

I am trying to get number of IPv6 extension headers in a packet.

For example I have a packet with 20 Destination Option header. how can I count it?!

Thanks

**Comment by avonar** [comment]
can you show the packet?

**Comment by mimta** [comment]
> Ether / fd17:625c:f037:2:3dd0:9f30:8dd9:654 > fd17:625c:f037:2:6489:cb90:54b2:548 (60) / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / IPv6ExtHdrDestOpt / Raw

**Comment by avonar** [comment]
maybe this will be useful for you
`import re
print len(re.findall('IPv6ExtHdrDestOpt', packet.summary()))`

**Comment by guedou** [comment]
There is no easy solution but you can build on the following example:
```
In [16]: p = IPv6()/IPv6ExtHdrFragment()/IPv6ExtHdrRouting()/ICMPv6EchoRequest()

In [17]: tmp = p.copy()

In [18]: while tmp:
    print issubclass(type(tmp), _IPv6ExtHdr); tmp = tmp.payload
   ....:     
False
True
True
False
```
