### ISSUE TITLE
IPv6 regex ?

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#960]
@guedou @p-l- Is this legit ?
`https://github.com/phaethon/scapy/pull/218`
Are we supposed to support such things ?

**Comment by guedou** [comment]
`fe80::1/64` is not a valid network address, however it is a valid IPv6 address. We could support this form, but `Net6()` should not return more than one address in this case (i.e. the patch is incorrect).

**Comment by guedou** [comment]
Looks ok to me:
```
[ip6 for ip6 in Net6("fe80::1/120")]
```
