### ISSUE TITLE
micropython

### ISSUE THREAD

**Issue by PGtips240** [secdev/scapy#964]
Hello,

I would like to use scapy with micropython on an esp8266.
Has anyone done this and if so could you let me know how to install it.

Many Thanks.

**Comment by guedou** [comment]
I have no idea. If you have any success, please report it to us !

**Comment by ikersl** [comment]
I also want to do that.

**Comment by polybassa** [comment]
```
MicroPython implements Python 3.4 and some select features of Python 3.5 and above. The sections below describe the current status of these features.
``` 
from https://docs.micropython.org/en/latest/genrst/index.html

I would love to see scapy on micropython, however, I doubt that it is possible because of the feature set implemented on micropython
