### ISSUE TITLE
Travis: builds failing on new OSX distros 

### ISSUE THREAD

**Issue by gpotter2** [secdev/scapy#967]
I've asked why, here's the answer:

https://github.com/travis-ci/travis-ci/issues/8829

We need to add pip setup to the install.sh, or find another way of installing the packages

**Comment by guedou** [comment]
The last answer indicates that an easy workaround is to change the ‘osx_image’. It could be a good short term fix.

**Comment by guedou** [comment]
#970 provided a temporary fix. A long term one must be implemented as described in the previously link travis issue.

**Comment by guedou** [comment]
#1106 provides a good way to fix this issue. 

Closing as everything works OK now.
