### ISSUE TITLE
Sniff function Is not Functioning on OS X

### ISSUE THREAD

**Issue by Naqu6** [secdev/scapy#97]
Hello,
I was trying to use Scapy's sniffing, and it was not functioning.
In pcapnet, there is a variable that is Null that the program assumes is Non-Null.
`>>> sniff(iface="en0")
WARNING: fileno: pcapy API does not permit to get capure file descriptor. Bugs ahead! Press Enter to trigger packet reading
WARNING: fileno: pcapy API does not permit to get capure file descriptor. Bugs ahead! Press Enter to trigger packet reading

WARNING: more fileno: pcapy API does not permit to get capure file descriptor. Bugs ahead! Press Enter to trigger packet reading
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/scapy/sendrecv.py", line 586, in sniff
    p = s.recv(MTU)
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 145, in recv
    pkt = self.ins.next()
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 92, in next
    s,us = h.getts()
AttributeError: 'NoneType' object has no attribute 'gets'`
Thanks in advance!

**Comment by Naqu6** [comment]
Sorry about this, it was a dependency issue.

**Comment by p-l-** [comment]
@Naqu6 thanks anyway. Could you add a comment explaining how you solved the problem, in case someone else with the same problem finds this ticket?

**Comment by Naqu6** [comment]
Got it.
In a bash shell, i ran:
sudo pip install pypcap
Instead of sudo pip install pcap.
