### ISSUE TITLE
Very limited documentation as a Python module

### ISSUE THREAD

**Issue by cothurn** [secdev/scapy#974]
As the title says, it is hard to find documentation for Scapy as a library, i.e. what each class/function does and what argument(s) does it take. The current documentation site provides very limited information.

**Comment by guedou** [comment]
While Scapy documentation has never been its best feature, your message is far from being helpful!

Instead of opening an issue, please consider contributing to the project by sending a pull-request that address your needs. We will do our best to review it quickly to improve the project.
