### ISSUE TITLE
Question: is it possible to generate Ethernet Pause frames

### ISSUE THREAD

**Issue by koorij** [secdev/scapy#976]
Hi, 

Is it possible to generate ethernet pause frames using this tool. 

in that case, can you please share some sample code for the same.

Regards,
Saravanankoori J

**Comment by stryngs** [comment]
@koorij Do you have an example PCAP?  If so, I will help you to reverse it and do it via Scapy.

**Comment by speakinghedge** [comment]
I did this a while ago while playing with some switches. Gimme a second to clean it up so I can create a PR from it...

**Comment by ayesuraj** [comment]
I have tried to use this module. But i am not able to figure out how i can achieve my requirment.
all i want to do is, using sendp i want to send packets with few or all frames as pause frames. is it possible to do this?. 
my requirement is to check at the receiving end whether my nic card is able to process or discard the pass frames that are sent from sender machine(which is scapy machine). it can have any priority being set

Regards,
yesuraj ABRAHAM
