### ISSUE TITLE
inet_pton is broken for IPv6 when more than one run of zeros exists

### ISSUE THREAD

**Issue by andysouthwell2** [secdev/scapy#978]
See comments I've left in (closed) issue 502. I presume I need to open a new ticket given that one is closed now, for it to get noticed?

a=inet_pton(socket.AF_INET6, 'fe80::ff:0:0:1')
print(inet_ntop(socket.AF_INET6, a))

This prints fe80::ff::1 which is invalid.

The problem is the way that inet_ntop strips trailing zeros and reduces array elements down into groups of colons. Unfortunately it fails to ensure that it doesn't end up with multiple double-colon occurrences. The best solution would be to determine the position and length of the longest range of zeros beforehand, and only replace those.

Below is the fix I am using locally. I have tested it only with Python 2.7 - I have no idea whether it works for Python 3 etc. Also, there may well be a more elegant, more Python-esque (less complex) way to write the code - but I hope, at least, that it's of benefit.

Best Regards
Andy Southwell

def longest_zero_span(addr):
    """Determines the longest span of zeros in addr"""
    longestStart = -1
    longestEnd = -1
    currStart = -1
    currEnd = -1
    for i in range(0, len(addr)):
        if int(addr[i], 16) == 0:
            if currStart >= 0:
                currEnd = i
                if longestStart < 0:
                    longestStart = currStart
                    longestEnd = currEnd
                else:
                    if (currEnd - currStart) > (longestEnd - longestStart):
                        longestEnd = currEnd
            else:
                currStart = i
                currEnd = i
        else:
            currStart = -1
            currEnd = -1
    return longestStart, longestEnd
 
def inet_ntop(af, addr):
    """Convert an IP address from binary form into text represenation"""
    if af == socket.AF_INET:
        return socket.inet_ntoa(addr)
    elif af == socket.AF_INET6:
        # IPv6 addresses have 128bits (16 bytes)
        if len(addr) != 16:
            raise Exception("Illegal syntax for IP address")
        parts = []
        for left in [0, 2, 4, 6, 8, 10, 12, 14]:
            try: 
                value = struct.unpack("!H", addr[left:left+2])[0]
                hexstr = hex(value)[2:]
            except TypeError:
                raise Exception("Illegal syntax for IP address")
            strlow = hexstr.lower()
            if len(hexstr) > 1:
                parts.append(strlow.lstrip("0"))
            else:
                parts.append(strlow)
        zeroSpanStart, zeroSpanEnd = longest_zero_span(parts)
        result = ''
        for i in range(0, len(parts)):
            if i >= zeroSpanStart and i <= zeroSpanEnd:
                if len(result) == 0 or not result[-1] == ':':
                    result += '::'
                elif result[-1] == ':' and (len(result) < 2) or not (result[-2] == ':'):
                    result += ':'
            else:
                if (i > 0) and (not result[-1] == ':'):
                    result += ':'
                result += parts[i]
                if (not i == (len(parts) - 1)) and not (result[-1] == ':'):
                    result += ':'
        return result

**Comment by gpotter2** [comment]
Please check that you are using the latest **dev** version: https://github.com/secdev/scapy/archive/master.zip
I cannot reproduce (on windows 10):
![image](https://user-images.githubusercontent.com/10530980/33897994-4d8f3aae-df67-11e7-855d-3364dc33a885.png)

**Comment by andysouthwell2** [comment]
Hi, you are right - I've tried that and it works fine. Must have been fixed already then (I was using 2.3.3 that came with our Python 2.7.x install). ok - thanks for having a look. :)

Marking as closed.

Best Regards
Andy
