### ISSUE TITLE
Question to TFTP Handling

### ISSUE THREAD

**Issue by lidllohntsich** [secdev/scapy#979]
Scapy is not able to dissect a TFTP pcap trace, whereas Wireshark can decode it.

A normal TFTP session starts with a TFTP_RRQ sent to port 69 of the TFTP server. (A TFTP server always listens on port 69). The TFTP server assigns a new port for the sessions and answers with a TFTP_DATA back to the client. The rest of the sessions is handled via this new server port.

Looking now at /scapy/layers/tftp.py I found the following bindings:
bind_layers(UDP, TFTP, dport=69)
bind_layers(TFTP, TFTP_RRQ, op=1)
bind_layers(TFTP, TFTP_WRQ, op=2)
bind_layers(TFTP, TFTP_DATA, op=3)
......

The first binding concerning dport=69 leads to the following result:
As the first TFTP_RRQ ends up on port 69, this message can be decoded.
As the TFTP server switches to a different port after the TFTP_RRQ, all other TFTP messages
(i.e. TFTP_DATA, TFTP_ACK....) will not have a proper binding any longer. All layers above
UDP will be shown as RAW.

Is this really the wanted behaviour?

Changing the first binding to:
bind_layers(UDP, TFTP) should solve the problem.

Comments are welcome.

**Comment by gpotter2** [comment]
`bind_layers(UDP, TFTP)` would mean that all layers following a UDP layer are TFTP ones.
This is definatly not the wanted behavior.

Sometimes, when scapy does not know which layer to use, it looks at the port, which in many cases is very significant. If your server is using custom implementations, ports or whatever, those ports will obviously change.

This is why it's intended that users add themselves 
`bind_layers(UDP, TFTP, dport=*X*)`
with whatever port they need, to their programs.

I hope I was able to answer your question :-)

Have a good week

**Comment by p-l-** [comment]
Please reopen if @gpotter2's comment are not enough.
