### ISSUE TITLE
Wireshark() - TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by andysouthwell2** [secdev/scapy#981]
(using latest dev-master under Windows 7).

It transpires that this is because (unlike the older 2.3.3 version I was previously using that shipped with our Python 2.7.x), it requires conf.prog.wireshark to be set to the path of the Wireshark exe.

Well, that's fair enough, but I feel scapy ought to be checking it's not None and throwing a more helpful error message please. Once I fixed that, wireshark() worked fine.

Thanks. :)

Regards
Andy

**Comment by gpotter2** [comment]
To be precise, on windows wireshark will be auto-detected if you have added its folder to your PATH var :)

**Comment by andysouthwell2** [comment]
OK, good to know - thanks. Still, a more helpful message would be an improvement I think.
