### ISSUE TITLE
Authentication failing with ESP

### ISSUE THREAD

**Issue by tejashkasundra** [secdev/scapy#983]
Hi,  
I want to generate encrypted packets using ESP. I tried using ESP, packet is getting encrypted but somehow authentication is failing so packet getting malformed. Can anyone please help me to get this done?  
My code looks like as below,  

b = IP(src="192.168.9.141",dst="172.17.30.113",flags=0x00)/TCP(dport=12,sport=1025)/Raw('testdata') b = IP(bytes(b)) 
sa = SecurityAssociation(ESP, spi = 0xdeadbeef, crypt_algo = 'AES-CBC', crypt_key = 'ced36ca65aaaedb2e9a7e73b4aa9039e', auth_algo = 'HMAC-SHA1-96', auth_key = '0xb50b05e64f46c4fb86eeab81590623c65b2913dd') 
e = sa.encrypt(b) k=Dot1Q(vlan=3,type=0x0800) f=Ether(src="a0:36:9f:bb:bd:f3",dst="a0:36:9f:bc:db:f4",type=0x8100) 
sendp(f/k/e)

**Comment by guedou** [comment]
Can you be more specific and give us the Scapy version, Python version, python-cryptography version and the OS that you are using ?

**Comment by tejashkasundra** [comment]
Please find below information,
Python 2.7
Scapy - 2.3.1

From above example, when I try to use crypt_key = 0xced36ca65aaaedb2e9a7e73b4aa9039e although it is valid key for AES-CBC, scapy gives error as below,
TypeError: invalid key size 34, must be (16, 24, 32)

Let me know for any other query.

**Comment by tejashkasundra** [comment]
Using OS Ubuntu

**Comment by guedou** [comment]
Did you try writing the key on another format ? The error message is quite explicit: your key is 2 bytes too long ...

**Comment by exploide** [comment]
The examples you gave show a very inconsistent usage of the keys. In your opening post you say `crypt_key = 'ced36ca65aaaedb2e9a7e73b4aa9039e'` (without 0x prefix) but then `auth_key = '0xb50b05e64f46c4fb86eeab81590623c65b2913dd'` (with 0x prefix) and finally in your subsequent post `crypt_key = 0xced36ca65aaaedb2e9a7e73b4aa9039e` (without quotation marks, passing an integer).

Maybe the error comes from the used `0x` within quotation marks. Additionally I guess it will process the whole string as it were bytes. So if your hex string represents your key, maybe you need to convert it to a byte array first.
