### ISSUE TITLE
Add possibility to escape from sniff() function

### ISSUE THREAD

**Issue by zyrikby** [secdev/scapy#984]
Currently, there is no possibility to escape from sniff() function. This is sometimes required if you run this function is a separate process and check externally if you need to finish this process.

It would be great to add something like this to the sniff() method https://github.com/secdev/scapy/blob/master/scapy/sendrecv.py:

```
def sniff(count=0, store=True, offline=None, prn=None, lfilter=None,
          L2socket=None, timeout=None, opened_socket=None,
          stop_filter=None, iface=None, stop_callback=None, *arg, **karg)
    ...
    try:
        while sniff_sockets:
            if stop_callback and stop_callback():
                break
```

**Comment by gpotter2** [comment]
@p-l- Duplicated https://github.com/secdev/scapy/issues/989
