### ISSUE TITLE
Losing packets in win10 even using L2ListenTcpdump

### ISSUE THREAD

**Issue by taoxinyi** [secdev/scapy#999]
I use WinDump, but some packets are missing when windump drops nothing. 

    windump.exe: listening on \Device\NPF_{8B70E329-3331-4F62-A25F-34045B1AFC33}
    7975 packets captured
    12513 packets received by filter
    0 packets dropped by kernel
    <Sniffed: TCP:7939 UDP:0 ICMP:0 Other:0>

In this example, WinDump captures all while scapy actually loses some.

**Comment by gpotter2** [comment]
Yes you can,

You just need to install the windump version matching with your (win/n)pcap version.

It also requires windump.exe to be in the PATH.

**Comment by taoxinyi** [comment]
Yes, this is my previous question that I edited. My question now is that scapy actually lose packets using Windump. Windump captures 7975 packets while scapy returns only 7939.

**Comment by guedou** [comment]
I replied on gitter.

Please don't harass us on different mediums and keep in mind that is an issue tracker not a forum! You are wasting our time.

**Comment by taoxinyi** [comment]
@guedou  Sorry, I previously thought that others on gitter may have solutions.

**Comment by chalilb** [comment]
hello, Is the question solved?
I have the same trouble。

**Comment by gpotter2** [comment]
Use a BPF filter if you're losing too much packets with Scapy. There's not much we can do.
